### ISSUE TITLE
Animations loading OK but not playing

### ISSUE THREAD

**Issue by edbarry1987** [airbnb/lottie-ios#1000]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 
Animations to play when calling play int he ViewDidAppear function.

## Actual Behavior
Previously animations were playing fine, after updating the version 3.1.2 they are not playing. 

## Code Example
`let animationView = AnimationView(name: "TRP")

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
        animationView.frame = self.animationContainer.bounds
        animationView.contentMode = UIViewContentMode.scaleAspectFit
        animationView.loopMode = LottieLoopMode.loop
        
        self.animationContainer.addSubview(animationView)
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(true)
        animationView.play(completion: { (finished) in
            print("playing")
        })
    }`
## Animation JSON

[TRP.json.zip](https://github.com/airbnb/lottie-ios/files/3461171/TRP.json.zip)

**Comment by JorgeSainz** [comment]
I have the same problem.

I exported an AfterEffects Animation in json format. I could preview it on Bodymovin plugin, but when i import it on my Swift file it didnt appear. if i change the animation name by another that currently works, it show the animation so its not a coding problem.

I uploaded to lottiefiles.com and the animation appears perfectly on the web player, but when it comes to preview it with their mobile app, it doesnt appear, so im confused if its a bug that certains animations didnt work on mobile and do it on web

**Comment by edbarry1987** [comment]
Lottiefiles.com works perfectly for me too. All images are displayed on iOS app but just won't play the animation.

**Comment by agwolff** [comment]
Same issue here.

**Comment by edbarry1987** [comment]
I have done a bit of testing with this last night, I have my view on a page view controller. When I swipe to the next page the animation doesn’t play, but if I swipe the page slowly but not move onto the next page... the animation starts to play!

Weirds but must be an error somewhere for when the page is first displayed on screen.

**Comment by agwolff** [comment]
I was having this issue occurring when entering the viewController for the first time. I would load the AnimationView and then use the play() method on viewDidAppear and nothing would happen. Then If I pushed to another VC and then popped back, the animation would play. My guess is that somehow my JSON file was still being loaded by the AnimationView init when I called the play() method thus, not playing on the first attempt. 

I was able to fix this by calling the play() method within the closure of the AnimationView init, so it would start playing once the view was loaded completely. Example below, might be worth a try:

    public class LottieTest: UIViewController {
    var lottie = AnimationView()

    override func viewDidLoad() {
        super.viewDidLoad()
        self.lottie = AnimationView(url: "lottie URL", closure: { [weak self] _ in
            guard let self = self else { return }
            self.lottie.play()
        })
        
        self.lottie.contentMode = .scaleAspectFill
        self.lottie.loopMode = .loop
        
        self.view.addSubview(self.lottie)
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.lottie.play()
    }   
    }

**Comment by tachcardapp** [comment]
These animation not working on iOS too. (I think that happens with circle animations)
https://lottiefiles.com/7726-clock
https://lottiefiles.com/7236-clock-seamless-animation

**Comment by OlehHrechyn** [comment]
These animations not working on iOS too. (I think that happens with circle animations)
https://lottiefiles.com/7726-clock
https://lottiefiles.com/7236-clock-seamless-animation

**Comment by lorenc-tomasz** [comment]
The same issue there. Animations play OK on 2.x, not play on 3.x :( Please fix it!

**Comment by WestonHanners-Earnin** [comment]
adding my voice here as it is effecting me as well.

**Comment by buba447** [comment]
This issue seems to have become a catch all for any animation problem. Each animation issue needs to be debugged on its own, as they could all be unique issues. Im closing this to reduce noise. Please everyone open a unique issue for each animation problem with a detailed description of the issue.

**Comment by nokia6290** [comment]
Issue still relevant in 2021 - 

using same lottie and in one screen it plays while in another it does not.

same identical lottie.

**Comment by kartuzovmax** [comment]
Experiencing same issue, where some animations will play on the web, but won't play in my app or even LottieFiles iOS app.

**Comment by jimmy510s** [comment]
Hi,

I had the same. I was trying to display an animation that a friend of mine gave me and in iOS it wasn't working when other animations did. Also the animation that didn't work on iOS was working correctly in the web previewer.  So we discovered that if the animation has a mask over a shape it can't load. Another case that we had the same mask over a solid colour  it worked like a charm.

We are using
- After effects + bodymovin plugin
- iOS Lottie version 3.4.0

i have included a working and not working lottie json file

[examples.zip](https://github.com/airbnb/lottie-ios/files/9508448/examples.zip)

**Comment by ozonetech** [comment]
This is 2023 am still experiencing the same fck issue

**Comment by tiagobbraga** [comment]
The same!
