### ISSUE TITLE
Add support for video Export usage 

### ISSUE THREAD

**Issue by tawhidkuet04** [airbnb/lottie-ios#1001]
I can export animation with video but the problem is animation speed is variable in different device while exporting .the animation is actually not rendered correctly depending on
device etc.The animation timespace is not linked to the video timespace . Any suggestion for this issue ?

**Comment by damikdk** [comment]
I got the same issue. The faster device the slower animation.

In my case animation looks perfect on iPhone 6 with ``animationView.respectAnimationFrameRate = true``. Any other device (XR, iPad Pro, iPhone 7/8) plays it much slower.

According [this](https://stackoverflow.com/q/30034202/7996650) question (4 years ago, btw), I decide to hardcode constants for devices for now :(

**Comment by tawhidkuet04** [comment]
@damikdk Thanks for the reply . How to set the hardcore constants for each device , I mean what constants i need to add to match the video timing ?

**Comment by damikdk** [comment]
I talking about this stupid and bad way. I will rewrite it in weeks and hopefully we will get help by then:

```
animationView.respectAnimationFrameRate = true
animationView.loopMode = .loop

var deviceFactor: Double = 1

switch UIDevice().type {
case .iPhone6, .iPhone7:
    deviceFactor = 0.4
case .iPadPro9_7:
    deviceFactor = 0.7
case .iPhoneXR:
    deviceFactor = 1
default:
    break
}
               
animationLayer.speed = Float((60 / animation.framerate) * deviceFactor)
```

I just found these values manually, they're inaccurate. And it is not 60 fps Lottie animation in output video, there is framedrops.

SOMEBODY, HELP US! Look at what I've done already!

**Comment by tawhidkuet04** [comment]
I am using version 2.5.3 and project is in obejctive C . Can't find this functions .  which version are you using ?

**Comment by damikdk** [comment]
@tawhidkuet04 I use last one and Swift, sorry. It doesn't matter, because even my awful code above can't save us. Because current export depends on both device AND animation.

It will be super useful if somebody point us to some CoreAnimation primitive that we can use for export with ``AVVideoCompositionCoreAnimationTool`` and ``AVAssetExportSession``. Doesn't matter public or private, we can fork and get it.

This setup can export animation, but I got the same problems @spykr [describe](https://github.com/airbnb/lottie-ios/issues/30#issuecomment-386158548) in #30
 
```
let animationView = AnimationView()
animationView.animation = Animation()
let animationLayer = animationView.layer

animationLayer.repeatCount = .greatestFiniteMagnitude
animationLayer.beginTime = AVCoreAnimationBeginTimeAtZero

animationLayer.frame = CGRect(x:0, y:0, width: 50, height: 50)
parentLayer.addSublayer(animationLayer)

animationView.play()
```

But animation **renders** in result video, albeit wrong. So there is some logic above native primitives. I just started digging, but help is super welcome.

**Comment by buba447** [comment]
Adding to feature requests

**Comment by MikhailZimin** [comment]
Hello there.
I faced with that problem. Has anyone solved it? Or can @buba447 tell a deadline for when it will be implemented?

**Comment by olivierlesnicki** [comment]
+1

**Comment by suxinde2009** [comment]
Ran into the same problem.

**Comment by namdhis** [comment]
Please help us.

**Comment by deven-youpi** [comment]
Is this problem solved yet?

**Comment by calda** [comment]
Just curious, why are folks interested in exporting Lottie animations to video files?

**Comment by calda** [comment]
Thanks all for the suggestion. We don't plan on adding support for video exports at this time. This seems like something that could be made available as a separate library on top of this one.
