### ISSUE TITLE
SwiftPM support requires iOS 12

### ISSUE THREAD

**Issue by maniramezan** [airbnb/lottie-ios#1003]
Hi, 

I might've missed it, but I couldn't find any place in the release notes declaring the minimum required iOS version needs to be 12 and the podspec has iOS 9 as deployment target. Was wondering if iOS 12 for SwiftPM support was intensional.

Thanks

**Comment by danielsaidi** [comment]
We're wondering the same. We're migrating from CocoaPods to SPM and would love to use the latest version of this library, but we're targeting iOS 11.

**Comment by RamblinWreck77** [comment]
@buba447 Would it be possible to push a hotfix correcting the Package.swift?

Should just be:

```
platforms: [.iOS(.v12)],
```

to

```
platforms: [.iOS(.v11)],
```

**Comment by maniramezan** [comment]
As I'm seeing in master, it's already fixed in master Lottie, [Package.swift](https://github.com/airbnb/lottie-ios/blob/master/Package.swift). Going to close this.
