### ISSUE TITLE
lottie-ios 3.1.1 haven't been pushed to the npm registry

### ISSUE THREAD

**Issue by LJNGDAHL** [airbnb/lottie-ios#1004]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0.3, together with `lottie-react-native`. In this version, I have some performance issues that I am hoping have been solved in recent various bug fixes. Before upgrading to 3.0.3, `lottie-react-native` was using `lottie-ios 2.5.0`, which did not have these performance issues.

## Expected Behavior 
Same or improved performance as previous versions of Lottie when running animations.

**Comment by janpe** [comment]
@buba447 I saw that you have resolved such issues before in the repo. Anything on this? Why no pushes to the registry after `3.0.3`?

**Comment by bitcrumb** [comment]
I would also like to see the updates pushed through to the npm registry. Thanks!

**Comment by smacgregor** [comment]
At the risk of being a me three, any chance we can get 3.1.1 published to npm?

**Comment by janpe** [comment]
Seems that there are new a couple of new versions released some days ago. 👍
