### ISSUE TITLE
DarkMode (UITraitCollection) support

### ISSUE THREAD

**Issue by maurovc** [airbnb/lottie-ios#1005]
## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [X] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift
- [] Objective-C

## Suggestion

Is there any idea on supporting UITraitCollection changes for dark mode?

Thanks!

**Comment by buba447** [comment]
Im not sure what lottie what the default expectation for a lottie animation in dark view would be.
It seems like it would vary depending on the animation loaded. It would be very easy to change the colors of your animation, or change the animation all together, by value providers (read more here http://airbnb.io/lottie/#/ios?id=value-providers). You could write a wrapper around a lottie view and change your animation however you'd like for the traits.
