### ISSUE TITLE
Render Issues on iOS

### ISSUE THREAD

**Issue by alsegra** [airbnb/lottie-ios#1011]
Hey guys, I'm having problems rendering my character's feet in my animation. As you can see in the folder I attached, the feet are being distorted/stretched to the sides. It kinda works on web and Android but it's not being rendered correctly on iOS (it has some minor visual mistakes too but not even comparable to the visual mistakes on iOS).
I've tried all kind of different stuff, made a lot of tests but I really don't know what else to check, I hope you can help me, please.
My Lottie version is 3.1.2 and my bodymovin version is 5.5.7. I attached the AE project file + 2 videos of the expected version and iOs error version.

[Test ninja.zip](https://github.com/airbnb/lottie-ios/files/3530459/Test.ninja.zip)

Many thanks!

**Comment by alsegra** [comment]
Well, it seems nobody is answering in this forum, but if you arrived here looking for a solution let me tell you what I did:

In the end, I didn't find a solution but I found the root of the problem so I could avoid it. 
Apparently, Lottie iOS has some problems/bug rendering 3 consecutive points in a single stroke (like the ones I did for the legs), so what I did was delete the last point that corresponds to the edge of the foot, leaving only 2 points to create the shape of the leg (hip and ankle), and creating the shape of the foot as a rectangle with rounded corners and keyframing the position by hand...it's a bit of a monkey work but it worked for me.

**Comment by calda** [comment]
Could you share a copy of the exported animation .json?
