### ISSUE TITLE
OC use CompatibleAnimation failed

### ISSUE THREAD

**Issue by muyuli** [airbnb/lottie-ios#1018]
CompatibleAnimation *animation = [[CompatibleAnimation alloc] initWithName:@"8795-beach-cabin" bundle:nil];

    CompatibleAnimationView *animationView = [[CompatibleAnimationView alloc] initWithFrame:self.view.frame];
    animationView.compatibleAnimation = animation;
//    animationView.frame = self.view.bounds;
//    animationView.loopAnimationCount = 10;
//    animationView.contentMode =  UIViewContentModeScaleAspectFill;
   
    animationView.backgroundColor = [UIColor redColor];
    [self.view addSubview:animationView];
    
    [animationView play];

**Comment by MuYuLi** [comment]
Does anyone know about it?
