### ISSUE TITLE
Can make animation.layers to Public？I need this layers.count and ip op. Swift can't access this layers property。Please.

### ISSUE THREAD

**Issue by xiaoqidevelopergithub** [airbnb/lottie-ios#1025]
## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [] iOS

## What Language are you in?
- [] Swift
- [] Objective-C

**Comment by buba447** [comment]
Theres no plan to make animation.layers public. It would require making most of the library classes public. 
My question is why? What do you need to do with animation.layers that you cant with the library?

**Comment by VVege** [comment]
> Theres no plan to make animation.layers public. It would require making most of the library classes public.
> My question is why? What do you need to do with animation.layers that you cant with the library?

I want to init Lottie in multi-thread，But UIView must be inited in Main thread。So，I need a layer like AnimationView。Lottie Kit didnt have this kind of Layer, I have to make by myself, but I cant event use AnimationContainer, this is the trouble
