### ISSUE TITLE
iOS Animation with included base64 images crash

### ISSUE THREAD

**Issue by Udjen747** [airbnb/lottie-ios#1027]
I have an issue using animation^ created with base64 images inside .json. 
Iam using latest 3.1.2 version^ and event in new empty project I have this. It crash with message `"Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan nan]"`
But when I try to open this animation in your "Example" project it works great!
[test.json.zip](https://github.com/airbnb/lottie-ios/files/3609645/test.json.zip)

**Comment by calda** [comment]
As you mentioned, the animation you shared renders correctly when I use it locally in our example project. This sounds potentially like an issue with UIKit / laying out the `AnimationView`. If you still need support, feel free to [start a discussion](https://github.com/airbnb/lottie-ios/discussions).
