### ISSUE TITLE
How to remove LOTAnimationView correctly and clean up animation data from memory? [macOS]

### ISSUE THREAD

**Issue by maxgribov** [airbnb/lottie-ios#103]
I'am try remove  `LOTAnimationView` calling it's `removeFromSuperview` method and get autolayout exeption for each sublayer (target macOS 10.12) :

> This application is modifying the autolayout engine from a background thread after the engine was accessed from the main thread. This can lead to engine corruption and weird crashes.
Stack:(
	0   CoreFoundation                      0x00007fffd3ad1e7b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffe86bccad objc_exception_throw + 48
	2   CoreFoundation                      0x00007fffd3b5099d +[NSException raise:format:] + 205
	3   Foundation                          0x00007fffd57087da _AssertAutolayoutOnAllowedThreadsOnly + 180
	4   Foundation                          0x00007fffd5497aff -[NSISEngine withBehaviors:performModifications:] + 31
	5   AppKit                              0x00007fffd155940e -[NSView(NSConstraintBasedLayout) _withAutomaticEngineOptimizationDisabled:] + 70
	6   AppKit                              0x00007fffd1558a1e -[NSView _setSuperview:] + 1029
	7   AppKit                              0x00007fffd155e609 -[NSView removeFromSuperview] + 447
	8   Lottie Test                         0x0000000100018f1e -[LOTAnimationView removeFromSuperview] + 78
	9   Lottie Test                         0x0000000100002870 __35-[ViewController buttonDidClicked:]_block_invoke + 80
	10  Lottie Test                         0x0000000100018c03 -[LOTAnimationView _callCompletionIfNecesarry] + 259
	11  Lottie Test                         0x0000000100018afa -[LOTAnimationView checkAnimationState] + 138
	12  Lottie Test                         0x00000001000038ac -[CADisplayLink tick] + 284
	13  Lottie Test                         0x000000010000350c displayLinkCallback + 76
	14  CoreVideo                           0x00007fffd5108006 _ZN13CVDisplayLink9performIOEP11CVTimeStamp + 248
	15  CoreVideo                           0x00007fffd5107b9a _ZN13CVDisplayLink11runIOThreadEv + 644
	16  libsystem_pthread.dylib             0x0000000100193c50 _pthread_body + 180
	17  libsystem_pthread.dylib             0x0000000100193b9c _pthread_body + 0
	18  libsystem_pthread.dylib             0x0000000100193385 thread_start + 13

Is there a correct way to remove `LOTAnimationView` without throwing exeptions?

Also all the animation data remain in the memory:
<img width="409" alt="screen shot 2017-02-18 at 06 14 55" src="https://cloud.githubusercontent.com/assets/6514571/23089846/aa2fbf32-f5a1-11e6-96d3-d0e4848baa42.png">
Is there a way to drop them?

**Comment by pawlowskialex** [comment]
Live objects in memory you see are part of `LOTAnimationCache`, and unrelated to the exception.

But regarding the exception, it seems to me you're trying to call `removeFromSuperview` on `LOTAnimationView` inside `playWithCompletion`.
That completion block is called on the same thread as display link timer, on iOS that's main thread, on macOS it's not.
If you call `removeFromSuperview` on the main thread it works fine.

I can fix it by dispatching completion to the main thread on macOS, and that's probably the right thing to do, to make the behavior consistent across platforms.

**Comment by maxgribov** [comment]
Thank you! On main thread everything works fine. And about the fact that to have the ability to drop the cache for the animation it makes sense to start a new issue?
