### ISSUE TITLE
Lottie SwiftUI Feature Request

### ISSUE THREAD

**Issue by robertpetras** [airbnb/lottie-ios#1033]
## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [X] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

**🙄 It would be nice if Lottie could support SwiftUI by default in the future.
👍 Is there any plan for it on the roadmap?
🙏 Thanks!**

## Which Version of Lottie are you using?

Lottie 3.1.3

## What Platform are you on? 

- [X] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift
- [] Objective-C

**Comment by Rapsssito** [comment]
Check out https://github.com/sponsors/buba447 for more info about Lottie iOS future. **Consider donating, if you can!**
