### ISSUE TITLE
Animation Json work in web but not in iOS SDK 3.1.3

### ISSUE THREAD

**Issue by yodesh87** [airbnb/lottie-ios#1038]
## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
 
## Which Version of Lottie are you using?

Lottie 3.1.3

## What Platform are you on? 
 - [] iOS

## What Language are you in?
- [] Swift
 
## Expected Behavior 
No display 

## Code Example
       if let animation = Animation.named("servishero_loading") {
            let animationView = AnimationView()
            animationView.frame = CGRect(x: 0, y: 0, width: 400, height: 400)
            animationView.center = self.view.center
            
            animationView.animation = animation
            animationView.contentMode = .scaleAspectFill
            animationView.animationSpeed = 0.5
            animationView.loopMode = .autoReverse
            
            view.addSubview(animationView)
            animationView.play()
}

**Comment by yodesh87** [comment]
[jsonzip.zip](https://github.com/airbnb/lottie-ios/files/3657588/jsonzip.zip)

json file

**Comment by alaadeego** [comment]
i have same issue

**Comment by buba447** [comment]
Fixed here https://github.com/airbnb/lottie-ios/pull/1039

**Comment by yodesh87** [comment]
Thanks it solved our problem
