### ISSUE TITLE
pod not search  lottie-ios?

### ISSUE THREAD

**Issue by sujiewen** [airbnb/lottie-ios#104]
SjwMacBook:~ Sjw$ pod search lottie-ios
[!] Unable to find a pod with name, author, summary, or description matching `lottie\-ios`
SjwMacBook:~ Sjw$ pod search lottie
[!] Unable to find a pod with name, author, summary, or description matching `lottie`
SjwMacBook:~ Sjw$ pod --version
1.2.0

**Comment by buba447** [comment]
This seems to be an issue with cocoa pods
Have you tried doing `pod repo update` ?
