### ISSUE TITLE
Add support for polygons

### ISSUE THREAD

**Issue by rdougan** [airbnb/lottie-ios#105]
I'm new to AE and Bodymovin, but it looks like polygons are not supported - at least polygons with Trim Paths.

I've attached a simple ae file along with an exported JSON.

I noticed @gpeal said "polygons will be supported soon" over at airbnb/lottie-android#120 but I'm not sure if that is just on Android.

[Archive.zip](https://github.com/airbnb/lottie-ios/files/786080/Archive.zip)

**Comment by therealsalih** [comment]
Hi @rdougan You're correct. polygons arent yet supported on iOS. @gpeal has begun testing out polygon support on Android as you can see here (https://github.com/airbnb/lottie-android/pull/115) but we're still working on the iOS side. 

In the meantime a very simple workaround is you can convert your polygon to a path and it will work fine. 

<img width="331" alt="screen shot 2017-02-19 at 11 44 13 am" src="https://cloud.githubusercontent.com/assets/5893643/23105752/e7c0100c-f698-11e6-876a-8dfd62794e28.png">

Just Ctrl click the polystar path and select "convert to bezier path"

**Comment by rdougan** [comment]
@therealsalih thank you! That solves my problem.

**Comment by javierHolvi** [comment]
How is the status here for supporting polygons @therealsalih ?

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
