### ISSUE TITLE
 Export from Bodymovin is blank - iOS App

### ISSUE THREAD

**Issue by mparrish91** [airbnb/lottie-ios#1053]
I am unable to view my animation in my iOS app. When I run the app the screen is completely blank where the animation should be.

I successfully exported from bodymovin and am accessing the json file in my Xcode project.  I am able to run other animations using Lottie in my XCode app so I know I am doing something  wrong with my animation.

I have attached the AEP file below.  
[Link](https://www.dropbox.com/s/vkj79zo6xyaddlk/Robot%20Animation.aep?dl=0)

[Images Link for the After Effects ](https://www.dropbox.com/sh/t6h2e3ohean3keh/AAAiNZagIYbuN3E7BSNXyNIla?dl=0)

Thank you

**Comment by buba447** [comment]
It looks like you are using nothing but images for your animation. Perhaps lottie isn't locating the images properly. Read more about image providers here and see if that helps. http://airbnb.io/lottie/#/ios?id=image-provider

**Comment by mparrish91** [comment]
Thank you Brandon.  I have tried using the image provider below.
It makes sense, however I am still having no luck.

Here is link to my AEP file 
Link to my converted Json file  [https://www.dropbox.com/s/rlxb56qtlq05rxs/elroi.json?dl=0](
link)

Link to my project.  [https://www.dropbox.com/s/fkz78jb9iab7i3b/ElroiAnimation.zip?dl=0](link)
