### ISSUE TITLE
Replace Image When App Running

### ISSUE THREAD

**Issue by batuhangoktepe** [airbnb/lottie-ios#1054]
I have an "images" folder and animation.json in my Xcode folders. I want to change the image named 1.png in the images folder but I can't. 
I have a downloaded image in my app from the internet. I want to change 1.png with that image.
Is this possible? 

I will be happy if you guys answer my question. 
Thank you so much.

**Comment by buba447** [comment]
Hello!

Yes you can fairly easily change out images and supply whatever images you want to a lottie view.
Lottie has a protocol `AnimationImageProvider` that can be used to supply the images. Its a fairly simply protocol that with a single function `imageForAsset(asset: ImageAsset) -> CGImage?`. This asks for the image for the asset.
If you create a class that conforms to the protocol and set it to the `imageProvider` property of the animation view you can supply images directly. You can even call `animationView.reloadImages()` to force an animation to reload its images.

Read more here http://airbnb.io/lottie/#/ios?id=image-provider

Cheers!

**Comment by tweakdoor** [comment]
what about andriod?
