### ISSUE TITLE
Precomp masking issue

### ISSUE THREAD

**Issue by btunick** [airbnb/lottie-ios#1070]
Using precomps in an animation, it does export the precomp information but doesn't mask objects that are going off the artboard in the precomp.

After effects version 16.1.3 (build 5)
bodymovin version 5.5.9

Is this a fixable issue or just something not supported yet?

**Comment by btunick** [comment]
guess I'll take that silence as a "we dont support this"? 

it'd just be cool to know before wasting my time trying to make a workaround

**Comment by btunick** [comment]
well in case anyone else with this issue stumbles across this,  here was my workaround: track matte each item that was overlapping the precomp artboard bounds to a solid the size of the precomp. hope that helps!

**Comment by buba447** [comment]
Hello! Sorry for the delay responding. Im fielding a lot of issues right now and Im pretty much the sole maintainer of this repo in my free time. So bear with me if Im a little slow to respond.

Yeah it's fair to say that if something goes off the precomp art board it wont mask. This can be fixed, but not simply. A refactor of the transform system needs to be done to fix this and also an issue with gradient scaling. I will add this bug to that task and bump its priority. Not sure when Ill get to it at the moment, but its on my radar.

Theres plenty of workarounds though, you could increase the bounds of the precomp, or your workaround seems to work too. Hope this helps!
Cheers.

**Comment by buba447** [comment]
Added to my todo

**Comment by buba447** [comment]
Should be fixed now!
https://github.com/airbnb/lottie-ios/pull/1087
