### ISSUE TITLE
Circular loading dots animation not displaying correctly on iOS, it does on lottiefiles web test

### ISSUE THREAD

**Issue by df1994** [airbnb/lottie-ios#1072]
## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.5

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 
https://gfycat.com/downrightjovialarachnid

## Actual Behavior
https://gfycat.com/playfulaffectionatealpaca

## Animation JSON
[animation_loading_dots.txt](https://github.com/airbnb/lottie-ios/files/3820941/animation_loading_dots.txt)

**Comment by buba447** [comment]
This animation has expressions which are currently [unsupported](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
