### ISSUE TITLE
Shadow animation Glitch

### ISSUE THREAD

**Issue by minaMagedNaeem** [airbnb/lottie-ios#1075]
## Check these before submitting:
- [✓] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [✓] This issue isn't related to another open issue

## This issue is a:
- [✓] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?
Lottie 3.1.5

## What Platform are you on? 

- [] MacOS
- [✓] iOS

## What Language are you in?
- [✓] Swift
- [] Objective-C

## Expected Behavior 
As in the animation in JSON file, there are three characters which are jumping and running from the left of the view to the right, each character has its own shadow.

## Actual Behavior
Shadows are rendered incorrectly ONLY on the first time, what happens is that on the first iteration/cycle of the animation, the burger character has a black part that appears when it touches the ground, also each character's shadow gets black on touching the ground. I have the animation on repeat, This issue happens on the first time only. After the first time, The animation runs just fine.

## Code Example
```
@IBOutlet weak var lottieAnimationView: AnimationView!

override func viewDidLoad() {
        super.viewDidLoad()
        
        lottieAnimationView.animation = Animation.named("scene")
        lottieAnimationView.contentMode = .scaleAspectFill
        lottieAnimationView.loopMode = .loop
}

override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)

        lottieAnimationView.play()
}
```

## Animation JSON

[scene.json.zip](https://github.com/airbnb/lottie-ios/files/3832454/scene.json.zip)

**Comment by lirazhad** [comment]
also happen on 3.1.5

**Comment by buba447** [comment]
Can you provide more information about your setup? Ive tried the animation and it runs fine over here. Hoping to narrow down the cause of the glitch.

**Comment by minaMagedNaeem** [comment]
Please mention what info you require and I'll provide it for you

**Comment by JamieWhite** [comment]
I think this is the same issue I have bumped into. I've gone through previous versions and this works fine in `3.0.5` and breaks in `3.0.6` onwards

**Comment by aswathr** [comment]
This occurs on 3.2.3. On iOS, there is the glitch that happens the first time, after that, the animation work fine. PFA sample project that describes the issue.
[testLottie.zip](https://github.com/airbnb/lottie-ios/files/7543493/testLottie.zip)

**Comment by calda** [comment]
Tested on master / 3.4.1 and it seems to animate correctly now
