### ISSUE TITLE
Unable to extend class AnimationView

### ISSUE THREAD

**Issue by shelbygold** [airbnb/lottie-ios#1077]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 

![Screen Shot 2019-11-14 at 2 53 43 PM](https://user-images.githubusercontent.com/48368538/68899290-992bf780-06ee-11ea-85dd-93a03d9ff0a9.png)

## Code Example
import Lottie
import UIKit

enum ImpactLoadingAnimationStyle {
    case app
    case white
}

class ImpactLoadingAnimationView: AnimationView{
    
    // MARK: - Properties
    
    // MARK: - Subviews
    
    
    // MARK: - Stored Constraints
    // (Store any constraints that might need to be changed or animated later)
   
    
    
    // MARK: - Initialization
    
    convenience init(style: ImpactLoadingAnimationStyle) {
        if let bundle = Bundle(identifier: "com.impact.ImpactSharedFramework") {
            switch style {
            case .app:
                switch ImpactSuite.currentApp {
                case .fortify:
                    self.init(name: "fortifySpinner", bundle: bundle)
                case .turn:
                    self.init(name: "turnSpinner", bundle: bundle)
                case .lift:
                     self.init(name: "liftSpinner", bundle: bundle)
                }
            case .white:
                self.init(name: "loadingSpinnerWhite", bundle: bundle)
            }
        } else {
            self.init(frame: .zero)
        }
        
        configureSubviews()
        configureTesting()
        configureLayout()
    }
    
    /// Set view/subviews appearances
    fileprivate func configureSubviews() {
        self.loopMode = .loop
        //RunLoop = true
        //loopAnimation = true
    }
    
    /// Set AccessibilityIdentifiers for view/subviews
    fileprivate func configureTesting() {
        accessibilityIdentifier = "ImpactLoadingAnimationView"
    }
    
    /// Add subviews, set layoutMargins, initialize stored constraints, set layout priorities, activate constraints
    fileprivate func configureLayout() {
        
        // Activate NSLayoutAnchors within this closure
        NSLayoutConstraint.activate([
            
            ])
    }
    
    public func startAnimation() {
        alpha = 1
        
        play()
    }
    
    public func stopAnimation() {
        alpha = 0
        stop()
    }
}

## Animation JSON

I have been using LOTAnimationView for several years now. I was finally forced to update some things but now LOTAnimationView doesn't exist. And AnimationView doesn't allow me to us it like LOTAnimation used to. Is there anyway you can change AnimationView from final to a inheritable class? This would help me from having to recode this whole animation. 

Thanks for taking the time to look at my issue.

**Comment by Rapsssito** [comment]
Submit your pull request removing `final` from the class and referencing this issue. I added `final` to all classes to improve performance. However, I don't think `AnimationView` being final will affect the performance much.

**Comment by shelbygold** [comment]
Thank you!

**Comment by Rapsssito** [comment]
You can follow this tutorial: https://gist.github.com/MarcDiethelm/7303312

**Comment by buba447** [comment]
Instead of subclassing it is suggested to wrap animation view. Subclassing can lead to errors with the animation view's lifecycle and animation.

**Comment by shelbygold** [comment]
Can you explain more about what you mean by wrap animation view?
