### ISSUE TITLE
JSON file with the same names but in different bundles are parsed to the same animation

### ISSUE THREAD

**Issue by jqoo** [airbnb/lottie-ios#1083]
## Check these before submitting:

- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)

- [] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 2.5.3

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [] Swift
- [x] Objective-C

## Code Example
`

+ (nullable instancetype)animationNamed:(nonnull NSString *)animationName inBundle:(nonnull NSBundle *)bundle {
  NSArray *components = [animationName componentsSeparatedByString:@"."];
  animationName = components.firstObject;
  
  // find cache only by animationName, but may be in different bundles
  LOTComposition *comp = [[LOTAnimationCache sharedCache] animationForKey:animationName];
  if (comp) {
    return comp;
  }
  // ...
}

`

**Comment by buba447** [comment]
Yeah this is a bug with how the cache is storing cached animations. It is not creating a unique name with the bundle.

**Comment by fmartinez318** [comment]
Is this still an issue? I am having something similar happen to me. Would clearing LRUAnimationCache work? I am unable to do this using the current Objective-C wrapper.

**Comment by calda** [comment]
This should be fixed now, because we use the bundle path as part of the cache key: https://github.com/airbnb/lottie-ios/blob/50fddd3a84e1adaf17dce5967217787b303b0030/Sources/Public/Animation/LottieAnimationHelpers.swift#L49
