### ISSUE TITLE
Layers not rendered properly on iOS with latest After Effects renditions

### ISSUE THREAD

**Issue by WJJongkind** [airbnb/lottie-ios#1085]
In a nutshell: On Android and Web an animation with snow is layered correctly behind the green layer and visible through the window. However, on iOS the snow falls in front of the green layer which is wrong. This bug also occurs on the iOS Lottiefiles preview app. As mentioned, on Android/web it works just fine.

## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)

## Which Version of Lottie are you using?
Lottie 3.1.5

## What Platform are you on? 
All iOS versions, macOS 10.14.6
- [X] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift

## Expected Behavior 
<img width="602" alt="Screenshot 2019-11-25 at 10 28 20" src="https://user-images.githubusercontent.com/42502002/69528396-6dbacf80-0f6e-11ea-902b-c40595636270.png">

## Actual Behavior
![Screenshot 2019-11-25 at 10 20 53](https://user-images.githubusercontent.com/42502002/69528409-73b0b080-0f6e-11ea-92e5-3f15d089ab19.png)

## Code Example
Just create a basic `AnimationView` with the given JSON. No code sample needed. Is also rendered wrongly in the Lottiefiles preview app.

## Animation JSON
As JSON files aren't supported on GitHub, here is a Google Drive link: https://drive.google.com/file/d/1BdbTsbranL9RASI6ozH0gBKS7Mo8Waa_/view?usp=sharing

**Comment by buba447** [comment]
Any chance I could get an after effects file to help me debug?

**Comment by WJJongkind** [comment]
@buba447 

It took a little while, but here is the AE file that you can use for debugging: https://drive.google.com/open?id=1ZUBvL9hNoVuWB8JTUgmBN2JfFmvLSTe9

Thank you for looking into this :)

**Comment by buba447** [comment]
Fixed and merged into master! https://github.com/airbnb/lottie-ios/pull/1087
Thanks for bringing this to my attention!

**Comment by WJJongkind** [comment]
@buba447 Thank you for picking this up so fast!
