### ISSUE TITLE
Severe performance issues in Lottie

### ISSUE THREAD

**Issue by christiankm** [airbnb/lottie-ios#1086]
Hi maintainers,
As others, we have severe performance issues with the latest version of Lottie. So far as I can red, it has to do with Swift Memory management.

From your perspective and findings, what are the primary causes of the problems? How can we optimise our animations to decrease resource usage? Fewer layers? complicated shapes and drawings?
Any learnings are most helpful. We can send you the animation files, and example app that causes us problems. Perhaps we can come to some improvements together.
On older devices, we are very close to crashes.

We have 5 animations in a collection view, that when all shown and scrolling, take up over 3-500 MB of memory and keeps CPU at 70-80%. We have severe frame drops with this setup.

I've read that going ack to Lottie 2.3.5 would help (as its Obj-C) but sadly our animations also uses Dynamic Texts.

## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [X] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [X] Swift
- [] Objective-C

## Animation JSON
Will send to email.

**Comment by iDevid** [comment]
I had a similar problem, some animation within a collectionView.
I founded tha in cellForItem, doing

`animationView.animation = Animation.named("my_animation.json")`

cause the framework to parse the json each time.
So just try with something like this: 
```
class AnimatableCell: UICollectionViewCell {

    @IBOutlet weak private var animationView: AnimationView!

    private var currentName: String = ""

    override func prepareForReuse() {
        super.prepareForReuse()
        animationView.stop()
    }

    func startAnimation() {
        animationView.loopMode = .loop
        animationView.play()
    }

    public func setAnimation(withName name: String, contentMode: UIView.ContentMode = .scaleAspectFit) {
        if name != currentName {
            currentName = name
            animationView.contentMode = contentMode
            animationView.animation = Animation.named(name)
        }
    }
}
```

**Comment by buba447** [comment]
Performance issues fall into two camps, parsing and playing animation. Parsing animation issues will not cause playback issue, but cause delays in loading the animations. Play back issues are not related to parsing and cause frame drops when playing.

Playback performance issues are being tracked here:
https://github.com/airbnb/lottie-ios/issues/895

Parsing performance issues are being tracked here:
https://github.com/airbnb/lottie-ios/issues/872

Im closing this issue since it's a duplicate. Please follow the linked issues for updates.
