### ISSUE TITLE
Animation loaded but not playing in iOS (same animation works on Android)

### ISSUE THREAD

**Issue by tanwei0319** [airbnb/lottie-ios#1090]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)

## Which Version of Lottie are you using?

Lottie 3.1.5

## What Platform are you on? 

- [x] iOS

## What Language are you in?
- [x] Swift

## Expected Behavior 
Animation to be played

## Actual Behavior
Lottie JSON was loaded but animation did not appear. Seems to be specific to this animation file on iOS only. Tried using the same lottie JSON in Android, as well as loading another animation with the same code, in both scenarios the animations worked perfectly.

## Animation JSON
I have shared the animation JSON via email.

**Comment by calda** [comment]
could you share a copy of the animation json?
