### ISSUE TITLE
Unable to set the frame of CompatibleAnimationView

### ISSUE THREAD

**Issue by whisterlee** [airbnb/lottie-ios#1091]
Hello! 

## Check these before submitting:

- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)

- [x] This issue isn't related to another open issue

## This issue is a:

- [x] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [ ]  Feature Request
- [ ] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [ ] MacOS

- [x] iOS

## What Language are you in?

- [ ] Swift
- [x] Objective-C

## Expected Behavior 

CompatibleAnimationView should be the same size as the parent view

## Actual Behavior

CompatibleAnimationView is not the same size as the parent view

![image](https://user-images.githubusercontent.com/17923550/69847605-8e5a9080-12b2-11ea-8bdc-d32d0718fe5f.png)

## Code Example

- (void)viewDidLoad
{
    [super viewDidLoad];
    
    CGFloat timeLineViewW = 276.f;
    CGFloat timeLineViewH = 96.f;
    CGFloat timeLineViewX = (self.view.bounds.size.width - timeLineViewW) / 2.f;
    CGFloat timeLineViewY = (self.view.bounds.size.width - timeLineViewH) / 2.f;
    UIView *timeLineView = [[UIView alloc] initWithFrame:CGRectMake(timeLineViewX, timeLineViewY, timeLineViewW, timeLineViewH)];
    timeLineView.backgroundColor = [UIColor blueColor];
    [self.view addSubview:timeLineView];
    
    CompatibleAnimationView *animationView = [[CompatibleAnimationView alloc] initWithFrame:timeLineView.bounds];
    animationView.contentMode = UIViewContentModeScaleAspectFit;
    animationView.loopAnimationCount = -1;
    animationView.compatibleAnimation = [[CompatibleAnimation alloc] initWithName:@"timeline" bundle:[NSBundle mainBundle]];
    [animationView play];
    [timeLineView addSubview:animationView];
}

## Animation JSON

[timeline.json.zip](https://github.com/airbnb/lottie-ios/files/3903965/timeline.json.zip)

**Comment by farfromrefug** [comment]
I am facing the same issue!

**Comment by farfromrefug** [comment]
@whisterlee actually found a fix! set `translatesAutoresizingMaskIntoConstraints` to `true` on the `CompatibleAnimationView`

**Comment by damikdk** [comment]
@farfromrefug Thank you so much, you just saved me!
