### ISSUE TITLE
Animation flick in the middle

### ISSUE THREAD

**Issue by mumensh** [airbnb/lottie-ios#1092]
## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.5

## What Platform are you on? 

- [] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift
- [] Objective-C

## Expected Behavior 

The animation is flicking at the middle, when I'm trying the same file on the web, there is no flick, but in iOS, it does, I've used the library example project to double check that's it's not something wrong in my project, but I've got the same result.

## Actual Behavior

It should be smooth as expected.
## Animation JSON

[replay.json.zip](https://github.com/airbnb/lottie-ios/files/3906488/replay.json.zip)

**Comment by caioremedio** [comment]
I'm facing exactly the same issue after upgrading to 3.0.

I ran your animation on objective-c version and its perfectly fine, but not on 3.0 version. Same as mine.

Any thoughts about that?

**Comment by calda** [comment]
I tested this animation using the new Core Animation rendering engine added in 3.4.0, and it plays as expected with no flickering. You can learn more here: https://github.com/airbnb/lottie-ios/discussions/1627
