### ISSUE TITLE
Why bodymovin export lottie-ios will add the line????

### ISSUE THREAD

**Issue by xiaoheliyu** [airbnb/lottie-ios#1094]
## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?
Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [YES] iOS

## What Language are you in?
- [YES] Swift
- [] Objective-C

## [Expected](`
![微信截图_20191204074040](https://user-images.githubusercontent.com/58513408/70139806-a8f18880-1669-11ea-8d05-d32917ceb595.png)

> url

`) Behavior 

[](url)
## Code Example
{"v":"5.5.10","fr":25,"ip":0,"op":120,"w":640,"h":750,"nm":"wangzai_loop","ddd":0,"assets":[{"id":"image_0","w":369,"h":430,"u":"images/","p":"img_0.png","e":0},{"id":"image_1","w":227,"h":129,"u":"images/","p":"img_1.png","e":0},{"id":"image_2","w":214,"h":182,"u":"images/","p":"img_2.png","e":0},{"id":"image_3","w":640,"h":750,"u":"images/","p":"img_3.png","e":0}],"layers":[{"ddd":0,"ind":1,"ty":4,"nm":"Shape Layer 3","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":1,"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":0,"s":[571.975,131.8,0],"to":[0.75,0.49,0],"ti":[0.113,-1.891,0]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":30.051,"s":[576.475,134.737,0],"to":[-0.114,1.903,0],"ti":[1.438,0.375,0]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":60.101,"s":[570.35,136.612,0],"to":[-1.438,-0.375,0],"ti":[-1.021,2.24,0]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":90.151,"s":[567.85,132.487,0],"to":[0.351,-0.77,0],"ti":[-0.688,0.115,0]},{"t":119,"s":[571.975,131.8,0]}],"ix":2},"a":{"a":0,"k":[-268.04,148.636,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"d":1,"ty":"el","s":{"a":0,"k":[10.152,10.152],"ix":2},"p":{"a":0,"k":[0,0],"ix":3},"nm":"Ellipse Path 1","mn":"ADBE Vector Shape - Ellipse","hd":false},{"ty":"fl","c":{"a":0,"k":[0.980392216701,0.356862745098,0.172549019608,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[-268.04,148.636],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[99.071,99.071],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Ellipse 1","np":3,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":120,"st":0,"bm":0},{"ddd":0,"ind":2,"ty":4,"nm":"Shape Layer 2","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":1,"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":0,"s":[608.404,441.725,0],"to":[1.063,0.521,0],"ti":[-0.833,-1.333,0]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":30.051,"s":[614.779,444.85,0],"to":[0.833,1.333,0],"ti":[1.333,-0.333,0]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":60.101,"s":[613.404,449.725,0],"to":[-1.333,0.333,0],"ti":[0.833,1.333,0]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":90.151,"s":[606.779,446.85,0],"to":[-0.833,-1.333,0],"ti":[-0.271,0.854,0]},{"t":119,"s":[608.404,441.725,0]}],"ix":2},"a":{"a":0,"k":[-268.04,148.636,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"d":1,"ty":"el","s":{"a":0,"k":[10.152,10.152],"ix":2},"p":{"a":0,"k":[0,0],"ix":3},"nm":"Ellipse Path 1","mn":"ADBE Vector Shape - Ellipse","hd":false},{"ty":"fl","c":{"a":0,"k":[0.980392216701,0.356862745098,0.172549019608,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[-268.04,148.636],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[99.071,99.071],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Ellipse 1","np":3,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":120,"st":0,"bm":0},{"ddd":0,"ind":3,"ty":4,"nm":"Shape Layer 1","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":1,"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":0,"s":[52.375,523,0],"to":[-1.333,1.292,0],"ti":[-0.75,-2.438,0]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":30.051,"s":[44.375,530.75,0],"to":[0.75,2.438,0],"ti":[-3.813,0.313,0]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":60.101,"s":[56.875,537.625,0],"to":[3.813,-0.313,0],"ti":[0.75,2.438,0]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":90.151,"s":[67.25,528.875,0],"to":[-0.75,-2.438,0],"ti":[2.479,0.979,0]},{"t":119,"s":[52.375,523,0]}],"ix":2},"a":{"a":0,"k":[-267.665,148.261,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"d":1,"ty":"el","s":{"a":0,"k":[10.152,10.152],"ix":2},"p":{"a":0,"k":[0,0],"ix":3},"nm":"Ellipse Path 1","mn":"ADBE Vector Shape - Ellipse","hd":false},{"ty":"fl","c":{"a":0,"k":[0.980392216701,0.356862745098,0.172549019608,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[-267.665,148.261],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[129.935,129.935],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Ellipse 1","np":3,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":120,"st":0,"bm":0},{"ddd":0,"ind":4,"ty":4,"nm":"eye_1","parent":6,"sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[100.249,218.057,0],"ix":2},"a":{"a":0,"k":[110,-90.25,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":1,"k":[{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":24,"s":[{"i":[[-16.292,0],[0,-19.192],[16.292,0],[0,19.192]],"o":[[16.292,0],[0,19.192],[-16.292,0],[0,-19.192]],"v":[[0,-34.75],[29.5,0],[0,34.75],[-29.5,0]],"c":true}]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":32,"s":[{"i":[[-18.664,0.288],[0,-9.96],[20.235,-0.12],[0.238,7.826]],"o":[[18.664,-0.288],[0,7.698],[-18.675,0.11],[-0.277,-9.102]],"v":[[0.011,-9.53],[29.398,4.411],[0.011,3.838],[-29.489,3.699]],"c":true}]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":40,"s":[{"i":[[-16.292,0],[0,-19.192],[16.292,0],[0,19.192]],"o":[[16.292,0],[0,19.192],[-16.292,0],[0,-19.192]],"v":[[0,-34.75],[29.5,0],[0,34.75],[-29.5,0]],"c":true}]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":48,"s":[{"i":[[-18.664,0.288],[0,-9.96],[20.235,-0.12],[0.238,7.826]],"o":[[18.664,-0.288],[0,7.698],[-18.675,0.11],[-0.277,-9.102]],"v":[[0.011,-9.53],[29.398,4.411],[0.011,3.838],[-29.489,3.699]],"c":true}]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":56,"s":[{"i":[[-16.292,0],[0,-19.192],[16.292,0],[0,19.192]],"o":[[16.292,0],[0,19.192],[-16.292,0],[0,-19.192]],"v":[[0,-34.75],[29.5,0],[0,34.75],[-29.5,0]],"c":true}]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":93,"s":[{"i":[[-16.292,0],[0,-19.192],[16.292,0],[0,19.192]],"o":[[16.292,0],[0,19.192],[-16.292,0],[0,-19.192]],"v":[[0,-34.75],[29.5,0],[0,34.75],[-29.5,0]],"c":true}]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":101,"s":[{"i":[[-18.664,0.288],[0,-9.96],[20.235,-0.12],[0.238,7.826]],"o":[[18.664,-0.288],[0,7.698],[-18.675,0.11],[-0.277,-9.102]],"v":[[0.011,-9.53],[29.398,4.411],[0.011,3.838],[-29.489,3.699]],"c":true}]},{"t":109,"s":[{"i":[[-16.292,0],[0,-19.192],[16.292,0],[0,19.192]],"o":[[16.292,0],[0,19.192],[-16.292,0],[0,-19.192]],"v":[[0,-34.75],[29.5,0],[0,34.75],[-29.5,0]],"c":true}]}],"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":0,"k":[1,1,1,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[110,-90.25],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[105.085,87.851],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Ellipse 1","np":3,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":120,"st":0,"bm":0},{"ddd":0,"ind":5,"ty":4,"nm":"eye_2","parent":6,"sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[276.249,218.057,0],"ix":2},"a":{"a":0,"k":[110,-90.25,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":1,"k":[{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":24,"s":[{"i":[[-16.292,0],[0,-19.192],[16.292,0],[0,19.192]],"o":[[16.292,0],[0,19.192],[-16.292,0],[0,-19.192]],"v":[[0,-34.75],[29.5,0],[0,34.75],[-29.5,0]],"c":true}]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":32,"s":[{"i":[[-18.664,0.288],[0,-9.96],[20.235,-0.12],[0.238,7.826]],"o":[[18.664,-0.288],[0,7.698],[-18.675,0.11],[-0.277,-9.102]],"v":[[0.011,-8.818],[29.398,5.122],[0.011,4.55],[-29.489,4.411]],"c":true}]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":40,"s":[{"i":[[-16.292,0],[0,-19.192],[16.292,0],[0,19.192]],"o":[[16.292,0],[0,19.192],[-16.292,0],[0,-19.192]],"v":[[0,-34.75],[29.5,0],[0,34.75],[-29.5,0]],"c":true}]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":48,"s":[{"i":[[-18.664,0.288],[0,-9.96],[20.235,-0.12],[0.238,7.826]],"o":[[18.664,-0.288],[0,7.698],[-18.675,0.11],[-0.277,-9.102]],"v":[[0.011,-8.818],[29.398,5.122],[0.011,4.55],[-29.489,4.411]],"c":true}]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":56,"s":[{"i":[[-16.292,0],[0,-19.192],[16.292,0],[0,19.192]],"o":[[16.292,0],[0,19.192],[-16.292,0],[0,-19.192]],"v":[[0,-34.75],[29.5,0],[0,34.75],[-29.5,0]],"c":true}]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":93,"s":[{"i":[[-16.292,0],[0,-19.192],[16.292,0],[0,19.192]],"o":[[16.292,0],[0,19.192],[-16.292,0],[0,-19.192]],"v":[[0,-34.75],[29.5,0],[0,34.75],[-29.5,0]],"c":true}]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":101,"s":[{"i":[[-18.664,0.288],[0,-9.96],[20.235,-0.12],[0.238,7.826]],"o":[[18.664,-0.288],[0,7.698],[-18.675,0.11],[-0.277,-9.102]],"v":[[0.011,-8.818],[29.398,5.122],[0.011,4.55],[-29.489,4.411]],"c":true}]},{"t":109,"s":[{"i":[[-16.292,0],[0,-19.192],[16.292,0],[0,19.192]],"o":[[16.292,0],[0,19.192],[-16.292,0],[0,-19.192]],"v":[[0,-34.75],[29.5,0],[0,34.75],[-29.5,0]],"c":true}]}],"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":0,"k":[1,1,1,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[110,-90.25],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[105.085,87.851],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Ellipse 1","np":3,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":120,"st":0,"bm":0},{"ddd":0,"ind":6,"ty":2,"nm":"head_2.png","cl":"png","refId":"image_0","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":1,"k":[{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":0,"s":[4.7]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":16,"s":[15.9]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":56,"s":[15.9]},{"t":70,"s":[4.7]}],"ix":10},"p":{"a":0,"k":[319,456,0],"ix":2},"a":{"a":0,"k":[185.249,395.307,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"ip":0,"op":120,"st":0,"bm":0},{"ddd":0,"ind":7,"ty":2,"nm":"body 2","refId":"image_1","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[335,524,0],"ix":2},"a":{"a":0,"k":[113.5,64.5,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"ip":0,"op":120,"st":0,"bm":0},{"ddd":0,"ind":8,"ty":2,"nm":"hand","refId":"image_2","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":1,"k":[{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":0,"s":[-25.2]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":16,"s":[-5.7]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":24,"s":[2]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":32,"s":[-5.7]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":40,"s":[2]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":48,"s":[-5.7]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":56,"s":[2]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":80,"s":[-25.2]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":93,"s":[-12.805]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":101.667,"s":[-25.2]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":110.334,"s":[-12.805]},{"t":119,"s":[-25.2]}],"ix":10},"p":{"a":0,"k":[267.5,501,0],"ix":2},"a":{"a":0,"k":[174.866,146,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"ip":0,"op":120,"st":0,"bm":0},{"ddd":0,"ind":9,"ty":2,"nm":"BG2.png","cl":"png","refId":"image_3","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[320,375,0],"ix":2},"a":{"a":0,"k":[320,375,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"ip":0,"op":120,"st":0,"bm":0}],"markers":[]}

## Animation JSON

[12_3_wangzai_loop_V4.zip](https://github.com/airbnb/lottie-ios/files/3921602/12_3_wangzai_loop_V4.zip)
[wangzai_loop.zip](https://github.com/airbnb/lottie-ios/files/3921603/wangzai_loop.zip)

**Comment by Rapsssito** [comment]
Please, consider reuploading your **expected** and **actual behavior** files.

**Comment by calda** [comment]
Could you share more details about your issue? What part specifically is displaying incorrectly?
