### ISSUE TITLE
Reversal image not working

### ISSUE THREAD

**Issue by nikolayzhuk** [airbnb/lottie-ios#1096]
Hello.
I have html lottie json file and it works in web browser perfectly.
Then I am going to make it run in iOS but reversal animation is not working in lottie-ios
I installed 3.1.5 version and I just tested it in Example/lottie-swift.
I attached my json file and images working in web browser.
Please help me what I should do.

Thanks
[reversal.zip](https://github.com/airbnb/lottie-ios/files/3950916/reversal.zip)

**Comment by calda** [comment]
Hi @nikolayzhuk, if you still need help with using images in your animations, feel free to [start a discussion](https://github.com/airbnb/lottie-ios/discussions).
