### ISSUE TITLE
Unused constant value 'scale' generates Swift compiler warning. 

### ISSUE THREAD

**Issue by pouriaalmassi** [airbnb/lottie-ios#1098]
The following build warning is emitted by an unused value. 

`
/path/Pods/lottie-ios/lottie-swift/src/Private/LayerContainers/CompLayers/TextCompositionLayer.swift:118:9: Initialization of immutable value 'scale' was never used; consider replacing with assignment to '_' or removing it
`

## This issue is a:
- [✓] Non-Crashing Bug (Visual or otherwise)
- [✘] Crashing Bug
- [✘] Feature Request
- [✓] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

- Lottie 3.1.5
- Installed with Cocoapods

## What Platform are you on? 

- [✘] MacOS
- [✓] iOS

## What Language are you in?
- [✓] Swift
- [✘] Objective-C

## Expected Behavior 
Lottie should not generate a warning on build. 

## Actual Behavior
Lottie generates a warning on build. 

<img width="1431" alt="Screen Shot 2019-12-12 at 9 27 36 am" src="https://user-images.githubusercontent.com/1231767/70665982-d53c8300-1cc1-11ea-8628-88ec88171c1d.png">

**Comment by kevinmbeaulieu** [comment]
Looks like this has been fixed here- https://github.com/airbnb/lottie-ios/commit/c3d47602f88c5b41b087a3e52b6e14ba026c7adb

**Comment by pouriaalmassi** [comment]
Cheers. I'll close this one.

**Comment by nbattelli** [comment]
I still have the warning
Xcode 11.3.1
lottie-ios 3.1.5

**Comment by kevinmbeaulieu** [comment]
Yeah it looks like there hasn’t been a release yet since the fix was merged
