### ISSUE TITLE
build errors duo to Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by pilot4u** [airbnb/lottie-ios#1100]
Cannot build our project which imports v3.1.5 via CocoaPods
attached error file
[lottie build erros.txt](https://github.com/airbnb/lottie-ios/files/3958517/lottie.build.erros.txt)

**Comment by devangelmotta** [comment]
Same mistake. Did you find any solution for this?

**Comment by calda** [comment]
Closing since this seems like a potentially outdated CocoaPods issue. Feel free to re-open if you're still experiencing this issue.
