### ISSUE TITLE
When will expressions be supported?

### ISSUE THREAD

**Issue by ninjz** [airbnb/lottie-ios#1102]
Hi Team,

I'm wondering if expressions is planned to be supported some time in the future? It seems that every issue I have encountered about this issue (#844 #574 ) , it has always been said that it is not supported on Lottie iOS and Android. Is it not possible to support on iOS and Android or is it just not yet supported?

Thanks

**Comment by buba447** [comment]
It can be supported and I plan on adding support to iOS eventually.

Right now the hold up is having time or resources to add such large feature. We have moved Lottie onto github sponsors in hope that we can crowd fund continued development.

**Comment by ninjz** [comment]
Ok that's great. Thanks for your response and the great work on this project.
