### ISSUE TITLE
Poor performance during scrolling even when animation is stopped 

### ISSUE THREAD

**Issue by IzikLisbon** [airbnb/lottie-ios#1105]
Since performance is poor when scrolling (See https://github.com/airbnb/lottie-ios/issues/852), I have tried to work around it by stopping animation during scrolling. 
However, performance stayed low even when the animation stopped.  

To repro it I have created an app with 3 pages where every page has a Lottie animation. 

With Core Animation profiling I have tried 3 scenarios:
1. Scrolling when Lottie is animating 
2. Scrolling when Lottie is stopped
3. Scrolling when Lottie is replaced with a UIImage.
 
Here are the results: 
![image](https://user-images.githubusercontent.com/10648880/71412158-430d7680-2601-11ea-81a4-47ea64a932bf.png)

setting `shouldRasterizeWhenIdle` to true had no affect. 

## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.5

## What Platform are you on? 
- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 
When scrolling, if animation is stopped, FPS (Frame Per Second) should stay high and Device Utilization should stay low. I am expecting the same performance as if Lottie would be replaced with a static UIImage.  

## Actual Behavior
Regardless of animation state (running/stopped) the performance is low.

## Code Example
Test app: https://github.com/IzikLisbon/lottie-performance-bug

A simple app with 3 pages where every page has a Lottie animation. 
Also expose 2 buttons:
1. Remove/Add Lottie
2. Stop/Play Lottie

Note: the app was tested with a much bigger JSON file and the profiler screenshot above was created with that file but even the [committed Animation JSON](https://github.com/IzikLisbon/lottie-performance-bug/blob/master/lottie_performance_bug/animations/medium_animation.json) shows that Device Utilization stays high when animation is stopped (but the FPS stays stable above 55).

## Animation JSON
https://github.com/IzikLisbon/lottie-performance-bug/blob/master/lottie_performance_bug/animations/medium_animation.json

**Comment by IzikLisbon** [comment]
Observation:  there are recursive calls to `updateContents` during scrolling even when animation is stopped: 
![recursive_call_to_updateContents](https://user-images.githubusercontent.com/10648880/71414686-e0ba7300-260c-11ea-8c8d-fa01e00b7c27.png)

**Comment by Rapsssito** [comment]
Might be related to #895

**Comment by IzikLisbon** [comment]
@Rapsssito it might be the same root cause as #895, however this issue is about scrolling when animation is stopped. Other issues refers to animation performance or scrolling performance when animation is running.
