### ISSUE TITLE
Dashes setting on shape layer path not working on iOS

### ISSUE THREAD

**Issue by sureMOE** [airbnb/lottie-ios#111]
I have animated the dashes property in After Effects on a shape layer and it translates fine for the Android player, but iOS doesn't recognize it and ignores the dashes altogether.

**Comment by sureMOE** [comment]
![unnamed](https://cloud.githubusercontent.com/assets/18271665/23224276/87a8b22c-f8e2-11e6-9785-58a2909c673b.png)
![img_0302 png](https://cloud.githubusercontent.com/assets/18271665/23224277/87b6d62c-f8e2-11e6-9460-d4bc9ec96b3a.png)

**Comment by therealsalih** [comment]
Hi @sureMOE Can you attach the AE file so we can check it out? Thanks!

**Comment by sureMOE** [comment]
Yes of course! Here it is. 

Also, I am having some ghosting/glitching when this thing loops. I can't figure out what I am doing to cause that in AE, so if you have any insight there, it would be awesome. Thanks!


[YTK_loader_bubbles.aep.zip](https://github.com/airbnb/lottie-ios/files/794547/YTK_loader_bubbles.aep.zip)

**Comment by sureMOE** [comment]
It appears that when it loops, it draws the entire circle first and then cuts it down to the trim path size. Is this a glitch in how Lottie is drawing the object?

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
