### ISSUE TITLE
UIWebView - deprecated but found

### ISSUE THREAD

**Issue by keisyrzk** [airbnb/lottie-ios#1112]
Hey,

I am facing the problem when submitting to Apple. I did the search with 'grep' command and have a result in Lottie. Could you please tell me if the problem really exists by your side?
Thanks.

MacBook-Pro-Esteban:iOS esteban$ grep -r UIWebView .
Binary file ./Lottie.framework.dSYM/Contents/Resources/DWARF/Lottie matches

iOS
Swift
Latest Lottie version (download 21.01.2020)

**Comment by RANGELJ** [comment]
Same here!, is ther any solution?, almost time to update or apple will not accept our apps

**Comment by JuhaO81** [comment]
Same same!

Running grep -r "UIWebView" . 

results:
Binary file ./Carthage/Build/iOS/Lottie.framework.dSYM/Contents/Resources/DWARF/Lottie matches

**Please remove UIWebView usage and all mentions of it. **

PS we are using lottie 3.1.6

**Comment by tariq235** [comment]
I am facing the same problem but i couldn't find UIWebView in the repo
"We couldn’t find any code matching 'UIWebView' in airbnb/lottie-ios"

**Comment by skovalysh** [comment]
Same!

Running grep -r "UIWebView" .

results:
Binary file ./Carthage/Build/iOS/Lottie.framework.dSYM/Contents/Resources/DWARF/Lottie matches

but I couldn't find UIWebView in the repo

**Comment by Jethro234** [comment]
Same here as well.

Running grep -r "UIWebView" .

I am using version 2.5.3

**Comment by jchesterdev** [comment]
Same here.

Also using version 2.5.3

**Comment by cah-siddharth-paneri** [comment]
Hi
Is there any resolution yet?

**Comment by RANGELJ** [comment]
Hi!, the problem disappeared when i update to react native .62, but i suspect it was caused by other dependency, version number of lottie-ios: ^3.1.6

**Comment by Jethro234** [comment]
> Hi!, the problem disappeared when i update to react native .62, but i suspect it was caused by other dependency, version number of lottie-ios: ^3.1.6

I'm not using React native, I have a native (objective-C) app.

**Comment by Jethro234** [comment]
> Hi
> Is there any resolution yet?

Agreed, an update would be useful.

**Comment by matiasvillagran** [comment]
Hi guys! 
any resolution yet?

**Comment by buba447** [comment]
Not really sure what to say about this one. Ive searched the entire project and can verify that there are no references to Webkit or UIWebView. 

Seems like in most cases its a problem with React, not Lottie.
