### ISSUE TITLE
Centering animation does not work

### ISSUE THREAD

**Issue by d0hnj0e** [airbnb/lottie-ios#1115]
## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift
- [] Objective-C

## Expected Behavior 
Centered animation view with equal size

## Actual Behavior
Uncentered animation view with different size

## Code Example
<img width="1124" alt="Xcode" src="https://user-images.githubusercontent.com/9201403/72831722-ad0e4f80-3c83-11ea-9601-8f8381e7c530.png">
<img width="1124" alt="iPhone" src="https://user-images.githubusercontent.com/9201403/72831801-db8c2a80-3c83-11ea-9f1b-d16882fca3bc.PNG">

**Comment by d0hnj0e** [comment]
Anyone?

**Comment by RamblinWreck77** [comment]
Try doing defining frame == bounds inside an override of  viewDidLayoutSubviews.

The actual bounds may/may not be fully defined when viewDidLoad completes. Thanks Apple! /s

**Comment by calda** [comment]
Closing since this sounds like an iOS SDK issue. If you'd still like support feel free to start a discussion.
