### ISSUE TITLE
Consider using ZippyJSON as a drop in improvement to Codable Performance Issues?

### ISSUE THREAD

**Issue by kyle-fox** [airbnb/lottie-ios#1117]
## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

Instead of trying to find time to make improvements yourself, or writing your own JSON parsing again, it might be worth testing out Lottie after just dropping in [ZippyJSON](https://github.com/michaeleisel/zippyjson) as a dependency? I came across it in [this thread](https://forums.swift.org/t/rearchitecting-jsonencoder-to-be-much-faster/28139). I know it's not an ideal solution, but it could serve as a placeholder to get better performance while waiting for a more permanent solution. Unfortunately, I haven't had the chance to test this myself, but when I do, I'll follow up here. Hoping your test suite would be a better place to run this anyway!

**Comment by liulichao123** [comment]
The swift version is more time-consuming to load Lottie than the OC(2.5.3) version, which I found to be caused by the different JSON parsing, especially when the APP started, loading multiple Lottie animations, which seriously slowed down the startup speed.
I hope this problem can be improved

**Comment by sheff1422** [comment]
@kyle-fox Unfortunately that is not completely drop in solution. I am working on that for the second day. And ZippyJSON behaves strange when decoding a heterogeneous list of objects for a given family.
I am trying to get in touch with ZippyJSON supporter and get more info. Rn It throws some exceptions.

**Comment by kyle-fox** [comment]
Closing, since it doesn't seem to be worth the change. Feel free to reopen if that changes!

**Comment by michaeleisel** [comment]
hi, author of zippyjson here. i've gotten a number of issues/prs from people concerning uses of lottie with it, so it seems popular and i'm happy to offer support. zippyjson is intended to be a drop-in replacement, and if you see any difference feel free to report it. sheff's planning to test the new release of zippyjson which has a fix for that issue. hopefully that's the last remaining blocker

**Comment by kyle-fox** [comment]
Might as well re-open, since it seems to be a possibility, at least? Sorry that I don't have time to do any further testing at the moment. Thanks for the info Michael!

**Comment by sheff1422** [comment]
@kyle-fox I will check if that is working for me this week.

**Comment by zabolotiny** [comment]
All who is interested in adding zippy json, i am experimenting with it rn. However at this point of time there is no expected performance boost. I will keep updating this thread during experiments

**Comment by michaeleisel** [comment]
Yes, let's hold off on expectations for now

**Comment by michaeleisel** [comment]
@zabolotiny have you tested the next version? in my testing, it's much faster than apple's

**Comment by michaeleisel** [comment]
i think we can go forwards. @zabolotiny do you still want to drive this?

**Comment by michaeleisel** [comment]
i can drive this. how can i run all the unit tests for this project? @buba447

**Comment by zabolotiny** [comment]
@michaeleisel  Sorry for really slow response time. I have a lot of things going on with main project and had to leave Lottie for some time as it was.
But today I returned back to this question and tested it with my animation pack again:
ZippyJSON 1.2.1
iPad Air 1
Lottie  (JSONDecoder)  -> 3.3701289892196655
Lottie  (ZippyJSON) -> 3.8821139335632324
So unfortunately rn it is slower than JSONDecoder :(

**Comment by calda** [comment]
3.4.0 includes a new parsing implementation that is 2x faster than the previous `Codable` implementation (#1561)
