### ISSUE TITLE
Add delay option for animation.

### ISSUE THREAD

**Issue by maurovc** [airbnb/lottie-ios#112]
something common in iOS like:

```
animationView.play(delay: 0.5) { (finished) in
 // Finished code
}
```

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC

**Comment by akashnimare** [comment]
@buba447 any way to add delay?
