### ISSUE TITLE
stat() failed with errno=1, code signature invalid

### ISSUE THREAD

**Issue by LiYanan2004** [airbnb/lottie-ios#1120]
## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [-] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [-] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [-] iOS

## What Language are you in?
- [-] Swift
- [] Objective-C

## Animation JSON

When I using the latest iOS version(13.3.1), the lottie has crashed when my app was launching.
here is the snapshot:
<img width="1125" alt="截屏2020-02-05下午7 41 33" src="https://user-images.githubusercontent.com/37542129/73839042-fb107f00-484f-11ea-82c1-9153727c746a.png">

**Comment by calda** [comment]
Closing since this seems like a potentially outdated issue. Feel free to re-open if you're still experiencing this issue.
