### ISSUE TITLE
Animation is not loading the images from the images folder

### ISSUE THREAD

**Issue by vburojevic** [airbnb/lottie-ios#1121]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 

Lottie json file with images folder is getting loaded and playing properly.

## Actual Behavior

Lottie animation is not displaying the images. Same file with same images works fine on Android. Also, demo HTML works just fine as well.

## Code Example
`private let animationView: AnimationView = {
        let view = AnimationView(name: "data")
        view.backgroundBehavior = .pauseAndRestore
        view.loopMode = .loop
        view.contentMode = .scaleAspectFit
        view.play()
        return view
    }()`

## Animation JSON

[data.json.zip](https://github.com/airbnb/lottie-ios/files/4162438/data.json.zip)

**Comment by vburojevic** [comment]
Can anyone comment on this, please?

**Comment by liulichao123** [comment]
You need to customize the AnimationImageProvider to be passed in as an argument when creating the AnimationView
AnimationView (animation, animation, imageProvider: customImageProvider),
Does the AnimationImageProvider determine how to load the image content

**Comment by calda** [comment]
+1, you'll need to set up an `AnimationImageProvider` if the default `BundleImageProvider` doesn't work automatically.
