### ISSUE TITLE
If a Lottie animation is looping when applicationWillResignActive occurs, and its parent view is resized/animated, the lottie animation will break/detatch from the parent.

### ISSUE THREAD

**Issue by RamblinWreck77** [airbnb/lottie-ios#1124]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.6

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 
-A centered/frame == bounds animation should remain in said view when the view is animated/size changed

## Actual Behavior
-When a system prompt is called "WillResignActive" is called, and if an animation is looping it will desync with its parent frame. The scenario is:

1) Top banner animates in prompting for push notifications permission , compressing some of the main page

2) A lottie animation is running centrally located on the main page. The banner animating in does *not* break the animation yet

3) Tapping the banner loads the system notification prompt (triggering WillResignActive)

4) As the iOS notification prompt appears the banner animates out, causing the main page layout to adapt. The looping lottie animation is now no longer centered in the parent frame, and seems to inherit additional incorrect offsets with each animation of the parent view.

I'd be happy to email any of the devs with a video of my app demoing the bug, as well as enable some debug layers so it's obvious the parent view is getting sized right. Thanks for all your hard work guys!

## Animation JSON
Not relevant, happens with any animation file

**Comment by calda** [comment]
Could you share a sample project that reproduces this issue?
