### ISSUE TITLE
Animation progress change listener

### ISSUE THREAD

**Issue by xenforox** [airbnb/lottie-ios#1131]
hello, is there a clean and working way to get continuous animationProgress. I tried to use a timers and CADisplaylink aswell but it doesnt seem to be getting the right value of progress or frame as the animation goes on. I’d apperciate any help thank you!

**Comment by buba447** [comment]
Use `animationView.realtimeAnimationProgress`

**Comment by AgileFlexAgency** [comment]
@xenforox  Let me guide with @buba447 's solid piece of advice:

> The preferred way to do this is to setup a CADisplayLink to run asynchronously alongside a playing animation and query the AnimationView.realtimeAnimationProgress.
> 
> Theres a great example of this in the main view controllers of the example app in the repo. The animation drives the progress bar in realtime.
> 
> Cheers!

We've implemented per Brandon's comments and everything works as expected.

@buba447 You're a PRO & thanks for taking the time to answer us.

**Comment by bogren** [comment]
Follow up question on the above issue, how do track each loop? My animation's `realtimeAnimationProgress` never reach 1 before starting over. 

I play the animation during long press gesture, start looping the animation, and for each I want to make another action.
