### ISSUE TITLE
Crashing on iPhone 6 plus(iOS 12.4.1), Message from debugger: Terminated due to memory issue

### ISSUE THREAD

**Issue by amolnikam** [airbnb/lottie-ios#1132]
## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [X] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.5

## What Platform are you on? 

- [] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift
- [] Objective-C

## Expected Behavior 

App should  not crash 
## Actual Behavior

App is crashing due to memory issue while loading loop animation on iPhone 6 plus iOS - 12.4.1

**Comment by mesutaltuncu** [comment]
Same issue

**Comment by dhipin** [comment]
This issue has been occurring for me all the iPhone devices with iOS 12.x.x

**Comment by freudibili** [comment]
Everything is fine on my android and ios emulator but I have the Same Issue on an iPhone 12.

I tried with different animation and only a few crashed.

**Comment by chj-damon** [comment]
same here.

**Comment by calda** [comment]
The new Core Animation rendering engine in Lottie 3.4.0 likely fixes this issue
