### ISSUE TITLE
iOS - Add delegate to return the current frame playing 

### ISSUE THREAD

**Issue by AgileFlexAgency** [airbnb/lottie-ios#1136]
iOS - Add delegate or hooked events to return the current frame playing (eg: 15 of 160 frames)

Thus other events can be triggered while the animationView plays between certain frames.

@buba447 - Brandon my contribution for this request will be $100 if you accept it.

## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
**- [] Feature Request**

## Which Version of Lottie are you using?
**Lottie 3.0**

## What Platform are you on? 
**- [] iOS**

## What Language are you in?
**- [] Swift**

**Comment by buba447** [comment]
The preferred way to do this is to setup a CADisplayLink to run asynchronously alongside a playing animation and query the `AnimationView.realtimeAnimationProgress`. 

Theres a great example of this in the main view controllers of the example app in the repo. The animation drives the progress bar in realtime.

Cheers!

**Comment by AgileFlexAgency** [comment]
We've implemented per your comments and everything works as expected.

Thank you for the time taken to answer us. 👍 🥇
