### ISSUE TITLE
Label animation is not animating inside Swift 

### ISSUE THREAD

**Issue by DieGlueckswurst** [airbnb/lottie-ios#1137]
## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 

![Bildschirmfoto 2020-03-02 um 13 11 40](https://user-images.githubusercontent.com/40027124/75675391-60a52f00-5c87-11ea-83ba-3767b8e8d55c.png)

## Actual Behavior

Inside the app there is animation at all and not even the font is being displaced correctly.

![Bildschirmfoto 2020-03-02 um 13 09 55](https://user-images.githubusercontent.com/40027124/75675289-29cf1900-5c87-11ea-9c93-1a17b0e8c0ee.png)

When uploading it to LottiFiles-Preview it is displaying the Font correctly but the "Stroke"-Animation is not how it should look (how it looks in AE). Here my AE-File: Maybe I am doing something wrong there, I am an absolut beginner to AE:

[WishlistStrokeAnimation.aep.zip](https://github.com/airbnb/lottie-ios/files/4275324/WishlistStrokeAnimation.aep.zip)

## Code Example
```
@objc func showAnimationTapped(){
        let logoAnimation = AnimationView(name: "StrokeAnimation")
        logoAnimation.contentMode = .scaleAspectFit
        logoAnimation.translatesAutoresizingMaskIntoConstraints = false
        self.view.addSubview(logoAnimation)
        
        logoAnimation.centerXAnchor.constraint(equalTo: view.centerXAnchor).isActive = true
        logoAnimation.centerYAnchor.constraint(equalTo: view.centerYAnchor).isActive = true
        logoAnimation.heightAnchor.constraint(equalToConstant: 200).isActive = true
        logoAnimation.widthAnchor.constraint(equalToConstant: 200).isActive = true
        
        logoAnimation.play()
 }
```

## Animation JSON

[StrokeAnimation.json.zip](https://github.com/airbnb/lottie-ios/files/4275315/StrokeAnimation.json.zip)

**Comment by calda** [comment]
This is the same issue as https://github.com/airbnb/lottie-ios/discussions/1692#discussioncomment-3320411 -- the animation has embedded font data for a font called `GlossAndBloom`, which isn't supported on iOS. To use this animation on iOS, you'd need to set up an `AnimationFontProvider` to vend this font.
