### ISSUE TITLE
Animated paths with gradients doesn't work properly only on iOS

### ISSUE THREAD

**Issue by marcmelapp** [airbnb/lottie-ios#1146]
**## Check these before submitting:**
- [✅] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [✅] This issue isn't related to another open issue

**## This issue is a:**
- [✅] Non-Crashing Bug (Visual or otherwise)

**## Which Version of Lottie are you using?**

Lottie 3.3.2

**## What Platform are you on?** 
- [✅] iOS 13.3.1

**## What Language are you in?**
- [✅] React Native

**## Expected Behavior** 
https://lottiefiles.com/share/a41JI7

**## Actual Behavior**
Scan the expected behavior QR code with the LottieFiles app or ↓
Video previews (Lottie Files app iOS)
[Previews.zip](https://github.com/airbnb/lottie-ios/files/4308228/Previews.zip)
• Preview with gradient
• Preview with fills

**## Animation JSON**
[Animations_json.zip](https://github.com/airbnb/lottie-ios/files/4308244/Animations_json.zip)
• Animation with gradient 
• Animation with classical fills

Hi,

I work on After Effect CC 16.1.2 running with bodymovin 5.5.10 on a macOS 10.14.5 (18F132).

The animation I've created lag a lot on the Lottie Files app (iOS) and integrated in react native app on iOS (work really well on Android).
The animation works fine on the web preview and the Lottie Sample app (on iOS). 

I think it's related to the Gradient Fill. I tryed several ways to avoid this lags without any success (masks, paths, one gradient fill per layer, etc.) nothing works.

Once I replace the Gradient Fills with classical Fill on AE, the animation work well but do not provide me the expected animation.

> **Edit: The problem is linked to the relation between the path and the gradient. The gradient works well without editing the path on the timeline. However, I can't do the animation I want without editing the path...**

You'll find enclosed two vidéos of the same animation, one with gradients fills and the other one with classical fills. 

I hope you'll be able to help me.

Thanks in advance.

Best Regards.
Marc

**Comment by ynamite** [comment]
I'm experiencing similar issue. Animation is nice and smooth on all browsers except on iOS. 
Latest lottie, lattest AE, latest bodymovin.

**Comment by LoKiLyn** [comment]
Same problem here. All works well except iOS

**Comment by absolute-heike** [comment]
Hey, have you tried running the animation in Lottie `3.0.0 - 3.2.1`? And also tried running it in Lottie 2.x (ObjC version)? I am currently trying to figure out a rendering issue related to paths and gradients. Might be related to this 🤔

**Comment by Nathan765** [comment]
I have the same problem ...

**Comment by ynamite** [comment]
I managed to fix my problem back then by simplifying the animation. The result looked identical, but I used a much simpler approach that worked in my case. It's been a while so I don't recall what it was I changed, but basically: simplify (if possible).

**Comment by Nathan765** [comment]
Hi, my UI designer was forced to simplify too... thank you for answering ;)

**Comment by ynamite** [comment]
Sure, glad it worked :)

**Comment by calda** [comment]
Today we released Lottie 3.4.0 which includes a new rendering engine powered by Core Animation ([more details here](https://github.com/airbnb/lottie-ios/discussions/1627)). This new rendering engine has significantly better performance, and should resolve the performance issues folks have been encountering with the previous main thread rendering engine. Please try it out by setting the `LottieConfiguration.renderingEngine` feature flag, and feel free to report any new issues that you experience when using the new rendering engine.
