### ISSUE TITLE
iOS: Rounding of rectangle isn't capped to maximum half of width or height, it creates star like artifacting

### ISSUE THREAD

**Issue by sureMOE** [airbnb/lottie-ios#115]
If you have a square that is 10 pixels by 10 pixels and you have a rounded corner set to 50 pixels (which is something you do in AE to keep from having to adjust the rounding if you are creating capsules, rounded lines, circles that transition to squares, etc) Lottie on iOS renders the rounded corners based on actual number instead of half maximum rounding possible (in example above, a 10x10 square can have a maximum rounding of 5 per corner). 

The result is crazy artifacts that look like weird stars. Screenshots included below.

Could be resolved by capping maximum rounding at half of smallest dimension in either h or w.

![img_0304 png](https://cloud.githubusercontent.com/assets/18271665/23231183/b8551708-f8fb-11e6-9ea9-ea8ef0329e26.png)
![img_0303 png](https://cloud.githubusercontent.com/assets/18271665/23231182/b8545750-f8fb-11e6-8c7b-6c8fd8e0ae4a.png)

**Comment by buba447** [comment]
Thanks for spotting this! Ill had a quick fix!

**Comment by buba447** [comment]
Fixed on master! Will be bumping version later today.
