### ISSUE TITLE
Some functions in lottie take too much to compile

### ISSUE THREAD

**Issue by FranDepascuali** [airbnb/lottie-ios#1151]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.6

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

##  Bug 
We measure our compile times and Lottie takes too much time to compile.

```
132.39ms	/Users/vagrant/git/ios/Pods/lottie-ios/lottie-swift/src/Private/LayerContainers/CompLayers/TextCompositionLayer.swift:106:17	instance method displayContentsWithFrame(frame:forceUpdates:)
816.12ms	/Users/vagrant/git/ios/Pods/lottie-ios/lottie-swift/src/Public/Animation/AnimationPublic.swift:25:15	static method named(_:bundle:subdirectory:animationCache:)
[03:42:57]: Cruising back to lane 'ios measure_build_time' 🚘
```

**Comment by calda** [comment]
If you're still experiencing this, could you file a new issue with updated information?
