### ISSUE TITLE
[Question] Should we make PRs for 2.x improvements?

### ISSUE THREAD

**Issue by Cyberbeni** [airbnb/lottie-ios#1152]
We are currently using 2.x because of the performance issues with 3.x and we added base64 image handling to macOS (just a copy paste of the iOS one) in our private fork. Should we make pull requests from this and future changes we make to 2.x?

**Comment by buba447** [comment]
Yes!
There is a branch alive for official objc support. Please make PRs against it.

Learn more here
https://github.com/airbnb/lottie-ios/blob/master/README.md#objective-c-support
