### ISSUE TITLE
Animation doesn't display with Lottie 3.1.8 - previously it worked

### ISSUE THREAD

**Issue by bluelagon** [airbnb/lottie-ios#1158]
## This issue is a:
- Regression (Something that once worked, but doesn't work anymore)
I used to work with Lottie 2.5.2 and I just wanted to update to latest version (3.1.6) but the animation doesn't appear. To reproduce it, I simply did a new project on XCode an put the json animation and the xcassets in the project.  And I did:

```
class ViewController: UIViewController {
    let animationView = AnimationView(name: "loader")
    override func viewDidLoad() {
        super.viewDidLoad()
        self.view.addSubview(animationView)
        self.animationView.center = self.view.center
        self.animationView.play()
    }
}
```

## Which Version of Lottie are you using?
Lottie 3.1.6

## What Platform are you on? 
- iOS

## What Language are you in?
- Swift

<img width="302" alt="Capture d’écran 2020-03-26 à 08 54 41" src="https://user-images.githubusercontent.com/32433902/77623162-e2634200-6f3f-11ea-93c7-528c46062207.png">

And here is my files hierarchy in XCode:
<img width="327" alt="Capture d’écran 2020-03-26 à 09 01 28" src="https://user-images.githubusercontent.com/32433902/77623487-77663b00-6f40-11ea-93c8-02a0e380a1c4.png">

And Here is also, the begining of the loader.json, to have the version number:

```
{"v":"5.4.2","fr":29.9700012207031,"ip":0,"op":152.000006191087,"w":270,"h":270,"nm":"v4","ddd":0,"assets":[{"id":"image_0","w":39,"h":39,"u":"images/","p":"img_0.png","e":0},{"id":"image_1","w":39,"h":51,"u":"images/","p":"img_1.png","e":0},{"id":"image_2","w":153,"h":152,"u":"images/","p":"img_2.png","e":0},{"id":"image_3","w":39,"h":14,"u":"images/","p":"img_3.png","e":0},{"id":"image_4","w":39,"h":14,"u":"images/","p":"img_
```

**Comment by AngeloD2022** [comment]
Does your animation include a composition influencing another using track mattes?

**Comment by bluelagon** [comment]
How can I check that ? Is it possible to check it on the json file ? (I'm not the author of the animation)

**Comment by bluelagon** [comment]
I just tried with the 3.1.8, and still have the issue.  If it can help, here is a block of code that is repeated in my lottie json file:
```
["0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167"],"t":112,"s":[100,0,100],"e":[100,0,100]},{"t":114.000004643315}],"ix":6,"x":"var $bm_rt;\nvar amp, freq, decay, n, t, v;\ntry {\n    amp = div(effect('Echelle - Overshoot')('ADBE Slider Control-0001'), 2.5), freq = div(effect('Echelle - Bounce')('ADBE Slider Control-0001'), 20), decay = div(effect('Echelle - Friction')('ADBE Slider Control-0001'), 20), n = 0, 0 < numKeys && (n = nearestKey(time).index, key(n).time > time && n--), t = 0 === n ? 0 : sub(time, key(n).time), $bm_rt = 0 < n ? (v = velocityAtTime(sub(key(n).time, div(thisComp.frameDuration, 10))), sum(value, div(mul(mul(div(v, 100), amp), Math.sin(mul(mul(mul(freq, t), 2), Math.PI))), Math.exp(mul(decay, t))))) : value;\n} catch (e$$4) {\n    $bm_rt = value = value;\n}"}},"ao":0,"ip":0,"op":152.000006191087,"st":0,"bm":0},{"ddd":0,"ind":15,"ty":2,"nm":"Pin - 3","refId":"image_14","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r"
```

**Comment by buba447** [comment]
This animation has an expression in it. Expressions aren’t support by Lottie-iOS, nor have they ever been.

**Comment by bluelagon** [comment]
Thank you for your help.
