### ISSUE TITLE
Lottie not matching view scaling animation

### ISSUE THREAD

**Issue by marciogranzotto** [airbnb/lottie-ios#1161]
Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.6

## What Platform are you on? 

- [ ] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [ ] Objective-C

## Expected Behavior 
When the AnimationView is resized, the Lottie layer should match the animation. That does work now if the view animation is a CABasicAnimation. But if the animation is, for example, a CASpringAnimation, the layer animation will not match the view's animation.
I stumbled with this when using AnimationViews inside a UICollectionViewCell displayed on a Today Widget.
When the widget changes size, between compact and expanded mode, my cells are resized, and apparently it uses a CASpringAnimation.

## Actual Behavior
Here's what that animation looks like with the current version. I painted the AnimationView's background yellow to demonstrate the difference between the view and layer animation.

Normal animation speed:
![Screen Recording 2020-03-28 at 12 41 56_2](https://user-images.githubusercontent.com/11080704/77827282-70335e80-70f3-11ea-946e-fb40fd76d60d.gif)

Slow Animations turned on:
![Screen Recording 2020-03-28 at 12 41 56_4](https://user-images.githubusercontent.com/11080704/77827356-e3d56b80-70f3-11ea-8952-4922ceed8b9a.gif)

**Comment by codejun9527** [comment]
has the problem been solved?

**Comment by marciogranzotto** [comment]
@codejun9527 the PR #1163 fixes it
