### ISSUE TITLE
Background behavior seems to be ignored on release 3.1.6

### ISSUE THREAD

**Issue by maelorhan** [airbnb/lottie-ios#1168]
Hello ! I am reproducing a bug in Lottie, version 3.1.6, which I can't reproduce in 3.1.5 so I would assume it is a regression. I am creating an `AnimationView` instance, this way : 

```
let bundle = Bundle(for: AnimatedLogoComponent.self)
let animationView = AnimationView(name: "animation", bundle: bundle)
animationView.loopMode = .playOnce
animationView.backgroundBehavior = .pauseAndRestore
```

Then I'm playing the animation with a completion block, this way : 

```
animatedView.play { [weak self] _ in
  }
```

However, if my app is moving to background, when moving back to foreground, the animation is played again from the beginning. It seems that backgroundBehavior is ignored, and it wasn't the case before release 3.1.6.

Thanks for your help

## Check these before submitting:
- [ ] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [ ] Feature Request
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.6

## What Platform are you on? 

- [ ] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [ ] Objective-C

## Expected Behavior 

`backgroundBehavior` set to `.pauseAndRestore` should cause animation to be paused and to be resumed where it was paused

## Actual Behavior

`backgroundBehavior` set to `.pauseAndRestore` cause animation to be restarted from the beginning (like if we were setting it to `.pause` default value)

## Code Example

```
let bundle = Bundle(for: AnimatedLogoComponent.self)
let animationView = AnimationView(name: "animation", bundle: bundle)
animationView.loopMode = .playOnce
animationView.backgroundBehavior = .pauseAndRestore
```

Then I'm playing the animation with a completion block, this way : 

```
animationView.play { [weak self] _ in
  }
```

**Comment by calda** [comment]
Testing in our example app, this appears to work correctly in 3.4.1. If you're still experiencing this issue, could you share a sample project that demonstrates the problem?
