### ISSUE TITLE
Drop Shadows not rendering

### ISSUE THREAD

**Issue by ryejay** [airbnb/lottie-ios#1169]
## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [X] MacOS
- [] iOS

## What Language are you in?
- [] Swift
- [] Objective-C

## Expected Behavior 

<img width="313" alt="Screen Shot 2020-04-03 at 9 37 25 am" src="https://user-images.githubusercontent.com/37563359/78306512-49f83d80-758f-11ea-8d58-6291daa2b428.png">
<img width="464" alt="Screen Shot 2020-04-03 at 9 40 47 am" src="https://user-images.githubusercontent.com/37563359/78306519-4ebcf180-758f-11ea-8aa3-4c9dca38fc5a.png">

## Actual Behavior

<img width="757" alt="Screen Shot 2020-04-03 at 9 42 15 am" src="https://user-images.githubusercontent.com/37563359/78306570-7613be80-758f-11ea-8057-ee8480064e03.png">

## Animation JSON

Hey there, 
I have seen other similar issues been raised about the compatibility of drop shadows with Lottie. From what I have read, this is fine and is supported, as long as the Drop Shadow effect is used, and not the layer style. I have used this, but for some reason I am still not getting the drop shadow to render. Any ideas?

Appreciate any help :)

**Comment by alexanderkhitev** [comment]
Hey! Do you have any updates? Or did you solve this issue? Thanks!

**Comment by calda** [comment]
Drop shadows are currently not implemented on iOS. PRs are welcome!

**Comment by calda** [comment]
Added support for drop shadows in #2142
