### ISSUE TITLE
Illustrator files not accepted

### ISSUE THREAD

**Issue by aileenkassing** [airbnb/lottie-ios#1171]
Hi,

I'm trying to export a simple after effects composition as a Lottie file (no effects, no gradients, just paths scaling and content changing opacity).

I tried to find out what was wrong and eventually noticed that none of my Illustrator files are exportable as Lottie. I animated a simple circle (only changing position) and still I couldn't export it. Exporting paths that I created directly in AE as Lottie works.
I tried it with both the bodymovin and Lottie plugin. I will attach my files below and hope that someone can help me fix this issue.

I am working on a Mac Book Pro and have the latest versions of after effects and illustrator installed. 

Thanks for helping me!
Aileen

## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [x] MacOS
- [] iOS

## What Language are you in?
- [] Swift
- [] Objective-C

## Animation JSON

[Circle-test.zip](https://github.com/airbnb/lottie-ios/files/4426344/Circle-test.zip)
-- seems like .json, .ai etc. files are not supported, so I compressed them into a zip file --

**Comment by calda** [comment]
Closing since this looks related to the After Effects plugin and not the iOS library implementation
