### ISSUE TITLE
AnimationCompletionDelegate strong reference ?

### ISSUE THREAD

**Issue by DiwakarThapa** [airbnb/lottie-ios#1174]
I updated the lottie-ios version of the app from 3.1.5 to 3.1.6 ? and found that **AnimationCompletionDelegate** is creating strong reference. Is this a bug ?

**Comment by calda** [comment]
I'm going to close this issue since it's a few years old. Feel free to re-open the issue and provide more information if you think there's a bug here that we should fix.
