### ISSUE TITLE
AnimatedButton and Switch on OSX

### ISSUE THREAD

**Issue by mribeiro** [airbnb/lottie-ios#1175]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [x] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.6

## What Platform are you on? 

- [x] MacOS
- [] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 

`AnimatedButton` and `AnimatedSwitch` should be available in macOS development environment

## Actual Behavior

Apparently only `AnimationView` is available

## Code Example
```
import Lottie

// This works
let animationView = AnimationView()
// Does not work
let animationButton = AnimatedButton() // Use of unresolved identifier 'AnimatedButton'
let animationSwitch = AnimatedSwitch() // Use of unresolved identifier 'AnimatedSwitch'
```
## Animation JSON
Not needed

**Comment by calda** [comment]
Given these classes subclass `UIView` / `UIControl`, which are not available on macOS, I don't think we plan on supporting these on macOS.
