### ISSUE TITLE
Shatter animation wont preview JSON

### ISSUE THREAD

**Issue by tr8b5** [airbnb/lottie-ios#1179]
I installed and reinstalled Bodymovin and adobe flash twice. The same thing happened with each version.

I am able to preview lottie JSON animations but for some reason I am unable to view my own custom shatter animation JSON which I really need for my iphone game.

Please help. Zip attached.
[Shatter LongBar.aep.zip](https://github.com/airbnb/lottie-ios/files/4482085/Shatter.LongBar.aep.zip)

**Comment by calda** [comment]
Closing since this looks related to the After Effects plugin and not the Lottie iOS library. Feel free to reopen if you have a `.json` animation file that behaves incorrectly on iOS.
