### ISSUE TITLE
Lottie Animation Layer Not Scaling With UIView Via UIViewPropertyAnimator

### ISSUE THREAD

**Issue by AssyriaGameStudio** [airbnb/lottie-ios#1180]
From Lottie 3.1.3 - Present release (3.1.6 at the time of writing), it appears the lottie animation within a UIView isn't scaling with the view itself.

I'm attempting to animate a frame change of a Lottie view using UIViewPropertyAnimator, and while the UIView's frame animates as expected, the scale of the animated Lottie layer jumps to immediately be the width and height of the end-frame, and doesn't animate to match the view bounds.

The position does appear to animate correctly, it's only the scale / bounds that are incorrect.

## This issue is a:
- [👍] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [👍] iOS

## What Language are you in?
- [👍] Swift
- [] Objective-C

## Expected Behavior 
The actual lottie animated layer should scale with the UIView as part of the UIViewPropertyAnimator animiation.

## Code Example

```
// Lottie view is an AnimationView with a looping animation playing on it and content mode of "scaleToFill".

lottieView.frame = CGRect(x: 0, y: 0, width: 300, height: 300)

let animator = UIViewPropertyAnimator(duration: 0.5, curve: .easeInOut)
{
lottieView.frame = CGRect(x: 0, y: 0, width: 100, height: 100)
}

animator.startAnimation()
```
## Animation JSON
Applies to all animations.

**Comment by AssyriaGameStudio** [comment]
Just updating that this issue is still unresolved in lottie 3.1.8.

**Comment by calda** [comment]
Could you share a sample project that reproduces this issue?
