### ISSUE TITLE
Error while exporting 

### ISSUE THREAD

**Issue by AdidiF** [airbnb/lottie-ios#1181]
Hey,
I tried to export some kind of animation and I got this error message while exporting:
<img width="934" alt="צילום מסך 2020-04-16 ב-14 50 19" src="https://user-images.githubusercontent.com/63790139/79498874-b153ca00-8032-11ea-8902-ba35f148fd85.png">
 
and it showen it again and again, can you tell me please what can make this errors?
thank you 🙏

**Comment by calda** [comment]
Closing since this looks related to the After Effects plugin, not the iOS library implementation
