### ISSUE TITLE
Animation layers missing 3.1.5 -> 3.1.6

### ISSUE THREAD

**Issue by meteora8888** [airbnb/lottie-ios#1186]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.6
used to work on Lottie 3.1.5

## What Platform are you on? 

- [x] iOS

## What Language are you in?
- [x] Swift
## Expected Behavior 
Animation loads and runs with including all layers 

<img width="391" alt="Screenshot 2020-04-27 at 10 21 57" src="https://user-images.githubusercontent.com/33287058/80350398-f4067500-8870-11ea-9bb2-131ea6719f48.png">

## Actual Behavior
Animation loads and runs but on layers is missing. The pin is not part of the animation on the 3.1.6 version of the pod

<img width="592" alt="Screenshot 2020-04-27 at 10 17 19" src="https://user-images.githubusercontent.com/33287058/80350054-75113c80-8870-11ea-995e-40315fe82220.png">

## Code Example

<pre><code>
 private func setupAnimation() {
        if let filePath = Bundle.main.path(forResource: "locationAnimation", ofType: "json") {
           let animation = Animation.filepath(filePath)
           let animationView = AnimationView(animation: animation)
           animationView.animation = animation
           animationViewContainer.addSubview(animationView)
           animationView.backgroundBehavior = .pauseAndRestore
           animationView.translatesAutoresizingMaskIntoConstraints = false
           animationView.topAnchor.constraint(equalTo: animationViewContainer.layoutMarginsGuide.topAnchor).isActive = true
           animationView.leadingAnchor.constraint(equalTo: animationViewContainer.leadingAnchor).isActive = true
           animationView.trailingAnchor.constraint(equalTo: animationViewContainer.trailingAnchor).isActive = true
           animationView.bottomAnchor.constraint(equalTo: animationViewContainer.bottomAnchor).isActive = true
           animationView.loopMode = .loop
           animationView.play()
        }
    }

</code></pre>

## Animation JSON

{"v":"5.5.7","fr":25,"ip":0,"op":60,"w":595,"h":595,"nm":"Comp 1","ddd":0,"assets":[{"id":"comp_0","layers":[{"ddd":0,"ind":1,"ty":3,"nm":"Null 1","sr":1,"ks":{"o":{"a":0,"k":0,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":1,"k":[{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":13,"s":[600,600,0],"to":[0,-9.667,0],"ti":[0,0,0]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":27,"s":[600,542,0],"to":[0,0,0],"ti":[0,-9.667,0]},{"t":31,"s":[600,600,0]}],"ix":2},"a":{"a":0,"k":[0,0,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"ip":0,"op":750,"st":0,"bm":0},{"ddd":0,"ind":2,"ty":4,"nm":"Shape Layer 1","td":1,"sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":1,"k":[{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":17,"s":[602.471,543.062,0],"to":[0,0,0],"ti":[0,0,0]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":28,"s":[602.471,532.062,0],"to":[0,0,0],"ti":[0,0,0]},{"t":31,"s":[602.471,541.1,0]}],"ix":2},"a":{"a":0,"k":[-12,12,0],"ix":1},"s":{"a":0,"k":[40,40,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":1,"k":[{"i":{"x":0.655,"y":0.897},"o":{"x":0.264,"y":0.147},"t":0.206,"s":[{"i":[[56.652,0],[0,-56.652],[-56.652,0],[0,56.652]],"o":[[-56.652,0],[0,56.652],[56.652,0],[0,-56.652]],"v":[[0,-102.578],[-102.578,0],[0,102.578],[102.578,0]],"c":true}]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0.094},"t":12.138,"s":[{"i":[[56.652,0],[0,-56.652],[-56.652,0],[0,56.652]],"o":[[-56.652,0],[0,56.652],[56.652,0],[0,-56.652]],"v":[[0,-52.578],[-102.578,50],[0,102.578],[102.578,50]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.333,"y":0},"t":22,"s":[{"i":[[56.652,0],[0,-56.652],[-56.652,0],[0,56.652]],"o":[[-56.652,0],[0,56.652],[56.652,0],[0,-56.652]],"v":[[0,-83.366],[-102.578,31.712],[0,127.578],[102.578,21.712]],"c":true}]},{"i":{"x":0.98,"y":0},"o":{"x":0.167,"y":0.167},"t":26,"s":[{"i":[[56.652,0],[0,-56.652],[-56.652,0],[0,56.652]],"o":[[-56.652,0],[0,56.652],[56.652,0],[0,-56.652]],"v":[[0,-84.333],[-102.578,30.117],[0,126.32],[102.578,20.62]],"c":true}]},{"t":30.890625,"s":[{"i":[[56.652,0],[0,-56.652],[-56.652,0],[0,56.652]],"o":[[-56.652,0],[0,56.652],[56.652,0],[0,-56.652]],"v":[[0,-102.578],[-102.578,0],[0,102.578],[102.578,0]],"c":true}]}],"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"st","c":{"a":0,"k":[0.783134011661,0.783134011661,0.783134011661,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":0,"ix":5},"lc":1,"lj":1,"ml":4,"bm":0,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"fl","c":{"a":0,"k":[0,0,0,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":1,"k":[{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":12,"s":[-15.294,84.938],"to":[0,-19.189],"ti":[0,5.181]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":26,"s":[-15.294,-30.195],"to":[0,-10.6],"ti":[0,-18.443]},{"t":31.1826171875,"s":[-15.294,80.461]}],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Ellipse 1","np":3,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":750,"st":0,"bm":0},{"ddd":0,"ind":3,"ty":4,"nm":"Shape Layer 2","parent":1,"tt":2,"sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":1,"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":0,"s":[2.002,-71,0],"to":[0,5.5,0],"ti":[0,-5.5,0]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":24,"s":[2.002,-38,0],"to":[0,0,0],"ti":[0,0,0]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":28,"s":[2.002,-38,0],"to":[0,-5.5,0],"ti":[0,5.5,0]},{"t":31,"s":[2.002,-71,0]}],"ix":2},"a":{"a":0,"k":[-12,12,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":1,"k":[{"i":{"x":0.655,"y":0.897},"o":{"x":0.253,"y":0.151},"t":0.206,"s":[{"i":[[56.652,0],[0,-56.652],[-56.652,0],[0,56.652]],"o":[[-56.652,0],[0,56.652],[56.652,0],[0,-56.652]],"v":[[0,-102.578],[-102.578,0],[0.628,212.578],[102.578,0]],"c":true}]},{"i":{"x":0.667,"y":0.827},"o":{"x":0.333,"y":0.1},"t":12.137,"s":[{"i":[[56.652,0],[0,-56.652],[-56.652,0],[0,56.652]],"o":[[-56.652,0],[0,56.652],[56.652,0],[0,-56.652]],"v":[[0,-60.578],[-102.578,42],[0.628,212.578],[102.578,42]],"c":true}]},{"i":{"x":0.667,"y":0.879},"o":{"x":0.333,"y":0.164},"t":23.241,"s":[{"i":[[56.652,0],[0,-56.652],[-56.652,0],[0,56.652]],"o":[[-56.652,0],[0,56.652],[56.652,0],[0,-56.652]],"v":[[0,-122.578],[-102.578,-20],[0.628,212.578],[102.578,-20]],"c":true}]},{"t":30.8212890625,"s":[{"i":[[56.652,0],[0,-56.652],[-56.652,0],[0,56.652]],"o":[[-56.652,0],[0,56.652],[56.652,0],[0,-56.652]],"v":[[0,-102.578],[-102.578,0],[0.628,212.578],[102.578,0]],"c":true}]}],"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":0,"k":[0.513725490196,0.352941176471,0.847058823529,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[-14.669,13],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Ellipse 1","np":2,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":750,"st":0,"bm":0}]}],"layers":[{"ddd":0,"ind":1,"ty":0,"nm":"Pin","refId":"comp_0","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[297.5,225.5,0],"ix":2},"a":{"a":0,"k":[600,600,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"w":1200,"h":1200,"ip":30,"op":60,"st":30,"bm":0},{"ddd":0,"ind":2,"ty":0,"nm":"Pin","refId":"comp_0","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[297.5,225.5,0],"ix":2},"a":{"a":0,"k":[600,600,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"w":1200,"h":1200,"ip":0,"op":30,"st":0,"bm":0},{"ddd":0,"ind":3,"ty":4,"nm":"Shape Layer 4","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[272.075,189.5,0],"ix":2},"a":{"a":0,"k":[0,0,0],"ix":1},"s":{"a":0,"k":[131.234,131.234,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[77.71,0],[0,-20.687],[-77.71,0],[0,20.687]],"o":[[-77.71,0],[0,20.687],[77.71,0],[0,-20.687]],"v":[[0,-37.457],[-140.707,0],[0,37.457],[140.707,0]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"st","c":{"a":0,"k":[0.133333333333,0.698039215686,0.627450980392,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":11,"ix":5},"lc":2,"lj":2,"bm":0,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"tr","p":{"a":0,"k":[19.374,142.543],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":-102600,"ix":6},"o":{"a":1,"k":[{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":52,"s":[100]},{"t":54,"s":[0]}],"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":33433,"ix":5},"nm":"Transform"}],"nm":"Ellipse 1","np":2,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false},{"ty":"gr","it":[{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":-102600,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Group 1","np":0,"cix":2,"bm":0,"ix":2,"mn":"ADBE Vector Group","hd":false},{"ty":"tm","s":{"a":1,"k":[{"i":{"x":[0.667],"y":[0.776]},"o":{"x":[0.333],"y":[0]},"t":24,"s":[100]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0.43]},"t":27,"s":[63.482]},{"t":37,"s":[0]}],"ix":1},"e":{"a":1,"k":[{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":10,"s":[100]},{"t":35,"s":[0]}],"ix":2},"o":{"a":0,"k":15,"ix":3},"m":1,"ix":3,"nm":"Trim Paths 1","mn":"ADBE Vector Filter - Trim","hd":false}],"ip":10,"op":47,"st":10,"bm":0},{"ddd":0,"ind":4,"ty":4,"nm":"Shape Layer 3","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[272.075,189.5,0],"ix":2},"a":{"a":0,"k":[0,0,0],"ix":1},"s":{"a":0,"k":[131.234,131.234,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[77.71,0],[0,-20.687],[-77.71,0],[0,20.687]],"o":[[-77.71,0],[0,20.687],[77.71,0],[0,-20.687]],"v":[[0,-37.457],[-140.707,0],[0,37.457],[140.707,0]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"st","c":{"a":0,"k":[0.133333333333,0.698039215686,0.627450980392,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":11,"ix":5},"lc":2,"lj":2,"bm":0,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"tr","p":{"a":0,"k":[19.374,142.543],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":-102600,"ix":6},"o":{"a":1,"k":[{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":42,"s":[100]},{"t":44,"s":[0]}],"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":33433,"ix":5},"nm":"Transform"}],"nm":"Ellipse 1","np":2,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false},{"ty":"gr","it":[{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":-102600,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Group 1","np":0,"cix":2,"bm":0,"ix":2,"mn":"ADBE Vector Group","hd":false},{"ty":"tm","s":{"a":1,"k":[{"i":{"x":[0.667],"y":[0.776]},"o":{"x":[0.333],"y":[0]},"t":14,"s":[100]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0.43]},"t":17,"s":[63.482]},{"t":27,"s":[0]}],"ix":1},"e":{"a":1,"k":[{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":0,"s":[100]},{"t":25,"s":[0]}],"ix":2},"o":{"a":0,"k":15,"ix":3},"m":1,"ix":3,"nm":"Trim Paths 1","mn":"ADBE Vector Filter - Trim","hd":false}],"ip":0,"op":37,"st":0,"bm":0},{"ddd":0,"ind":5,"ty":4,"nm":"Shape Layer 2","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[382.969,99.5,0],"ix":2},"a":{"a":0,"k":[0,0,0],"ix":1},"s":{"a":0,"k":[147.368,147.368,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[86.894,0],[0,-86.894],[-86.894,0],[0,86.894]],"o":[[-86.894,0],[0,86.894],[86.894,0],[0,-86.894]],"v":[[0,-157.336],[-157.336,0],[0,157.336],[157.336,0]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"st","c":{"a":0,"k":[0.133333333333,0.698039215686,0.627450980392,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":0,"ix":5},"lc":1,"lj":1,"ml":4,"bm":0,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"fl","c":{"a":0,"k":[0.890196078431,0.898039215686,0.905882352941,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[-57.997,159.336],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Ellipse 1","np":3,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":-9,"op":60,"st":6,"bm":0}],"markers":[{"tm":97,"cm":"1","dr":0}]}

**Comment by jannisnikoy** [comment]
Same for me, certain animations have layers missing. Tested on 3.1.8, though on 3.1.5 the same issue occurs for me

**Comment by calda** [comment]
Looks like this animation renders correctly in the latest version of Lottie:

<img src="https://user-images.githubusercontent.com/1811727/183763482-355e9ac7-4878-4d61-af98-0b843dc3c8fa.png" width=350>
