### ISSUE TITLE
Add a background behavior to allow an AnimationView to continue animating even after leaving the window

### ISSUE THREAD

**Issue by dfowjGH** [airbnb/lottie-ios#1188]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Feature Request

## Which Version of Lottie are you using?

Lottie 3.1.5

## What Platform are you on?
- [x] iOS

## What Language are you in?
- [x] Swift

## Expected Behavior 
There should be a `backgroundBehavior` option on `AnimationView` such that the animation continues playing even when removed from a window. 

This would allow an animation view to change superviews (being removed from one and added to another) without a glitch or loss of smoothness in the animation.

## Actual Behavior
When an animation view changes superviews while running and using the `.pauseAndRestore` background behavior, there is a small "hitch" in the animation presumably caused by the animation pausing when leaving the window, and then resuming when being re-added.

## Code Example
- I can provide an example if needed

## Animation JSON
n/a

**Comment by calda** [comment]
`LottieBackgroundBehavior.continuePlaying` behaves this way (and is the default behavior when using the new Core Animation rendering engine.
