### ISSUE TITLE
Animation layer wont be set in background sometime

### ISSUE THREAD

**Issue by seanliu1** [airbnb/lottie-ios#1189]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.3

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 
Animation should be reset even in background

## Actual Behavior
We have a video player which a button to play or pause using lottie 
We support airplay and remote command center, we found that if we try to set animation in background mode, due to user action using command center. The app's animation wont be set correctly sometime```

var state: PlayPauseState = .playing {
        didSet {
            guard oldValue != state else { return }
            if state == .playing {
                animationView.animation = Animation.Name.playToPause
            } else {
                animationView.animation = Animation.Name.pauseToPlay
            }
            animationView.play()
        }
    }
```

**Comment by calda** [comment]
Could you share a sample project that reproduces this issue?
