### ISSUE TITLE
Add support for gradients

### ISSUE THREAD

**Issue by colasbd** [airbnb/lottie-ios#119]
Supporting gradients would be great! 

Is it difficult? Do you plan supporting it soon?

**Comment by buba447** [comment]
@colasbd Gradient support is on our roadmap for version 2!
We are finishing up Precomp support now :)

**Comment by dong108** [comment]
Nice,wish it will be soon

**Comment by colasbd** [comment]
@buba447 What's Precomp?
Do you have any rough idea on when the v2 will be available? (1 week, 1 month, 3 months,...)
Thanks for Lottie! 
I guess many developers and designers rely on your great work :+1: !

**Comment by reddigfabian** [comment]
Looks like the latest Android version for Lottie has this support. Any info on whether or not the iOS version is caught up to that?

**Comment by boemekeld** [comment]
Any news? Can I have acess to Precomp?

**Comment by mradzinski** [comment]
Any news on this one @buba447? We are currently developing a project and would be great (and a life saver) to integrate Lottie in it :blush:

**Comment by lucasnachtigall** [comment]
Any news on the release ?

**Comment by stephenkopylov** [comment]
Waitin for it!

**Comment by boemekeld** [comment]
any news, please?

**Comment by allenwong** [comment]
Still waiting for it !!!!

**Comment by buba447** [comment]
Lottie V2 is out! We have added support for Linear gradients! Radial TBD

**Comment by BalzacV** [comment]
Hi guys. I have problem with gradients. Im exporting linear and radial gradients but they doesn't work.

**Comment by buba447** [comment]
@BalzacV Can you share an example? Gradients should be supported in the latest version of lottie.

**Comment by BalzacV** [comment]
@buba447 well we figure out that there are few issues. First the gradient need to be in RGB. We've tested it on simple square, without animation. It work now. But also we've change to RGB on more complex animations and it dosn't work. I will update the post and share results.

**Comment by twowei** [comment]
https://share.haiku.ai/19f63773-578d-4ec1-8dbb-dadacc86a579/latest
This example is made by Haiku, seems like the liner gradients doesn't work.
