### ISSUE TITLE
Error occurred while trying to install by cocoapod

### ISSUE THREAD

**Issue by geomrmx** [airbnb/lottie-ios#1192]
`pod install` with this library by pod **'lottie-ios'** is failed. I installed latest cocoapods and tried `pod install --repo-update` as well, but same result. Please look at the attached screenshot.

![error](https://user-images.githubusercontent.com/36443286/81708512-e1766900-9436-11ea-8318-85bbba53ec97.png)

**Comment by calda** [comment]
Closing since this looks like an issue with the CocoaPods command line tool and not Lottie itself
