### ISSUE TITLE
Trim Path animation stutter

### ISSUE THREAD

**Issue by ghost** [airbnb/lottie-ios#1197]
## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.8

## What Platform are you on? 
- [] iOS

## What Language are you in?
- [] Swift
- [] Objective-C

## Expected Behavior 
Smooth animation of trim path.

[Lines-D_AE.mp4.zip](https://github.com/airbnb/lottie-ios/files/4629988/Lines-D_AE.mp4.zip)

## Actual Behavior
I get a stutter kind of movement movement at the beginning of the key frame and the end. (Only on the iphone)
[RPReplay_Final1589477061.MP4.zip](https://github.com/airbnb/lottie-ios/files/4629994/RPReplay_Final1589477061.MP4.zip)

## Animation JSON

[Lines-D.json.zip](https://github.com/airbnb/lottie-ios/files/4629980/Lines-D.json.zip)

**Comment by calda** [comment]
Today we released Lottie 3.4.0 which includes a new rendering engine powered by Core Animation ([more details here](https://github.com/airbnb/lottie-ios/discussions/1627)). This new rendering engine has significantly better performance, and should resolve the performance issues folks have been encountering with the previous main thread rendering engine. Please try it out by setting the `LottieConfiguration.renderingEngine` feature flag, and feel free to report any new issues that you experience when using the new rendering engine.
