### ISSUE TITLE
Part of animation not displayed

### ISSUE THREAD

**Issue by VadimSos** [airbnb/lottie-ios#1199]
## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)

## Which Version of Lottie are you using?
Lottie 3.1.8

## What Platform are you on? 

- [] iOS

## What Language are you in?
- [] Swift

## Expected Behavior 

[expected_video.mp4.zip](https://github.com/airbnb/lottie-ios/files/4655600/expected_video.mp4.zip)

## Actual Behavior

[actual_video.mp4.zip](https://github.com/airbnb/lottie-ios/files/4655608/actual_video.mp4.zip)

## Code Example
let lottieView = AnimationView()
lottieView.animation = Animation.named("splash")
lottieView.frame.size = animationView.frame.size
lottieView.contentMode = .scaleAspectFit
lottieView.loopMode = .playOnce
animationView.addSubview(lottieView)
lottieView.play()

## Animation JSON

[splash.json.zip](https://github.com/airbnb/lottie-ios/files/4655610/splash.json.zip)

**Comment by demoker** [comment]
me too

**Comment by jannisnikoy** [comment]
What is the size of the json file for this? I actually landed here looking for the same answer as I experienced the same issues. Noticably, it seem large json files are causing these issues. From various animations in the app I'm working on, it's only the ones that are at least 250kb or higher that seem to have issues.

**Comment by jannisnikoy** [comment]
Just noticed you've attached the json to the issue, looks like it's only 6kb.. so much for my theory that file size had anything to do with it...

**Comment by demoker** [comment]
It's only 59kb, as in Lottie editor it works fine,
Is it because there is an expression in the animation file？

**Comment by demoker** [comment]
and in android is fine

**Comment by kizitonwose** [comment]
I have this issue as well in ` 3.1.8`. I kept downgrading/testing and the issue persisted until I got to `3.1.5` which works perfectly. So it looks like something broke in the `3.1.6` release.

**Comment by mattwhitlock** [comment]
3.15 -> 3.1.6 broke display of some layers.
See issue #1186

**Comment by MattSkala** [comment]
We have a similar issue with the following animation: https://lottiefiles.com/share/jmlp7okg
The result on iOS, where the line animation is missing: https://user-images.githubusercontent.com/1122874/104896921-0df46480-5978-11eb-8eb7-2404e23e89d6.mov

We are using Lottie 3.1.9, and downgrading to 3.1.5 did not solve the issue.

**Comment by sebbbbbb** [comment]
Hello, i got a similar issue and i had to downgrade to 3.1.5 too.

I did a diff between 3.1.5 and 3.1.6 and the commmit 6ede9ee115afc1114f8babe0f10f1217879fa0b7 seem to be responsible of this issue.

**Comment by Maddoc42** [comment]
@sebbbbbb reverting that commit on 3.1.9 did solve this issue for us! Thanks for the pointer.

In case anyone needs it, a `patch-package` patch

`patches/lottie-ios+3.1.9.patch`
```
diff --git a/node_modules/lottie-ios/lottie-swift/src/Private/LayerContainers/CompLayers/PreCompositionLayer.swift b/node_modules/lottie-ios/lottie-swift/src/Private/LayerContainers/CompLayers/PreCompositionLayer.swift
index eb2b29c..576ba24 100644
--- a/node_modules/lottie-ios/lottie-swift/src/Private/LayerContainers/CompLayers/PreCompositionLayer.swift
+++ b/node_modules/lottie-ios/lottie-swift/src/Private/LayerContainers/CompLayers/PreCompositionLayer.swift
@@ -29,8 +29,8 @@ final class PreCompositionLayer: CompositionLayer {
     }
     self.frameRate = frameRate
     super.init(layer: precomp, size: CGSize(width: precomp.width, height: precomp.height))
-    contentsLayer.masksToBounds = true
-    contentsLayer.bounds = CGRect(origin: .zero, size: CGSize(width: precomp.width, height: precomp.height))
+    masksToBounds = true
+    bounds = CGRect(origin: .zero, size: CGSize(width: precomp.width, height: precomp.height))
     
     let layers = asset.layers.initializeCompositionLayers(assetLibrary: assetLibrary, layerImageProvider: layerImageProvider, textProvider: textProvider,  fontProvider: fontProvider, frameRate: frameRate)
```

**Comment by eybeestudios** [comment]
> @sebbbbbb reverting that commit on 3.1.9 did solve this issue for us! Thanks for the pointer.
> 
> In case anyone needs it, a `patch-package` patch
> 
> `patches/lottie-ios+3.1.9.patch`
> 
> ```
> diff --git a/node_modules/lottie-ios/lottie-swift/src/Private/LayerContainers/CompLayers/PreCompositionLayer.swift b/node_modules/lottie-ios/lottie-swift/src/Private/LayerContainers/CompLayers/PreCompositionLayer.swift
> index eb2b29c..576ba24 100644
> --- a/node_modules/lottie-ios/lottie-swift/src/Private/LayerContainers/CompLayers/PreCompositionLayer.swift
> +++ b/node_modules/lottie-ios/lottie-swift/src/Private/LayerContainers/CompLayers/PreCompositionLayer.swift
> @@ -29,8 +29,8 @@ final class PreCompositionLayer: CompositionLayer {
>      }
>      self.frameRate = frameRate
>      super.init(layer: precomp, size: CGSize(width: precomp.width, height: precomp.height))
> -    contentsLayer.masksToBounds = true
> -    contentsLayer.bounds = CGRect(origin: .zero, size: CGSize(width: precomp.width, height: precomp.height))
> +    masksToBounds = true
> +    bounds = CGRect(origin: .zero, size: CGSize(width: precomp.width, height: precomp.height))
>      
>      let layers = asset.layers.initializeCompositionLayers(assetLibrary: assetLibrary, layerImageProvider: layerImageProvider, textProvider: textProvider,  fontProvider: fontProvider, frameRate: frameRate)
> ```

This patch let my missing animation layers appear!

**Comment by calda** [comment]
This animation works correctly now when I test it on 4.1.2:

<img src="https://user-images.githubusercontent.com/1811727/214173563-74ac2f89-e123-466a-b319-166f46e5df6b.png" width=350>
