### ISSUE TITLE
iOS & Android Request: Can we have a full screen mode in both players?

### ISSUE THREAD

**Issue by sureMOE** [airbnb/lottie-ios#120]
Then we can test animations at full bleed which will work great for splash animations. Also, there's inconsistency in the player behavior. On iOS, the player you compile has full screen, but can't hide the bottom bar. The Android player doesn't have full screen or a way to hide the bars. 

Thanks for all the awesome work on this!

**Comment by buba447** [comment]
We are currently working on a mac app for previewing! 
I don't have any currently plans to maintain the example iOS browser in the near future.
