### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by JLLJHD** [airbnb/lottie-ios#1200]
## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [✅] iOS

## What Language are you in?
- [✅] Swift
- [] Objective-C

## Code Example
    self.layerImageProvider = LayerImageProvider(imageProvider: imageProvider, assets: animation.assetLibrary?.imageAssets)
iOS 9.x 版本闪退 野指针

**Comment by CodeOcenS** [comment]
I get same trouble
the Xcode version is 11.5/11.3.1

**Comment by calda** [comment]
Closing since Lottie no longer supports iOS 9
