### ISSUE TITLE
Animation not playing completely in 3.1.0

### ISSUE THREAD

**Issue by SebRut** [airbnb/lottie-ios#1203]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.0

## What Platform are you on? 

- [x] iOS

## What Language are you in?
- [x] Swift

## Expected Behavior 
The animation should be played completely.

## Actual Behavior
The animation isn't played completely in Lottie 3.1.0 or newer but works fine in Lottie 3.0.3.

## Animation JSON
Privately shared via mail.

**Comment by calda** [comment]
Could you share a copy of your animation json?
