### ISSUE TITLE
SPM Related Issue with Designables Build Failed

### ISSUE THREAD

**Issue by omartan** [airbnb/lottie-ios#1205]
Lottie 3.1.8
iOS13
Xcode 11.5

So I initially did my code with Cocoa Pods and Designables was Successful, but because I'm not a fan of CP too much, I decided to use SPM, only to find out that with the same code, for some reason I get this, thoughts?

<img width="273" alt="Screenshot 2020-05-31 at 02 48 15" src="https://user-images.githubusercontent.com/12379413/83336866-7f987900-a2e9-11ea-959a-b198b5867c1f.png">

If I leave it `Class` and `Module` blank, it'll crash and give this error

<img width="1035" alt="Screenshot 2020-05-31 at 02 53 07" src="https://user-images.githubusercontent.com/12379413/83337032-a3a88a00-a2ea-11ea-96a5-5f9511185a4d.png">

**Comment by guillevc** [comment]
Having the same issue, did you find any solution?

**Comment by calda** [comment]
Could you share a sample project that reproduces this issue?
