### ISSUE TITLE
Animation is playing different on iOS and Android/Preview

### ISSUE THREAD

**Issue by alexpapanis** [airbnb/lottie-ios#1209]
## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.8

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 
all the rays of the sun should appear....
![Captura de Tela 2020-06-04 às 15 14 42](https://user-images.githubusercontent.com/1793731/83795823-6dfefa80-a676-11ea-8128-fed1fd918377.png)

## Actual Behavior
But only the upper ray appears. The same JSON file works perfectly on Android or Preview on Lottie website.

<img width="108" alt="Captura de Tela 2020-06-04 às 15 16 41" src="https://user-images.githubusercontent.com/1793731/83795827-6fc8be00-a676-11ea-8822-c1a492189502.png">

## Animation JSON
https://lottiefiles.com/share/XA5lBH

[processingOrder.json.zip](https://github.com/airbnb/lottie-ios/files/4732026/processingOrder.json.zip)

**Comment by avlonder** [comment]
same here with https://lottiefiles.com/1801-fireworks

**Comment by alexpapanis** [comment]
Thanks a lot, @avlonder . I was wondering the problem was that. iOS library doesn't support Repeater.

**Comment by fvermeulen** [comment]
This one as well
https://lottiefiles.com/7181-burst?lang=de
