### ISSUE TITLE
Feature Request: `AnimationFontProvider`

### ISSUE THREAD

**Issue by eric-robinson** [airbnb/lottie-ios#1212]
## Check these before submitting:
- [✔️] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [✔️] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1

## What Platform are you on? 

- [✔️] MacOS
- [✔️] iOS

## What Language are you in?
- [✔️] Swift
- [✔️] Objective-C

## Request Details
 
We have a need to support dynamic fonts in Lottie animations. We've been able to accomplish this by rewriting the Bodymovin JSON before loading it into an `AnimationView`, but Lottie framework support for this would be an improvement to our design.

To support this, a new `AnimationFontProvider` is requested, which would follow a similar pattern to `AnimationTextProvider`:

```swift
/**
 Font provider is a protocol that is used to supply fonts to `AnimationView`.
 */
protocol AnimationFontProvider {
	func fontFor(
		keypathName: String, 
		sourceFont: CTFont, 
		sourceText: String, 
		targetSize: CGSize
	) -> CTFont
}
```

This would be added as a property on `AnimationView`:

```swift
public var fontProvider: AnimationFontProvider
```

The `AnimationFontProvider` should be queried after the `AnimationTextProvider` in `TextCompositionLayer`. This will allow the final `sourceText` to be used in font selection, such as supplying the best fitting font for the dynamic text at the provided `taregetSize`.

Thank you for considering this!

**Comment by buba447** [comment]
Fixed by https://github.com/airbnb/lottie-ios/pull/1243

**Comment by roimulia2** [comment]
Can you share an example of the usage? I'm trying to change the font of this animation: https://lottiefiles.com/68713-secuence-motion-text  for two days. Pretty much feel stuck and I couldn't find any related resources. 

Thank you so much!

**Comment by roimulia2** [comment]
I opened an issue here: https://github.com/airbnb/lottie-ios/issues/1546 @buba447  @eric-robinson
