### ISSUE TITLE
Animation flickering on iOS 

### ISSUE THREAD

**Issue by vntguca** [airbnb/lottie-ios#1213]
## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.8

## What Platform are you on? 

- [] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift
- [] Objective-C

## Expected Behavior 
Animation pulse normally, no flickering up and down as on Android and Web

![expected](https://user-images.githubusercontent.com/18052572/85332750-e35c2f00-b4ae-11ea-9479-181b921e0488.gif)

## Actual Behavior
Image flickers up and down while animating
![ios_issue](https://user-images.githubusercontent.com/18052572/85332708-cb84ab00-b4ae-11ea-980e-50e1df904d7a.gif)

## Animation JSON

https://lottiefiles.com/share/YTP9Sf
[anim.json.zip](https://github.com/airbnb/lottie-ios/files/4815491/anim.json.zip)

**Comment by CellularDoor** [comment]
Hi Vntguca!
Have you figured out what caused this lag?
I have the same problem..

**Comment by vntguca** [comment]
No luck yet @CellularDoor

**Comment by RockyAo** [comment]
same problem.

**Comment by kapsyst** [comment]
Same issue here.

**Comment by RockyAo** [comment]
#1227 

try this answers, it's works for me

**Comment by calda** [comment]
Today we released Lottie 3.4.0 which includes a new rendering engine powered by Core Animation ([more details here](https://github.com/airbnb/lottie-ios/discussions/1627)). This new rendering engine has significantly better performance, and should resolve the performance issues folks have been encountering with the previous main thread rendering engine. Please try it out by setting the `LottieConfiguration.renderingEngine` feature flag, and feel free to report any new issues that you experience when using the new rendering engine.
