### ISSUE TITLE
Fail to build app in Xcode 12

### ISSUE THREAD

**Issue by ricardohochman** [airbnb/lottie-ios#1214]
## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [ ] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [ ] Feature Request
- [X] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.8

## What Platform are you on? 

- [ ] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift
- [ ] Objective-C

## Expected Behavior 
Project building successfully

## Actual Behavior
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/10833188/85423639-51efca00-b54d-11ea-93e4-0f4003dc77b2.png">

```
Undefined symbols for architecture armv7:
  "type metadata for Swift._StringObject.Variant", referenced from:
      outlined init with take of Swift._StringObject.Variant in AnimationKeypathExtension.o
ld: symbol(s) not found for architecture armv7
```

Xcode Version 12.0 beta (12A6159)

**Comment by danl3v** [comment]
In beta 1, we found that substrings seem to have issues compiling. We could get it building by updating 

`func equalsKeypath(_ keyname: String) -> Bool` - if you wrap the prefix and suffix methods with `String()`, we were then able to build

**Comment by danl3v** [comment]
https://github.com/airbnb/lottie-ios/pull/1215

**Comment by m760622** [comment]
I fixed it by going to the **Build Settings ** for **Lottie-ios**  Deployment  and changed the **iOS Deployment Target** to iOS 13

**Comment by danl3v** [comment]
This is fixed in Xcode 12 beta 4 and the PR can be reverted

**Comment by calda** [comment]
Closing since this seems like a potentially outdated issue. Feel free to re-open if you're still experiencing this issue.

**Comment by Harry-KNIGHT** [comment]
I got this issue
