### ISSUE TITLE
Lottie moves slow between two loops

### ISSUE THREAD

**Issue by ACommonChinese** [airbnb/lottie-ios#1216]
I did try Swift and Objective-C on iOS, shows one issue both, Take Objective-C for example:

    [_lottieView setAnimationNamed:@"myLottie.json" inBundle:[NSBundle mainBundle]];
    _lottieView.loopAnimation = YES;
    [_lottieView play];

The lottie works well, but after end of whole animation and start again(loopAnimation = YES), there are always a pause between them (lotie moves slow than normal), the lottie works well in web-lottie and android-lottie

**Comment by tinjurko** [comment]
Same here!

**Comment by calda** [comment]
Today we released Lottie 3.4.0 which includes a new rendering engine powered by Core Animation ([more details here](https://github.com/airbnb/lottie-ios/discussions/1627)). This new rendering engine has significantly better performance, and should resolve the performance issues folks have been encountering with the previous main thread rendering engine. Please try it out by setting the `LottieConfiguration.renderingEngine` feature flag, and feel free to report any new issues that you experience when using the new rendering engine.
