### ISSUE TITLE
Text Path iOS

### ISSUE THREAD

**Issue by DSalman** [airbnb/lottie-ios#1217]
## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [x] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 

![Screen Shot 2020-06-29 at 8 32 51 AM](https://user-images.githubusercontent.com/1105016/86006082-78958100-b9e3-11ea-9e1f-ecb6c8bc60b1.png)

## Actual Behavior

![Screen Shot 2020-06-29 at 8 36 05 AM](https://user-images.githubusercontent.com/1105016/86006200-9f53b780-b9e3-11ea-8d94-85596b5ed9e7.png)

## Code Example

[data.json.zip](https://github.com/airbnb/lottie-ios/files/4845519/data.json.zip)

**Comment by calda** [comment]
Lottie doesn't support text paths on iOS: http://airbnb.io/lottie/#/supported-features
