### ISSUE TITLE
Animation doesn't play

### ISSUE THREAD

**Issue by DSalman** [airbnb/lottie-ios#1218]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 

[FA Intro.mov.zip](https://github.com/airbnb/lottie-ios/files/4851412/FA.Intro.mov.zip)

## Animation JSON

[Archive.zip](https://github.com/airbnb/lottie-ios/files/4851417/Archive.zip)

Capture is from LottieWeb, the native (iOS) version does play at all. This might actually be a feature request rather than a bug.

**Comment by calda** [comment]
It looks like this animation probably uses unsupported text layer features: https://airbnb.io/lottie/#/supported-features
