### ISSUE TITLE
Lottie invalid if have image

### ISSUE THREAD

**Issue by ACommonChinese** [airbnb/lottie-ios#1220]
new swift version, if lottie json file use images, and the images within an directory, Lottie is invalid:
```
let animation = Animation.named("Boat_Loader", subdirectory: "TestAnimations") # If Boat_Loader used image, it will not play
animationView.animation = animation
animationView.play()
```

From source code, the BundleImageProvider always read file from Bundle.main, if the image is not in main bundle, it fails got them

**Comment by ACommonChinese** [comment]
BundleImageProvider

**Comment by YGEqual** [comment]
> BundleImageProvider

How do?
