### ISSUE TITLE
Json files is taking more time to load(Approximately 1.7 secounds)

### ISSUE THREAD

**Issue by dayakar06** [airbnb/lottie-ios#1224]
Hi Folks,

Here in my current application am using the Lottie json files for animations, json file size is 1.2mb. which is loading quite good in lottie preview website.

When i'm integrating the lottie json file/s in my code or lottie-iOS sample code its taking around 1.7seconds to load one animation out of 3. Incase if I load all the 3 animation at same time it is taking around 2.8 seconds which looks like user stacked in this page opening screen.

If anyone faced same issue please let me know what solution resolved for you...

Thank you...
Dayakar

**Comment by petro2050** [comment]
I have the same issue. I'm loading a JSON animation into `WKWebView` and it takes 1-2 seconds before it loads. `lottie-player.js` as well as the animation are embedded in the iOS app. The rendering should be immediate, but it isn't.

https://github.com/LottieFiles/lottie-player/issues/31

**Comment by calda** [comment]
I believe the new dictionary-based decoding option in 3.4.0 should help improve performance here.
