### ISSUE TITLE
Animation does not show at all

### ISSUE THREAD

**Issue by petro2050** [airbnb/lottie-ios#1226]
I have a JSON file that I could play in a browser, but when I try to show it on iOS, I see nothing but a blank screen. I have other JSON files that iOS can play fine. It seems the file with the problem is using some elements that are not supported. The file was generated in After Effects. Is there a list of unsupported features I could look at to try to figure out the root cause of the issue?

**Comment by Wini996** [comment]
i have the same issue

**Comment by KorolZhu** [comment]
[test.zip](https://github.com/airbnb/lottie-ios/files/4985660/test.zip)

this can play at browser, but can not play at ios, using 3.1.8

**Comment by joehinkle11** [comment]
Same problem here

**Comment by joehinkle11** [comment]
Xcode Beta 6 (12A8189n) and it still doesn't work

**Comment by petro2050** [comment]
This library has all sorts of issues. Unfortunately, I had to revert to showing GIFs. It's a shame because Lottie is faster and smaller in size.

**Comment by calda** [comment]
here's the list of supported after effects features: https://airbnb.io/lottie/#/supported-features
