### ISSUE TITLE
Archiving on Xcode 12 beta 2 fails prevents Carthage use

### ISSUE THREAD

**Issue by moglistree** [airbnb/lottie-ios#1228]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
~- [] Non-Crashing Bug (Visual or otherwise)~
~- [] Crashing Bug~
~- [] Feature Request~
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.8

## What Platform are you on? 

~- [] MacOS~
- [x] iOS

## What Language are you in?
- [x] Swift
- [x] Objective-C

## Expected Behavior 

Successful archive

## Actual Behavior

When attempting to archive using Xcode Beta 2 it fails on compile time with the following output:

```
Undefined symbols for architecture armv7:
  "type metadata for Swift._StringObject.Variant", referenced from:
      outlined init with take of Swift._StringObject.Variant in AnimationKeypathExtension.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This prevents usage of Lottie trough Carthage.

## Code Example
NA

## Animation JSON

NA

**Comment by skymobilebuilds** [comment]
switch to lottie master branch and it will succeed. A PR has been merged with the fix. Tested on Xcode 12 beta 2 on Big Sur.

**Comment by amine2233** [comment]
same issue here

**Comment by froesmatheus** [comment]
It works for me on the `master` branch 👍

**Comment by moglistree** [comment]
So when is the next release coming?

**Comment by calda** [comment]
Closing since this seems like a potentially outdated issue. Feel free to re-open if you're still experiencing this issue.
