### ISSUE TITLE
Allow subclassing AnimationView

### ISSUE THREAD

**Issue by jeffwatkins** [airbnb/lottie-ios#1230]
## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift
- [] Objective-C

## Expected Behavior
We'd like to extend Lottie's AnimationView to support seamlessly switching between animations when a user changes between light and dark user interface styles. To do this we need to implement `traitCollectionDidChange` and swap the running animation. (I'm fairly certain we can do this with minimal dropped frames, especially if we pre-load the alternate animation.)

## Actual Behavior
`AnimationView` is `final` so we can't subclass it. That means we'll have to create a wrapper view and completely re-implement the entire public interface. Additionally we'll need to ensure we keep up to date with changes to the public interface. This is rather undesirable.

## Code Example

class WFAnimationView: AnimationView {
}

**Comment by simonmitchell** [comment]
This would also be amazing so I can have animations in `UICollectionViewCell` without them re-setting every time the collection view is re-drawn. Want to add an `animationIdentifier` property to the subclass so I only have to change out the animation on the `AnimationView` if it's actually changed!

**Comment by buba447** [comment]
The officially suggested way is to create a wrapper. You do not have to re-implement the entire public interface if you expose the underlying animation view in your wrapper.

**Comment by simonmitchell** [comment]
Yeah sorry @buba447 I realised I could achieve this by creating a wrapper shortly after commenting ☺️
