### ISSUE TITLE
How to set the last frame of the animation when Lottie animation is stoped in iOS (Swift).

### ISSUE THREAD

**Issue by dayakar06** [airbnb/lottie-ios#1232]
Hi folks,

I had requirement view transition, when when view transition happening we have to stop the Lottie animation with last frame of the animation. so I have tried but couldn't find any solution for it can anyone help me on this...

Thank you..

**Comment by calda** [comment]
You could set `animationView.currentProgress` to 1, for example. If you have other questions, feel free to [start a discussion](https://github.com/airbnb/lottie-ios/discussions).
