### ISSUE TITLE
Default `fromFrame` is incorrect

### ISSUE THREAD

**Issue by dbagwell** [airbnb/lottie-ios#1233]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.8

## What Platform are you on? 
- [ ] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [ ] Objective-C

## Expected Behavior 
Calling `AnimationView`'s `play(fromFrame:toFrame:loopMode:completion:)` method without specifying the `fromFrame` parameter should play the animation from the current frame.

Also, calling `play(completion:)` when the current frame is not at the start should play the animation from the current frame.

## Actual Behavior
When `play(fromFrame:toFrame:loopMode:completion:)` is called, the animation is played from the frame number that is equivalent to the current "progress".

When `play(completion:)` is called, the animation is played from the start.

## Code Example
```
let animationView = AnimationView(name: "animationWith100Frames")
view.addSubview(animationView)
animationView.currentFrame = 50
// Note: current progress should now be 0.5, because frame 50 is halfway into the animation
animationView.play(toFrame: 100) // Instead of starting at frame 50, the animation starts at frame 0.5
// Or using the line below instead
animationView.play() // Instead of starting at frame 50, the animation starts at frame 0
```

## Possible Solution
This should be simply fixed by changing `currentProgress` on [line 320 of AnimationView.swift](https://github.com/airbnb/lottie-ios/blob/master/lottie-swift/src/Public/Animation/AnimationView.swift#L320) to `currentFrame`.

And by changing `animation.startFrame` on [line 268 of AnimationView.swift](https://github.com/airbnb/lottie-ios/blob/master/lottie-swift/src/Public/Animation/AnimationView.swift#L268) to `currentFrame`.

**Comment by calda** [comment]
Good catch! Fixed in #1707.
