### ISSUE TITLE
Animation Showing Black Content

### ISSUE THREAD

**Issue by VishalMXPlayer** [airbnb/lottie-ios#1237]
## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.8

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [X] Swift
- [] Objective-C

## Expected Behavior 
Animation plays as intended. It works correctly on https://lottiefiles.com/preview

<img width="1790" alt="Screenshot 2020-07-30 at 7 56 43 PM" src="https://user-images.githubusercontent.com/66253529/88934936-d517e480-d29e-11ea-91ef-6435cfd9c89e.png">

## Actual Behavior
The animation is showing black content. If should be clear as shown in the screenshot shared in the Expected Behavior.

<img width="398" alt="Screenshot 2020-07-30 at 7 58 09 PM" src="https://user-images.githubusercontent.com/66253529/88935136-0e505480-d29f-11ea-949d-7cba267a384d.png">

## Code Example

        let animationView = AnimationView()
        let animation = Animation.named("games-icon-animation")
        animationView.animation = animation
        animationView.contentMode = .scaleAspectFill
        animationView.loopMode = .playOnce
        
        view.addSubview(animationView)
        animationView.translatesAutoresizingMaskIntoConstraints = false
        NSLayoutConstraint.activate([
            animationView.centerXAnchor.constraint(equalTo: view.centerXAnchor, constant: 0),
            animationView.widthAnchor.constraint(equalToConstant: 132),
            animationView.heightAnchor.constraint(equalToConstant: 132),
            animationView.centerYAnchor.constraint(equalTo: view.centerYAnchor, constant: 0)
        ])
        
        animationView.play()  

## Animation JSON
[games-icon-animation.json.zip](https://github.com/airbnb/lottie-ios/files/5002010/games-icon-animation.json.zip)

**Comment by calda** [comment]
This animates correctly in the latest version of Lottie, and doesn't have any rendering glitches when I test it using the new Core Animation rendering engine
