### ISSUE TITLE
Line of pixels appearing between side by side shapes

### ISSUE THREAD

**Issue by awesamm** [airbnb/lottie-ios#1238]
I've created a wave animation where I have 4 columns side by side, they are all masked and perfectly aligned—i've zoomed in as far as i can to ensure they are definitely aligned. When rendering lottie files, it appears that the masks arent lined up and that theres a line of pixel between each column, so i overlapped the layers so technically if it was misaligning technically there should be the other colour below. however this has not fixed the issue? anyone know hoe to fix this?

## Which Version of Lottie are you using?

- Lottie 3.0
- Windows

## Animation JSON
https://lottiefiles.com/share/0P7Y1C

**Comment by calda** [comment]
Closing since the animation appears to render the same on iOS as it does on https://lottiefiles.com. If you still need support, feel free to [start a discussion](https://github.com/airbnb/lottie-ios/discussions).
