### ISSUE TITLE
animationView.loopMode = .playOnce makes animation stop

### ISSUE THREAD

**Issue by charlotzzz** [airbnb/lottie-ios#1242]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Code Example
```
struct LottieView: UIViewRepresentable {
    typealias UIViewType = UIView
    var filename: String
    
    func makeUIView(context: UIViewRepresentableContext<LottieView>) -> UIView {
        let view = UIView(frame: .zero)
        
        let animationView = AnimationView()
        let animation =  Animation.named(filename)
        
        animationView.animation = animation
        animationView.contentMode = .scaleAspectFit
        
        animationView.play()
        animationView.loopMode = .playOnce
        
        
        animationView.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(animationView)
        
        NSLayoutConstraint.activate([
            animationView.widthAnchor.constraint(equalTo: view.widthAnchor),
            animationView.heightAnchor.constraint(equalTo: view.heightAnchor)
        ])
        
        return view
        
    }
    
    func updateUIView(_ uiView: UIView, context: UIViewRepresentableContext<LottieView>) {
        
    }
    

}
```

Hi, I want to play my animation only once so I put `animationView.loopMode = .playOnce`. But instead, the animation just stops at some frame without any movement. I have tried it with some other animations, and they also stops.

**Comment by TerenzeY** [comment]
Same here.

**Comment by calda** [comment]
Could you share a complete/runnable sample project that reproduces this issue?
