### ISSUE TITLE
Lottie framework not worked with IOS 9 and IOS 10 with latest xcode(above xcode 11.3)

### ISSUE THREAD

**Issue by Puneet31072020** [airbnb/lottie-ios#1249]
The lottie animation view crashed when open the . the crash is only observed in IOS 9 an d IOS 10 when using the XCode 11.5. Earlier there was no such crash observed with xcode 11.3. 

Device used: Ipad
Version: 9.3.5
Apache License:  Version 2.0, January 2004
 https://www.apache.org/licenses/
Lottie Version: 3.0
Language: Swift

**Comment by cbowns** [comment]
Can you share your crash log here?

**Comment by ljs19850321** [comment]
Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x1813b4160 objc_release + 16
1  Lottie                         0x1016edde8 $s6Lottie18AnimationContainerC9animation13imageProvider04textF0AcA0B0C_AA0b5ImageF0_pAA0b4TextF0_ptcfcTf4gngn_n + 608
2  Lottie                         0x1016f5394 $s6Lottie13AnimationViewC04makeB5Layer33_99563BA6970B38756C8913CDCC351EC4LLyyF + 268
3  Lottie                         0x1016f4e20 $s6Lottie13AnimationViewC9animationAA0B0CSgvs + 76
4  lottie_react_native            0x102e98e78 $s19lottie_react_native13ContainerViewC13setSourceJsonyySSF + 368
5  lottie_react_native            0x102e991d8 $s19lottie_react_native13ContainerViewC13setSourceJsonyySSFToTm + 92
6  React                          0x10219f574 __49-[RCTComponentData createPropBlock:isShadowView:]_block_invoke.89 + 228
7  React                          0x10219f728 __49-[RCTComponentData createPropBlock:isShadowView:]_block_invoke_2.90 + 364
8  React                          0x10219f9e8 __37-[RCTComponentData setProps:forView:]_block_invoke + 124
9  CoreFoundation                 0x181c1ccac __65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 120
10 CoreFoundation                 0x181c1cb84 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 180
11 React                          0x10219f944 -[RCTComponentData setProps:forView:] + 136
12 React                          0x1021f3568 __44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke + 180
13 React                          0x1021f3664 __44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.417 + 28
14 libdispatch.dylib              0x1817814bc _dispatch_call_block_and_release + 24
15 libdispatch.dylib              0x18178147c _dispatch_client_callout + 16
16 libdispatch.dylib              0x181786b84 _dispatch_main_queue_callback_4CF + 1844
17 CoreFoundation                 0x181cecd50 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
18 CoreFoundation                 0x181ceabb8 __CFRunLoopRun + 1628
19 CoreFoundation                 0x181c14c50 CFRunLoopRunSpecific + 384
20 GraphicsServices               0x1834fc088 GSEventRunModal + 180
21 UIKit                          0x186efe088 UIApplicationMain + 204
22 Paytm First Games              0x100070adc main + 15 (AppDelegate.swift:15)
23 ???                            0x1817b28b8 (Missing)

**Comment by ljs19850321** [comment]
a lot of iOS 9 and 10 crash

**Comment by caioremedio** [comment]
This thread has some infos about this issue: https://github.com/airbnb/lottie-ios/issues/1155

But basically you can't use Xcode >= 11.4 if you are still supporting iOS 9.

**Comment by cbowns** [comment]
I understand the iOS 9 issue, but reports of issues on iOS 10 are different (and more concerning for me as a Lottie client).

**Comment by ljs19850321** [comment]
got it

**Comment by cbowns** [comment]
I tested Lottie 3.1.8 on iOS 10.3.3 with Xcode 11.6 and had no issues. Please attach *full file* crash reports (e.g. they must include iOS version) here.

**Comment by yjkyz** [comment]
iOS 9 It will appear crash

**Comment by cbowns** [comment]
https://www.google.com/search?client=safari&rls=en&q=ios+how+to+get+a+crash+log&ie=UTF-8&oe=UTF-8

**Comment by Jason8Zhang** [comment]
Xcode 11.5 iOS 9.3.5 crash at animate init with the latest versioin(3.1.8).
When enabled Zombie Objects switch , I find the below log in console.
*** -[Lottie.AnimationContainer release]: message sent to deallocated instance 0x1977ba50

**Comment by calda** [comment]
Lottie no longer supports iOS 9
