### ISSUE TITLE
Update .podspec to 1.0.5

### ISSUE THREAD

**Issue by xinsight** [airbnb/lottie-ios#125]
I noticed the cocoapod podspec is still at 1.0.4 but the current version is 1.0.5.

Also the `Example/` cocoapod project is still using 1.0.0. Just needs a `pod install`

**Comment by buba447** [comment]
The bump to 1.0.5 was solely for NPM purposes. Theres no difference in the cocoa pod code between the two. 
Later today we are going to be bumping the version for everything to 1.5 once a few more bug fixes go through!
Thanks for grabbing this but we will close it for now and wait for the release later today :)
