### ISSUE TITLE
Still active? iOS 14 having many issues.

### ISSUE THREAD

**Issue by TerenzeY** [airbnb/lottie-ios#1251]
Is Lottie still active?

iOS 14 has many issues where animations are stuck.

**Comment by buba447** [comment]
Yes! Lottie is still active.
I’m pretty much the sole maintainer. I’m working to address issues when I get the, emphasis on free, time.

**Comment by TerenzeY** [comment]
Got it!

**Comment by TerenzeY** [comment]
Actually, may I ask what are the common reasons that cause animations to be cancelled?

`animationView.play(fromProgress: 0,
                       toProgress: 1,
                       loopMode: LottieLoopMode.playOnce,
                       completion: { (finished) in
                        if finished {
                          print("Animation Complete")
                        } else {
                          print("Animation cancelled")
                        }
    })`

**Comment by joehinkle11** [comment]
@buba447 I hope you can get to it! The library was working great before iOS 14. I can't get it to render anything on iOS 14 with the Xcode beta.

**Comment by cbowns** [comment]
@joehinkle11 are you seeing it fail to load files, or fail to render?

**Comment by TerenzeY** [comment]
Sometimes it's stuck halfway, dug further and seems like it has been cancelled.

**Comment by joehinkle11** [comment]
> @joehinkle11 are you seeing it fail to load files, or fail to render?

I would have to look into it more. I was using a SwiftUI view that someone wrote. Weirdly it would show in the SwiftUI previews in Xcode, but once you built it for an app or click the play button in the previews, it would disappear. So I'm guess it's a failure to render
