### ISSUE TITLE
Crash in AnimationView.stop

### ISSUE THREAD

**Issue by davidpasztor** [airbnb/lottie-ios#1254]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Crashing Bug
## Which Version of Lottie are you using?

Lottie 3.1.8

## What Platform are you on? 

- [x] iOS 13.5

## What Language are you in?
- [x] Swift

## Expected Behavior 

I should be able to call `AnimationView.stop()` without it crashing.

## Actual Behavior

When stopping the animation, I get a crash in `AnimationView.stop()` on the last line, `CATransaction.flush()`. Sadly this crash is quite intermittent, so I am not sure how exactly to reproduce it.
>Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
The code is called on the main thread.

## Code Example
```swift
/// SwiftUI wrapper for `AnimationView`
@available(iOS 13, *)
public struct AnimationViewWrapper: UIViewRepresentable {

    private let animation: Lottie.Animation?
    private let loopMode: LottieLoopMode
    @ObservedObject private var animate: ObservableContainer<Bool>

    /// Designated initialiser
    /// - parameter animationName: the name of the animation to load
    /// - parameter animate: controls whether the animation is playing or not. Setting this property to `true` starts the animation, while setting it to `false` stops it.
    /// - parameter loopMode: how the animation should behave once it starts playing
    public init(animationName: String, animate: ObservableContainer<Bool>, loopMode: AnimationLoopMode = .playOnce) {
        self.animation = Animation.named(animationName, bundle: Bundle(for: BundleLocator.self))
        self.loopMode = loopMode.lottie
        self.animate = animate
    }

    public func makeUIView(context: UIViewRepresentableContext<Self>) -> UIView {
        // Wrapping `animationView` in a `UIView` with `NSLayoutConstraint`s is necessary for `animationView` to follow the size set on the SwiftUI wrapper
        let view = UIView()

        let animationView = AnimationView(animation: animation)
        animationView.loopMode = loopMode
        animationView.contentMode = .scaleAspectFit

        animationView.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(animationView)

        NSLayoutConstraint.activate([
            animationView.widthAnchor.constraint(equalTo: view.widthAnchor),
            animationView.heightAnchor.constraint(equalTo: view.heightAnchor)
        ])

        return view
    }

    public func updateUIView(_ uiView: UIView, context: UIViewRepresentableContext<Self>) {
        guard let animationView = uiView.subviews.lazy.compactMap({ $0 as? AnimationView }).first else { return }
        // Crash originates from here on `animationView.stop()`
        animate.value ? animationView.play() : animationView.stop()
    }
}

/// The sole purpose of this class is to be passed to `Bundle(for:)`, which requires a class, not a struct, hence we cannot pass `AnimationViewWrapper` to it. For this reason, this class should always live in the same file as `AnimationViewWrapper`.
private class BundleLocator {}
```

**Comment by Nooba** [comment]
It took me a bit of time, but I was able to isolate one case where it crashes easily.
I have a collectionView in one of my application which uses self-sizing cells, one of which contains an AnimationView.
Unfortunately, if you call `collectionView.reloadSections(…)` on said visible collectionView, any call to `CATransaction.flush()` in the layout size computation `func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize` crashes the app.

On my specific case the animationView is not paramount to the cell size, meaning I can ignore it when computing the size, which should avoid the crash, but it still is a case where the call to `CATransaction.flush()` from the pod caused some crashes.

According to the documentation :

> Delays the commit until any nested explicit transactions have completed.
> 
> Flush is typically called automatically at the end of the current runloop, regardless of the runloop mode. If your application does not have a runloop, you must call this method explicitly.
> 
> **However, you should attempt to avoid calling flush explicitly**. By allowing flush to execute during the runloop your application will achieve better performance, atomic screen updates will be preserved, and transactions and animations that work from transaction to transaction will continue to function.

Overall, does this call to flush creates more harm than good? I have no idea, i never suffered from any animation not stopping when `.stop()` was called. Which seems to be the reason behind this call. cf commit message : https://github.com/airbnb/lottie-ios/commit/5ea3aeda7c153076f3ebc6788cee3a893452316a
