### ISSUE TITLE
Repeated "nil host used in call to allowsSpecificHTTPSCertificateForHost" in Log

### ISSUE THREAD

**Issue by qazwini** [airbnb/lottie-ios#1256]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 

Loads animation without issues.

## Actual Behavior

Loads animation without issues, but in the debug logs, this is what it spams me with 18 times:
```
2020-09-13 04:45:20.335076-0400 AppName[8898:1527281] nil host used in call to allowsSpecificHTTPSCertificateForHost
2020-09-13 04:45:20.335111-0400 AppName[8898:1527281] nil host used in call to allowsAnyHTTPSCertificateForHost:
```

## Code Example
In Collection View Cell:
```
var animationView = AnimationView()
```

In cellForItemAt:
```
cell.animationView.animation = Animation.named("myMandela")
cell.animationView.layer.masksToBounds = true
cell.animationView.contentMode = .scaleAspectFill
cell.animationView.play()
cell.animationView.loopMode = .loop
cell.animationView.backgroundBehavior = .pauseAndRestore
```

When I remove `cell.animationView.animation = Animation.named("myMandela")`, everything works fine—no errors in log.

This happens on iOS 14 beta physical device & simulator using Xcode 12 Beta.

## Animation JSON

The JSON file is enormous. I will email it.

**Comment by karasahinemre** [comment]
Same here

**Comment by Trueg112** [comment]
I'm facing same issue.

**Comment by qazwini** [comment]
This is still an issue with iOS 14.0 release on physical device and simulator using Xcode 12 GM.

**Comment by manojalwisnz** [comment]
Yes, the same issue for Ionic ios app on the emulator.

**Comment by lestadNew** [comment]
The same issue

**Comment by dicksondickson** [comment]
Same issue here. I appears this error shows up in the log when and embedded image assets (jpeg, png) is in the json file. Tried files from my own animation with and without embed image assets and from lottiefiles.com and the results are consistent.

**Comment by chenyk0317** [comment]
The same issue
2020-09-29 11:15:56.979597+0800 zhenghaoban[22354:752056] nil host used in call to allowsAnyHTTPSCertificateForHost:
2020-09-29 11:15:56.980136+0800 zhenghaoban[22354:752056] nil host used in call to allowsSpecificHTTPSCertificateForHost
2020-09-29 11:15:56.980226+0800 zhenghaoban[22354:752056] nil host used in call to allowsAnyHTTPSCertificateForHost:
2020-09-29 11:15:56.980755+0800 zhenghaoban[22354:752056] nil host used in call to allowsSpecificHTTPSCertificateForHost
2020-09-29 11:15:56.980840+0800 zhenghaoban[22354:752056] nil host used in call to allowsAnyHTTPSCertificateForHost:

**Comment by nsalvaro** [comment]
Same here... hope this gets fixed cause it's really slowing down the app... a lot!

**Comment by sedrakk** [comment]
Same as well..

**Comment by kgillespieatmosphere** [comment]
We are also seeing this on iOS using version 6.1.1

**Comment by fjtrujy** [comment]
Same issue over here!

**Comment by wswoodruff** [comment]
I'm working on a Cordova project and was brought to this page — just sharing in case anyone else gets here for the same reason

Had an issue very similar to this — repeated logs of `nil host used in call to allowsSpecificHTTPSCertificateForHost` and I'd also see a `-999` error.

I fixed it by re-adding `cordova-plugin-deeplinks` since I had recently removed some unfinished deep linking code

The diff roughly looked like this, only changes needed in `package.json`

```diff
{
  ...
  "dependencies": {
    ...
+   "cordova-plugin-deeplinks": "^1.1.1"
  },
  "cordova": {
    ...
+ "cordova-plugin-deeplinks": {}
}
```

**Comment by norbdev** [comment]
Same here, Xcode 12.2, iOS 14.2, iPhone 6S

**Comment by LunightLab** [comment]
same issue, Xcode 12.2, Simulator iPhone 12

**Comment by hansemannn** [comment]
Honestly, it doesn't help much to duplicate the same issue over and over again. You can just follow the thread and/or try to solve it.

I looked into the solution of @wswoodruff and tried to find related code in the Cordova plugin that may also apply for native code. The module is mainly handling user activities, but also includes some URL schemes that might influence this issue. @wswoodruff Would you mind sending over an (anonymized) version of your url schemes inside the generated Info.plist? That might lead into the right direction. Also: Did anyone file a radar already?

**Comment by qazwini** [comment]
Is there a way to at least hide the message for now? It's spamming my console and causing me to not see other important stuff.

**Comment by WyattMufson** [comment]
Anyone have a solution to this?

**Comment by usmansc** [comment]
Same here, Xcode 12.2, iOS 14.3, iPhone Xr

**Comment by remif25** [comment]
Same problem here on MacBook Pro M1, XCode 12.3, IOS 14.3.

**Comment by rlxone** [comment]
Same here. Xcode 12.3, iOS 14.3

**Comment by pz2147** [comment]
Same here. Xcode Version 12.4 (940.20)

2021-01-28 15:40:54.349565+0800 [67861:574777] nil host used in call to allowsSpecificHTTPSCertificateForHost
2021-01-28 15:40:54.349698+0800 [67861:574777] nil host used in call to allowsAnyHTTPSCertificateForHost:

Pod information
pod 'lottie-ios', '<= 3.1.8'

**Comment by MichalMartinu** [comment]
I have same problem. Xcode 12.4, iOS 14.4

**Comment by vpopovyc** [comment]
Facing same issue using 3.2.0 release.

**Comment by m4rr** [comment]
Same here.

**Comment by gsborisgithub** [comment]
opening local html files using UIWebView loadRequest in my app causes that. html files have img tags to locally stored jpegs. Ended up converting images into base64 data and pasting them in img tags. no errors now. wish there was a better way though.

**Comment by vpopovyc** [comment]
Ok, I found what was causing that issue.
If animation file contain base64 image encoded like **data:image/**_image_mime_type_placeholder_**;base64,**_base64_encoded_image_placeholder_,
e.g. "data:image/png;base64,...", you will see this error.

To fix this, in `BundleImageProvider` `func imageForAsset(asset: ImageAsset) -> CGImage?` you should change parsing of base64 images.
Original:
```swift
if asset.name.hasPrefix("data:"),
    // two lines below are generating that issue,
    // I suppose they were taken from here https://stackoverflow.com/a/46195857
    let url = URL(string: asset.name),
    let data = try? Data(contentsOf: url),
    let image = UIImage(data: data) {
        return image.cgImage
}
```
Fix can look like that:
```swift
if asset.name.hasPrefix("data:") {
    let encodedAsset = asset.name
    let mimeLookupUpperBound = 25
    let searchRange = encodedAsset.startIndex..<encodedAsset.index(encodedAsset.startIndex, offsetBy: mimeLookupUpperBound)
    let mimeRange = encodedAsset.range(of: ";base64,", range: searchRange)
    let base64String = String(encodedAsset[mimeRange!.upperBound..<encodedAsset.endIndex])

    if let data = Data(base64Encoded: base64String, options: .ignoreUnknownCharacters),
       let image = UIImage(data: data) {
        return image.cgImage
    }
}
```
I've tested this approach on iOS 14.4 with 3.1.9 and it works for me.
Hope that helps 😅

**Comment by YanSteph** [comment]
Any news for a future correction?

**Comment by vpopovyc** [comment]
@hansemannn please take a look

**Comment by hansemannn** [comment]
@vpopovyc The change makes sense. Can you create a pull request or should I?

**Comment by vpopovyc** [comment]
@hansemannn please make it, Lottie codebase is new for me, don't want to break things :)

**Comment by hansemannn** [comment]
I think @buba447 is best qualified to review and implement this change. And with so much traction on this issue, the chances are good to integrate it soon :-)

**Comment by Fernandez-Aldo** [comment]
Following. When are you planning to hace this issue solved?

**Comment by exotexot** [comment]
Having the same issue, and im _NOT_ using this module. 
So there's a chance that this is unrelated to this library.

**Comment by swarnaditya** [comment]
uring startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_COLLATE failed, using "C" 
3: Setting LC_TIME failed, using "C" 
4: Setting LC_MESSAGES failed, using "C" 
5: Setting LC_MONETARY failed, using "C" 
[R.app GUI 1.74 (7950) x86_64-apple-darwin17.0]

WARNING: You're using a non-UTF8 locale, therefore only ASCII characters will work.
Please read R for Mac OS X FAQ (see Help) section 9 and adjust your system preferences accordingly.
starting httpd help server ... done
2021-04-08 18:33:51.228 R[37X36:24QW742] nil host used in call to allowsSpecificHTTPSCertificateForHost
2021-04-08 18:33:51.228 R[37X36:24QW742] nil host used in call to allowsAnyHTTPSCertificateForHost:

**Comment by norbdev** [comment]
SPM + 3.2.2

nil host used in call to allowsAnyHTTPSCertificateForHost:
nil host used in call to allowsSpecificHTTPSCertificateForHost

**Comment by flaviolivolsi** [comment]
@vpopovyc thank you - that helped!

**Comment by smamczak** [comment]
Any update?

**Comment by calda** [comment]
Fixed on `master` by #1524

**Comment by rawandahmad698** [comment]
not fixed, I still have this issue!

**Comment by lajosdeme** [comment]
not solved, having the same issue

**Comment by mobiletoly** [comment]
with most recent version (on master) - fixed for me

**Comment by AlexanderKvamme** [comment]
I am also experiencing this issue

**Comment by calda** [comment]
3.4.0 includes a fix for this issue

**Comment by fpiantoni** [comment]
@calda has this been fixed? if so what do i need to upgrade?

**Comment by dZbear** [comment]
Still having this issue with 3.4.0

**Comment by fpiantoni** [comment]
@dZbear Are you still experimenting the same issue?

**Comment by Noice-Anas** [comment]
same here I am still facing it. 
IOS: 15.0
Xcode: 13.4.1

**Comment by josemv3** [comment]
[vpopovyc](https://github.com/vpopovyc) commented [on Mar 2, 2021](https://github.com/airbnb/lottie-ios/issues/1256#issuecomment-788941762) Solved my issue. Also, switching from SVG files to just png also worked.

**Comment by RiffatIslam** [comment]
same issue
xcode 15.0.1
 iOS 16.2
