### ISSUE TITLE
Cannot override 'init' which has been marked unavailable

### ISSUE THREAD

**Issue by cczufish** [airbnb/lottie-ios#1264]
## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] iOS

## What Language are you in?
- [] Swift

## Animation JSON

ImageCompositionLayer

    required init?(coder _: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

Cannot override 'init' which has been marked unavailable

**Comment by cczufish** [comment]
@available(*, unavailable)
    required init?(coder _: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

**Comment by andriyslyusar** [comment]
I am start getting the same error with latest Xcode 12.1

**Comment by cczufish** [comment]
> I am start getting the same error with latest Xcode 12.1

I fixed this error，cancel SwiftFormat in my project，and remove pod files，then pod install

**Comment by andriyslyusar** [comment]
@cczufish Thanks, save my day. I did a SwiftFormat by mistake on Pods directory.
