### ISSUE TITLE
`scanHexInt32` was deprecated in iOS 13.0

### ISSUE THREAD

**Issue by spease** [airbnb/lottie-ios#1270]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.8

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 
No warnings

## Actual Behavior
1 warning

## Code Example
Internal to the library (looks like it might be src/Private/Utility/Extensions/StringExtensions.swift)

## Animation JSON
N/A

**Comment by keith** [comment]
This was fixed in newer releases
