### ISSUE TITLE
reloading Data in View Base Table View on OSX freezing Lottie animation

### ISSUE THREAD

**Issue by VitaliiDeveloper** [airbnb/lottie-ios#1273]
Hello everybody. Maybe somebody already had this issue:

When you have a lot of cells and headers in NSTableView, Lottie's layers gonna be freezing. 
Steps:

0. Added Lottie VC and V on RootViewController ( like overlay )
1. Loaded, Showed, and Play Lottie Animation
2. From global() and main.async queues did some tasks
3. Call reloadData for NSTableView from main.async
4. Until cell creating ( most viewed when more than 5 headers on-screen ) Lottie gonna be a stuck

Maybe somebody has an answer on how to fix it

## Which Version of Lottie are you using?
Latest from CocoaPods

## What Platform are you on? 
-  MacOS

## What Language are you in?
- Swift

## Expected Behavior 
1. Loaded, Showed, and Play Lottie Animation
2. From global() and main.async queues did some tasks
3. Call reloadData for NSTableView from main.async
4. Lottie continue loading
.....

## Actual Behavior
1. Loaded, Showed, and Play Lottie Animation
2. From global() and main.async queues did some tasks
3. Call reloadData for NSTableView from main.async
4. Until cell creating ( most viewed when more than 5 headers on-screen ) Lottie gonna be a stuck

**Comment by WifiFly** [comment]
how to slove
