### ISSUE TITLE
Anyone having issues with rendering (not rendering at all) in iOS 14?

### ISSUE THREAD

**Issue by marcibk** [airbnb/lottie-ios#1277]
## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [x] iOS

Anyone having issues with rendering (not rendering at all) in iOS 14?

**Comment by mfranc28** [comment]
Yes

**Comment by buba447** [comment]
Can you provide some more context? Animations, setup, and tests that you may have done?

It’s nearly impossible for us to debug issues that only say ‘animation is not working’ without further context. Thanks!
