### ISSUE TITLE
Animation not playing properly on iOS

### ISSUE THREAD

**Issue by martinbrown08** [airbnb/lottie-ios#1278]
## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift
- [] Objective-C

## Expected Behavior 
Animation to play as expected.

## Actual Behavior
Some layers appear to be wrong on iOS, I guess due to some of the supported features not right, but I can't find why. I thought I could get some help because I dont know where else to look for a solution!

## Animation JSON
I'll email the files!

**Comment by Ezra-Black** [comment]
was the code in question working before? I seem to have suddenly lost animation playback myself.

**Comment by martinbrown08** [comment]
I don't understand the question, sorry! ( I'm Spanish)

**Comment by Ezra-Black** [comment]
Do you have a code example or a animation JSON?

**Comment by martinbrown08** [comment]
Yeah I do!
https://lottiefiles.com/share/u6jvmez3

I've been told the issue is the use of expressions. I've already tried to bake them but that didn't fix the issue. Maybe I'm doing it wrong tho...

**Comment by calda** [comment]
The animation link no longer works, so I'm closing this issue. Feel free to re-open the issue, with a copy of the animation, if you still need support. It sounds like this was because the animation used expressions, which are not supported on iOS.
