### ISSUE TITLE
Animation play ok on web, but no on iOS

### ISSUE THREAD

**Issue by cuicmex** [airbnb/lottie-ios#1284]
I have a json file for lottie animation:
https://lottiefiles.com/share/f44vtncy
https://assets3.lottiefiles.com/packages/lf20_f44vtncy.json

Using lottiefiles.com, the animation plays fine, but when I tested the same animation on LottieFiles iOS, it doesn't show all elements in the animation. (The rays coming out of the star are not all shown)

LottieFiles iOS version: 1.2.1

1. Load animation in lottiefiles.com
2. Read animation QR with LottieFiles iOS
3. See the difference between the rays coming out from the star

The attached zip contain the mov file showing both cases.

**Comment by martinbrown08** [comment]
Im on a similar case with a bunch of json files. If you find any solution for it please share!

**Comment by redpandatronicsuk** [comment]
I think your file uses _Repeater_ which is not supported on iOS. See here: https://github.com/airbnb/lottie/blob/master/supported-features.md

**Comment by cuicmex** [comment]
That's it. The designer created the animation using the repeat function. He has modified the animation creating the rays layers one by one and now works fine.

Thanks a lot.
