### ISSUE TITLE
build fail in xcode 12.2

### ISSUE THREAD

**Issue by wcly** [airbnb/lottie-ios#1287]
![image](https://user-images.githubusercontent.com/23275036/99249019-5f7f5680-2844-11eb-9009-9b6c47b84075.png)
**version:** 
- "lottie-ios": "3.1.9",
- "lottie-react-native": "^3.3.1"
- "react-native": "0.61.5"
- xcode: Version 12.2 (12B45b)

**Comment by Cyberbeni** [comment]
You need to do a clean build after Xcode update (assuming it also contains a newer Swift version)

**Comment by calda** [comment]
Closing since this seems like a potentially outdated issue. Feel free to re-open if you're still experiencing this issue.
