### ISSUE TITLE
Build error from Lottie.AnimationFontProvider

### ISSUE THREAD

**Issue by kockok** [airbnb/lottie-ios#1290]
With error:

![Screenshot 2020-11-20 at 5 23 18 PM](https://user-images.githubusercontent.com/232541/99783249-23eed000-2b55-11eb-994c-aebbf76055ce.png)

## Check these before submitting:
- [v] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [v] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [v] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

    `"lottie-ios": "^3.1.9",`
   `"lottie-react-native": "^3.5.0",`

## What Platform are you on? 

- [v] MacOS
- [v] iOS

## What Language are you in?
- [v] Swift
- [] Objective-C

## Expected Behavior 

build success
## Actual Behavior

build failed

**Comment by christianrank** [comment]
I just had the same issue after upgrading all packages, I guess something in lottie-react-native is incompatible with lottie-ios 3.1.9.

Just get back to 3.1.8 and it will work, it is the version that should be used according to the lottie-react-native readme.
`"lottie-ios": "3.1.8",`

**Comment by calda** [comment]
Closing since this seems like a potentially outdated issue. Feel free to re-open if you're still experiencing this issue.
