### ISSUE TITLE
2.5.3 type is "gs" and "mm" is wrong.how to handle it

### ISSUE THREAD

**Issue by wjssxc** [airbnb/lottie-ios#1298]
## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] iOS

## What Language are you in?
- [] Objective-C

**Comment by calda** [comment]
Could you share more about your issue, or a copy of your animation json?
