### ISSUE TITLE
Undefined symbol: enum case for Lottie.LottieLoopMode.loop(Lottie.LoopMode.Type)

### ISSUE THREAD

**Issue by caniodica** [airbnb/lottie-ios#1299]
I have a framework that includes Lottie. The framework builds succesfully. The integrating app of my framework fails to build reporting  an error on Lottie.LottieLoopMode.loop

## Check these before submitting:
● This issue isn't related to another open (Maybe with Xcode 12.2 build issues? #1287)

## This issue is a:
● Crashing Bug

## Which Version of Lottie are you using?

Lottie 3.1.8 | Lottie 3.1.9

## What Platform are you on? 

● iOS

## What version of Xcode are you using? 

● Xcode 12.2

## What Language are you in?
● Swift

## Expected Behavior 

Build Succeeded

## Actual Behavior

![errore xcode](https://user-images.githubusercontent.com/13018040/101050821-138f1a00-3585-11eb-9d89-7f7424be5932.png)

## Code Example
```
private static func initMyCustomAnimation(animation: Animation, animationView: AnimationView){
        animationView.animation = animation
        animationView.loopMode = .loop
        animationView.play()
    }
```

The error refers to the loopMode enum.

**Comment by DrAma999** [comment]
Your issue is related to mine, check it here https://github.com/airbnb/lottie-ios/issues/1292

**Comment by caniodica** [comment]
> Your issue seems related to mine, check it here #1292

Thank you, @DrAma999. I still cant'understand the reason of this misalignment with Xcode 12.2, but I'll use your suggested workaround.

**Comment by calda** [comment]
Closing since this seems like a potentially outdated issue. Feel free to re-open if you're still experiencing this issue.
