### ISSUE TITLE
a11y

### ISSUE THREAD

**Issue by aaroncrespo** [airbnb/lottie-ios#13]
Do text Animations expose an accessibility id? Is there a mechanism for enabling or enhancing Accessibility for these custom views/layers?

**Comment by buba447** [comment]
We don't yet support text in animations but we have some ideas on how to make it work!
And a11y support is extremely important to us for text, I hadn't yet thought about making the animations themselves accessible outside of the standard iOS accessibility! Good call :)

Gonna leave this issue open until we come up with a strategy.

**Comment by aaroncrespo** [comment]
Yeah maybe poor use of term "text animation" but I thought about this when I saw https://github.com/airbnb/lottie-ios/blob/master/_Gifs/Examples4.gif

**Comment by buba447** [comment]
Ahhh! In that demo each letter is an individual lottie animation wrapped in UICollectionView class that takes text input, strips and sanitizes and loads each letter of animation individually. 
A.json B.json and so on.
So for a11y support there the containing class that loads the LAAnimations would have to also point to animations made for other languages and it's textfield would have to have a11y support.

**Comment by aaroncrespo** [comment]
this is for accessibility not internationalization.

**Comment by aaroncrespo** [comment]
For example how would a blind person be able to read those text fields.
