### ISSUE TITLE
Swift can't read the Lottie JSON file and display animation

### ISSUE THREAD

**Issue by RyshchukDmytro** [airbnb/lottie-ios#1302]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 

Animations is working

## Actual Behavior

Blank screen while animation is working and this message inside log
`keyNotFound(Discriminator(stringValue: "ty", intValue: nil), Swift.DecodingError.Context(codingPath: [_JSONKey(stringValue: "Index 12", intValue: 12), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key Discriminator(stringValue: \"ty\", intValue: nil) (\"ty\").", underlyingError: nil))`
Inside https://lottiefiles.com/preview it's working fine, but swift can't read that JSON.

## Animation JSON

Unfortunately to due to NDA I can't attach JSON file.

**Comment by foxsin10** [comment]
maybe you can use some breakpoints to track some details, the error message seems like your json file was missing some value of  'ty'

**Comment by juanfolivera** [comment]
I'm having the same issue with the attached animation, it's working correctly on 2.5.2

[countdown.json.zip](https://github.com/airbnb/lottie-ios/files/5788948/countdown.json.zip)

**Comment by calda** [comment]
@RyshchukDmytro, could you share a copy of your animation json?
