### ISSUE TITLE
Raises an exception on iOS app running M1 mac. (Running with Designed for iPhone)

### ISSUE THREAD

**Issue by muukii** [airbnb/lottie-ios#1304]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [x] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [x] iOS (But running on M1 mac)

## What Language are you in?
- [x] Swift
- [] Objective-C

## Animation JSON

https://gist.github.com/muukii/350fd80a53958179b2efa576126c12b0#file-aninmation-json

---

Thanks to a great library that enables incredible smooth animations on the App, we can create animations what we want.
So, I faced an issue while running the iOS app on M1 mac that built with arm64. and this runs as designed for iPhone.
I don't know why, but CoreAnimation framework raises an exception about manipulating CATransform3D.

I'll attach more information if you needed.
Thanks.

![image](https://user-images.githubusercontent.com/1888355/103148407-a4cb6800-47a2-11eb-944e-8ee152848ec5.png)

**Comment by damikdk** [comment]
I guess we are first on this page. Can't find anything about it.

**Comment by damikdk** [comment]
For now, I just need to run app, so I just comment 'skewed()' part of makeTransform method in 'VectorsExtensions.swift:214':

```swift
      return CATransform3DMakeTranslation(position.x, position.y, 0)
        .rotated(rotation)
//        .skewed(skew: -skew, skewAxis: skewAxis)
        .scaled(scale * 0.01)
        .translated(anchor * -1)
```

**Comment by dev299** [comment]
1. Are you running Lottie with Xcode in Rosetta mode? 
2. Are you using Cocoapods or Swift Package Manager to pull `lottie-ios`?

**Comment by rsaadi** [comment]
We are also facing the same issue. The Xcode is running natively on MacBook Pro M1 (not on Rosetta), and we are using the SPM integration with the latest version 3.2.1.

**Comment by chrispix** [comment]
We just started experiencing this exact same issue. We're using Carthage to build Lottie, but the crash persists if I update it to use SPM. Like @rsaadi the crash occurs when running on an M1 Mac with Xcode not in Rosetta mode.

The interesting thing is we haven't updated Lottie or the animation recently (except to test whether SPM would fix the problem). The commit on our side that causes the crash to occur added an unrelated dependency via SPM.

**Comment by BrunoVillanova-SaudeID** [comment]
Same, here using M1 Mac. Workaround for me was to set Xcode to run in Rosetta mode.

**Comment by spicymatt** [comment]
Same issue here. Code was building and running fine just a few weeks ago. Using SPM in Xcode on M1 (not Rosetta). We have not updated the animation. It was working fine in June...which is kind of weird as nothing seems to have changed in the repo since that date.

**Comment by simba909** [comment]
I've been seeing this issue as well, started seeing it with Xcode 12.5.1 IIRC.

For some reason this seems related to the use of SpriteKit/Metal (at least this is the case for a project I'm working on), and if I remove any SpriteKit/Metal code the issue disappears.

Curious if anyone else is using either of these in their projects?

**Comment by fbp93** [comment]
Still having the issue, the workaround doesn't work for me. Any updates?

**Comment by spicymatt** [comment]
Hello. I am running Lottie in a macOS app using the latest official branch (reference to the old Mac-only branch was removed). 
Compiles fine but raises the same error in makeSkew(…)

Matthieu

**Comment by calda** [comment]
Is anyone still able to reproduce this issue? The linked animation plays correctly for me using Lottie 4.0 on my M1 Mac.
