### ISSUE TITLE
Compilation error caused by incorrect arguments in TextLayer

### ISSUE THREAD

**Issue by cloudex1** [airbnb/lottie-ios#1306]
Any one can help me to resolve me in this issue. Thank you 

## Check these before submitting:
- The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- This issue isn't related to another open issue

## This issue is a:
- Crashing Bug

## Which Version of Lottie are you using?

Lottie 3.1.9

## What Platform are you on? 
- MacOS
- iOS

## What Language are you in?
- Swift version 4.2

## Actual Behavior
<img width="1014" alt="Screen Shot 2021-01-04 at 11 13 49 PM" src="https://user-images.githubusercontent.com/76769698/103557620-6d6d6180-4eee-11eb-8b77-74501af45558.png">

**Comment by calda** [comment]
Closing since this seems like a potentially outdated issue. Feel free to re-open if you're still experiencing this issue.
