### ISSUE TITLE
Custom AnimationImageProvider not overriding images in animation

### ISSUE THREAD

**Issue by ChristianMcc** [airbnb/lottie-ios#1307]
## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift
- [] Objective-C

## Expected Behavior 
The image in the animation should be replaced when imageForAsset is called on the custom AnimationImageProvider

## Actual Behavior
ImageForAsset is not currently being called and so there is no attempt to replace the images in the animation (I've tried pausing the animation and reloading the images as per other threads).

## Code Example

See Custom image provider here, my animation only has one image so it's hard coded to return a single image and ignore what imageAsset is actually being request. I've confirmed that the following code can return an image for me the issue is that it's not being called.

```
final class LottieImageProvider: AnimationImageProvider {
    func imageForAsset(asset: ImageAsset) -> CGImage? {
        let defaults = UserDefaults.standard
        if let path = defaults.value(forKey: <IMAGE_KEY>) as? String,
           let imageData = try? Data(contentsOf: URL(string: path)!),
           let image = UIImage(data: imageData) {
            return image.cgImage
        }
        return nil
    }
}


Setting the imageProvider here:

```
    self.loadingAnimationView?.imageProvider = LottieImageProvider()
    self.loadingAnimationView?.reloadImages()
    loadingAnimationView?.play(fromProgress: 0, toProgress: 1, loopMode: .playOnce) { _ in
            // some completion handler
     }

## Animation JSON
Can supply privately if needed - replacing the image for android by updating the bitmap worked so I'm inclined to believe it's not the JSON.

**Comment by djukidjuki** [comment]
Did you manage to solve this issue?

**Comment by Peter4137** [comment]
Issue was fixed in [this commit](https://github.com/airbnb/lottie-ios/commit/47d7ef0aee4c2feea6e55f6db22e4d24ba85b4b2) I believe

**Comment by emreond** [comment]
I want to change only one image inside my lottie animation. Can I use this property for that purpose?

**Comment by ChristianMcc** [comment]
Yes you can @emreond , and Sorry @djukidjuki  Peter is correct the issue was fixed in a later version we hadn't pulled in, I'll be closing this issue.
