### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Goallying** [airbnb/lottie-ios#1308]
carsh at this line in LOTLayerContainer  
_wrapperLayer.transform = [_transformInterpolator transformForFrame:newFrame];

Exception	NSException *	"-[__NSCFConstantString runActionForKey:object:arguments:]: unrecognized selector sent to instance 0x101509df8"	0x0000600000c204b0

iphonex 12.4 simulator

**Comment by calda** [comment]
Closing since this seems like a potentially outdated issue. Feel free to re-open if you're still experiencing this issue.
