### ISSUE TITLE
Animation layer is missed - Frames cutted off

### ISSUE THREAD

**Issue by moniquealtero** [airbnb/lottie-ios#1312]
I was working on the update of React Native and  project's libraries update but I noticed that some animation on iOS is being cutted off some layers and before this it was working fine (also it looks fine on Android).

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)

## Which Version of Lottie are you using?
  "lottie-ios": "3.1.9",
  "lottie-react-native": "3.5.0",
  "react-native": "0.63.4",

## What Platform are you on? 
- [X] iOS

## What Language are you in?
- [X] Swift

## Expected Behavior 

![android](https://user-images.githubusercontent.com/28611472/105913946-5d87ff80-600c-11eb-8921-6aab1bdcc7df.gif)

## Actual Behavior

![IOS](https://user-images.githubusercontent.com/28611472/105913955-637de080-600c-11eb-8a10-1695a41fcbb5.gif)

## Code Example

```
 <View style={styles.animationWrapper}>
        <LottieView
          source={Animations.wallet}
          autoPlay
          style={styles.animation}
          loop={false}
          ref={animationOne}
        />
  </View>
```

## Animation JSON

Onine link: https://codebeautify.org/online-json-editor/cbb2bd65

**Probably related to:**

https://github.com/lottie-react-native/lottie-react-native/issues/615
https://github.com/airbnb/lottie-ios/issues/1199
https://github.com/airbnb/lottie-ios/issues/1186

**Comment by zhangyy2017** [comment]
I have same issue,how to fix this ?

**Comment by zhangyy2017** [comment]
I'm iOS  , use "lottie-ios": "3.1.9"

**Comment by LPFr3D** [comment]
Você conseguiu resolver seu problema, Monique?
Estou com o mesmo problema, porém em outra animação. (Android)

**Comment by moniquealtero** [comment]
> Você conseguiu resolver seu problema, Monique?
> Estou com o mesmo problema, porém em outra animação. (Android)

@LPFr3D Fiz downgrade para 3.0.3.

**Comment by AnilkumarRabhasa** [comment]
Any solution for this, Even I am also getting same

**Comment by sidvenu** [comment]
I have the same problem with this: https://lottiefiles.com/5201-progress-bar file
