### ISSUE TITLE
Question about bounds clipping

### ISSUE THREAD

**Issue by adenisonafifi** [airbnb/lottie-ios#132]
Hello, thank you for the great library!

I'm interested in using Lottie in a scenario where I will often want the animator to be able to create an animation that extends beyond the bounds of the UIView. Does Lottie allow this? Or will it be necessary to increase the bounds of LOTAnimationView to create this effect?

**Comment by buba447** [comment]
LOTAnimationView will clip to its own bounds and scale the animation
according to how the contentMode is set on the view.

**Comment by adenisonafifi** [comment]
Thank you for the quick response. Figured clipping to its own bounds would be the case.
