### ISSUE TITLE
lottie-ios 3.2.1 haven't been published to the npm registry

### ISSUE THREAD

**Issue by ifsnow** [airbnb/lottie-ios#1320]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Expected Behavior 
To use `lottie-ios 3.2.1` in `lottie-react-native`, it must be published on NPM. 
It's not an urgent problem, but please.

**Comment by danilojpferreira** [comment]
Same issue here

**Comment by calda** [comment]
3.4.0 is now available on npm
