### ISSUE TITLE
Lottie-ios crashes with Symbol not found in the Cocoapods 1.10.1

### ISSUE THREAD

**Issue by wellbranding** [airbnb/lottie-ios#1321]
Hello, after updating our CocoaPods to the 1.10.1 after 1.8.4 our SDK which uses Lottie-IOS crashes the app, after it integrates our SDK. The crash message is the following:
**Symbol not found: _$s6Lottie0A8LoopModeO4loopyA2CmFWC
  Referenced from:**
  
  

Only after I added the following line in the PodFile it started to work:
post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
end
end
end

Can you include it in your library, so that I would not need to override configs myself, because we can't distribute our SDK anymore, cause not all of our clients have this setting and it will crash the app

**Comment by lukas2** [comment]
Probably related to https://github.com/airbnb/lottie-ios/issues/1292

**Comment by wellbranding** [comment]
@lukas2 Yes it is, but the Lottie team should enable module stability themselves, not the other way around. Is this library still maintained?
