### ISSUE TITLE
Lottie json - Text language change weird behaviour

### ISSUE THREAD

**Issue by jatinfl15** [airbnb/lottie-ios#1323]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [ ] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [x] Feature Request
- [ ] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [ ] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [ ] Objective-C

## Expected Behavior 

![Simulator Screen Shot - iPhone 12 mini - 2021-03-16 at 16 01 05](https://user-images.githubusercontent.com/70931173/111297451-a4d95680-8673-11eb-80c6-c6a1ff7dc25d.png)

## Actual Behavior

![Simulator Screen Shot - iPhone 12 mini - 2021-03-16 at 16 01 15](https://user-images.githubusercontent.com/70931173/111297196-5f1c8e00-8673-11eb-8e30-64917d7e12a5.png)

## Code Example
After text updated json File.
[UserCreation.json.zip](https://github.com/airbnb/lottie-ios/files/6148217/UserCreation.json.zip)
NOTE : one more thing it will run on iOS side properly. but not in lottie web preview & Android.

## Animation JSON

[6.json.zip](https://github.com/airbnb/lottie-ios/files/6148124/6.json.zip)

while changing those text(in hindi language) it will remove the text color and without text border it can't possible to see those text.

NOTE: Gujrati language fonts works properly.

**Comment by roimulia2** [comment]
Did you fix it by chance?

**Comment by calda** [comment]
This issue appears to be fixed in Lottie 4.0 -- feel free to re-open this issue if you're still experiencing problems.

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/1811727/214174653-3a633264-297c-46d8-938b-9abf30d06e34.png">
