### ISSUE TITLE
Animations always use screen scale as the rendering scale, which isn't always preferred

### ISSUE THREAD

**Issue by JoeSzymanski** [airbnb/lottie-ios#1325]
## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [X] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

While investigating performance issues around large, complex animations in Lottie 3 (all of which worked fine in Lottie 2.5.x), I discovered that the drawing context in Lottie 3 was significantly larger than the same animation running in Lottie 2. After some digging, I discovered that Lottie 3 will use the screen's scale as the rendering scale, which can significantly impact performance of large (i.e. screen-sized) animations. For something like gradients, this can make animations almost impossible to run in a performant manner.

Lottie 3 doesn't expose any way to modify the render scale of the animation layer, so there's no way to tune the tradeoffs between the accuracy of the drawing versus the performance. With a simple test of forcing the render scale to 1, the animations play extremely well.

The render scale should be exposed in some way to allow the developer to choose to run with a different render scale than the screen for performance reasons.

**Comment by JoeSzymanski** [comment]
I will be looking into create a PR for this, but I need to spend some time figuring out the optimal way to manage exposing the render scale, since I don't think the animation layer should be exposed directly, but I need to make sure the correct scale is used in all cases.

**Comment by absolute-heike** [comment]
Great find @JoeSzymanski!!

I was playing around with this idea and this is what I found:
* In ObjC (2.5.2) `contentsScale` is 1.0 for all sublayers
* Setting `contentsScale` to `1.0` in lottie-swift has **no** visual impact at all
* `contentsScale = 1.0` has tremendous impact on Performance. Some numbers with a complex test animation:
  * Swift contentsScale 3.0: ~70% CPU Utilization
  * Swift contentScale 1.0: ~40% CPU Utilization
  * ObjC (defaults to scale 1.0): ~37% CPU Utilization
  
I know that documentation tells us to adjust the contentsScale of a programatically created Layer. But what do we gain by setting contentsScale to 3.0? Except for hotter iPhone? I haven't found any differences so far.

**Comment by absolute-heike** [comment]
contentsScale 3.0 vs contentsScale 1.0 comparison

![Artboard](https://user-images.githubusercontent.com/522881/112004826-74396700-8b22-11eb-9bec-e8182a67ab4c.png)

**Comment by calda** [comment]
I believe this is fixed in 3.4.0
