### ISSUE TITLE
Crash in Demo: show transition A

### ISSUE THREAD

**Issue by sanatory** [airbnb/lottie-ios#133]
xcode 8.2.1, iOS: 10.2.1
1. go to Animated Transitions Demo
2. tap show transition A button

ER: do something nice
AR: crash with`-[LOTCompositionLayer addSublayer:toLayerNamed:]: unrecognized selector sent to instance 0x17005d700`

**Comment by buba447** [comment]
Fixed!

**Comment by sanatory** [comment]
it works, but on iPhone6 layout glitches... 
[transitions layout glitch.zip](https://github.com/airbnb/lottie-ios/files/804790/transitions.layout.glitch.zip)
