### ISSUE TITLE
Get issue to display Lottie file.

### ISSUE THREAD

**Issue by debabrataroy718** [airbnb/lottie-ios#1331]
Hi,
I am getting issues when i display the Lottie file. it showing partial animation. I have attracted a video and JSON file.

**Pod version:** 3.2.1
**language**: Swift

Code:
`self.loattieAnimation = AnimationView(name: "AppLoading")`
 `self.loattieAnimation?.autoresizingMask = [.flexibleHeight, .flexibleWidth]`
 ` self.loattieAnimation?.contentMode = .scaleAspectFill`
  `self.loattieAnimation?.frame = self.view.bounds`
  `self.view.addSubview(self.loattieAnimation!)`
  
  
  
  
[AppLoading.json.zip](https://github.com/airbnb/lottie-ios/files/6230289/AppLoading.json.zip)

https://user-images.githubusercontent.com/58464481/113018214-ec94cd80-919d-11eb-8300-25f847a03d3d.mov

Thanks

**Comment by calda** [comment]
This animation appears to render correctly on `master`. Thanks for the report!
