### ISSUE TITLE
The animation stops when I navigate to other page and go back

### ISSUE THREAD

**Issue by IHNEL** [airbnb/lottie-ios#1332]
## Lottie-iOS Issue

I create a custom LottieView like below, it works fine for me with looping. However, when I navigate to other page then go back, the animation stops. I don't find anyway to restart or resume it.  Could someone help me please?

```
import SwiftUI
import Lottie
//Following this tutorial: https://designcode.io/swiftui-handbook-lottie-animation 
struct LottieView: UIViewRepresentable {
    var name = "success"
    var loopMode: LottieLoopMode = .loop
    
    func makeUIView(context: UIViewRepresentableContext<LottieView>) -> UIView {
        let view = UIView(frame: .zero)
        let animationView = AnimationView()
        let animation = Animation.named(name)
        animationView.animation = animation
        animationView.contentMode = .scaleAspectFit
        animationView.play()
        animationView.translatesAutoresizingMaskIntoConstraints = false
        animationView.loopMode = loopMode
        view.addSubview(animationView)
        NSLayoutConstraint.activate([
            animationView.heightAnchor.constraint(equalTo: view.heightAnchor),
            animationView.widthAnchor.constraint(equalTo: view.widthAnchor),
        ])
        return view
    }
    func updateUIView(_ uiView: UIView, context: UIViewRepresentableContext<LottieView>) {
    }
}

```

## Check these before submitting:
- [v] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [v] This issue isn't related to another open issue

## This issue is a:
- [v] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [v] iOS

## What Language are you in?
- [v] Swift
- [] Objective-C

**Comment by BannaGo** [comment]
i meet the same problem

**Comment by 007-Heroa** [comment]
animationView.backgroundBehavior = .pauseAndRestore

**Comment by BeyondChallenge** [comment]
same problem

**Comment by fchiusolo** [comment]
+1

**Comment by ssoubhik** [comment]
The same Problem is on TabView also.
Animation freezes if I slide back to a previous tab

**Comment by bluerainxty** [comment]
i meet the same problem

**Comment by ngay881855** [comment]
> animationView.backgroundBehavior = .pauseAndRestore

This solved the problem. I think this issued can be marked as invalid.

**Comment by User-Lawn** [comment]
i meet the same problem.....

**Comment by calda** [comment]
Should we make `.pauseAndRestore` the default in Lottie 4.0? Feedback is welcome: https://github.com/airbnb/lottie-ios/discussions/1649

**Comment by Fredposk** [comment]
Adding an `.id(UUID())` modifier to the LottieView will keep it from updating and breaking animations when other views change `State` and invalidate the struct

**Comment by calda** [comment]
In Lottie 4.0 we are changing the default behavior of `LottieBackgroundBehavior` from `.pause` to `.pauseAndRestore`, which should fix the underlying issue here.

**Comment by ronitbluesemi** [comment]
> animationView.backgroundBehavior = .pauseAndRestore

Thanks your solution is working for me

**Comment by chitgoks** [comment]
Why not make this as the default value for backgroundBehavior?

**Comment by calda** [comment]
`pauseAndRestore` is the default behavior starting in Lottie 4.0 and later
