### ISSUE TITLE
Encoding Animation to data failure

### ISSUE THREAD

**Issue by Polenoso** [airbnb/lottie-ios#1333]
We implemented our own animation cache provider, so we've implemented the protocol `AnimationCacheProvider`.
This animation provider is a file provider where we just read from the file bundle and when we need to save the animation to the cache we encode the received animation to data. 

The problem is that the saved file is not equal to the file downloaded by the download task.
<code shared>
It seems that all the data received in the .json file is not decoded into the Animation object so once we encode the Animation to Data some info is lost.

To test the difference between the json files (the one in the server and the one in the disk after encoding from Animation) we used the FileMerge tool to compare both files and they seem different.

## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.2.0

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Code Example
```
final class LottieFileProvider: AnimationCacheProvider {
    static var shared = LottieFileProvider()
    
    private let urlBuilder: LottieFileURLBuilding
    
    init(urlBuilder: LottieFileURLBuilding = LottieFileURLBuilder()) {
        self.urlBuilder = urlBuilder
    }
    
    func animation(forKey: String) -> Animation? {
        do {
            let path = urlBuilder.buildPath(for: forKey)
            let data = try Data(contentsOf: path)
            return try JSONDecoder().decode(Animation.self, from: data)
        } catch {
            return nil
        }
    }
    
    func setAnimation(_ animation: Animation, forKey: String) {
        do {
            let path = urlBuilder.buildPath(for: forKey)
            let directory = urlBuilder.directory
            try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true, attributes: nil)
            let data = try JSONEncoder().encode(animation)
            try data.write(to: path)
        } catch {
           print(error.localizedDescription)
        }
    }
    
    func clearCache() {
        do {
            let url = urlBuilder.directory
            try FileManager.default.removeItem(at: url)
        } catch {
           print(error.localizedDescription)
        }
    }
}
```
## Animation JSON

[animation_example.json.zip](https://github.com/airbnb/lottie-ios/files/6243048/animation_example.json.zip)

**Comment by mlch911** [comment]
I have the same problem. Any updates ?

**Comment by Polenoso** [comment]
@mlch911 we wrote an article last year with an adhoc solution. I hope it helps.

https://medium.com/inside-wallapop/building-your-own-cache-for-lottie-files-in-ios-6b387fce2f37

**Comment by mlch911** [comment]
> @mlch911 we wrote an article last year with an adhoc solution. I hope it helps.
> 
> https://medium.com/inside-wallapop/building-your-own-cache-for-lottie-files-in-ios-6b387fce2f37

ok. I cached those json files rather than `Animation` Models just like your article.
