### ISSUE TITLE
Updating textProvider does not recursively apply the textProvider into PreCompositionLayers

### ISSUE THREAD

**Issue by itsallmememe** [airbnb/lottie-ios#1334]
## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [X] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?
Lottie 3.2.1

## What Platform are you on? 

- [] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift
- [] Objective-C

## Expected Behavior 
Updating the `AnimationView.textProvider` property should recursively propagate the `AnimationTextProvider` through the `PreCompositionLayer`'s enclosed `TextCompositionLayer`'s and `PreCompositionLayer`'s.

## Actual Behavior
Supplying a AnimationTextProvider using `AnimationView.init()` ensures that the textProvider is propgated to all enclosed `TextCompositionLayer`, `PreCompositionLayer` and their subsequent enclosed `TextCompositionLayer`'s . This works as expected.

However, if I later update the `AnimationView.textProvider` property the new value *does not* propagate through the `PreCompositionLayer`'s. It is only sent to the the top level `TextCompositionLayer`'s.

## Code Example
Works as expected. The textprovider is recursively sent to all the TextCompositionLayers and PreCompositionLayers.
```
let lottieAnimation = Animation.filepath("path_to_lottie_with_precomposed_text_layers")!
let textProvider = CustomTextProvider()
let lottieView = AnimationView(animation: lottieAnimation, textProvider: textProvider)
```

Later on... if I update the textProvider then the new class is *not* propagated through the PreCompositionLayers.
```
let newTextProvider = NewCustomTextProvider()
lottieView.textProvider = newTextProvider
```

## Animation JSON
Can send this if you require. Please mention me and I'll email over.

**Comment by calda** [comment]
I believe this is fixed but could be mistaken, feel free to re-open if its still an issue
