### ISSUE TITLE
iOS 10 Release Bitcode Crash

### ISSUE THREAD

**Issue by StratusHunter** [airbnb/lottie-ios#1336]
## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [X] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [X] iOS

## What Language are you in?
- [] Swift
- [X] Objective-C

## Expected Behavior 

When building with bitcode enabled iOS 10 devices should not crash on init.

## Actual Behavior

iOS 10 live builds with bitcode enabled is crashing on init.

## Code Example
Firebase:
__hidden#2494_ line 81
Animation.init(from:)

Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000000fffffffc

Crashed: com.apple.main-thread
0  <APP>                          0x126c9c Animation.init(from:) + 81 (__hidden#2494_:81)
***********

2  libswiftCore.dylib             0x94357f swift_stdlib_getDescription + 843596
3  libswiftFoundation.dylib       0xb5246b (Missing)
4  libswiftFoundation.dylib       0xb367d7 (Missing)
5  libswiftFoundation.dylib       0xbfd1b7 (Missing)
***********
11 UIKit                          0x2179b95b -[UINib instantiateWithOwner:options:] + 1890
12 UIKit                          0x2179d593 -[NSBundle(UINSBundleAdditions) loadNibNamed:owner:options:] + 190
***********
17 UIKit                          0x212cbeb7 -[UIViewController loadViewIfRequired] + 966
18 UIKit                          0x212e2ee9 -[UIViewController __viewWillAppear:] + 118
19 UIKit                          0x21460a8f -[UINavigationController _startCustomTransition:] + 1100
20 UIKit                          0x2137e8f5 -[UINavigationController _startDeferredTransitionIfNeeded:] + 652
21 UIKit                          0x2137e58d -[UINavigationController __viewWillLayoutSubviews] + 50
22 UIKit                          0x2137e50d -[UILayoutContainerView layoutSubviews] + 196
23 UIKit                          0x212c9483 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1224
24 QuartzCore                     0x1ef21cb7 -[CALayer layoutSublayers] + 126
25 QuartzCore                     0x1ef15d77 CA::Layer::layout_if_needed(CA::Transaction*) + 354
26 QuartzCore                     0x1ef15c05 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 16
27 QuartzCore                     0x1eea4839 CA::Context::commit_transaction(CA::Transaction*) + 320
28 QuartzCore                     0x1eec2fdb CA::Transaction::commit() + 578
29 UIKit                          0x2153d805 _UIApplicationFlushRunLoopCATransactionIfTooLate + 172
30 UIKit                          0x21a5a3f1 __handleEventQueue + 4784
31 UIKit                          0x21a5a57d __handleHIDEventFetcherDrain + 144
32 CoreFoundation                 0x1c05bfdd __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 12
33 CoreFoundation                 0x1c05bb05 __CFRunLoopDoSources0 + 424
34 CoreFoundation                 0x1c059f51 __CFRunLoopRun + 1160
35 CoreFoundation                 0x1bfad1af CFRunLoopRunSpecific + 470
36 CoreFoundation                 0x1bfacfd1 CFRunLoopRunInMode + 104
37 GraphicsServices               0x1d757b41 GSEventRunModal + 80
38 UIKit                          0x2132fa53 UIApplicationMain + 150
39 <APP>                         0x29869d main + 18 (main.m:18)
40 libdyld.dylib                  0x1b79a4eb <redacted> + 2

## Animation JSON

Any animation causes the crash

**Comment by StratusHunter** [comment]
This is when importing using SPM (in case that makes any difference)

Also to clarify I'm importing the Swift version of the library into an Objective-C project then using the compat classes to load the animation. (See below)

````
    CompatibleAnimation *const lotAnimation = [[CompatibleAnimation alloc] initWithName:animation bundle:[NSBundle mainBundle]];

    if (self.animationView == nil) {

        self.animationView = [[CompatibleAnimationView alloc] initWithFrame:self.animationContainer.bounds];
        self.animationView.contentMode = UIViewContentModeScaleAspectFit;
        self.animationView.loopAnimationCount = -1;
        self.animationView.translatesAutoresizingMaskIntoConstraints = YES;
        [self.animationContainer addSubview:self.animationView];
    }

**Comment by calda** [comment]
Closing since Lottie no longer supports iOS 10
