### ISSUE TITLE
Animation flickers at end of loop only on IOS

### ISSUE THREAD

**Issue by timothy** [airbnb/lottie-ios#1340]
## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [?] This issue isn't related to another open issue: [Maybe this but not sure it was reported a while ago for a different version...](https://github.com/airbnb/lottie-ios/issues/1297)

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.2.1

## What Platform are you on? 

- [] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift
- [] Objective-C

## Expected Behavior 

The expected behavior is to not have the flicker at the end of the animation but to instead smoothly loop. The idea is to have the waves smoothly look like they are continuously falling.

## Actual Behavior

![screen flicker](https://user-images.githubusercontent.com/7410132/116302665-13c3c800-a767-11eb-9882-8a49fa9a32d9.gif) 

## Animation JSON

I emailed brandon@withrow.io with JSON.  

Let me know if more details are needed. Thanks!

**Comment by ewjc** [comment]
Simple test of this behavior:

[lottie test.zip](https://github.com/airbnb/lottie-ios/files/6387390/lottie.test.zip)

**Comment by ferico55** [comment]
hi @ewjc I would like to look deeper into this. can you please upload the animation file here or send it to my email at ferico55@gmail.com

**Comment by ferico55** [comment]
I dug deeper into this and found that this is caused by the json file that is trying to animate the `opacity` within the `Fill` of the shape. Somehow the opacity value interpolation for this `FillNode` is a bit wrong.

The work around I suggested via email is to animate opacity value for the whole layer thus affecting `ShapeCompositionLayer`'s opacity rather than the fill. And it works (at least for now). I will keep trying to find out why the fill transition is inaccurate

**Comment by DidierCOQUARD** [comment]
Bonjour à Vous et encore Merci

**Comment by DracoRubi** [comment]
Hi! Any update on this issue?

If not, I'd appreciatte a tip on how exactly can I use the workaround mentioned by ferico55. Honestly, I have no clue on how to animate opacity value for the whole layer.

**Comment by ferico55** [comment]
@DracoRubi unfortunately I still unable to pinpoint the issue in the code. But animating the whole layer as I mentioned will be different depends on the app you used. In this case, they used KeyShape. can you share with me your json file and raw animation files? .ae or .keyshape I will help you with the workaround

**Comment by DracoRubi** [comment]
@ferico55 Sorry for the delay in the answer! This is my json file for the animation:
[LoaderJson.zip](https://github.com/airbnb/lottie-ios/files/6540991/LoaderJson.zip)

**Comment by calda** [comment]
@timothy, could you share a copy of your animation json? I tested the one @DracoRubi shared and it seems to work correctly when I test it on master.
