### ISSUE TITLE
Rendering issue on macOS, console outputs  "CGBitmapContextGetWidth: invalid context"

### ISSUE THREAD

**Issue by jimmycoyne** [airbnb/lottie-ios#1342]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [x] MacOS
- [] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 

<img width="344" alt="Screenshot 2021-04-28 at 07 02 51" src="https://user-images.githubusercontent.com/130512/116354057-c3447d00-a7ef-11eb-9368-4075ca0fd0f2.png">
## Actual Behavior

<img width="443" alt="Screenshot 2021-04-28 at 07 00 21" src="https://user-images.githubusercontent.com/130512/116353857-68ab2100-a7ef-11eb-8a5b-bb8173e9a20c.png">

## Code Example
Used macOS sample app.

``` swift
  override func viewDidLoad() {
    super.viewDidLoad()
    
    let animation = Animation.named("reaction-test2", subdirectory: "TestAnimations")
    let animationView  = AnimationView(animation: animation)
    view.addSubview(animationView)
    self.preferredContentSize = animationView.bounds.size
    animationView.loopMode = .loop
    animationView.play()
  }
  ````

## Animation JSON

[reaction-test2-json.txt](https://github.com/airbnb/lottie-ios/files/6389412/reaction-test2-json.txt)

Renders correcly on iOS but missing a layer on macOS. See the following console output

```
CGBitmapContextGetWidth: invalid context 0x6000022e06c0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE
```

With CG_CONTEXT_SHOW_BACKTRACE enabled 

```
CG_CONTEXT_SHOW_BACKTRACE
[com.airbnb.lottie-swift-macOS] CGBitmapContextGetWidth: invalid context 0x60000321ea00. Backtrace:
  <CGBitmapContextGetWidth+76>
   <$s6Lottie20GradientFillRendererC6renderyySo12CGContextRefaF+2096>
    <$s6Lottie20GradientFillRendererCAA10RenderableA2aDP6renderyySo12CGContextRefaFTW+20>
     <$s6Lottie16ShapeRenderLayerC4draw2inySo12CGContextRefa_tFTo+212>
      <CABackingStoreUpdate_+180>
       <___ZN2CA5Layer8display_Ev_block_invoke+64>
        <-[CALayer _display]+1732>
         <_ZN2CA5Layer17display_if_neededEPNS_11TransactionE+768>
          <_ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd+432>
           <_ZN2CA11Transaction6commitEv+732>
            <_ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv+144>
             <__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__+36>
              <__CFRunLoopDoObservers+576>
               <CFRunLoopRunSpecific+684>
                <RunCurrentEventLoopInMode+292>
                 <ReceiveNextEventCommon+320>
                  <_BlockUntilNextEventMatchingListInModeWithFilter+76>
                   <_DPSNextEvent+868>
                    <-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]+1312>
                     <-[NSApplication run]+600>
                      <NSApplicationMain+1064>
                       <main+12>                        <start+4>
                       ```

Note: Just tested on the 2.x branch and  renders correctly.

**Comment by jimmycoyne** [comment]
When we have a layer with opacity gradient,  the width and height of CGContext in GradientFillRenderer  are empty. As a test, I hardwired some values for height/width and the annimation rendered correctly. 

``` swift 

  let maskContext = CGContext(data: nil,
                                    width: inContext.width,
                                    height: inContext.height,
                                    bitsPerComponent: 8,
                                    bytesPerRow: inContext.width,
                                    space: maskColorSpace,
                                    bitmapInfo: 0) else { return }

```

Happy to dig a bit deeper if some one could advice. As the entry point for this tick of runloop is ShapeRenderLayer.draw with an invalid width/height context, it is not clear where to investigate next. 

``` Swift
  override func draw(in ctx: CGContext) {
    if let path = renderer.outputPath {
      if !path.isEmpty {
        ctx.addPath(path)
      }
    }
    renderer.render(ctx)
  }
  ```

**Comment by calda** [comment]
I'm no longer able to reproduce this issue when testing with Lottie 4.0 -- feel free to re-open this issue if you're able to reproduce the problem again.
