### ISSUE TITLE
Animation is playing different on iOS and web

### ISSUE THREAD

**Issue by kumamoo** [airbnb/lottie-ios#1350]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [ ] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.2.2

## What Platform are you on? 

- [ ] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [ ] Objective-C

## Expected Behavior 

![image](https://user-images.githubusercontent.com/25575220/117944704-1fef7e00-b340-11eb-98b9-2288fe4955f5.png)

## Actual Behavior

**The little girl's eyes disappeared, but the same JSON file works perfectly on Android or Preview on Lottie website.**
![IMG_8534](https://user-images.githubusercontent.com/25575220/117944401-ce46f380-b33f-11eb-8761-38636ef09f53.PNG)

## Animation JSON

[data.json.zip](https://github.com/airbnb/lottie-ios/files/6464860/data.json.zip)

**Comment by roarapps** [comment]
This isn't the most helpful comment, but girl without eyes is scary as f!

**Comment by rahveekotadiya** [comment]
Have you found any solution for this issue? @kumamoo.

**Comment by calda** [comment]
This appears to work correctly now on `master`:

<img src="https://user-images.githubusercontent.com/1811727/182741725-569730ac-9db8-4a93-aaa1-2bcc4fdd5af9.png" width=350>
