### ISSUE TITLE
Safari Playback "Lags" Or Is "Slow"... What Do We Do? 

### ISSUE THREAD

**Issue by c062785** [airbnb/lottie-ios#1351]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [x] MacOS
- [x] iOS

## What Language are you in?
- [] Swift
- [] Objective-C

## Expected Behavior 

Should play like it does on Chrome, fast, smooth. See link : https://lottie-test-f146f3.webflow.io/

https://user-images.githubusercontent.com/28090764/118144879-d0ea2d00-b3c1-11eb-8f35-cfe607841617.mov

## Actual Behavior

Safari makes the Lottie 'lag' and load slowly. 

We embedded the lottie from 'lottiefiles' upload and the same thing happens in Safari. Only way that it plays 'faster' is if the actual size of the embed is 300 x 300px..

Unsure if it is the lot files or what? 

https://user-images.githubusercontent.com/28090764/118145020-f5dea000-b3c1-11eb-898b-a46c4d3e60e8.mov

## Animation JSON

Emailed 'lottie' to Brandon.

**Comment by ferico55** [comment]
Hi @c062785 you might want to direct your issue to the lottie-web repo here https://github.com/airbnb/lottie-web

**Comment by c062785** [comment]
Ferico, 

Thank you, I’ll try posting there. 

Chris
