### ISSUE TITLE
Reduced rendering quality after removing `renderScale` in 3.2.2

### ISSUE THREAD

**Issue by sochalewski** [airbnb/lottie-ios#1353]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [ ] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [ ] Feature Request
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.2.3

## What Platform are you on? 

- [ ] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [ ] Objective-C

## Expected Behavior 
Assets are rendered in high quality on Retina devices as in 3.2.1 and lower.

![before](https://user-images.githubusercontent.com/5808283/118618589-0f1d8d00-b7c4-11eb-9555-813140e7cd41.jpg)
Lottie View as the left bar button item.

## Actual Behavior
Assets are rendered in low quality on Retina devices in 3.2.2 and greater (see #1328).

![after](https://user-images.githubusercontent.com/5808283/118618606-12b11400-b7c4-11eb-9096-4098c2d945ed.jpg)
Lottie View as the left bar button item.

## Compare
![compare](https://user-images.githubusercontent.com/5808283/118619386-d500bb00-b7c4-11eb-990f-e0eac3d2441a.jpg)
Zoomed 2x, 3.2.1 on the left, 3.2.3 on the right.

## Code Example
Does not matter.

## Animation JSON
Does not matter.

**Comment by astrokin** [comment]
have the same issue

**Comment by absolute-heike** [comment]
Just a quick note: This seems to be related to https://github.com/airbnb/lottie-ios/issues/1363 and https://github.com/airbnb/lottie-ios/issues/1022#issuecomment-556124547

I'm trying to figure out the right place to fix this issue. If you need a quickfix: there is a manual way of fixing this inside of After Effects

> For now it can be fixed in after effects by manually scaling the path up and resetting the scale of the group/layer to <=100%

**Comment by absolute-heike** [comment]
@astrokin @sochalewski Great News: I found the reason for the Bug and already fixed it. I will still have to refactor Gradient Stroke Rendering before opening up a PR, but I hope that this won't take too long: https://github.com/airbnb/lottie-ios/issues/1363#issuecomment-892521993
