### ISSUE TITLE
Some portion of animation layer is missing in iOS

### ISSUE THREAD

**Issue by AnilkumarRabhasa** [airbnb/lottie-ios#1355]
Thanks for the great library. For 2 animations, its getting missing some portion of animation.

I am using iOS and version is   pod 'lottie-ios', '3.2.3'

How to fix this, its working for android and web also fine.

Only missing some portion of animation in iOS.

Any solutions?
For me its urgent fix needed.

Any suggestions will be highly appreciate

**Comment by rahveekotadiya** [comment]
Same here have you found any solution because it work on well in android and web.

**Comment by AnilkumarRabhasa** [comment]
@rahveekotadiya From library, I did not get any solution, Our json file we have modified into multiple parts then it worked.

**Comment by calda** [comment]
Could you share a copy of your animation json?
