### ISSUE TITLE
DEAD_CODE_STRIPPING still required?

### ISSUE THREAD

**Issue by sehdich** [airbnb/lottie-ios#1356]

**Comment by Oleh-H** [comment]
Why this setting needs to be disabled?

**Comment by markuspb** [comment]
It's still mentioned in the README file - do we have an update on this one?

**Comment by markuspb** [comment]
it's mentioned to be needed cause of https://bugs.swift.org/plugins/servlet/mobile#issue/SR-11564 - however, I did not experience using that flag in any other external library...

**Comment by calda** [comment]
Removed this from the README
