### ISSUE TITLE
Major performance hit on Android when using track mattes out of After Effects

### ISSUE THREAD

**Issue by sureMOE** [airbnb/lottie-ios#136]
This seems to be an issue that's relegated to Android playback of JSON files that isn't reproducible on iOS. When using track mattes from After Effects, frame rates just plummet. Not sure what exactly is going on, but wondering if anybody else has seen same issues.

**Comment by buba447** [comment]
Can you add this issue over at the Android repo?
We will be able to better track and assist you there. https://github.com/airbnb/lottie-android
