### ISSUE TITLE
Support multi-platform Xcode Projects (iOS and macOS) in Swift Package Manager

### ISSUE THREAD

**Issue by bigadz** [airbnb/lottie-ios#1361]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [x] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 
- [x] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 

For a SwiftUI cross-platform application with multiple Xcode targets (iOS AND macOS), I expect to be able to include Lottie for iOS and macOS in the one Xcode project.

i.e. these two:

https://github.com/airbnb/lottie-ios (branch: `master`)
https://github.com/airbnb/lottie-ios (branch: `lottie/macOS-spm`)

## Actual Behavior

Xcode won't allow the unique repo (https://github.com/airbnb/lottie-ios) to be added a second time, so I'm forced to choose one of the two available branches.

Workaround: I can fork the airbnb repo, thereby creating the second repo for Xcode to recognise. 

Better solutions: Either

1.  Move the macOS branch of the `airbnb/lottie-ios` repo to its own `airbnb/lottie-macos` repo, or
2. Support cross-platform within the existing `airbnb/lottie-ios` repo.

Thank you!

**Comment by xbladesub** [comment]
Same issue... Added macOS version via SPM and iOS version via CocoaPods. Getting an error while building iOS target:

Multiple targets match implicit dependency for linker flags '-framework Lottie'. Consider adding an explicit dependency on the intended target to resolve this ambiguity. (in target 'iOS' from project 'XXX')

**Comment by xbladesub** [comment]
> ## Check these before submitting:
> * [x]  The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
> * [x]  This issue isn't related to another open issue
> 
> ## This issue is a:
> * [] Non-Crashing Bug (Visual or otherwise)
> * [] Crashing Bug
> * [x]  Feature Request
> * [] Regression (Something that once worked, but doesn't work anymore)
> 
> ## Which Version of Lottie are you using?
> Lottie 3.0
> 
> ## What Platform are you on?
> * [x]  MacOS
> * [x]  iOS
> 
> ## What Language are you in?
> * [x]  Swift
> * [] Objective-C
> 
> ## Expected Behavior
> For a SwiftUI cross-platform application with multiple Xcode targets (iOS AND macOS), I expect to be able to include Lottie for iOS and macOS in the one Xcode project.
> 
> i.e. these two:
> 
> https://github.com/airbnb/lottie-ios (branch: `master`)
> https://github.com/airbnb/lottie-ios (branch: `lottie/macOS-spm`)
> 
> ## Actual Behavior
> Xcode won't allow the unique repo (https://github.com/airbnb/lottie-ios) to be added a second time, so I'm forced to choose one of the two available branches.
> 
> Workaround: I can fork the airbnb repo, thereby creating the second repo for Xcode to recognise.
> 
> Better solutions: Either
> 
> 1. Move the macOS branch of the `airbnb/lottie-ios` repo to its own `airbnb/lottie-macos` repo, or
> 2. Support cross-platform within the existing `airbnb/lottie-ios` repo.
> 
> Thank you!

Helped "dirty fork" solution 🎉

**Comment by xbladesub** [comment]
"dirty fork" solution helped 🎉

**Comment by Moriquendi** [comment]
It looks like SPM doesn't support conditional exclusion of certain folders. 
Correct me if I'm wrong but the only solution would be to add `#if os(macOS) ... #endif` macros in all the files in Public/iOS. Meh.
Maybe someone could write a script that appends those lines automatically so it'd be easier to maintain?

**Comment by chuynadamas** [comment]
Just open a PR using the ```macros``` approach to integrate the multi-platform support 👆
