### ISSUE TITLE
Gradient rendering regression in Lottie 3+ compared to ObjC

### ISSUE THREAD

**Issue by absolute-heike** [airbnb/lottie-ios#1363]
@buba447 I am currently debugging the gradient regression in 3.2.2 and found out, that this regression was already introduced when switching from Obj-C to Swift.
The problem seems to be related to layers scaled inside of After Effects. The sample animation contains 3 layers:
1. A shape with the size of 23x23
2. A linear gradient
3. A transform that scales this shape up

When debugging the different versions I am seeing that the context size is 46x46 in `Obj-C` as well as Swift `3.2.2`. Context size in Swift `3.2.1` is 3 times as high (138x138) which has a drastic impact on performance and still looks way worse than Obj-C.

I couldn't find any significant difference in the gradient rendering code, so I assume that the issue is related to shape rendering or transform handling in Lottie-Swift.

Any hints, where I should have a deeper look to track down the bug?

## Comparison
https://user-images.githubusercontent.com/522881/120313618-88e06b00-c2da-11eb-809e-51c45227d7c4.mov

## Animation JSON
[gradient-animation.json.zip](https://github.com/airbnb/lottie-ios/files/6575772/gradient-animation.json.zip)

## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?
Lottie 3.0

## What Platform are you on?

- [] MacOS
- [x] iOS

**Comment by absolute-heike** [comment]
This seems to be related to https://github.com/airbnb/lottie-ios/issues/1022#issuecomment-556124547

Now I just need to figure out the right place to make this change^^

**Comment by absolute-heike** [comment]
@buba447 I finally figured it out! 🎉

The issue is with the way the path is rendered. In ObjC the path was solved with a `CAShapeLayer` as a mask whereas Swift adds the path to the `CGContext` directly.

When the `CAShapeLayer` is scaled up with a transform, it's scaled razer-sharp. But `CGContext.addPath()` is rendered at low resolution and only transformed afterwards

The solution I'm now aiming for now is:
Remove `renderer.shouldRenderInContext` altogether and migrate `GradientFillRenderer` and `GradientStrokeRenderer` to be layer-backed (Just as in ObjC, if I got this right). This way the gradients can continue to be rendered in low resolution while the path is rendered correctly which would make sure, that there is no performance hit compared to ObjC.

**Comment by absolute-heike** [comment]
Great News! I fixed the path rendering for gradients!

Turns out that `context.addPath()` doesn't scale up the Path when a transform is applied to the Layer. I went back to the way ObjC applied the Path which is by adding a mask on top of a Gradient Layer. This fixes the scaling and in combination with the new Lottie 3 way of rendering Gradients to alpha results in even faster performance for these animations than even Lottie 2.5 could handle.

I will still have to refactor Gradient Strokes before I can open up a PR.

Will try to create a Benchmark comparison between Lottie 2.5.x, Lottie 3.2.0 and my fix just out of curiosity 😁

**Comment by Tibimac** [comment]
@absolute-heike Hi and thanks a lot for this fix because I actually face with this problem 😕
When can we expect a new release with this fix ?

**Comment by Tibimac** [comment]
@buba447 Hello Brandon, Do you think we can expect this to be merged soon? It fix a critical bug so it would be more than nice to include it in next release. Thanks a lot in advance.

**Comment by calda** [comment]
I believe this was resolved by #1558, thanks all!
