### ISSUE TITLE
Swift Compiler Error - Xcode beta 13.0

### ISSUE THREAD

**Issue by TwanLuttik** [airbnb/lottie-ios#1366]
I'm currently using Xcode beta 13.0 and I getting swift compiling errors when building for production on iOS 15

**Versions**
lottie-ios: 3.2.3
littie-react-native: 4.0.2
react-native: 0.64.1

**Platform**
iOS

**Language**
Swift

**Error**
`Command /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1`

**What I did to maybe resolve the issue**
- Cleaning the build folder
- Deleting derived data
- reinstall with yarn
- reinstalled pods

**Update (42 minutes later)**
I tested it out with the regular Xcode 12 and it builds fine without any compiling issues

**Comment by hervenivon** [comment]
Any update on this one?

**Comment by calda** [comment]
Closing since this seems like a potentially outdated issue. Feel free to re-open if you're still experiencing this issue.
