### ISSUE TITLE
Deprecation warning for the use of `class` in protocol inheritance

### ISSUE THREAD

**Issue by codedbypm** [airbnb/lottie-ios#1369]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.2.1

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 
The compiler should not spit out warning about `class` being deprecated as protocol inheritance in favor of `AnyObject`

## Actual Behavior
The compiler spits this out when building with fastlane

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/17159280/122651618-4e7c2800-d13a-11eb-901a-fbf17f015575.png">

**Comment by amit2908** [comment]
This seems fixed and must be closed!!

**Comment by kachalo** [comment]
Issue still exists in `lottie/macos-spm` branch.
