### ISSUE TITLE
ios9 crash

### ISSUE THREAD

**Issue by wmh8638** [airbnb/lottie-ios#1370]
xcode 12.2 ios9 carsh
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x20)
    frame #0: 0x0000000182890160 libobjc.A.dylib`objc_release + 16
  * frame #1: 0x00000001101982d0 Lottie`AnimationContainer.init(animation=0x000000013322a170, imageProvider=0x000000013335f360, textProvider=0x00000001308cfe30, fontProvider=0x00000001308d19f0) at AnimationContainer.swift:113:28
    frame #2: 0x0000000110197fec Lottie`AnimationContainer.__allocating_init(animation:imageProvider:textProvider:fontProvider:) at AnimationContainer.swift:0
    frame #3: 0x00000001101a58dc Lottie`AnimationView.makeAnimationLayer(self=0x00000001308cfbc0) at AnimationView.swift:817:26
    frame #4: 0x00000001101a562c Lottie`AnimationView.animation.didset(self=0x00000001308cfbc0) at AnimationView.swift:65:7
    frame #5: 0x00000001101a5b4c Lottie`AnimationView.animation.setter(value=0x000000013322a170, self=0x00000001308cfbc0) at AnimationView.swift:0
    frame #6: 0x0000000100ab6f54 MyChevySwift`closure #1 in SGMRefreshHeader.loadingView.getter at SGMRefreshHeader.swift:16:33
    frame #7: 0x0000000100ab63f8 MyChevySwift`SGMRefreshHeader.loadingView.getter(self=0x00000001333619a0) at SGMRefreshHeader.swift:12:52
    frame #8: 0x0000000100ab6bd0 MyChevySwift`SGMRefreshHeader.state.didset(self=0x00000001333619a0) at SGMRefreshHeader.swift:35:17
    frame #9: 0x0000000100ab6b58 MyChevySwift`SGMRefreshHeader.state.setter(value=idle, self=0x00000001333619a0) at SGMRefreshHeader.swift:0
    frame #10: 0x0000000100ab6ac8 MyChevySwift`@objc SGMRefreshHeader.state.setter at <compiler-generated>:0
    frame #11: 0x000000011061fbb4 MJRefresh`-[MJRefreshComponent initWithFrame:](self=0x00000001333619a0, _cmd="initWithFrame:", frame=(origin = (x = 0, y = 0), size = (width = 0, height = 0))) at MJRefreshComponent.m:26:14
    frame #12: 0x0000000100ab6770 MyChevySwift`SGMRefreshHeader.init(frame=(origin = (x = 0, y = 0), size = (width = 0, height = 0))) at SGMRefreshHeader.swift:23:15
    frame #13: 0x0000000100ab69d4 MyChevySwift`@objc SGMRefreshHeader.init(frame:) at <compiler-generated>:0
    frame #14: 0x0000000110623424 MJRefresh`+[MJRefreshHeader headerWithRefreshingBlock:](self=MyChevySwift.SGMRefreshHeader, _cmd="headerWithRefreshingBlock:", refreshingBlock=0x000000010081a794) at MJRefreshHeader.m:23:28
    frame #15: 0x0000000100a027e8 MyChevySwift`@nonobjc MJRefreshGifHeader.__allocating_init(refreshingBlock:) at <compiler-generated>:0
    frame #16: 0x0000000100d6d350 MyChevySwift`SGMDiscoveryVC.viewDidLoad(self=0x00000001309ae810) at SGMDiscoveryVC.swift:229:68
    frame #17: 0x0000000100d6f534 MyChevySwift`@objc SGMDiscoveryVC.viewDidLoad() at <compiler-generated>:0
    frame #18: 0x0000000188370c40 UIKit`<redacted> + 996
    frame #19: 0x0000000188431230 UIKit`<redacted> + 72
    frame #20: 0x0000000188431108 UIKit`<redacted> + 416
    frame #21: 0x0000000188430350 UIKit`<redacted> + 144
    frame #22: 0x000000018842fef4 UIKit`<redacted> + 868
    frame #23: 0x000000018842fb1c UIKit`<redacted> + 60
    frame #24: 0x000000018842fa84 UIKit`<redacted> + 208
    frame #25: 0x000000018836c1e4 UIKit`<redacted> + 656
    frame #26: 0x0000000185cfe994 QuartzCore`<redacted> + 148
    frame #27: 0x0000000185cf95d0 QuartzCore`<redacted> + 292
    frame #28: 0x0000000185cf9490 QuartzCore`<redacted> + 32
    frame #29: 0x0000000185cf8ac0 QuartzCore`<redacted> + 252
    frame #30: 0x0000000185cf8820 QuartzCore`<redacted> + 500
    frame #31: 0x0000000185cf1de4 QuartzCore`<redacted> + 80
    frame #32: 0x00000001831c8728 CoreFoundation`<redacted> + 32
    frame #33: 0x00000001831c64cc CoreFoundation`<redacted> + 372
    frame #34: 0x00000001830f0c70 CoreFoundation`CFRunLoopRunSpecific + 416
    frame #35: 0x00000001883df94c UIKit`<redacted> + 460
    frame #36: 0x00000001883da088 UIKit`UIApplicationMain + 204
    frame #37: 0x0000000116fb5468 libswiftUIKit.dylib`UIKit.UIApplicationMain(Swift.Int32, Swift.Optional<Swift.UnsafeMutablePointer<Swift.UnsafeMutablePointer<Swift.Int8>>>, Swift.Optional<Swift.String>, Swift.Optional<Swift.String>) -> Swift.Int32 + 168
    frame #38: 0x0000000100c0a4dc MyChevySwift`static UIApplicationDelegate.main() at <compiler-generated>:0
    frame #39: 0x0000000100c0a454 MyChevySwift`static AppDelegate.$main(self=MyChevySwift.AppDelegate) at <compiler-generated>:0
    frame #40: 0x0000000100c0a520 MyChevySwift`main at <compiler-generated>:0
    frame #41: 0x0000000182c8e8b8 libdyld.dylib`<redacted> + 4

**Comment by luzsyn** [comment]
iOS9 crash  +1

**Comment by calda** [comment]
Lottie no longer supports iOS 9
