### ISSUE TITLE
Export Working fine on web player but does not work when tested on ios

### ISSUE THREAD

**Issue by OferHealthy** [airbnb/lottie-ios#1376]
Hello,
I am new to Lottie and this is my first time posting.
I am an animator in my profession, so please forgive me current lack of knowledge in coding.
Nice to meet you all.

## Check these before submitting:
- [V] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Bodymovin 5.7.11, LottieFiles [Couldn't find the version but it's the latest]

## What Platform are you on? 

- [] MacOS
- [] iOS
I work on a PC
Windows 10, Ae 2021, Chrome V 91.0.4472.124

## What Language are you in?
- [] Swift
- [] Objective-C

## Expected Behavior 
Created a simple animation from Ai. After first failed attempts I deleted all the Ai files and converted them to shapes.
Gradients also had some issues so I replaced them with solid colors.
I used the 'Supported Feature' list to make sure I don't make any other mistakes [hopefully] cross platforms.
I test the JSON files on web before sending them, however I cannot test them on ios and the files does not work there.
I expected the files that played on the web to work as well on ios and andriod.
plus, when I try to export from LottieFiles plugin, it exports the '.json' file as '.file' and not '.json'. Only when I export from 'bodymovin' it works on web. 

## Actual Behavior
The animation won't work on ios, even though it works on web [I know it's different parameters but i've checked everything in 'unsupported Feature'.
 

## Animation JSON

Downloadable Link [Ae and JSON files]:
https://we.tl/t-QxP3LuDzTx

Many thanks.

**Comment by b1ack0u7** [comment]
If I had understood correctly, the files aren´t showing in IOS and it´s strange because I just made a small code using
"Main 3_T12.json" and it does show it, well here I leave the code in case you need it.
Hope you find it useful ;)

![Captura de Pantalla 2021-07-14 a la(s) 15 09 55](https://user-images.githubusercontent.com/57413081/125686645-054e3f2c-2a4b-4c99-b634-28f7243d5a22.png)
```Swift
import SwiftUI
import Lottie
import UIKit

struct ContentView: View {
    var body: some View {
        VStack {
            LottieView(LottieName: "anim") //Name of the json file without .json
                .frame(width: 200, height: 200, alignment: .center) //Use frame to adjust size of your Lottie
                .padding()

            Text("It Works")
        }
    }
}

struct LottieView: UIViewRepresentable {
    let LottieName:String
    typealias UIViewType = UIView
    
    func makeUIView(context: UIViewRepresentableContext<LottieView>) -> UIView {
        let view = UIView(frame: .zero)
        
        let animationView = AnimationView()
        animationView.animation = Animation.named(LottieName)
        animationView.contentMode = .scaleAspectFit
        animationView.loopMode = .playOnce
        animationView.play()
        view.addSubview(animationView)
        
        animationView.translatesAutoresizingMaskIntoConstraints = false
        
        NSLayoutConstraint.activate([
            animationView.widthAnchor.constraint(equalTo: view.widthAnchor),
            animationView.heightAnchor.constraint(equalTo: view.heightAnchor)
        ])
        return view
    }
    
    func updateUIView(_ uiView: UIView, context: UIViewRepresentableContext<LottieView>) {
        //Nothing
    }
}
```

**Comment by calda** [comment]
Could you share a copy of your animation json? It looks like the previous link you shared has expired.
