### ISSUE TITLE
This lottie json cannot play!!!

### ISSUE THREAD

**Issue by John-Gods** [airbnb/lottie-ios#1380]
## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)

## Which Version of Lottie are you using?

Lottie 3.2.3

## What Platform are you on? 

- [] iOS

## What Language are you in?
- [] Swift

## Animation JSON

[fire.json.zip](https://github.com/airbnb/lottie-ios/files/6889914/fire.json.zip)

**Comment by Arth1sBack** [comment]
Same problem here. I cannot play any _pure vector animations_. Animations with raster images seems fine though

**Comment by calda** [comment]
The linked animation uses features not supported on iOS, like masks with the `difference` blend mode
