### ISSUE TITLE
Support for drop shadow on After effects

### ISSUE THREAD

**Issue by vipmallela** [airbnb/lottie-ios#1381]
Hi, I am wondering if Lottie supports drop shadows and opacity used for them in after effects. I have an animation where I increase the opacity of the dial shown below to cast a shadow. I have tried to export it multiple times but it doesn't seem to be working on iOS. I just wanted to know if this effect is even supported by lottie, before giving it another go.

Screenshot:
![image](https://user-images.githubusercontent.com/87431895/127307936-e07fd224-b3f5-4891-ac67-c773ce5fb2d7.png)

**Comment by calda** [comment]
Could you share a copy of your animation json?
