### ISSUE TITLE
Animation is not supported

### ISSUE THREAD

**Issue by lashkhi** [airbnb/lottie-ios#139]
Hey, I'm not so familiar with After Effects, but I've tried to add an animation from this simple tutorial: https://helpx.adobe.com/premiere-pro/how-to/logo-animation.html?playlist=/ccx/v1/collection/product/after-effects/segment/designer/explevel/beginner/applaunch/orientation/collection.ccx.js  I've removed all the graphics and only text animation is left. I'm selecting my generated JSON file from JSONExplorerViewController, but animation is not played. Attached please find a JSON file. 
[data.json.zip](https://github.com/airbnb/lottie-ios/files/806191/data.json.zip)

**Comment by buba447** [comment]
We don't currently support text layers due to internationalization problems that we haven't solved yet.

**Comment by buba447** [comment]
One thing you can do is convert the text layer to a shape layer using the trace function in AE
https://www.premiumbeat.com/blog/quick-tip-converting-text-to-masks-in-after-effects/

@lashkhi

**Comment by pc1849** [comment]
@buba447 How about your progress on supporting text layers now? Shape layer can't solve i18n problems.
