### ISSUE TITLE
[Flutter] Lottie animation not showing on iOS

### ISSUE THREAD

**Issue by wpikespeak** [airbnb/lottie-ios#1390]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [] Swift
- [x] Objective-C

## Expected Behavior 

The animation should show

## Actual Behavior

The animation didn't show.
## Animation JSON

https://lottiefiles.com/share/vkkyqfez

Also, if this is not the right channel for the issues, can you please help us point out to the correct audience. Thanks in advance :)

**Comment by calda** [comment]
This animation uses layer effects, which aren't supported on iOS according to https://airbnb.io/lottie/#/supported-features
