### ISSUE TITLE
Apply Tint Color to entire view similar to that on Android

### ISSUE THREAD

**Issue by ravitripathi** [airbnb/lottie-ios#1392]
Is it possible to apply a color to the entire view, like we can do on Android? Currently the API on iOS requires us to know the entire Keypaths, or loops through all Keypaths and figure out which might work.

_Originally posted by @ravitripathi in https://github.com/airbnb/lottie-ios/issues/277#issuecomment-908091587_

**Comment by ravitripathi** [comment]
The use case here is that our design team might generates Lottie JSONs from AfterEffects, but the name of the layers can be random. Due to the way accessing Keypaths works on iOS, we don't have a way to apply an overall tint color to all fill layers in a Lottie animation. Is there a way to achieve this on iOS? Currently this is possible on Android via color filters, as mentioned in #277

**Comment by calda** [comment]
You should be able to apply a custom color value provider to all layers by using the `**.Color` keypath. Did you try that?

**Comment by calda** [comment]
Feel free to [start a discussion](https://github.com/airbnb/lottie-ios/discussions) if you'd still like support!
