### ISSUE TITLE
Animation stopped after switch on Background

### ISSUE THREAD

**Issue by OussamaMhz** [airbnb/lottie-ios#1394]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0.4

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 

After returning from Background mode 
the animation should be running

## Actual Behavior

the animation stopped when the app return to foreground mode
*Reproducing bug on iOS 14.7

## Code Example

private let animationView = AnimationView (
        name: "sas_measure_device",
        bundle: Bundle.main
    )

let animationContainerView = UIView(frame: .zero)
        animationContainerView.translatesAutoresizingMaskIntoConstraints = false
        animationView.translatesAutoresizingMaskIntoConstraints = false
        animationView.loopMode = .loop
        animationView.backgroundBehavior = .pauseAndRestore
...

**Comment by calda** [comment]
Could you share a sample project that reproduces this issue? Your sample code looks correct to me.

**Comment by baiyidjp** [comment]
> 

Hi

I also ran into this problem, as soon as the current page viewWillDisapper, the didMoveToWindow of the AnimationBaseView would trigger the code that caused removeAnimation to be called, and the animation would simply Stop

**Comment by baiyidjp** [comment]
> > 
> 
> Hi
> 
> I also ran into this problem, as soon as the current page viewWillDisapper, the didMoveToWindow of the AnimationBaseView would trigger the code that caused removeAnimation to be called, and the animation would simply Stop

this is answer [#1332](https://github.com/airbnb/lottie-ios/issues/1332)
