### ISSUE TITLE
Building universal frameworks with common architectures is not possible. The device and simulator slices for "Lottie" both build for: arm64

### ISSUE THREAD

**Issue by edward-sentongo** [airbnb/lottie-ios#1396]
Facing this issues while using Carthage:
_Building universal frameworks with common architectures is not possible. The device and simulator slices for "Lottie" both build for: arm64_

The only output I get is:
*** Building scheme "Lottie_tvOS" in Lottie.xcodeproj

Not other scheme other than tvOS is creating a framework

**Comment by balajifoodpanda** [comment]
Have you found any solution to this? I am getting the same error

**Comment by shalutyagihike** [comment]
I am facing the same issue.

**Comment by victor-yn** [comment]
@calda do we have any news on this?

**Comment by calda** [comment]
Does this still happen using Lottie 3.4.0?

**Comment by akfpnd** [comment]
Yes still facing issue in carthage
