### ISSUE TITLE
Lottie animation not scaling to fit view if the view breaks the animation's intrinsic aspect ratio

### ISSUE THREAD

**Issue by zhusteph** [airbnb/lottie-ios#1399]
## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [ ] Feature Request
- [X] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.2.3

## What Platform are you on? 

- [ ] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift
- [ ] Objective-C

## Expected Behavior 

The actual animation should preferably scale according to the constraints on the view as opposed to based on the aspect ratio if `contentMode` is set to `scaleToFill`.

## Actual Behavior

The yellow border around the progress bar should be extending / stretching to encapsulate the entire length of the progress bar, according to the constraints we're setting. However, it seems that while the view for the animation is the correct size, according to our constraints, the actual animation itself (the yellow bar expands) doesn't size with it, since this breaks the existing aspect ratio, even when we set `contentMode` to `scaleToFill`. 

This has worked on previous versions of Lottie.

<img width="200" alt="Screen Shot 2021-10-08 at 4 05 23 PM" src="https://user-images.githubusercontent.com/11544142/136618923-1d23e558-2077-49fa-9849-1fd3afe37dab.png">

## Animation JSON

Emailing this!

**Comment by calda** [comment]
Could you share a sample project that reproduces this issue?

**Comment by zhusteph** [comment]
@calda I can send you the json file + some sample code for debugging, but I unfortunately cannot send you the whole project because it's IP I don't own.

**Comment by calda** [comment]
A standalone sample xcode project that demonstrates this issue would be helpful! No need to send the full project.
