### ISSUE TITLE
Smulator can show the animation, but the application show nothing 

### ISSUE THREAD

**Issue by wuyuqiu** [airbnb/lottie-ios#140]
{"v":"4.5.8","fr":25,"ip":0,"op":408,"w":1277,"h":800,"ddd":0,"assets":[{"id":"image_0","w":400,"h":120,"u":"images/","p":"img_0.png"},{"id":"image_1","w":1277,"h":800,"u":"images/","p":"img_1.png"}],"layers":[{"ddd":0,"ind":0,"ty":2,"nm":"xing.png","cl":"png","refId":"image_0","ks":{"o":{"a":0,"k":100},"r":{"a":0,"k":0},"p":{"a":1,"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":0,"s":[1482.5,20,0],"e":[1166.5,110,0],"to":[-52.6666679382324,15,0],"ti":[185.83332824707,-57.1666679382324,0]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":128,"s":[1166.5,110,0],"e":[367.5,363,0],"to":[-185.83332824707,57.1666679382324,0],"ti":[180,-57.1666679382324,0]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":251,"s":[367.5,363,0],"e":[86.5,453,0],"to":[-180,57.1666679382324,0],"ti":[46.8333320617676,-15,0]},{"t":379}]},"a":{"a":0,"k":[200,60,0]},"s":{"a":0,"k":[100,100,100]}},"ao":0,"ip":0,"op":750,"st":0,"bm":0,"sr":1},{"ddd":0,"ind":1,"ty":2,"nm":"0eb30f2442a7d93392aa5da3ae4bd11372f001db.jpg","cl":"jpg","refId":"image_1","ks":{"o":{"a":0,"k":100},"r":{"a":0,"k":0},"p":{"a":0,"k":[638.5,400,0]},"a":{"a":0,"k":[638.5,400,0]},"s":{"a":0,"k":[100,100,100]}},"ao":0,"ip":0,"op":750,"st":0,"bm":0,"sr":1}]}

I create a folder  with two picture and  json ，but my phone  show nothing for me;

**Comment by buba447** [comment]
@wuyuqiu This issue was fixed yesterday afternoon on Master. We haven't bumped the version yet.
If you're using cocoa pods then you can update later today when the version bumps to 1.5.1
or you can pull the latest master.

@wuyuqiu

**Comment by wuyuqiu** [comment]
This is my demo , [https://pan.baidu.com/s/1pLrZ5Jt](url)

I used cocoa pods   with “pod ‘lottie-ios’ ”  

![2017-03-01 09 55 17](https://cloud.githubusercontent.com/assets/12904518/23442838/17f37b22-fe66-11e6-8dca-406a57fa6427.png)
