### ISSUE TITLE
keyNotFound for iOS, works on Web

### ISSUE THREAD

**Issue by aphex3k** [airbnb/lottie-ios#1403]
## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- This issue isn't related to another open issue

## This issue is a:
- Non-Crashing Bug (Visual or otherwise)
- Crashing Bug
- Feature Request
- [X] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.2.3

## What Platform are you on? 

- MacOS
- [X] iOS

## What Language are you in?
- [x] Swift
- Objective-C

## Expected Behavior 
- decode lottie json

## Actual Behavior
```
keyNotFound(CodingKeys(stringValue: "ind", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "assets", intValue: nil), _JSONKey(stringValue: "Index 329", intValue: 329), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"ind\", intValue: nil) (\"ind\").", underlyingError: nil))
```

## Example Code

```
_ = AnimationView(url: URL(string:"https://vpn1.codingmerc.com/AHM/swiss-alps_background_828x734.json")) { [weak self] error in
      if let error = error {
          self?.logger.error(
"""
Unable to download lottie animation with error: \(error.localizedDescription)"
"""
          )
      }
  }
```

## Animation JSON
- https://vpn1.codingmerc.com/AHM/swiss-alps_background_828x734.json

## Example in Web
 - the file plays fine in the web player: https://vpn1.codingmerc.com/AHM/index.html
 - ![Screenshot 2021-10-14 125746](https://user-images.githubusercontent.com/433270/137386888-ec92fd10-c073-47c8-a05f-ba2283dd1341.jpg)

**Comment by EE-Yat-Ho** [comment]
I solved it by modifying it like below

// LayerModel.swift
// self.index = try container.decode(Int.self, forKey: .index)
self.index = try container.decodeIfPresent(Int.self, forKey: .index) ?? 0
