### ISSUE TITLE
Animation is pixelated

### ISSUE THREAD

**Issue by rvw** [airbnb/lottie-ios#1407]
My Lottie file (animated or non-animated) that I created with the online SVG to Lottie converter (https://lottiefiles.com/svg-to-lottie/convert) appears pixelated, while the Web (and Android) version appear sharp like a vector image/animation should.

Steps to reproduce:
- Create shape in Sketch or Figma with a gradient fill
- Export to SVG
- Convert to Lottie using https://lottiefiles.com/svg-to-lottie/convert

## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)

## Which Version of Lottie are you using?
LottieFiles for Mac v1.2.3 (27)
SVG to Lottie converter on: https://lottiefiles.com/svg-to-lottie/convert

## What Platform are you on? 

- [x] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift

## Expected Behavior 
Objects look sharp, no pixelation.

## Actual Behavior

<img width="100%" alt="Screen Shot 2021-10-26 at 16 28 06" src="https://user-images.githubusercontent.com/903647/138900064-05e092b4-36b4-4ea1-a8b3-a4ca1ca82f75.png">
<img width="100%" alt="Screen Shot 2021-10-26 at 16 28 18" src="https://user-images.githubusercontent.com/903647/138900087-d1004557-ec05-4d22-869e-d65abe2712db.png">

## Code Example
In this Zip, the Sketch file and the generated SVG file are included, so you can test it out yourself.
[color-blob.zip](https://github.com/airbnb/lottie-ios/files/7418987/color-blob.zip)

## Animation JSON

```
{"v":"5.6.6","ip":0,"op":1,"fr":60,"w":208,"h":226,"layers":[{"ind":19265,"nm":"surface74460","ao":0,"ip":0,"op":60,"st":0,"ty":4,"ks":{"ty":"tr","o":{"k":100},"r":{"k":0},"p":{"k":[0,0]},"a":{"k":[0,0]},"s":{"k":[133.33,133.33]},"sk":{"k":0},"sa":{"k":0}},"shapes":[{"ty":"gr","hd":false,"nm":"surface74460","it":[{"ty":"gr","hd":false,"it":[{"ty":"sh","ks":{"k":{"i":[[0,0],[18.14,-34.81],[19.5,37.41],[-36.94,0]],"o":[[36.94,0],[-18.14,34.81],[-19.5,-37.41],[0,0]],"v":[[78.38,0],[152.25,141.75],[4.5,141.75],[78.38,0]],"c":true}}},{"ty":"gf","s":{"k":[77.7,42.31]},"e":{"k":[77.7,192.33]},"t":1,"h":{"k":0},"a":{"k":0},"g":{"p":3,"k":{"k":[0,0.65,0.39,0.39,0.4,0.81,0.64,0.29,1,0.4,0.12,0.62,0,1,0.4,1,1,1]}},"hd":false,"o":{"k":100}},{"ty":"tr","o":{"k":100},"r":{"k":0},"p":{"k":[0,0]},"a":{"k":[0,0]},"s":{"k":[100,100]},"sk":{"k":0},"sa":{"k":0},"hd":false}]},{"ty":"tr","o":{"k":100},"r":{"k":0},"p":{"k":[0,0]},"a":{"k":[0,0]},"s":{"k":[100,100]},"sk":{"k":0},"sa":{"k":0},"hd":false}]}]}],"meta":{"g":"LF SVG to Lottie"}}
```

**Comment by zootzootryan** [comment]
I have this issue too, and it seems to be the same as this issue reported in October 2020 - 
https://github.com/airbnb/lottie-ios/issues/1279

General suggestions is to revert to 3.2.1 - it's still not perfect but it's a lot better. I'm exporting from AE into a iOS Xcode13 project.

<img width="725" alt="V3 2 1" src="https://user-images.githubusercontent.com/52362056/139968774-85f7d8c5-b12b-460d-a6c3-fd30fe2719cf.png">
<img width="725" alt="V3 2 3" src="https://user-images.githubusercontent.com/52362056/139968779-76c4dc5a-ab02-4393-9aca-fa144c2c208a.png">

**Comment by Iyuna** [comment]
You can use either 3.2.1 library version or this fork with the latest library version and the fix https://github.com/airbnb/lottie-ios/pull/1426.
