### ISSUE TITLE
Failed to render and update auto layout status for UIView

### ISSUE THREAD

**Issue by FelipeDocil** [airbnb/lottie-ios#1409]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [x] Crashing Bug
- [] Feature Request
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.2.3

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 
It should allow me to compile

## Actual Behavior
Two error messages
> IB Designables: Failed to render and update auto layout status for UIView (iN0-l3-epB): The agent threw an exception.
![](https://i.imgur.com/zS6Qst4.png)

And 
> The agent raised a "NSUnknownKeyException" exception: <Lottie.AnimationView > setValue:forUndefinedKey:]: this class 
is not key value code-compliant for the key adjustsImageSizeForAccessibilityContentSizeCategory.
![](https://i.imgur.com/RQW5ETB.png)

## Details

The rest of my .xib files are working fine, apart for the only one that I have variations based on traits, then this compile error appears. Before this file used LOTAnimationView and it was working but now since I'm migrating my project from Lottie 2 to 3, it's giving me this compile errors.

Also running on Xcode 12.5.1

**Comment by calda** [comment]
Closing since this seems like a potentially outdated issue. Feel free to re-open if you're still experiencing this issue.
