### ISSUE TITLE
Animation not shown

### ISSUE THREAD

**Issue by Rozariozaro** [airbnb/lottie-ios#141]
I used bodymovin aftereffects plugin to generate .json file. The animation provided on the example projects are working fine I dont know what I am doing wrong. 
Json File : [https://www.dropbox.com/s/atvg9jbnpzmicgb/karaoke.json?dl=0](url)

Please help me solve this.

**Comment by therealsalih** [comment]
Can you attach your AE file?

By the looks of the JSON it looks like you're referencing some png images. 

@buba447 is there an issue that shows how to use the image support?

**Comment by buba447** [comment]
There was an issue with image support on iOS that we fixed on master yesterday. I will bump the cocoa pods and carthage version to 1.5.1 later today with the fix!
If you still have issues after that please let me know!
