### ISSUE TITLE
Cannot parse json in case of jpg sequences, lost indices while parsing 

### ISSUE THREAD

**Issue by chizhavko** [airbnb/lottie-ios#1412]
## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.2.3

## What Platform are you on? 
- [x] iOS

## What Language are you in?
- [x] Swift
- [x] Objective-C

## Expected Behavior 

I should be able to parse json, its not possible right now because we have non-optional parsing type for "ind" key:
`self.index = try container.decode(Int.self, forKey: .index)`

## Actual Behavior

We use lotty not as vector graphics, but as a sequence of JPG images. And in this JSON we do not have their indices. Each picture is a separate object, it is also the initial frame, and this same frame is its own index. Due to the non-index option, we have no way to parse JSON.

## Code Example

![Screenshot 2021-11-07 at 19 18 29](https://user-images.githubusercontent.com/70526783/140653071-5813b919-8cfa-4555-b98d-34192f5b37dc.png)

## Animation JSON

[data.json.zip](https://github.com/airbnb/lottie-ios/files/7492637/data.json.zip)

**Comment by chizhavko** [comment]
#1413 https://github.com/airbnb/lottie-ios/pull/1413
Fixed in this PR

**Comment by calda** [comment]
@chizhavko, does the change in #1433 fix your issue? The json file you shared appears to parse successfully now.
