### ISSUE TITLE
crash when initializing AnimationView (maybe only in simulator)

### ISSUE THREAD

**Issue by michaelknoch** [airbnb/lottie-ios#1415]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [ ] Non-Crashing Bug (Visual or otherwise)
- [x] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Saw the crash happening in 3.2.3 and latest master. Also when going back a bunch of commits I haven't found a version which does not crash.

## What Platform are you on? 

- [ ] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [ ] Objective-C

## Expected Behavior 
it should not crash

## Actual Behavior
The app crashes on startup when AnimationView gets initialized with name and bundle **when running on simulators**. It always happens for me using xcode 13.1 on Macbook with **M1 Pro**, saw very rare occurrences on intel simulators and never on physical devices. Also it doesn't seem to happen when running xcode through rosetta.

`EXC_BAD_ACCESS`

<img width="1624" alt="Screenshot 2021-11-12 at 12 47 39" src="https://user-images.githubusercontent.com/5617793/141462918-5c5199d9-1c61-46d3-b12a-0b990f65eb06.png">

## Code Example
https://github.com/michaelknoch/LottieCrashApp

## Animation JSON
both animations seem to cause the crash, even when the stack trace looks slightly different:
https://github.com/michaelknoch/LottieCrashApp/blob/main/checkmark.json
https://lottiefiles.com/84896-loader-25d-bear

**Comment by lorenc-tomasz** [comment]
The same on xcode 13.1

**Comment by michaelknoch** [comment]
it doesn't seem to happen in our react native app which also uses lottie-ios under the hood. Still never saw it on real devices.

**Comment by lorenc-tomasz** [comment]
To me, it only happens when xcode is "connected" to the app in debug mode. If I open the app on simulator without xcode help - there is no issue with that.

**Comment by lorenc-tomasz** [comment]
Issue on xcode 13.1 with sim on my side: 

<img width="852" alt="Zrzut ekranu 2021-12-6 o 11 49 29" src="https://user-images.githubusercontent.com/7620331/144833361-3e9ca5e4-2a2b-4b14-8c99-2ecc75387a14.png">

**Comment by lorenc-tomasz** [comment]
@michaelknoch Could you test Xcode 13.2 RC, please? I don't have this issue with new 13.2.

**Comment by lorenc-tomasz** [comment]
OK. So today on 13.2 RC I had the same error again. It's look like it's somehow random :(

**Comment by blick9** [comment]
@michaelknoch @lorenc-tomasz 
did you resolve the issue? i have the same problem. how did you solve it?
it occurs not only in simulators but also in real device.
I tried Xcode 13.0 to 13.2.1 versions.

**Comment by blick9** [comment]
@michaelknoch @lorenc-tomasz
did you resolve the issue? i have the same problem. how did you solve it?
it occurs not only in simulators but also in real device.
I tried Xcode 13.0 to 13.2.1 versions.

**Comment by michaelknoch** [comment]
@blick9 still happening for me literally every time I use simulators. Haven't seen it on a device and I can't see it in our production crash logs. Still annoying and it surprises me that there aren't more reports. Does this only happen on M1 pro/max devices?

**Comment by blick9** [comment]
@michaelknoch thanks! i'll try it!

**Comment by michaelknoch** [comment]
I can confirm that the same library version crashes when referencing the xcodeproj directly and does not crash when using SPM. It also doesn't crash in release builds using xcodeproj. So I guess this is related to optimizations, debug mode etc.

**Comment by michaelknoch** [comment]
enabling optimizations for debug and disabling incremental builds for target `LottieLibraryIOS` prevents the crash from happening

![Screenshot 2022-03-28 at 12 39 18](https://user-images.githubusercontent.com/5617793/160381162-fbbbcf51-3999-4e39-8872-d044a8091ca1.png)
