### ISSUE TITLE
Animation cannot be fully loaded

### ISSUE THREAD

**Issue by GitFreedom** [airbnb/lottie-ios#1417]
## Which Version of Lottie are you using?
3.1.9

## What Platform are you on? 
- [] iOS

## What Language are you in?
- [] Swift

## Animation JSON
[Animation JSON](https://yuwencdn.kaishustory.com/kstory/pangu/attachment/24a6f08d-def5-46e2-aa89-f155be39a8ff_info_s=215661.json)

**Comment by calda** [comment]
This animation loads and plays correctly when I test on `master`, as far as I can tell. Could you try it out on the latest version of Lottie and let us know if it works as you expect?
