### ISSUE TITLE
Completion block not called after changing loopAnimation flag

### ISSUE THREAD

**Issue by christoph-eero** [airbnb/lottie-ios#142]
Use case:  We have animations that have an intro, loop and outro that are supposed to be strung together seamlessly.  Since we cannot loop on parts of a Lottie animation, a workaround was to swap views as animations end.  The middle loop is configured with loopAnimation = true and a completion block. 

The block is not called while the animation is looping which is logically consistent and expected.  However, when changed to loopAnimation = false it should still call the block because it was played with a block.

1.  Create and lay out an animation view
2.  Set view.loopAnimation = true
3.  Call view.playWithCompletion() with a valid block
4.  Set a breakpoint in the block
5.  Programmatically set view.loopAnimation = false

Expected result:  View finishes current animation, then calls block
Actual result:  View finished current animation, does not call block

**Comment by buba447** [comment]
Ohhh when you set loop animation LOT removes the reference to the completion block. This was to avoid keeping completion blocks forever. 

Hmmm i can see that this is a pretty valid use case though.

**Comment by christoph-eero** [comment]
Yup, I just found the line of code that does it and commented it out.  To avoid keep unused completion blocks, how about only create the _completionDisplayLink if playWithCompletion() was called?
