### ISSUE TITLE
Animation playing bug in iOS SDK or In LottieFiles APP

### ISSUE THREAD

**Issue by maiyabj** [airbnb/lottie-ios#1422]
Hello.
When I play the json animation file with Lottie iOS SDK, it has bugs.
I play in LottieFiles APP, it has bugs.
If I play animation in the web version with Lottie JSON Editor - everything looks fine.
Seems like iOS SDK renders the animation differently.
I attach the animation file.
Is it the SDK bug or can my designer change something in the json?

Also I attach the Json.
[fireworks.json.zip](https://github.com/airbnb/lottie-ios/files/7638877/fireworks.json.zip)

Thank you!

**Comment by calda** [comment]
It looks like this animation uses repeaters, which we added in #1688
