### ISSUE TITLE
Animation Touch Events

### ISSUE THREAD

**Issue by steve7688** [airbnb/lottie-ios#1430]
Hey guys I had a huge Lottie file including several elements in the this view.

For example there is a bird and a snake and a tiger and a hunter etc. in this animation view.

I wanna get some kind of callback when user click on these elements.

is it possible though Lottie for iOS and Android?

**Comment by calda** [comment]
Closing since this is a question and not a bug report. Feel free to start a [discussion](https://github.com/airbnb/lottie-ios/discussions) if you'd still like support.
