### ISSUE TITLE
Can't Install Lottie with Carthage

### ISSUE THREAD

**Issue by jliussuweno25** [airbnb/lottie-ios#1438]
## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- 
## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] iOS

## What Language are you in?
- [] Swift

## Expected Behavior
Can be installed with Carthage

## Actual Behavior
<img width="577" alt="Screen Shot 2021-12-13 at 12 06 58" src="https://user-images.githubusercontent.com/95082093/145755602-0e6bbae3-3b09-4626-8487-eba7e3bc2cd5.png"> 

Cannot install lottie library with carthage

## Code Example
<img width="365" alt="Screen Shot 2021-12-13 at 12 08 06" src="https://user-images.githubusercontent.com/95082093/145755672-bcf6387e-8be8-4869-acf5-f299df1fedf7.png">

**Comment by baveku** [comment]
https://github.com/airbnb/lottie-ios/issues/1448#issuecomment-996612284

**Comment by calda** [comment]
@jliussuweno25, does the fix discussed in https://github.com/airbnb/lottie-ios/issues/1448#issuecomment-998960232 work for you?
