### ISSUE TITLE
Lottie not building on M1 MAX - Could not read serialized diagnostics file

### ISSUE THREAD

**Issue by TheInkedEngineer** [airbnb/lottie-ios#1439]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [ ] Non-Crashing Bug (Visual or otherwise)
- [x] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [x] MacOS
- [ ] iOS

## What Language are you in?
- [x] Swift
- [ ] Objective-C

## Expected Behavior 
The application to build.

## Actual Behavior
The application does not build and throw the following error:

```
/Library/Developer/Xcode/DerivedData/test-dcjkneocylqbqebqtiucqofhlazk/Build/Intermediates.noindex/Lottie.build/Debug/Lottie.build/Objects-normal/arm64/AnimationCacheProvider.dia:1:1: warning: Could not read serialized diagnostics file: error("Invalid diagnostics signature") (in target 'Lottie' from project 'Lottie')
Command CompileSwift failed with a nonzero exit code
```

<img width="271" alt="Screenshot 2021-12-13 at 10 40 42" src="https://user-images.githubusercontent.com/13349066/145794275-901e0541-7bb8-40ea-bbd1-67edba0d1481.png">

## Code Example
No code needed.

To replicate, create new macOS app, add Lottie package, try to build, build fails.

I am using a M1 MAX MacBook Pro, running Xcode 13.1 and macOS Monterey.
I tried with a new project, clean build, no derived data or cache

**Comment by TheInkedEngineer** [comment]
I tried on an M1 as well, same error.

**Comment by calda** [comment]
@TheInkedEngineer, I don't have access to an M1 machine at this time. Would you mind checking out `master`, running `bundle exec rake build:package:iOS`, and then sharing the log output? That may help me diagnose this issue.

**Comment by TheInkedEngineer** [comment]
@calda here you go:

```bash
set -o pipefail && xcodebuild build -scheme Lottie -destination generic/platform=iOS | mint run xcbeautify
sh: mint: command not found
2021-12-13 19:42:41.061 xcodebuild[29779:968830] [MT] IDEFileReferenceDebug: [Load] <IDESwiftPackageCore.IDESwiftPackageSpecialFolderFileReference, 0x60000357a100: name:Samples path:group:Samples> Failed to load container at path: /Users/theinkedengineer/Code/lottie-ios/Tests/Samples, Error: Error Domain=com.apple.dt.IDEContainerErrorDomain Code=6 "Cannot open "Samples" as a "Swift User Managed Package Folder" because it is already open as a "Folder"." UserInfo={NSLocalizedDescription=Cannot open "Samples" as a "Swift User Managed Package Folder" because it is already open as a "Folder".}
rake aborted!
Command failed with status (127): [set -o pipefail && xcodebuild build -schem...]
/Users/theinkedengineer/Code/lottie-ios/Rakefile:88:in `xcodebuild'
/Users/theinkedengineer/Code/lottie-ios/Rakefile:12:in `block (3 levels) in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `load'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:28:in `run'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli.rb:494:in `exec'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli.rb:30:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli.rb:24:in `start'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/exe/bundle:49:in `block in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/exe/bundle:37:in `<top (required)>'
/usr/bin/bundle:23:in `load'
/usr/bin/bundle:23:in `<main>'
Tasks: TOP => build:package:iOS
(See full trace by running task with --trace)
```

**Comment by calda** [comment]
hmm not much useful log output there -- maybe try `xcodebuild build -scheme Lottie -destination generic/platform=iOS`?

**Comment by TheInkedEngineer** [comment]
Strangely, the build succeeded.

Here is the full log:

[lottie-log.txt](https://github.com/airbnb/lottie-ios/files/7706370/lottie-log.txt)

**Comment by TheInkedEngineer** [comment]
Here is the platform=macOS 

[lottie-log-mac.txt](https://github.com/airbnb/lottie-ios/files/7706409/lottie-log-mac.txt)

**Comment by calda** [comment]
Good to know! I recently restructured how the project is organized / build (#1427), so it's possible those changes fixed issues with the previous setup.

How were you building Lottie before, when you saw the failure? Were you building from `master` or building a release via Cocoapods etc? (we haven't cut a release with the new build changes)

**Comment by TheInkedEngineer** [comment]
@calda I was including it with SPM version 3.2.3, and just building the macOS project.
So master is ahead of 3.2.3?

**Comment by calda** [comment]
Yes! 3.2.3 is the latest official release. There are a dozen or so commits on master that are currently not included in an official release: https://github.com/airbnb/lottie-ios/compare/3.2.3...master

**Comment by TheInkedEngineer** [comment]
actually, I downloaded master, and used it as a local package, it does build. 
Fingers crossed you guys manage to release soon.

Thanks

**Comment by TheInkedEngineer** [comment]
@calda solved with 3.3.0

**Comment by TheInkedEngineer** [comment]
Solved with 3.3.0

**Comment by calda** [comment]
Great! Thanks for the update

**Comment by TacticCoder** [comment]
same here for 3.3.0 with m1, works great on macOS with intel processor

**Comment by marcellocamara** [comment]
@TheInkedEngineer could you help me to find the solution for this error?

"Cannot open "Samples" as a "Swift User Managed Package Folder" because it is already open as a "Folder"

I have a similar issue on another package and cannot find the way to fix it.
It seems pretty easy, but I've no knowledges on XCode/Swift/iOS native

**Comment by calda** [comment]
I think this happens because we have multiple "folder references" for a single folder ("Samples") in our Xcode workspace. I don't know what this error is for, considering the project still works correctly otherwise. Removing one of the folder references makes the error go away, but we actually use those references so just decided to leave the error as-is in our workspace.
