### ISSUE TITLE
Lottie isn't working on iOS Xcode but working perfect on Android.

### ISSUE THREAD

**Issue by FushiandU** [airbnb/lottie-ios#1445]
When XCODE is trying to preview then this code appear in error.

keyNotFound(CodingKeys(stringValue: "ind", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "assets", intValue: nil), _JSONKey(stringValue: "Index 63", intValue: 63), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"ind\", intValue: nil) (\"ind\").", underlyingError: nil))

**Comment by calda** [comment]
1. what version of Lottie are you using? have you tried this on the latest version (3.3.0)?
 2. could you share a copy of the animation json file that is resulting in this error?
 
 Thanks!

**Comment by shivangpandya9** [comment]
Same issue please check
