### ISSUE TITLE
Dependency "lottie-ios" has no shared framework schemes using Carthage

### ISSUE THREAD

**Issue by sandeep-yudiz** [airbnb/lottie-ios#1448]
## This issue is a:
- Can't Install Lottie with Carthage 

## Which Version of Lottie are you using?

Lottie 3.3.0
github "airbnb/lottie-ios" "master"

## What Platform are you on? 

-  iOS

## What Language are you in?
- Swift

## Error 
https://github.com/airbnb/lottie-ios/tree/42dc2f40bbb7cbcff8866b369beea62683a50f36
![Screenshot 2021-12-17 at 3 16 51 PM](https://user-images.githubusercontent.com/24805252/146526100-01334cd5-d155-48c5-a5ca-e74aeed97b96.png) 

https://github.com/airbnb/lottie-ios/tree/cac9ede96fc134a2f96f923fdbb0cfa80246215a
![Screenshot 2021-12-17 at 3 25 25 PM](https://user-images.githubusercontent.com/24805252/146525959-029e3a75-a321-48ac-a7b5-b3c134c3038f.png)

**Kindly fix these issues ASAP.**

**Comment by baveku** [comment]
I have no idea, why they removed Carthage in v3.3.0. But I think we can use v3.2.3 for Carthage.
```
github "airbnb/lottie-ios" "3.2.3"
```

**Comment by sandeep-yudiz** [comment]
Yes, That version on we getting an error for the Lottie file for parsing and **animation not working**!. 

`keyNotFound(CodingKeys(stringValue: "ind", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "assets", intValue: nil), _JSONKey(stringValue: "Index 63", intValue: 63), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: "ind", intValue: nil) ("ind").", underlyingError: nil))
`
This fix was added in the 3.3.0 version. 
Added parsing support for layers with no index (ind) property (#1433)

**Comment by calda** [comment]
Sorry about that! This was an accident, will fix it asap (probably Monday) and publish a new release.

**Comment by calda** [comment]
Fixed in #1453, `github "airbnb/lottie-ios" "master"` should work now. Thanks for reporting this issue!

One thing to note is that when using Carthage you now have to `import LottieCarthage` (instead of `import Lottie`). Let me know if this works for you.

**Comment by gmondada** [comment]
Hi @calda, Thanks for the fix.
Changing the module name requires the source code to be changed. I don't think the source code should care about how Lottie has been compiled/linked. I personally use Carthage in compilation scripts and once the framework is built, it's just a framework, it should not carry the name of the compilation process. That said, I can workaround this in my compilation script.

**Comment by calda** [comment]
Thanks for the feedback @gmondada, agree the previous setup wasn't ideal.

I fixed this in #1454 so the Carthage framework is just called "Lottie", so you can use `import Lottie` again.

**Comment by lonsky** [comment]
Current version from master produces this warning during linking:
`
ld: warning: linking against a dylib which is not safe for use in application extensions: /Users/*******/Projects/*********/Carthage/Build/iOS/Lottie.framework/Lottie
`
doesn't happen on v3.2.3
