### ISSUE TITLE
My own guide json file has no effect on my mobile phone

### ISSUE THREAD

**Issue by gaopeng1223** [airbnb/lottie-ios#145]
When I put the json demo official runtime inside, give 'Lottie - Example [3264-739481] + [LOTShapeGroup shapeItemWithJSON: frameRate: compBounds:] : Warning: the star is not supported. Convert to vector path?', could you tell me what do you mean, it is said that my json file wrong

**Comment by therealsalih** [comment]
@gaopeng1223 it means polygons and polystars aren't yet support. See this issue https://github.com/airbnb/lottie-ios/issues/105  for a workaround and also to track polystar support
