### ISSUE TITLE
Certain Elements not visible on IOS but works fine on Android and Web

### ISSUE THREAD

**Issue by rajAppmetry** [airbnb/lottie-ios#1458]
Lottie Version - 3.3.0
Xcode - 13.2.1
Device Checked - IOS 15 and 14

Problem:
Some components present in our Lottie JSON are not visible on IOS but works perfectly fine on Android and Web. 
Attached are screenshots for the same (1st from IOS and 2nd from the web) 
You can notice the centre logo missing in IOS whereas it is present on the Web for the same JSON.
 
<img width="230" alt="Screenshot 2021-12-27 at 11 51 49 AM" src="https://user-images.githubusercontent.com/38988176/147441318-1febd8ff-6373-4af1-a0a8-c7fd16c5729c.png">
<img width="230" alt="Screenshot 2021-12-27 at 11 52 53 AM" src="https://user-images.githubusercontent.com/38988176/147441311-826979d7-e837-4364-bceb-fa96509f17d6.png">

**Comment by calda** [comment]
Could you share a copy of the animation json?

**Comment by gaowei887** [comment]
i have the issue too！
hope fix it soon！

**Comment by gaowei887** [comment]
> 

https://wos3.58cdn.com.cn/TuyqPoNmLTAu/lottie/hongbaowiwi1.json

**Comment by calda** [comment]
When I test that animation on master, it renders the same as it does when I test it on https://lottiefiles.com

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/1811727/183966796-8f5ab8b7-568c-4a74-a0b7-eabfe49431da.png">

**Comment by gaowei887** [comment]
> When I test that animation on master, it renders the same as it does when I test it on https://lottiefiles.com
> 
> <img alt="image" width="1143" src="https://user-images.githubusercontent.com/1811727/183966796-8f5ab8b7-568c-4a74-a0b7-eabfe49431da.png">

last day i have check my local version is 3.1.9 ,but when i update to the latest version ,it is worked! i do not kown which version has fixed it already.
