### ISSUE TITLE
Layer Styles support for Precomps

### ISSUE THREAD

**Issue by vikram-kumar** [airbnb/lottie-ios#146]
Am trying to add outline stroke for my pre-comp animation using     
Layer > Layer Styles > Stroke.

![precomp_layerstyles](https://cloud.githubusercontent.com/assets/3540373/23453924/5577be16-fe90-11e6-9d88-6fb3cbdd4434.png)

**Comment by buba447** [comment]
Marking as a feature request

**Comment by therealsalih** [comment]
@buba447 Layer Styles arent yet supported in bodymovin btw

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
