### ISSUE TITLE
Float height and float width not supported

### ISSUE THREAD

**Issue by ivanmkc** [airbnb/lottie-ios#1460]
According to https://github.com/airbnb/lottie-web/blob/master/docs/json/animation.json, `height` and `width` can be a number, not specifically an int.

```
    "h": {
      "title": "Height",
      "description": "Composition Height",
      "type": "number"
    },
```  

When an animation has a float, the iOS library fails with a decoding error.

Attached is an example file, which works fine on web.

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
[0c29ccc7-a286-41a0-8f99-0f1bf9b4b955.json.zip](https://github.com/airbnb/lottie-ios/files/7789883/0c29ccc7-a286-41a0-8f99-0f1bf9b4b955.json.zip)

- [] Objective-C

## Code Example
`Animation.named(name)`

## Animation JSON
Attached

**Comment by calda** [comment]
Thanks for the report, fixed in #1694
