### ISSUE TITLE
Carthage checkout - adding Lottie as project in workspace

### ISSUE THREAD

**Issue by pashdevore** [airbnb/lottie-ios#1464]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [ ] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [ ] Feature Request
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Issue occurs in Lottie 3.3.0 and greater
Currently able to use version 3.2.3

## What Platform are you on? 

- [ ] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [ ] Objective-C

## Expected Behavior 

My team's current workflow for adding Lottie (v3.2.3) as well as other frameworks into our app is as follows:
1) Add the dependency to our Cartfile
2) Use `carthage checkout` to pull the associated dependency
3) Add the `.xcodeproj` to the app workspace from the checked out files
4) Add the iOS framework to `Frameworks, Libraries, and Embedded Content` and ensure `Embed & Sign` is the option selected
5) Build and run

## Actual Behavior

As of version 3.3.0 and greater, the only way to incorporate the Lottie framework into our app is to run `carthage build --use-xcframeworks` and add the built xcframework into our project. We don't want to incorporate `carthage build` into our workflow or CI builds and are hoping for a resolution that would allow us to continue to use our current method.

**Comment by calda** [comment]
This is a known issue in 3.3.0, but should work on `master` (e.g. if you use `github "airbnb/lottie-ios" "master"` in your Cartfile)

**Comment by calda** [comment]
Oh, sorry, I misunderstood your problem. We recently restructured the xcode project structure to be more SPM-first. You may be able to use the `Lottie.framework` defined in `CarthageSupport/CarthageSupport.xcodeproj`.

**Comment by pashdevore** [comment]
Okay, went ahead and tried pulling from `master` and using the `CarthageSupport/CarthageSupport.xcodeproj` in our workspace.

This results in the following error when building:
> Missing package product `_LottieCore`

**Comment by calda** [comment]
You may also have to pull in `Lottie.xcworkspace`, which is where the SPM `_LottieCore` package is defined.

**Comment by pashdevore** [comment]
That results in the same error.

**Comment by pashdevore** [comment]
Any other ideas on getting this to work?

**Comment by calda** [comment]
I think this can likely be made to work with the current project setup, since we still have an `xcworkspace` that defines the necessary schemes. Although I would personally recommend using an "officially supported" method like building the `.framework` via Carthage.

**Comment by calda** [comment]
Closing since this seems like a potentially outdated issue (we restructured the project again so this should no longer be an issue). Feel free to re-open if you're still experiencing this issue.
