### ISSUE TITLE
lottie-ios 3.3.0 haven't been pushed to the npm registry

### ISSUE THREAD

**Issue by kentakang** [airbnb/lottie-ios#1477]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [ ] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [x] Feature Request
- [ ] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.3.0

## What Platform are you on? 

- [ ] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [ ] Objective-C

lottie-ios 3.3.0 haven't been pushed to the npm registry.
npm registry latest version is 3.2.3

**Comment by dorperezx** [comment]
?

**Comment by Noitham** [comment]
No plan to release this version on npm?

**Comment by calda** [comment]
3.4.0 is now available on npm
