### ISSUE TITLE
A strange technique in the implementation of LOTLayerView

### ISSUE THREAD

**Issue by dark19940411** [airbnb/lottie-ios#149]
Recently, I've read the source code of lottie-ios through because i was interested in the animation on iOS. I've noticed that lottie parsed the JSON file and wrapped the data into LOTComposition and LOTLayer.  After that, LOTAnimationView will use LOTLayer and LOTComposition to initialize LOTLayerView, which is the place really applying Core Animation. In this process, as a good data supply, you make one LOTLayer match to one LOTLayerView. However, I saw you use a loop to deal with the LOTLayer within the composition initializing LOTLayerView in LOTAnimationView, which means every model in layers of the composition will be used to initialize LOTLayerVIew. At the mean time, you use another loop in layerView to backtrace a layerView's parent LOTLayer(it's still in the composition's layers.) to initialize a LOTParentLayer(Just like the LOTLayerView--a CALayer applied animation). I know this conduct could guarantee the correctness of the sublayer's animation. But wouldn't it be duplicated? wouldn't it be a waste of the memory?
I should say sorry in advance because this is a long question. And I don't know if I clarify the situation. But I really wonder the answer.

**Comment by buba447** [comment]
Hey! Thank you for the interest in Lottie and for looking through the source code!

First a bit of backstory on how parenting works in after effects vs ios.
In after effects you can parent a layer to another layer. Though they call it parenting, it has a different meaning than what we are use to in the UIKit world. When a layer is parented to another layer it simply follows the transform of the "Parented" layer and offsets itself accordingly. Any other modifications to the parent layer do not affect the child layer.

So when looping through the parent views I am creating LOTParentLayer(s) which are stripped down layers that only contains a single CALayer and just the transform animation. 
Doing this allows layers to be parented to other layers so they move in unison. We aren't actually parenting the layers but building a simple coordinate hierarchy above the child layer. 
This also avoids any errors that would come from a parent layer being hidden but the child layer being visible.

**Comment by dark19940411** [comment]
This really solves my confusion! Thank you so much!
