### ISSUE TITLE
Carthage build result can not be used on different machine

### ISSUE THREAD

**Issue by thangngoquocOura** [airbnb/lottie-ios#1492]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.3.0 - master

## What Platform are you on? 

- [x] iOS

## What Language are you in?
- [x] Swift

## Expected Behavior 
Pre-built xcframework of Lottie using Carthage (`carthage bootstrap --platform iOS --use-xcframeworks --cache-builds`) is portable and can be used on different dev machine.

Our setup includes checking out the `Carthage/Build` folder, the CI machine can uses the pre-built xcframeworks of all dependencies. In v3.2.3 it used to work.

## Actual Behavior
In v3.3.0 I changed the Carthfile to point to `master` according to https://github.com/airbnb/lottie-ios/issues/1448#issuecomment-998197310 It works on my local env after running `carthage update --platform iOS --use-xcframeworks --cache-builds`, but the CI can't compile the project with error message "Missing required module LottieCore".

After trying to run `carthage update lottie-ios --platform iOS --use-xcframeworks` on the CI machine, it can compile the project successfully.

The CI machine and my local env are using the same Xcode, tool chain and macOS version, they are both x86 intel Mac. Switching back to 3.2.3 works as expected.

## Animation JSON

**Comment by calda** [comment]
Fixed in #1496 (which has been merged, so this should be fixed on `master` now). Thanks again for reporting this issue.
