### ISSUE TITLE
Path not showing

### ISSUE THREAD

**Issue by foulkesjohn** [airbnb/lottie-ios#150]
I've been given the following by my designer and it doesn't seem to display in the lottie explorer demo. I've tried stepping through the code to see what the issue but can't really see why it doesn't display. It displays in chrome with the demo exported by bodymoving. Is anyone able to explain what the issue is? I suspect the designer has used an unsupported feature but can't offer any assistance to which one it could be.

[data.json.zip](https://github.com/airbnb/lottie-ios/files/813524/data.json.zip)

**Comment by xinsight** [comment]
Just tested it with my branch that adds more warnings (#147) and I get lots of:

`+[LOTShapeGroup shapeItemWithJSON:frameRate:compBounds:]: Warning: merge shape is not supported. name: Merge Paths 1`

Could that be the issue?

**Comment by buba447** [comment]
Yeah thats right we aren't supporting merge shapes yet

**Comment by buba447** [comment]
Closing as a duplicate issue

**Comment by SriSamVictor** [comment]
i can't change the position of the lottie animations
