### ISSUE TITLE
NSImage -cgImage method in extension conflicts with other category implementation

### ISSUE THREAD

**Issue by vdudchak** [airbnb/lottie-ios#1500]
In our project we have two packages (Lottie and SDWebImage) with -CGImage category added to NSImage with slightly different implementations. Maybe it would be better to add prefix (like lottie_cgImage) here to avoid method name collisions.
https://github.com/airbnb/lottie-ios/blob/8f2d4dbf84b2985f26e588c76d51135dde73d471/Sources/Public/macOS/FilepathImageProvider.macOS.swift#L66

**Comment by calda** [comment]
Does #1501 fix this for you?

**Comment by vdudchak** [comment]
It fixed the problem, thank you!
