### ISSUE TITLE
Mask path (Add mode) appears as filled in shape, instead of being invisible

### ISSUE THREAD

**Issue by jhughes696** [airbnb/lottie-ios#1505]
## Lottie-iOS Issue

Masks paths are being rendered as visible filled in paths, instead of staying invisible. This issue only appears when it first loads, then any playback after the initial load looks fine. So for some reason the first time the masks load, they render incorrectly. 

The issue is happening with Masks on invisible Shape layers that are being used as an Alpha Matte, as well as on visible Shape Layers that are not set to "None" track matte.

WATCH AfterEffects walkthrough here: https://www.loom.com/share/2a52c7e5b31946e8be1da90a78c57b58

A package of .json and .aep files can be downloaded here: https://www.dropbox.com/sh/ml0v90dz0xpniyx/AAB_hTTctlR80KYWwxRvnBHka?dl=0

##Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [X] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie files iOS app 2.4.5 

## What Platform are you on? 

- [] MacOS
- [x] iOS 15.2.1

## What Language are you in?
- [] Swift
- [] Objective-C

## Expected Behavior 
![arm_AE_ExpectedBehavior](https://user-images.githubusercontent.com/50207823/151625970-b96828ec-3c82-42ba-9aa8-3b2e775285a1.gif)

## Actual Behavior
![arm_Lottie_ActualBehavior](https://user-images.githubusercontent.com/50207823/151625978-3b32f097-e6ab-4ea6-819b-1e0753357eb5.gif)

## Animation JSON

https://assets9.lottiefiles.com/packages/lf20_vgqatzfz.json

**Comment by calda** [comment]
Could you share more details about how you're reproducing this issue? I tested this animation on `master` and it works correctly. What version of Lottie are you testing with?

![2022-02-01 09 51 59](https://user-images.githubusercontent.com/1811727/152023982-a9806bcc-2648-4cf3-a584-356dee10e992.gif)

**Comment by calda** [comment]
Aha! This was fixed by #1397, which hasn't been included in an official yet.

When I revert that change, I am able to reproduce your issue:

<img src="https://user-images.githubusercontent.com/1811727/152024813-a0c4935d-4e9b-437c-b343-d92b12fd502e.gif" width=350>

@jhughes696, are you able to use `master` instead of `3.3.0`?

**Comment by jhughes696** [comment]
Thanks for looking into this! I will ask the eng. team what version they are currently using/and  if they can use master.
