### ISSUE TITLE
Lottie animation differences on iOS

### ISSUE THREAD

**Issue by fcf-al** [airbnb/lottie-ios#1517]
The animation is different from expected. Attached is the gif downloaded from lottiefiles preview.

## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.3.0

## What Platform are you on? 

- [x] iOS

## What Language are you in?
- [x] Swift

## Expected Behavior 
![animation_200_kzo31d1r](https://user-images.githubusercontent.com/99732041/154059930-c2d9b0eb-6439-4cb0-bce0-291f22046e25.gif)

## Actual Behavior
![Simulator Screen Shot - iPhone 13 Pro - 2022-02-15 at 07 13 53](https://user-images.githubusercontent.com/99732041/154060067-b413037c-c881-4556-9437-e73164c92504.png)

## Code Example

```
        let animation = Animation.named("pin")
        self.animationView.animation = animation
        self.animationView.contentMode = .scaleAspectFill
        self.animationView.loopMode = .loop
        self.animationView.animationSpeed = 1.5
        self.animationView.play()
```

**Comment by calda** [comment]
Could you share the .json file for this animation (or a link to it on LottieFiles)?

**Comment by fcf-al** [comment]
Updated. The issue is with a particular layer the "nm": "ADBE Vector Filter - Repeater", if I remove that layer then the preview displays on the web displays what one would see on iOS. So I'm assuming the framework has an issue rendering that layer.

**Comment by calda** [comment]
According to this page in the documentation, iOS doesn't currently support Repeaters: https://airbnb.io/lottie/#/supported-features

**Comment by fcf-al** [comment]
Noted, closing issue. Thanks for your time!
