### ISSUE TITLE
ProMotion Support?

### ISSUE THREAD

**Issue by metroidmen** [airbnb/lottie-ios#1519]
Just curious if there will be an update to support ProMotion? The animations are already very smooth, but it would be a nice touch to see them move even smoother!

Thanks!

**Comment by calda** [comment]
I don't have firm plans to work on this at this moment, but agree that this would be a great enhancement

**Comment by calda** [comment]
@metroidmen I heard this is working automatically on the most recent versions of iOS (at least when using the new Core Animation rendering engine, possible also the Main Thread engine). If you have a ProMotion device, would you mind checking?

**Comment by brian-voong** [comment]
Core Animation engine definitely look smooth and 60+ FPS, but its hard to measure this for sure.
