### ISSUE TITLE
Enhancement Request: Round Corners for iOS

### ISSUE THREAD

**Issue by jhughes696** [airbnb/lottie-ios#1523]
Currently "Round Corners" for bezier paths is supported on Lottie Web and Android, but not iOS. It would be great if it was supported on iOS as well. 

It would be a huge enhancement from an animation perspective. Below is an animation test that illustrates the capabilities of Round Corners, when applied to a Bezier Path in After Effects ( [ json download link](https://www.dropbox.com/s/ub8o5eax19h0uti/RoundedCornersTest.json?dl=0) )

![RoundedCorners_test](https://user-images.githubusercontent.com/50207823/155399677-b9e81494-1a59-4a61-b297-f46c30938183.gif)
![RoundedCorners_test_PathPreview](https://user-images.githubusercontent.com/50207823/155399692-26997329-b327-4d14-b9d8-112b0716f986.gif)

**Comment by calda** [comment]
For future reference, an algorithm for applying a corner radius to a bezier path is implemented [here](https://github.com/airbnb/lottie-web/blob/master/player/js/utils/shapes/RoundCornersModifier.js) for lottie-web and [here](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/animation/content/RoundedCornersContent.java#L74) for lottie-android. After porting this algorithm to Swift it should be reasonably straightforward to add this support.

**Comment by jhughes696** [comment]
Hey there! Any new progress regarding this feature request? Thanks!

**Comment by Rimesh** [comment]
Provided link for LottieFiles json is not working.
<img width="696" alt="permission" src="https://user-images.githubusercontent.com/26106450/197326284-e2a36f03-17d0-42b0-a9d8-e3ec5521a0cb.png">

**Comment by jhughes696** [comment]
@Rimesh I just updated the JSON Link so you can download it without permissions.

**Comment by calda** [comment]
Implemented in #1795 -- thank you very much @johnny-duo!

**Comment by jhughes696** [comment]
YES! Thanks so much @johnny-duo & @calda. This will be super helpful for animators and should theoretically allow us to reduce file size (less point data).
