### ISSUE TITLE
Crash Lottie.Animation.init(from: Swift.Decoder) throws -> Lottie.Animation (Animation.swift:32) - SIGABRT

### ISSUE THREAD

**Issue by ragu-pdx** [airbnb/lottie-ios#1530]
## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [X] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift
- [] Objective-C

## Expected Behavior 

Application is able to load and play animation files reliably

## Actual Behavior

Most of the time, the animation code works with all our animations. However, users are experiencing this crash at a non-trivial rate. It's unclear why the crash is occurring at all, when all the animations normally play just fine and most of the time everything is working perfectly fine.

## Code Example
```
Lottie
Lottie.Animation.init(from: Swift.Decoder) throws -> Lottie.Animation Animation.swift:32
Lottie
protocol witness for Swift.Decodable.init(from: Swift.Decoder) throws -> A in conformance Lottie.Animation : Swift.Decodable in Lottie <compiler-generated>:0
libswiftCore.dylib
dispatch thunk of Swift.Decodable.init(from: Swift.Decoder) throws -> A
Lottie
function signature specialization <Arg[4] = Dead> of static Lottie.Animation.named(_: Swift.String, bundle: __C.NSBundle, subdirectory: Swift.String?, animationCache: Lottie.AnimationCacheProvider?) -> Lottie.Animation? AnimationPublic.swift:67
Lab Central
Lab_Central.HomeReaderCollectionViewModel.(updateAnimation in _102FE8CBB6E2D5E78BC409C4E4492266)() -> () Animation+Storage.swift:22
Lab Central
closure #1 (Swift.Bool) -> () in Lab_Central.HomeReaderCollectionViewCell.(set in _AD16348B20A1A412316DA215E413C6D1)(animation: Lottie.Animation?) -> () HomeReaderCollectionViewModel.swift:61
Lottie
Lottie.AnimationCompletionDelegate.animationDidStop(_: __C.CAAnimation, finished: Swift.Bool) -> () AnimationContext.swift:66
Lottie
@objc Lottie.AnimationCompletionDelegate.animationDidStop(_: __C.CAAnimation, finished: Swift.Bool) -> () <compiler-generated>:0
QuartzCore
CA::Layer::run_animation_callbacks(void*)
```

**Comment by calda** [comment]
Perhaps the new dictionary decoding implementation in 3.4.0 resolves this issue
