### ISSUE TITLE
Animation Gets Paused in milisecons when Metal is enabled

### ISSUE THREAD

**Issue by mehmetbaykar** [airbnb/lottie-ios#1532]
I have a Video-Call Api that uses Metal. After playing Lottie animation, when the Video-Call Api starts (enabling Metal) Lottie animation gets paused for milliseconds and then continues.

## This issue is a:
- Non-Crashing Bug (Visual or otherwise)

## Which Version of Lottie are you using?

- Lottie 3.2.3

## What Platform are you on? 
- iOS 15.3.1,  iPhone 11

## What Language are you in?
- Swift

## Code Example
`  private var animationView :AnimationView!{ 
        didSet{
            animationView.animationSpeed = 1.25
            animationView.loopMode = .loop
            animationView.backgroundBehavior = .pauseAndRestore
        }
    }`
## Animation

![Example](https://user-images.githubusercontent.com/20362928/159505121-25bf1241-e329-43fd-ab84-29ac5468aa04.gif)

**Comment by calda** [comment]
Yesterday we released Lottie 3.4.0 which includes a new rendering engine powered by Core Animation ([more details here](https://github.com/airbnb/lottie-ios/discussions/1627)). This new rendering engine has significantly better performance, and should resolve the performance issues folks have been encountering with the previous main thread rendering engine. Please try it out by setting the `LottieConfiguration.renderingEngine` feature flag, and feel free to report any new issues that you experience when using the new rendering engine.
