### ISSUE TITLE
CompatibleAnimationView set frame is not work when I use in oc

### ISSUE THREAD

**Issue by liushengqiangGitHub** [airbnb/lottie-ios#1534]
## Check these before submitting:
 The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
 

## This issue is a:
  Non-Crashing Bug (Visual or otherwise) 

## Which Version of Lottie are you using?
  Lottie 3.0

## What Platform are you on? 

[iOS]

## What Language are you in?
 Objective-C 

## Expected Behavior 

https://user-images.githubusercontent.com/19679062/160113446-cedcaae8-bad0-4d0b-981e-4cff57dee0b1.png

## Actual Behavior

https://user-images.githubusercontent.com/19679062/160113586-01b81806-4efe-4bb2-9f41-24a0d0c5ffbd.png
 

## Code Example

        //set animation json object
        CompatibleAnimation  *weatherAnimation = [[CompatibleAnimation alloc] initWithName:@"xiaxue" bundle:[NSBundle mainBundle]];

        //set frame
        CompatibleAnimationView *view_LottieAnimation = [[CompatibleAnimationView alloc] initWithFrame:CGRectMake(0, 0, 414, 219)];
        view_LottieAnimation.compatibleAnimation = weatherAnimation;
        view_LottieAnimation.contentMode = UIViewContentModeScaleAspectFit;

        *****  fixed   code. ******* 

        //1:in CompatibleAnimationView, change the ''animationView'' private to @objc public ,and  reset the             animationView.contentMode in this.
        view_LottieAnimation.animationView.contentMode = UIViewContentModeScaleAspectFit;

        //2:reset the translatesAutoresizingMaskIntoConstraints = YES;
        view_LottieAnimation.translatesAutoresizingMaskIntoConstraints = YES;

        I hope you can fix it in release version.and update this framework.thanks!! 
        ************************************************************************************
        view_LottieAnimation.loopAnimationCount = -1;
        [self.view_Weather_Content addSubview:view_LottieAnimation];
  
        [view_LottieAnimation play];
## Animation JSON
https://github.com/airbnb/lottie-ios/files/8350186/default.zip

**Comment by calda** [comment]
@liushengqiangGitHub, I don't fully understand the suggested change -- if you'd like us to make a change to `ComaptibleAnimationView`, would you mind posting a pull request along with before/after images? Thanks!
