### ISSUE TITLE
Cannot load underlying module for 'Lottie' in Pipeline that runs Unit Test

### ISSUE THREAD

**Issue by MahmoudZinji** [airbnb/lottie-ios#1551]
This is the first time i ever raise an issue so excuse me for any wrong format or missing infos.

## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.3.0

## What Platform are you on? 

- [] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift
- [] Objective-C

## Expected Behavior 

The code in my pipelines keep throwing an error whrn running the **RUN UNIT TESTS** and the error is 
`Cannot load underlying module for 'Lottie'`

![Screenshot 2022-04-27 at 08 48 24](https://user-images.githubusercontent.com/19683593/165458216-6de1f656-b9a3-4298-a508-f9a7fead4a63.png)

![Screenshot 2022-04-27 at 08 50 17](https://user-images.githubusercontent.com/19683593/165458479-b2ef32e1-0644-457d-8328-b76aeeaade08.png)

## Actual Behavior

The app works really fine on my local machine and all the work is as intended.

**Comment by calda** [comment]
Closing since this seems like a CocoaPods build system issue and not a Lottie bug
