### ISSUE TITLE
Animation getting cropped

### ISSUE THREAD

**Issue by vipinpahwa** [airbnb/lottie-ios#1552]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.5

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 
<img width="244" alt="Screenshot 2022-05-02 at 3 26 50 PM" src="https://user-images.githubusercontent.com/40717158/166216943-93d4f3c1-a2c7-4067-8a55-b8de7ef35d28.png">

## Actual Behavior
Happens intermittently
<img width="244" alt="Screenshot 2022-05-02 at 3 25 16 PM" src="https://user-images.githubusercontent.com/40717158/166216758-044d0d26-5b37-4683-8e9f-f54223e6b821.png">

## Code Example

```
private func showAnimation(url: URL, withInterval: Bool) {
        removeImageView()
        addAnimatedImageIfNeeded()
        self.preloadedLottieData.mutate { [weak self] dictionary in
            guard let animationData = dictionary[url.absoluteString] else {
                DispatchQueue.global(qos: .userInteractive).async {
                    if let animationData = try? Data(contentsOf: url) {
                        DispatchQueue.main.async { [weak self] in
                            self?.decodeAndPlayAnimation(data: animationData, withInterval: withInterval)
                        }
                    }
                }
                return
            }
            
            DispatchQueue.main.async { [weak self] in
                self?.decodeAndPlayAnimation(data: animationData, withInterval: withInterval)
            }
        }
    }

private func addAnimatedImageIfNeeded() {
        guard let animatedImageView = self.animatedImageView else {
            
            let animationView = AnimationView()
            animationView.translatesAutoresizingMaskIntoConstraints = false
            animationView.isUserInteractionEnabled = false
            animationView.contentMode = .bottomRight
            animationView.loopMode = .playOnce
            animationView.backgroundBehavior = .pauseAndRestore
            self.animatedImageView = animationView
            
            addAnimatedImageIfNeeded()
            return
        }
        
        guard animatedImageView.superview == nil else { return }
        
        addSubview(animatedImageView)

        NSLayoutConstraint.activate([
            animatedImageView.rightAnchor.constraint(equalTo: rightAnchor),
            animatedImageView.bottomAnchor.constraint(equalTo: bottomAnchor),
            animatedImageView.heightAnchor.constraint(equalToConstant: 92),
            animatedImageView.widthAnchor.constraint(equalToConstant: 150)
        ])
    }

```

**Comment by calda** [comment]
@vipinpahwa, could you share a runnable sample project that demonstrates this issue?

**Comment by vipinpahwa** [comment]
Was able to resolve this by some code changes on app side. Closing this issue.
