### ISSUE TITLE
Animation not the same when in iOS app

### ISSUE THREAD

**Issue by Carlosanielrf** [airbnb/lottie-ios#1557]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.3.0

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 
![Screenshot 2022-05-05 at 11 28 00](https://user-images.githubusercontent.com/104981788/166907133-cda3eb0b-a773-465d-9686-e6ca68137ae0.png)

## Actual Behavior
![Screenshot 2022-05-05 at 11 28 06](https://user-images.githubusercontent.com/104981788/166907160-c339dc4d-b272-460d-9fce-a5a426154fc8.png)

Preview made with lottie render.
The circles are distorted, the text isn't bold and even the colors look different.

## Code Example

```
private func setupTankAnimationView(animationName: String? = nil) {
        let jsonName = animationName ?? defaultJSOName
        
        tankAnimationView.animation = Animation.named(jsonName)
        tankAnimationView.loopMode = .loop
        tankAnimationView.fontProvider = FontProvider(family: fontFamily, size: size)
        tankAnimationView.sizeToFit()
        tankAnimationView.play()
}
```

## Animation JSON

**Comment by calda** [comment]
Could you share a copy of the animation json?

**Comment by Carlosanielrf** [comment]
> Could you share a copy of the animation json?

Hi just send you the animation json.
