### ISSUE TITLE
Animation inside UIPageViewController doesn't play

### ISSUE THREAD

**Issue by marcelofabri** [airbnb/lottie-ios#1565]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [ ] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [ ] Feature Request
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [ ] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [ ] Objective-C

## Expected Behavior 

Animations after the second page inside an `UIPageViewController` don't play. A workaround is to set `backgroundBehavior = .pauseAndRestore`.

This is a regression from Lottie 2 to 3.

## Actual Behavior

They should play

## Code Example

https://github.com/airbnb/lottie-ios/issues/1084

**Comment by marcelofabri** [comment]
I was able to repro it inside the Demo project in a page view controller with the `scroll` mode: https://github.com/marcelofabri/lottie-ios/pull/new/page-view-controller.

However I don't know if there's a good fix here since `backgroundBehavior ` fundamentally works differently. Maybe `pauseAndRestore` should've been the default behavior?

**Comment by calda** [comment]
Closing since there's a known solution

**Comment by calda** [comment]
In Lottie 4.0 we are changing the default behavior of `LottieBackgroundBehavior` from `.pause` to `.pauseAndRestore`, which should fix the underlying issue here.
