### ISSUE TITLE
Carthage compatibility is somewhat broken

### ISSUE THREAD

**Issue by Bogidon** [airbnb/lottie-ios#157]
#### **TL;DR**: Carthage compatibility is somewhat broken. You can temporarily use [this fork](https://github.com/teespring/lottie-ios) if you only need iOS.

Not sure to what extent Carthage isn't working, or exactly why. It has to do with the `#if TARGET_OS_IPHONE || TARGET_IPHONE_SIMULATOR` precompiler flags ([the latter was deprecated in iOS 9](https://github.com/mstg/iOS-full-sdk/blob/master/iPhoneOS9.3.sdk/usr/include/TargetConditionals.h#L71)). I discovered the issue when trying to use `LOTAnimationTransitionController`, whose implementation is unavailable when compiled through Carthage. 

The error you'd get if you try using the transition controller, would look something like this (the architecture depending on the one you're currently building `x86_64`, `arm64`, etc):
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_LOTAnimationTransitionController", referenced from:
      objc-class-ref in <YOUR CLASS>.o
ld: symbol(s) not found for architecture x86_64
```

I created a fork as a quick workaround that removes macOS support to get Carthage working again. [You can find it here](https://github.com/teespring/lottie-ios). I have not tested this with Cocoapods, so definitely _don't use the fork_ for anything but Carthage compatibility for iOS.

At some point I hope to help create a real fix. Until then, here are some possible solutions in case someone else wants to give it a shot:
1. Some files could just be removed from the macOS target, eliminating the need for precompiler flags. 
1. `#import <TargetConditionals.h>` might fix the precompiler flags not working
1. If  `LOTAnimationTransitionController` (for example) works with Cocoapods, this may be an issue with the flags Carthage passes (or more likely doesn't pass) when it builds frameworks. I don't know much about this, so it would require collaboration with [Carthage/Carthage](https://github.com/Carthage/Carthage).

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
