### ISSUE TITLE
Changes to LOTComposition and LOTAnimationView interfaces

### ISSUE THREAD

**Issue by benpious** [airbnb/lottie-ios#160]
I'd like to propose two changes to Lottie; the first is allowing the user to set the animation on an `LOTAnimationView` after instantiating it, and the second is making a subset of `LOTComposition`'s API public. 

There's several elements of `LOTAnimationView` which make it difficult to work with. Firstly, you can't create an `LOTAnimationView` without first creating whatever animation data you want to display. 

For example, consider this example of the normal flow for getting an image off the network and displaying it:

```
urlSession.getData { [weak self] data in 
   if data {
       self?.imageView.image = UIImage(data)
   }
}
```

Lottie, however, provides no way to instantiate an `LOTAnimationView` and subsequently change the animation (or even to instantiate a functional `LOTAnimationView` instance without having the animation data on-hand). Therefore, you'd have to instantiate it when the animation data comes in. 

This isn't ergonomic for several reasons; it requires you to use an optional for your view property in Swift (unless you wrap `LOTAnimationView` in a wrapper), it may require you to break up autolayout code to only apply constraints after the view has come in, and it may require you to create a new `LOTAnimationView` (resetting all of the associated state) if you want to change animations; for example if you were using an `LOTAnimationView` in a collection view or tableview with reusable cells.

In my local branch, I found that only minor changes were required to support this; the setter was as simple as

```
- (void)setSceneModel:(LOTComposition *)sceneModel {
    _sceneModel = sceneModel;
    [self _setupWithSceneModel:sceneModel restoreAnimationState:NO];
    [self invalidateIntrinsicContentSize];
}
```

and properly overriding `initWithFrame` to call`_initializeAnimationContainer`, though there may be cases I'm missing in my approach. 

Since the `LOTAnimationView` actually works just fine without animation data until it's provided. I suppose there's issues with what happens if `LOTAnimationView.play` is called before animation data is set, but this could be dealt with with a `shouldPreserveAnimationState` property allowing the user to configure behavior when the scene model changes. 

Another issue is the decision to make `LOTComposition` private to the module. This prevents the caller from inflating compositions on a thread of their choice, which, given the size of the JSON files produced by animations, seems to be a potential performance issue. My profiling on the iPhone 7 simulator shows that it takes 4.0 ms to convert a fairly simple animation into an `LOTComposition`, which is 1/4 of a frame. I think it would be better to publicly expose `LOTComposition` and its initializer, so the user can construct one however they like. 

This is what I've got on my local branch for the public header:

```
NS_SWIFT_NAME(Composition)
@interface LOTComposition : NSObject

- (_Nullable instancetype)initWithJSON:(NSDictionary * _Nullable)jsonDictionary;

@end
```

This also opens up the potential for the user to implement their own strategy for caching compositions, instead of relying on the built in caching, which may not be appropriate for all use cases.

**Comment by buba447** [comment]
Lottie V2 is out and the LOTComposition API is now public! Setting animation is coming quickly.

**Comment by buba447** [comment]
Im going to close this and track the setting issue here, since its represented in several issues https://github.com/airbnb/lottie-ios/issues/344

**Comment by buba447** [comment]
Added here https://github.com/airbnb/lottie-ios/pull/347
