### ISSUE TITLE
how to reduce CPU usage in my osx app

### ISSUE THREAD

**Issue by ihoudf** [airbnb/lottie-ios#1602]
In this osx app，only have these codes,but the cpu usage is highest。

`class ViewController: NSViewController {

    let animationV = AnimationView()
    override func viewDidLoad() {
        super.viewDidLoad()
        
        animationV.animation = Animation.named("77631-bee-lounging")
        animationV.loopMode = .loop
        view.addSubview(animationV)

        animationV.frame = NSRect(x: 0, y: 0, width: 200, height: 200)
        animationV.play()
    }

    override var representedObject: Any? {
        didSet {
        // Update the view, if already loaded.
        }
    }

}`

![截屏2022-05-19 上午10 47 04](https://user-images.githubusercontent.com/13429905/169194365-9880da1b-8197-4ed8-8e2c-9ed11b89cba8.png)

**Comment by calda** [comment]
The Core Animation rendering engine is now available in Lottie 3.4.0 ([more details](https://github.com/airbnb/lottie-ios/discussions/1627)) -- enabling it should eliminate the CPU overhead of playing your Lottie animation.
