### ISSUE TITLE
Lottie file works on Android and Web Preview, but not iOS

### ISSUE THREAD

**Issue by mattgapadmi** [airbnb/lottie-ios#1603]
The attached lottie file works on Android and Web Preview, but not on iOS. This can be seen by opening it in the LottieFiles iOS App. Note that in order to see it in the web preview, you need to change the preview background colour to something other than white.

## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?
Lottie 3.3.0

## What Platform are you on? 

- [ ] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [ ] Objective-C

## Expected Behavior 
Animation should appear as it does on Web Preview

## Actual Behavior
Animation is not shown

## Code Example
N/A

## Animation JSON
Attached
[lf20_9bvc1u7o.json.zip](https://github.com/airbnb/lottie-ios/files/8730824/lf20_9bvc1u7o.json.zip)

**Comment by SinoAlak** [comment]
I have the same issue. It is working with the preview tool. Android and web. However, not on ios and the error I am getting is a decoding error. 

Printing description of error:
▿ DecodingError
  ▿ keyNotFound : 2 elements
    - .0 : CodingKeys(stringValue: "ip", intValue: nil)
    ▿ .1 : Context
      ▿ codingPath : 3 elements
        - 0 : CodingKeys(stringValue: "assets", intValue: nil)
        ▿ 1 : _JSONKey(stringValue: "Index 1", intValue: 1)
          - stringValue : "Index 1"
          ▿ intValue : Optional<Int>
            - some : 1
        ▿ 2 : _JSONKey(stringValue: "Index 18", intValue: 18)
          - stringValue : "Index 18"
          ▿ intValue : Optional<Int>
            - some : 18
      - debugDescription : "No value associated with key CodingKeys(stringValue: \"ip\", intValue: nil) (\"ip\")."
      - underlyingError : nil


[loading-indicator.json.zip](https://github.com/airbnb/lottie-ios/files/8749999/loading-indicator.json.zip)

**Comment by calda** [comment]
Thanks for the report, fixed in #1693
