### ISSUE TITLE
LOTAnimationView should catch exceptions from parsing JSON

### ISSUE THREAD

**Issue by benpious** [airbnb/lottie-ios#161]
`LOTAnimationView.animationFromJSON` performs no validation of the contents of `animationJSON` which can result in an Objective-C Exception being thrown if the objects in the keys it reads aren't the types that it expects. 

One doesn't typically expect an exception to be thrown while instantiating a UIView subclass, and this is particularly inconvenient behavior in Swift, given that Swift actually can't catch Objective-C exceptions. Also, the potential exists for invalid JSON to *not* cause a crash, but instead to silently not produce any animation at all; as far as I'm aware there is no way to detect this at runtime. 

An easy solution to this problem would be to catch the exceptions inside of `_mapFromJSON`, and simply return `nil` from `initWithJSON`. If combined with #160, this would allow the caller to easily respond to invalid JSON from either Swift or Objective-C by providing a placeholder or taking other appropriate actions, since by convention in both Swift and Objective-C, constructors that take arguments that can be invalid are usually failable.

**Comment by buba447** [comment]
Lottie V2 should fix this.
