### ISSUE TITLE
My .json file not display .

### ISSUE THREAD

**Issue by xyfqldy** [airbnb/lottie-ios#162]
I am newcomer of AE , Here is my export file ,but it doesn't render,please point my mistake,Grateful.

[cat.json…]()

**Comment by gpeal** [comment]
@xyfqldy Your json file didn't properly attach to your comment.

**Comment by Stitch-Taotao** [comment]
Sorry,this is my .json file.
[cat.json.zip](https://github.com/airbnb/lottie-ios/files/840086/cat.json.zip)

**Comment by gpeal** [comment]
@xyfqldy Your animation json references a bunch of images. Is that expected? Are they possibly Illustrator layers?

**Comment by xyfqldy** [comment]
I had not import images directory. After add images directory , animation work fine.

**Comment by iNicson** [comment]
did you mean you dragged the images folder to your project? I did the same but it is not loading
