### ISSUE TITLE
 iOS Crash : <compiler-generated> line 2147483647 <name omitted>

### ISSUE THREAD

**Issue by siddew201** [airbnb/lottie-ios#1621]
## Which Version of Lottie are you using?

Lottie 3.3.0

## Expected Behavior 
App should not crash.

## Actual Behavior
App is crashing on production. Not able to reproduce
Crashed: com.apple.main-thread
0  CoreFoundation                 0xec18 __CFBasicHashRehash + 104
1  CoreFoundation                 0x112f0 __CFTryParseBinaryPlist + 172
2  CoreFoundation                 0x6887c _CFPropertyListCreateWithData + 160
3  CoreFoundation                 0x6af0c CFPropertyListCreateWithData + 60
4  CFNetwork                      0x26ba4 CFURLRequestCopyHTTPRequestBodyStream + 2444
5  CFNetwork                      0x291c7c __CFTubeSetTubeTypeNotifier + 53976
6  CFNetwork                      0x794dc CFURLConnectionCreateWithProperties + 648
7  CFNetwork                      0x788b0 CFURLConnectionSendSynchronousRequest + 9528
8  CFNetwork                      0x764e0 CFURLConnectionSendSynchronousRequest + 360
9  CFNetwork                      0x121908 _CFURLConnectionCopyTimingData + 14612
10 Foundation                     0xac64c -[NSData(NSData) initWithContentsOfURL:options:maxLength:error:] + 280
11 Lottie                         0x248c4 <name omitted> + 4481534148 (<compiler-generated>:4481534148)
12 Lottie                         0x24528 imageForAsset + 4481533224 (<compiler-generated>:4481533224)
13 Lottie                         0x2486c imageForAsset + 4481534060 (<compiler-generated>:4481534060)
14 Lottie                         0x45d34 reloadImages + 4481670452 (ImageCompositionLayer.swift:4481670452)
15 Lottie                         0x17f20 makeAnimationLayer + 4481482528 (AnimationView.swift:4481482528)
16 Lottie                         0x17604 animation.set + 132 (AnimationView.swift:132)
17 TCPApp                         0x7bd754 getLoaderView + 93 (AppModulesHelperProvider.swift:93)
18 TCPUIKit                       0x11878 setUp + 49 (LoaderView.swift:49)
19 TCPUIKit                       0x11404 init + 27 (LoaderView.swift:27)
20 TCPUIKit                       0x114cc init + 4511634636 (<compiler-generated>:4511634636)
21 TCPUIKit                       0x915e0 <name omitted> + 149 (UIViewControllerExtension.swift:149)
22 TCPUIKit                       0x1ce48 <name omitted> + 4511682120 (<compiler-generated>:4511682120)
23 libdispatch.dylib              0x1c04 _dispatch_call_block_and_release + 32
24 libdispatch.dylib              0x3950 _dispatch_client_callout + 20
25 libdispatch.dylib              0x11d30 _dispatch_main_queue_callback_4CF + 940
26 CoreFoundation                 0x51ce4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
27 CoreFoundation                 0xbebc __CFRunLoopRun + 2540
28 CoreFoundation                 0x1f3c8 CFRunLoopRunSpecific + 600
29 GraphicsServices               0x138c GSEventRunModal + 164
30 UIKitCore                      0x51b0bc -[UIApplication _run] + 1100
31 UIKitCore                      0x298be8 UIApplicationMain + 2124
32 TCPApp                         0xa34528 main + 39 (AppDelegate.swift:39)
33 ???                            0x1088f1a24 (Missing)

**Comment by calda** [comment]
Closing since this looks like an iOS SDK issue and not a Lotte bug report.
