### ISSUE TITLE
imageForAsset(asset: ImageAsset) creates a warning in Xcode Version 14.0 beta 2 due to sync. requests

### ISSUE THREAD

**Issue by tscholze** [airbnb/lottie-ios#1622]
## Which Version of Lottie are you using?

Lottie 3.3.0

## Expected Behavior 
No warnings

## Actual Behavior
Getting warnings (no errors) using Xcode Version 14.0 beta 2 
<img width="1160" alt="Bildschirmfoto 2022-07-05 um 18 59 43" src="https://user-images.githubusercontent.com/5583469/177379372-4ebc431f-60d5-4694-a2f3-355be8c47e6d.png">

**Comment by calda** [comment]
I think this warning should be fixed by #1524, which is included in `3.4.0`. When loading base64 images we now use the `UIImage(data: Data(base64Ecoded:))` initializers instead of loading directly from the encoded URL.
