### ISSUE TITLE
`automatic` `renderingEngine` in `AnimationView` not rendering gradients properly

### ISSUE THREAD

**Issue by simondelphia** [airbnb/lottie-ios#1628]
Gradients in a couple of my Lottie files are not rendering properly with the `.automatic` `renderingEngine` enabled

| Main Thread  | Automatic |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/69437320/177619361-74bf0819-814d-4f4e-b993-ceca88b54291.png">  |  <img src="https://user-images.githubusercontent.com/69437320/177619436-32d26c15-1ffe-4922-baab-5cfa18602d90.png">  |

It’s a normal linear gradient, but the colour at one end is rgba(75,177,97,0.2) and the colour at the other is rgba(75,177,97,0), so the gradient is only changing the alpha

Lottie 3.4.0, installed via SPM. iOS 15.5 simulator running on macOS 12.4 (21F79) (M1 Macbook Pro)

If you would like a copy of the Lottie file I would prefer to send it privately.

Note this particular animation view is also embedded in a SwiftUI view, in case that's relevant.

**Comment by simondelphia** [comment]
Done, thank you

**Comment by calda** [comment]
Fixed in #1634, thanks for the report!
