### ISSUE TITLE
Is the npm registry not being maintained anymore?

### ISSUE THREAD

**Issue by ifsnow** [airbnb/lottie-ios#1631]
The last version of lottie-ios in npm is still [3.2.3](https://www.npmjs.com/package/lottie-ios).

Shouldn't we expect to use lottie-ios using npm from now on?

Please tell us the direction of operation of this project.

Thanks!

**Comment by calda** [comment]
It looks like there are a bunch of people using Lottie through npm (150k+ weekly downloads) so it makes sense to continue maintaining this. I don't personally have permission to upload a new version to npm right now, but I'll work on getting the permissions sorted out and then share an update.

**Comment by calda** [comment]
3.4.0 is now available on npm
