### ISSUE TITLE
Mixed `isHold` / `!isHold` keyframes are currently unsupported by the Core Animation engine.

### ISSUE THREAD

**Issue by smolskyaleksey** [airbnb/lottie-ios#1632]
``` swift
        let animation = Animation.filepath(url.path, animationCache: LRUAnimationCache.sharedCache)
        let provider = FilepathImageProvider(filepath: URL(fileURLWithPath: url.path).deletingLastPathComponent().path)
        let view = AnimationView(
            animation: animation,
            imageProvider: provider,
            configuration: LottieConfiguration(renderingEngine: .coreAnimation)
        )
        view.loopMode = loopAnimation ? .loop : .playOnce
        view.contentMode = .scaleAspectFit
        addSubview(view)
```

Lottie 3.4.0

Lottie/AnimationView.swift:1003: Assertion failed: Encountered Core Animation compatibility issues while setting up animation:
[Pre-comp 106.arm_L.arm_L] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.body.body] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.hand_L.hand_L] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.eye_R_close.eye_R_close] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.eye_R_close 2.eye_R_close 2] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.eyebrow_R.eyebrow_R] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.eyebrow_L.eyebrow_L] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.mouth.mouth] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.hand_R.hand_R] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.hand_R 2.hand_R 2] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.arm_L.arm_L] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.body.body] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.hand_L.hand_L] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.eye_R_close.eye_R_close] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.eye_R_close 2.eye_R_close 2] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.eyebrow_R.eyebrow_R] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.eyebrow_L.eyebrow_L] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.mouth.mouth] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.hand_R.hand_R] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.hand_R 2.hand_R 2] Mixed `isHold` / `!isHold` keyframes are currently unsupported

This animation cannot be rendered correctly by the Core Animation engine.
To resolve this issue, you can use `RenderingEngineOption.automatic`, which automatically falls back
to the Main Thread rendering engine when necessary, or just use `RenderingEngineOption.mainThread`.

2022-07-07 13:49:27.930390+0300  Lottie/AnimationView.swift:1003: Assertion failed: Encountered Core Animation compatibility issues while setting up animation:
[Pre-comp 106.arm_L.arm_L] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.body.body] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.hand_L.hand_L] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.eye_R_close.eye_R_close] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.eye_R_close 2.eye_R_close 2] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.eyebrow_R.eyebrow_R] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.eyebrow_L.eyebrow_L] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.mouth.mouth] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.hand_R.hand_R] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.hand_R 2.hand_R 2] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.arm_L.arm_L] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.body.body] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.hand_L.hand_L] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.eye_R_close.eye_R_close] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.eye_R_close 2.eye_R_close 2] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.eyebrow_R.eyebrow_R] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.eyebrow_L.eyebrow_L] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.mouth.mouth] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.hand_R.hand_R] Mixed `isHold` / `!isHold` keyframes are currently unsupported
[Pre-comp 106.hand_R 2.hand_R 2] Mixed `isHold` / `!isHold` keyframes are currently unsupported

This animation cannot be rendered correctly by the Core Animation engine.
To resolve this issue, you can use `RenderingEngineOption.automatic`, which automatically falls back
to the Main Thread rendering engine when necessary, or just use `RenderingEngineOption.mainThread`.

File with animation
https://storage.googleapis.com/gem-backoffice-assets/smileAnimation/ABg5-Uw2Hkcff7lE2LCKRRDDnbb6NHiuswW86XFNd4QH1OfVgYtCPohlHGmswb6N6An4wGce7ncSU7I0KkeXM9UaomGer4_8cg.ehpPDiU_hJ4ukpo7

**Comment by calda** [comment]
This is currently unsupported by the Core Animation rendering engine. I don't think there's anything fundamentally blocking us from adding this support, it just hasn't been implemented yet (pull requests are welcome!).

I recommend using `LottieConfiguration(renderingEngine: .automatic)` instead of `LottieConfiguration(renderingEngine: .coreAnimation)` -- `.automatic` will automatically fall back to using the main thread rendering engine in cases like this where the Core Animation rendering engine doesn't support a given animation

**Comment by smolskyaleksey** [comment]
I saw PR already exist for "isHold". 
I used version 2.5.3 before 3.4.0 with automatic mode and performance was better in version 2.5.3. I diceded roll back
