### ISSUE TITLE
Xcode crashes due to endless loop when loading Lottie file

### ISSUE THREAD

**Issue by simondelphia** [airbnb/lottie-ios#1635]
When I run from Xcode on a physical iPhone (tried both an iPhone 7 and an iPhone XS) the app crashes when it's pushing to a view that has a Lottie `AnimationView` in it. This doesn't occur when using a simulator, though even if it does work the app does take a bit longer than expected to do the transition to the view with the animation in it. 

In Xcode I am seeing an EXC_BAD_ACCESS and an endless loop on `PathOutputNode.hasOutputUpdates(_:)` 

- The animation is embedded inside a SwiftUI View (I will check to see if it happens in a UIView-only setup too)
- If I change the rendering engine to `.coreAnimation` it doesn't crash (though still waiting for #1628 to be released before I change the engine)
- It also crashes if I run the app without Xcode attached (e.g. reopen after crash) — suggests that it only happens with debug configurations…
- It does not crash if I run a released version of the app from TestFlight

## Which Version of Lottie are you using?

Lottie 3.4.0 (also tried 3.3.0)

## Expected Behavior 
No crash or endless loop. No hanging.

## Actual Behavior
Crashes due to endless loop.
<img width="1308" alt="image" src="https://user-images.githubusercontent.com/69437320/177858655-7ec29039-6951-454a-bd97-9ef415f63ecb.png">

## Animation JSON
* This is the same one I emailed to Cal Stephens here: #1628

**Comment by calda** [comment]
If this works when using the Core Animation rendering engine I'd suggest updating to using the commit on master that includes the fix you need -- I personally don't plan on fixing issues with the main thread rendering engine in cases where the Core Animation rendering engine behaves correctly
