### ISSUE TITLE
Carthage macOS use the wrong Swift Module Name (Lottie_macOS) but not (Lottie)

### ISSUE THREAD

**Issue by dreampiggy** [airbnb/lottie-ios#1638]
## Which Version of Lottie are you using?

Lottie 3.4.0

## Expected Behavior 

The `PRODUCT_MODULE_NAME` should be `Lottie`, not `Lottie_macOS`, which is the target name.

This will cause downstream have to use 

```swift
import Lottie_macOS
```

instead, which is a break chanage from Lottie v3.1.0

<img width="864" alt="截屏2022-07-09 01 32 44" src="https://user-images.githubusercontent.com/6919743/178042113-3bd02c63-f597-469f-8fe0-01fe0d405d93.png">

**Comment by calda** [comment]
Thanks for the report! Fixed in #1641.
