### ISSUE TITLE
Sample JSON file demonstrating incorrect fill when using Core Animation rendering.

### ISSUE THREAD

**Issue by j4johnfox** [airbnb/lottie-ios#1643]
## Which Version of Lottie are you using?
Lottie 3.4.x with Core Animation rendering turned on

## Expected Behavior 
The bell icon should not be filled in when running using Core Animation rendering
![Lottie-Bell-Correct](https://user-images.githubusercontent.com/32667/178336499-9b5a8b2e-a5f7-4423-b7fb-be807eb92eb6.gif)

## Actual Behavior
It is filled
![Lottie-Bell-Incorrect](https://user-images.githubusercontent.com/32667/178336589-6a44f7d0-02e6-4d97-997b-dfc0247accf1.gif)

**Comment by calda** [comment]
Fixed in #1647, thanks for the report!
