### ISSUE TITLE
Typing 1-10 and other keyboard symbols not supported 

### ISSUE THREAD

**Issue by mitulmarsonia** [airbnb/lottie-ios#165]
First i want thanks for making supper library.

Is it possible to give input support like -
(1) able to type  number :0 to 9  (2)symbols  as per Keyboard like ? >  $ % ! () etc . ?

Thanks

**Comment by buba447** [comment]
Sorry the keyboard demo only supports Alpha symbols. It is intended to show some of the things you can do with Lottie.
