### ISSUE TITLE
Package size has increased 823.09K from 3.1.8 to 3.4.0

### ISSUE THREAD

**Issue by dongqihouse** [airbnb/lottie-ios#1657]
## Which Version of Lottie are you using?

Lottie 3.4.0

## Expected Behavior 
Whether the project can be optimized

## Actual Behavior
The app size has increase 823.09K from 3.1.8 to 3.4.0.
Whether the project has redundant code.

**Comment by calda** [comment]
What was the package binary size in 3.1.8, and what is it in 3.4.0? How are you calculating these numbers?

**Comment by hyandell** [comment]
https://www.npmjs.com/package/lottie-ios/v/3.4.0 - Total unpacked size 208MB
https://www.npmjs.com/package/lottie-ios/v/3.2.3 - Total unpacked size 779kB

Difference appears to be primarily be due to the inclusion of this file:

    Tests/Artifacts/LottieTests.xcresult/Data/data.0~9u8KAGpgtSm-mQ12Py8RZUbYbDlBhM3w1I2MQO53K2CSn6IePp7g65DBcdXTYMfG1bgoJ-6x30fjnGe-2UYsDQ==

**Comment by calda** [comment]
Closing for now since this doesn't seem particularly unexpected. Feel free to reopen with more information if you feel this is unexpected.
