### ISSUE TITLE
Cannot build on iOS with Carthage

### ISSUE THREAD

**Issue by ondrej-hanslik-csob-cz** [airbnb/lottie-ios#1658]
## Which Version of Lottie are you using?

Lottie 3.4.0

## Expected Behavior 

The package is successfully built.

## Actual Behavior

```
carthage update  --platform iOS
```
Output:
```
xcodebuild: error: Unable to read project 'lottie-swift.xcodeproj' from folder '/Users/(redacted)/Carthage/Checkouts/lottie-ios/Example'.
	Reason: Project /Users/(redacted)/Carthage/Checkouts/lottie-ios/Example/lottie-swift.xcodeproj cannot be opened because it is missing its project.pbxproj file.
```

The issue is probably caused by non-existing file reference in https://github.com/airbnb/lottie-ios/blob/master/Example/Example.xcodeproj/project.xcworkspace/contents.xcworkspacedata .
The file got renamed but its contents were not updated.

**Comment by calda** [comment]
I'm not able to reproduce this issue, could you share more information about your Carthage configuration? A sample project would be very helpful.

**Comment by ondrej-hanslik-csob-cz** [comment]
Hey, I have tested it and it seems the problem appears only inside one project. The `Cartfile` is pretty simple because only lottie is in there. I am still trying to check what is causing the problem in that specific project.

However, note that the file reference I have listed above is definitely wrong.

**Comment by ondrej-hanslik-csob-cz** [comment]
Okey, it seems this was somehow caused by Carthage itself. It seems that renaming project files between versions 3.2.3 and 3.3.0 broke something because my Carthage was trying to build lottie 3.4.0 using paths from 3.2.3.
I have deleted everything related to lottie in the project folder and the problem got magically fixed.

My apologies for the troubles.
