### ISSUE TITLE
3.4.0 npm package is very large

### ISSUE THREAD

**Issue by hyandell** [airbnb/lottie-ios#1659]
Apologies if this is well known, please resolve/ignore if so.

I noticed that the latest version of lottie-ios is a lot larger than previous versions and am wondering if that was accidental.

https://www.npmjs.com/package/lottie-ios/v/3.4.0 - Total unpacked size 208MB
https://www.npmjs.com/package/lottie-ios/v/3.2.3 - Total unpacked size 779kB

Difference appears to be primarily be due to the inclusion of this file:

Tests/Artifacts/LottieTests.xcresult/Data/data.0~9u8KAGpgtSm-mQ12Py8RZUbYbDlBhM3w1I2MQO53K2CSn6IePp7g65DBcdXTYMfG1bgoJ-6x30fjnGe-2UYsDQ==

**Comment by calda** [comment]
Oops, sorry about that! Will make sure to not include that file in the 3.4.1 release

**Comment by calda** [comment]
Fixed in 3.4.1, which is only 2mb. Thanks for the report!
