### ISSUE TITLE
Rendered AnimationView goes blank when its animation property is set to another value

### ISSUE THREAD

**Issue by cocoatoucher** [airbnb/lottie-ios#1661]
## Which Version of Lottie are you using?

Lottie 3.4.0

1. Have an `AnimationView` that has its `animation` property set and currently rendered on screen.
2. Set this `AnimationView`'s `animation` property to another value (tested via `Animation.named()`)

This is a common scenario for switching the animation file between light and dark versions.

## Expected Behavior 
- AnimationView should render the newly set animation. (works below 3.4.0)

## Actual Behavior
- AnimationView goes blank and doesn't render anything.

## Animation JSON
- Tested with different animation files and was able to reproduce every time, also Expected Behavior works with versions below 3.4.0.

**Comment by calda** [comment]
I'm not able to reproduce this issue in our Example demo app (code change [here](https://github.com/airbnb/lottie-ios/commit/ff6506712cc75864e3b65453009b68b38d945005), gif below). Could you share a sample project or sample code that reproduces this issue?

<img src="https://user-images.githubusercontent.com/1811727/180890466-04e5ec76-6e69-4f2d-bbf0-04e138efae2a.gif" width=350>
