### ISSUE TITLE
Animation using inverted matte layer are suffering frame drops in 3.4.0

### ISSUE THREAD

**Issue by kirti-swiggy** [airbnb/lottie-ios#1683]
In lottie version 3.4.0 (and 3.4.1), frames are dropping for animations using inverted matte layer. 

I dug deep into the problem. Found out that https://github.com/airbnb/lottie-ios/pull/1388 is the cause. After reverting this change, animation seems to work fine.

## Which Version of Lottie are you using?

Lottie 3.4.0

## Expected Behavior 

https://user-images.githubusercontent.com/98816658/182025258-01d7e8bb-6241-41f3-9cb0-6d6e46aaf50b.mp4

## Actual Behavior
Animation doesn't play.

## Animation JSON
[lf20_eLe0Jq.json.zip](https://github.com/airbnb/lottie-ios/files/9228777/lf20_eLe0Jq.json.zip)

## Sample project

[TestLottie.zip](https://github.com/airbnb/lottie-ios/files/9228783/TestLottie.zip)

**Comment by calda** [comment]
Thanks for digging in and finding the change that caused this regression! I'll revert that change and add your sample animation to the regression suite.

**Comment by calda** [comment]
Fixed in https://github.com/airbnb/lottie-ios/pull/1684
