### ISSUE TITLE
Hidden flag ignored in CoreAnimation renderer

### ISSUE THREAD

**Issue by oblador** [airbnb/lottie-ios#1687]
When setting the `hd` flag to `true` on a layer, the old main thread renderer will correctly not show it, but the new Core Animation renderer will. 

## Which Version of Lottie are you using?

Lottie 3.4.1

## Expected Behavior 
![Simulator Screen Shot - iPhone 11 - 2022-08-02 at 17 05 47](https://user-images.githubusercontent.com/378279/182407980-ec826f8f-8256-4bcb-8a24-4cf51bebf601.png)

## Actual Behavior
![Simulator Screen Shot - iPhone 11 - 2022-08-02 at 17 05 33](https://user-images.githubusercontent.com/378279/182408022-24e29b75-0d84-47eb-a1ad-a289dceda113.png)

## Animation JSON
<details>
<pre>
{"v":"5.7.6","fr":29.9700012207031,"ip":0,"op":100,"w":225,"h":225,"nm":"Comp 1","ddd":0,"assets":[],"layers":[{"ddd":0,"ind":1,"ty":4,"nm":"Shape Layer 1","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[112.5,112.5,0],"ix":2,"l":2},"a":{"a":0,"k":[0,0,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"shapes":[{"ty":"gr","it":[{"ty":"rc","d":1,"s":{"a":0,"k":[111,111],"ix":2},"p":{"a":0,"k":[0,0],"ix":3},"r":{"a":0,"k":0,"ix":4},"nm":"Rectangle Path 1","mn":"ADBE Vector Shape - Rect","hd":true},{"ty":"fl","c":{"a":0,"k":[0.98431372549,0.737254901961,0.01568627451,1],"ix":4},"o":{"a":0,"ix":5,"k":[{"s":0,"t":0,"i":null,"o":null,"ti":null,"to":null,"h":1},{"s":100,"t":50,"i":null,"o":null,"ti":null,"to":null,"h":0},{"s":0,"t":100,"i":null,"o":null,"ti":null,"to":null,"h":0}]},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":true},{"ty":"tr","p":{"a":0,"k":[-3,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Rectangle 1","np":3,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":true}],"ip":0,"op":900.000036657751,"st":0,"bm":0}],"markers":[]}
</pre>
</details>

**Comment by calda** [comment]
Thanks for the report, fixed in https://github.com/airbnb/lottie-ios/pull/1689.
