### ISSUE TITLE
`CoreTextRenderLayer` incorrectly renders some letters partially off the frame

### ISSUE THREAD

**Issue by A30008910-wei** [airbnb/lottie-ios#1696]
Since Lottie 3.1.9, `CoreTextRenderLayer` is rendering some single line text out of the drawing frame if the letter strokes to descent (e.g. `j`, `g` and `y`).

Note: the images below were captured with `CoreTextRenderLayer.drawDebug(_:)`

Tested on 

* Xcode 14 Beta 4, iOS 16 simulator
* Xcode 13.4.1, iOS 15.5 simulator
* Xcode 13.4.1, macOS 12.4 & macOS 12.5

## Which Version of Lottie are you using?

Lottie 3.4.1 (but issue exists since 3.1.9)

## Expected Behavior 

<img width="270" src="https://user-images.githubusercontent.com/89169304/182768903-853d9931-ca05-44ec-8286-2b655edfd8f0.png" />

It looks like a previously removed workaround in the commit 766f555fc4a5e5b1271f9dbd53d2500d47abb20a can be applied to `CoreTextRenderLayer` for a fix.

```Swift
    guard let font = font else { return }

    // ...

    // This fixes a vertical padding issue that arises when drawing some fonts.
    // For some reason some fonts, such as Helvetica draw with and ascender that is greater than the one reported by CTFontGetAscender.
    // I suspect this is actually an issue with the Attributed string, but cannot reproduce.

    if let fillFrame = fillFrame {
      var o = [CGPoint] (repeating: .zero, count: 1)
      let count = CFArrayGetCount(CTFrameGetLines(fillFrame))
      if count > 0 {
        CTFrameGetLineOrigins (fillFrame, CFRange (location: count-1,length: 1), &o)
        let diff = CTFontGetDescent(font) - o[0].y
        ctx.translateBy(x: 0, y: diff)
      }
    } else if let strokeFrame = strokeFrame {
      var o = [CGPoint] (repeating: .zero, count: 1)
      let count = CFArrayGetCount(CTFrameGetLines(strokeFrame))
      if count > 0 {
        CTFrameGetLineOrigins (strokeFrame, CFRange (location: count-1,length: 1), &o)
        let diff = CTFontGetDescent(font) - o[0].y
        ctx.translateBy(x: 0, y: diff)
      }
    }
```

## Actual Behavior

Note that the letter `g` is partially out of the frame.

<img width="270" src="https://user-images.githubusercontent.com/89169304/182770313-1d4c8a84-a81b-4fff-8914-3802afe3f511.png" />

## Animation JSON

https://github.com/airbnb/lottie-ios/blob/master/Tests/Samples/Nonanimating/verifyLineHeight.json

**Comment by calda** [comment]
Fixed in #1697, thanks @weisunOW!
