### ISSUE TITLE
Crash on debug mode on iOS

### ISSUE THREAD

**Issue by MariusCatanoiu** [airbnb/lottie-ios#1708]
Works ok on release mode, but crashes on debug (simulator and physical device - iPhone 11). No issue on android

lottie-ios: 3.4.x
lottie-react-native: 5.1.4
react-native: 0.69.4

```
Lottie/BundleImageProvider.swift:70: Fatal error: Could not find image "" in bundle
2022-08-09 18:38:39.160481+0300 FootballRivals[90082:4467289] Lottie/BundleImageProvider.swift:70: Fatal error: Could not find image "" in bundle
INFO : BSG_KSCrashReport.c (1513): void bsg_kscrashreport_writeStandardReport(BSG_KSCrash_Context *const, const char *const): Writing crash report to /Users/myUser/Library/Developer/CoreSimulator/Devices/023DBC3E-E840-41EA-9C1A-219BEBC325D1/data/Containers/Data/Application/968C507E-9D38-4B0B-8F79-707B95DC41E2/Library/Caches/KSCrashReports/myApp/myApp-CrashReport-9FA94124-B947-4276-955D-7CD2968131C9.json
```

**Comment by calda** [comment]
In 3.4.1 we emit an assertion failure when an image cannot be found. We changed this to just log a message instead recently, but haven't cut a new release yet. You could either update to `master`, or as a temporary workaround set `LottieLogger.shared = .printToConsole` to suppress the assertion.
