### ISSUE TITLE
Swift - Use of unresolved identifier LOTAnimationView

### ISSUE THREAD

**Issue by nunogoncalves** [airbnb/lottie-ios#171]
Hi,

I'm trying Lottie on a barebones project using CocoaPods. 
`pod 'lottie-ios', '1.5.1'`

My bridging file 
`#import <Lottie/Lottie.h>`

With this, I don't need to add the import on my swift file (a ViewController). If I comment it, I need the import. Nevertheless the result is the same: 

I can't access `LOTAnimationView` but can access `LAAnimationView` though.
<img width="1076" alt="screenshot 2017-03-14 15 09 16" src="https://cloud.githubusercontent.com/assets/3007012/23907184/3bcdc09a-08c8-11e7-8ced-76caa5d0626c.png">

I'm not sure what else I can do. If it's relevant, I can add my project here. 
Thank you

**Comment by jmyers0022** [comment]
Does your `Podfile.lock` show version 1.5.1? I ran into the same thing, and it turned out I needed to run a `pod update` to update my local version.

**Comment by nunogoncalves** [comment]
Yap.
```
PODS:
  - lottie-ios (1.5.1)

DEPENDENCIES:
  - lottie-ios

SPEC CHECKSUMS:
  lottie-ios: f680a7c4cb7a567ecf258fde0f967913aff111b8

PODFILE CHECKSUM: 3e944e1de95ad45cc8668e5a7f30b560d9269608

COCOAPODS: 1.2.0.beta.1
```

**Comment by nunogoncalves** [comment]
So I have updated my Cocoapods gem with
```gem update cocoapods```
to the latest version ```1.2.1.beta.1```
and I got it working... I will never understand these issues.

**Comment by Achyut-Sagar** [comment]
Is your project name "Lottie" ? If it is, you must change it to something else.You can't call your project with the name of a module.

**Comment by nunogoncalves** [comment]
No it's not. 
I'm going to close this issue, because I zipped my project, sent it to a friend, and he had no trouble whatsoever. I'm guessing some derived data Xcode magic is preventing me from running this. Xcode just kills me... :(

**Comment by agibson73** [comment]
I am actually having the same issue at the moment. :(
