### ISSUE TITLE
3.4.1 via cocoapods won't compile

### ISSUE THREAD

**Issue by DancinDirk** [airbnb/lottie-ios#1710]
Attempted to install Lottie for the first time via cocoapods. App would not build
Downgraded to 3.4.0 and the app builds fine. 

## Which Version of Lottie are you using?

Lottie 3.4.1

## Expected Behavior 
The app will build

## Actual Behavior
The app does not build

**Comment by calda** [comment]
What error are you getting? This could be a dupe of https://github.com/airbnb/lottie-ios/issues/1685.

**Comment by calda** [comment]
Lottie supports Swift 5.3+. What version of Xcode are you using, and what is your project's Swift language version? If your project is targeting language version 4.x it will need to be updated to 5.3+.

**Comment by saimt** [comment]
doing pod install gives me this
`[!] CocoaPods could not find compatible versions for pod "lottie-ios":
  In Podfile:
    lottie-ios (= 3.4.1)

None of your spec sources contain a spec satisfying the dependency: `lottie-ios (= 3.4.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
`

Project's swift language: 5
Xcode: 13.4.1
cocoa pods version: 1.11.3

**Comment by calda** [comment]
have you tried the suggestions in the error message, like `pod repo update` or `pod install --repo-update`? What is in your Podfile?

**Comment by saimt** [comment]
it wasn't working for me until I opened terminal using Rosetta. Previously it was working without Rosetta
