### ISSUE TITLE
Core Animation engine unexpectedly ignoring spatial keyframes

### ISSUE THREAD

**Issue by brian-voong** [airbnb/lottie-ios#1711]
## Which Version of Lottie are you using?

Lottie 3.4.1

## Expected Behavior 
Using the old Main Thread animation, we get the expected bouncing dots effect:

https://user-images.githubusercontent.com/102084882/183986754-daa4056a-09cb-4c4a-9ac7-4361981891f1.mp4

## Actual Behavior
Missing bouncing dots effect using Core Animation

https://user-images.githubusercontent.com/102084882/183986597-a692e645-ed7e-4d26-80d5-83d65342ea48.mp4

## Animations JSON file
I can email the animation file to your team if necessary.

**Comment by calda** [comment]
Could you share a copy of the animation json? If you can't share it publicly you can email it to cal.stephens@airbnb.com

**Comment by brian-voong** [comment]
Any idea on release of 3.4.2?

**Comment by calda** [comment]
Probably soon -- you can also always point your project to depend on a specific commit on `master`

**Comment by brian-voong** [comment]
Cool, we'll wait for 3.4.2 to make it easier in the future for updates.
