### ISSUE TITLE
RenderingEngine in automatic mode incorrectly displays animations.

### ISSUE THREAD

**Issue by dsgnow** [airbnb/lottie-ios#1716]
Hello, I have a problem with an animation with the renderingEngine option enabled: RenderingEngineOption = .automatic. In this case, the animation does not display correctly. For .mainThread everything is ok but I don't want to set this option for the whole application because of one animation. I tried to change renderMode={"..."} for this particular animation but nothing changed. 

## Which Version of Lottie are you using?
Lottie 3.4.0, also checked on 3.4.1

## Expected Behavior 
The dot should animate along the path
https://user-images.githubusercontent.com/64083032/184303326-a1f3cd72-59df-4a0e-9463-f2e4f98ba60c.mov

## Actual Behavior
The dot at the end of the animation does not stick to the path
https://user-images.githubusercontent.com/64083032/184303354-40a6502d-dc0e-4eb2-aa27-634aaa991f27.mov

## Animation JSON
[circle.json.zip](https://github.com/airbnb/lottie-ios/files/9314384/circle.json.zip)

**Comment by calda** [comment]
Thanks for the report -- I tested on the latest version on master and this appears to be working correctly now. I think this problem was fixed by #1714.
