### ISSUE TITLE
Crash: LayerTransformNode.swift line 2147483647

### ISSUE THREAD

**Issue by siddew201** [airbnb/lottie-ios#1719]
## Which Version of Lottie are you using?

Lottie 3.4.0
## Expected Behavior 
Should not crash.

## Actual Behavior
Getting crash on end user device.

Crashed: com.apple.main-thread
0  libswiftCore.dylib             0x4751dc swift_slowAlloc.cold.1 + 16
1  libswiftCore.dylib             0x3d696c swift_slowAlloc + 120
2  libswiftCore.dylib             0x3d6b30 swift_allocObject + 64
3  Lottie                         0x2ad58 specialized CompositionLayer.init(layer:size:) + 4416466264 (LayerTransformNode.swift:4416466264)
4  Lottie                         0x2bb18 Array<A>.initializeCompositionLayers(assetLibrary:layerImageProvider:textProvider:fontProvider:frameRate:) + 4416469784 (CompositionLayersInitializer.swift:4416469784)
5  Lottie                         0x54d50 specialized PreCompositionLayer.init(precomp:asset:layerImageProvider:textProvider:fontProvider:assetLibrary:frameRate:) + 36 (PreCompositionLayer.swift:36)
6  Lottie                         0x2b9a8 Array<A>.initializeCompositionLayers(assetLibrary:layerImageProvider:textProvider:fontProvider:frameRate:) + 4416469416 (PreCompositionLayer.swift:4416469416)
7  Lottie                         0x12e8c specialized AnimationContainer.init(animation:imageProvider:textProvider:fontProvider:) + 35 (AnimationContainer.swift:35)
8  Lottie                         0x17d98 AnimationView.makeAnimationLayer() + 4416388504 (AnimationContainer.swift:4416388504)
9  Lottie                         0x17604 AnimationView.animation.setter + 132 (AnimationView.swift:132)
10 TCPApp                         0x7ccce4 AppModulesHelperProvider.getLoaderView() + 93 (AppModulesHelperProvider.swift:93)
11 TCPUIKit                       0x115d0 LoaderView.setUp() + 49 (LoaderView.swift:49)
12 TCPUIKit                       0x1115c LoaderView.init(frame:) + 27 (LoaderView.swift:27)
13 TCPUIKit                       0x11224 @objc LoaderView.init(frame:) + 4446753316 (<compiler-generated>:4446753316)
14 TCPUIKit                       0x915f0 closure #1 in UIViewController.showDotsLoaderScreen(hideNavBar:) + 149 (UIViewControllerExtension.swift:149)
15 TCPUIKit                       0x1cba0 thunk for @escaping @callee_guaranteed () -> () + 4446800800 (<compiler-generated>:4446800800)
16 libdispatch.dylib              0x25cc _dispatch_call_block_and_release + 32
17 libdispatch.dylib              0x40f4 _dispatch_client_callout + 20
18 libdispatch.dylib              0x128ac _dispatch_main_queue_drain + 928
19 libdispatch.dylib              0x124fc _dispatch_main_queue_callback_4CF + 44
20 CoreFoundation                 0x5097c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
21 CoreFoundation                 0xb4d0 __CFRunLoopRun + 2036
22 CoreFoundation                 0x1ebac CFRunLoopRunSpecific + 612
23 GraphicsServices               0x1360 GSEventRunModal + 164
24 UIKitCore                      0x40aa34 -[UIApplication _run] + 888
25 UIKitCore                      0x210e04 UIApplicationMain + 340
26 TCPApp                         0xa44940 main + 39 (AppDelegate.swift:39)
27 ???                            0x21f4538f8 (Missing)

**Comment by calda** [comment]
Can you share a copy of the animation json?
