### ISSUE TITLE
Trim path + gradient stroke = odd wobble effect

### ISSUE THREAD

**Issue by tonypinkevych** [airbnb/lottie-ios#1724]
## Which Version of Lottie are you using?

Lottie 3.4.2

## Expected Behavior 

https://user-images.githubusercontent.com/13913581/185784796-0dade04a-247c-41b4-a522-3616cbae605a.mov

## Actual Behavior

If play shape with `gradient stroke and trim path` it has very strange rendering behaviour. A strange wobble effect appears.
But if I use `rectangle with fill gradient` + `mask with solid stroke and trim path` then it's working perfectly.

https://user-images.githubusercontent.com/13913581/185784795-f66e60fb-88db-4290-835c-590a53ff5176.mov

## Animation JSON

Gradient stroke + trim path
[heart-bad.json.zip](https://github.com/airbnb/lottie-ios/files/9388791/heart-bad.json.zip)

Gradient rectangle + mask (solid stroke + trim path)
[heart-good.json.zip](https://github.com/airbnb/lottie-ios/files/9388792/heart-good.json.zip)

**Comment by calda** [comment]
What rendering engine are you using? The new Core Animation rendering engine fixes most issues like this.

**Comment by tonypinkevych** [comment]
Thanks for quick response. I'm using the default one because there is no doc on different rendering engines 🤔

My SwiftUI component looks as follows:

```swift
struct LottieView: UIViewRepresentable {
    let lottieFile: String
 
    let animationView = AnimationView()
 
    func makeUIView(context: Context) -> some UIView {
        let view = UIView(frame: .zero)
 
        animationView.animation = Animation.named(lottieFile)
        animationView.backgroundColor = .black
        animationView.contentMode = .scaleAspectFit
        animationView.play()
        animationView.loopMode = .loop
 
        view.addSubview(animationView)
 
        animationView.translatesAutoresizingMaskIntoConstraints = false
        animationView.heightAnchor.constraint(equalTo: view.heightAnchor).isActive = true
        animationView.widthAnchor.constraint(equalTo: view.widthAnchor).isActive = true
 
        return view
    }
}
```

**Comment by calda** [comment]
Here's info about how you can try the new Core Animation rendering engine: https://github.com/airbnb/lottie-ios/discussions/1627. I expect that will resolve your issue. We plan on enabling the new engine by default in Lottie 4.0, likely coming later this year.

**Comment by tonypinkevych** [comment]
@calda it's working perfectly, thanks!
