### ISSUE TITLE
Core Animation rendering engine doesn't respect precomp time stretch

### ISSUE THREAD

**Issue by boduoduo** [airbnb/lottie-ios#1725]
Some lottie features are not supported with Core Animation Engine

## Which Version of Lottie are you using?

Lottie 3.4.2

## Expected Behavior 
the left one on this video.
https://user-images.githubusercontent.com/18454418/185827872-989f1a36-ecb9-46b9-b7e2-882d372f1baf.MP4

## Actual Behavior
the right one on this video.
https://user-images.githubusercontent.com/18454418/185827872-989f1a36-ecb9-46b9-b7e2-882d372f1baf.MP4

## Animation JSON

{"v":"5.7.13","fr":60,"ip":0,"op":30,"w":30,"h":30,"nm":"list_global_liked_1129","ddd":0,"assets":[{"id":"comp_0","nm":"60x60icon light like","layers":[{"ddd":0,"ind":1,"ty":4,"nm":"形状","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[30.28,29.5,0],"ix":2,"l":2},"a":{"a":0,"k":[0,0,0],"ix":1,"l":2},"s":{"a":0,"k":[300,300,100],"ix":6,"l":2}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0,-1.52],[0.02,-0.14],[0,0],[0,0],[0,0],[-0.17,-1.36],[0,0],[0,0],[0.01,-0.12],[0,0],[0,0],[1.24,-0.07],[0,0],[0,0],[0.07,0.9],[0,0],[0,0],[-0.9,0.08],[0,0],[0,0],[-0.4,0.76],[0,0],[0,0],[-0.25,0.04],[0,0]],"o":[[1.52,0],[0,0.14],[0,0],[0,0],[0,0],[1.4,0],[0,0],[0,0],[0,0.12],[0,0],[0,0],[-0.25,1.23],[0,0],[0,0],[-0.92,0],[0,0],[0,0],[0,-0.92],[0,0],[0,0],[0.86,0],[0,0],[0,0],[0.11,-0.24],[0,0],[0,0]],"v":[[-0.02,-7.75],[2.73,-5],[2.7,-4.59],[2.66,-4.39],[2.36,-3.08],[5.28,-3.08],[8.01,-0.67],[8.03,-0.5],[8.03,-0.33],[8.01,0.03],[7.98,0.21],[6.91,5.54],[4.38,7.74],[4.21,7.75],[-6.28,7.75],[-8.02,6.14],[-8.03,6],[-8.03,-1.33],[-6.42,-3.08],[-6.28,-3.08],[-5.27,-3.08],[-3.23,-4.32],[-3.16,-4.47],[-1.94,-7.3],[-1.36,-7.74],[-1.25,-7.75]],"c":true},"ix":2},"nm":"路径 1","mn":"ADBE Vector Shape - Group","hd":false},{"ind":1,"ty":"sh","ix":2,"ks":{"a":0,"k":{"i":[[0,0],[0.27,-0.02],[0,0],[0,0],[0.02,-0.11],[0,0],[0,0],[-0.11,-0.03],[0,0],[0,0]],"o":[[-0.26,0.07],[0,0],[0,0],[-0.12,0],[0,0],[0,0],[0,0.11],[0,0],[0,0],[0,0]],"v":[[-4.21,-1.735],[-5,-1.595],[-5.27,-1.585],[-6.28,-1.585],[-6.52,-1.395],[-6.53,-1.335],[-6.53,6.005],[-6.34,6.245],[-6.28,6.255],[-4.21,6.255]],"c":true},"ix":2},"nm":"路径 2","mn":"ADBE Vector Shape - Group","hd":false},{"ind":2,"ty":"sh","ix":3,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0.39,-0.35],[0,0],[0,0],[-0.16,0.52],[0,0],[0,0],[0,0.08],[0.63,0.07],[0,0],[0,0],[-0.04,0.43],[0,0],[0,0],[0,0.09],[0.63,0.06]],"o":[[0,0],[0,0],[-0.22,0.51],[0,0],[0,0],[0.56,0],[0,0],[0,0],[0.01,-0.08],[0,-0.65],[0,0],[0,0],[-0.44,0],[0,0],[0,0],[0.02,-0.09],[0,-0.65],[0,0]],"v":[[-0.021,-6.25],[-0.761,-6.25],[-1.781,-3.88],[-2.711,-2.58],[-2.711,6.25],[4.209,6.25],[5.409,5.37],[5.439,5.25],[6.509,-0.09],[6.529,-0.33],[5.409,-1.58],[5.279,-1.58],[1.419,-1.58],[0.679,-2.4],[0.689,-2.5],[1.199,-4.72],[1.229,-5],[0.109,-6.24]],"c":true},"ix":2},"nm":"路径 3","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":0,"k":[0.40000000596,0.407843142748,0.443137258291,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"填充 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"形状","np":4,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":300,"st":0,"bm":0}]},{"id":"comp_1","nm":"60icon global liked","layers":[{"ddd":0,"ind":1,"ty":4,"nm":"形状","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[29.634,29.25,0],"ix":2,"l":2},"a":{"a":0,"k":[0,0,0],"ix":1,"l":2},"s":{"a":0,"k":[300,300,100],"ix":6,"l":2}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0,-1.46],[0.02,-0.14],[0,0],[0,0],[0,0],[-0.16,-1.09],[0,0],[0,0],[0.01,-0.1],[0,0],[0,0],[1.24,-0.07],[0,0],[0,0],[0.07,0.9],[0,0],[0,0],[-0.9,0.08],[0,0],[0,0],[-0.4,0.76],[0,0],[0,0],[-0.25,0.04]],"o":[[0,0],[1.44,0.08],[0,0.14],[0,0],[0,0],[0,0],[1.13,0],[0,0],[0,0],[0,0.1],[0,0],[0,0],[-0.25,1.23],[0,0],[0,0],[-0.92,0],[0,0],[0,0],[0,-0.92],[0,0],[0,0],[0.86,0],[0,0],[0,0],[0.11,-0.24],[0,0]],"v":[[-1.104,-7.75],[-0.914,-7.74],[1.666,-5],[1.636,-4.59],[1.606,-4.39],[1.306,-3.08],[5.636,-3.08],[7.866,-1.15],[7.876,-0.99],[7.886,-0.83],[7.866,-0.54],[7.836,-0.39],[6.656,5.54],[4.126,7.74],[3.956,7.75],[-6.134,7.75],[-7.874,6.14],[-7.884,6],[-7.884,-1.33],[-6.274,-3.08],[-6.134,-3.08],[-5.124,-3.08],[-3.084,-4.32],[-3.014,-4.47],[-1.794,-7.3],[-1.214,-7.74]],"c":true},"ix":2},"nm":"路径 1","mn":"ADBE Vector Shape - Group","hd":false},{"ind":1,"ty":"sh","ix":2,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0.04,-0.23],[0,0],[0,0],[-0.23,-0.04],[0,0],[0,0],[-0.04,0.23],[0,0],[0,0],[0.23,0.04]],"o":[[0,0],[-0.25,0],[0,0],[0,0],[0,0.24],[0,0],[0,0],[0.25,0],[0,0],[0,0],[0,-0.25],[0,0]],"v":[[-3.607,-1.193],[-4.607,-1.193],[-5.097,-0.783],[-5.107,-0.693],[-5.107,5.347],[-4.697,5.837],[-4.607,5.847],[-3.607,5.847],[-3.117,5.437],[-3.107,5.347],[-3.107,-0.693],[-3.517,-1.183]],"c":true},"ix":2},"nm":"路径 2","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"mm","mm":1,"nm":"合并路径 1","mn":"ADBE Vector Filter - Merge","hd":false},{"ty":"fl","c":{"a":0,"k":[1,0.176470592618,0.333333343267,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"填充 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"形状","np":4,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":300,"st":0,"bm":0}]},{"id":"comp_2","nm":"allcirclelined","layers":[{"ddd":0,"ind":1,"ty":0,"nm":"1","refId":"comp_3","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":315,"ix":10},"p":{"a":0,"k":[45,47,0],"ix":2,"l":2},"a":{"a":0,"k":[45,45,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"w":90,"h":90,"ip":0,"op":60,"st":0,"bm":0},{"ddd":0,"ind":2,"ty":0,"nm":"2","refId":"comp_3","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":270,"ix":10},"p":{"a":0,"k":[45,47,0],"ix":2,"l":2},"a":{"a":0,"k":[45,45,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"w":90,"h":90,"ip":0,"op":60,"st":0,"bm":0},{"ddd":0,"ind":3,"ty":0,"nm":"3","refId":"comp_3","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":225,"ix":10},"p":{"a":0,"k":[45,47,0],"ix":2,"l":2},"a":{"a":0,"k":[45,45,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"w":90,"h":90,"ip":0,"op":60,"st":0,"bm":0},{"ddd":0,"ind":4,"ty":0,"nm":"4","refId":"comp_3","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":180,"ix":10},"p":{"a":0,"k":[45,47,0],"ix":2,"l":2},"a":{"a":0,"k":[45,45,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"w":90,"h":90,"ip":0,"op":60,"st":0,"bm":0},{"ddd":0,"ind":5,"ty":0,"nm":"5","refId":"comp_3","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":135,"ix":10},"p":{"a":0,"k":[45,47,0],"ix":2,"l":2},"a":{"a":0,"k":[45,45,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"w":90,"h":90,"ip":0,"op":60,"st":0,"bm":0},{"ddd":0,"ind":6,"ty":0,"nm":"6","refId":"comp_3","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":90,"ix":10},"p":{"a":0,"k":[45,47,0],"ix":2,"l":2},"a":{"a":0,"k":[45,45,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"w":90,"h":90,"ip":0,"op":60,"st":0,"bm":0},{"ddd":0,"ind":7,"ty":0,"nm":"7","refId":"comp_3","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":45,"ix":10},"p":{"a":0,"k":[45,47,0],"ix":2,"l":2},"a":{"a":0,"k":[45,45,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"w":90,"h":90,"ip":0,"op":60,"st":0,"bm":0},{"ddd":0,"ind":8,"ty":0,"nm":"8","refId":"comp_3","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[45,47,0],"ix":2,"l":2},"a":{"a":0,"k":[45,45,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"w":90,"h":90,"ip":0,"op":60,"st":0,"bm":0}]},{"id":"comp_3","nm":"圆形","layers":[{"ddd":0,"ind":1,"ty":4,"nm":"line","sr":1,"ks":{"o":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":55,"s":[100]},{"t":57,"s":[0]}],"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":1,"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":0,"s":[45,45,0],"to":[0,-5.625,0],"ti":[0,5.625,0]},{"t":55,"s":[45,11.25,0]}],"ix":2,"l":2},"a":{"a":0,"k":[-0.019,-23.339,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"shapes":[{"ty":"gr","it":[{"ty":"rc","d":2,"s":{"a":1,"k":[{"i":{"x":[0.833,0.833],"y":[0.833,0.833]},"o":{"x":[0.167,0.167],"y":[0.167,0.167]},"t":0,"s":[3,20]},{"t":55,"s":[3,4]}],"ix":2},"p":{"a":0,"k":[0,0],"ix":3},"r":{"a":0,"k":20,"ix":4},"nm":"矩形路径 1","mn":"ADBE Vector Shape - Rect","hd":false},{"ty":"fl","c":{"a":0,"k":[1,0.176470588235,0.333333333333,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"填充 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[-0.019,-23.339],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"矩形 1","np":3,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":60,"st":0,"bm":0}]}],"layers":[{"ddd":0,"ind":1,"ty":0,"nm":"iconlightdianzan","refId":"comp_0","sr":1,"ks":{"o":{"a":1,"k":[{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":0,"s":[100]},{"t":5,"s":[0]}],"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[15,15,0],"ix":2,"l":2},"a":{"a":0,"k":[30,30,0],"ix":1,"l":2},"s":{"a":1,"k":[{"i":{"x":[0.667,0.667,0.667],"y":[1,1,1]},"o":{"x":[0.333,0.333,0.333],"y":[0,0,0]},"t":0,"s":[33.333,33.333,100]},{"t":5,"s":[13.333,13.333,100]}],"ix":6,"l":2}},"ao":0,"w":60,"h":60,"ip":0,"op":300,"st":0,"bm":0},{"ddd":0,"ind":2,"ty":0,"nm":"iconselected","refId":"comp_1","sr":1,"ks":{"o":{"a":1,"k":[{"i":{"x":[0.667],"y":[0.982]},"o":{"x":[0.333],"y":[0]},"t":5,"s":[0]},{"t":6,"s":[100]}],"ix":11},"r":{"a":1,"k":[{"i":{"x":[0.667],"y":[0.682]},"o":{"x":[0.167],"y":[0]},"t":5,"s":[0]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[-0.095]},"t":15,"s":[-15]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":20,"s":[10]},{"i":{"x":[0.833],"y":[1]},"o":{"x":[0.167],"y":[0]},"t":25,"s":[-4]},{"t":29,"s":[0]}],"ix":10},"p":{"a":0,"k":[8.917,20.667,0],"ix":2,"l":2},"a":{"a":0,"k":[11.75,47,0],"ix":1,"l":2},"s":{"a":1,"k":[{"i":{"x":[0.667,0.667,0.667],"y":[0.919,0.919,-1.956]},"o":{"x":[0.167,0.167,0.167],"y":[0,0,0]},"t":5,"s":[13.333,13.333,100]},{"i":{"x":[0.667,0.667,0.667],"y":[1,1,1]},"o":{"x":[0.333,0.333,0.333],"y":[-0.325,-0.325,2.956]},"t":10,"s":[40,40,100]},{"i":{"x":[0.833,0.833,0.833],"y":[1,1,1]},"o":{"x":[0.333,0.333,0.333],"y":[0,0,0]},"t":15,"s":[33.333,33.333,100]},{"t":20,"s":[33.333,33.333,100]}],"ix":6,"l":2}},"ao":0,"w":60,"h":60,"ip":0,"op":300,"st":0,"bm":0},{"ddd":0,"ind":3,"ty":0,"nm":"allcirclee","refId":"comp_2","sr":0.33333333333333,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[15,15,0],"ix":2,"l":2},"a":{"a":0,"k":[45,45,0],"ix":1,"l":2},"s":{"a":0,"k":[40,40,100],"ix":6,"l":2}},"ao":0,"w":90,"h":90,"ip":8,"op":28,"st":8,"bm":0}],"markers":[]}

**Comment by calda** [comment]
Are you using `RenderingEngineOption.automatic`, or `RenderingEngineOption.coreAnimation`?

**Comment by calda** [comment]
I tested and this issue occurs with `RenderingEngineOption.automatic`, so is definitely a bug. Will take a look.

**Comment by calda** [comment]
Thanks for the report, fixed in #1726.

**Comment by boduoduo** [comment]
Thanks!, it performs normally with branch 'master'
