### ISSUE TITLE
Animation shown wrong

### ISSUE THREAD

**Issue by Rozariozaro** [airbnb/lottie-ios#173]
I am trying to animate a globe using lottie framework. The animation is done using AfterEffects and exported using bodymovin plugin. I cant seem to get the right output. I dont know where I am going wrong. Please help me resolving this issue.. 

AEP file: [https://www.dropbox.com/s/8ztpuwkze1ln7cg/globe.aep?dl=0](url)
Json file: [https://www.dropbox.com/s/65baxbhszj99qch/globe.json?dl=0](url)
Expected output: [https://www.dropbox.com/s/cb8mvc6m54yltxi/globe.gif?dl=0](url)
My output: [https://www.dropbox.com/s/4epqu3qqo4cvwo5/globe%20output.mov?dl=0](url)

**Comment by therealsalih** [comment]
Hi @Rozariozaro Your animation contains one feature not currently supported called "Fill Rule" Track the progress on that feature here: https://github.com/airbnb/lottie-ios/issues/43

We're close to getting this done on iOS, just need a little more time

Thanks!

**Comment by gpeal** [comment]
@Rozariozaro FYI, this works on Android as of 2.0.0-beta1

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
