### ISSUE TITLE
Some layers cannot render transparent.

### ISSUE THREAD

**Issue by wickyou23** [airbnb/lottie-ios#1732]
Hello team,

I'm impressed with the new Lottie version. The core animation helps our app run smoother, but it has some problems with our animation, I think some layers cannot render transparent. Could you help us check it?

Thanks.

## Which Version of Lottie are you using?

Lottie 3.4.2

## Expected Behavior 
https://app.lottiefiles.com/share/3d38bd66-aa91-43d2-bf6e-171b9e02ae82

## Actual Behavior
![ezgif com-gif-maker](https://user-images.githubusercontent.com/5183190/186855246-c11ca8b0-c35a-4390-a413-d904e719a8e4.gif)

## Animation JSON
https://app.lottiefiles.com/share/3d38bd66-aa91-43d2-bf6e-171b9e02ae82

**Comment by calda** [comment]
Thanks for the report! Looks like there are two issues with this animation:
 1. The new engine was accidentally ignoring the gradient `location` values, so the alpha gradient was the wrong size. Fixed here: #1734.
 2. There also does seem to be an issue with gradient transparency, like you mentioned. I'm not sure what's causing this yet, but I'll look in to it more on Monday.

**Comment by calda** [comment]
Fixed the alpha rendering issue in #1737, thanks for the report!

**Comment by wickyou23** [comment]
@calda It works like a charm. Thanks for your support.
