### ISSUE TITLE
Fill does not animate with automatic rendering engine

### ISSUE THREAD

**Issue by ejensen** [airbnb/lottie-ios#1744]
## Which Version of Lottie are you using?

Lottie 3.4.3

## Expected Behavior

![MainThread](https://user-images.githubusercontent.com/915431/188901178-cb889447-433e-431e-a6c6-40f3a9b24855.gif)

## Actual Behavior

![CoreAnimation](https://user-images.githubusercontent.com/915431/188901199-6a5720b5-d0fc-48a3-ac03-c930652ee79e.gif)

## Animation JSON

[notifications_icon_animation.json.zip](https://github.com/airbnb/lottie-ios/files/9506887/notifications_icon_animation.json.zip)

**Comment by calda** [comment]
Thanks for the report, fixed in #1757.
