### ISSUE TITLE
Mask over shape loads but not displays

### ISSUE THREAD

**Issue by jimmy510s** [airbnb/lottie-ios#1745]
Hi,

I was trying to display an animation that a friend of mine gave me and in iOS it wasn't working when other animations did. Also the animation that didn't work on iOS was working correctly in the web previewer. So we discovered that if the animation has a mask over a shape it can't load. Another case that we had the same mask over a solid colour it worked like a charm. 

We are using
- After effects + bodymovin plugin
- iOS Lottie version 3.4.0

[examples.zip](https://github.com/airbnb/lottie-ios/files/9508510/examples.zip)

**Comment by calda** [comment]
I think this is because the `not_working.json` example uses Difference masks, which iOS does not support according to the [list of supported features](https://airbnb.io/lottie/#/supported-features).
