### ISSUE TITLE
AnimationView not on main thread - SwiftUI + UIViewRepresentable

### ISSUE THREAD

**Issue by jakesquareone** [airbnb/lottie-ios#1751]
Lottie 3.4.3

Using the LottieView inside a UIViewRepresentable (for SwiftUI) in the latest XCode (14.0) gives _"-[UIView init] must be used from main thread only"_

The AnimationView class is being instantiated when the LottieView UIViewRepresentable is created with a:
_let animationView = AnimationView()_

This has only just started to give a purple runtime error in XCode.

What is a better way to prepare the AnimationView in a UIViewRepresentable here?

**Comment by calda** [comment]
Can you share a sample project that reproduces this issue?

**Comment by UPFT-KazunoriAoki** [comment]
It happened in my environment when I added the following to "Other Swift Flags".
`-Xfrontend -warn-concurrency -Xfrontend -enable-actor-data-race-checks`

I'm glad if you can use it as a reference.

**Comment by kazuao** [comment]
It happened in my environment when I added the following to "Other Swift Flags".
`-Xfrontend -warn-concurrency -Xfrontend -enable-actor-data-race-checks`

I'm glad if you can use it as a reference.
