### ISSUE TITLE
animation not working as expected with this animation

### ISSUE THREAD

**Issue by mmdock** [airbnb/lottie-ios#1759]
## Which Version of Lottie are you using?

Lottie 3.4.3

## Expected Behavior 
Animation works like it does in the lottie web shared url

## Actual Behavior
there is no animation speed / duration.  In the with the lottie-ios pod it basically jumps from the start to the end immediately.  I have tried modifying the speed programmatically, with no success.  

## Animation JSON
can find JSON here: https://app.lottiefiles.com/share/368cf19d-c598-42ff-81c8-73c86a8ac04f

**Comment by adhityasp** [comment]
This issue still reproducible on 4.3.4

**Comment by calda** [comment]
The stroke animation is coming from a layer effect (under the `ef` layer key), which is not supported on iOS: https://airbnb.io/lottie/#/supported-features
