### ISSUE TITLE
Add support for `animating multiple keyframes for gradient startPoint` with the Core Animation renderer

### ISSUE THREAD

**Issue by jorgealegre** [airbnb/lottie-ios#1762]
Hello! I was super excited to see the performance improvements in https://github.com/airbnb/lottie-ios/discussions/1627. Although switching to the newer version of the library and forcing the use of the Core Animation did yield good CPU usage results, there is an animation we use in our project that doesn't render properly.

These are the logs I get in the console when using Core Animation:

```
Lottie/AnimationView.swift:1046: Assertion failed: Encountered Core Animation compatibility issues while setting up animation:
[shimmering orb rotating -withBlueInFront 4.gradient- vertical flowdown.Gradient Fill 1] The Core Animation rendering engine does not support animating multiple keyframes for gradient startPoint values (due to limitations of Core Animation `CAKeyframeAnimation`s).
[shimmering orb rotating -withBlueInFront 4.mask-flowdown dup.Gradient Fill 1] The Core Animation rendering engine does not support animating multiple keyframes for gradient startPoint values (due to limitations of Core Animation `CAKeyframeAnimation`s).
```

## Which Version of Lottie are you using?

Lottie 3.4.4

## Expected Behavior 

https://user-images.githubusercontent.com/13305965/194884059-083fce3b-b18e-4874-9f38-9dfd3fda4906.mov

## Actual Behavior

https://user-images.githubusercontent.com/13305965/194884191-90202011-399e-4bfb-ad8f-8fbb6a40cfb9.mov

## Animation JSON

[shield-button.json.zip](https://github.com/airbnb/lottie-ios/files/9746573/shield-button.json.zip)

**Comment by calda** [comment]
Implemented in https://github.com/airbnb/lottie-ios/pull/1798, thanks for the report and sample animation!

**Comment by jorgealegre** [comment]
@calda Nice! 🎉
