### ISSUE TITLE
LottieAnimationHelpers and LottieAnimationView convenience inits differ in default cache behavior

### ISSUE THREAD

**Issue by pejato** [airbnb/lottie-ios#1773]
## Which Version of Lottie are you using?

Lottie 3.x.x

## Expected Behavior 
The helpers in `LottieAnimationHelpers.swift` and the convenience inits in `LottieAnimationViewInitializers.swift` specify the same default cache.

## Actual Behavior

A default cache of `nil` is passed for helpers in `LottieAnimationHelpers.swift` and a default cache of `LRUAnimationCache.sharedCache` is passed for the convenience inits in `LottieAnimationViewInitializers.swift`.

[LottieAnimationViewInitializers](https://github.com/airbnb/lottie-ios/blob/b4bd0604ded9574807f41b4004b57dd1226a30a4/Sources/Public/Animation/LottieAnimationViewInitializers.swift) and [LottieAnimationHelpers](https://github.com/airbnb/lottie-ios/blob/b4bd0604ded9574807f41b4004b57dd1226a30a4/Sources/Public/Animation/LottieAnimationHelpers.swift) for reference.

**Comment by calda** [comment]
It makes sense to update the helpers in `LottieAnimationHelpers.swift` to include the cache by default, to match the other initializers. Would you be willing to make a pull request with this change @pejato?

**Comment by pejato** [comment]
@calda So fast wow ⚡️!

Absolutely, I can put up a PR after work today.

**Comment by calda** [comment]
that would be great, thanks!
