### ISSUE TITLE
LRUAnimationCache should be smarter?

### ISSUE THREAD

**Issue by marcelofabri** [airbnb/lottie-ios#1774]
## Which Version of Lottie are you using?

Lottie 3.5.0

## Expected Behavior 

`LRUAnimationCache` should:

1. have a memory limit
2. evict when getting memory warnings

I'm curious why we're not using a `NSCache` instead.

## Actual Behavior

The limit is based on number of animations, which can widely vary. It also never clears any cached animations under memory pressure.

**Comment by calda** [comment]
I'm open to providing alternative, smarter cache implementations, and updating the default cache used in our animation helper functions. I don't think we can remove or change the behavior of the existing `LRUAnimationCache` though, since that would be source breaking for consumers.

**Comment by marcelofabri** [comment]
Yeah, we can keep it around, but having the right default is the most important thing IMO.

**Comment by marcelofabri** [comment]
Also found https://github.com/airbnb/lottie-ios/pull/1411 which is pretty similar with what I had in mind
