### ISSUE TITLE
Star Review Example Missing

### ISSUE THREAD

**Issue by mknippen** [airbnb/lottie-ios#178]
Lottie's sample's show some great things that it can do!

One of my favorites is the star review system. This would be awesome to have as a sample. It would be a perfect example showing an animation reacting to a user's tap.

Is this something you could consider adding to the sample app?

**Comment by gpeal** [comment]
@mknippen We aren't planning on adding the star to our sample app because it's part of the Airbnb product and we don't ship Airbnb product animations with the sample app. Feel free to recreate it though :)
