### ISSUE TITLE
oldAnimation.removeFromSuperlayer  -  EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by zohairhadi** [airbnb/lottie-ios#1784]
I recently shifted to 3.5.0 and when I first ran the app, I had to change Animation -> LottieAnimation which fixed that error. But I came into this runtime error on `oldAnimation.removeFromSuperlayer()` as can be seen in the screenshot. I don't have an idea why this is happening. I have the correct version of pod installed and the deployment targets are correct too.

## Which Version of Lottie are you using?
Lottie 3.5.0

## Expected Behavior 

There shouldn't be an error here.

## Actual Behavior

<img width="949" alt="Screenshot 2022-10-19 at 12 31 53 PM" src="https://user-images.githubusercontent.com/45510142/196625686-c9c9efcb-f3a6-4bbd-971c-53f0a3b2b667.png">

**Comment by calda** [comment]
Does your project use storyboards? If so, the workaround in https://github.com/airbnb/lottie-ios/issues/1771#issuecomment-1279012842 should help (replace `AnimationView` with `LottieAnimationView` and `Animation` with `LottieAnimation` in the storyboard file).

If not, could you share a sample project that reproduces your issue?

**Comment by zohairhadi** [comment]
Thank you so much! Yes, this worked!
