### ISSUE TITLE
WebP images not supported

### ISSUE THREAD

**Issue by dhruvilPatelSwiggy** [airbnb/lottie-ios#1786]
The assets are not being fetched from the iOS end when lotties are exported as **Optimized JSON File** option(working fine in Android).
<img width="427" alt="6:24-PM-Wed--19Oct2022-screen" src="https://user-images.githubusercontent.com/89441718/196883322-46174da8-464c-41a5-baae-603715a7e4f9.png">

Possible cause: Inside the json file can see that image is of type:
- **png/jpeg** for non-optimized json file: ` "p": "data:image/jpeg;base64,...`
- **webp**  for optimized json file, which might be causing the issue: `"p": "data:image/webp;base64,...`

## Which Version of Lottie are you using?

Lottie 3.5.0

## Expected Behavior 

Without optimization it's working as expected:
https://user-images.githubusercontent.com/89441718/196882548-3e11217d-bf25-4e5f-93ca-5eb54fef2f9d.mp4

## Actual Behavior

With optimization unable to load:
https://user-images.githubusercontent.com/89441718/196882573-8a2fb09f-8e34-462e-b47d-a6fafe1aeb82.mp4

## Animation JSON

With & Without Optimization json files: 
[DemoLottie.zip](https://github.com/airbnb/lottie-ios/files/9827343/DemoLottie.zip)

## Sample Project

[SampleLottieProject.zip](https://github.com/airbnb/lottie-ios/files/9827353/SampleLottieProject.zip)

**Comment by calda** [comment]
iOS doesn't natively support WebP images, so animations using WebP won't work on iOS. 

Is this the LottieFiles optimizer? I'd suggest sharing feedback with them that the image optimization feature doesn't work on iOS.

**Comment by calda** [comment]
If we do end up adding dotLottie support (https://github.com/airbnb/lottie-ios/pull/1785), then that will help quite a lot with file sizes. I see your "unoptimized" animation is 500kb. If I compress that to a zip file (which is basically what a dotLottie file is) then it's only 120kb (even smaller than the 200kb "optimized" animation).

**Comment by mmdock** [comment]
didn't iOS add support for webp in iOS 14?
