### ISSUE TITLE
Swift import Lottie ,but xcode show:No such module 'Lottie'

### ISSUE THREAD

**Issue by zhoulornalion** [airbnb/lottie-ios#179]
Hi! 
I had installed lottie ,and this is the terminal picture:
![2017-03-19 5 04 46](https://cloud.githubusercontent.com/assets/26518676/24079596/77c41b74-0cc6-11e7-89c7-1a8226b688e6.jpg)
but when i type 'import Lottie' in swift,there is a mistake like this:
![2017-03-19 5 21 17](https://cloud.githubusercontent.com/assets/26518676/24079699/e73b2c20-0cc8-11e7-9922-2e8e2446bd60.jpg)
I'm not sure what else I can do.
thank you !

**Comment by xinsight** [comment]
Lottie is written in objc, so you might need to add an objective c bridging header, so that your swift code can "see" Lottie.

Easiest way is to add an objc class, and xcode will prompt to add the bridging header. Then add to the header:

    #import <Lottie/Lottie.h>

**Comment by zhoulornalion** [comment]
Thank you very much! Your answer is very helpful!

**Comment by zhoulornalion** [comment]
I had fix this problem, that was my mistake!
Just forgot command+B
