### ISSUE TITLE
README.md broken

### ISSUE THREAD

**Issue by chaseacton** [airbnb/lottie-ios#180]
Some of the markdown in the readme is broken. This is because GitHub formalized their markdown standards and headings now require a space after "#".

https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown

![screen shot 2017-03-20 at 1 40 01 pm](https://cloud.githubusercontent.com/assets/3307194/24120692/be8ea3f6-0d72-11e7-8811-8d8b0e4f4c81.png)

**Comment by madsonic** [comment]
I believe there is a typo too
`LOTAnimatedView.animationNamed("here_goes_your_json_file_name_without_.json")`
but should be 
`LOTAnimationView(name "here_goes_your_json_file_name_without_.json")`
