### ISSUE TITLE
Improper background (white veil) with coreAnimation rendering engine.

### ISSUE THREAD

**Issue by aureliencolas** [airbnb/lottie-ios#1800]
There's a difference in the rendering of an animation between the `mainThread` and `coreAnimation` rendering engines on iOS.
When rendering with `coreAnimation`, a slight white veil appears on top of part of the screen during the whole animation.

The issue is reproduced on an iPad pro with iOS 16.1

## Which Version of Lottie are you using?
Lottie 3.5.0 but the issue was already reproducible with 3.4.1

## Expected Behavior 
With `mainThread` rendering engine, the behaviour is correct.
![IMG_0196](https://user-images.githubusercontent.com/82930766/200356919-979406c3-41a4-4aee-bad1-e52a748adf19.PNG)

## Actual Behavior
With `coreAnimation` rendering engine, the behaviour is not correct.
![IMG_0195](https://user-images.githubusercontent.com/82930766/200356935-cd91201f-502b-4a58-a484-6b96839aafb5.PNG)

## Animation JSON
We have not made this JSON ourselves, it has been provided by our client.
[1440x1080.txt](https://github.com/airbnb/lottie-ios/files/9953417/1440x1080.txt)

Thanks for your help.
Aurélien.

**Comment by calda** [comment]
Thanks for the report -- the Core Animation and Main Thread rendering engines were using different color spaces. Fixed in #1801.

**Comment by aureliencolas** [comment]
Many thanks to you for this quick fix!


*Aurélien COLAS*iOS & AppleTV
[image: logo_ntg]

103 rue de Grenelle
CS 10841 - 75345 Paris 7 Cedex
Follow us on:
[image: logo_lkdn] <https://www.linkedin.com/company/netgem> [image:
logo_twitter] <https://twitter.com/netgem>


[image: Carrousel-signature_JUIN22.gif]
