### ISSUE TITLE
Generate xcframework/framework by Carthage has a problem

### ISSUE THREAD

**Issue by hojideli** [airbnb/lottie-ios#1809]
## Which Version of Lottie are you using?

Lottie 3.5.0

I used Xcode 14.1 latest version.
Mac os: Ventura 13.0

$ carthage update --platform ios
OR
$ carthage update --platform ios --use-xcframeworks

## What's happening

Error on (carthage_dependency)! Exit status of command 'carthage update --platform ios --use-xcframeworks' was 1 instead of 0.
*** Fetching lottie-ios
*** Checking out lottie-ios at "9e19fd1a62a1658538d2d1ec6f0e43b2cc989678"
*** xcodebuild output can be found in /var/folders/z1/jlhfp_c561z9mz12yg58n4rw0000gn/T/carthage-xcodebuild.MTJOpQ.log
A shell task (/usr/bin/xcrun xcodebuild -project /Users/Projects/Carthage/Checkouts/lottie-ios/Lottie.xcodeproj -scheme Lottie_iOS -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -showBuildSettings -skipUnavailableActions) failed with exit code 6:
2022-11-11 xcodebuild[1804:25219] [MT] DVTAssertions: ASSERTION FAILURE in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot1/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-21534.1/IDEFoundation/Execution/RunDestinations/IDERunDestinationCLI.m:566
Details:  Unhandled/unexpected case where no run destinations were produced.
Object:   <IDERunDestinationCLI>
Method:   +resolveRunDestinationsWithWorkspace:scheme:buildAction:schemeCommand:schemeTask:destinationSpecifications:architectures:timeout:runDestinationManager:deviceManager:fallbackPreferredSDK:fallbackPreferredArchitectures:skipUnsupportedDestinations:shouldSkipRunDestinationValidation:didDisambiguate:disambiguatedMatches:disambiguatedMatchesDescription:error:
Thread:   <_NSMainThread: 0x13260b490>{number = 1, name = main}
Hints: 

Backtrace:
  0   -[DVTAssertionHandler handleFailureInMethod:object:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1   _DVTAssertionHandler (in DVTFoundation)
  2   _DVTAssertionFailureHandler (in DVTFoundation)
  3   _sortDevicesForDisplay (in IDEFoundation)
  4   -[Xcode3CommandLineBuildTool _resolveRunDestinationsForBuildAction:] (in Xcode3Core)
  5   -[Xcode3CommandLineBuildTool _resolveInputOptionsWithTimingSection:] (in Xcode3Core)
  6   -[Xcode3CommandLineBuildTool run] (in Xcode3Core)
  7   XcodeBuildMain (in libxcodebuildLoader.dylib)
  8   start (in dyld)

**Comment by calda** [comment]
This looks like an issue with Carthage -- could you file an issue over on that project?

**Comment by hojideli** [comment]
The problem was in Carthage and  I use Swift Package Manager to get it
