### ISSUE TITLE
Lottie load json not show completed

### ISSUE THREAD

**Issue by yuanshuainiuniu** [airbnb/lottie-ios#1815]
Lottie 3.5

## Expected Behavior 
<img width="550" alt="image" src="https://user-images.githubusercontent.com/9314006/203465650-8a44c41c-25ac-4bb6-a528-59c1189edc59.png">

## Actual Behavior
![image](https://user-images.githubusercontent.com/9314006/203465671-2a9b07d9-c7a6-45a5-82bf-3a39a557c9f8.png)

## Animation JSON
https://images3.c-ctrip.com/ztrip/train_bin/22-11/img_me_xzqd3.json

**Comment by yuanshuainiuniu** [comment]
this issue appears only on ios devices, no problem with android devices

**Comment by rogerjin1206** [comment]
i have same issue....

**Comment by calda** [comment]
This animation seems to work when I test it on the latest version (4.0.1), so I'm going to close this issue. If you're still experiencing this problem feel free to re-open the issue and provide more information (ideally with a sample project if possible).

<img src="https://user-images.githubusercontent.com/1811727/208785050-dc8e09be-a568-49fa-b29c-034fee47fac1.gif" width=350>
