### ISSUE TITLE
Thread 1: EXC_BAD_ACCESS (code=1, address=0x8)

### ISSUE THREAD

**Issue by lixiang1994** [airbnb/lottie-ios#1828]
## Which Version of Lottie are you using?

Lottie 3.5.0

## Expected Behavior 

<img width="1465" alt="image" src="https://user-images.githubusercontent.com/13112992/205637090-cfc8212c-5ce4-41fa-9431-226ea6839203.png">

## Animation JSON

[loading.json.zip](https://github.com/airbnb/lottie-ios/files/10154110/loading.json.zip)

**Comment by calda** [comment]
Are you using storyboards / xibs? If so, this is the same issue as https://github.com/airbnb/lottie-ios/issues/1771.

**Comment by lixiang1994** [comment]
I use storyboard and LottieAnimationView

**Comment by lixiang1994** [comment]
```
fileprivate extension LottieAnimationView {
    
    /// 直播中控件更改颜色
    func set(living color: UIColor) {
        let _color = LottieColor(r: 1.0,  g: 0.28,  b: 0.2, a: 1.0)
        let value = ColorValueProvider(_color)
        setValueProvider(value, keypath: AnimationKeypath(keypath: "形状图层 7.形状 1.描边 1.Color"))
        setValueProvider(value, keypath: AnimationKeypath(keypath: "形状图层 6.形状 1.描边 1.Color"))
        setValueProvider(value, keypath: AnimationKeypath(keypath: "形状图层 5.形状 1.描边 1.Color"))
        setValueProvider(value, keypath: AnimationKeypath(keypath: "形状图层 3.形状 1.描边 1.Color"))
    }
}
```
