### ISSUE TITLE
OC version animation cannot be displayed completely

### ISSUE THREAD

**Issue by ChengQuanYe** [airbnb/lottie-ios#1833]
Lottie 2.5.3  OC version

can't show check
<img width="410" alt="image" src="https://user-images.githubusercontent.com/17982983/206075984-6cd408f0-2cc7-43d3-870e-a7d7f9534501.png">

expected
https://user-images.githubusercontent.com/17982983/206076099-3d60155b-083b-4b88-8cf8-a1ee1ca0d50f.mp4

actually
https://user-images.githubusercontent.com/17982983/206076126-dbbb8301-4f30-4350-9919-70be4eadd0e3.mp4

json:
{"v":"5.7.13","fr":60,"ip":0,"op":120,"w":96,"h":96,"nm":"房间内-关注","ddd":0,"assets":[{"id":"image_0","w":84,"h":84,"u":"images/","p":"follow_img_0.png","e":0}],"layers":[{"ddd":0,"ind":1,"ty":4,"nm":"爱心","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[48,51,0],"ix":2,"l":2},"a":{"a":0,"k":[0,0,0],"ix":1,"l":2},"s":{"a":1,"k":[{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"t":0,"s":[100,100,100]},{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"t":9,"s":[130,130,100]},{"t":24.880859375,"s":[0,0,100]}],"ix":6,"l":2}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[-0.846,-0.87],[-1.312,0],[0,-2.557],[0,0],[0,7.426],[-2.575,0]],"o":[[0.846,-0.87],[2.575,0],[0,6.757],[0,0],[0,-2.557],[1.312,0]],"v":[[0,-5.594],[3.341,-7],[8,-2.009],[0,7],[-8,-2.009],[-3.341,-7]],"c":true},"ix":2},"nm":"1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"gf","o":{"a":0,"k":100,"ix":10},"r":1,"bm":0,"g":{"p":3,"k":{"a":0,"k":[0,0.985,0.422,0.563,0.5,0.993,0.515,0.484,1,1,0.607,0.405],"ix":9}},"s":{"a":0,"k":[8,-7],"ix":5},"e":{"a":0,"k":[-8,-7],"ix":6},"t":1,"nm":"2","mn":"ADBE Vector Graphic - G-Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[300,300],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"Gradient Fill 1","np":2,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":300,"st":0,"bm":0},{"ddd":0,"ind":2,"ty":4,"nm":"对号","sr":1,"ks":{"o":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":23.105,"s":[0]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":24.881,"s":[100]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":57.229,"s":[100]},{"t":72.15625,"s":[0]}],"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[47,52.466,0],"ix":2,"l":2},"a":{"a":0,"k":[-2.333,10.722,0],"ix":1,"l":2},"s":{"a":1,"k":[{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"t":57.229,"s":[100,100,100]},{"t":72.15625,"s":[0,0,100]}],"ix":6,"l":2}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0]],"v":[[6.626,3.614],[-6.626,3.614],[-6.626,-3.614]],"c":false},"ix":2},"nm":"4","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"gs","o":{"a":0,"k":100,"ix":9},"w":{"a":0,"k":3,"ix":10},"g":{"p":3,"k":{"a":0,"k":[0,0.985,0.422,0.563,0.5,0.993,0.515,0.484,1,1,0.607,0.405],"ix":8}},"s":{"a":0,"k":[6.626,-3.614],"ix":4},"e":{"a":0,"k":[-6.626,-3.614],"ix":5},"t":1,"lc":2,"lj":2,"bm":0,"nm":"5","mn":"ADBE Vector Graphic - G-Stroke","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[300,300],"ix":3},"r":{"a":0,"k":-45,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"3","np":2,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false},{"ty":"tm","s":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":24.881,"s":[100]},{"t":33,"s":[0]}],"ix":1},"e":{"a":0,"k":100,"ix":2},"o":{"a":0,"k":0,"ix":3},"m":1,"ix":2,"nm":"修剪路径 1","mn":"ADBE Vector Filter - Trim","hd":false}],"ip":0,"op":300,"st":0,"bm":0},{"ddd":0,"ind":3,"ty":4,"nm":"成员","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[48,48,0],"ix":2,"l":2},"a":{"a":0,"k":[0,0,0],"ix":1,"l":2},"s":{"a":1,"k":[{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"t":57.229,"s":[0,0,100]},{"t":75,"s":[100,100,100]}],"ix":6,"l":2,"x":"var $bm_rt;\nvar n, n, t, t, v, amp, freq, decay;\n$bm_rt = n = 0;\nif (numKeys > 0) {\n    $bm_rt = n = nearestKey(time).index;\n    if (key(n).time > time) {\n        n--;\n    }\n}\nif (n == 0) {\n    $bm_rt = t = 0;\n} else {\n    $bm_rt = t = $bm_sub(time, key(n).time);\n}\nif (n > 0 && t < 1) {\n    v = velocityAtTime($bm_sub(key(n).time, $bm_div(thisComp.frameDuration, 10)));\n    amp = 0.06;\n    freq = 3;\n    decay = 5;\n    $bm_rt = $bm_sum(value, $bm_div($bm_mul($bm_mul(v, amp), Math.sin($bm_mul($bm_mul($bm_mul(freq, t), 2), Math.PI))), Math.exp($bm_mul(decay, t))));\n} else {\n    $bm_rt = value;\n}"}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0.828],[0.828,0],[0,0],[0,-0.828],[-0.828,0],[0,0]],"o":[[0,-0.828],[0,0],[-0.828,0],[0,0.828],[0,0],[0.828,0]],"v":[[6,5.5],[4.5,4],[-4.5,4],[-6,5.5],[-4.5,7],[4.5,7]],"c":true},"ix":2},"nm":"7","mn":"ADBE Vector Shape - Group","hd":false},{"ind":1,"ty":"sh","ix":2,"ks":{"a":0,"k":{"i":[[0,2.761],[2.761,0],[0,-2.761],[-2.761,0]],"o":[[0,-2.761],[-2.761,0],[0,2.761],[2.761,0]],"v":[[5,-2],[0,-7],[-5,-2],[0,3]],"c":true},"ix":2},"nm":"8","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"mm","mm":1,"nm":"9","mn":"ADBE Vector Filter - Merge","hd":false},{"ty":"gf","o":{"a":0,"k":100,"ix":10},"r":1,"bm":0,"g":{"p":3,"k":{"a":0,"k":[0,0.985,0.422,0.563,0.5,0.993,0.515,0.484,1,1,0.607,0.405],"ix":9}},"s":{"a":0,"k":[6,-7],"ix":5},"e":{"a":0,"k":[-6,-7],"ix":6},"t":1,"nm":"abc","mn":"ADBE Vector Graphic - G-Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[300,300],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"6","np":4,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":300,"st":0,"bm":0},{"ddd":0,"ind":4,"ty":2,"nm":"bg","refId":"image_0","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[48,48,0],"ix":2,"l":2},"a":{"a":0,"k":[42,42,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"ip":0,"op":300,"st":0,"bm":0}],"markers":[]}

**Comment by calda** [comment]
This animation appears to work correctly in the latest version of Lottie (I just tested on 4.0.1):

<img src="https://user-images.githubusercontent.com/1811727/208784756-dd38f1c3-1ded-4954-a358-016c3616164f.gif" width=350>
