### ISSUE TITLE
In my app Lottie is taking too much time to load

### ISSUE THREAD

**Issue by prachit1105** [airbnb/lottie-ios#1840]
Hello, Great work guys. we were getting crash some time on device after loading screen where Lottie used. I have gone through Time profile and in MainThreadAnimationLayer file Xcode showing 81.5%
```
public override func display() {
    guard Thread.isMainThread else { return }
    var newFrame: CGFloat
    if
      let animationKeys = animationKeys(),
      !animationKeys.isEmpty
    {
      newFrame = presentation()?.currentFrame ?? currentFrame //81.5%
    } else {
      // We ignore the presentation's frame if there's no animation in the layer.
      newFrame = currentFrame
    }
    if respectAnimationFrameRate {
      newFrame = floor(newFrame)
    }
    animationLayers.forEach { $0.displayWithFrame(frame: newFrame, forceUpdates: false) }
  }

```

## Which Version of Lottie are you using?

Lottie 3.x.x

## Expected Behavior 
I just want to know can we reduce this weightage .

**Comment by calda** [comment]
The new Core Animation rendering engine ([enabled by default in Lottie 4.0](https://github.com/airbnb/lottie-ios/discussions/1832)) eliminates the CPU overhead of playing most Lottie animations. Please try that and let us know how it goes!
