### ISSUE TITLE
Provide correct currentProgress when using .mainThread rendering engine

### ISSUE THREAD

**Issue by goergisn** [airbnb/lottie-ios#1845]
## Which Version of Lottie are you using?

Lottie 4.0.1 (Also noticed on 4.0.0)

## Expected Behavior 
Asking the AnimationView its `currentProgress` should return the correct progress regardless of using the `.mainThread` or `.coreAnimation` rendering engine

## Actual Behavior
The `currentProgress` property always returns 0 when using the `.mainThread` rendering engine.

### Discovery

After some investigation it seems that `MainThreadAnimationLayer` is not updating the `currentFrame` property correctly. From my uninformed point of view it looks like it should be updated in the `display()` override when updating all animationLayers with the newFrame.

### Potential fix

Happy to create a Pull Request for it if this is the correct place.

```
  public override func display() {
    guard Thread.isMainThread else { return }
    var newFrame: CGFloat
    defer { currentFrame = newFrame }
    if
      let animationKeys = animationKeys(),
      !animationKeys.isEmpty
    {
      newFrame = presentation()?.currentFrame ?? currentFrame
    } else {
      // We ignore the presentation's frame if there's no animation in the layer.
      newFrame = currentFrame
    }
    if respectAnimationFrameRate {
      newFrame = floor(newFrame)
    }
    animationLayers.forEach { $0.displayWithFrame(frame: newFrame, forceUpdates: false) }
  }
```

**Comment by goergisn** [comment]
@calda I just verified that it (based on my tests with Lottie 3.1.5) never reflected the current animation value but with the introduction of `CoreAnimationLayer` the behavior started to be different based on the used rendering engine.

I created a PR that addresses it https://github.com/airbnb/lottie-ios/pull/1848

**Comment by calda** [comment]
Closing this issue given the discussion here: https://github.com/airbnb/lottie-ios/pull/1848#issuecomment-1346901488

Thanks for the report
