### ISSUE TITLE
setValueProvider not working as before

### ISSUE THREAD

**Issue by calda** [airbnb/lottie-ios#1847]
### Discussed in https://github.com/airbnb/lottie-ios/discussions/1846

<div type='discussions-op-text'>

<sup>Originally posted by **ana-bonnet** December 12, 2022</sup>
Hello - hope you are all good.

We just update the SDK from 3.4.3 to 4.0.1 using cocoa pods. We are using a few simple animations that contains only one color, for example we have a circular loader and we have been updating the color with the code below, have been working great but since we updated the library it doesn't work anymore, the JSON hasn't change, so does any of this flow have been updated in the 4.0.1 version? Do I need to change anything?

`let animationView: LottieAnimationView = LottieAnimationView(name: "loader")`
`let keypath = AnimationKeypath(keys: ["**", "Stroke 1", "**", "Color"])`
`let colorProvider = ColorValueProvider(theme.tintColor.lottieColorValue)`  
`animationView.setValueProvider(colorProvider, keypath: keypath)`

Thanks a lot in advance.</div>

**Comment by ana-bonnet** [comment]
Hey here a copy of the animation
[loader.zip](https://github.com/airbnb/lottie-ios/files/10209271/loader.zip)

**Comment by dtodereanfourthline** [comment]
I have the same issue... can someone look into this?
`logHierarchyKeypaths()` is not printing anything anymore either.
This is happening after updating from 3.2.3 to the latest master version

**Comment by dtodereanfourthline** [comment]
@calda this is a blocker and I find it weird to ignore such an issue? 
Why don't old lottie jsons work anymore? What changed after 4.x.x?

**Comment by calda** [comment]
Have you tried using the original Main Thread rendering engine as a workaround? You can set `LottieConfiguration.shared.renderingEngine = .mainThread` or pass a custom config to your `LottieAnimationView`.

**Comment by dlewandaDK** [comment]
Following along here as it looks like your suggestion @calda will work for us, but I'd love to not have to render on the main thread as soon as I can get the color right. Any idea if/when this might be resolved?

**Comment by dtodereanfourthline** [comment]
I created a new project, I set the animation in `viewDidLoad()` and yet `logHierarchyKeypaths()` is still not printing anything.
Why did the API change? The documentation seems the same.

**Comment by karlpuusepp** [comment]
If anyone else has issues with `logHierarchyKeypaths()` not printing anything, the issue is that `LottieLogger` does not print INFO messages by default for non-DEBUG builds. This includes the precompiled `.xcframework` as well as Carthage integrations.

A workaround is to define a custom info logger:
```swift
LottieLogger.shared = LottieLogger(info: { print($0()) })
```

**Comment by ppamorim** [comment]
Yes the `coreAnimation` renderer is broken. I couldn't change the colour of this animation: https://lottiefiles.com/12195-locked

I had to init lottie with this configuration:

```swift
final class Lockview: LottieAnimationView {
  
  override init(frame: CGRect) {
    super.init(
      animation: LottieAnimation.named("12195-locked"),
      configuration: LottieConfiguration(renderingEngine: RenderingEngineOption.mainThread)
    )
    initialConfig()
  }

  required init?(coder aDecoder: NSCoder) {
    super.init(
      animation: LottieAnimation.named("12195-locked"),
      configuration: LottieConfiguration(renderingEngine: RenderingEngineOption.mainThread)
    )
    initialConfig()
  }
}
```

**Comment by calda** [comment]
@ppamorim, could you please file a new issue with the full sample code of `initialConfig()` that behaves unexpectedly when using the Core Animation rendering engine? If you share that part I'll take a look.

**Comment by calda** [comment]
How are you attempting to change the color of the animation?

**Comment by ppamorim** [comment]
@calda I tried to replicate but success, I rightifully copied the class to the another project and I can't replicate, could the deployment target to 13.0 trigger this issue? I can't test on 13.0 because Xcode 14.3.1 has a bug where the simulator crashes on this version.
Everything is terrible :(
