### ISSUE TITLE
Using rendering engine .coreAnimation showing animation differently than before

### ISSUE THREAD

**Issue by trilliwon** [airbnb/lottie-ios#1855]
## Which Version of Lottie are you using

Lottie 4.0.1

## Expected Behavior 

- .coreAnimation RenderingEngine show same as .mainThread engine and [web-player](https://lottiefiles.com/web-player) playing

<img src="https://user-images.githubusercontent.com/14218787/207595837-40d56ba3-912d-4daa-b916-e9d0fcc98ffc.png"  width="200" />

## Actual Behavior

- different with web-player and .mainThread engine

<img src="https://user-images.githubusercontent.com/14218787/207602195-dcd95022-1c00-4b32-94f2-f442119ff90b.png"  width="200" />

## Animation JSON

- https://static.toss.im/lotties/general/loan-load.json

**Comment by pravintate** [comment]
have similar issue in iOS colors are not visible as well as animation not work as per expectation but when I see json in web browsers preview then it works fine.

**Comment by calda** [comment]
Thanks for the report! Fixed in #1872.
