### ISSUE TITLE
Animation and colors are not showing as per the JSON file

### ISSUE THREAD

**Issue by pravintate** [airbnb/lottie-ios#1859]
## Which Version of Lottie are you using?

Lottie 4.0.1

## Expected Behavior 
<img width="345" alt="Screenshot 2022-12-15 at 6 02 59 PM" src="https://user-images.githubusercontent.com/12951399/207860233-11e45093-60f1-4784-a1ba-e31ebac681e3.png">

## Actual Behavior
<img width="231" alt="Screenshot 2022-12-15 at 6 03 49 PM" src="https://user-images.githubusercontent.com/12951399/207860430-e5d13588-d300-48d4-a8ea-98c6978ab50c.png">

## Animation JSON

https://user-images.githubusercontent.com/12951399/207861481-2eb25ff6-8979-49f8-89a4-be87657b030e.mov

Code 
`
func loader() {

        let animation = LottieAnimation.named("lodingJSON",
                                        bundle: .main,
                                        subdirectory: nil, animationCache: nil)
                                        
        let animationView = LottieAnimationView(animation: animation,
                                                configuration: LottieConfiguration(renderingEngine: .automatic))
                                                
        animationView.frame = view.bounds
        
        animationView.contentMode = .scaleAspectFit
        
        animationView.loopMode = .loop
        
        animationView.animationSpeed = 0.5
        
        view.addSubview(animationView)
        
        animationView.play()
        
    }
    
`

**I'm facing two issues as below:** 
1. Animation not showing originals colors instead of that it showing black color only, but when I check it in browser Lottie viewer then it showing the color. 
2. In Lottie viewer from browser animation show perfect but in app it look not correct. 

Am I missing anything here, please let me know. 
Thanks.

**Comment by calda** [comment]
Can you share a copy of your animation json file?
