### ISSUE TITLE
Lottie animation Crash on IOS 16

### ISSUE THREAD

**Issue by sychiam** [airbnb/lottie-ios#1864]
It working fine after update my device to iOS 16, it always crash at here. If below version iOS 16 it no any problem. Any idea for this problem ?

## Which Version of Lottie are you using?

Lottie 3.4.0

## Actual Behavior
<img width="747" alt="Screenshot 2022-12-19 at 5 37 04 PM" src="https://user-images.githubusercontent.com/110146381/208394800-0d649c18-8bf1-4559-b1cc-6dfaf14d4843.png">

**Comment by calda** [comment]
Does your project use storyboards? If so this is probably the same issue as https://github.com/airbnb/lottie-ios/issues/1830. If not, could you share a sample project that reproduces this issue?

**Comment by joanmolinas** [comment]
I've found the solution in another discussion #1771.

**Comment by sychiam** [comment]
Thanks..  I change the class name  in Storyboard from AnimationView to LottieAnimationView . It works !!! 


> I've found the solution in another discussion #1771.
