### ISSUE TITLE
`LottieAnimationView`'s `play(toFrame:)` does not update `currentFrame`

### ISSUE THREAD

**Issue by pejato** [airbnb/lottie-ios#1865]
## Which Version of Lottie are you using?

Latest master, commit hash: 0ceb3ece6feffeb213e6cc6b9fcea0b3b8ad507f

When I call `play(toFrame: someFrame)` on a `LottieAnimationView` and read `animationView.currentFrame` after the animation has completed, I get back `0.0` instead of `someFrame`.

## Expected Behavior 
After `play(toFrame: someFrame)` completes, I would expect that `animationView.currentFrame == someFrame`

## Actual Behavior
After `play(toFrame: someFrame)` completes, `animationView.currentFrame == 0.0`.

I tested this with the Lottie example workspace (Lottie.xcworkspace) by adding

```
      animationView.play(toFrame: 86) { _ in
          print("Current frame = \(self.animationView.currentFrame)")
      }
``` 

at the bottom of AnimationPreviewViewController.viewDidLoad and commenting out the CADisplayLink related logic (updateAnimation, animationCallback) and opening `9squares_AlBoardman`. I also changed the loopMode of the animation view in this file to `playOnce`

**Comment by calda** [comment]
Is this a regression, or has it always behaved this way?

**Comment by pejato** [comment]
If it's a regression it has been around for a little while, I think. I initially repro'd this on commit c23ff9ec3bb65ed9ef5037d18d0ebc3b04cdf110 and repro'd it for the issue with a newer commit.
