### ISSUE TITLE
Loading animation has blink when animation loops

### ISSUE THREAD

**Issue by zhaodg** [airbnb/lottie-ios#188]
Animation blinks just before looping. 
[loading.zip](https://github.com/airbnb/lottie-ios/files/863584/loading.zip) It is all right on HTML or Android or iOS Simulator.
My device is iPhone6s iOS9

**Comment by zhaodg** [comment]
Simulator have same problem, but after 3 or more loops.

**Comment by zhaodg** [comment]
AE file.
[loading.aep.zip](https://github.com/airbnb/lottie-ios/files/863681/loading.aep.zip)

**Comment by zhaodg** [comment]
If the loading animation does not have blink, it will have a a moment's pause between the last frame and the first frame.

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
