### ISSUE TITLE
Main Thread renderer shape layer issue

### ISSUE THREAD

**Issue by snow-google** [airbnb/lottie-ios#1880]
The main thread renderer does not render shape layers with certain combinations of contentMode and frame height/width. The easiest repro is when the content mode is set to aspect fit. In this scenario, having an animationView with a larger height than width causes the animation to not render while having a larger width than height seems to work fine. The CoreAnimation renderer has a different issue with this same animation. Here is the issue in case it is helpful: https://github.com/airbnb/lottie-ios/pull/1878. There are similar issues when using contentMode aspect fill.

## Which Version of Lottie are you using?

Lottie 3.5.0

## Expected Behavior 

When width of AnimationView exceeds height (correct):
![width bigger](https://user-images.githubusercontent.com/121244810/209380577-98018e2b-dfea-4588-92c1-0d658cfb72fd.png)

## Actual Behavior

When height of AnimationView exceeds width (incorrect):
![height bigger](https://user-images.githubusercontent.com/121244810/209380721-36b88fd3-9ff8-4e3d-b887-d2c3879af3d2.png)

## Animation JSON

{"v":"5.1.10","fr":60,"ip":0,"op":18,"w":96,"h":96,"nm":"Video_Off_On","ddd":0,"assets":[],"layers":[{"ddd":0,"ind":1,"ty":4,"nm":"Video_Icon","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[48,48,0],"ix":2},"a":{"a":0,"k":[12,8,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"hasMask":true,"masksProperties":[{"inv":false,"mode":"s","pt":{"a":1,"k":[{"i":{"x":1,"y":1},"o":{"x":0.4,"y":0},"n":"1_1_0p4_0","t":0,"s":[{"i":[[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0]],"v":[[2.053,-7.01],[0.363,-5.32],[24.003,18.32],[25.693,16.63]],"c":true}],"e":[{"i":[[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0]],"v":[[2.053,-7.01],[0.363,-5.32],[0.365,-5.313],[2.055,-7.003]],"c":true}]},{"t":17}],"ix":1},"o":{"a":0,"k":100,"ix":3},"x":{"a":0,"k":0,"ix":4},"nm":"Mask 1"}],"shapes":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0.74,0],[0,0],[0,-0.73],[0,0],[-0.73,0],[0,0],[0,0.73],[0,0],[0,0],[0,0]],"o":[[0,0],[0,-0.73],[0,0],[-0.73,0],[0,0],[0,0.73],[0,0],[0.74,0],[0,0],[0,0],[0,0],[0,0]],"v":[[18.67,6],[18.67,1.33],[17.33,0],[1.33,0],[0,1.33],[0,14.67],[1.33,16],[17.33,16],[18.67,14.67],[18.67,10],[24,15.33],[24,0.67]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":0,"k":[0,0,0,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":1,"k":[{"i":{"x":0.999,"y":1},"o":{"x":0.4,"y":0},"n":"0p999_1_0p4_0","t":0,"s":[{"i":[[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0]],"v":[[0.364,-5.32],[-1.326,-3.63],[22.314,20.01],[24.004,18.32]],"c":true}],"e":[{"i":[[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0]],"v":[[0.364,-5.32],[-1.326,-3.63],[-1.346,-3.643],[0.344,-5.333]],"c":true}]},{"t":17}],"ix":2},"nm":"Path 2","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":0,"k":[0,0,0,1],"ix":4},"o":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":16,"s":[100],"e":[0]},{"t":17}],"ix":5},"r":1,"nm":"Fill 2","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Group 1","np":2,"cix":2,"ix":3,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":18,"st":0,"bm":0},{"ddd":0,"ind":2,"ty":4,"nm":"BG","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[48,48,0],"ix":2},"a":{"a":0,"k":[0,0,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ty":"rc","d":1,"s":{"a":0,"k":[96,96],"ix":2},"p":{"a":0,"k":[0,0],"ix":3},"r":{"a":0,"k":0,"ix":4},"nm":"BG_Path","mn":"ADBE Vector Shape - Rect","hd":false},{"ty":"fl","c":{"a":0,"k":[1,1,1,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Rectangle 1","np":2,"cix":2,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":18,"st":0,"bm":0}],"markers":[]}

**Comment by nevil** [comment]
Not sure if this is helpful in any way for investigating this issue...
It seems like disabling the use of the mask layer makes it render.
(although incorrectly as the mask is missing)

So something related to the scale transform on the RootAnimationLayer and using layer masks?

**Comment by nevil** [comment]
It seems to me like the issue is the `veryLargeRect` constant that is used when creating the subtract mask.
```swift
        /// Add a bounds rect to invert the mask
        let newPath = CGMutablePath()
        newPath.addRect(CGRect.veryLargeRect)
        newPath.addPath(shapePath)
        path = newPath
```

On the iPhone 14 Pro rendering will work when shrinking the veryLargeRect by half.
I guess the size becomes too large when the scale transform is applied for the `scaleToFill` / `scaleAspectFit` / `scaleAspectFill` modes.

 Maybe the simplest change is to just reduce the size of the `veryLargeRect ` constant?

 ```swift
extension CGRect {
    static var veryLargeRect: CGRect {
    CGRect(
      x: -10_000_000,
      y: -10_000_000,
      width: 20_000_000,
      height: 20_000_000)
  }
}
```

**Comment by calda** [comment]
Interesting! If that fixes the issue would you mind submitting a pull request?

**Comment by snow-google** [comment]
Thank you so much @nevil for your effort to find and resolve the root cause of this rendering issue! I greatly appreciate your help with this bug! Closing for now as I expect this to resolve the issue based on the before/after videos in https://github.com/airbnb/lottie-ios/pull/1884. Thanks to the maintainers for quickly accepting this PR!
