### ISSUE TITLE
Old iOS versions have rendering issues [iOS 13]

### ISSUE THREAD

**Issue by zabolotiny** [airbnb/lottie-ios#1882]
## Which Version of Lottie are you using?

Lottie 4.0.1 commit 0ceb3ece

## Expected Behavior 
<img width="378" alt="CleanShot 2022-12-26 at 14 31 51@2x" src="https://user-images.githubusercontent.com/10601271/209545218-c6008f23-c501-4600-8e30-a0df9761725f.png">

## Actual Behavior
![wrong](https://user-images.githubusercontent.com/10601271/209545226-10940e86-49ba-4b1a-8160-63b165f910ff.jpeg)

This issue happens for iOS 13 devices when I use `LottieConfiguration(renderingEngine: .automatic)`.
When I use `LottieConfiguration(renderingEngine: .mainThread)` everything goes back to normal.
Animation works fine on iOS16 with both rendering engines.

**Comment by zabolotiny** [comment]
Same for iOS 14

**Comment by calda** [comment]
Can you share a copy of your animation json?

**Comment by zabolotiny** [comment]
[dragon.zip](https://github.com/airbnb/lottie-ios/files/10346411/dragon.zip)
This one 
@calda

**Comment by calda** [comment]
Thanks for sharing the animation json. Here's a fix: #1894
