### ISSUE TITLE
Unable to use v4.0.1 using carthage

### ISSUE THREAD

**Issue by aakarsh-sasi** [airbnb/lottie-ios#1883]
## Which Version of Lottie are you using?

Trying to use Lottie 4.0.1

## Expected Behavior 
Should build xcframework

## Actual Behavior
Fails with error
A shell task (/usr/bin/xcrun xcodebuild -project /Users/aakarsh/Desktop/xyz/Lottie.xcodeproj CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 74:
xcodebuild: error: Could not resolve package dependencies:
  Package.resolved file is corrupted or malformed; fix or delete the file to continue: unsupported schema version 2

**Comment by calda** [comment]
What command are you running that produces this error?

**Comment by aakarsh-sasi** [comment]
`./carthage.sh bootstrap lottie-ios --platform iOS --use-xcframeworks --no-use-binaries`

I'm on Xcode 13.1 (Swift 5.5) and the binary xcframework attached on GitHub is created using Swift 5.7. Hence had to add --no-use-binaries so that it is built on the system itself. It used to work on the older versions, but throws the above error now

**Comment by aakarsh-sasi** [comment]
Working fine for 3.4.3

**Comment by aakarsh-sasi** [comment]
@calda any solution to this? We can't update to the latest version

**Comment by calda** [comment]
Can you share a sample project that reproduces this issue? When I run `carthage bootstrap lottie-ios --platform iOS --use-xcframeworks --no-use-binaries` I don't get any errors.
