### ISSUE TITLE
Gradient fill are not showing in version 4.0.1

### ISSUE THREAD

**Issue by JunseokNoh** [airbnb/lottie-ios#1887]
Hi. I'm having an issue.
when I use Lottie 4.0.1 version, cannot render gradient fill 
Any help would be greatly appreciated.

## Which Version of Lottie are you using?

Lottie 4.0.1

## Expected Behavior 
<img src = "https://user-images.githubusercontent.com/40800157/209985543-339c33d8-2207-4ad1-a899-0da73c9cb160.png" width = 30% />

## Actual Behavior
<img src = "https://user-images.githubusercontent.com/40800157/209985576-564af66f-e243-4ba8-8777-39015bf66d63.png" width = 30%/>

## Animation JSON
[lottie Test.json.zip](https://github.com/airbnb/lottie-ios/files/10320717/lottie.Test.json.zip)

**Comment by calda** [comment]
Thanks for the report! Here's a fix: #1888
