### ISSUE TITLE
After Effects file for making custom viewController transitions

### ISSUE THREAD

**Issue by lukicmarko** [airbnb/lottie-ios#189]
Is there any After Effects file for making custom viewController transitions?
I have found vcTransition1.json file but I can't find After Effects file.

**Comment by buba447** [comment]
To make a transition you just need to have a layer in your after effects file that will represent your in view controller and your out view controller. These layers will be used to mask the in and out view controller. They can be solids or shapes or whatever.
When you initialize the transition you simply pass in the string name of the in and out layer as you see it in after effects.
