### ISSUE TITLE
Dynamic refresh rate issue

### ISSUE THREAD

**Issue by konstantin-tcherkashin** [airbnb/lottie-ios#1890]
Noticed on iPhone 13 Pro (with dynamic screen refresh rate), SwiftUI project, iOS 16.1. 

When nothing happens on screen for a couple of seconds, iOS lowers the refresh rate to a 10-12 hertz. Hence the animation have only 10-12fps. 

- The issue only appears when a custom animationSpeed < 1 is applied;
- If any other animation is running on screen (including notifications and other system stuff), the issue is not reproducing;
- If screen recording is enabled, the issue is not reproducing (feels like screen recording forces 60fps system-wide).

## Which Version of Lottie are you using?

Lottie 4.0.1, CoreAnimation rendering engine

## Expected Behavior 
Forcing system to sustain normal refresh rate

## Actual Behavior
Dropping frames as screen refresh rate is lowered

**Comment by calda** [comment]
Can you share a sample project that reproduces this issue? I'm unable to reproduce this issue when testing with the Lottie example app on my iPhone 14 Pro. I always see the animation playing at 60fps, according to Instruments.
