### ISSUE TITLE
Lottie 4.0.1 issue under iOS 16.2 in SwiftUI

### ISSUE THREAD

**Issue by iKK001** [airbnb/lottie-ios#1891]
## Which Version of Lottie are you using?

Lottie 4.0.1

## Expected Behavior 

On my previous Lottie version 3.4.1, everything was fine. But now with 4.0.1 my code no longer compiles.

I am using SwiftUI under iOS 16.2, XCode 14.2 and Swift 5.7.2

Here is my code of the LottieView under SwiftUI

```swift
import SwiftUI
import Lottie

struct LottieView: UIViewRepresentable {
    
    var lottieFile: String
    var loopMode: LottieLoopMode = .playOnce
    var animationView = AnimationView()
    
    func makeUIView(context: UIViewRepresentableContext<LottieView>) -> UIView {
        let view = UIView()
        
        animationView.animation = Animation.named(lottieFile)
        animationView.contentMode = .scaleAspectFill
        animationView.loopMode = loopMode
        
        animationView.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(animationView)
        
        NSLayoutConstraint.activate([
            animationView.widthAnchor.constraint(equalTo: view.widthAnchor),
            animationView.heightAnchor.constraint(equalTo: view.heightAnchor)
        ])
        
        return view
    }
    
    func updateUIView(_ uiView: UIView, context: UIViewRepresentableContext<LottieView>) {
        animationView.play()
    }
}
```

## Actual Behavior
Here a screenshot of the error messages when compiling under Lottie 4.0.1

(it seems to no longer find the AnimationView() for some reason.

What do I need to change when using Lottie 4.0.2 under iOS 16.2 in SwiftUI ??

![Screenshot 2023-01-02 at 22 58 09](https://user-images.githubusercontent.com/8404556/210280762-2a6cfe6c-7601-4484-bc1f-e9aedeedac96.png)

**Comment by iKK001** [comment]
Ah I think I've found out: When compiling under Lottie 3.5.0 I get at least the information that `AnimationView` was deprecated and it should rather be `LottieAnimationView` instead.

I tried the same under Lottie 4.0.1 and it worked. (i.e. replacing `AnimationView` with `LottieAnimationView` and also replacing `Animation` with `LottieAnimation`, as follows:

```Swift
import SwiftUI
import Lottie

struct LottieView: UIViewRepresentable {
    
    var lottieFile: String
    var loopMode: LottieLoopMode = .playOnce
    var animationView = LottieAnimationView()
    
    func makeUIView(context: UIViewRepresentableContext<LottieView>) -> UIView {
        let view = UIView()
        
        animationView.animation = LottieAnimation.named(lottieFile)
        animationView.contentMode = .scaleAspectFill
        animationView.loopMode = loopMode
        
        animationView.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(animationView)
        
        NSLayoutConstraint.activate([
            animationView.widthAnchor.constraint(equalTo: view.widthAnchor),
            animationView.heightAnchor.constraint(equalTo: view.heightAnchor)
        ])
        
        return view
    }
    
    func updateUIView(_ uiView: UIView, context: UIViewRepresentableContext<LottieView>) {
        animationView.play()
    }
}
```

**Comment by calda** [comment]
Closing this issue since you found the workaround. As you noticed we renamed `Animation` to `LottieAnimation` in 4.0 to resolve a conflict with `SwiftUI.Animation`. Unfortunately we can't add a deprecation message since something like `@deprecated typealias Animation = LottieAnimation` would still conflict with `SwiftUI.Animation`.
