### ISSUE TITLE
CoreAnimation lottie render issue

### ISSUE THREAD

**Issue by bartosz-pawelczyk** [airbnb/lottie-ios#1895]
Hello,

Recently i've updated Lottie to the newest version. Some of using animations has stop working. When i change `LottieConfiguration.shared.renderingEngine` to previous setting `.mainThread` everything is fine. 
What is wrong with this json file? Why `CoreAnimation` cant render animation?

## Which Version of Lottie are you using?

Lottie 4.0.1

## Expected Behavior 
![ezgif-3-e1fae19139](https://user-images.githubusercontent.com/90895410/210742625-f6c4b725-0159-46c3-bed2-413d8c66ccc3.gif)

## Actual Behavior
<img width="471" alt="Screenshot 2023-01-05 at 09 56 01" src="https://user-images.githubusercontent.com/90895410/210742647-57d69a27-1a66-4dad-aea4-2cce071c1bb5.png">

## Animation JSON
[lottie.json.zip](https://github.com/airbnb/lottie-ios/files/10350826/lottie.json.zip)

**Comment by bartosz-pawelczyk** [comment]
@calda

**Comment by calda** [comment]
Thanks for the report, fixed in #1899.
