### ISSUE TITLE
Text is not displayed from the after effects animation file

### ISSUE THREAD

**Issue by visinigirineeraj** [airbnb/lottie-ios#190]
Hello,

I had created an animation using text and some layers in Adobe After Effects. 
I rendered the json file from the animation project using the BodyMovin Plugin. It working fine in the google chrome, safari, morzilla.

But, unfortunately the text is not rendering  in iOS Application. Can you please help us to get this done?

Thanks in Advance
Neeraj

**Comment by xinsight** [comment]
Did you convert your text to shape vectors?

Post your after effects file and the json and maybe someone can help.

**Comment by Saik0s** [comment]
I have the same issue, lottie does not show any text on my animations, tried different fonts. The only way to show it - to convert text to the shape.

**Comment by visinigirineeraj** [comment]
But I  want to make the content as dynamic, which will change in real time.
Can you please help me in doing Animations with Dynamic Content ?

Thanks in Advance

**Comment by buba447** [comment]
Lottie doesnt currently support Text layers. This is noted in other issues.

**Comment by RishabhTayal** [comment]
Can you please point to the other issue? Is there a plan for the support? How should we go about implementing the text in After Effects?

**Comment by RishabhTayal** [comment]
I converted the text layer to shape layer in After Effects. It still doesn't show in iOS. However the same `json` file works on Android.

**Comment by brunomunizaf** [comment]
For those who are still facing this, in my team we did a workaround: We had each letter on a separate layer from illustrator. Or you can do it straight into AE but click convert to shapes from text.

**Comment by safaafrewan** [comment]
@brunomunizaf
Is there a solution other than this now?

**Comment by hungify2022** [comment]
any update ?

**Comment by brunomunizaf** [comment]
@safaafrewan not that I'm aware of, sry :(
