### ISSUE TITLE
Minor playOnce behavior difference between the Core Animation Engine and the Main Thread Engine

### ISSUE THREAD

**Issue by nevil** [airbnb/lottie-ios#1900]
## Which Version of Lottie are you using?

Latest master (03eeda861705c742af3ede84711f7c3ace1ac7e2 at this time)

## Issue

Related to #1877 

There is a small behavior difference between Main Thread Engine and Core Animation Engine.
In the sample app, play animation issue_1877.
- Play once
- Once the animation is paused, select "Play once" again.

With Main Thread engine the animation plays from frame 0.
With the Core Animation Engine the animation doesn't play. (plays 0 frames)

I guess it is a question of what is expected in this case...

**Comment by calda** [comment]
Can you share a video demo of this issue? I'm not able to reproduce it.

<img src="https://user-images.githubusercontent.com/1811727/211373814-4fae58b1-94ca-41bc-9b08-c748ee2ed7a7.gif" width=350>

**Comment by nevil** [comment]
It happens with the `issue_1877` animation. Maybe something specific about that file...


https://user-images.githubusercontent.com/36905/211439010-ab71e42f-2a77-480a-aac4-8c78f02af83c.mp4

**Comment by nevil** [comment]
@calda 
I didn't try this with latest master 🙇 .
This bug is actually fixed with the fix from #1901 

Closing as fixed. Thank you!
