### ISSUE TITLE
Minor AnimatedSwitch behavior difference between the Core Animation Engine and the Main Thread Engine

### ISSUE THREAD

**Issue by nevil** [airbnb/lottie-ios#1901]
## Which Version of Lottie are you using?

Latest master (03eeda861705c742af3ede84711f7c3ace1ac7e2 at this time)

## Description
Relates to #1877 

Can be reproduced using the sample app.
- Set the engine to Main Thread Engine.
- Open Controls Demo
--> Observe that the `Issue #1877` switch is animating.

- Set the engine to Core Animation Engine.
- Open Controls Demo
--> Observe that the `Issue #1877` switch is set to the final frame immediately.

I guess it is a question of how closely the Core Animation Engine should copy Main Thread Engine's behavior...

**Comment by calda** [comment]
Thanks for the report! To me it seems like the behavior of the Core Animation engine is more correct here. I'd rather not change the behavior of the Main Thread engine, to preserve the existing functionality, so I think we can leave this as-is.

**Comment by calda** [comment]
This is actually an issue with `LottieAnimationView` and not just `AnimatedSwitch` -- we got a report of the same issue in https://github.com/airbnb/lottie-ios/discussions/1907. I'll go ahead and fix this.
