### ISSUE TITLE
СoreAnimation resets currentProgress to zero

### ISSUE THREAD

**Issue by VAKutuzov** [airbnb/lottie-ios#1904]
Lottie 4.0.1

## Expected Behavior 
On previous versions and on 4.0.1( with renderingEngine: .mainThread) works fine

## Actual Behavior
With .coreAnimation or .automatic some animations depending on ScrollView or values of DatePicker are jumping to zero position, when should they start from the previous position

**Comment by calda** [comment]
I believe this was fixed by #1897, which will be included in the next release.

**Comment by VAKutuzov** [comment]
Great, TY
