### ISSUE TITLE
Updating several colors can be long

### ISSUE THREAD

**Issue by valentinperignon** [airbnb/lottie-ios#1905]
## Which Version of Lottie are you using?

Lottie 4.0.1

## Expected Behavior 
Changing several colors should be instant.

## Actual Behavior

https://user-images.githubusercontent.com/25110022/211365304-3e396487-fb5c-4507-86c6-6ab03e4896ef.mp4

We change the colors thanks to `setValueProvider` (https://github.com/Infomaniak/ios-mail/pull/463/files#diff-d7aad4802256729fcd8c50012bb3f966a41b0f0aefd05094442f6c4994523c59R26), but as we are updating about 50 keypaths, it takes some time.

Is there a method to makes this quicker ?

## Animation JSON
https://github.com/Infomaniak/ios-mail/blob/master/MailResources/illu_1.json

**Comment by calda** [comment]
Can you share a sample project that reproduces this issue?

**Comment by valentinperignon** [comment]
[LottieAnimation.zip](https://github.com/airbnb/lottie-ios/files/10382554/LottieAnimation.zip)
Sure. Here is a small project.
You can notice that the UI freezes for a few seconds when you press the button, while the colors are changed
