### ISSUE TITLE
Renderer parity issue: image layers placement

### ISSUE THREAD

**Issue by snow-google** [airbnb/lottie-ios#1913]
## Which Version of Lottie are you using?

Lottie 4.0.1 (HEAD)

## Issue
I am not sure which behavior (if either) is the correct one. Below are two screenshots, one from each renderer. These screenshots show an image that was provided for an animation that does not take up the entirety of the animation view. For the main thread renderer the image is centered whereas for the Core Animation renderer renders the image layer anchored to the origin. I tried updating the anchor point of the image layer in the /Sources/Private/CoreAnimation/Layers/ImageLayer.swift ImageLayer::layout API as a way of centering it, but changing the anchor point causes the image to not show at all. This is consistent with the code and comments in: Sources/Private/CoreAnimation/Extensions/CALayer+fillBounds.swift.

What is the correct behavior here, and how can we achieve it consistently across renderers?

## Main Thread
![Main Thread HEAD](https://user-images.githubusercontent.com/121244810/212169646-52400050-0650-4b1a-9bfe-445759a3b5e3.png)

## Core Animation
![Core Animation HEAD](https://user-images.githubusercontent.com/121244810/212169672-98f31b8b-c91b-4016-a41b-841b6f3a3b28.png)

## Animation JSON
I think this would happen with any image that does not take up a full animation view.

**Comment by calda** [comment]
Can you share a copy of an animation json that reproduces this issue?

**Comment by calda** [comment]
> What is the correct behavior here

I typically use the Lottie web implementation as a source of truth for how an animation is supposed to render. How does the animation look when you preview it on lottiefiles.com?

**Comment by snow-google** [comment]
That's a good tip. Thanks!

Let me see if I can track down the actual animation. I only have access to a screenshot of it right now.

**Comment by snow-google** [comment]
The animation JSON is below. It looks like all it does is render an image and rotate it clockwise. The image itself is missing, but I expect you could insert any image of that size. The web player shows the image in the middle of the view which would match the Main Thread renderer's behavior.

{"v":"5.9.0","fr":24,"ip":0,"op":48,"w":512,"h":512,"nm":"Comp 1","ddd":0,"assets":[{"id":"image_0","w":256,"h":256,"u":"images/","p":"img_0.png","e":0}],"layers":[{"ddd":0,"ind":1,"ty":2,"nm":"photos_logo.png","cl":"png","refId":"image_0","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":0,"s":[0]},{"t":48,"s":[360]}],"ix":10},"p":{"a":0,"k":[256,256,0],"ix":2,"l":2},"a":{"a":0,"k":[128,128,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"ip":0,"op":48,"st":0,"bm":0},{"ddd":0,"ind":2,"ty":1,"nm":"Pale Red Solid 1","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[256,256,0],"ix":2,"l":2},"a":{"a":0,"k":[256,256,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"sw":512,"sh":512,"sc":"#f2e7e6","ip":0,"op":48,"st":0,"bm":0}],"markers":[]}

**Comment by csmulhern** [comment]
Here's a copy of the animation [JSON](https://github.com/airbnb/lottie-ios/files/10406946/embedded.txt) (using a TXT extension, as JSON cannot be attached apparently) that has the image data embedded as base64 encoded data. Let me know if that's helpful in reproducing the issue.

**Comment by calda** [comment]
Thanks! Will find a chance to take a look

**Comment by calda** [comment]
I can't reproduce this issue with either of the sample animation json files here. Could you share a sample project that reproduces this issue?

<img src="https://user-images.githubusercontent.com/1811727/212698253-06178593-169e-4f23-97c1-421d5d8283a5.png" width=300> <img src="https://user-images.githubusercontent.com/1811727/212698269-82c16cd8-bce0-439a-86d8-dee918621429.png" width=300>

**Comment by csmulhern** [comment]
Just to comment for posterity: the issue here is actually with how we were snapshotting this view for testing, which was not compatible with the Core Animation rendering engine. For more information, see: https://github.com/airbnb/lottie-ios/discussions/1769#discussioncomment-3860672.
