### ISSUE TITLE
What happened to Animation.named

### ISSUE THREAD

**Issue by chitgoks** [airbnb/lottie-ios#1914]
## Which Version of Lottie are you using?

Lottie 4.0.1

Animation.named doesnt exist anymore. The documentation still instructs to use .named(lottieFile)

**Comment by calda** [comment]
`Animation` was renamed to `LottieAnimation`, so this would be `LottieAnimation.named(...)` now.

**Comment by chitgoks** [comment]
thanks. you are right.

**Comment by Baza207** [comment]
I think the documentation might need to get updated then @calda https://airbnb.io/lottie/#/ios?id=animation-model
