### ISSUE TITLE
New rendering engine ignores Skew parameter

### ISSUE THREAD

**Issue by Ogerets** [airbnb/lottie-ios#1915]
## Which Version of Lottie are you using?

Lottie 4.0.1

## Expected Behavior 

https://user-images.githubusercontent.com/20406383/212380586-dbc1be60-75e7-40e5-8a88-f1e82b1af8e9.MP4

## Actual Behavior

https://user-images.githubusercontent.com/20406383/212380763-f8e5da23-3053-4e47-a01b-be9ec19da1e5.MP4

## Animation JSON

[AnimationWithSkew.json.zip](https://github.com/airbnb/lottie-ios/files/10413865/AnimationWithSkew.json.zip)

**Comment by arsfeshchenko** [comment]
I have the same problem with the Skew function 👍

**Comment by oleg13solomakha** [comment]
Ah, it appears we share a common conundrum with the Skew function.

**Comment by calda** [comment]
Thanks for the report and sample animation json. Fixed in #1917.
