### ISSUE TITLE
Unable to add lottie-spm framework to a target

### ISSUE THREAD

**Issue by aureliencolas** [airbnb/lottie-ios#1925]
When adding a package dependency to the project, Xcode allows to select a target to add the framework to. The Lottie package is then properly added to this target. However, since I have multiple targets using Lottie, I have to manually add the Lottie framework to the other targets. 

**The issue**: the Lottie package is not available in the "Frameworks and libraries to add" popup.

Actually, if the Lottie package is removed from the original target (the one selected when adding the package dependency), it cannot be added again, for the same reason.

When using the Lottie-ios repository, the Lottie package is available when adding packages to a target.

## Which Version of Lottie are you using?

Lottie-spm 4.1.0

## Expected Behavior 
The Lottie package can be added to a target.

## Actual Behavior
The Lottie package cannot be added to a target.
![image](https://user-images.githubusercontent.com/82930766/213656412-b9accd1c-ced5-423f-9bcc-2bb18d0ab896.png)

**Comment by calda** [comment]
Thanks for the report, here's a fix: https://github.com/airbnb/lottie-spm/pull/5. We'll release 4.1.1 with this fix later today.
