### ISSUE TITLE
Add support for Fill Effect

### ISSUE THREAD

**Issue by im9uri** [airbnb/lottie-ios#193]
First, thank you for this opening up this library!

I was testing several animations, when I came across this warning
[LOTLayer _mapFromJSON:withCompBounds:withFramerate:withAssetGroup:]: Warning: fill effect not supported

Looking at the code, it seems that when initializing LOTLayer, elements starting with "ef" issue the warning above.

However in the README it's stated that fill effect is supported.

[favorite_on.json.zip](https://github.com/airbnb/lottie-ios/files/872737/favorite_on.json.zip)

Any help would be greatly appreciated.

**Comment by therealsalih** [comment]
Hi @im9uri no Effects are supported in Lottie. I'm assuming you're trying to use this fill

![screen shot 2017-03-27 at 9 49 45 am](https://cloud.githubusercontent.com/assets/5893643/24367771/c0ccb5d0-12d2-11e7-97f9-0f5e0d997e3f.png)

The fill the README is speaking of, is the fill within a shape layer

![screen shot 2017-03-27 at 9 49 36 am](https://cloud.githubusercontent.com/assets/5893643/24367776/c55c01fa-12d2-11e7-8dcf-5f3113e4ad6e.png)

**Comment by im9uri** [comment]
thanks for the help @therealsalih . Changing fill effect with fill within a shape layer did the necessary trick.
