### ISSUE TITLE
LottieAnimationView taking too much time to load the lottie file

### ISSUE THREAD

**Issue by Siddhant2155** [airbnb/lottie-ios#1936]
The Lottie is taking a few seconds to load, freezing the app UI.

## Which Version of Lottie are you using?

Lottie 4.0.1

**Comment by calda** [comment]
Can you share a copy of your animation json?

**Comment by Siddhant2155** [comment]
Hi @calda 

Please find the Lottie attached. 

[search_loader.json.zip](https://github.com/airbnb/lottie-ios/files/10553401/search_loader.json.zip)

**Comment by calda** [comment]
Thanks for the report. This doesn't seem to be a bug or specific performance issue with Lottie -- this is just a very, very large animation. It's 1.7MB and has thousands of layers, which is much larger than the animations I typically see. Both the Core Animation and Main Thread render engines take about 100ms to set up this animation when I test it locally, which isn't surprising considering they have to build and configure thousands of `CALayer`s (one for each shape). To improve performance of this animation I'd suggest reducing the number of individual group / shapes.

**Comment by calda** [comment]
When I test this locally I see the Core Animation and Main Thread rendering engines taking about the same amount of time to get set up. If you're seeing the Core Animation rendering engine take noticeably longer than the Main Thread rendering engine, you could configure your `LottieAnimationView` to use that engine instead by passing in `configuration: LottieConfiguration(renderingEngine: .mainThread)`.
