### ISSUE TITLE
lottie-spm in multiple local swift packages causing issues

### ISSUE THREAD

**Issue by woutergoossens** [airbnb/lottie-ios#1938]
## Which Version of Lottie are you using?

Lottie 4.1.2 (SPM lottie-spm)

## Expected Behavior 
We are using multiple local swift packages in our project (with several external dependencies).
When we use the swift package "https://github.com/airbnb/lottie-ios.git" all is working fine but when we switch to lottie-spm this causes issues that LottieAnimationView is not found for example.

Lottie is used in 2 packages:

PackageA (Design package):
target dependency --> 
`.product(name: "Lottie", package: "lottie-spm")`
All files are building fine.

PackageB (Presentation package):
has a dependency with local PackageA (and I don't need to define Lottie anymore as dependency as it's fetched via PackageA). Lottie is available/visible as Package Dependency on the left panel of Xcode. 
```
 dependencies: [
        .package(path: "../PackageA"),
```

BUT then we get several errors that LottieAnimationView is not found in scope. Also complaining on files from the PackageA
<img width="449" alt="Screenshot 2023-01-24 at 21 46 26" src="https://user-images.githubusercontent.com/355048/214512773-0ce21cba-b33b-41eb-bcf5-a721629eb77f.png">

I tried to reproduce the issues on a new test project but didn't succeed. 
Any idea what could cause this issue?

**Comment by calda** [comment]
> I tried to reproduce the issues on a new test project but didn't succeed.

Does this mean you created a sample project with the same dependency structure as your main project, but weren't able to reproduce this build issue (e.g. it was able to build and import Lottie as expected)?

I'm not sure what would cause this. If you're able to create / share a project that reproduces this issue I'd be happy to investigate. Otherwise you could continue using lottie-ios instead of lottie-spm as a workaround.

**Comment by calda** [comment]
> PackageB (Presentation package):
has a dependency with local PackageA (and I don't need to define Lottie anymore as dependency as it's fetched via PackageA)

Have you tried adding lottie-spm as a dependency of PackageB anyway?

**Comment by aadeshmindtickle** [comment]
Hello, any solution on this ? as I am facing exact same issue.
