### ISSUE TITLE
Expose textProvider in CompatibleAnimationView to support dynamic text

### ISSUE THREAD

**Issue by ciss1995** [airbnb/lottie-ios#1943]
Opening an issue to support textProvider in CompatibleAnimationView for when Lottie is used in objC. 

As a suggestion from looking at the code, we could have a wrapper around AnimationTextProvider which initializes with a dictionary e.g:

```
@objc
public final class CompatibleAnimationTextProvider: NSObject {
 @objc
 public init(values: [String: String])
 {
   self.values = values
   super.init()
 }
 internal var textProvider: AnimationTextProvider? {
   return DictionaryTextProvider(self.values);
 }
 private let values: [String: String]
}
```

and then expose it to textProvider e.g:

```
@objc
 public var compatibleAnimationTextProvider: CompatibleAnimationTextProvider? {
   didSet {
     animationView.textProvider = compatibleAnimationTextProvider?.textProvider
   }
 }
```

## Which Version of Lottie are you using?

Lottie 4.0.1

## Expected Behavior 
Be able to dynamically change texts when using Lottie in objC.

## Actual Behavior
When using Lottie in objC through the wrapper CompatibleAnimationView, textProvider isn't exposed to dynamically change texts.

**Comment by calda** [comment]
Are you interested in making those suggested changes in a pull request? Seems like a good approach to me
