### ISSUE TITLE
dotLottie load fail

### ISSUE THREAD

**Issue by RayFor24** [airbnb/lottie-ios#1945]
## Which Version of Lottie are you using?

Lottie 4.1.2

my dotlottie File can play success in https://app.lottiefiles.com/preview?utm_medium=web&utm_source=navigation-preview&fileUrl=

but when I use in my app like this:

DotLottieFile.named("testdot") { result in
                    switch result {
                    case .success(let dotLottieFile):
                        self.tipsAniView = LottieAnimationView(dotLottie: dotLottieFile)
                        self.tipsAniView.loopMode = .loop
                        self.tipsAniView.play()
                    case .failure(let error):
                        print(error)
                    }
                }

error: failure	Foundation.Data.CompressionError	corruptedData
Error when decoding lottie "testdot": corruptedData

You can unzip  dotLottieFile.zip. get dotLottie

## Animation JSON

[dotLottieFile.zip](https://github.com/airbnb/lottie-ios/files/10683228/dotLottieFile.zip)

**Comment by calda** [comment]
Thanks for the report! Fixed in #1978
