### ISSUE TITLE
Automatic mode not working for some animations with unsupported functionality

### ISSUE THREAD

**Issue by JoeSzymanski** [airbnb/lottie-ios#1946]
We started testing Lottie v4.1.2 to determine if it would be safe to update, and have run into a strange issue with a subset of animations.

When running the animation in mainThread mode, the animation works correctly. When running in the animation in automatic mode, we get the warning "The Core Animation rendering engine doesn't currently support applying trims to filled shapes (only stroked shapes)" which is expected at the moment. However, in automatic mode, the animation does not display at all, even though the code appears to be attempting to fall back to the mainThread rendering engine.

We have seen the fall back to mainThread rendering enginer work correctly for other animations, though. The common thread among animations that don't work is the listed feature around trim paths and filled shapes.

One example animation is attached.

## Which Version of Lottie are you using?

Lottie 4.1.2

## Expected Behavior 
When using the automatic rendering engine mode and the animation has an unsupported feature, it should fall back to the mainThread rendering mode and properly display the animation.

## Actual Behavior
The unsupported feature is properly logged and the code appears to attempt to fall back to the mainThread rendering mode, but the animation never actually plays.

## Animation JSON
[fireworks2018.json.zip](https://github.com/airbnb/lottie-ios/files/10689818/fireworks2018.json.zip)

**Comment by calda** [comment]
This animation behaves correctly when I test it locally -- `RenderingEngineOption.automatic` falls back to the main thread rendering engine. 

If you are still experiencing this problem, could you re-open this issue and include a sample project that demonstrates it? Thanks!

<img src="https://user-images.githubusercontent.com/1811727/222850368-e5857af5-a04b-4b69-8549-d95e3a38f501.gif" width=300>

**Comment by JoeSzymanski** [comment]
I was able to create a small project that recreated this bug trivially. 

[TestingLottie.zip](https://github.com/airbnb/lottie-ios/files/10898878/TestingLottie.zip)

In ViewController.viewDidLoad, you can change the rendering mode between automatic and mainThread and see that automatic raises warnings, but does not play the animation, while mainThread plays the animation.

I am currently using Xcode 14.1 running on an iPhone 16.1 simulator, though I'm not sure if these setting matter.

**Comment by JoeSzymanski** [comment]
I'm not sure if there's a way to repoen this issue, or if I should just create a new issue with the same content.

**Comment by JoeSzymanski** [comment]
I created  new issue with the same information since I didn't see a way to reopen this issue. It's #1984.
