### ISSUE TITLE
Animation Loops Inappropriately When Using Core Animation Renderer

### ISSUE THREAD

**Issue by SeanMcTex** [airbnb/lottie-ios#1947]
## Which Version of Lottie are you using?

Lottie 4.1.2

We upgraded from Lottie 3.5.0 to Lottie 4.1.2 and found that using the new CA renderer causes our animations to loop inappropriately. Rather than having the badge animate in and rest, the animation immediately loops back to the beginning as soon as the badge is displayed.

## Expected Behavior 

Animation should play until badge appears and then remain. This is the behavior we see with the `.mainThread` renderer under 4.1.2, so can use that as a workaround, but would love to get the efficiencies of the CA renderer.

![image](https://user-images.githubusercontent.com/1564380/217653112-592734a3-c4ca-4119-aba2-1ea8ff211877.png)

## Actual Behavior

Animation loops immediately:

https://user-images.githubusercontent.com/1564380/217652717-3c081465-7b95-47b9-be34-382a1535b303.mov

## Animation JSON

(Github wouldn't allow me to upload the JSON directly, so here's a ZIP!)
[notification_bell_99_plus.json.zip](https://github.com/airbnb/lottie-ios/files/10689986/notification_bell_99_plus.json.zip)

**Comment by calda** [comment]
Could you share a sample project that demonstrates this issue? I'm unable to reproduce it when testing locally on the latest master branch

<img src="https://user-images.githubusercontent.com/1811727/222857924-88c4ae57-4a1f-4e4b-80af-c42737be171c.gif" width=300>
