### ISSUE TITLE
Facing "Multiple binaries share the same codesign path..." on Archiving MacOS App

### ISSUE THREAD

**Issue by asad-ather** [airbnb/lottie-ios#1948]
## Which Version of Lottie are you using?

Lottie 4.1.2

## Expected Behavior 
MacOS app archive integrated with lottie-spm should be able to be validated and distributed.

## Actual Behavior
Getting an error on trying to distribute the archive

<img width="757" alt="Screenshot 2023-02-08 at 11 45 49 AM" src="https://user-images.githubusercontent.com/26603745/217994378-9e1cf93e-0dd7-4e6c-96b5-2aa6935b951d.png">

## Animation JSON

N/A

**Comment by calda** [comment]
Thanks for the report. I'm able to reproduce this locally in a sample project.

**Comment by asad-ather** [comment]
> Thanks for the report. I'm able to reproduce this locally in a sample project.

Thanks @calda for the quick triage, I am not sure if its the right fix, but here is how another library fixed this/similar issue: https://github.com/cossacklabs/themis/pull/944

Hoping it can give some clues for a quick fix...

**Comment by calda** [comment]
Wow, very helpful! I'll try that and see if it helps. Thanks :)
