### ISSUE TITLE
CoreAnimation rendering engine changed the behavior of Text providers

### ISSUE THREAD

**Issue by JoeSzymanski** [airbnb/lottie-ios#1949]
In testing the new verison of Lottie, I ran into an issue where custom text providers were not working in automatic mode but were working in mainThread mode.

By adding a log message in DictionaryTextProvider.textFor(keypathName: String, sourceText: String), I noticed the following:

Automatic mode:
JRS - custom text for keypathName ENVELOPE-FRONT.sender_username, sourceText: sender_username
JRS - custom text for keypathName ENVELOPE-FRONT.From, sourceText: From:
JRS - custom text for keypathName ENVELOPE-BACK-TEXTBOX.LETTER-TEXTBOX.sender_username, sourceText: sender_username
JRS - custom text for keypathName ENVELOPE-BACK-TEXTBOX.LETTER-TEXTBOX.custom_text, sourceText: custom_text

MainThread mode:
JRS - custom text for keypathName sender_username, sourceText: sender_username
JRS - custom text for keypathName From, sourceText: From:
JRS - custom text for keypathName custom_text, sourceText: custom_text
JRS - custom text for keypathName sender_username, sourceText: sender_username
JRS - custom text for keypathName From, sourceText: From:
JRS - custom text for keypathName custom_text, sourceText: custom_text
JRS - custom text for keypathName sender_username, sourceText: sender_username

It looks like the new CoreAnimation enginer is using a different definition for the keypathName parameter, which means it's not possible to safely support both modes.

## Which Version of Lottie are you using?

Lottie 4.1.2

## Animation JSON
Working to confirm that I can share the JSON file. I will update once I have approval.

**Comment by calda** [comment]
Yeah, the two rendering engines have different `AnimationKeypath` implementations which are different in some edge cases that we aren't handling correctly yet. Please share your animation json when you're able to!

**Comment by JoeSzymanski** [comment]
The json for the animation is attached.

[love_letter.json.zip](https://github.com/airbnb/lottie-ios/files/10710730/love_letter.json.zip)
