### ISSUE TITLE
Compatibility issues with RenderingEngineOption.automatic 

### ISSUE THREAD

**Issue by IgorRosocha** [airbnb/lottie-ios#1950]
## Context
Hello, I have just upgraded Lottie from 3.5.0 to 4.1.2, and my animation doesn't behave correctly in `.playOnce` loop mode, once it is played immediately after pushing the `View`. Animation glitches half-way and animates again from the start. After changing `renderingEngine` to `.mainThread`, everything seems to work just fine.

I am rendering animation in SwiftUI, using a convenience wrapper - see https://github.com/LukasHromadnik/Lottie-SwiftUI.

## Which Version of Lottie are you using?

Lottie 4.1.2

## Expected Behavior 

Animation should play only once.

## Actual Behavior

Animation glitches half-way and animates again from the start.

https://user-images.githubusercontent.com/23634980/218518381-4bc50403-8b0c-4ee4-98bc-32ce8494cbed.mov

## Animation JSON

`
{"v":"4.8.0","meta":{"g":"LottieFiles AE 3.1.1","a":"","k":"","d":"","tc":""},"fr":60,"ip":0,"op":40,"w":300,"h":300,"nm":"checkmark-circle 2","ddd":0,"assets":[],"layers":[{"ddd":0,"ind":2,"ty":4,"nm":"Shape Layer 1","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[150,150,0],"ix":2},"a":{"a":0,"k":[0,0,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0.469,-75.25],[58.969,0.5],[0.469,60.75],[0,0],[0,0],[0,0]],"o":[[45.969,-0.5],[0.469,64],[-61.529,-0.522],[3.469,-66],[0,0],[0,0],[0,0]],"v":[[-0.469,-110],[109.531,0],[-0.469,110],[-110.469,0],[-45.031,3.375],[-17.031,30.625],[43.031,-29.812]],"c":false},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"st","c":{"a":0,"k":[0.376470595598,0.607843160629,0.384313732386,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":14.06,"ix":5},"lc":2,"lj":2,"bm":0,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Shape 1","np":3,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false},{"ty":"tm","s":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":1,"s":[0]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":29,"s":[76.259]},{"t":39,"s":[83]}],"ix":1},"e":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":1,"s":[8]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":29,"s":[82.034]},{"t":39,"s":[100]}],"ix":2},"o":{"a":0,"k":0,"ix":3},"m":1,"ix":2,"nm":"Trim Paths 1","mn":"ADBE Vector Filter - Trim","hd":false}],"ip":-19,"op":281,"st":-19,"bm":0},{"ddd":0,"ind":4,"ty":4,"nm":"Oval","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[150,150,0],"ix":2},"a":{"a":0,"k":[0,0,0],"ix":1},"s":{"a":0,"k":[98,98,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"d":1,"ty":"el","s":{"a":0,"k":[225.094,225.094],"ix":2},"p":{"a":0,"k":[0,0],"ix":3},"nm":"Ellipse Path 1","mn":"ADBE Vector Shape - Ellipse","hd":false},{"ty":"st","c":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":16,"s":[0.921568632126,0.929411768913,0.92549020052,1]},{"t":24,"s":[0.376470595598,0.607843160629,0.384313732386,1]}],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":14.062,"ix":5},"lc":2,"lj":2,"bm":0,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Oval","np":2,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false},{"ty":"tm","s":{"a":0,"k":0,"ix":1},"e":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":0,"s":[0]},{"t":35,"s":[100]}],"ix":2},"o":{"a":0,"k":0,"ix":3},"m":1,"ix":2,"nm":"Trim Paths 1","mn":"ADBE Vector Filter - Trim","hd":false}],"ip":-19,"op":281,"st":-19,"bm":0}],"markers":[]}
`

**Comment by calda** [comment]
This animation plays correctly when I test it locally. Perhaps this is an issue with the SwiftUI wrapper implementation.

<img src="https://user-images.githubusercontent.com/1811727/222851246-c7d00770-cd41-4617-9c29-b468aa28a804.gif" width=300>
