### ISSUE TITLE
Animation not rendering correctly since 4.x upgrade

### ISSUE THREAD

**Issue by benlacey** [airbnb/lottie-ios#1952]
Since updating to Lottie iOS 4.x I've noticed one of our animations appears slightly corrupted - you can see the 'waves' at the animation endpoint appear to thin strangely towards the right hand side.  This does not appear when previewed on lottiefiles.com

Using your example app I've been able to confirm that the same animation renders correctly on 3.5.0, but incorrectly on 4.x, and does not render correctly when using either rendering engine on 4.x

## Which Version of Lottie are you using?

Lottie 4.1.2

## Actual & Expected Behavior 

![lottie_connecting](https://user-images.githubusercontent.com/5020620/218805427-da9faea0-2460-45b0-b6c3-601a4a7b8b76.png)

## Animation JSON

Animation uploaded here: [connecting_product.lottie.zip](https://github.com/airbnb/lottie-ios/files/10862747/connecting_product.lottie.zip)

Any thoughts on what could be causing the wonky display of these waves, or whether there's a workaround we can pursue?

I wonder if there's a feature our animator used that was fine on 3.5 but not on 4.x?

**Comment by calda** [comment]
Can you share a sample project that reproduces this issue? When I test it locally with the latest master branch the animation appears identical between the Core Animation and Main Thread rendering engines.

| Core Animation | Main Thread |
| ---- | ---- |
| ![Simulator Screen Shot - iPhone 14 Pro - 2023-03-03 at 16 10 58](https://user-images.githubusercontent.com/1811727/222858172-c4d73951-4d4e-4476-ae08-dd08e59b2c07.png) | ![Simulator Screen Shot - iPhone 14 Pro - 2023-03-03 at 16 11 05](https://user-images.githubusercontent.com/1811727/222858176-d579e42e-9269-4c87-9647-db553cdb0ada.png) |
