### ISSUE TITLE
Crash on ShapeRenderLayer.init(renderer:)  EXC_BAD_ACCESS (KERN_INVALID_ADDRESS)

### ISSUE THREAD

**Issue by sh0rt2020** [airbnb/lottie-ios#1961]
All online users crashed on iPadOS 12.x.x.  And sometimes is OK.

## Which Version of Lottie are you using?

Lottie 3.5.0

## Actual Behavior

![Screenshot 2023-02-16 at 14 03 13](https://user-images.githubusercontent.com/4645745/219281807-c82b10ee-91c4-4a83-86e4-a94f722a1e2b.png)

**Comment by sh0rt2020** [comment]
This is the animation json.
https://gist.github.com/sh0rt2020/e1e435f9f4fd7c5a4858f8e26a2879c2

**Comment by calda** [comment]
Can you share a sample project that reproduces this issue, and/or test on Lottie 4.0+? I don't experience a crash when testing this on Lottie 4.1.3.

**Comment by sh0rt2020** [comment]
Thank you for your reply.
But I can't reproduce this crash on my device too. Currently only online users encountered this crash, and I will update Lottie in next version to see if there is still this crash.

**Comment by sh0rt2020** [comment]
@calda I am curious, do you have a checklist for animation json file for avoiding crash?
