### ISSUE TITLE
Lottie's `Bundle+Module.swift` conflicts with the Swift-generated `Bundle.module`

### ISSUE THREAD

**Issue by bsrz** [airbnb/lottie-ios#1962]
## Which Version of Lottie are you using?

Lottie 3.5.0

## Expected Behavior 

Swift's generated `Bundle.module` should be accessible even when using Lottie in a Swift Package.

## Actual Behavior

When using creating your own Swift Package...
  ... and your module has resources
  ... and you need to refer to the Swift-generated `Bundle.module`
  ... and one of your other modules uses Lottie
  ... Lottie's `Bundle+Module.swift` conflicts with the Swift-generated `Bundle.module`
  ... and prevents your code from compiling

## Screenshots

![CleanShot000115@2x](https://user-images.githubusercontent.com/1077441/219732407-bd756d68-eea8-4c3c-b99a-7df69bd46a73.png)

**Comment by calda** [comment]
Would you be able to make a pull request that renames this to something else? If it's just internal we can rename it to whatever we want.

**Comment by bsrz** [comment]
@calda see #1965 I think that's all that's needed, all tests passed locally
