### ISSUE TITLE
2 Duplicate Symbol For Architecture x86_64

### ISSUE THREAD

**Issue by jasperpogi02** [airbnb/lottie-ios#197]
I always get this error whenever I add a library in Podfile then pod install it

![screen shot 2017-03-29 at 4 54 57 pm](https://cloud.githubusercontent.com/assets/5517897/24446639/d2f6f840-14a0-11e7-87c4-172b7a953469.png)

I use Xcode 8.3 | Swift 3 | Cocoapods
and this is my podFile

target 'flyakeed' do
  
    pod 'lottie-ios'

    pod 'FSCalendar'

    pod 'Alamofire', '~> 4.3'
      
    pod 'SwiftyJSON'

    pod 'NHRangeSlider', '~> 0.2'

    pod 'MGSwipeTableCell'

    use_frameworks!

end

**Comment by jasperpogi02** [comment]
Right now I fixed this issue by commenting out the pod 'lottie-ios' and pod install and putting it back again then pod install :)

But I don't want to encounter this issue again when I add new pods. hope you can help me with this :)

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
