### ISSUE TITLE
Runtime compilation failed

### ISSUE THREAD

**Issue by MrDcm** [airbnb/lottie-ios#1974]
Xcode version is 12.5.1,
Multiple files reported errors during compilation. What is the reason?
![WechatIMG55](https://user-images.githubusercontent.com/16145775/221117717-205fa5a1-0fae-410f-bc1d-c1498a793cce.jpeg)
![WechatIMG56](https://user-images.githubusercontent.com/16145775/221117976-48db1bee-69df-4b1f-815e-23908dff77e9.jpeg)

**Comment by calda** [comment]
Xcode 12.5.1 includes Swift 5.4.2. As of Lottie 4.0, minimum-supported Swift version is now Swift 5.5 (in Xcode 13.0+). You'd need to either update to Xcode 13.0+, or use Lottie 3.5 instead.
