### ISSUE TITLE
Not building after update the pod

### ISSUE THREAD

**Issue by fbarraganperchwell** [airbnb/lottie-ios#1975]
I'm getting this following errors: 

![Screenshot 2023-02-27 at 14 39 43](https://user-images.githubusercontent.com/115487825/221680537-50cd68a4-e3ab-4c8c-9def-979dedbcbd66.png)

lottie version 4.1.3 with Xcode 14.2, MacOs Ventura 13.2.1 and M1 with Cocoapods

**Comment by calda** [comment]
Have you tried to clean and/or delete derived data and then rebuild? If this still happens after doing a clean build, can you share a sample project that reproduces this issue?
