### ISSUE TITLE
Automatic mode not working for some animations with unsupported functionality

### ISSUE THREAD

**Issue by JoeSzymanski** [airbnb/lottie-ios#1984]
This is the issue from #1946 reopened, as I didn't see any way to reopen the existing issue.

We started testing Lottie v4.1.2 to determine if it would be safe to update, and have run into a strange issue with a subset of animations.

When running the animation in mainThread mode, the animation works correctly. When running in the animation in automatic mode, we get the warning "The Core Animation rendering engine doesn't currently support applying trims to filled shapes (only stroked shapes)" which is expected at the moment. However, in automatic mode, the animation does not display at all, even though the code appears to be attempting to fall back to the mainThread rendering engine.

We have seen the fall back to mainThread rendering enginer work correctly for other animations, though. The common thread among animations that don't work is the listed feature around trim paths and filled shapes.

One example animation is attached.

## Which Version of Lottie are you using?

Lottie 4.1.2

## Expected Behavior 
When using the automatic rendering engine mode and the animation has an unsupported feature, it should fall back to the mainThread rendering mode and properly display the animation.

## Actual Behavior
The unsupported feature is properly logged and the code appears to attempt to fall back to the mainThread rendering mode, but the animation never actually plays.

## Animation JSON
[fireworks2018.json.zip](https://github.com/airbnb/lottie-ios/files/10913612/fireworks2018.json.zip)

Here is a small project that replciates this issue:
[TestingLottie.zip](https://github.com/airbnb/lottie-ios/files/10913614/TestingLottie.zip)

**Comment by calda** [comment]
An immediate workaround would be to add `guard finished else { return }` to your completion handler. That has the same effect as the change in #1994 (ignoring the extra unexpected completion handler call).
