### ISSUE TITLE
Critical Severity Risk - JSON Injection

### ISSUE THREAD

**Issue by arunkumar-g3690** [airbnb/lottie-ios#1985]
## Summary
On line 159 of LottieAnimationHelpers.swift, the method from:data:strategy:() writes unvalidated input into JSON. This call could allow an attacker to inject arbitrary elements or attributes into the JSON entity.The method writes unvalidated input into JSON. This call could allow an attacker to inject arbitrary elements or attributes into the JSON entity.

## Which Version of Lottie are you using?

Lottie 4.1.3

## Actual Issue
JSON injection occurs when:

1. Data enters a program from an untrusted source.
In this case, the data enters at lambda { (Data?, URLResponse?, Error?) -&gt; Void }() in LottieAnimationHelpers.swift on line 205.

2. The data is written to a JSON stream.
In this case, the JSON is written by jsonObject:with:options:() in LottieAnimationHelpers.swift on line 159.

Applications typically use JSON to store data or send messages. When used to store data, JSON is often treated like cached data and may potentially contain sensitive information. When used to send messages, JSON is often used in conjunction with a RESTful service and can be used to transmit sensitive information such as authentication credentials.

The semantics of JSON documents and messages can be altered if an application constructs JSON from unvalidated input. In a relatively benign case, an attacker may be able to insert extraneous elements that cause an application to throw an exception while parsing a JSON document or request. In a more serious case, such as ones that involves JSON injection, an attacker may be able to insert extraneous elements that allow for the predictable manipulation of business critical values within a JSON document or request. In some cases, JSON injection can lead to cross-site scripting or dynamic code evaluation.

## Expected Fix 
When writing user supplied data to JSON, follow these guidelines:
1. Do not create JSON attributes with names that are derived from user input.
2. Ensure that all serialization to JSON is performed using a safe serialization function that delimits untrusted data within single or double quotes and escapes any special characters.

**Comment by calda** [comment]
I don't believe this is a security risk from a library perspective. It would be up to library consumers to trust or validate the `Data` input into this method.
