### ISSUE TITLE
Wrong Colors and Shapes in animation

### ISSUE THREAD

**Issue by arturdev** [airbnb/lottie-ios#1996]
## Which Version of Lottie are you using?

Lottie 4.1.3

## Expected Behavior 
In the simulator I always see the correct one

![Simulator Screen Shot - iPad Pro (12 9-inch) (6th generation) - 2023-03-11 at 19 01 58](https://user-images.githubusercontent.com/6263856/224613636-30eb88f9-9310-4bae-8e6e-e68ab4a2fb42.png)

## Actual Behavior

But on physical devices, SOMETIMES the animation looks like this! See the colors and shapes are somehow mixed! Restarting the animating (by killing and reopening the app, etc..) sometimes helps.
![IMG_2851](https://user-images.githubusercontent.com/6263856/224613653-cd2b1425-ab57-43d2-a075-dbdc870a1fc8.jpg)

## Animation JSON
Will post a link to json if needed.

**Comment by calda** [comment]
Can you share the animation json with a sample project that demonstrates this issue, plus repo steps?

**Comment by arturdev** [comment]
json file: https://drive.google.com/file/d/1jITvmu2NNZjnoypQvgLTmXekwo0Ks7VH/view?usp=sharing

**Comment by calda** [comment]
Can you share a sample project that demonstrates this issue? The animation plays correctly when I run it on my device.

**Comment by arturdev** [comment]
It will play correctly indeed, but after some (unknown to me) steps it becomes like in the screenshot I've posted.. 
So I can't tell any way to reproduce the issue (I can't reproduce even myself), but I'm getting many complains from the users..
