### ISSUE TITLE
Question : Is it possible to load remote json files into lottie lib ?

### ISSUE THREAD

**Issue by HWSTS** [airbnb/lottie-ios#200]
Hi,

firstly thank you for this great work its make apps animations become amazing .

I just wonder if i have stored some json files in app backend ex : firebase  storage , can i load this animation into my app via file URL or i have to download it first ? 
any explanation would be much appreciated .

Thank you again

**Comment by fabionuno** [comment]
@HWSTS you can load from an URL.

```objective-c
LOTAnimationView *animation = [[LOTAnimationView alloc] initWithContentsOfURL:[NSURL URLWithString:URL]];
[self.view addSubview:animation];
```

**Comment by HWSTS** [comment]
well this is great, sorry i know this part related to android but how to load the same file in android ?

**Comment by SantiagoGaleano** [comment]
Does anyone know how to load json files from firebase?

**Comment by AndroidDeveloperLB** [comment]
@SantiagoGaleano You can put very long json file on Firebase?

**Comment by SantiagoGaleano** [comment]
I have my animation .json in base of fire but I pass the url in the src of the lottie and it appears error

**Comment by AndroidDeveloperLB** [comment]
@SantiagoGaleano Sorry but it doesn't make sense. If the URL is to a file of json file, it should work as I wrote.
If it's not, you will have to do other things before, depending on what you did.

**Comment by SantiagoGaleano** [comment]
@AndroidDeveloperLB  What I'm doing in ionic and on the way I'm passing the firebase route, you have facebook or some mail to be able to contact you thank you very much

**Comment by AndroidDeveloperLB** [comment]
@SantiagoGaleano Sorry but I lack the experience to understand what you mean
