### ISSUE TITLE
Xcode 14.3 (RC1): "Failed to build module 'Lottie'; this SDK is not supported by the compiler"

### ISSUE THREAD

**Issue by RamblinWreck77** [airbnb/lottie-ios#2000]
## Which Version of Lottie are you using?

Lottie 4.1.2

## Expected Behavior 
import Lottie succeeds

## Actual Behavior
import Lottie throws error:
```
Failed to build module 'Lottie'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)', while this compiler is 'Apple Swift version 5.8 (swiftlang-5.8.0.124.1 clang-1403.0.22.11.100)'). Please select a toolchain which matches the SDK.
```

**Comment by RamblinWreck77** [comment]
Possibly relevant SO post:

https://stackoverflow.com/questions/70556401/swift-version-conflict-this-sdk-is-not-supported-by-the-compiler-please-select

is `BUILD_LIBRARY_FOR_DISTRIBUTION` set?

**Comment by calda** [comment]
We're tracking this issue in https://github.com/airbnb/lottie-ios/issues/1963

**Comment by RamblinWreck77** [comment]
@calda thanks for the quick reply!
