### ISSUE TITLE
Some animations stop automatically in the middle of the animation

### ISSUE THREAD

**Issue by 27leaves** [airbnb/lottie-ios#2005]
## Which Version of Lottie are you using?

Lottie 4.1.3

### Description

We use the library with a bunch of different animations and until now everything worked fine. Lately we had 2 animations that would just stop in the middle of the animation and start again at the beginning when the loop would be finished (I guess). 

Referencing lottie-react-native issue: https://github.com/lottie-react-native/lottie-react-native/issues/893

### Steps to Reproduce

I created a minimal example
1. Clone https://github.com/goodbag/MinimalLottieIosExample
2. pod install
3. Run the app

**Expected behavior:**
The animations loop smoothly

**Actual behavior:** 
The first animation stops in the middle and in the end it flickers and starts at the beginning again.
The second animation stops in the middle and starts at some point at the beginning again.
The third animation runs smoothly -> just one correct example.

See also the provided video

https://user-images.githubusercontent.com/999419/173605138-a9e588ab-4bb9-47aa-99cd-9c1a23ccd162.mp4

**Comment by calda** [comment]
The first two animations include javascript expressions, which are only supported by lottie-web and are not supported by lottie-ios.

**Comment by calda** [comment]
This is a common issue, so in #2006 I've added a new warning that's logged when attempting to play an animation that uses javascript expressions.

**Comment by 27leaves** [comment]
Thank you very much @calda ! 

A bit of background where I come from: I get those animations from my designer, who - I think - designs the animations in AfterEffects and exports them from there. Do you have any hint on how to avoid those JS expressions or how to get rid of them? I tried opening them in the Lottie Editor but I could not find a way to edit/remove those.

Thank you (and sorry for asking that here in the issue) - don't feel obliged to answer

**Comment by calda** [comment]
I believe these correspond to After Effects expressions: https://helpx.adobe.com/after-effects/using/expression-basics.html

**Comment by calda** [comment]
I would expect the only real workaround would be rework the animation in After Effects to look correct without using any of those expressions

**Comment by 27leaves** [comment]
Okay, thank you!
