### ISSUE TITLE
Quick Help not working with SPM binaryTarget version

### ISSUE THREAD

**Issue by osrufung** [airbnb/lottie-ios#2011]
## Which Version of Lottie are you using?

Lottie 3.x.x

## Expected Behavior 
Using the SPM version from https://github.com/airbnb/lottie-spm I'm not able to see the API documentation in the Quick menu, but only in the auto-complete dialog.

<img width="1124" alt="Screenshot 2023-03-29 at 16 27 13" src="https://user-images.githubusercontent.com/583458/228810534-ee1bd86f-599a-4b82-8ff5-b7824bfee756.png">

## Actual Behavior
Documentation should be visible in the Quick Menu

**Comment by calda** [comment]
This sounds like an issue with Xcode, not with the Lottie library. Could you file a feedback with Apple?
