### ISSUE TITLE
兼容OC的类希望开放一个属性

### ISSUE THREAD

**Issue by fanlilinSaber** [airbnb/lottie-ios#2021]
CompatibleAnimationView.swift

能不能开放出 属性 backgroundBehavior 的设置，这对我来说很重要可以修复一个问题

**Comment by calda** [comment]
@fanlilinSaber, does this help? https://github.com/airbnb/lottie-ios/pull/2027

**Comment by fanlilinSaber** [comment]
Thank you very much
