### ISSUE TITLE
Lottie crashing at LottieVector3D init

### ISSUE THREAD

**Issue by samantha2006** [airbnb/lottie-ios#2026]
## Which Version of Lottie are you using?

Lottie 4.1.3
Xcode 14.2
iOS 16.0 target 

## Expected Behavior 

I've tried setting up the animation via Storyboard and also programmatically.  It works fine in a demo project and worked perfectly in my full app earlier today but then it started crashing and I don't know why.  I have tried re-downloading the package multiple times, I've tried pods, I've tried the full repo for SPM as well as the iOS version.  It is crashing before the animation starts playing, it can't load the animation.  I don't understand how or why it would work fine and then stop working and also why it works fine in a sample app.  

Also, once it starts crashing, then it continues, even if I try to remove the animation file name from Storyboard.

## Actual Behavior

Crash at LottieVector3D init

## Animation JSON

I can email it to you, it's for an unreleased product.  The animation works fine in LottieFiles and also in a demo project I have that runs fine in the Xcode simulator.

The same thing is happening when I try to use animation that I download from LottieFiles - like a simple coffee cup animation here:  https://assets4.lottiefiles.com/packages/lf20_Dz3Jb8.json

**Comment by calda** [comment]
Can you share a sample Xcode project that demonstrates this issue?

**Comment by samantha2006** [comment]
Hi - what's the best way for me to share a sample project?

**Comment by samantha2006** [comment]
Hi - well, I'm sorry to have wasted your time.  I have it working again in my app, after deleting the package for the 5th time and setting it up again.  I have no idea why it kept getting into a crash state, but it's working and I'm going to just hope it keeps on working right!  If it does start up again, I'll try making a sample project to demonstrate the issue.  Thanks!
