### ISSUE TITLE
Animation proportions distorted

### ISSUE THREAD

**Issue by jamesmato** [airbnb/lottie-ios#203]
So I have an animation we're intending to use as a loading spinner. However the size and positions of layers gets messed up when we actually implement the json file.

[What it looks like with lottie](https://www.dropbox.com/s/tit9nt0yunbyydz/Logo%20Loop%20NOT%20RIGHT.mov?dl=0)

[What it _should_ look like](https://www.dropbox.com/s/28oo1e7cybottdr/Logo_Loop_RED.mp4?dl=0)

I've removed expressions and tried making the masks into shape layers and nothing seems to work.
Any ideas?

**Comment by therealsalih** [comment]
Hi @jamesmato can you send through your AEP file? It all depends on how the animation was built
