### ISSUE TITLE
iPadOS 12 ShapeRenderLayer.init(renderer:)

### ISSUE THREAD

**Issue by cinema8150** [airbnb/lottie-ios#2031]
All crash on OS 12, and I can`t found this err json.

## Which Version of Lottie are you using?

Lottie 4.1.3

![image](https://user-images.githubusercontent.com/77312323/230814977-f15e9313-f6cb-4bd4-8a51-62fbb683f84d.png)

![image](https://user-images.githubusercontent.com/77312323/230814885-8ada9b02-d515-4120-acc6-b51a1fcbb5a1.png)

**Comment by calda** [comment]
Can you please share a sample Xcode project that reproduces this issue?
