### ISSUE TITLE
colors not showing on iOS when colors edited with lottie editor

### ISSUE THREAD

**Issue by gsgou** [airbnb/lottie-ios#2032]
Colors not showing on iOS when colors edited with [lottie editor](https://lottiefiles.com/es/lottie-editor)
There also different headers, trailers when comparing the json files attached in the
compare json files.zip

## Which Version of Lottie are you using?

Lottie 4.1.0

## Expected Behavior 
Shows animation as in Android

## Actual Behavior
replace Animation string
from 84628-voice-line-wave-animation_original.json
to. 84628-voice-line-wave-animation_edited.json

## Animation JSON
[compare.json.files.zip](https://github.com/airbnb/lottie-ios/files/11208309/compare.json.files.zip)

**Comment by calda** [comment]
Testing this locally, the animations on iOS look the same as they do when I test the animations on lottiefiles.com, which suggests that the iOS implementation is correct
