### ISSUE TITLE
getting 'corruptedData'

### ISSUE THREAD

**Issue by mchiasson-youi** [airbnb/lottie-ios#2038]
Getting a 'corruptedData' error when attempting to load one of our dotLottie file. the same file works perfectly fine in lottie-compose and lottie-web.

## Which Version of Lottie are you using?

Lottie 4.1.3

## Expected Behavior 
no error

## Actual Behavior
corruptedData

## Animation JSON
Unable to share due to NDA.

**Comment by mchiasson-youi** [comment]
Could be related to https://github.com/airbnb/lottie-ios/issues/1945

If that is the case, when should we expect the fix to be released? Is there a work around that we can do for now? Thank!

**Comment by mchiasson-youi** [comment]
Found a work around: using `.json` instead of `.lottie` seems to work for us.

**Comment by calda** [comment]
I'll release an update soon. In the mean time pointing your app to the `master` branch instead of the latest release is a good option.
