### ISSUE TITLE
NSDataAsset Leaking

### ISSUE THREAD

**Issue by b3ll** [airbnb/lottie-ios#2039]
## Which Version of Lottie are you using?

Lottie 3.x.x

## Expected Behavior 

No leaking `NSDataAsset` instances.

## Actual Behavior

When `LottieAnimation` is allocated via most paths (notably `LottieAnimation.named(animationName, bundle: bundle)`), it has a fallback path to check xcassets for resources via `NSDataAsset`. If the name for an animation is incorrectly specified, and that animation doesn't exist (or the wrong bundle is supplied), it'll fall back to trying to initialize `NSDataAsset` with the name of the asset as the key. If the key for the asset doesn't exist, calling `NSDataAsset`'s initializer causes a leak (at least as of iOS 16.4). 

I'll be filing a feedback with Apple, but in the meantime just wanted to report it if you wanted to add some sort of assert to notify others of a missing `xcasset` resource with an error / debug message.

## Animation JSON

Can be any json really.

Here's a sample project, just calling `NSDataAsset(name: "anything_that_doesnt_exist", bundle: .main)` is enough to cause a leak to hapen. 

[NSDataAssetLeak.zip](https://github.com/airbnb/lottie-ios/files/11299286/NSDataAssetLeak.zip)

**Comment by calda** [comment]
Thanks for the report. This appears to be an issue with `NSDataAsset` itself and not Lottie, since you can repro this in a sample project that doesn't include Lottie. Closing for now since there wouldn't be a fix on our end. Thanks for filing a feedback with Apple!
