### ISSUE TITLE
Support for PointValueProvider with CoreAnimation rendering engine

### ISSUE THREAD

**Issue by aswathr** [airbnb/lottie-ios#2042]
Prior to the introduction of CoreAnimation rendering, point value providers were working on MainThreadAnimation. Requesting support for point value providers on CoreAnimation engine.
The use case is that I have Lottie json with two identical (mirrored) layers that add a sparkles kind of effect to the text that I'd configure in-between the two. To configure the (variable) distance between the layers, I use a point value provider on a a keypath as such: `RightGroup.Transform.Position` and `LeftGroup.Transform.Position`. PFB the lottie json being used.

## Which Version of Lottie are you using?
Lottie 4.1.3

## Expected Behavior 
Need support for PointValueProvider
These are screen captures recorded using MainThreadAnimation renderer to illustrate my use case.
https://user-images.githubusercontent.com/10108566/234231522-0c28bd54-6133-4036-a40c-fc4a4d952426.mov
https://user-images.githubusercontent.com/10108566/234231532-a9e0b6b8-2348-4ace-a8aa-11924aa68f9b.mov

## Animation JSON
[rewardsGroup.json.zip](https://github.com/airbnb/lottie-ios/files/11320731/rewardsGroup.json.zip)

**Comment by calda** [comment]
Can you share sample code of how you're configuring the value providers? 

In the meantime, I'd suggest continuing to use the Main Thread rendering engine by passing `configuration: LottieConfiguration(renderingEngine: .mainThread)` to your `LottieAnimationView`.

**Comment by aswathr** [comment]
PFA sample project. I'm currently using Main Thread rendering to render these. However, since I have multiple lottie sparkle views (in a table view) in a view, it is taking a performance hit especially on older devices. So I've disabled this animation on older/ less capable devices.
[lottieValueProviderSample.zip](https://github.com/airbnb/lottie-ios/files/11328787/lottieValueProviderSample.zip)
