### ISSUE TITLE
Using lottie-ios causes TestFlight to reject project because of Bitcode

### ISSUE THREAD

**Issue by jkhoel** [airbnb/lottie-ios#2043]
Following XCode 14, Apple has depricated support for Bitcode. Using lottie-ios now causes a rejection in TestFlight/App Store with the following reason:
`ITMS-90482: Invalid Executable - The executable 'MyApp.app/Frameworks/Lottie.framework/Lottie' contains bitcode.`

If I build my project and run `otool` on it, it does indeed show that it contains bytecode:
```sh
$ otool -l output/Lottie.framework/Lottie | grep __LLVM -1
  cmdsize 152
  segname __LLVM
   vmaddr 0x0000000000190000
--
  sectname __bundle
   segname __LLVM
      addr 0x0000000000190000
```

## Which Version of Lottie are you using?

Lottie 4.1.3 (via Swift package manager)

## Expected Behavior 
This to go trough without any issue :)

## Actual Behavior
App gets rejected by Apple as lottie-ios introduces bitcode into the project

**Comment by calda** [comment]
Hopefully we can find repro steps for this issue that just require clicking the "Validate App" button in the Organizer rather than actually uploading a full project to App Store Connect

**Comment by jkhoel** [comment]
@calda I will check if I can release the project we are using somewhere public 🙏 

But I think it should suffice to just make _some_ project, add lottie-ios and then try uploading the IPA to testflight
