### ISSUE TITLE
Support `animating multiple keyframes for stroke dashPattern values` with the Core Animation rendering engine

### ISSUE THREAD

**Issue by mbastos** [airbnb/lottie-ios#2046]
Hi! We recently upgraded Lottie to v4 in our project, and because the default rendering engine is now Core Animation, we noticed that an animation that we use has compatibility issues, which results in some errors being logged to the console. When switching back to `.mainThread` rendering, the errors are gone, but we are interested in the performance gains provided by the new renderer.

This is the error output when using the `.coreAnimation` rendering engine:

```
Lottie/LottieAnimationView.swift:1144: Assertion failed: Encountered Core Animation compatibility issues while setting up animation:
[Shape Layer 3.Ellipse 1.Stroke 1] The Core Animation rendering engine does not support animating multiple keyframes for stroke dashPattern values, due to limitations of Core Animation.
[Shape Layer 3.Ellipse 1.Stroke 1] The Core Animation rendering engine does not support animating multiple keyframes for stroke dashPattern values, due to limitations of Core Animation.
[Shape Layer 5.Ellipse 1.Stroke 1] The Core Animation rendering engine does not support animating multiple keyframes for stroke dashPattern values, due to limitations of Core Animation.
[Shape Layer 5.Ellipse 1.Stroke 1] The Core Animation rendering engine does not support animating multiple keyframes for stroke dashPattern values, due to limitations of Core Animation.
[Shape Layer 4.Ellipse 1.Stroke 1] The Core Animation rendering engine does not support animating multiple keyframes for stroke dashPattern values, due to limitations of Core Animation.
[Shape Layer 4.Ellipse 1.Stroke 1] The Core Animation rendering engine does not support animating multiple keyframes for stroke dashPattern values, due to limitations of Core Animation.

This animation cannot be rendered correctly by the Core Animation engine.
To resolve this issue, you can use `RenderingEngineOption.automatic`, which automatically falls back
to the Main Thread rendering engine when necessary, or just use `RenderingEngineOption.mainThread`.
```

## Which Version of Lottie are you using?

Lottie 4.1.3

## Expected Behavior 

The animation to be played with the Core Animation renderer.

## Actual Behavior

Lottie outputs an error and is only capable of playing the animation with the main thread renderer.

## Animation JSON

[loading.json.zip](https://github.com/airbnb/lottie-ios/files/11334206/loading.json.zip)

**Comment by calda** [comment]
Thanks for the sample animation. Unfortunately it is not possible to support this in the Core Animation rendering engine, because Core Animation itself doesn't support animating `lineDashPattern`: https://developer.apple.com/documentation/quartzcore/cashapelayer/1521921-linedashpattern

**Comment by calda** [comment]
I tested this and confirmed that Core Animation doesn't support this, even if we create the `CAAnimation`s etc
