### ISSUE TITLE
The lottie animation is loaded and displayed but with no animation.

### ISSUE THREAD

**Issue by cristian1980** [airbnb/lottie-ios#2055]
The attached json file does not animate in the sample application https://github.com/airbnb/lottie-ios/tree/master/Example/iOS.

Thank you for any help.

## Which Version of Lottie are you using?

Lottie 4.2.0 and 4.1.3 have this issue

## Expected Behavior 
The animation should animate. 

## Actual Behavior
The animation in the attached file is loaded and displayed correctly but no animation can be observed.
![image](https://user-images.githubusercontent.com/5364569/235214535-5a79c746-c8ca-4393-984f-7ca00587512a.png)

## Animation JSON
The json file is attached.

[v13.json.zip](https://github.com/airbnb/lottie-ios/files/11355954/v13.json.zip)

**Comment by calda** [comment]
Thanks for the report @cristian1980, here's a fix: https://github.com/airbnb/lottie-ios/pull/2157

**Comment by calda** [comment]
@travismmorgan, the issue with your animation was fixed by #2156

![2023-08-24 15 56 54](https://github.com/airbnb/lottie-ios/assets/1811727/d594821d-b6ff-4249-967b-b4976af62a07)
