### ISSUE TITLE
Xcode 14.3 build warning when installing via CocoaPods: no rule to process file .../ZipFoundation/README.md

### ISSUE THREAD

**Issue by reggian** [airbnb/lottie-ios#2056]
## Which Version of Lottie are you using?

Lottie 4.2.0

## Expected Behavior 
No build warnings with Xcode 14.3 when installing via CocoaPods.

## Actual Behavior
Xcode 14.3 emits a build warning:
>no rule to process file '.../Pods/lottie-ios/Sources/Private/Model/DotLottie/ZipFoundation/README.md' of type 'net.daringfireball.markdown' for architecture 'arm64'

I didn't try other install methods nor Xcode versions.

It seems this was introduced with #1978.

**Comment by Shiaulis** [comment]
is there any chance to have a minor version release with this change? This warning bothers now our CI process 😊

**Comment by vg-identance** [comment]
any updates?

**Comment by MAmmarShahid** [comment]
facing same issue

**Comment by calda** [comment]
This is fixed in 4.3.0
