### ISSUE TITLE
Feature request: replace animation layer with UIView

### ISSUE THREAD

**Issue by tomgilder** [airbnb/lottie-ios#206]
I want to incorporate some native UI controls into an animation, to have them pop and scale out of an animation and finish at full size.

Would it be possible to replace an animation layer with a UIView, having captured it with `snapshot​View​After​Screen​Updates:`?

Thank you for an amazing library 👍

**Comment by buba447** [comment]
We currently offer partial support for this through the `- (void)addSubview:(nonnull LOTView *)view
      toLayerNamed:(nonnull NSString *)layer;` function. Currently the layer added is only masked by the after effects layer specified, but we are working to add motion suppport as well.

**Comment by buba447** [comment]
This now works in V2 of lottie!
