### ISSUE TITLE
Undefined symbols for architecture arm64 with Lottie 4.1.3

### ISSUE THREAD

**Issue by caniodica** [airbnb/lottie-ios#2061]
## Which Version of Lottie are you using?

Lottie 4.1.3

## Context
Xcode 14.3
Cocoapods 1.12.1
CPU Mac M1

The app have some dependencies installed via cocoapods (1.12.1, latest stable). One of these dependencies has Lottie v 4.1.3 in its podspec. 

## Expected Behavior 
Building Successfully

## Actual Behavior
The app can't build and the error is `ld: symbol(s) not found for architecture arm64`
It seems a problem in the linking phase.

Here a screenshot of the error in Xcode:

<img width="1372" alt="Screenshot 2023-05-10 alle 19 20 20" src="https://github.com/airbnb/lottie-ios/assets/13018040/e1396b4c-b624-4bd0-981b-5c3906bc3b2b">

**Comment by calda** [comment]
Can you please share a sample project that demonstrates this issue? Thanks!

**Comment by caniodica** [comment]
I am unable to share a demo project because my app uses a private dependency, which in turn has Lottie 4.2.0 as a dependency.

Anyway, I was able to fix the issue adding a post_install script in my podfile:
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name == "lottie-ios"
                target.build_configurations.each do |config|
                    config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
                end
            end
        end
    end
end
```
