### ISSUE TITLE
The main thread is stuck while FilepathImageProvider imageForAsset 

### ISSUE THREAD

**Issue by lqwang521** [airbnb/lottie-ios#2063]
## Which Version of Lottie are you using?

Lottie 3.4.0

## Expected Behavior 
Supports child threads to load images

## Actual Behavior
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: 9CE4920F-2D00-4656-BF15-79292946EE2F
Beta Identifier:     1F817F8C-AD5A-4E70-B438-8599C643A537
Hardware Model:      iPhone11,2
Process:             youavideo [2915]
Path:                /private/var/containers/Bundle/Application/7238C531-6E07-4BB3-9023-6A129B5EEF5B/youavideo.app/youavideo
Identifier:          com.baidu.youavideo
Version:             5.3.10 (5.3.10.4)
AppStoreTools:       14E221
AppVariant:          1:iPhone11,2:16
Beta:                YES
Code Type:           ARM-64 (Native)
Role:                Non UI
Parent Process:      launchd [1]
Coalition:           com.baidu.youavideo [10968]

Date/Time:           2023-05-09 11:05:09.9999 +0900
Launch Time:         2023-05-09 11:05:02.1812 +0900
OS Version:          iPhone OS 16.1.1 (20B101)
Release Type:        User
Baseband Version:    5.01.01
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: FRONTBOARD 2343432205 
<RBSTerminateContext| domain:10 code:0x8BADF00D explanation:scene-create watchdog transgression: application<com.baidu.youavideo>:2915 exhausted CPU time allowance of 6.12 seconds
ProcessVisibility: Background
ProcessState: Running
WatchdogEvent: scene-create
WatchdogVisibility: Background
WatchdogCPUStatistics: (
"Elapsed total CPU time (seconds): 11.190 (user 11.190, system 0.000), 59% CPU",
"Elapsed application CPU time (seconds): 8.342, 44% CPU"
) reportType:CrashLog maxTerminationResistance:Interactive>

Triggered by Thread:  0

Kernel Triage:
VM - pmap_enter retried due to resource shortage
VM - pmap_enter retried due to resource shortage
VM - pmap_enter retried due to resource shortage
VM - pmap_enter retried due to resource shortage
VM - pmap_enter retried due to resource shortage

Thread 0 name:   Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	       0x1d3072248 stat + 8
1   Foundation                    	       0x19088bac4 -[NSFileManager fileExistsAtPath:] + 92
2   UIKitCore                     	       0x198aba3c0 ___UIImageCollectImagePathsForPath_block_invoke_2 + 568
3   UIKitCore                     	       0x198aaa074 ___UIImageCollectImagePathsForPath_block_invoke + 736
4   UIKitCore                     	       0x1989b0af4 _UIImageCollectImagePathsForPath + 616
5   UIKitCore                     	       0x198809fc0 _UIImageSourceAtPath + 136
6   UIKitCore                     	       0x1986709e0 -[UIImage initWithContentsOfFile:cache:] + 72
7   youavideo                     	       0x107aad8e4 0x104f4c000 + 45488356
8   youavideo                     	       0x107aadb90 0x104f4c000 + 45489040
9   youavideo                     	       0x107a76414 0x104f4c000 + 45261844
10  youavideo                     	       0x107a764c0 0x104f4c000 + 45262016
11  youavideo                     	       0x107acb420 0x104f4c000 + 45610016
12  youavideo                     	       0x107ad8660 0x104f4c000 + 45663840
13  youavideo                     	       0x107a615ec 0x104f4c000 + 45176300
14  youavideo                     	       0x107a6ac60 0x104f4c000 + 45214816
15  youavideo                     	       0x107a69c88 0x104f4c000 + 45210760
16  youavideo                     	       0x10921ec80 0x104f4c000 + 70069376
17  youavideo                     	       0x10921e368 0x104f4c000 + 70067048
18  youavideo                     	       0x10921e4e0 0x104f4c000 + 70067424
19  youavideo                     	       0x10921e41c 0x104f4c000 + 70067228
20  youavideo                     	       0x108d0064c 0x104f4c000 + 64702028
21  youavideo                     	       0x108d041f4 0x104f4c000 + 64717300
22  youavideo                     	       0x108d03fc0 0x104f4c000 + 64716736
23  youavideo                     	       0x108d052a0 0x104f4c000 + 64721568
24  youavideo                     	       0x108cc0558 0x104f4c000 + 64439640
25  youavideo                     	       0x108cc091c 0x104f4c000 + 64440604

## Animation JSON
{"v":"5.6.10","fr":25,"ip":0,"op":47,"w":510,"h":414,"nm":"全局交付文件","ddd":0,"assets":[{"id":"image_0","w":83,"h":81,"u":"images/","p":"img_0.png","e":0},{"id":"image_1","w":658,"h":658,"u":"images/","p":"img_1.png","e":0},{"id":"image_2","w":330,"h":330,"u":"images/","p":"img_2.png","e":0},{"id":"image_3","w":330,"h":330,"u":"images/","p":"img_3.png","e":0},{"id":"image_4","w":330,"h":330,"u":"images/","p":"img_4.png","e":0},{"id":"image_5","w":330,"h":330,"u":"images/","p":"img_5.png","e":0},{"id":"image_6","w":330,"h":330,"u":"images/","p":"img_6.png","e":0},{"id":"image_7","w":330,"h":330,"u":"images/","p":"img_7.png","e":0},{"id":"image_8","w":330,"h":330,"u":"images/","p":"img_8.png","e":0},{"id":"image_9","w":330,"h":330,"u":"images/","p":"img_9.png","e":0},{"id":"image_10","w":330,"h":330,"u":"images/","p":"img_10.png","e":0},{"id":"image_11","w":330,"h":330,"u":"images/","p":"img_11.png","e":0},{"id":"image_12","w":330,"h":330,"u":"images/","p":"img_12.png","e":0},{"id":"image_13","w":330,"h":330,"u":"images/","p":"img_13.png","e":0},{"id":"image_14","w":330,"h":330,"u":"images/","p":"img_14.png","e":0},{"id":"image_15","w":330,"h":330,"u":"images/","p":"img_15.png","e":0},{"id":"image_16","w":330,"h":330,"u":"images/","p":"img_16.png","e":0},{"id":"image_17","w":330,"h":330,"u":"images/","p":"img_17.png","e":0},{"id":"image_18","w":330,"h":330,"u":"images/","p":"img_18.png","e":0},{"id":"image_19","w":330,"h":330,"u":"images/","p":"img_19.png","e":0},{"id":"image_20","w":330,"h":330,"u":"images/","p":"img_20.png","e":0},{"id":"image_21","w":330,"h":330,"u":"images/","p":"img_21.png","e":0},{"id":"image_22","w":330,"h":330,"u":"images/","p":"img_22.png","e":0},{"id":"image_23","w":330,"h":330,"u":"images/","p":"img_23.png","e":0},{"id":"image_24","w":330,"h":330,"u":"images/","p":"img_24.png","e":0},{"id":"image_25","w":330,"h":330,"u":"images/","p":"img_25.png","e":0},{"id":"image_26","w":129,"h":57,"u":"images/","p":"img_26.png","e":0},{"id":"comp_0","layers":[{"ddd":0,"ind":1,"ty":2,"nm":"相机0000.png","cl":"png","refId":"image_2","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[248,240,0],"ix":2},"a":{"a":0,"k":[165,165,0],"ix":1},"s":{"a":0,"k":[121.818,121.818,100],"ix":6}},"ao":0,"ip":0,"op":2,"st":0,"bm":0},{"ddd":0,"ind":2,"ty":2,"nm":"相机0002.png","cl":"png","refId":"image_3","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[248,240,0],"ix":2},"a":{"a":0,"k":[165,165,0],"ix":1},"s":{"a":0,"k":[121.818,121.818,100],"ix":6}},"ao":0,"ip":2,"op":4,"st":2,"bm":0},{"ddd":0,"ind":3,"ty":2,"nm":"相机0004.png","cl":"png","refId":"image_4","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[248,240,0],"ix":2},"a":{"a":0,"k":[165,165,0],"ix":1},"s":{"a":0,"k":[121.818,121.818,100],"ix":6}},"ao":0,"ip":4,"op":6,"st":4,"bm":0},{"ddd":0,"ind":4,"ty":2,"nm":"相机0006.png","cl":"png","refId":"image_5","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[248,240,0],"ix":2},"a":{"a":0,"k":[165,165,0],"ix":1},"s":{"a":0,"k":[121.818,121.818,100],"ix":6}},"ao":0,"ip":6,"op":8,"st":6,"bm":0},{"ddd":0,"ind":5,"ty":2,"nm":"相机0008.png","cl":"png","refId":"image_6","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[248,240,0],"ix":2},"a":{"a":0,"k":[165,165,0],"ix":1},"s":{"a":0,"k":[121.818,121.818,100],"ix":6}},"ao":0,"ip":8,"op":10,"st":8,"bm":0},{"ddd":0,"ind":6,"ty":2,"nm":"相机0010.png","cl":"png","refId":"image_7","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[248,240,0],"ix":2},"a":{"a":0,"k":[165,165,0],"ix":1},"s":{"a":0,"k":[121.818,121.818,100],"ix":6}},"ao":0,"ip":10,"op":12,"st":10,"bm":0},{"ddd":0,"ind":7,"ty":2,"nm":"相机0012.png","cl":"png","refId":"image_8","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[248,240,0],"ix":2},"a":{"a":0,"k":[165,165,0],"ix":1},"s":{"a":0,"k":[121.818,121.818,100],"ix":6}},"ao":0,"ip":12,"op":14,"st":12,"bm":0},{"ddd":0,"ind":8,"ty":2,"nm":"相机0014.png","cl":"png","refId":"image_9","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[248,240,0],"ix":2},"a":{"a":0,"k":[165,165,0],"ix":1},"s":{"a":0,"k":[121.818,121.818,100],"ix":6}},"ao":0,"ip":14,"op":16,"st":14,"bm":0},{"ddd":0,"ind":9,"ty":2,"nm":"相机0016.png","cl":"png","refId":"image_10","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[248,240,0],"ix":2},"a":{"a":0,"k":[165,165,0],"ix":1},"s":{"a":0,"k":[121.818,121.818,100],"ix":6}},"ao":0,"ip":16,"op":18,"st":16,"bm":0},{"ddd":0,"ind":10,"ty":2,"nm":"相机0018.png","cl":"png","refId":"image_11","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[248,240,0],"ix":2},"a":{"a":0,"k":[165,165,0],"ix":1},"s":{"a":0,"k":[121.818,121.818,100],"ix":6}},"ao":0,"ip":18,"op":20,"st":18,"bm":0},{"ddd":0,"ind":11,"ty":2,"nm":"相机0020.png","cl":"png","refId":"image_12","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[248,240,0],"ix":2},"a":{"a":0,"k":[165,165,0],"ix":1},"s":{"a":0,"k":[121.818,121.818,100],"ix":6}},"ao":0,"ip":20,"op":22,"st":20,"bm":0},{"ddd":0,"ind":12,"ty":2,"nm":"相机0022.png","cl":"png","refId":"image_13","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[248,240,0],"ix":2},"a":{"a":0,"k":[165,165,0],"ix":1},"s":{"a":0,"k":[121.818,121.818,100],"ix":6}},"ao":0,"ip":22,"op":24,"st":22,"bm":0},{"ddd":0,"ind":13,"ty":2,"nm":"相机0024.png","cl":"png","refId":"image_14","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[248,240,0],"ix":2},"a":{"a":0,"k":[165,165,0],"ix":1},"s":{"a":0,"k":[121.818,121.818,100],"ix":6}},"ao":0,"ip":24,"op":26,"st":24,"bm":0},{"ddd":0,"ind":14,"ty":2,"nm":"相机0026.png","cl":"png","refId":"image_15","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[248,240,0],"ix":2},"a":{"a":0,"k":[165,165,0],"ix":1},"s":{"a":0,"k":[121.818,121.818,100],"ix":6}},"ao":0,"ip":26,"op":28,"st":26,"bm":0},{"ddd":0,"ind":15,"ty":2,"nm":"相机0028.png","cl":"png","refId":"image_16","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[248,240,0],"ix":2},"a":{"a":0,"k":[165,165,0],"ix":1},"s":{"a":0,"k":[121.818,121.818,100],"ix":6}},"ao":0,"ip":28,"op":30,"st":28,"bm":0},{"ddd":0,"ind":16,"ty":2,"nm":"相机0030.png","cl":"png","refId":"image_17","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[248,240,0],"ix":2},"a":{"a":0,"k":[165,165,0],"ix":1},"s":{"a":0,"k":[121.818,121.818,100],"ix":6}},"ao":0,"ip":30,"op":32,"st":30,"bm":0},{"ddd":0,"ind":17,"ty":2,"nm":"相机0032.png","cl":"png","refId":"image_18","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[248,240,0],"ix":2},"a":{"a":0,"k":[165,165,0],"ix":1},"s":{"a":0,"k":[121.818,121.818,100],"ix":6}},"ao":0,"ip":32,"op":34,"st":32,"bm":0},{"ddd":0,"ind":18,"ty":2,"nm":"相机0034.png","cl":"png","refId":"image_19","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[248,240,0],"ix":2},"a":{"a":0,"k":[165,165,0],"ix":1},"s":{"a":0,"k":[121.818,121.818,100],"ix":6}},"ao":0,"ip":34,"op":36,"st":34,"bm":0},{"ddd":0,"ind":19,"ty":2,"nm":"相机0036.png","cl":"png","refId":"image_20","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[248,240,0],"ix":2},"a":{"a":0,"k":[165,165,0],"ix":1},"s":{"a":0,"k":[121.818,121.818,100],"ix":6}},"ao":0,"ip":36,"op":38,"st":36,"bm":0},{"ddd":0,"ind":20,"ty":2,"nm":"相机0038.png","cl":"png","refId":"image_21","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[248,240,0],"ix":2},"a":{"a":0,"k":[165,165,0],"ix":1},"s":{"a":0,"k":[121.818,121.818,100],"ix":6}},"ao":0,"ip":38,"op":40,"st":38,"bm":0},{"ddd":0,"ind":21,"ty":2,"nm":"相机0040.png","cl":"png","refId":"image_22","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[248,240,0],"ix":2},"a":{"a":0,"k":[165,165,0],"ix":1},"s":{"a":0,"k":[121.818,121.818,100],"ix":6}},"ao":0,"ip":40,"op":42,"st":40,"bm":0},{"ddd":0,"ind":22,"ty":2,"nm":"相机0042.png","cl":"png","refId":"image_23","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[248,240,0],"ix":2},"a":{"a":0,"k":[165,165,0],"ix":1},"s":{"a":0,"k":[121.818,121.818,100],"ix":6}},"ao":0,"ip":42,"op":44,"st":42,"bm":0},{"ddd":0,"ind":23,"ty":2,"nm":"相机0044.png","cl":"png","refId":"image_24","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[248,240,0],"ix":2},"a":{"a":0,"k":[165,165,0],"ix":1},"s":{"a":0,"k":[121.818,121.818,100],"ix":6}},"ao":0,"ip":44,"op":46,"st":44,"bm":0},{"ddd":0,"ind":24,"ty":2,"nm":"相机0046.png","cl":"png","refId":"image_25","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[248,240,0],"ix":2},"a":{"a":0,"k":[165,165,0],"ix":1},"s":{"a":0,"k":[121.818,121.818,100],"ix":6}},"ao":0,"ip":46,"op":48,"st":46,"bm":0}]}],"layers":[{"ddd":0,"ind":1,"ty":2,"nm":"星星1.png","cl":"png","refId":"image_0","sr":1,"ks":{"o":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":23,"s":[0],"e":[50]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":34,"s":[50],"e":[0]},{"t":45}],"ix":11},"r":{"a":0,"k":28,"ix":10},"p":{"a":0,"k":[374,176,0],"ix":2},"a":{"a":0,"k":[41.5,40.5,0],"ix":1},"s":{"a":1,"k":[{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"t":23,"s":[42,42,100],"e":[49,49,100]},{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"t":34,"s":[49,49,100],"e":[38,38,100]},{"t":45}],"ix":6}},"ao":0,"ip":0,"op":250,"st":0,"bm":0},{"ddd":0,"ind":2,"ty":2,"nm":"星星1.png","cl":"png","refId":"image_0","sr":1,"ks":{"o":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":16,"s":[0],"e":[50]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":28,"s":[50],"e":[0]},{"t":39}],"ix":11},"r":{"a":0,"k":-26,"ix":10},"p":{"a":0,"k":[139,157,0],"ix":2},"a":{"a":0,"k":[41.5,40.5,0],"ix":1},"s":{"a":1,"k":[{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"t":16,"s":[59,59,100],"e":[72,72,100]},{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"t":28,"s":[72,72,100],"e":[38,38,100]},{"t":39}],"ix":6}},"ao":0,"ip":0,"op":250,"st":0,"bm":0},{"ddd":0,"ind":3,"ty":2,"nm":"1da8f6bc28f99236fd7d51e395787264ccfb45c331153-zVijbX_fw658.webp","cl":"webp","refId":"image_1","sr":1,"ks":{"o":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":25,"s":[0],"e":[100]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":29,"s":[100],"e":[0]},{"t":32}],"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[276,297,0],"ix":2},"a":{"a":0,"k":[329,329,0],"ix":1},"s":{"a":0,"k":[34.65,34.65,100],"ix":6}},"ao":0,"ip":0,"op":250,"st":0,"bm":0},{"ddd":0,"ind":4,"ty":0,"nm":"预合成 1","refId":"comp_0","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[257,382,0],"ix":2},"a":{"a":0,"k":[255,382.51,0],"ix":1},"s":{"a":0,"k":[89,89,100],"ix":6}},"ao":0,"ef":[{"ty":5,"nm":"色相/饱和度","np":11,"mn":"ADBE HUE SATURATION","ix":1,"en":1,"ef":[{"ty":7,"nm":"通道控制","mn":"ADBE HUE SATURATION-0002","ix":1,"v":{"a":0,"k":1,"ix":1}},{},{"ty":0,"nm":"主色相","mn":"ADBE HUE SATURATION-0004","ix":3,"v":{"a":0,"k":0,"ix":3}},{"ty":0,"nm":"主饱和度","mn":"ADBE HUE SATURATION-0005","ix":4,"v":{"a":0,"k":0,"ix":4}},{"ty":0,"nm":"主亮度","mn":"ADBE HUE SATURATION-0006","ix":5,"v":{"a":0,"k":3,"ix":5}},{"ty":7,"nm":"彩色化","mn":"ADBE HUE SATURATION-0007","ix":6,"v":{"a":0,"k":0,"ix":6}},{"ty":0,"nm":"着色色相","mn":"ADBE HUE SATURATION-0008","ix":7,"v":{"a":0,"k":0,"ix":7}},{"ty":0,"nm":"着色饱和度","mn":"ADBE HUE SATURATION-0009","ix":8,"v":{"a":0,"k":25,"ix":8}},{"ty":0,"nm":"着色亮度","mn":"ADBE HUE SATURATION-0010","ix":9,"v":{"a":0,"k":0,"ix":9}}]}],"w":510,"h":414,"ip":0,"op":250,"st":0,"bm":0},{"ddd":0,"ind":5,"ty":2,"nm":"Ellipse 272.png","cl":"png","refId":"image_26","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[255,388.75,0],"ix":2},"a":{"a":0,"k":[64.5,28.5,0],"ix":1},"s":{"a":0,"k":[100,62.281,100],"ix":6}},"ao":0,"ip":0,"op":250,"st":0,"bm":0}],"markers":[]}

**Comment by calda** [comment]
I think this is the same issue as https://github.com/airbnb/lottie-ios/issues/1330
