### ISSUE TITLE
Pixellated Shape Layers

### ISSUE THREAD

**Issue by collinleix** [airbnb/lottie-ios#2066]
Hello! 

Parts of our animation is showing up pixelated on iOS.  It plays fine in Web browser.   Most are direct shape layers, not precomped.   Some objects are scaled past 100%, but nothing past 370%.  Scaling has been fine in the past, so this seems to be the bug?

This is a similar behavior to this past issue 1022: https://github.com/airbnb/lottie-ios/issues/1022 

## Which Version of Lottie are you using?

Lottie 4.1.2

## Expected Behavior 
<img width="402" alt="Expected Behavior" src="https://github.com/airbnb/lottie-ios/assets/133789995/863c4611-9167-443c-91bd-218144f0dec1">

## Actual Behavior
![Actual Behavior](https://github.com/airbnb/lottie-ios/assets/133789995/31abc363-c59b-4095-a1f0-dad9e8a6518b)

## Animation JSON

JSON and AE files in here:
[D12_Bug Report.zip](https://github.com/airbnb/lottie-ios/files/11489333/D12_Bug.Report.zip)

**Comment by calda** [comment]
Thanks for the report! Fixed in https://github.com/airbnb/lottie-ios/pull/2067.
