### ISSUE TITLE
Lottie Animation support for Dynamic Island 

### ISSUE THREAD

**Issue by rajivd15** [airbnb/lottie-ios#2068]
## Which Version of Lottie are you using?

Lottie-ios 4.0.1

## Expected Behavior 
Lottie Animation on Dynamic Island View

## Actual Behavior
Lottie Animation is not working when using UIViewRepresentable Swift view in Dynamic Island Expanded region. It's displaying Yellow image with no entry symbol. 

![IMG_8263](https://github.com/airbnb/lottie-ios/assets/10971883/0a264db1-6542-4606-8fdd-f7a8445b76dc)

## Animation JSON
JSON: 
{"v":"5.7.5","fr":60,"ip":0,"op":90,"w":64,"h":64,"nm":"check","ddd":0,"assets":[],"layers":[{"ddd":0,"ind":1,"ty":4,"nm":"check","sr":1,"ks":{"o":{"a":0,"k":100},"r":{"a":0,"k":0},"p":{"a":0,"k":[32,32,0]},"a":{"a":0,"k":[0,0,0]},"s":{"a":0,"k":[33.333,33.333,100]}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ks":{"a":0,"k":{"i":[[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0]],"v":[[9.25,-6],[-2.75,6],[-9.25,-0.5]],"c":false}},"nm":"Path 1","hd":false},{"ty":"tm","s":{"a":1,"k":[{"i":{"x":[0.461],"y":[1]},"o":{"x":[0.466],"y":[0]},"t":44,"s":[100]},{"t":90,"s":[0]}]},"e":{"a":0,"k":100},"o":{"a":0,"k":0},"m":1,"nm":"Trim Paths 1","hd":false},{"ty":"st","c":{"a":0,"k":[0.119997918606,0.750781238079,0.458097785711,1]},"o":{"a":0,"k":100},"w":{"a":0,"k":3},"lc":2,"lj":2,"bm":0,"nm":"Stroke 1","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0]},"a":{"a":0,"k":[0,0]},"s":{"a":0,"k":[350,350]},"r":{"a":0,"k":0},"o":{"a":0,"k":100},"sk":{"a":0,"k":0},"sa":{"a":0,"k":0},"nm":"Transform"}],"nm":"check","bm":0,"hd":false}],"ip":0,"op":90,"st":0,"bm":0},{"ddd":0,"ind":2,"ty":4,"nm":"circle","sr":1,"ks":{"o":{"a":0,"k":100},"r":{"a":0,"k":0},"p":{"a":0,"k":[32,32,0]},"a":{"a":0,"k":[0,0,0]},"s":{"a":0,"k":[33.333,33.333,100]}},"ao":0,"shapes":[{"ty":"gr","it":[{"d":1,"ty":"el","s":{"a":0,"k":[53,53]},"p":{"a":0,"k":[0,0]},"nm":"Ellipse Path 1","hd":false},{"ty":"tm","s":{"a":0,"k":0},"e":{"a":1,"k":[{"i":{"x":[0.34],"y":[1]},"o":{"x":[0.66],"y":[0]},"t":0,"s":[0]},{"t":77,"s":[100]}]},"o":{"a":1,"k":[{"i":{"x":[0.34],"y":[1]},"o":{"x":[0.66],"y":[0]},"t":0,"s":[-360]},{"t":77,"s":[0]}]},"m":1,"nm":"Trim Paths 1","hd":false},{"ty":"st","c":{"a":0,"k":[0.119997918606,0.750781238079,0.458097785711,1]},"o":{"a":0,"k":100},"w":{"a":0,"k":3},"lc":2,"lj":1,"ml":4,"bm":0,"nm":"Stroke 1","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0]},"a":{"a":0,"k":[0,0]},"s":{"a":0,"k":[300,300]},"r":{"a":0,"k":0},"o":{"a":0,"k":100},"sk":{"a":0,"k":0},"sa":{"a":0,"k":0},"nm":"Transform"}],"nm":"circle","bm":0,"hd":false}],"ip":0,"op":90,"st":0,"bm":0}],"markers":[]}

**Comment by Jdb156158** [comment]
最后找到解决办法了吗

**Comment by rajivd15** [comment]
No Solution yet on this! We ended up not using Lottie.
