### ISSUE TITLE
how can i assigning res Image custom path for Animation?

### ISSUE THREAD

**Issue by liuzhiyi1992** [airbnb/lottie-ios#207]
how can i assigning .json and res image in custom filepath outsize project bundle，like app document path.

**Comment by yanchaoGan** [comment]
just like this.

- (LOTAnimationView *)animateView
{
    if (!_animateView) {
        
        NSString *jsonFilePath = your json file path;
        NSData *data = [NSData dataWithContentsOfFile:jsonFilePath];
        NSDictionary *jsonDic = [NSJSONSerialization JSONObjectWithData:data options:NSJSONReadingMutableLeaves error:nil];
        
        LOTAnimationView  *animate = [LOTAnimationView  animationFromJSON:jsonDic];
        _animateView = animate;
        animate.frame = (CGRect){0,0,self.view.bounds.size.width, self.view.bounds.size.height};
        animate.contentMode = UIViewContentModeScaleAspectFit;
    }
    return _animateView;
}
