### ISSUE TITLE
Animation Content Mode not being respected using UIViewRepresentable

### ISSUE THREAD

**Issue by mitjacendak** [airbnb/lottie-ios#2070]
Hello,
When using UIViewRepresentable, `contentMode` doesn't seem to be respected. `animationView.maskAnimationToBounds` doesn't help either. The issue can be seen on any animation.

## Which Version of Lottie are you using?

Lottie 4.2.0

## Expected Behavior 
![IMG_2767](https://github.com/airbnb/lottie-ios/assets/99665127/5e11e4cd-6377-42f5-88b1-9f6cdb9f56c1)

## Actual Behavior
![IMG_2765](https://github.com/airbnb/lottie-ios/assets/99665127/a7c2d59b-3a9b-4e6a-9f4e-0c8e124bdf93)

## Code Example & Animation Used
The animation used in the example was: https://lottiefiles.com/97240-success

```Swift
struct LottieView: UIViewRepresentable {
    func startAnimation(_ animationView: LottieAnimationView, animation: LottieAnimation, loopMode: LottieLoopMode) {
        animationView.animation = animation
        animationView.loopMode = loopMode
        animationView.play()
    }

    func makeUIView(context: Context) -> LottieAnimationView {
        let animationView = LottieAnimationView(animation: LottieAnimation.asset("success"))
        animationView.contentMode = .scaleAspectFit
        animationView.play()

        return animationView
    }

    func updateUIView(_ animationView: UIViewType, context: Context) {}
}
```

It's possible to bypass this issue by doing:
```Swift
    func makeUIView(context: Context) -> UIView {
        let view = UIView(frame: .zero)

        let animationView = LottieAnimationView(animation: LottieAnimation.asset("success"))
        animationView.translatesAutoresizingMaskIntoConstraints = false
        
        view.addSubview(animationView)
        
        NSLayoutConstraint.activate([
            animationView.topAnchor.constraint(equalTo: view.topAnchor),
            animationView.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            animationView.bottomAnchor.constraint(equalTo: view.bottomAnchor),
            animationView.trailingAnchor.constraint(equalTo: view.trailingAnchor)
        ])
        
        return view
    }
```

**Comment by mitjacendak** [comment]
CC: @harishramu as he had the same/similar issue.

**Comment by calda** [comment]
We've added a new first-party `LottieView` on `master`, and are supporting that moving forwards. Since this uses a custom Lottie <-> SwiftUI implementation rather than the first-party solution , I'm going to close it for now. Feel free to open a new issue if you try this with the new `LottieView` and it still doesn't work as expected.
