### ISSUE TITLE
Getting warning in latest update pod Version 4.2.0

### ISSUE THREAD

**Issue by Spatel91111** [airbnb/lottie-ios#2071]
I have updated the latest pod below:

Installing lottie-ios 4.2.0 (was 4.1.3)

After the update, there is displayed one warning as below

no rule to process file '/.../Pods/lottie-ios/Sources/Private/Model/DotLottie/ZipFoundation/README.md' of type 'net.daringfireball.markdown' for architecture 'arm64'

**Comment by calda** [comment]
This is fixed on master as of https://github.com/airbnb/lottie-ios/pull/2057, so you could resolve this by pointing your podfile to `master` instead of 4.2.0.

**Comment by vg-identance** [comment]
@calda when release is planned?

**Comment by calda** [comment]
The next release will include the new SwiftUI LottieView, and there are still some additional changes I need to make on that before it's ready to be released.

**Comment by calda** [comment]
Given this is fixed on master, and we plan on releasing a new version soon (maybe when Xcode 15 is released), I'm going to go ahead and close this issue.
