### ISSUE TITLE
Bug - Animated Transitions Demo 

### ISSUE THREAD

**Issue by SilenceZhou** [airbnb/lottie-ios#208]
Why is the height and width of the animation changed when it comes to the animation?

![Uploading 图片.png…]()

**Comment by SilenceZhou** [comment]
![Uploading Snip20170407_2.png…]()

**Comment by SilenceZhou** [comment]
Look forward to your reply

**Comment by SilenceZhou** [comment]
![snip20170407_2](https://cloud.githubusercontent.com/assets/9305458/24792572/368c4cae-1bb1-11e7-87a5-a67825e5991c.png)

**Comment by SilenceZhou** [comment]
Look forward to your reply

**Comment by darkesfang** [comment]
Hi, I found that after controller transition animation, the bounds of presented view remained unchanged(not matched with screen). It might be the same issue as this one.

**Comment by iDevo** [comment]
Same here using the sample lines of code. 
Does anyone knows a workaround for this glitch?

Thanks in advance! 

`#pragma mark -- View Controller Transitioning

- (id<UIViewControllerAnimatedTransitioning>)animationControllerForPresentedController:(UIViewController *)presented
                                                                  presentingController:(UIViewController *)presenting
                                                                      sourceController:(UIViewController *)source {
    LOTAnimationTransitionController *animationController = [[LOTAnimationTransitionController alloc] initWithAnimationNamed:@"vcTransition1"
                                                                                                              fromLayerNamed:@"outLayer"
                                                                                                                toLayerNamed:@"inLayer"];
    return animationController;
}

- (id<UIViewControllerAnimatedTransitioning>)animationControllerForDismissedController:(UIViewController *)dismissed {
    LOTAnimationTransitionController *animationController = [[LOTAnimationTransitionController alloc] initWithAnimationNamed:@"vcTransition2"
                                                                                                              fromLayerNamed:@"outLayer"
                                                                                                                toLayerNamed:@"inLayer"];
    return animationController;
}
`
