### ISSUE TITLE
Lottie Snapshot testing layout issue

### ISSUE THREAD

**Issue by paul-weichhart** [airbnb/lottie-ios#2080]
Hello everybody!

I'm currently struggling getting the latest Lottie Version to work with FBSnapshotVerifyView. We recently switched to Version 4 (from 2) & now all Snapshot tests are red because of a layout issue. We are using Autolayout & while the layout is working just fine in the running App, all LottieAnimationViews are black & misplaced while running the Tests. I suspect a View lifecycle event to be necessary to call for the rendering but I wasn't able to nail it down.

Thanks a lot for sharing any insights that might help fixing this!

## Which Version of Lottie are you using?

Lottie 4.2.0

## Expected Behavior 
![reference_test_no_selection_light@3x](https://github.com/airbnb/lottie-ios/assets/133361491/f9045a78-9694-4a65-b8ae-39dad776f04f)
Emojies are rendered as before

## Actual Behavior
![Snapshot](https://github.com/airbnb/lottie-ios/assets/133361491/84282aed-e10c-4bcd-9cca-5f4c8cb9fc04)

## Animation JSON
{"v":"5.7.4","fr":29.9700012207031,"ip":0,"op":72.0000029326201,"w":800,"h":800,"nm":"excited","ddd":0,"assets":[],"layers":[{"ddd":0,"ind":1,"ty":4,"nm":"Teeth","parent":2,"sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[0,-7.194,0],"ix":2,"l":2},"a":{"a":0,"k":[0,0,0],"ix":1,"l":2},"s":{"a":0,"k":[100,102.765,100],"ix":6,"l":2}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":1,"k":[{"i":{"x":0.667,"y":0.668},"o":{"x":0.62,"y":0},"t":7,"s":[{"i":[[0,0],[-91,0],[0,0],[57.5,0]],"o":[[0,0],[91,0],[0,0],[-57.5,0]],"v":[[-139.5,84],[2,142.5],[148,82.5],[2,96]],"c":true}]},{"i":{"x":1,"y":1},"o":{"x":0,"y":0},"t":24,"s":[{"i":[[0,0],[-91,0],[0,0],[57.5,0]],"o":[[0,0],[91,0],[0,0],[-57.5,0]],"v":[[-139.5,84],[2,153.5],[148,82.5],[2,96]],"c":true}]},{"i":{"x":0.378,"y":1},"o":{"x":0.333,"y":0.332},"t":47,"s":[{"i":[[0,0],[-91,0],[0,0],[57.5,0]],"o":[[0,0],[91,0],[0,0],[-57.5,0]],"v":[[-139.5,84],[2,153.5],[148,82.5],[2,96]],"c":true}]},{"t":62.0000025253118,"s":[{"i":[[0,0],[-91,0],[0,0],[57.5,0]],"o":[[0,0],[91,0],[0,0],[-57.5,0]],"v":[[-139.5,84],[2,142.5],[148,82.5],[2,96]],"c":true}]}],"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"rd","nm":"Round Corners 1","r":{"a":0,"k":19,"ix":1},"ix":2,"mn":"ADBE Vector Filter - RC","hd":false},{"ty":"st","c":{"a":0,"k":[0.156862999411,0.180391992307,0.211765005074,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":0,"ix":5},"lc":1,"lj":1,"ml":4,"bm":0,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"fl","c":{"a":0,"k":[1,1,1,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Shape 1","np":4,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":90.0000036657751,"st":0,"bm":0},{"ddd":0,"ind":2,"ty":4,"nm":"Bottom Mouth","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":1,"k":[{"i":{"x":0.667,"y":0.906},"o":{"x":0.718,"y":0},"t":7,"s":[400,402.5,0],"to":[0,-6,0],"ti":[0,7.667,0]},{"i":{"x":1,"y":1},"o":{"x":0,"y":0},"t":24,"s":[400,366.5,0],"to":[0,-7.667,0],"ti":[0,-6,0]},{"i":{"x":0.237,"y":1},"o":{"x":0.333,"y":0.066},"t":47,"s":[400,356.5,0],"to":[0,6,0],"ti":[0,-7.667,0]},{"t":62.0000025253118,"s":[400,402.5,0]}],"ix":2,"l":2},"a":{"a":0,"k":[0,0,0],"ix":1,"l":2},"s":{"a":0,"k":[100,97.309,100],"ix":6,"l":2}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":1,"k":[{"i":{"x":0.667,"y":0.669},"o":{"x":0.63,"y":0},"t":7,"s":[{"i":[[75.5,0],[0,0],[-159.501,0],[0,0]],"o":[[-75.5,0],[0,0],[158.5,0],[0,0]],"v":[[0,64.5],[-186,40],[0.5,223],[192.5,40.5]],"c":true}]},{"i":{"x":1,"y":1},"o":{"x":0,"y":0},"t":24,"s":[{"i":[[75.5,0],[0,0],[-173.5,0],[0,0]],"o":[[-75.5,0],[0,0],[176.5,0],[0,0]],"v":[[0,64.5],[-186,40],[0.5,238.415],[192.5,40.5]],"c":true}]},{"i":{"x":0.391,"y":1},"o":{"x":0.333,"y":0.334},"t":47,"s":[{"i":[[75.5,0],[0,0],[-173.5,0],[0,0]],"o":[[-75.5,0],[0,0],[176.5,0],[0,0]],"v":[[0,64.5],[-186,40],[0.5,238.415],[192.5,40.5]],"c":true}]},{"t":62.0000025253118,"s":[{"i":[[75.5,0],[0,0],[-159.501,0],[0,0]],"o":[[-75.5,0],[0,0],[158.5,0],[0,0]],"v":[[0,64.5],[-186,40],[0.5,223],[192.5,40.5]],"c":true}]}],"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"rd","nm":"Round Corners 1","r":{"a":0,"k":24,"ix":1},"ix":2,"mn":"ADBE Vector Filter - RC","hd":false},{"ty":"st","c":{"a":0,"k":[0.156862999411,0.180391992307,0.211765005074,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":0,"ix":5},"lc":1,"lj":1,"ml":4,"bm":0,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"fl","c":{"a":0,"k":[0.156862999411,0.180391992307,0.211765005074,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Shape 1","np":4,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":90.0000036657751,"st":0,"bm":0},{"ddd":0,"ind":3,"ty":4,"nm":"Right Star","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":10,"ix":10},"p":{"a":1,"k":[{"i":{"x":0.667,"y":0.889},"o":{"x":0.802,"y":0},"t":7,"s":[549.5,240.25,0],"to":[1.5,-4.667,0],"ti":[-2.167,6.333,0]},{"i":{"x":1,"y":1},"o":{"x":0,"y":0},"t":21,"s":[558.5,212.25,0],"to":[2.167,-6.333,0],"ti":[1.5,-4.667,0]},{"i":{"x":0.288,"y":1},"o":{"x":0.333,"y":0.087},"t":47,"s":[562.5,202.25,0],"to":[-1.5,4.667,0],"ti":[2.167,-6.333,0]},{"t":62.0000025253118,"s":[549.5,240.25,0]}],"ix":2,"l":2},"a":{"a":0,"k":[-132.5,-166.75,0],"ix":1,"l":2},"s":{"a":1,"k":[{"i":{"x":[0.688,0.688,0.667],"y":[0.927,0.927,1]},"o":{"x":[0.796,0.796,0.333],"y":[0,0,0]},"t":7,"s":[100,100,100]},{"i":{"x":[1,1,0.667],"y":[1,1,1]},"o":{"x":[0,0,0.333],"y":[0,0,0]},"t":21,"s":[106,106,100]},{"i":{"x":[0.238,0.238,0.667],"y":[1,1,1]},"o":{"x":[0.333,0.333,0.333],"y":[0,0,0]},"t":47,"s":[108,108,100]},{"t":62.0000025253118,"s":[100,100,100]}],"ix":6,"l":2}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[-176.5,-214],[-207,-128.5],[-230.376,-11.627],[-132.5,-74.5],[-58.5,-128],[29.148,-202.406],[-86.5,-215]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"rd","nm":"Round Corners 1","r":{"a":0,"k":40,"ix":1},"ix":2,"mn":"ADBE Vector Filter - RC","hd":false},{"ty":"st","c":{"a":0,"k":[0.156862999411,0.180391992307,0.211765005074,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":0,"ix":5},"lc":1,"lj":1,"ml":4,"bm":0,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"fl","c":{"a":0,"k":[0.945098039216,0.407843137255,0.129411764706,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Shape 3","np":4,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false},{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[-130.206,-321.931],[-176.5,-214],[-207,-128.5],[-230.376,-11.627],[-132.5,-74.5],[-58.5,-128],[-86.5,-215]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"rd","nm":"Round Corners 1","r":{"a":0,"k":40,"ix":1},"ix":2,"mn":"ADBE Vector Filter - RC","hd":false},{"ty":"st","c":{"a":0,"k":[0.156862999411,0.180391992307,0.211765005074,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":0,"ix":5},"lc":1,"lj":1,"ml":4,"bm":0,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"fl","c":{"a":0,"k":[0.945098039216,0.407843137255,0.129411764706,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Shape 2","np":4,"cix":2,"bm":0,"ix":2,"mn":"ADBE Vector Group","hd":false},{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[-176.5,-214],[-290.702,-206.117],[-207,-128.5],[-132.5,-74.5],[-29.391,-12.672],[-58.5,-128],[-86.5,-215]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"rd","nm":"Round Corners 1","r":{"a":0,"k":40,"ix":1},"ix":2,"mn":"ADBE Vector Filter - RC","hd":false},{"ty":"st","c":{"a":0,"k":[0.156862999411,0.180391992307,0.211765005074,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":0,"ix":5},"lc":1,"lj":1,"ml":4,"bm":0,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"fl","c":{"a":0,"k":[0.945098039216,0.407843137255,0.129411764706,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Shape 1","np":4,"cix":2,"bm":0,"ix":3,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":90.0000036657751,"st":0,"bm":0},{"ddd":0,"ind":4,"ty":4,"nm":"Left Star","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":-10,"ix":10},"p":{"a":1,"k":[{"i":{"x":0.667,"y":0.889},"o":{"x":0.802,"y":0},"t":7,"s":[248.5,240.25,0],"to":[-1.5,-4.667,0],"ti":[1.5,6.333,0]},{"i":{"x":1,"y":1},"o":{"x":0,"y":0},"t":21,"s":[239.5,212.25,0],"to":[-1.5,-6.333,0],"ti":[-1.5,-4.667,0]},{"i":{"x":0.288,"y":1},"o":{"x":0.333,"y":0.089},"t":47,"s":[239.5,202.25,0],"to":[1.5,4.667,0],"ti":[-1.5,-6.333,0]},{"t":62.0000025253118,"s":[248.5,240.25,0]}],"ix":2,"l":2},"a":{"a":0,"k":[-132.5,-166.75,0],"ix":1,"l":2},"s":{"a":1,"k":[{"i":{"x":[0.688,0.688,0.667],"y":[0.927,0.927,1]},"o":{"x":[0.796,0.796,0.333],"y":[0,0,0]},"t":7,"s":[100,100,100]},{"i":{"x":[1,1,0.667],"y":[1,1,1]},"o":{"x":[0,0,0.333],"y":[0,0,0]},"t":21,"s":[106,106,100]},{"i":{"x":[0.238,0.238,0.667],"y":[1,1,1]},"o":{"x":[0.333,0.333,0.333],"y":[0,0,0]},"t":47,"s":[108,108,100]},{"t":62.0000025253118,"s":[100,100,100]}],"ix":6,"l":2}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[-176.5,-214],[-207,-128.5],[-230.376,-11.627],[-132.5,-74.5],[-58.5,-128],[29.148,-202.406],[-86.5,-215]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"rd","nm":"Round Corners 1","r":{"a":0,"k":40,"ix":1},"ix":2,"mn":"ADBE Vector Filter - RC","hd":false},{"ty":"st","c":{"a":0,"k":[0.156862999411,0.180391992307,0.211765005074,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":0,"ix":5},"lc":1,"lj":1,"ml":4,"bm":0,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"fl","c":{"a":0,"k":[0.945098039216,0.407843137255,0.129411764706,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Shape 3","np":4,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false},{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[-130.206,-321.931],[-176.5,-214],[-207,-128.5],[-230.376,-11.627],[-132.5,-74.5],[-58.5,-128],[-86.5,-215]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"rd","nm":"Round Corners 1","r":{"a":0,"k":40,"ix":1},"ix":2,"mn":"ADBE Vector Filter - RC","hd":false},{"ty":"st","c":{"a":0,"k":[0.156862999411,0.180391992307,0.211765005074,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":0,"ix":5},"lc":1,"lj":1,"ml":4,"bm":0,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"fl","c":{"a":0,"k":[0.945098039216,0.407843137255,0.129411764706,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Shape 2","np":4,"cix":2,"bm":0,"ix":2,"mn":"ADBE Vector Group","hd":false},{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[-176.5,-214],[-290.702,-206.117],[-207,-128.5],[-132.5,-74.5],[-29.391,-12.672],[-58.5,-128],[-86.5,-215]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"rd","nm":"Round Corners 1","r":{"a":0,"k":40,"ix":1},"ix":2,"mn":"ADBE Vector Filter - RC","hd":false},{"ty":"st","c":{"a":0,"k":[0.156862999411,0.180391992307,0.211765005074,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":0,"ix":5},"lc":1,"lj":1,"ml":4,"bm":0,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"fl","c":{"a":0,"k":[0.945098039216,0.407843137255,0.129411764706,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Shape 1","np":4,"cix":2,"bm":0,"ix":3,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":90.0000036657751,"st":0,"bm":0},{"ddd":0,"ind":5,"ty":4,"nm":"Face","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[400,400,0],"ix":2,"l":2},"a":{"a":0,"k":[0,0,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"shapes":[{"ty":"gr","it":[{"d":1,"ty":"el","s":{"a":0,"k":[600,600],"ix":2},"p":{"a":0,"k":[0,0],"ix":3},"nm":"Ellipse Path 1","mn":"ADBE Vector Shape - Ellipse","hd":false},{"ty":"st","c":{"a":0,"k":[1,1,1,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":0,"ix":5},"lc":1,"lj":1,"ml":4,"bm":0,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"fl","c":{"a":0,"k":[1,0.78431372549,0.172549019608,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0.659,0.368],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Ellipse 1","np":3,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":90.0000036657751,"st":0,"bm":0}],"markers":[{"tm":7.00000028511585,"cm":"Start Animation\r","dr":0},{"tm":20.0000008146167,"cm":"Start Build Up\r","dr":0},{"tm":39.0000015885026,"cm":"End Build Up","dr":0},{"tm":53.0000021587343,"cm":"Start Fade Out\r","dr":0},{"tm":65.0000026475043,"cm":"End Animation","dr":0}]}

**Comment by paul-weichhart** [comment]
Some of the approaches I already tried:
* calling `layoutIfNeeded` & `layoutSubviews`
* Adding the View to a ViewController & calling `loadViewIfNeeded`,  `beginAppearanceTransition` & `endAppearanceTransition`
* Adding the ViewController to a Window & calling all of the above including `makeKeyAndVisible`

**Comment by calda** [comment]
This is a known limitation of the Core Animation rendering engine. We have more discussion, including about workarounds, here: https://github.com/airbnb/lottie-ios/discussions/1769#discussioncomment-3860672
