### ISSUE TITLE
JSON File not working

### ISSUE THREAD

**Issue by milanivarni** [airbnb/lottie-ios#21]
@buba447 
Awesome Library, thanks for sharing it with us!

From After Effect, I generated JSON File with the help of [https://github.com/bodymovin/bodymovin#bodymovin](url), It gave me two files one is **data.json** file and second is **img.png** file.

Then due to issue of [Cocoapods](https://github.com/airbnb/lottie-ios/issues/4#issuecomment-277196717), I included these two files in Example Provided by this library.
In this project, I changed in **LottieRootViewController**,

`- (void)viewDidLoad {`
 ` [super viewDidLoad];`
   ...........
`self.lottieLogo = [LAAnimationView animationNamed:@"data copy"]; //was LottieLogo1
  self.lottieLogo.contentMode = UIViewContentModeScaleAspectFill;`
`[self.view addSubview:self.lottieLogo];`

But, didn't working.
**Provide some proper guidance, how actually this works?**

Here is two files: 
[data copy.txt](https://github.com/airbnb/lottie-ios/files/750039/data.copy.txt)

**change its extension from data copy.txt -> data copy.json**

and below is .png file,

![img_0](https://cloud.githubusercontent.com/assets/22673922/22586673/1b2fe0d8-ea24-11e6-8b10-9c822e681fd7.png)

**Comment by buba447** [comment]
Hello!
Currently we don't support import image assets. This is something we're working on though. 
This image could be made with shape layers though, which is what Lottie mainly animates.

**Comment by YugandharVadlamudi** [comment]
This is not working i placed .json it is throughing exception
