### ISSUE TITLE
play(fromFrame:toFrame:) doesn't stop at end frame with CA rendering engine

### ISSUE THREAD

**Issue by nathansalaun-sofia** [airbnb/lottie-ios#2106]
## Which Version of Lottie are you using?

Lottie 4.2.0

## Expected Behavior 
When calling `play(fromFrame:toFrame:completion:)`, I expect Lottie to play the animation in the given frames range and call the completion callback when it ends. This works fine with the main thread rendering engine but as soon as I switch to CA it breaks.

## Actual Behavior
The animation plays from the beginning to the end, never stopping at the requested end frame. The completion callback is also never called.

## Animation JSON
Sadly I can't share our animation file 🙁

**Comment by calda** [comment]
Can you please share a sample Xcode project that demonstrates this issue? Thanks!

**Comment by siddharth952** [comment]
Was able to reproduce this.
Seems to occurring if we use the mainThread rendering engine
`LottieConfiguration.shared.renderingEngine = .mainThread`

We would need to use a lottie which has two states eg:
1. Processing State (Frame: 0 to 100) This would be in autoReverse **LottieLoopMode**
2. Final State (Frame: 101 - 200) This would be in playOnce  **LottieLoopMode**

Now we use the following code to play from an specific frame range:
```
private func playAnimation(){
        animationView.animationSpeed = 1
        if fromFrame >= 0 {
            animationView.play(fromFrame: fromFrame ,toFrame: toFrame, loopMode: loopMode) { _ in }
        } else {
            animationView.loopMode = loopMode
            animationView.play { _ in }
        }
    }
    
```
