### ISSUE TITLE
no rule to process file

### ISSUE THREAD

**Issue by Muthu1133** [airbnb/lottie-ios#2112]
Hi,

Getting this warning after recent pod update. Let me know once fixed.

Showing Recent Messages
no rule to process file '/Users/developer/Appsolute/bref-ios-develop/Pods/lottie-ios/Sources/Private/Model/DotLottie/ZipFoundation/README.md' of type 'net.daringfireball.markdown' for architecture 'arm64'

**Comment by calda** [comment]
Tracking this issue here: https://github.com/airbnb/lottie-ios/issues/2071

It will be fixed in the next release.

**Comment by luispadron** [comment]
Any update on a new release 🙏🏼
