### ISSUE TITLE
The list of compatibility issues is empty 

### ISSUE THREAD

**Issue by claustrofob** [airbnb/lottie-ios#2114]
Trying to debug animation rendering got this messages:
```
Encountered Core Animation compatibility issues while setting up animation:


This animation cannot be rendered correctly by the Core Animation engine.
To resolve this issue, you can use `RenderingEngineOption.automatic`, which automatically falls back
to the Main Thread rendering engine when necessary, or just use `RenderingEngineOption.mainThread`.
```

Seems like it must be one issue in there but its `description` is empty.

[animation_sample.json.zip](https://github.com/airbnb/lottie-ios/files/12136068/animation_sample.json.zip)

## Which Version of Lottie are you using?

Lottie 4.2.0

**Comment by calda** [comment]
When I run the linked animation on master, it plays correctly with the core animation rendering engine and doesn't need to fall back to the main thread rendering engine. If there was an issue in 4.2.0, it seems to be fixed now.
