### ISSUE TITLE
OC 项目打开 swift error后 抛异常

### ISSUE THREAD

**Issue by everyStudyNow** [airbnb/lottie-ios#2115]
extension LottieVector3D: AnyInitializable {

  init(value: Any) throws {
    guard var array = value as? [Double] else {
      throw InitializableError.invalidInput
    }
    x = array.count > 0 ? array.removeFirst() : 0
    y = array.count > 0 ? array.removeFirst() : 0
    z = array.count > 0 ? array.removeFirst() : 0
  }

}
直接走到这行代码 throw InitializableError.invalidInput 抛出异常 但是跳过异常后 动画还可以正常显示

**Comment by xiongqg** [comment]
I have the same problem too, Did you solve it?

**Comment by Ru5C55an** [comment]
I have the same issue!
