### ISSUE TITLE
Looping and currentProgress creates race condition

### ISSUE THREAD

**Issue by denandreychuk** [airbnb/lottie-ios#2123]
When we use looping with 'currentProgress' modifiers, and 'currentProgress' is set to 0, the animation plays for a few seconds before pausing.

Here's the logic I'm trying to implement:

- The animation progress is set to 0.
- The user presses the play button.
- The animation starts playing.
- When the user presses the stop button, the animation pauses and reverts back to 0.

Code in context of LazyVStack with a lot of animations:

>         LottieView {
>             try await DotLottieFile.named(someAnimation)
>         }
>         .looping()
>         .resizable()
>         .loadAnimationTrigger(.constant(isPlaying))
>         .currentProgress(isPlaying ? nil : 0)

Also, is there a specific reason to use Binding for 'loadAnimationTrigger' instead of any Equatable type?

Ideally, this is what is expected from the API:
- The animation respects the 'currentProgress' modifier. If it's set to a specific value, it should disregard the looping modifier.
- If we change 'currentProgress' from a value to nil and a looping modifier is present, the animation should revert back to looping.

**Comment by calda** [comment]
Thanks for the report. Could you share a small sample project that demonstrates this issue? That would be really helpful. Then I'll take a look at fixing the issue.

**Comment by calda** [comment]
I think I understand your issue though so I should be able to fix it without a sample project.

**Comment by calda** [comment]
Here's a fix: https://github.com/airbnb/lottie-ios/pull/2128
