### ISSUE TITLE
Some animation are broken in lottie-ios 4.2.0 with hardware acceleration

### ISSUE THREAD

**Issue by AndreiBehel** [airbnb/lottie-ios#2130]
Hello. I have problem with my lottie animation. I'm using react native and [lottie-react-native](https://github.com/lottie-react-native/lottie-react-native). After update to major version which brings lottie-ios 4.2.0 some lottie animations become broken. The maintaener provided workaround https://github.com/lottie-react-native/lottie-react-native/issues/1082#issuecomment-1668227272 to set software acceleration mode.
Is it possible to fix this issue with hardware acceleration?

## Which Version of Lottie are you using?

Lottie 4.2.0

## Expected Behavior 

https://github.com/airbnb/lottie-ios/assets/16404722/7100242c-127a-45aa-9005-c45497a38d98

## Actual Behavior

https://github.com/airbnb/lottie-ios/assets/16404722/4f2ae5c9-6788-430e-bde9-ade17feb1af3

## Animation JSON
<details>
  <summary>lottie.json</summary>
{"v":"5.6.6","ip":0,"op":160,"fr":60,"w":70,"h":70,"assets":[],"layers":[{"ind":386,"nm":"surface1542","ao":0,"ip":0,"op":264,"st":0,"ty":4,"ks":{"ty":"tr","o":{"k":100},"r":{"k":0},"p":{"k":[0,0]},"a":{"k":[0,0]},"s":{"k":[133.33,133.33]},"sk":{"k":0},"sa":{"k":0}},"shapes":[{"ty":"gr","hd":false,"nm":"surface1542","it":[{"ty":"gr","hd":false,"it":[{"ty":"sh","ks":{"k":{"i":[[0,0],[-1.24,0],[0,-1.24],[0,0],[0.92,-0.51],[0,0],[0.59,1.05],[-1.05,0.59],[0,0]],"o":[[0,-1.24],[1.24,0],[0,0],[0.32,0.96],[0,0],[-1.05,0.59],[-0.59,-1.04],[0,0],[0,0]],"v":[[24.75,12],[27,9.75],[29.25,12],[29.25,25.76],[28.25,28.32],[15.23,35.62],[12.27,34.78],[13.11,31.83],[24.75,25.3]],"c":true}}},{"ty":"sh","ks":{"k":{"i":[[0,0],[0,0.68],[0.69,0],[0,-0.69],[-0.68,0]],"o":[[0.69,0],[0,-0.69],[-0.68,0],[0,0.68],[0,0]],"v":[[26.84,27.82],[28.08,26.57],[26.84,25.33],[25.6,26.57],[26.84,27.82]],"c":true}}},{"ty":"fl","o":{"a":1,"k":[{"i":{"x":[0.67],"y":[1]},"o":{"x":[0.33],"y":[0]},"t":59,"s":[0]},{"t":109,"s":[100]}],"ix":5},"c":{"k":[0.29,0.75,0.69,1]}},{"ty":"tr","o":{"k":100},"r":{"k":0},"p":{"k":[0,0]},"a":{"k":[0,0]},"s":{"k":[100,100]},"sk":{"k":0},"sa":{"k":0},"hd":false}]},{"ty":"gr","hd":false,"it":[{"ty":"sh","ks":{"k":{"i":[[0,0],[3.11,0],[0,3.11],[-3.11,0],[0,-3.11]],"o":[[0,3.11],[-3.11,0],[0,-3.11],[3.11,0],[0,0]],"v":[[32.25,26.62],[26.62,32.25],[21,26.62],[26.62,21],[32.25,26.62]],"c":false}}},{"ty":"fl","o":{"a":1,"k":[{"i":{"x":[0.67],"y":[1]},"o":{"x":[0.33],"y":[0]},"t":59,"s":[0]},{"t":109,"s":[30]}],"ix":5},"c":{"k":[0.29,0.75,0.69,1]}},{"ty":"tr","o":{"k":100},"r":{"k":0},"p":{"k":[0,0]},"a":{"k":[0,0]},"s":{"k":[100,100]},"sk":{"k":0},"sa":{"k":0},"hd":false}]},{"ty":"gr","hd":false,"it":[{"ty":"sh","ks":{"k":{"i":[[0,0],[18.78,0],[0,18.78],[-18.78,0],[0,-18.78]],"o":[[0,18.78],[-18.78,0],[0,-18.78],[18.78,0],[0,0]],"v":[[69,35],[35,69],[1,35],[35,1],[69,35]],"c":false}}},{"ty":"st","lc":1,"lj":1,"ml":4,"o":{"k":100},"w":{"k":2},"c":{"k":[0.29,0.75,0.69,1]},"hd":false},{"ty":"tr","o":{"k":100},"r":{"k":0},"p":{"k":[0,0]},"a":{"k":[0,0]},"s":{"k":[75,75]},"sk":{"k":0},"sa":{"k":0},"hd":false}]},{"ty":"tr","o":{"k":100},"r":{"k":0},"p":{"k":[0,0]},"a":{"k":[0,0]},"s":{"k":[100,100]},"sk":{"k":0},"sa":{"k":0},"hd":false}]},{"ty":"tm","s":{"a":0,"k":0,"ix":1},"e":{"a":1,"k":[{"i":{"x":[0.27],"y":[1]},"o":{"x":[0.5],"y":[0]},"t":0,"s":[0]},{"t":66,"s":[100]}],"ix":2},"o":{"a":0,"k":0,"ix":3},"m":1,"ix":2,"hd":false}]}],"meta":{"g":"LF SVG to Lottie"}}
</details>

**Comment by matinzd** [comment]
Same issue [here](https://github.com/airbnb/lottie-ios/issues/2085) as well. It seems a regression on iOS.

**Comment by calda** [comment]
Thanks for the report, here's a fix: https://github.com/airbnb/lottie-ios/pull/2156

**Comment by matinzd** [comment]
> Thanks for the report, here's a fix: https://github.com/airbnb/lottie-ios/pull/2156

Is there any plan to release new version for iOS?

**Comment by calda** [comment]
Yes, soon :)
