### ISSUE TITLE
Support for VisionOS

### ISSUE THREAD

**Issue by daniele-pizziconi** [airbnb/lottie-ios#2137]
### Discussed in https://github.com/airbnb/lottie-ios/discussions/2096

<div type='discussions-op-text'>

<sup>Originally posted by **phiren** June 30, 2023</sup>
Project not building even for Phone target due to UIScreen & Haptic Feedback API.
Small fixes will make whole library usable for VisionOS.
</div>

An attempt was done here: https://github.com/airbnb/lottie-ios/pull/2100

**Comment by calda** [comment]
There is an existing discussion about this here: https://github.com/airbnb/lottie-ios/discussions/2096 PRs welcome!
