### ISSUE TITLE
Lottie iOS rendering appears pixelated

### ISSUE THREAD

**Issue by mthole** [airbnb/lottie-ios#214]
I'm experimenting with using Lottie for the first time, and am pretty excited about it. Right now I'm using it to implement a simple bouncing map marker animation, and the iOS rendering is appearing more pixelated than expected:

**iOS rendering:**
![image](https://cloud.githubusercontent.com/assets/11229/24973803/ff472044-1f74-11e7-8e17-3f67a4c5be64.png)
(this is rendering at 64x64pt, per the JSON definition; @2x)

**Bodymovin HTML rendering **
![image](https://cloud.githubusercontent.com/assets/11229/24974053/da5831a0-1f75-11e7-8ccc-7b7b0000bab0.png)
(forced the view to be 128x128px here to match sizes)

It looks like the anti-aliasing is better on the HTML rendering. Is it possible that the iOS rendering is rendering everything at 64x64px, rather than point, and thus upscaling 2x?

HTML output:
https://gist.github.com/mthole/660096674907725ba265b7dd2ba5fb29

JSON output:
https://gist.github.com/mthole/a2df34b8cb6b093181ac082cbdad92a4

**Comment by teichhorstGB** [comment]
This is happening to us as well.  On Android and web browsers it looks great.  iOS has pixelation and it doesn't look so great.

**Comment by samiam2017** [comment]
I'm having the same issue animation looks smooth on the Android Emulator and Web but iOS is pixelated. Any help would be appreciated.

**Comment by buba447** [comment]
Have you tried on device?

**Comment by samiam2017** [comment]
@buba447 It does look cleaner on device. Thanks!

**Comment by randyho-kk** [comment]
We're seeing this also and is happening on device.  Anyone have ideas on how we can fix or work around it?

**Comment by michaelgum** [comment]
We are having the same issue. While it does look cleaner on device than it does in the XCode simulator, it still has some jagged edges / looks pixelated.

**Comment by skdevil** [comment]
This issue still exists. On web preview, it looks sharp but on the real device, it is pixelated.

**Comment by astrokin** [comment]
I've the same issue

**Comment by minimoz** [comment]
Same issue here, the animation is supposed to be vectorized but it's still pixelated on iOS only

**Comment by baezf** [comment]
Same issue.

**Comment by jhughes696** [comment]
@buba447 Hey I'm having a similar issue.  I'm seeing pixelation on iOS animations using LottieFiles App: Player Version 3.3.0 

It's weird because some shapes are pixelated, some are sharp: 

<img width="462" alt="image" src="https://user-images.githubusercontent.com/50207823/184707687-20fad0fa-7892-476c-82ab-5deb43437385.png">

**Comment by calda** [comment]
@jhughes696 I think this issue is resolved by the new Core Animation rendering engine
