### ISSUE TITLE
Remove Readme.md from xcframework posted on tag

### ISSUE THREAD

**Issue by jesus-mg-ios** [airbnb/lottie-ios#2153]
## Which Version of Lottie are you using?

Lottie 4.2.0

## Expected Behavior 
Do Not include Readme.md

## Actual Behavior
It Is included

## Possible solution

Include Readme.md in EXCLUDED_SOURCE_FILE_NAMES build settings

**Comment by calda** [comment]
Makes sense. 

I believe this was fixed by https://github.com/airbnb/lottie-ios/pull/2132. When you [download](https://github.com/airbnb/lottie-ios/suites/14990496654/artifacts/855507823) the XCFramework archive from that PR's CI job, it no longer includes any README.md files.

**Comment by jesus-mg-ios** [comment]
Should be fixed yas. One question related to it. When will there be another release, more or less?
