### ISSUE TITLE
Error: 'Lottie/Lottie.h'

### ISSUE THREAD

**Issue by ThalesBMC** [airbnb/lottie-ios#2158]
I recently encountered an issue with the Lottie library in my React Native project. I'm using a Lottie animation for the splash screen, and everything was working fine until I updated to version 5.1.5 of lottie-react-native. After the update, I received the following error: 'Lottie/Lottie.h' file not found

I have double-checked my configuration and ensured that Lottie.framework is correctly set up in my project. I also followed every step in the installation and configuration instructions provided in the documentation.

Here are the relevant details of my setup:

React Native version: 0.67.0
lottie-ios version: 3.4.0
lottie-react-native version: 5.1.5

Thank you for your support.

**Comment by calda** [comment]
Please share a sample Xcode project that reproduces this issue. If you can only reproduce the issue when using React Native, please file an issue on the Lottie React Native repo instead.
