### ISSUE TITLE
Is there any way to achieve this effect ?

### ISSUE THREAD

**Issue by vikram-kumar** [airbnb/lottie-ios#218]
Hi,
Am trying to achieve this outer glow effect on irregular shapes. 
<img width="425" alt="outline" src="https://cloud.githubusercontent.com/assets/3540373/25081424/f13f0bf0-2367-11e7-9a39-2c772d71a119.png">

**Comment by Kirow** [comment]
same question here. need shadow/glow animation effect.

**Comment by arush** [comment]
+1

**Comment by buba447** [comment]
We dont support shadow glow effects currently. We will look into them after we release 2.0.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
