### ISSUE TITLE
If I try to loop, it blinks

### ISSUE THREAD

**Issue by KarlosQ** [airbnb/lottie-ios#219]
In iOS the animations behave erratically when trying to loop the animations. In Android they work fine but in iOS they play static bits between each loop iteration and blink every time. In other words the moving elements in the animation disappear each loop iteration, while the static element do not blink.

In issue #122 the solution is change ip to 1 and st to 1 but if I do this in all JSON the animation blink more, the static element blink too if I do this.

Any idea why this happens or how to solve it? 

The aep and json files

[Cloud.zip](https://github.com/airbnb/lottie-ios/files/933053/Cloud.zip)

**Comment by therealsalih** [comment]
Hi! I took a look at your AE file. Right now in Lottie-iOS, precomps can't be offset in time. So the way you have that second layer offset wont perform correctly in the animation
![image](https://user-images.githubusercontent.com/5893643/26984330-d4025da2-4cf3-11e7-8556-d6551735d602.png)

Until we get that feature fixed, the workaround for now is to just bring those precomp elements into your main comp and either duplicate the keyframes or duplicate the layers

![image](https://user-images.githubusercontent.com/5893643/26984403-1e216ef0-4cf4-11e7-999c-90d87d2e4626.png)

One other small note is that your comps had a framerate of 25fps. Its best to keep your comps at 60fps

**Comment by KarlosQ** [comment]
Thanks @therealsalih ! Now animations in loop works fine in iOS 👍 👍
