### ISSUE TITLE
Animation Trim Multiple Shapes Individually (implemented in bodymovin) but not in Lottie yet

### ISSUE THREAD

**Issue by yozef** [airbnb/lottie-ios#22]
I've been trying out this aep.
In After effects: 
![rocket_aep](https://cloud.githubusercontent.com/assets/287256/22597098/342037e6-e9fc-11e6-8eef-2798e33f5d19.gif)

The result is this json file: https://www.dropbox.com/s/8r807g1hcntrzt7/rocket.json?dl=0

The result:
![rocket_result](https://cloud.githubusercontent.com/assets/287256/22597360/46678b1a-e9fd-11e6-925d-c2a4d5e37198.gif)

Bodymovin Settings, if it helps:
<img width="300" alt="screen shot 2017-02-03 at 10 42 02 am" src="https://cloud.githubusercontent.com/assets/287256/22597402/7a4e9d10-e9fd-11e6-8710-329f0ab4de65.png">

**Comment by buba447** [comment]
Are you using trim offsets?

**Comment by yozef** [comment]
I'm using trim paths: 
<img width="755" alt="screen shot 2017-02-03 at 10 58 40 am" src="https://cloud.githubusercontent.com/assets/287256/22597972/d5d325e6-e9ff-11e6-8040-7b92a36000a3.png">

**Comment by yozef** [comment]
I tried again with another design, I get the same:
![checkmark_aep](https://cloud.githubusercontent.com/assets/287256/22601231/02e4a666-ea0c-11e6-8aec-50b1a801947c.gif)

Result:
![result](https://cloud.githubusercontent.com/assets/287256/22601243/0aac94d0-ea0c-11e6-836d-ae77fc7c1798.gif)

(If you need the aep file, I can send it to you)

**Comment by Audiobrad** [comment]
I'm having some similar issues that seem to have something to do with position or anchor point transforms not coming through properly. Although, I think this issue might be due to bodymovin because it renders the exact same way in the bodymovin player

**Comment by yozef** [comment]
For me, at least, both the exported html, and the view within iOS are giving the same result. @buba447 could it be on Bodymovin's end? 

On another note, I do see Trim Paths Start, Trim Paths End, Trim Paths Offset as supported.

**Comment by yozef** [comment]
I'm pretty sure this is a Bodymovin issue. Closing this issue here, and added it in Bodymovin.

**Comment by yozef** [comment]
This turns out to be a `bodymovin` issue which dosen't handle yet Triming Multiple Shapes **Individually**

Out of curiosity @buba447: Once bodymovin handles this use case, would lottie-ios & lottie-android handle them as well out of the box or support would also be needed for these libraries?

**Comment by buba447** [comment]
Ohhh interesting! I will have to look into this

**Comment by Audiobrad** [comment]
I was experiencing this yesterday as well. Good to know where it's coming from. 

I was working with a simple animation with two paths being trimmed by animating the "End" property in separate groups on the same shape layer. My quick fix was to animate the "End" property in one group and animate there "Start" property in the other. The other option would be to separate the groups into their own layers. The Explode Shapes Layers script is extremely helpful for this process with more complex animations. http://aescripts.com/explode-shape-layers/

**Comment by yozef** [comment]
Trim Multiple Shapes **Individually** is now supported in `bodymovin` version 4.5.4.

**Comment by gpeal** [comment]
I can look into supporting this on Android as well

**Comment by tomasbarcys** [comment]
Any update on this? Would love to be able to use Trim Multiple Shapes Individually.

**Comment by gpeal** [comment]
@yozef  @tomasbarcys It's not trivial to get done on Android and iOS but we are working on it :)

**Comment by gpeal** [comment]
@yozef Can you attach the AE file for either or both of your animations?

**Comment by yozef** [comment]
@gpeal https://www.dropbox.com/s/p131s4evkclbn34/rocket.aep?dl=0

**Comment by gpeal** [comment]
@yozef Thanks. As of 2.0.0-beta2 which I'm going to release today, I was able to get rocket working. However, I had to make one small modification. I moved the stroke outside of shape 1 and shape 2 so that the trim path individually knows about both shapes:
![image](https://cloud.githubusercontent.com/assets/1307745/24086688/7ace3bd2-0cd1-11e7-939e-8aefe31a8b18.png)

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
