### ISSUE TITLE
Animation is not rendered correctly

### ISSUE THREAD

**Issue by mihaelaplesa** [airbnb/lottie-ios#220]
Hi,
I've exported the JSON using Bodymovin.
In web the animation is rendered perfectly but when try to load it on iOS it not the correct animation.
I've attached the web animation+json and a iOS screenshot.
[test.zip](https://github.com/airbnb/lottie-ios/files/951419/test.zip)
![iosanimation](https://cloud.githubusercontent.com/assets/27953151/25333517/329a79be-28f3-11e7-9960-066cc8bfd5a2.png)

**Comment by buba447** [comment]
Its hard to say without looking at the after effects file. Can you send that?

**Comment by mwhitt** [comment]
I'm having similar issue ... works in web but not on iOS ... here is after effects file.

[spinner.json.zip](https://github.com/airbnb/lottie-ios/files/1089195/spinner.json.zip)

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
