### ISSUE TITLE
Motion trails since 4.3.0

### ISSUE THREAD

**Issue by AlasdairWem** [airbnb/lottie-ios#2200]
Hi all 👋 

We've noticed lagging/trails/tracing on the dots in this animation when they move together after full pin entry. 
The animation is two separate Lotties cycling from one to the other.
The problem *becomes noticeable here: ecdadec88b057e484b6a11a01454e7af343e3203
Our configuration of the view is unaltered.

## Which Version of Lottie are you using?

4.3.2

## Expected Behavior 

https://github.com/airbnb/lottie-ios/assets/104841860/8a5c7949-5bda-42dc-aedd-54444da0ecb1

## Actual Behavior

https://github.com/airbnb/lottie-ios/assets/104841860/aecccbf3-a805-42de-b4e9-85eec29d3799

## Animation JSON

[stageThreeBottomToTop.json.zip](https://github.com/airbnb/lottie-ios/files/12737759/stageThreeBottomToTop.json.zip)

**Comment by AlasdairWem** [comment]
On closer inspection, my suspicion is that the animation/layer isn't removed as quickly as it was previously, hence showing a trace of the old before the new begins. Perhaps there's something we can do to work around this?

Able to reproduce in the project attached -

[lottieBugReproduction.zip](https://github.com/airbnb/lottie-ios/files/12748932/lottieBugReproduction.zip)

**Comment by calda** [comment]
Thank you very much for the sample project! Much appreciated.

Here's a fix: #2202

**Comment by AlasdairWem** [comment]
🎉 Thanks so much! Really appreciate it 🙏
