### ISSUE TITLE
lottie-spm crashing on device when used inside a framework target

### ISSUE THREAD

**Issue by apps4everyone** [airbnb/lottie-ios#2201]
Hey, 

wanted to switch to lottie-spm but the app is crashing on device when used inside a framework target (not directly in the main app target.

My main app
- MyFrameworkTargetKit
  - MyFrameworkTarget
    - Lottie SPM
 
On device there is the crash with this error:
(no such file)Library not loaded: @rpath/Lottie.framework/Lottie

Only change:
https://github.com/airbnb/lottie-ios.git -> https://github.com/airbnb/lottie-spm.git

**Comment by calda** [comment]
Can you please share a sample project that demonstrates this issue?

**Comment by calda** [comment]
Also, make sure you're embedding "Lottie.framework" in your app binary in the Xcode "Embedded Libraries" panel

**Comment by apps4everyone** [comment]
Hey, hopefully this project is ok, please change team and bundle identifiers so you can run on your device.

[LottieTest.zip](https://github.com/airbnb/lottie-ios/files/12741036/LottieTest.zip)

PS: thx for the quick reply

**Comment by calda** [comment]
The app builds and runs successfully after I add the Lottie library under "Frameworks, Libraries, and Embedded Content":

### Before (crashes)

<img width="715" alt="Screenshot 2023-09-27 at 10 39 38 AM" src="https://github.com/airbnb/lottie-ios/assets/1811727/c738d83e-e748-495b-ba24-edc7e8dd5052">

### After (no crash)

<img width="702" alt="Screenshot 2023-09-27 at 10 39 47 AM" src="https://github.com/airbnb/lottie-ios/assets/1811727/be922848-ca5d-4c4a-80f4-11813845d02b">

**Comment by apps4everyone** [comment]
Hey, sorry for the late reply but this is only a bad workaround because this would copy the binary twice to the app. And also this is not needed with the non XCFramework version in https://github.com/airbnb/lottie-ios/
I guess it is a SPM related bug.

**Comment by apps4everyone** [comment]
The transitive dependency should work without adding the Lottie library under "Frameworks, Libraries, and Embedded Content" again. It is already in
LottieTest -> LottieTestFrameworkKit -> LottieTestFramework
Or why it is working with https://github.com/airbnb/lottie-ios/ ?

**Comment by apps4everyone** [comment]
here is the example with https://github.com/airbnb/lottie-ios/
[LottieTestNONSPM.zip](https://github.com/airbnb/lottie-ios/files/12774779/LottieTestNONSPM.zip)

**Comment by apps4everyone** [comment]
I guess this is not 100% working when used in sub dependencies
https://github.com/airbnb/lottie-spm/blob/main/Package.swift#L20

**Comment by calda** [comment]
If embedding the library in that way doesn't work for your use case, you could continue using the lottie-ios repo.
