### ISSUE TITLE
Command CpHeader field with a nonzero exit code - Xcode 15 - iOS 17

### ISSUE THREAD

**Issue by ismetdemirer** [airbnb/lottie-ios#2203]
I'm trying to compile my project with Xcode 15 and iOS 17. But I get the error in the screenshot.

## Which Version of Lottie are you using?

Lottie 3.2.3

## Expected Behavior 

<img width="345" alt="Ekran Resmi 2023-09-29 23 26 53" src="https://github.com/airbnb/lottie-ios/assets/243714/436c537c-5a38-4ff8-b321-1735cb150da3">

**Comment by calda** [comment]
Can you share a sample Xcode project that demonstrates this error? Thanks

**Comment by ismetdemirer** [comment]
I found the solution. I made iOS Deployment Target 12.0 in the Pods project, everything improved. 
<img width="896" alt="Ekran Resmi 2023-09-30 02 26 54" src="https://github.com/airbnb/lottie-ios/assets/243714/3c2c54cd-01d9-48b5-b746-8bdd8231e2d4">
