### ISSUE TITLE
Unable to download lottie from network source

### ISSUE THREAD

**Issue by Ajay19990** [airbnb/lottie-ios#2206]
## Which Version of Lottie are you using?

Lottie 4.3.2

## Expected Behavior 
The lottie should load up and play when fetched over a network

## Actual Behavior
The lottie doesn't show up, seems it's not downloading

## Animation JSON
Here is the lottie url- https://www.jsonkeeper.com/b/QFW5

[lottie-downloader.zip](https://github.com/airbnb/lottie-ios/files/12828120/lottie-downloader.zip)

**Comment by Ajay19990** [comment]
<!--

## Which Version of Lottie are you using?

Lottie 4.3.2

## Expected Behavior 
The lottie should load up and play when fetched over a network

## Actual Behavior
The lottie doesn't show up, seems it's not downloading

## Animation JSON
Here is the lottie url- https://www.jsonkeeper.com/b/QFW5

[lottie-downloader.zip](https://github.com/airbnb/lottie-ios/files/12828120/lottie-downloader.zip)

**Comment by calda** [comment]
What is the expected behavior of the sample project you shared? When I build / run it, I see an animation download and play successfully:

<img width="350" alt="Screenshot 2023-10-06 at 9 03 12 AM" src="https://github.com/airbnb/lottie-ios/assets/1811727/285194f6-6936-4d0b-8787-6d7d9ab20238">

**Comment by calda** [comment]
I see the problem -- the json file at [this URL](https://www.jsonkeeper.com/b/QFW5) is downloaded successfully, but then fails to parse. Did this animation parse successfully in previous versions?

**Comment by Ajay19990** [comment]
> I see the problem -- the json file at [this URL](https://www.jsonkeeper.com/b/QFW5) is downloaded successfully, but then fails to parse. Did this animation parse successfully in previous versions?

Thanks for your response. Yes it actually was working in version 4.2.0
