### ISSUE TITLE
While building the app Xcode 15 an error "ios/LottieReactNative/ContainerView.swift Could not build Objective-C module 'lottie_react_native'"

### ISSUE THREAD

**Issue by KaterinaUK** [airbnb/lottie-ios#2210]
Hi everyone, I am experiencing an issue after upgrade to XCode 15, I have an error saying "LottieReactNative/ContainerView.swift Could not build Objective-C module 'lottie_react_native'"
I found a few issues but the solution provided did not work:
https://github.com/lottie-react-native/lottie-react-native/issues/734
https://github.com/lottie-react-native/lottie-react-native/issues/906

I tried:
1.  `pod deintegrate && rm -rf podfile.lock && pod update`
2. Quit Xcode.
Delete project's temp files located at ~/Library/Developer/Xcode/DerivedData
Delete ProjectName.xcworkspace
Delete Podfile.lock file and Pods folder
Run pod install.
Open the newly created ProjectName.xcworkspace file and build.

None of these were working for me.
--
<img width="479" alt="Screenshot 2023-10-12 at 11 15 29" src="https://github.com/airbnb/lottie-ios/assets/68429856/7cb0956a-e4d7-4a68-a809-0d18b23920bc">
>

## Which Version of Lottie are you using?

"lottie-ios": "^3.4.0",
"lottie-react-native": "^5.1.4"

## Expected Behavior 
The build should succeed.

## Actual Behavior

<img width="458" alt="Screenshot 2023-10-12 at 11 19 44" src="https://github.com/airbnb/lottie-ios/assets/68429856/bed74e41-136d-4018-bd59-75a6ce1c86af">

## Animation JSON
NA

**Comment by calda** [comment]
This sounds like a problem with Lottie React Native. Please file an issue on that repo instead: https://github.com/lottie-react-native/lottie-react-native

**Comment by viktasidenfy** [comment]
I am experiencing the same behaviour on the iOS project. This problem occurs on xCode 14.3 and newer with `use_frameworks!` commented out in the podfile. It should not be connected to React Native.
