### ISSUE TITLE
Introduce privacy manifest

### ISSUE THREAD

**Issue by calda** [airbnb/lottie-ios#2213]
This repo needs to provide a privacy manifest, as described here: https://developer.apple.com/news/?id=av1nevon

**Comment by dg-yoshida** [comment]
Hello.
Does lottie-ios support privacy manifests?
Also, when will you respond?

Thank you!

**Comment by EricJMoon** [comment]
Since this SDK uses ZipFoundation, action on the "Privacy Manifest" is required.
ZipFoundation SDK has already taken action on “Privacy Manifest”.
Please confirm this.

**Comment by esteluk** [comment]
Is there appetite to backport this to earlier major releases of Lottie?

**Comment by calda** [comment]
We added a privacy manifest in https://github.com/airbnb/lottie-ios/pull/2252. We also need to adopt code signing, which we will be adding soon. I expect to include both of those updates in Lottie 4.4.0, which we will probably release in January.

**Comment by slice-varundudeja** [comment]
privacy manifest pod update requires minimum deployment target to be 14.1. is that necessary?
