### ISSUE TITLE
iOS error: "vertex point out of bounds"

### ISSUE THREAD

**Issue by mitjaeichhorn** [airbnb/lottie-ios#222]
Hello!

you are our last hope! The whole Lottie idea is great and long needed, and we got it working on Android, but iOS is taking days to fix and is still crashing...
It gives everytime the same Error: vertex point out of bounds.

Does some has and idea what is can be? We event took the sample AfterEffects file from https://github.com/airbnb/lottie-android/tree/master/After%20Effects%20Samples and it didn't help.

Any idea?

Thank you very much!!! 
[Eb.json.txt](https://github.com/airbnb/lottie-ios/files/952416/Eb.json.txt)

**Comment by aquarchitect** [comment]
@mitjaeichhorn I had a similar problem and resolved it by trimming out-of-bounds geometries in AE before exporting.

**Comment by samiam2017** [comment]
@aquarchitect can you go into more detail of trimming out-of-bounds geometries. When you look at lottie project samples there are a number of projects where shape layers travel outside of the canvas. 

I'm running into the same problem as @mitjaeichhorn where I'm getting the "vertex point out of bounds" error when the devs try to implement the animation. The strange thing is that the animation plays fine when I test it in the lottie android app. How do you do your testing to avoid the back and forth with devs?

**Comment by samiam2017** [comment]
k I answered my own question for others running into this issue, I found a stray path element outside the shape layer group in the timeline (below the transform, stroke and fill properties). When I deleted it problem was solved. I recommend downloading xcode for troubleshooting was a huge help isolating the problem element.

**Comment by buba447** [comment]
Fix found here! https://github.com/airbnb/lottie-ios/pull/257
