### ISSUE TITLE
Animation misses parts on iOS only

### ISSUE THREAD

**Issue by ilazakis** [airbnb/lottie-ios#2220]
## Which Version of Lottie are you using?

Lottie 4.3.3

## Expected Behavior 
Lottie JSON files to animate same on iOS as it does on web.

## Actual Behavior
The animations seem to be missing some parts (an "eye" in this case).

## Animation JSON
**Listing two examples**
[chatbot-falling-asleep.json](https://github.com/airbnb/lottie-ios/files/13045542/chatbot-falling-asleep.json)
[chatbot-sorry.json](https://github.com/airbnb/lottie-ios/files/13045543/chatbot-sorry.json)

**Comment by calda** [comment]
Thanks for the report, here's a fix: https://github.com/airbnb/lottie-ios/pull/2221

**Comment by ilazakis** [comment]
Thanks for looking into this so quickly, and for such a quick resolution @calda 🙏
