### ISSUE TITLE
Error Domain=NSCocoaErrorDomain Code=260 "The file “heart-icon-like.lottie” couldn’t be opened because there is no such file."

### ISSUE THREAD

**Issue by rcrahul43** [airbnb/lottie-ios#2224]
## Which Version of Lottie are you using?

Lottie 4.1.3

## Actual Behavior
Animation files are removed from cache and not loaded once app received memory warning.
SDK throws following warning:
`Error when decoding lottie "heart-icon-like": Error Domain=NSCocoaErrorDomain Code=260 "The file “heart-icon-like.lottie” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/rahulchaudhari/Library/Developer/CoreSimulator/Devices/0B02E6E5-9824-4730-992A-A10FFABD3B75/data/Containers/Data/Application/3D23C25E-7ABE-477A-8AC7-7C851BA46868/tmp/heart-icon-like.lottie}
`
https://github.com/airbnb/lottie-ios/assets/10935538/d9c05e34-920d-4dbf-a4da-0388ea594161

**Comment by calda** [comment]
Can you please share a sample project with specific steps to reproduce your issue?

**Comment by rcrahul43** [comment]
[LottieSample.zip](https://github.com/airbnb/lottie-ios/files/13110886/LottieSample.zip)

Steps to reproduce are recorded in the video attached previously. 
Basically in case of system memory warning, lottie files are not available.
