### ISSUE TITLE
Animation is not correct after updating to 4.3.x

### ISSUE THREAD

**Issue by squarefrog** [airbnb/lottie-ios#2226]
After updating to 4.3.0 or higher, we noticed that our startup animation handles flip transitions incorrectly. Running `git bisect` against the example project leads us to believe [this PR](https://github.com/airbnb/lottie-ios/pull/2067) introduced the issue.

We are able to work around this issue by using main thread as the rendering engine.

## Which Version of Lottie are you using?

Lottie 4.3.x

## Expected Behavior 
In 4.2.0 we see the animation rotate the B character up, then flip then rotate down.

| | |
|-|-|
|![4 2 0 A](https://github.com/airbnb/lottie-ios/assets/343450/56cd9882-8964-4774-a295-196f6d84bb2f)  | ![4 2 0 B](https://github.com/airbnb/lottie-ios/assets/343450/7ccd6daf-ea29-488a-a654-e36c2e6f485f) |

## Actual Behavior
In 4.3.x the x position of the B character changes during the flip transition

| | |
|-|-|
| ![4 3 3 A](https://github.com/airbnb/lottie-ios/assets/343450/d5e90323-14a0-4646-99d1-e8d551c1b410)| ![4 3 3 B](https://github.com/airbnb/lottie-ios/assets/343450/44c7167f-3e03-460b-b035-ff830f9efb16)|

## Animation JSON
 [0splash_logo_animation.json](https://github.com/airbnb/lottie-ios/files/13242566/0splash_logo_animation.json)

**Comment by calda** [comment]
Thanks for identifying the PR that introduced this regression! Fixed in https://github.com/airbnb/lottie-ios/pull/2285.

**Comment by squarefrog** [comment]
This is amazing, thank you @calda !
