### ISSUE TITLE
my animtion show nothing，Warn: image not found: data:image/png;base64

### ISSUE THREAD

**Issue by chunqingawei** [airbnb/lottie-ios#2230]
## Which Version of Lottie are you using?

Lottie 3.x.x

## Animation JSON

Warn: image not found: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAARgAAAEYCAYAAACHjumMAAAACXBIWXMAAAABAAAAAQBPJcTWAAAAJHpUWHRDcmVhdG9yAAAImXNMyU9KVXBMK0ktUnBNS0tNLikGAEF6Bs5qehXFAAAgAElEQVR4nHx9W7bkOIgtRJ/5rzuKO8sy/SH2S3Z2rKo8EbYegGCDkCz3/L///1RV1UxX99RMV1Xx+6+nnuqqKV3f391VM1XVe6/m1c6pc8qx/PX57MPoAH13e9VFOuqffas+vlc16WD5bQvXnqn6ddcsX/j39Pdux9uanurt76mq3yVf1c+PeIa8nHaStz2fMrNXf30YeKqqnsPP1KFjeqpMJlP6HZSYTGfL9RnVqtm/GGzUXNmBFpZnQx19QjbTqu/lp6oadXqOHMhrfbTvJKGNDh4lJdNDjOWWHdbP8mX1JPgincMxspE5N5f2Zmv/bBPfTQdrpqbbCsTw/LPe6RM9or7R8FxEQP/HvoNY737yMsdikre07/mjwltb8f2oDMdOveBum/F3b91+g8DVuQNByKiv+kaR6kxR9mtYMEKvewy0L6adO5VPIXXS230pA8BCvEBWVVW/gtFJdjeoCKQFOuIZElloawynDMSor6mqh0J0ZgCKS38DKFwnZdRjwFmoZ+CEvniP7Ugbaaw0cPx9tzkLYxV6YO1sZ8/y3CNDUZfmLACwi0phZuQBYHd+PSgz53vwyLFSTVb9BJcK+nrbV9ve3scn8PK3F6bcOgfsuX3cOPviYd7AUuIDoOxOyPx9GUvB70MoN2dlTE7VX/166r+q+gkj2MNR+oNSjXu8D+E2DWAtJtC+SxZx2gBINKMhGFshkHgZs9PkIkJfrqBj995gIlA4/dwRVXdRKcTX++Ntg0Y32tPW9jcL1P1dl8ICBzA4DmwCtgPb4153bhrM1zRAaCOILSIMWIMelJ1U4i08AZRroINOFwBoi5dRAVisc4BM2xgOGVn1hRNzEG1YukU4G5p0HfpPg11Pg8Cl5gEfMn5x6YDnvNov9t9XGQdByWbMgX9F8E6dIp5J3b5AJUEN8v4Gr0EY/agGbC403H64c1VFG4OaHYKIZ04Er67/aqrrfwpe4t8GKW+Y9zD4iB6qxtp5sztWj5FJVTg7THnU/6i8e66qFwgkWCFod1ru6EhyxLUTgaRPQFz9nr5d4KbQKtr9nvY4COja3T6A8J7+PbDDVcSjCuaFA3zR1vCX3NReh3EwClI0FDHuNe2R7LfNp64oZe+bAvm/BzSN18poJaM6p2FYXlFJqDuLezRBMA1KLpCBPtoQeQkWga4ZWFIXyJvIhjLcUXVMpK6o5eb5BfTGdz3L/68YtUxVNcGlxROj019KwJuejzEeawdMVhVmE5g2V83f8YKPFFrfjbgrtIAKd99G0pdAG1ggITxmgwGZVf2bms0fsL9u9icBuAG6RAQCRzie9+hLqbpyCqXvtyGzLDwpxaEylIMhvO5ldNJdRlfVHWkpukK/621GkAlQUeS7Gg/vHDkW/Qbcos6n7a6MgU/DaMEAH4MUU92ljVESTA2DD8Ft2Yi+EtSzzmS5qY0KbrBQeQeenmKUAtlYz8azNWMqdd1iPw9omFEUZGpwOzFGJCORvyIR73T7AeDNLLU7HiKxa+Y5Edxvq72mRDtb2A7bQOyxxl4RVgCsjc9bIEc/I73QfyfEXn6ey7u7+ZIgoh8IAlajYQOMK0FLsGGobEbQVfMYYFmoRbOyhOwPAsP9ayr1jq4AKkurAWPn3O8VXWBKF2GqgUTwePWp696+fvs4eVRXVZnktLHIZKtoVqE0UuG9gOLu25XbgYJJXC+1YyPg2b5szKaR2zH/bFHNneiNKQd0qKd8KvQs5aAL0RoAz5Pe4kbjRZC8QKVLIPYFJBlJAe9l5KwTxniXD4o0Te0ppCCi22hUbXo/APFD32/nwFHLfv/Yz6zEsp9veQl4L3uwfB7kFGB8Bv/HRkX4nEhiBUND2lL9U3kkDturb3mC0CYnur/MwqOZt4EBFzCFDCG4IRowejL1/g0aM29zFPOpYdmMbJqEuKK48uQH3qYU7WC+747JEMMjscgLTdM4mfR0IDk1zNvKSKZQtjdSgOF2ysCN+gIo3FO/Av6x9rwOk7yINPB/HXk8hXl6gkuAA4GnzopYKQsgwx79Zr9W7zJyj2iYazLwxH3UV+7MhL36eSd1x/qrB3retB/cZw20C33byEQ02gf3+Hvl/AzHYJ6Kqe8MohqTBWcfJo/g4/xGns7lQV2uqWGIhPsT9UPW01s4jBJhvAbLfw8JgLUcBTnAkoZVxiS9uq0EyXAdKs3It4sfjOwxhdj/X/nya7oRgLX9eIKXGGjGkkv1IKmt/Fjb2T+lbajrSduTOL/BZhOr3sR6bxgrQYL0yUCpCI8lFmsYRQBM0hhGITeVJxVRxuVg7v2mkeM6r3mk8xgQcbqZipnyOk7taawMQZeuaNPvoa3xxC3CdgHkqfe8wErtXBEewbXqWLNyRUeNJYHZrQ3PmO7MYVaGCrpWBj59NzSJewYIh0QHlv1tcjlJ+guc0KYB2dg1lbnkWVW1CwoEMh+PewD1+YscQFtIjMbbdFnffUVEA8Iy9Z5Tp1FWKfkqQMr9KG3FR9fRJIHCpkatqRPpKcw9QQdAUuGgVssqy7ziLcnk3ntDPqx+Zv2Nx+vDfIxNS3paKzmcKtnA8x/95rIpxxEMgWdrH221lSdky+C8/bi/xbE4IEDxulteZBSnR1PF6U+M+Rm9xwxx4XApeANc0Npz5FaQ/aH1TK8MjF1HMN2CjEBWqw2SyURmaUxcRmFfuA5DMkCwggIyK2eXqqqep07itubkVxBloy4z/l7X2jKguHUwKXHnavYYutaSh/Xj20j27t8pTsWX251qW8JWcjJt7jR0bzxjfmFyVUR7bmBsW8ew6D3lABgNQaGqqn5rKBdwYcMepnVU1E7S/bsDg0BD/Llx5SqPgUMLRF051M4bgPB5fMAxtVgiNRUZM8p+K0WAsk1rPNghON18mRyCB8tt+LTF6XdFBFCNCkZEgPF2jTdwoR4bMBxDNrrMORB8QF943qtOKdHbbNhzGMCoWX1UQtQl/VoZQzuWK0qp2jUC0kEnLKvz/pWnO+LdpPm9KgQd8GEhCWaP+1MgJv0y1dhaH4scM1X1o9yTRyvXmPpKvjP9R0JydXXF0F39yFgxRSC6w+AsGnHl841vRaM9A6/NOQY48G5oCmC0modoRA7hMPX7wcPPtrNISGW8vaJklytGKW7tb3mD5FpUeppeIJwy4DOA9LJVXG2Bj9byIwYXymiX4CEeDZgDIOpxJ+kr37EKFsn0Uf0LvKYcXAwoRnmvHDcAYnOKlkKX4d9Rziup7SB2tSFQKQPdm3K1oaaQXPWrGJOsn33exltZ9oPusMlR2RrpMSPdoGO/TNf8ttcHtT+iEpG4VS/H4gX6Lm+6jOmxTVHPbwCz4UDLFsamniT9EPBjhTe9WIoGkNRnhIFIx1T0o4wxb21X7Rb39f74XiUAc3p0Dwa/uYtHilqjfS/d5zGE2kjmTvj6PhZvE0K+c0rKM4kuN0etZmGOCoMXLzG1nEImQC2ZEUfEEYYvmbpShaeGkaN9BweLNOi9/fta09RuWIup0pZCIhD5FLs3JZoLfZunw29EFJBB79TN61AOU6Qpjb9rnn73x+inkv9NuEceYqwtk29PR7/+YS7D7qEtL/vc91YXgibce4YVZrpmo5Z53G5SFtXp5HwG5vpR/G6jPNIbj9ZOPQCgA4fbSvJ753H28we5VtXUr4+XZ2xxAU9DYAsIEtAxqrNK9rE3pvSH7TGszL0gnt+AogiBtSiJlrRDVsjqwvAczTtf0ky4ZhTTAZKfqz/8boBi3xX1CRhpeJCHz5HFTU6FxuHYIikvS0I1BjI4Myzce8QQDcl5agGEoqtifTlH9DEsww1tPu

**Comment by calda** [comment]
Please share the full animation json file. I also see you mentioned you're using a rather old version of Lottie (3.x). Have you tried updating to a more recent version?
