### ISSUE TITLE
Failed to load asynchronous Lottie animation with error: The file “manifest.json” couldn’t be saved in the folder because a file with the same name already exists.

### ISSUE THREAD

**Issue by denandreychuk** [airbnb/lottie-ios#2234]
We have a button which starts multiple animations at the same time in the list. It ends up with only one row playing the animation and the others just appearing blank. In the console, I receive this error message:
Failed to load asynchronous Lottie animation with error: Error Domain=NSCocoaErrorDomain Code=516 "The file “manifest.json” couldn’t be saved in the folder because a file with the same name already exists."

```
  LottieView {
      try await DotLottieFile.named("animation")
  }
  .playing(loopMode: .loop)
```

**Comment by calda** [comment]
This is probably the same issue as https://github.com/airbnb/lottie-ios/issues/2224. I believe https://github.com/airbnb/lottie-ios/pull/2229 has probably fixed this issue. Could you retry with your package reference pointing to the latest commit on master, and see if that fixes the issue?

If not, please share a sample project that demonstrates the issue.

**Comment by denandreychuk** [comment]
No longer reproduces on master. Thank you, @calda!
