### ISSUE TITLE
What does this Xcode crash mean?

### ISSUE THREAD

**Issue by sureMOE** [airbnb/lottie-ios#224]
I am trying to trouble shoot the problem I am having here, but I can't decipher what's going on. I have tried a number of things in After Effects, but it doesn't help. Also, for some reason this file works on Android player 2.0.0 beta4. Any ideas?

2017-04-28 09:31:10.095802 Lottie-Example[2189:808224] *** Assertion failure in -[LOTAnimatableNumberValue _buildAnimationForKeyframes:], /Users/schurman/Documents/lottie-ios-master/lottie-ios/Classes/AnimatableProperties/LOTAnimatableNumberValue.m:55
2017-04-28 09:31:10.096869 Lottie-Example[2189:808224] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Lottie: Keyframe animation has incorrect time values or invalid number of keyframes'
*** First throw call stack:
(0x18c9421c0 0x18b37c55c 0x18c942094 0x18d3cf79c 0x100142784 0x1001423bc 0x100168c00 0x100168774 0x100164478 0x100163e44 0x100163c24 0x100164078 0x100163e44 0x100163c24 0x100164078 0x100163e44 0x100163c24 0x100164078 0x1001584b0 0x100157340 0x100152e88 0x10015290c 0x10014e884 0x10003a274 0x100039e64 0x10003be08 0x1928ca078 0x19297ab34 0x192a2dd5c 0x192a1fb10 0x19278e854 0x18c8ef7dc 0x18c8ed40c 0x18c8ed89c 0x18c81c048 0x18e2a2198 0x1928072fc 0x192802034 0x100041060 0x18b8005b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by jorgeneidem** [comment]
Did you at any point use Keyframe Assistant to time-reverse keyframes? That gave me a similar error message.

**Comment by sureMOE** [comment]
Wow, I bet I totally did...I use that ALL the time. Is that a known bug?

**Comment by jorgeneidem** [comment]
Maybe we should create a more specific issue on that. In general reversing/flipping/mirroring using negative values seem to cause some trouble.

**Comment by Dreadrik** [comment]
I have the same issue. Animation works fine on Android, but I get this assert on iOS.

**Comment by adilanchian** [comment]
Any update on this issue? Just received this same error today as well.

**Comment by buba447** [comment]
We have issues with reversed time layers on ios right now. Support for this is coming with the next major release! Hold tight!

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
