### ISSUE TITLE
`backgroundBehavior` doesn't seem to do anything

### ISSUE THREAD

**Issue by freak4pc** [airbnb/lottie-ios#2242]
## Which Version of Lottie are you using?

Lottie 4.3.3

## Expected Behavior 

Moving to background and then back to foreground should respect the applied `backgroundBehavior`

## Actual Behavior

No matter what I set (I tried `stop` or `pauseAndResume`), the animation is "stuck" in a weird state and not the intiial frame, as would be expected. 

https://github.com/airbnb/lottie-ios/assets/605076/13165487-4771-42f1-aac4-7a64a59a9c3c

**Comment by calda** [comment]
Thanks for the report. Please share a sample project that demonstrates this issue, including a description of the expected behavior.

**Comment by calda** [comment]
Are you using the SwiftUI `LottieView` or UIKit `LottieAnimationView`? 

If you're using `LottieView`, perhaps you could check if this change fixes your issue: https://github.com/airbnb/lottie-ios/pull/2237

**Comment by freak4pc** [comment]
This is actually a UIKit `LottieAnimationView`, could it make any difference?

**Comment by freak4pc** [comment]
Hey Cal, sorry, I think this is related to some custom code we have around the view to support dark/light animations and trait collections. Closing this 🙌
