### ISSUE TITLE
My lottie file can be displayed and played normally on the official platform. But using Lottie 4.3.3 prompts playback failure

### ISSUE THREAD

**Issue by RayFor24** [airbnb/lottie-ios#2243]
My lottie file can be displayed and played normally on the official platform. But using Lottie 4.3.3 prompts playback failure。
The following error will be reported
Lottie.Archive.ArchiveError.unreadableArchive

Here is my code：

DotLottieFile.named("ip_coffee") { result in
            switch result {
            case .success(let dotLottieFile):
                self.animateView.loadAnimation(from: dotLottieFile)
                self.animateView.play()
            case .failure(let error):
                print(error)
            }
        }

[ip_coffee.lottie.zip](https://github.com/airbnb/lottie-ios/files/13522303/ip_coffee.lottie.zip)

## Which Version of Lottie are you using?

Lottie 4.3.3

**Comment by calda** [comment]
I took a look at the file, and its actually a json file, not a dotLottie file.

If you rename the file from `ip_coffee.lottie` to `ip_coffee.json`, you'll see that it is able to be loaded properly.

<img width="662" alt="image" src="https://github.com/airbnb/lottie-ios/assets/1811727/81e3aa88-e83d-4a9d-8057-3fd0b95f1bce">

**Comment by RayFor24** [comment]
The dotlottie file above is from my https://lottiefiles.com Downloaded from the website.
![d0b28ec1208af629c98c1ddf3](https://github.com/airbnb/lottie-ios/assets/8860631/93883af4-edb3-4d5d-b96c-e29e7ffbe14a)

How should I present. lottie format files in a project
