### ISSUE TITLE
Lottie file works on Web Preview, but not on iOS

### ISSUE THREAD

**Issue by yanunsey** [airbnb/lottie-ios#2244]
The attached lottie file works on Web Preview, but not on iOS. This can be seen by opening it in the LottieFiles iOS App.

This information is from the LottieFiles App:

- View resolution: 390 x 390

- iOS Player: 4.3.1

- dotLottieLoader: 4.3.1

## Check these before submitting:

- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## What Platform are you on?

- [ ] MacOS
- [x]  iOS

## What Language are you in?

- [x] Swift
- [ ] Objective-C

## This issue is a:

- [x]  Non-Crashing Bug (Visual or otherwise)
- [ ]  Crashing Bug
- [ ]  Feature Request
- [ ]  Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

lottie-ios 4.3.3

## Expected Behavior 
Animation should appear as it does on Web Preview

## Actual Behavior
Animation is not shown

## Animation JSON

[Button.json](https://github.com/airbnb/lottie-ios/files/13522946/Button.json)

**Comment by calda** [comment]
This animation renders and animates properly when I test it locally. If you are seeing something different, please share a sample project that demonstrates the problem and reopen this issue. Thanks!

<img width="662" alt="image" src="https://github.com/airbnb/lottie-ios/assets/1811727/626074de-c715-416d-b38b-0fafc7877908">

**Comment by calda** [comment]
It's possible this is a bug that was fixed in a recent version of Lottie, since 4.3.1 is not the most up-to-date version.

**Comment by calda** [comment]
Are you only testing in the LottieFiles app? The LottieFiles app is using an outdated version of Lottie, so doesn't include any recent bug fixes.

**Comment by calda** [comment]
Perhaps this was an issue fixed on master but not fixed in 4.3.3. We released 4.3.4 yesterday, maybe give that a try.
