### ISSUE TITLE
iOS bug - Animation on iOS missing some shape layers

### ISSUE THREAD

**Issue by AmirShalev** [airbnb/lottie-ios#225]
My name is Amir Shalev and I a part of AutoCAD mobile UX team in Tel Aviv.

I would like to tell you that your work is AWESOME! Keep it going! Thanks a lot for this cool feature.
I just started exploring this awesome plugin for After Effects, and I am having a small problem with viewing all of my shape layers.

I’m using both. On Android, it seems to work, but on iOS, the triangle disappears on the device for some reason.

Do you have an idea what is the problem?

JSON file is attached.

**Comment by xuran** [comment]
我也遇到过这样的额问题，并且发现字体重叠

**Comment by brianliebler** [comment]
I'm having the same issue. The rendered animation is a square in our iOS app when it should have three triangles as part of the icon. Please advise.

**Comment by Kymer** [comment]
I have experienced the same issue (under certain conditions). Really odd.

@AmirShalev I'm not seeing the JSON file. I can reliably replicated the issue in a small iOS project, but can't share the specific animation. Want to give it a shot with your animation.

**Comment by AlexDM0** [comment]
I also have this issue. My AE file is made out of 5 instances of the ball, 5 instances of the bar, precomposed into the animation of the logo. The demo that I export from bodymovin looks fine in the HTML viewer. It's only animated scales, rotations and positions. Nothing complicated.

On both the simulator and the device it looks like this:
https://github.com/crownstone/CrownstoneApp/blob/lottie/js/animations/screencapture.gif

Whereas it should look like this:
https://cdn.rawgit.com/crownstone/CrownstoneApp/lottie/js/animations/demo.html

The svg is here:
https://github.com/crownstone/CrownstoneApp/blob/lottie/js/animations/crownstoneAnimatedLogo.json

Any clues?

**Comment by buba447** [comment]
Can i get a link to an after effects file that shows this behavior? @AlexDM0 @Kymer @AmirShalev

**Comment by AmirShalev** [comment]
@buba447 @AlexDM0 @Kymer 
I explored all Lottie files and followed their working method. In the end, I solved this issue by working with Illustrator and After Effects. I Designed all my assets in Illustrator and imported into After Effects, only then I used on each illustrator layer the action "Create Shapes from Vector Layer." After that, I worked with a Null object to move all shapes layers. And finally, in the end, it worked in iOS.

I used this link to understand how to convert Illustrator files into shape
https://helpx.adobe.com/after-effects/atv/cs6-tutorials/converting-imported-vector-graphics-from-illustrator-to-shape-la.html

**Comment by AlexDM0** [comment]
@buba447 Here is my file:
https://www.dropbox.com/s/5sdqkbjugcsegaz/crownstoneLogo.aep?dl=0

**Comment by AmirShalev** [comment]
@AlexDM0 @buba447 @Kymer Here is the file I created and succeeded to view on an iOS device.
https://drive.google.com/file/d/0B11YO4RxuS6lRjV0eUswTjE3c1k/view?usp=sharing

**Comment by buba447** [comment]
Hey everyone. Seems to be a lot of issues here that arent necessarily the same issue. @AlexDM0 Your issue is with expressions. We dont currently support expressions on any platform of lottie, and we do not have any immediate plans to implement that support.
Everyone else that is seeing an issue on ios but not on android, I suspect it has to do with fill rules, or merge paths. These are two major features that have been implemented on android but not yet on ios. When you convert an illustrator file to AE it usually relies heavily on these to features. We are working hard to implement this on ios and will bump the version to 2.0 when its finished.

**Comment by AlexDM0** [comment]
Hi, thanks for the investigation! I tried it before without expressions but with moving masks. The result was the same. I'll revert my AE file to test it again and report back. 

Cheers

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
