### ISSUE TITLE
App refreshes when I minimise it and open again.

### ISSUE THREAD

**Issue by sanket-zywa** [airbnb/lottie-ios#2255]
I recently upgraded to 4.3.4 from 3.2.3 and this issue started happening. I had to downgrade the SDK to remove the bug.

## Which Version of Lottie are you using?

Lottie 4.3.4

## Expected Behavior 
If I minimise the app and comes back to the app, it should not refresh and maintain the previous state.

## Actual Behavior
If I minimise the app and comes back to the app, it refreshes the app from the storyboard start point.

**Comment by calda** [comment]
Please share a sample project that demonstrates this issue, thanks

**Comment by sanket-zywa** [comment]
I'm using swiftui in uikit project. Can that be a problem?
