### ISSUE TITLE
iOS App submission will require a privacy manifest and signature

### ISSUE THREAD

**Issue by shaillymt** [airbnb/lottie-ios#2256]
12/07 Apple published a privacy update on their website: [Privacy updates for App Store submissions](https://developer.apple.com/news/?id=r1henawx)

It requires third-party SDKs to include a privacy manifest file and this will be required by Spring 2024.

Lottie is on the list of [third-party SDKs that require a privacy manifest and signature](https://developer.apple.com/support/third-party-SDK-requirements/)

What is your ETA on completing and publishing per the requirements?

**Comment by calda** [comment]
We added a privacy manifest in https://github.com/airbnb/lottie-ios/pull/2252.

Please continue any other discussion in https://github.com/airbnb/lottie-ios/issues/2213.
