### ISSUE TITLE
Async loading of animation removes SwiftUI animation

### ISSUE THREAD

**Issue by denandreychuk** [airbnb/lottie-ios#2257]
Suppose we have a simple animation view which loads DotLottie file:
```
@State private var flag = false

var body: some View {
    LottieView {
        try await DotLottieFile.named(animation)
    } placeholder: {
        Image(placeholder)
    }
    .looping()
    .resizable()
    .offset(y: flag ? 0 : 300)
    .onAppear {
        withAnimation {
            flag = true
        }
    }
}
```

The code above moves to offset 0 immediately, removing SwiftUI offset animation

**Comment by SoylentGraham** [comment]
Can I ask where you found the documentation for this style of loading?
I've spent the last hour trying to load data in 10 different ways, and then stumbled upon this example, which worked! :)
