### ISSUE TITLE
In lottie-ios (4.3.3) my all lottie.json file works only 1 file have issue and unable to load that 

### ISSUE THREAD

**Issue by iOSGaurav90** [airbnb/lottie-ios#2258]
Hello 
i am facing issue while load the Lottie file in my iOS app. i do have 1 common loader controller where i am loading the different Lottie according to flow so code is common with same code only 1 file is not working and i am unable to find the root cause for that 

- We have view on storyboard with class **LottieAnimationView**  on which i am trying to load Lottie with below code 

` 
var lottieView : LottieAnimationView?
func animationSetup(){
        self.lottieView = .init(name:lottieFileName)
        self.lottieView?.backgroundBehavior = .pauseAndRestore
        self.lottieView?.contentMode = .scaleAspectFit
        self.lottieView?.frame = self.animationView.frame
        self.lottieView!.loopMode = .loop
        self.animationView.addSubview(self.lottieView!)
        self.lottieView?.play()
    }`
    
    Adding the screenshot along with that json file which is not working in screen shot where red box is shown there i am trying to load that Lottie 
![Simulator Screen Shot - iPhone 14 - 2023-12-14 at 10 45 32](https://github.com/airbnb/lottie-ios/assets/153794767/cfc0b752-6ea5-4a3c-ac0d-f8cf6c823207)

The file which is not working 
This same file is working fine with older version of SDK, even now this file is working fine on Android 
[fibo_with_watch_round_circle_bg.json](https://github.com/airbnb/lottie-ios/files/13668844/fibo_with_watch_round_circle_bg.json)

## Which Version of Lottie are you using?

Lottie 4.3.3

**Comment by calda** [comment]
Have you tried Lottie 4.3.4 yet? We fixed a similar issue recently

**Comment by iOSGaurav90** [comment]
> Have you tried Lottie 4.3.4 yet? We fixed a similar issue recently

Hey calda Thanks for quick response, It is working in 4.3.4 Thanks..!!!

**Comment by iOSGaurav90** [comment]
This issue is fixed in 4.3.4
