### ISSUE TITLE
Precomps always start at zero and play before being visible

### ISSUE THREAD

**Issue by mikekaminskyUX** [airbnb/lottie-ios#226]
When playing back an animation, any precomps that are used (for repeating elements) will start playing immediately, so that by the time the animation reaches that point in the timeline the object will appear only showing the last frame.

This behavior did not appear when using the Lottie Android test app.

**Comment by jjc235** [comment]
Hi Mike, have you found a fix for this?  I am seeing the same behaviour.

**Comment by mikekaminskyUX** [comment]
No resolution, we have had to manually adjust every pre-comp into it's own composition that starts at 0. Results in a ~50% larger file so really hoping for a new build soon. The Android 2.0 build correctly addresses this.

**Comment by therealsalih** [comment]
We're working to get that fixed. You can also follow the status of that change at https://github.com/airbnb/lottie-ios/issues/176

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
