### ISSUE TITLE
Animation from JSON file not shown after change the animation from DotLottieFile.

### ISSUE THREAD

**Issue by adhityasp** [airbnb/lottie-ios#2265]
Hi Lottie team,
I stumbled upon this issue when I want to change the animation between .lottie and .json file to the same @IBoutlet LottieAnimationView and after debugging for 2 days straight.. I can't find the solution. 

But here's what I found:
- When loading the .json animation for the first time, it works fine
- Changing between different .json animation has no issue
- Changing between .lottie & .json triggered this behavior only when loading the .json file 2nd time onwards
- Always reproducible with renderingEngine .MainThread / CoreAnimation
- The animation is successfully load & decode, `isHidden` property is `false`. But still not shown to the user.
- Not all animation can trigger this issue ( I have sample animation that can't reproduce this issue )

## Background
Why I need to change between .json & .lottie file?
- I want to migrate all animations to .lottie on the local file first. But the remote URL still using the old .json file.

## Workaround
- Always create LottieAnimationView before showing the animation can solve this issue. But we will have some flickering & it's annoying to remove the subview over & over again. It's easier to just change the animation using `.animation / loadAnimation()`
- Change all animations to .lottie in 1 go.

I think this is not the animation file issue and more like rendering issue. Maybe there's something is need to be clean up when changing from DotLottieFile to LottieAnimation that makes the 2nd json load is not appear 🤔.
 
I made the sample project below to reproduce this issue. Hope it helps.

## Which Version of Lottie are you using?
Lottie 4.3.4

## Expected Behavior 
Animation from .json file shown / give warning if there's any incompatible behavior after changing from .lottie remote file.

## Actual Behavior
Animation from .json file not shown / give warning if there's any incompatible behavior after changing from .lottie remote file.
<video src="https://github.com/airbnb/lottie-ios/assets/19931734/6f2bb1dd-979a-4ba9-a010-391b42fd3dba"/>

### Animation used to reproduce:
.json URL: https://lottie.host/9fa13ee4-8169-4fc1-b1b4-481bfdb823f1/WLhGQBTXSy.json 
.lottie URL: https://lottie.host/c9ff306b-87ea-476b-a66a-90a51db25b43/HDJcxfBMg5.lottie
   - This .lottie file was converted from https://lottiefiles.com/tools/lottie-to-dotlottie

### Another animation used to debug but the behavior is expected:
[Animation2.json](https://github.com/airbnb/lottie-ios/files/13698088/Animation2.json)

## Sample project to reproduce the issue
[animationJsonURLNotShownAfterChangeFromDotLottieRemoteFile.zip](https://github.com/airbnb/lottie-ios/files/13698071/animationJsonURLNotShownAfterChangeFromDotLottieRemoteFile.zip)

**Comment by calda** [comment]
The problem here is that:
1. Loading a dotLottie animation with images applies a `DotLottieImageProvider` to the `LottieAnimationView`
2. Switching to a json animation doesn't clear the `DotLottieImageProvider`
3. `DotLottieImageProvider`s don't handle base 64 images, and instead return nil.

A simple fix on our side is to just update `DotLottieImageProvider` to handle base 64 image providers. We'll make this change and it will be included in the next release.

In the meantime, a workaround on your side could be to switch back to using the standard `BundleImageProvider` after switching from a dotLottie animation to a standard JSON animation. Updating your `loadAnimation` method to the following fixes the issue:

```swift
  private func loadAnimation(url: URL) {
      if url.pathExtension == "json" {
          LottieAnimation.loadedFrom(url: url) { [weak self] animation in
              guard let self else { return }
              if let animation {
                  self.animationView?.animation = animation
                  self.animationView?.loopMode = .loop
                  animationView.imageProvider = BundleImageProvider(bundle: Bundle.main, searchPath: nil)
                  animationView.play()
                  label.text = "Animation shown: URL JSON"
              }
          }
      } else {
          DotLottieFile.loadedFrom(url: url) { [weak self] result in
              guard let self else { return }
              if case .success(let dotLottie) = result {
                  self.animationView?.loadAnimation(from: dotLottie)
                  self.animationView?.animationLoaded = { [weak self] animationView, _ in
                      animationView.loopMode = .loop
                      animationView.play()
                      self?.label.text = "Animation shown: URL DotLottie"
                  }
              }
          }
      }
  }
```

The SwiftUI `LottieView` doesn't have this issue, because we switch back to the user-provided `AnimationImageProvider` after switching away from a dotLottie animation.
