### ISSUE TITLE
Lottie iOS - Cocoapods is not working (Internal Server Error)

### ISSUE THREAD

**Issue by burakeray** [airbnb/lottie-ios#2266]
Hello,
https://cocoapods.org/pods/lottie-ios
It returns "Internal Server Error"

When we try to "pod update", it is not working.
Could you please solve this?

Thank you so much.

**Comment by calda** [comment]
This is an issue with the cocoapods website / server, and not specific to Lottie (it affects all other pods as far as I can tell). Seems like a temporary outage to me.
