### ISSUE TITLE
Size is not propagated from LottieView to placeholder in SwiftUI

### ISSUE THREAD

**Issue by denandreychuk** [airbnb/lottie-ios#2267]
Body of LottieView is wrapper into ZStack, which cause placeholder not to inherit frame size from parent. 

Example:
```
LottieView {
    try await DotLottieFile.named("animation")
} placeholder: {
    Image("placeholder")
        .resizable()
}
.resizable()
.frame(height: 100)
```

**Comment by annie-gupta** [comment]
Hi @denandreychuk , Please assign this issue to me. Thank you.

**Comment by denandreychuk** [comment]
@annie-gupta unfortunately only someone from team members can do the assignments, but I think that you can make a fork and push the PR to fix this
