### ISSUE TITLE
iOS only - missing some parts

### ISSUE THREAD

**Issue by gongxiaokai** [airbnb/lottie-ios#2270]
## Which Version of Lottie are you using?

 Lottie 4.3.4

## Expected Behavior 
Lottie JSON files to animate same on iOS as it does on web.

## Actual Behavior
The animations seem to be missing some parts

## Animation JSON
[message_gift.json](https://github.com/airbnb/lottie-ios/files/13815318/message_gift.json)

**Comment by kolyan94** [comment]
Same here, only the small part of the animation renders on iOS, but works well on Android and web

**Comment by calda** [comment]
Thanks for the report, fixed in https://github.com/airbnb/lottie-ios/pull/2276
