### ISSUE TITLE
no rule to process file 'PrivacyInfo.xcprivacy' of type 'text.xml' with CocoaPods

### ISSUE THREAD

**Issue by rradenkov-paysafe** [airbnb/lottie-ios#2297]
When integrating Lottie 4.4.0 with CocoaPods a build warning is displayed that PrivacyInfo.xcprivacy can not be processed.
Reason for this is that 'PrivacyInfo.xcprivacy' is included in source files and Xcode treats it as such.
```
s.source_files = 'Sources/**/*'
```

## Which Version of Lottie are you using?

Lottie 4.4.0

## Expected Behavior 
No Xcode warnings are shown

## Actual Behavior
Following Xcode build warning is displayed
`no rule to process file '.../lottie-ios/Sources/PrivacyInfo.xcprivacy' of type 'text.xml' for architecture 'x86_64'`

## Animation JSON
N/A

**Comment by VaslD** [comment]
Are you using Xcode 14? Privacy manifests (`*.xcprivacy`) are introduced in Xcode 15 so I don't know how Xcode 14 handles them.

I just upgraded to Lottie 4.4, with the latest Xcode (15.2) I did not encounter this error.

**Comment by rradenkov-paysafe** [comment]
I am using Xcode 15.2 as well.
![lottie-cocoapods-warning](https://github.com/airbnb/lottie-ios/assets/72293299/f206d117-b470-4977-9878-c2bee56ef83a)

Other libraries that added Privacy manifests don't include it in sources and I don't see build warnings: https://github.com/onevcat/Kingfisher/blob/ac3268e519bd81c333ce7a8d69d56ab66081fa60/Kingfisher.podspec#L38

**Comment by picselladmin** [comment]
Facing the same issue here

**Comment by calda** [comment]
This was fixed by https://github.com/airbnb/lottie-ios/pull/2307 right?

**Comment by OgabekDev** [comment]
I am using LottieView via Cocoapods. Could you tell me what the solution is? I am updating the pods but I haven't gotten a result.

**Comment by kronenthaler** [comment]
I see the fixed merged into the master branch, but can you release a new version with this change?

**Comment by calda** [comment]
Just released 4.4.1 https://github.com/airbnb/lottie-ios/releases/tag/4.4.1

**Comment by OgabekDev** [comment]
Thank you. I updated the pod

**Comment by OgabekDev** [comment]
[!] Error installing lottie-ios
[!] /usr/bin/git clone https://github.com/airbnb/lottie-ios.git /var/folders/3l/f24m17z140bbv86_dsgy4l0w0000gn/T/d20240222-12056-6fl9q6 --template= --single-branch --depth 1 --branch 4.4.1

Cloning into '/var/folders/3l/f24m17z140bbv86_dsgy4l0w0000gn/T/d20240222-12056-6fl9q6'...
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 5122 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

There is a kind of error while updating pod

**Comment by gezquinndesign** [comment]
Don't know how much of an issue this actually is, but FYI, it's also happening on the latest version of lottie-react-native (v6.7.0) - might need to upgrade the dependency to the latest version of lottie-ios.

**Comment by TheRogue76** [comment]
> Don't know how much of an issue this actually is, but FYI, it's also happening on the latest version of lottie-react-native (v6.7.0) - might need to upgrade the lottie-ios dependency to the latest version.

LRN maintainer here. lottie-react-native 6.7.0 is using lottie-ios 4.4.1. Please open an issue back in the repo and i will take a look.

**Comment by gezquinndesign** [comment]
@TheRogue76 Looks like this is sorted in lottie-react-native 6.7.2.
