### ISSUE TITLE
Separate Dimensions - Position Transform

### ISSUE THREAD

**Issue by Audiobrad** [airbnb/lottie-ios#23]
I was using Facebook Keyframes and have recently been testing lottie. I've encountered a few issues with exports I specifically adapted to be used in Keyframes that render correctly in bodymovin and keyframes, but not in lottie. After some trouble shooting I was able to fix the problem by un-separating the dimensions for the position transforms on layers that had previously been separated. 

Separating position transform dimensions is often a significant part of my workflow and it would be useful to maintain this functionality.

**Comment by buba447** [comment]
We're hoping to add this in the next dot release

**Comment by gpeal** [comment]
Android will support this as well in the next release

**Comment by buba447** [comment]
@Audiobrad Just added into master! Will be in the next cocoa pod release!

**Comment by revolter** [comment]
@buba447, Could you provide an estimate date for the next release?
