### ISSUE TITLE
`PrivacyInfo.xcprivacy` is not included in `lottie-spm` repo

### ISSUE THREAD

**Issue by ryo0126** [airbnb/lottie-ios#2308]
## Which Version of Lottie are you using?

Lottie 4.4.0

## Description

I'm using lottie iOS via `lottie-spm` repo, but `PrivacyInfo.xcprivacy` is not included in `lottie-spm` although it is included in `lottie-ios` repo.
https://github.com/airbnb/lottie-spm

As you can see it in the URLs below, Package.swift in `lottie-ios` includes `PrivacyInfo.xcprivacy`, but Package.swift in `lottie-spm` doesn't.
https://github.com/airbnb/lottie-spm/blob/main/Package.swift
https://github.com/airbnb/lottie-ios/blob/master/Package.swift

Why isn't it included in `lottie-spm`?
Is it better to use `lottie-ios` in SPM instead of `lottie-spm` until it gets included in `lottie-spm`?

**Comment by calda** [comment]
Yes, that's right. The privacy manifest is included in the Lottie.xcframework that is downloaded.

If Xcode doesn't properly detect / handle this (e.g. when compiling the overall privacy info for your app) please let us know!

**Comment by ryo0126** [comment]
Thank you for your responses.

> "Instead of downloading the full git history of Lottie and building it from source, the lottie-spm repo just contains a pointer to the precompiled XCFramework included in the [latest lottie-ios release](https://github.com/airbnb/lottie-ios/releases/latest) (typically ~8MB)."

I'm sorry I misunderstood meaning of this.
I checked `artifacts` directory in Xcode's `DerivedData` and could find `PrivacyInfo.xcprivacy` inside `Lottie.xcframework` directory.

Thank you so much.

**Comment by Younghun-Jeong** [comment]
ex) swift package manager - Firebase
Firebase / FirebaseDynamicLinks / Sources / Resources / PrivacyInfo.xcprivacy is Exist!!

I think lottie-spm need same file too.
