### ISSUE TITLE
Warning in Xcode when using Lottie 4.4.0 with cocoa pods

### ISSUE THREAD

**Issue by cweymann** [airbnb/lottie-ios#2309]
## Which Version of Lottie are you using?

Lottie 4.4.0

## Expected Behavior 
no warnings

## Actual Behavior
Xcode (15.2.0) warning when building (used cocoa pods 1.14.3 for integration):

invalid character in Bundle Identifier. This string must be a uniform type identifier (UTI) that contains only alphanumeric (A-Z,a-z,0-9), hyphen (-), and period (.) characters.

## Comment

Of course this is a minor issue, but I assume it's easily fixable. 

In my tests I could fix the issue by removing the underscore from the bundle identifier in the lottie-ios-Lottie_Privacy target 

Thanks

## Animation JSON

not an animation related issue

**Comment by calda** [comment]
https://github.com/airbnb/lottie-ios/pull/2317 should fix this
