### ISSUE TITLE
Issue using multiple trim path

### ISSUE THREAD

**Issue by loulouchab** [airbnb/lottie-ios#231]
Hello team, 
I have an issue with my animation/export and I don't understand why... Is it from the AE file or the export ?
This is the animation I want :
![anim-logo](https://cloud.githubusercontent.com/assets/28431447/25738118/a3d06838-317b-11e7-87e9-0b26ace9723a.gif)

And this is the animation I have 
![animation-1](https://cloud.githubusercontent.com/assets/28431447/25738133/b89f2434-317b-11e7-8022-97e0708b7a1b.gif)

Any ideas ?

This my AE file 
[anim-logo-2.aep.zip](https://github.com/airbnb/lottie-ios/files/978412/anim-logo-2.aep.zip)

Thanks for your help :)

Louis

**Comment by loulouchab** [comment]
Hello again, 

Do you have any idea ?
Thank you very much

**Comment by therealsalih** [comment]
Hi! I took a look at your AE file and youre using the stroke and fill effects. At the moment Lottie does not support any effects

![image](https://user-images.githubusercontent.com/5893643/26984668-226e0d96-4cf5-11e7-8e7b-9be694b0615b.png)

You can however achieve the exact same effect using a stroke and trim paths within a shape layer and then using your original shape as a matte

![image](https://user-images.githubusercontent.com/5893643/26984831-cb5fe118-4cf5-11e7-8de0-82e9bea9fc36.png)
