### ISSUE TITLE
Issue with Animation Rendering

### ISSUE THREAD

**Issue by geoffgerman** [airbnb/lottie-ios#232]
So, running into some issues with rendering art in the JSON file here. Our AE file is setup with Shape layers and trim paths and we're running into art on layers staying present even after they are completed on the timeline (explosions). Also, having an issue where the "THANKS" type has the counter (triangle in the middle of A) not knocking out. Any help you could provide would be great. : )
[02 Working animations.zip](https://github.com/airbnb/lottie-ios/files/980007/02.Working.animations.zip)

**Comment by buba447** [comment]
Hello! The layers bug should now be fixed (layers not disappearing).
We are currently working to add support for trim paths (which will knock out that triangle in the middle)

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
