### ISSUE TITLE
module map 'xxx/lottie-ios/Lottie.modulemap' not found

### ISSUE THREAD

**Issue by mistdon** [airbnb/lottie-ios#2323]
## Which Version of Lottie are you using?

Lottie 4.4.0
Xcode: 15.2
Mac OS: Mac Sonoma 14.2.1 (23C71)

## Expected Behavior 
Xcode Archive success.

## Actual Behavior
Everything works on Xcode14.3, When I upgrade Xcode to 15.2
If I Run Build , everything is OK,
But When I archive to Release, there are errors below:

module map file '/Users/shen/Library/Developer/Xcode/DerivedData/lofter-avlgcrseiffvzihiubzldcztqeis/Build/Products/Release-iphonesimulator/lottie-ios/Lottie.modulemap' not found

no such module lottie

## Animation JSON
My Podfile like this:
install! 'cocoapods', :disable_input_output_paths => true
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'
inhibit_all_warnings!

project 'MyProject.xcodeproj'
target 'MyProject' do
  use_modular_headers!

  pod 'lottie-ios', '4.4.0'

end

post_install do |installer|
  if flutter_build_with_framework == 0
     flutter_post_install(installer) if defined?(flutter_post_install)
  end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |configuration|
      target.build_settings(configuration.name)['ONLY_ACTIVE_ARCH'] = 'NO'
      configuration.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      configuration.build_settings['ENABLE_BITCODE'] = 'NO'
      # Pod中的库，不允许自动生成证书
      configuration.build_settings['CODE_SIGN_STYLE'] = 'Manual'
      configuration.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      if configuration.name == 'Debug'
        configuration.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)','DEBUG=1']
      elsif configuration.name == 'Test'
        configuration.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)','TEST=1']
      elsif configuration.name == 'Release'
        configuration.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
      end
    end
  end
end

Can anyone helps me to find out the reason?

**Comment by calda** [comment]
Please share a sample project that demonstrates the issue
