### ISSUE TITLE
[guide] how to custom ui, eg: txt

### ISSUE THREAD

**Issue by yanchaoGan** [airbnb/lottie-ios#233]
how can i change animate layer 's txt ， just for dynamic update。 
i cannot find any code involve CATextLayer,  if do something like this, may i change lib code?

**Comment by buba447** [comment]
We dont currently support text rendering.

**Comment by Joy-Chiang** [comment]
@buba447 Are there any concrete progress? About support text layer.

**Comment by serhii-londar** [comment]
@buba447 How about images? Is it possible to insert custom image to animation?

**Comment by buba447** [comment]
@serhii-londar It sure is! Check out https://github.com/airbnb/lottie-ios/blob/master/lottie-ios/Classes/PublicHeaders/LOTAnimationView.h#L153

**Comment by RishabhTayal** [comment]
Is there a roadmap for this feature? I believe this feature will be helpful to a lot of people.

**Comment by Leocata14** [comment]
Any update on text rendering? Would be extremely helpful

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
