### ISSUE TITLE
SPM: skipping cache due to an error

### ISSUE THREAD

**Issue by gerchicov-vg** [airbnb/lottie-ios#2335]
## Which Version of Lottie are you using?

Lottie 4.4.1

## Expected Behavior 
SPM is finished with no error

## Actual Behavior
On package resolving
```
skipping cache due to an error: https://github.com/airbnb/lottie-ios: An unknown error occurred. http parser error: stream ended at an unexpected time (-1)
```
In Xcode it is 52% downloaded and download is restarted again and again.

**Comment by calda** [comment]
This sounds like an SPM package download issue, not an issue with Lottie itself.

You could consider trying to use the `lottie-spm` package rather than `lottie-ios`. `lottie-spm` is a smaller download so may be less likely to hit this issue.
