### ISSUE TITLE
CFBundleShortString does not reflect the Lottie version

### ISSUE THREAD

**Issue by jesus-mg-ios** [airbnb/lottie-ios#2336]
## Which Version of Lottie are you using?

Lottie 4.4.1 binary xcframework. https://github.com/airbnb/lottie-ios/releases/download/4.4.1/Lottie-Xcode-15.2.xcframework.zip

## Expected Behavior 
CFBundleShortString: 4.4.1

## Actual Behavior
CFBundleShortString: 1.0

**Comment by calda** [comment]
Where / how are you accessing the `CFBundleShortString`?

**Comment by jesus-mg-ios** [comment]
To the plist xcframework or framework inside it. For using a cache dependency manager in-house solution.

**Comment by calda** [comment]
Fixed in #2341.

You could download an updated XCFramework bundle with the correct version number from the PR's build artifacts: https://github.com/airbnb/lottie-ios/actions/runs/8254291973/artifacts/1319873297
