### ISSUE TITLE
Negative rotation combined with negative scale not working 

### ISSUE THREAD

**Issue by jorgeneidem** [airbnb/lottie-ios#234]
If you flip a shape horizontally in After Effects by setting the scale x-value to negative, and then try to animate a negative rotation (-180° or -1x), it will not rotate in the expected direction on iOS (it will revert to a positive rotation). 

Negative rotation is working on its own. Negative scale x-value is working on its own. But the combination does not work.

This problem does not exist in After Effects preview, in Lottie-Android or on lottiefiles.com web preview. So a preview of negative rotation + negative scale will look OK until you play on your iOS device, where it will rotate the wrong way.

**Comment by jorgeneidem** [comment]
tl;dr
![ezgif-2-5ae40219f5](https://cloud.githubusercontent.com/assets/4020663/25904457/9747b616-359f-11e7-969f-fe26af5a2924.gif)

**Comment by buba447** [comment]
Will look into this soon! Sorry for the trouble!

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!

**Comment by ksnilsson** [comment]
Having similar issue with negative rotation not coming through in .json. Plays fine when rendered traditionally, and all positive rotation works correctly.
