### ISSUE TITLE
Bezier path is unexpectedly missing final segment

### ISSUE THREAD

**Issue by barendu** [airbnb/lottie-ios#2342]
## Which Version of Lottie are you using?

Lottie 4.4.1

## Actual Behavior

Uploading RPReplay_Final1710824469.MP4…

## Animation JSON

[data.json](https://github.com/airbnb/lottie-ios/files/14645577/data.json)

**Comment by barendu** [comment]
[Uploading loading_video_UHD…]()

**Comment by chengongwen** [comment]
从2.2.5升级到4.4.1 lottie，相同lottie资源，4.4.1加载有问题，加载的黑色元素被丢失了

**Comment by barendu** [comment]
我的是动画不对

**Comment by barendu** [comment]
Uploading RPReplay_Final1710824469.MP4…

**Comment by calda** [comment]
For future reference, this seems to be an issue where the bezier path is unexpectedly missing its last element:

<img width="1100" alt="image" src="https://github.com/airbnb/lottie-ios/assets/1811727/c52c70c1-1f24-4eaa-b0a5-fa2b23496246">

(left is the iOS main thread rendering engine, right is lottie-web)

**Comment by calda** [comment]
Here's a fix: https://github.com/airbnb/lottie-ios/pull/2418
