### ISSUE TITLE
How to clear LOTAnimationCache

### ISSUE THREAD

**Issue by LaughingJack** [airbnb/lottie-ios#235]
What is the suggested mechanism for clearing the animation cache? I currently have a pair of somewhat large animations that I only need to run once and don't want to keep around from memory management purposes. How it it suggested to clear out the cache and free up our run time memory?

**Comment by buba447** [comment]
Ohh! this is a good suggestion. Will added it to future enhancement.
The cache definitely needs an upgrade to support different caching strategies. Sorry!

**Comment by bellchen** [comment]
any schedule about this? Very eager to get this function
