### ISSUE TITLE
Different CALayer performances of different types of Lottie

### ISSUE THREAD

**Issue by Yookiely** [airbnb/lottie-ios#2352]
lottie-ios 4.3.0
I would like to use the following code to obtain a screenshot of Lottie View
`           UIGraphicsBeginImageContextWithOptions(animationView.bounds.size, false, 0)
            if let context = UIGraphicsGetCurrentContext() {
                animationView.layer.render(in: context)
                let image = UIGraphicsGetImageFromCurrentImageContext()
                UIGraphicsEndImageContext()
            }`
But it will exhibit different results due to different lottie types. 
If I use lottie with Base64 Image, I can't get the correct Image.
Example. 

issue_1800.json in Project Example

I want to have
<img width="406" alt="image" src="https://github.com/airbnb/lottie-ios/assets/32568756/6952fc7d-014a-450e-88a2-77d1782f4ba9">
but real...
<img width="943" alt="image" src="https://github.com/airbnb/lottie-ios/assets/32568756/186ef18b-4968-4732-9b0e-275ca1b683ab">

And if I use the lottie source file which doesn't have base64 Img, It will be correct.

So why? Could the lottie source file with base64 Img use other way to get the correct snapshot?

**Comment by Yookiely** [comment]
BTW LottieAnimationLayer is also not work.

**Comment by calda** [comment]
Here is some discussion: https://github.com/airbnb/lottie-ios/discussions/1769#discussioncomment-3860672. This is a known limitation of the Core Animation rendering engine.
