### ISSUE TITLE
Need Privacy Info included in the SDK

### ISSUE THREAD

**Issue by parvez-keeptruckin** [airbnb/lottie-ios#2353]
As per the [requirements](https://developer.apple.com/support/third-party-SDK-requirements/) from Apple, the Lottie iOS SDK will have to include the `PrivacyInfo.xcprivacy` in it. This is needed since Apple listed `lottie` as one of the SDKs that require to include privacy info as per the [list](https://developer.apple.com/support/third-party-SDK-requirements/).

**Comment by calda** [comment]
We have a privacy manifest here, which is included in the latest version of lottie-ios: https://github.com/airbnb/lottie-ios/blob/master/Sources/PrivacyInfo.xcprivacy

lottie-spm isn't integrated with it correctly according to https://github.com/airbnb/lottie-ios/issues/2344, but we'll fix that soon
