### ISSUE TITLE
CGPointExtension causes crash

### ISSUE THREAD

**Issue by Rspoon3** [airbnb/lottie-ios#2356]
`CGPoint.init(value:)` is crashing in `CGPointExtension.swift`. This stems from creating a `LottieAnimation` from a file path. This work is being kicked off from a `AsyncStream` on a background thread. This is happening on multiple iOS devices and iOS 15, 16, and 17 over the last 90 days.

The Firebase stack trace points to Line 20
<img width="709" alt="Screenshot 2024-04-01 at 11 18 13 AM" src="https://github.com/airbnb/lottie-ios/assets/42879920/13c5a464-d8b2-4074-8567-94f6a04e2d12">

## Which Version of Lottie are you using?

Lottie 4.2.0 and 4.4.1

## Expected Behavior 
Creating a LottieAnimation should not cause a crash.

## Actual Behavior
Creating a LottieAnimation occasionally causes a crash.

**Comment by calda** [comment]
For us to investigate, share a sample project that demonstrates this crash.

**Comment by Rspoon3** [comment]
@calda I have created a demo project that uses the same manner our application, but I cannot reproduce the crash with it. However I’m not to surprises by this as no-one within my company can replicate the original crash in the first place. Should I reopen this issue with demo project or will it be marked as closed/not reproducible?

**Comment by calda** [comment]
If the sample project doesn't reproduce the crash then no need to share or re-open this issue. Thanks for taking a closer look though!
