### ISSUE TITLE
pod lib lint error

### ISSUE THREAD

**Issue by shijian123** [airbnb/lottie-ios#2362]
The following build commands failed:
    	Ld /Users/xxx/Library/Developer/Xcode/DerivedData/App-bbdiuvavmfbqeyafsistcpmwcfaz/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/lottie-ios.build/Objects-normal/x86_64/Binary/Lottie normal x86_64 (in target 'lottie-ios' from project 'Pods')

xcode 15.0.1 M2

**Comment by calda** [comment]
For us to investigate, share sample project that demonstrates this error.
