### ISSUE TITLE
Privacy manifest

### ISSUE THREAD

**Issue by yunsanch** [airbnb/lottie-ios#2368]
## Which Version of Lottie are you using?

Lottie 4.4.1

## Expected Behavior 
have a privacy manifest manifest to adhere to [Apple privacy policy ](https://developer.apple.com/support/third-party-SDK-requirements/)

## Actual Behavior
there is not privacy manifest

**Comment by calda** [comment]
4.4.1 and 4.4.2 include a privacy manifest: https://github.com/airbnb/lottie-ios/blob/master/Sources/PrivacyInfo.xcprivacy
