### ISSUE TITLE
Animation works on old version of Lottie, but not new version

### ISSUE THREAD

**Issue by AdamMak** [airbnb/lottie-ios#237]
I have recently added Lottie to my project as would like to use some animations in my app. However I the animation will not load properly, I have an animation where a white circle appears and an icon appears in the middle before disappearing. 

On the old version of the framework downloaded from here

https://github.com/airbnb/lottie-ios

It shows you add the animation with this code

> LOTAnimationView *animation = [LOTAnimationView animationNamed:@"Lottie"];
> [self.view addSubview:animation];
> [animation playWithCompletion:^(BOOL animationFinished) {
>   // Do Something
> }];

If I download this project, and add my code in there, it works fine. However, when I add the Lottie project via Pods, it must be a different version as instead you have to use this

> LAAnimationView *animation = [LAAnimationView animationNamed:@"toaster_on"];
> [self.view addSubview:animation];
> [animation playWithCompletion:^(BOOL animationFinished){
>   // Do Something        
>  }];

With the new version of the code, my animation does not run properly. White circle appears not icon never appears in the middle. Could anyone help explain why the old code works, but the new one does not?

Any help would be much appreciated!

**Comment by AdamMak** [comment]
I managed to get this working by downloading the zip file of Lottie which seems to be a different version than the one installed via cocoapods. So basically if you want to make sure your animation works, download the zip file from Github and add manually add Lottie to your project.

Does anyone know why the version downloaded via cocoapods does not work properly?

**Comment by Dreadrik** [comment]
It is a bug that has been fixed in master, but it has not yet been tagged in a release.
Can we please have a new CocoaPods release?

**Comment by jondwillis** [comment]
If you can't wait:

```pod 'lottie-iost', :git => 'https://github.com/airbnb/lottie-ios.git'```

**Comment by buba447** [comment]
We will be adding a new release tomorrow!
