### ISSUE TITLE
File Timestamp Required Reason — Should it be C617.1 instead of 3B52.1 ?

### ISSUE THREAD

**Issue by macdrevx** [airbnb/lottie-ios#2371]
## Which Version of Lottie are you using?

Lottie 4.4.1

## Expected Behavior 
Privacy Manifest lists C617.1 as the reason for using file timestamp APIs

## Actual Behavior
Privacy Manifest lists 3B52.1 as the reason for using file timestamp APIs

## Discussion

Lottie 4.4.1's privacy manifest lists 3B52.1 as the required reason for using file timestamp APIs. Apple [defines](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api) this reason as:

> Declare this reason to access the timestamps, size, or other metadata of files or directories that the user specifically granted access to, such as using a document picker view controller.

This reason doesn't seem to fit with my understanding of Lottie as dealing merely with playback of animation files, so I'm wondering whether it should actually be C617.1:

> Declare this reason to access the timestamps, size, or other metadata of files inside the app container, app group container, or the app’s CloudKit container.

At least for our use case, this seems right since we bundle animation files with our app and then play them back with Lottie (without the end-user specifically granting access to those files since they're in the app bundle).

**Comment by calda** [comment]
Thanks for the suggestion, you're correct. Updated in https://github.com/airbnb/lottie-ios/pull/2380.
