### ISSUE TITLE
Privacy Manifest issue

### ISSUE THREAD

**Issue by huemae** [airbnb/lottie-ios#2372]
## Which Version of Lottie are you using?

Lottie 4.4.2(ab15129d567eda5da0631fcba23de60144a612f4)

## Expected Behavior 
When i use "Generate Privacy Report" in xcode with mentioned version of Lottie

Maybe report should contain information

## Actual Behavior
This report does not contain any information about Lottie at all

**Comment by calda** [comment]
This is expected, see the discussion here: https://github.com/airbnb/lottie-ios/discussions/2364#discussioncomment-9007397
