### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by ealeksandrov** [airbnb/lottie-ios#2391]
I'm seeing unexpected broken images for a set of icons that we use (all of them - some tooling/export issue?).
They look fine on the web.

Tested on Core Animation and Main Thread engines.

## Which Version of Lottie are you using?

Lottie 4.4.3

## Screenshots

Expected | Actual
--|--
<img width="150" src="https://github.com/airbnb/lottie-ios/assets/3132438/d206d56a-50d7-4676-a1d3-07154d4adafb">|<img width="150" src="https://github.com/airbnb/lottie-ios/assets/3132438/7e74cea7-916f-416b-9b64-e3689e8f6804">

## Animation file

[crown_traditional.lottie.zip](https://github.com/airbnb/lottie-ios/files/15154555/crown_traditional.lottie.zip)

**Comment by dannyhertz** [comment]
Also seeing this issue!

**Comment by ldakhoa** [comment]
Also seeing this issue, lottie 4.4.3

**Comment by faizan-ahsan-brainx** [comment]
you can use version 3.5.0 it will work on it

**Comment by calda** [comment]
This is the same issue as https://github.com/airbnb/lottie-ios/issues/2345. Working on a fix and tracking it there.

**Comment by ealeksandrov** [comment]
We found a workaround for our case.
Removing "Offset Path" elements from our compositions (in After Effects source, before the export) resolves the issue.

**Comment by calda** [comment]
For this animation that renders incorrectly, was it exported directly from After Effects, or was it exported from some other tool like the lottie files editor? If it was exported directly from after effects, could you share the AE file?

**Comment by ealeksandrov** [comment]
@calda yes, it comes from After Effects. I've sent the AE file to the email address from your GH profile, hope that helps.
