### ISSUE TITLE
Hi @calda , we noticed that the issue also happens with gradients.

### ISSUE THREAD

**Issue by chrischang26** [airbnb/lottie-ios#2396]
Hi @calda , we noticed that the issue also happens with gradients.
Instead of not showing any keypaths with 4.4.0 and above (we are on 4.4.1), we see duplicated gradient keypaths, hence it's displaying black shadow where we apply custom gradient.

_Originally posted by @chrischang26 in https://github.com/airbnb/lottie-ios/issues/1988#issuecomment-2089327030_

**Comment by calda** [comment]
For us to take a look, share a sample animation file and sample code that demonstrates the issue.
