### ISSUE TITLE
Problem in rendering combined or merge paths when shape is filled.

### ISSUE THREAD

**Issue by Mushrankhan** [airbnb/lottie-ios#240]
![screen shot 2017-05-20 at 4 57 50 pm](https://cloud.githubusercontent.com/assets/16305446/26275431/a2ef2d06-3d7d-11e7-96f2-1ef60469e075.png)

Anyone have solution !!

**Comment by buba447** [comment]
We are currently adding support for merge paths!

**Comment by buba447** [comment]
@samiam2017 We are hoping in the next month!

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
