### ISSUE TITLE
App crashing on lottie 4.4.3

### ISSUE THREAD

**Issue by asadkazmi-mset** [airbnb/lottie-ios#2406]
I update lottie to its latest version for privacy manifest, after updating to 4.4.3 xcode asked me to change some of the file names
        Previous  -> Latest
1-  Animation.named(animationName) -> LottieAnimation.named(animationName)
2- @IBOutlet weak var animationView: AnimationView! -> @IBOutlet weak var animationView: LottieAnimationView!

## Which Version of Lottie are you using?

Lottie 4.4.3 using swift package manager

## Expected Behavior 
App should be running smoothly like on the older version

## Actual Behavior
on actual app is crashing and giving me some threading error
<img width="1458" alt="Screenshot 2024-05-13 at 12 13 41 PM" src="https://github.com/airbnb/lottie-ios/assets/130658996/4087ace1-5ba0-49b7-a846-67268f9b3abe">

## Animation JSON
[onboarding-reg-preselector.json](https://github.com/airbnb/lottie-ios/files/15290676/onboarding-reg-preselector.json)

**Comment by calda** [comment]
Are you using a storyboard? If so did you rename `AnimationView` to `LottieAnimationView` in your storyboard file as well? If those references aren't updated the app will crash like this.

**Comment by asadkazmi-mset** [comment]
@calda  I had updated that, but didn't recreate the connection, 
I recreated the connection and it is working now, Thank you :-)

**Comment by ASContis** [comment]
@calda I have updated name in storyboard as well. But still it crashing with latest version 4.5.0
