### ISSUE TITLE
Lottie Animation Rendering issue on iOS and Android

### ISSUE THREAD

**Issue by gitercn** [airbnb/lottie-ios#2417]
We've encountered an issue with Lottie animations that is similar to the one reported in [airbnb/lottie-ios#2391](https://github.com/airbnb/lottie-ios/issues/2391). However, their Lottie files are different from this one, and I'm not sure if the underlying reasons are the same. So we submitted this issue.

The animations appear differently when viewed on Android and iOS devices compared to the desktop version. On mobile platforms, the animations seem to have rendering issues, whereas on the desktop, they display correctly.

## Which Version of Lottie are you using?

Lottie 4.4.3

## Expected Behavior 
![Expected](https://github.com/airbnb/lottie-ios/assets/53464166/8938a067-34bf-4f6a-b63d-24552a980af9)

## Actual Behavior
![Screenshot_20240522-182845_Lottie](https://github.com/airbnb/lottie-ios/assets/53464166/90e3b987-0f35-4470-b28e-d829aac07dbc)

## Animation JSON
[demo.json](https://github.com/user-attachments/files/15532813/demo.json)

**Comment by calda** [comment]
Looks like the same issue as https://github.com/airbnb/lottie-ios/issues/2345 -- tracking this issue there.

**Comment by calda** [comment]
Quick question @gitercn, was this animation exported directly from after effects, or exported from another tool like the lottie files editor?
