### ISSUE TITLE
pod install fail

### ISSUE THREAD

**Issue by Andrew5** [airbnb/lottie-ios#2427]
[!] Error installing lottie-ios
[!] Failed to download 'lottie-ios': [!] /usr/bin/git clone https://github.com/airbnb/lottie-ios.git /var/folders/pn/sccp1m013_9d4y3ts8mx3cl00000gn/T/d20240612-12744-63adrg --template= --single-branch --depth 1

Cloning into '/var/folders/pn/sccp1m013_9d4y3ts8mx3cl00000gn/T/d20240612-12744-63adrg'...
fatal: unable to access 'https://github.com/airbnb/lottie-ios.git/': Failed to connect to 127.0.0.1 port 7890 after 0 ms: Couldn't connect to server

This often occurs, and other libraries can handle it, but this one cannot for china bei jing,I also hung up a network proxy

**Comment by calda** [comment]
This is most likely an issue with Cocoapods itself, rather than Lottie.
