### ISSUE TITLE
您好, 我们的UI设计师在AE文件用了图层透明度和外发光效果, 导致iOS播放动画闪屏

### ISSUE THREAD

**Issue by qxuewei** [airbnb/lottie-ios#243]
您好, 我们的UI设计师在AE文件用了图层透明度和外发光效果, 生成json文件, 导致iOS播放动画闪屏,请问有什么解决方案吗? 谢谢!

Hello, our UI designer in the AE file with a layer transparency and luminous effect, resulting in iOS playback animation splash screen. Thank you very much!

**Comment by dong108** [comment]
外发光不能用吧
