### ISSUE TITLE
Warning: group effect not supported

### ISSUE THREAD

**Issue by Kingson** [airbnb/lottie-ios#244]
I tried lottie on iOS device, but report warning to me, detail info below:
`2017-05-25 09:52:35.808 LottieDemo[1165:49593] -[LOTLayer _mapFromJSON:withCompBounds:withFramerate:withAssetGroup:]: Warning: group effect not supported: ADBE Numbers2 / 编号`
Any help to me, Thanks!

**Comment by CHPisces** [comment]
[LOTLayer _mapFromJSON:withCompBounds:withFramerate:withAssetGroup:]: Warning: fill effect not supported: ADBE Fill / 填充

**Comment by buba447** [comment]
Lottie doesnt support layer effects. Your composition has a layer with an effect attatched to it.

**Comment by UberJason** [comment]
Hi @buba447, not to necro this thread (keeping it a closed issue and not raising a new one), but I'm wondering if there are any plans to support layer effects like drop shadows in the future?
