### ISSUE TITLE
Crash malloc: Heap corruption detected, free list is damaged at 0x281305900 *** Incorrect guard value: 0

### ISSUE THREAD

**Issue by TttGggVv** [airbnb/lottie-ios#2458]
## Which Version of Lottie are you using?

Lottie 4.4.1
设备
型号：iPhone 8
屏幕方向：正面朝上
可用 RAM： 146.05 MB
操作系统
版本：16.7.8
屏幕方向：纵向
Jailbroken: No

[com.glazero.ios_issue_c0cdbdc992526f262ac2de53e98cb2c3_crash_session_6e83ec59a9f34a0c9c2c3bd8fb58c52c_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/16423495/com.glazero.ios_issue_c0cdbdc992526f262ac2de53e98cb2c3_crash_session_6e83ec59a9f34a0c9c2c3bd8fb58c52c_DNE_0_v2_stacktrace.txt)
[com.glazero.ios_issue_c0cdbdc992526f262ac2de53e98cb2c3_crash_session_6e83ec59a9f34a0c9c2c3bd8fb58c52c_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/16423498/com.glazero.ios_issue_c0cdbdc992526f262ac2de53e98cb2c3_crash_session_6e83ec59a9f34a0c9c2c3bd8fb58c52c_DNE_0_v2_stacktrace.txt)

**Comment by calda** [comment]
Could you share a sample project that reproduces this issue?

**Comment by TttGggVv** [comment]
Sorry, no. I saw it on the background Crash collection platform.
