### ISSUE TITLE
hello, why some .json file can not play ,even crash

### ISSUE THREAD

**Issue by 304164084** [airbnb/lottie-ios#246]
i download some .json file in www.lottiefiles.com. most of them can't play or show in my ipad. even thouth get crash. here some file address <https://www.lottiefiles.com/128-around-the-world, https://www.lottiefiles.com/91-mailsent>, you can try it . here is my code
`LAAnimationView *animation = [LAAnimationView animationNamed:@"Plane.json"];
    animation.frame = CGRectMake(0, 100, [UIScreen mainScreen].bounds.size.width, 700);
    [self.view addSubview:animation];
    animation.loopAnimation = YES;
    [animation playWithCompletion:^(BOOL animationFinished) {
        // Do Something
    }];`

**Comment by buba447** [comment]
I was not able to reproduce. Can you give us more information? What was the crash? What was the console log output?
