### ISSUE TITLE
Stutter when loading lottie in Lazy VStack 

### ISSUE THREAD

**Issue by sanchit-goel-swiggy** [airbnb/lottie-ios#2465]
## Which Version of Lottie are you using?

Lottie 4.5.0

Hi, I’m using a LottieView in my SwiftUI project, where I’m passing a URL to download the Lottie animation. This view is embedded in a LazyVStack. However, I’m experiencing significant UI lag when scrolling through the stack. Any suggestions on how to improve the performance or fix this issue? I have also tried downloading and caching the lottie file and loading the lottie from cache for subsequent loads, that is also not working properly.

```swift 
enum ImageViewType {
case image
case lottie
}

struct TestLottieView: View {

private let urlSession: URLSession = URLSession.shared
let data : [ImageViewType] = [.lottie, .image, .image, .image, .image, .lottie, .image, .image, .lottie, .image, .image, .image, .image, .image, .image, .lottie, .image]

var body: some View {
    ScrollView {
        LazyVStack {
            ForEach(data.indices, id: \.self) { index in
                switch data[index] {
                case .image:
                    ImageTempView()
                case .lottie:
                    LottieTempView()
                }
            }
        }
    }
}

}

struct LottieTempView: View {
var body: some View {
LottieView {
await LottieAnimation.loadedFrom(url: URL(string: "https://media-assets.swiggy.com/MERCHANDISING_BANNERS/LOTTIES/MERCH/2024/7/10/ff6c573d-0f94-45ff-90a2-5e7c3899bc22_Monsoon4.json")!)
} placeholder: {
Rectangle().fill(Color.red)
}
}
}

struct ImageTempView: View {
var body: some View {
Image("img1")
.resizable()
.frame(width: 300, height: 200)
}
}
```

## Actual Behavior
More evident when running it on a device/simulator

https://github.com/user-attachments/assets/1d6ad6b4-5f9a-4142-8eee-fc4a705c33d8

## Animation JSON

https://media-assets.swiggy.com/MERCHANDISING_BANNERS/LOTTIES/MERCH/2024/7/10/ff6c573d-0f94-45ff-90a2-5e7c3899bc22_Monsoon4.json

**Comment by calda** [comment]
This is better as a discussion in the existing thread: https://github.com/airbnb/lottie-ios/discussions/2464
