### ISSUE TITLE
Weird animation distortion

### ISSUE THREAD

**Issue by Azraiths** [airbnb/lottie-ios#2467]
Hello, 
Something weird is happening with animation in SwiftUI. Tried fixed frames, dynamic frames,, changing engine and etc.
 code is quite straightforward           

>   LottieView(animation: .named("loading-2"))
>                         .looping()

## Which Version of Lottie are you using?

Lottie 4.5.0

## Expected Behavior 

<img width="675" alt="Screenshot 2024-08-10 at 7 05 25 PM" src="https://github.com/user-attachments/assets/e5e71c88-0a88-4434-887c-9ac5a91500af">

## Actual Behavior

<img width="290" alt="Screenshot 2024-08-10 at 7 05 19 PM" src="https://github.com/user-attachments/assets/8cd7b7e6-343b-4303-9422-eb8b7d2bf60d">

## Animation JSON

[loading-2.json](https://github.com/user-attachments/files/16569316/loading-2.json)

**Comment by calda** [comment]
This looks like the same issue as https://github.com/airbnb/lottie-ios/issues/2345. Did you export this animation from the LottieFiles.com editor? This is a bug with the LottieFiles editor exporting an animation that is not spec compliant so is unsupported by iOS and Android.
