### ISSUE TITLE
Bug while rendering shape layers

### ISSUE THREAD

**Issue by ShaunShi** [airbnb/lottie-ios#247]
Hi team,
Thank you very much for your great job, and I'm so glad that my team are able to try out lottie animations in native iOS app.
I am an interaction designer and my team is working on a Chinese travelling App called "TongCheng". When we were testing on lottie, we found some issues and may need your help.
This is a loading animation on AE. I mainly get it work by trimming path of shape layers. Then I used bodymovin to render into a json file, which I've sent to _**lottie@airbnb.com**_  together with aep file as email attachment . The email is with the same title.
But it's kinda not working correctly. Let me show you more details:
![image](https://cloud.githubusercontent.com/assets/28948997/26446081/403a6bc0-4175-11e7-8a93-cd33f367cbf5.png)
this is what we see on AE at 02:02.

![image](https://cloud.githubusercontent.com/assets/28948997/26446126/67b22a3a-4175-11e7-9d5c-43e394f85ddc.png)
and this  is what we see on bodymovin preview at 61/75(the very same frame on AE).

But after we coding the json file out on iOS, we got this odd shape at the same frame:
![image](https://cloud.githubusercontent.com/assets/28948997/26446265/e46cfdac-4175-11e7-8e1f-1e3789534f05.png)

And what's more, we also got some odd shapes at other frames:
![image](https://cloud.githubusercontent.com/assets/28948997/26446301/0e40e594-4176-11e7-83b4-19383fea395c.png)
![image](https://cloud.githubusercontent.com/assets/28948997/26446315/20097232-4176-11e7-8873-812127a0a21c.png)

I don't know how to get this issue fixed. 
Really looking forward to your kind reply.
Thank you very much.

**Comment by ShaunShi** [comment]
Hello, is there anyone who can look into this and help me out? Thank you.

**Comment by buba447** [comment]
@ShaunShi Im happy to look into this for you!

**Comment by buba447** [comment]
Having looked into the file it seems that control points are being added to the mainlines layer on frame 62, which is causing the issue. We currently dont dependably support adding of control points. 

<img width="506" alt="screen shot 2017-06-13 at 2 42 42 pm" src="https://user-images.githubusercontent.com/1163980/27106148-042b136a-5047-11e7-9442-596585463e38.png">
<img width="440" alt="screen shot 2017-06-13 at 2 42 46 pm" src="https://user-images.githubusercontent.com/1163980/27106147-04294490-5047-11e7-9a1a-41bd4da73dc6.png">

**Comment by ShaunShi** [comment]
@buba447 I really appreciate your reply. I got my animation modified a little bit. And seems it's working correctly on the iOS simulator. Will try it out on our next App release. =P
BTW,could you please let me know is removing of path vertices supported in Lottie now?

**Comment by buba447** [comment]
@ShaunShi Great! glad it worked out! We dont support it yet but we are targeting it for the next big release (2.0)
