### ISSUE TITLE
In Arabic, the text cannot be displayed.

### ISSUE THREAD

**Issue by alisamili** [airbnb/lottie-ios#2473]
## Which Version of Lottie are you using?

Lottie 3.3.0 & 4.3.3

## Expected Behavior 

In Arabic:
<img width="340" alt="image" src="https://github.com/user-attachments/assets/9554fbff-e498-4f61-b9b8-9c63c4a7b52c">
In others:
<img width="445" alt="image" src="https://github.com/user-attachments/assets/a5a8fb4d-2170-44c3-9f91-c741345276a5">
## Actual Behavior

                let replacements = ["#textnodea": getStringWithKey("xxx1"), "#textnodeb": getStringWithKey("xxx2")]
                let textProvider = DictionaryTextProvider(replacements)
                let animationView = AnimationView.init(animation: animation, textProvider: textProvider)
                animationView.contentMode = .scaleAspectFit
                animationView.loopMode = .playOnce
## Animation JSON

Sorry,unable to provide due to unavailable reasons.

**Comment by calda** [comment]
For us to take a look, share a sample animation with sample code demonstrating the issue
