### ISSUE TITLE
Why IOS7 not support but still normal rendering and play

### ISSUE THREAD

**Issue by liujianan901228** [airbnb/lottie-ios#248]
The library Support ios8 and above, but I use IOS7  phone can still normal rendering and play, could you tell me if this library is used in the engineering of IOS7 will have what problem?

**Comment by buba447** [comment]
Theoretically it should work with iOS7 buyt I havent fully tested it, which is why the library is set to ios8.

**Comment by zhangsn** [comment]
@buba447 Sad ಥ_ಥ。Got any plan to fully test it on iOS7?

**Comment by buba447** [comment]
It will work on ios 7 but rolling the project file back will have to be done manually as xcode no longer allows 7 as a selectable base SDK.
This is unofficial support.
