### ISSUE TITLE
Xcode 16 RC, iOS 18 App is Crashing

### ISSUE THREAD

**Issue by garima-swiggy** [airbnb/lottie-ios#2480]
## Which Version of Lottie are you using?

Lottie 4.3.3
Xcode version 16.0 RC
iOS18.0 - Beta

Happens intermittently for iOS 18.0 Beta (other devices)
Happens every time for iOS 18.1 Beta iPhone 15Pro

## Expected Behavior

Compiling without error

## Actual Behavior

App crashes with the following logs:

<img width="1211" alt="Screenshot 2024-09-17 at 11 31 10 AM" src="https://github.com/user-attachments/assets/e12ea362-ccab-4f5f-a9c3-8e68879cd6c0">

[stacktrace.txt](https://github.com/user-attachments/files/17023603/stacktrace.txt)

Usage: 

```/// LottieView extension supports the dotLottie and json format for lottie files for swiftUI
extension LottieView {
    init(lottieUrl: URL, placeholder: @escaping (() -> Placeholder), didLottieLoad: (((Result<Any, Error>)) -> Void)? = nil) {
        self.init {
            guard let animation = await getLottieAnimation() else {
                didLottieLoad?(.failure(LottieError.genericError))
                return nil
            }
            switch animation {
            case .json(let lottieAnimation):
                didLottieLoad?(.success(lottieAnimation))
                return lottieAnimation.animationSource
            case .dotLottie(let dotLottieFile):
                didLottieLoad?(.success(dotLottieFile))
                return dotLottieFile.animationSource
            }
        } placeholder: {
            placeholder()
        }
    }
}```

**Comment by calda** [comment]
Can you share a sample project that demonstrates this issue, with repro steps?

**Comment by CricHeroesiOS** [comment]
https://github.com/RevenueCat/purchases-ios/pull/4286

Replace withCheckedThrowingContinuation Calls With withUnsafeThrowingContinuation

**Comment by garima-swiggy** [comment]
On upgrading to iOS18.0 (stable version), the issue is not reproducible

**Comment by CricHeroesiOS** [comment]
We use withCheckedThrowingContinuation in our app as well 
sometime is crashing in  iOS18.0 (stable version) as well.
We are replacing this and testing same....

**Comment by Ovidiu-S** [comment]
It happens on IOS18.0 also, in a Flutter app

**Comment by calda** [comment]
It sounds like this was an issue affecting iOS 18 betas, which has since been fixed: https://developer.apple.com/forums/thread/761580
