### ISSUE TITLE
Crashes while using JSON below. Same json works on android app but crashes on iOS. 

### ISSUE THREAD

**Issue by riddhima** [airbnb/lottie-ios#249]
https://gist.github.com/riddhima/35dc23cd7a86cad27931690e2d75d338

**Comment by therealsalih** [comment]
Hi! Can you send the AE file so we can get a look at whats under the hood?

**Comment by riddhima** [comment]
https://www.dropbox.com/s/6swt0q3x4lwnv4y/calendar-animation%20%281%29.aep?dl=0

**Comment by buba447** [comment]
Fix found here https://github.com/airbnb/lottie-ios/pull/257

**Comment by riddhima** [comment]
@buba447 Thanks. When will the fix be released?
