### ISSUE TITLE
Methods don't follow swift 3 guidelines

### ISSUE THREAD

**Issue by arronhunt** [airbnb/lottie-ios#25]
`let animationView = LAAnimationView.animationNamed(animationNamed: "foobar")`

should really be

`let animationView = LAAnimationView.animation(named: "foobar")`

https://swift.org/documentation/api-design-guidelines/

**Comment by chefnobody** [comment]
If @buba447's choice of Obj-C was intentional, I would think that the API is meant to look like an API for the language in which it was written rather than an API for a language it might be bridged to. I could be wrong though.

**Comment by tskulbru** [comment]
In instances (like the one mentioned) where the auto generated swift method name isn't following the Swift naming conventions, the API should define its own override using `NS_SWIFT_NAME`.

Its not a major issue, but still. Would be nice if the library followed proper naming conventions.

https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html#//apple_ref/doc/uid/TP40014216-CH10-ID162
