### ISSUE TITLE
Lottie support for AE Repeater

### ISSUE THREAD

**Issue by losifer** [airbnb/lottie-ios#250]
Super excited about using Lottie for the first time with my own files. Added into Xcode only to see that the shape repeater support doesn't transfer. I noticed this was a request in the Android repo so I thought I'd add to iOS.

Great stuff though... whenever you can, honestly y'all are doing a lot already!

Thanks again.
Los

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!

**Comment by spearmootz** [comment]
@buba447 are shapre repeaters supposed to be working?
its not for ios, im just wondering because there is another post saying it doesnt work and you guys know and are working on it.
