### ISSUE TITLE
Failed to build module with lottie-ios

### ISSUE THREAD

**Issue by MuthuHere** [airbnb/lottie-ios#2505]
## Which Version of Lottie are you using?

'lottie-ios', '~> 4.5.0'

## Actual Behavior
<img width="404" alt="image" src="https://github.com/user-attachments/assets/40a5aa30-3b2b-4157-9fb1-162198c1291d">

unable to build

**Comment by calda** [comment]
Please share a sample Xcode project that demonstrates this issue

**Comment by MuthuHere** [comment]
[Lottie-Test.zip](https://github.com/user-attachments/files/17883003/Lottie-Test.zip)

here you go!
