### ISSUE TITLE
Floating point errors calculating keyframe end progress

### ISSUE THREAD

**Issue by aembury7** [airbnb/lottie-ios#2508]
## Which Version of Lottie are you using?

Lottie 4.4.2

## Expected Behavior 
Changing between markers without flickering/dropping frames.

To reproduce this issue, simply change from marker "voiceLoop1" to "voiceLoop2" to "voiceLoop3" in a random order.

[Please note this was updated in Android here.](https://github.com/airbnb/lottie-android/pull/2588)

## Actual Behavior
This is a bug that leads to the wrong keyframe being used due to a floating point rounding error.
Given specific composition start frames and the existing floating point rounding, you could wind up with the following situation:

Keyframe 1 has an endFrame of 48 and an endProgress of 0.095051385
Keyframe 2 has a startFrame of 48 and a startProgress of 0.09505139

## Animation JSON
Please find attached.
[DemoVoice.json](https://github.com/user-attachments/files/18027035/DemoVoice.json)

**Comment by calda** [comment]
When I test this animation locally, cycling randomly through the three markers, I don't see any flickering:

https://github.com/user-attachments/assets/1ffd46de-09c8-4ef6-baf8-5d09fccfa436

For us to investigate further you'd need to share a sample Xcode project that demonstrates the flickering issue.

For reference, this is how I set up the looping:

```swift
.playbackMode(playbackMode)
.animationDidFinish { completed in
  marker = ["voiceLoop1", "voiceLoop2", "voiceLoop3"].filter { $0 != marker }.randomElement()!
}
```

```swift
@State private var marker = ["voiceLoop1", "voiceLoop2", "voiceLoop3"].randomElement()!

private var playbackMode: LottiePlaybackMode {
  .playing(.marker(marker, loopMode: .playOnce))
}
```
