### ISSUE TITLE
Only works if Loop is enabled

### ISSUE THREAD

**Issue by jjc235** [airbnb/lottie-ios#251]
I've found that animations only work when looping is enabled.  Once you turn it off, or try to set Progress etc., it just freezes (seems like underlying animationState is change however)

Any ideas?

**Comment by buba447** [comment]
I havent seen this! can you give me more context? @jjc235

**Comment by jjc235** [comment]
Hey Brandon. It's now fixed but the version that was on Pods before you
left had this problem.
