### ISSUE TITLE
Dot lottie are not releasing memory when view gets destroyed

### ISSUE THREAD

**Issue by Preetam7064** [airbnb/lottie-ios#2510]
## Which Version of Lottie are you using?

Lottie 4.5.0

## Code to reproduce
struct DotLottieView: UIViewRepresentable {
    
    var fileName: String
    var speed: Double = 1.0
    var mode: LottieLoopMode = .loop
    var onComplete: (() -> Void)?
    
    class Coordinator {
        var lastFileName: String = ""
    }
    
    func makeCoordinator() -> Coordinator {
        return Coordinator()
    }
    
    func makeUIView(context: Context) -> UIView {
        let containerView = UIView()
        containerView.clipsToBounds = true
        
        let animationView = LottieAnimationView()
//        animationView.loopMode = mode
        animationView.animationSpeed = speed
        animationView.contentMode = .scaleAspectFill
        animationView.translatesAutoresizingMaskIntoConstraints = false
        animationView.tag = 1001 // Unique identifier for the Lottie view
        
        containerView.addSubview(animationView)
        NSLayoutConstraint.activate([
            animationView.leadingAnchor.constraint(equalTo: containerView.leadingAnchor),
            animationView.trailingAnchor.constraint(equalTo: containerView.trailingAnchor),
            animationView.topAnchor.constraint(equalTo: containerView.topAnchor),
            animationView.bottomAnchor.constraint(equalTo: containerView.bottomAnchor)
        ])
        
        // Load the animation
        DotLottieFile.named(fileName) { [weak animationView] result in
            guard case .success(let lottie) = result, let animationView = animationView else { return }
            animationView.loadAnimation(from: lottie)
            animationView.loopMode = mode
            animationView.play { [onComplete] completed in
                onComplete?()
            }
        }
        
        // Save the initial file name in the coordinator
        context.coordinator.lastFileName = fileName
        
        return containerView
    }
    
    func updateUIView(_ uiView: UIView, context: Context) {
        guard let animationView = uiView.viewWithTag(1001) as? LottieAnimationView else { return }
        
        if context.coordinator.lastFileName != fileName {
            // Load and play the new animation
            DotLottieFile.named(fileName) { [weak animationView] result in
                guard case .success(let lottie) = result, let animationView = animationView else { return }
                animationView.loadAnimation(from: lottie)
                animationView.loopMode = mode
                animationView.animationSpeed = speed
                animationView.play { [onComplete] completed in
                    onComplete?()
                }
            }
            
            // Update the stored file name
            context.coordinator.lastFileName = fileName
        }
    }
}

**Comment by calda** [comment]
Does this happen when using the official LottieView SwiftUI view? If so, could you share sample code of a repro case?
