### ISSUE TITLE
after push to a tableViewController then come back,the animationProgress is 1

### ISSUE THREAD

**Issue by XanderXu** [airbnb/lottie-ios#252]
play first,
then if I  push to a tableViewController then come back,the animation can't play because animationProgress is still 1,and call the completionHandle immedetaly.
if I have a tabBarComtroller and switch to  a tableViewController then come back, the animation can't play either.
so I have to set animationProgress = 0 everytime before call play.
but if I don't jump to other controller, when I call play, it can play from begining.
Is it a bug?

**Comment by buba447** [comment]
Have you tried pausing the animation on viewwilldisappear?
We do this in the example app for the animated lottie logo. If you push a view controller while its playing and then go back the animation seamlessly stops and starts back.

**Comment by XanderXu** [comment]
thank you!
