### ISSUE TITLE
Crash when i continuous typing on TypingDemoViewController

### ISSUE THREAD

**Issue by Paladinfeng** [airbnb/lottie-ios#26]
*_Platform: iOS 10.3
*_Console:  *** Terminating app due to uncaught exception 'NSRangeException', reason: '-[__NSCFString replaceCharactersInRange:withString:]: Range or index out of bounds'
*** First throw call stack:
(0x183663fac 0x1820c853c 0x183663ef4 0x183601e8c 0x10007e1e8 0x10007cbf8 0x189a7a63c 0x189a4353c 0x189cb0808 0x189cb0430 0x18a31231c 0x189cb036c 0x189a431c4 0x189a42aec 0x189a410dc 0x189a3f374 0x189cc6fc4 0x1898b38a8 0x189cc6c74 0x1898bdc7c 0x1898b91c8 0x189889e9c 0x18a07f920 0x18a07a09c 0x18a07a4a8 0x1836123c8 0x183611d38 0x18360f944 0x18353f9bc 0x184fac074 0x1898ee984 0x100081028 0x18254d59c)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by buba447** [comment]
Hmmm i wonder if this will be fixed by the current pull request.
Thanks for the heads up! I'll double check it!
