### ISSUE TITLE
can we achieve shadow effect ?

### ISSUE THREAD

**Issue by Mushrankhan** [airbnb/lottie-ios#261]

**Comment by buba447** [comment]
This is a duplicate of https://github.com/airbnb/lottie-ios/issues/218
We dont currently have immediate plans to add support for this. We will look into it after the next major release.

**Comment by Mushrankhan** [comment]
Ok. Thanks for immediate reply. We are waiting for this.

**Comment by hdinhof1** [comment]
You can add a shadow to your view. Make sure `masksToBounds = false`

```
        layer.shadowOffset = CGSize(width: 0, height: 20)
        layer.shadowRadius = 20
        layer.shadowColor = UIColor.black.cgColor
        layer.shadowOpacity = 0.30
        layer.masksToBounds = false
```
