### ISSUE TITLE
AE shape groups breaks on iOS

### ISSUE THREAD

**Issue by tomfrew** [airbnb/lottie-ios#262]
In the AE shapes that are generated from illustrator files, when there are groups of strokes and fills then it does not displays correctly on iOS - It just renders as full rectangles. If they are taken out of their groups then they work fine but that means if you have multiple paths in a shape then they conflict.

The files play correctly on Android but just not on iOS

This is an example of a group that doesn't display correctly.
<img width="508" alt="screen shot 2017-06-14 at 16 04 46" src="https://user-images.githubusercontent.com/845195/27139744-b87c9cce-511b-11e7-8935-40c967bb9f83.png">

How is shows on iOS:
![simulator screen shot 14 jun 2017 16 36 41](https://user-images.githubusercontent.com/845195/27140128-aab6c0fa-511c-11e7-9f1a-95329fb063df.png)

How it shows on Android:
![screen shot 2017-06-13 at 15 04 56](https://user-images.githubusercontent.com/845195/27140137-b1124adc-511c-11e7-9e8d-7c81fcf04e86.png)

Some shapes I can manually remove the groups but only if the paths are distinct and don't overlap. For more complex shapes the strokes apply across multiple paths and it breaks the shapes.

Any suggestions on how to fix or an AE workaround would be really appreciated!

**Comment by buba447** [comment]
Hello! Sorry youre having trouble! Any way you can send me the after effects file so I can debug?

**Comment by therealsalih** [comment]
Hi! Looks like the issue is "fill rules", which is still being worked out on iOS. I've had some success using "Explode shape layers" http://aescripts.com/explode-shape-layers/ Give it a shot and see if breaking everything out into its own layer will help you.

**Comment by tomfrew** [comment]
Thanks for the script @therealsalih, and thanks @buba447 for the offer to debug. 

From the concepts from that script, I've been playing around and now understand what shape groupings are supported in iOS and so have been rebuilding the AE shapes and seems to be working now!

**Comment by therealsalih** [comment]
@tomfrew Glad you could find a suitable workaround. In future versions of Lottie-iOS that has fill rules etc, you wont have to do any workarounds

**Comment by magesme** [comment]
Hi @tomfrew, can you please tell me how you rebuild the shapes in your AE-File in order to work. I guess I'm having the same Problem here. The files play correctly on Android but just not on iOS.

Thanks
