### ISSUE TITLE
Animation circular mask not working and animation stops before complete

### ISSUE THREAD

**Issue by petemorris** [airbnb/lottie-ios#267]
Hi,

Sorry, I'm not an expert on After Effects, but I'll try to describe the issue.

The animation that works well on the web previewer at (lottiefiles.com/preview) but doesn't work in iOS.

First, the animation comes out as a square rather than a circle (mask not being applied presumably), and second the animation stops well before it's finished.

Hope that's enough information to go on. If you need any other information, let me know and I'll try my best to get it. Here's the JSON file:

https://drive.google.com/file/d/0B5CGaiDpoIMtS21lVTJaalRnUGc/view?usp=sharing

Many thanks

**Comment by therealsalih** [comment]
Hi @petemorris Can you send us the AE file so we can see how its built?

**Comment by petemorris** [comment]
Hi,

Sure here you go:

https://drive.google.com/file/d/0B5CGaiDpoIMtQUtsYkk3dE54UGc/view?usp=sharing

If you have any questions about it, let me know (I don't know anything about AE but can ask our designer).

Thanks

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
