### ISSUE TITLE
Issue with iOS Lottie file (working with android)

### ISSUE THREAD

**Issue by jamesrdavis** [airbnb/lottie-ios#269]
I'm having issues with the iOS version of Lottie displaying our animations correctly/fully.

Android is working absolutely fine however iOS isn't. Could someone be so kind as to look at my aep to see if they can help?

**Comment by OliverWangHansen** [comment]
Have the same problem, it looks like the last part of the animation is inverted.

**Comment by buba447** [comment]
I would be happy to look into your problems!

Currently the biggest difference between Android and iOS is that iOS doesnt yet support merge paths or fill rules.

**Comment by jamesrdavis** [comment]
Thanks so much @buba447  Here is a link to an example file that works fine with Android but not with ios https://drive.google.com/drive/folders/0B7z5yLGNWDVrMG1zN09TTlk2LTQ?usp=sharing

I look forward to your feedback.

**Comment by jamesrdavis** [comment]
Hi, @buba447 have you had an opportunity to look into this?

**Comment by buba447** [comment]
Hello @jamesrdavis Ive looked at your animaiton and it looks like you are using gradient Fill which is currently supported on Android but not yet implemented on iOS!
We are working hard to add this feature soon!

**Comment by xxx50236** [comment]
Hi, @buba447  I met the same problem in ios and I put the aep file,json and the gif that  I hope to get.
[source.zip](https://github.com/airbnb/lottie-ios/files/1108503/source.zip)
Unfortunately, you can see there is some problem about the mouse when the animation is playing. By the way it works perfectly in Android, so can you help me to look into this

**Comment by jamesrdavis** [comment]
Thanks, @buba447 but I'm having issues with files that don't have gradients. It works with Android however not iOS.

I'd really apprciate it if you could looking into the file here that isn't using a gradient but still isn't displaying correctly:
https://drive.google.com/file/d/0B7z5yLGNWDVrcnR3b1VJOGJvLTg/view?usp=sharing

Thanks, in advance - James

**Comment by buba447** [comment]
@jamesrdavis Ive looked at your file and the issue is with precomps. Theres a bug (that i just discovered!) where precomps dont support time offset. So the keyframes and timeline need to match up with the parent comp. This is a silly bug, ill have to look into fixing it. For now you can just bring the layers out of the precomp. This will make your comp a little messy but it iwll work.

**Comment by buba447** [comment]
@xxx50236  Hello! Sorry for your troubles. I have taken a look at your file and found the problem.
Lottie has a bug rendering line caps when the path line has a mix of tangents and non tangent vertices. I will work to fix this but in the meantime you can select the mouth and add tangents to both ends of it. You will have to do this for every keyframe.

<img width="516" alt="screen shot 2017-06-30 at 10 11 47 am" src="https://user-images.githubusercontent.com/1163980/27746552-90919738-5d7c-11e7-962b-2e1e20d0eab2.png">

**Comment by olafchou** [comment]
@buba447  how do i update lottie plugin?

**Comment by quydn** [comment]
@buba447 bu
I have a interactive status, on android should run and nice, but on iOS, it will be slow and not a valid. Help me please, thanks a lots :( 

https://www.dropbox.com/s/x0kc09x7igb3abm/Demo.zip?dl=0

**Comment by frzo** [comment]
Hi, 
i think i got the same Problem. On the Web-Preview and Android, my JSON-File is played properly, but iOS ist missing the last 60 Frames. Would be very glad if you could check it out (hope the json-File works for you):
https://www.dropbox.com/s/ysnz7f6mgihk6id/msgListEmpty.json?dl=0

Thanks in Advance!

**Comment by Thapthi** [comment]
Hi, im facing a similar issue. My json export is working fine on android phone on lottie preview. But half of it is gone when brought on lottie preview on iOS. How to fix this?

**Comment by Thapthi** [comment]
Also, my loopout(); expressions are not playing. So the animation plays and got still for the rest of the duration.
