### ISSUE TITLE
Incorrect size of subview added with addSubview(UIView!, toLayerNamed: String!)

### ISSUE THREAD

**Issue by pastiryna** [airbnb/lottie-ios#270]
View added through the function addSubview(UIView!, toLayerNamed: String!) has incorrect size. The previous fix https://github.com/airbnb/lottie-ios/issues/198 doesn't help.

**Comment by anton-semenyuk** [comment]
Is there any other function to add image dynamically in animation?

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
