### ISSUE TITLE
Finished flag always false in completion handler

### ISSUE THREAD

**Issue by fonkadelic** [airbnb/lottie-ios#272]
The `animationFinished` flag from `-[LOTAnimationView playWithCompletion:]` is always false. The underlying problem seems to be that the animation progress is not exactly `1.0` at the end. 
Note that this used to work before `v1.5.2` and was probably introduced by #259.

**Comment by dandongyan** [comment]
Did it be solved? I want to konw the solution

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
