### ISSUE TITLE
Can't render AE gradient fill?

### ISSUE THREAD

**Issue by allenwong** [airbnb/lottie-ios#274]
I use gradient fill in every normal shapes, exported .json, but it looks lotties doesn't support render gradient color, it's transparent now. Anyone knows a way to fix that?
[http://imgur.com/gallery/OWJMq](url)

**Comment by buba447** [comment]
This is on our roadmap for future features. We are currently working on it for version 2 of the ios library. Lottie Android already supports gradient fill!
Please check the roadmap at the bottom of the main readme to track features.

**Comment by adxiaoquan32** [comment]
same issue for me!

**Comment by buba447** [comment]
@adxiaoquan32 Please read my response above.

**Comment by buba447** [comment]
Lottie 2.0 is released and adds support for Linear Gradients.
