### ISSUE TITLE
how to use colorfilter like android?

### ISSUE THREAD

**Issue by Panjianan** [airbnb/lottie-ios#277]
in Android, You can add a color filter to the whole animation, a specific layer, or specific content within a layer:

// Any class that conforms to the ColorFilter interface
final PorterDuffColorFilter colorFilter = new PorterDuffColorFilter(Color.RED, PorterDuff.Mode.LIGHTEN);

// Adding a color filter to the whole view
animationView.addColorFilter(colorFilter);

// Adding a color filter to a specific layer
animationView.addColorFilterToLayer("hello_layer", colorFilter);

// Adding a color filter to specfic content on the "hello_layer"
animationView.addColorFilterToContent("hello_layer", "hello", colorFilter);

// Clear all color filters
animationView.clearColorFilters();

but i can't find code in this framework

**Comment by buba447** [comment]
Lottie 2.0 is out and supports dynamically changing colors!
The interface is slightly different than Android. You have to know the path to the color in after effects. Example:
```[lottieAnimation setValue:[UIColor greenColor] forKeypath:@"Layer 1.Shape 1.Fill 1" atFrame:@0];```

**Comment by agueroveraalvaro** [comment]
Hi, thank you very much for the great library. You can change the color of animation directly in json file editing the following line 
`"c":{"k":[0,0.7,1,1]}`
where the parameters are the color ;)

**Comment by buba447** [comment]
@agueroveraalvaro Yes, but that will change the color for ALL animations that reference the file. A more efficient, less destructive and safer way is to use our programatic recoloring that is documented here https://github.com/airbnb/lottie-ios#changing-animations-at-runtime

**Comment by agueroveraalvaro** [comment]
Yes exactly, i was forgotten that it only works in simple animation and your documentation is so much better. I have a question, in android i can't found the correct syntax to change color 
`animationView.addColorFilter(colorFilter);`
addColorFilter doesn't work and i try to use 
`animation_view.setColorFilter(colorFilter);`
with the following error :
> java.lang.IllegalArgumentException: This shouldn't be used.

**Comment by gpeal** [comment]
@agueroveraalvaro either use https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/SimpleColorFilter.java or https://developer.android.com/reference/android/graphics/PorterDuffColorFilter.html

**Comment by agueroveraalvaro** [comment]
Ok, thanks very much for the orientation, great library :)

**Comment by kashiftriffort** [comment]
@agueroveraalvaro thanks for sharing this knowledge, it work successfully.

**Comment by englishsister** [comment]
LOTAnimationView provides - (void)logHierarchyKeypaths which will recursively log all settable keypaths for the animation. This is helpful for changing animationations at runtime.

**Comment by gpeal** [comment]
@englishsister 
`animationView.resolveKeyPath(KeyPath("**"))` will return a list of all available keypaths. You can iterate through them and log them. 

In fact, we do that [here](https://github.com/airbnb/lottie-android/commit/074176b4574ce41fadf3fba09213e902ede914ac#diff-d8a7e5497fc7f344e53ef427003a343bR50).

**Comment by SanaAhmed** [comment]
animationView.resolveKeyPath(KeyPath("**")) will return a list of all available keypaths. You can iterate through them and log them.

This return an error in latest SDK that     Value of type 'LOTAnimationView' has no member 'resolveKeyPath'

**Comment by SanaAhmed** [comment]
@kashiftriffort 
Can you share some code how you did it?

**Comment by englishsister** [comment]
@gpeal 非常感谢，我当时用了logHierarchyKeypaths获取到了我需要更改的路径， 因为再最新的SDK中我没有找到“ resolveKeyPath”

**Comment by ravitripathi** [comment]
Is it possible to apply a color to the entire view, like we can do on Android? Currently the API on iOS requires us to know the entire Keypaths, or loops through all Keypaths and figure out which might work.
