### ISSUE TITLE
images not working in Xcode

### ISSUE THREAD

**Issue by tarekjam** [airbnb/lottie-ios#278]
Actually I just tried to export simple shape with json and it worked fine
but when I try to do this with compose with couple images "png or jpeg" it seems not responding in Xcode .
what could be the issue, Thanks in advance

**Comment by bellchen** [comment]
talk is cheap, show your code

**Comment by Alchemistxxd** [comment]
i have meet the same issue, all images and .json are in main bundle, but image didn't show.

        `let v = LOTAnimationView(name: "data", bundle: .main)`
        `v.frame = CGRect(x: 0, y: 0, width: 200, height: 400)`
        `v.play()`
        `v.loopAnimation = true`

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
