### ISSUE TITLE
Version 1.5.2 broke negative animation speeds

### ISSUE THREAD

**Issue by welshm** [airbnb/lottie-ios#280]
Previously could "undo" an animation by setting it's speed to -1 and calling play.

This no longer animates with version 1.5.2

**Comment by welshm** [comment]
Inside `- (void)updateAnimationLayerWithTimeOffset:(CFTimeInterval)timeOffset` I suspect that setting the `beginTime` is incorrect.

My understanding of CAMediaTiming is that `beginTime` should still be set to `CACurrentMediaTime` to match the parent and that the `timeOffset` should be set to the specified `offset/speed`.

However, doing that fixes some issues (it will start the animation backwards) and causes others (sometimes forward animation is janky, backwards animation doesn't complete).

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
