### ISSUE TITLE
Masks not sequencing opacity

### ISSUE THREAD

**Issue by samiam2017** [airbnb/lottie-ios#284]
Hey guys I'm trying to get these masks to sequence on and off in opacity. It works in the bodymovin demo file, but not on Android and iOS using the Lottie Library. Any advice would be appreciated.

-S

[TO_GitHub.zip](https://github.com/airbnb/lottie-ios/files/1109767/TO_GitHub.zip)

**Comment by samiam2017** [comment]
My work around has been to do away with the masks and the dashed stroke element, and just importing vector shapes and individually animate each shape layer that makes up the arrows. Another issue I was noticing was that there was this weird artifacting with the masks not sure if that was a result of the dashed stroke shape shifting out of position or if was a specific issue with the mask. An awesome gift to us would be to support feathered masks, but I figure this might be a big technical issue.

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
