### ISSUE TITLE
BUG: Repeating animation on e.g. button click

### ISSUE THREAD

**Issue by mcplectrum** [airbnb/lottie-ios#285]
Since the update from 1.5.1 to 1.5.2 repetitive calls to ```viewToAnimate.play()``` do not trigger the animation again. The animation does work on the first call, but then stops working and nothing happens. If I checkout 1.5.1 everything is fine.

**Comment by welshm** [comment]
The 1.5.2 release seems very buggy overall to me. Is it possible to roll back the cocoapod release to 1.5.1? AFAIK cocoapods doesn't let you target a specific revision, only major.minor

**Comment by mcplectrum** [comment]
You could use carthage instead of cocoapods: In your Cartfile you can point to a specific version / sha etc. like ``` github "airbnb/lottie-ios" "20b94330121ce4a33e1fa50897552390580933aa"```

**Comment by welshm** [comment]
Appreciate the suggestion! Unfortunately, with the rest of our dependencies coming through Cocoapods, we won't be able to migrate anytime soon.

**Comment by Alex1989Wang** [comment]
In fact, you can also specify a specific commit you want to use even with Cocoapods. See this link for the detailed answer: https://stackoverflow.com/questions/20936885/cocoapods-and-github-forks.

**Comment by mcplectrum** [comment]
good to know @Alex1989Wang . I was not sure if you can do that with cocoapods and was not directly able to find something related 👍

**Comment by buba447** [comment]
Will look into this!

**Comment by rob-keepsafe** [comment]
Seeing this same issue; tried resetting via `animation.animationProgress = 0` but doesn't help

The only difference I'm seeing from the example app's lottie logo example is that I'm removing the view from the superview and adding it again each time. If I instead hide/unhide the view, it works fine and will reset properly

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
