### ISSUE TITLE
how to switch animation?

### ISSUE THREAD

**Issue by WZBbiao** [airbnb/lottie-ios#287]
I show animation in UICollectionViewCell,  Every animation is different, In order to avoid cell's recycling, I need to load animation again when the cell every time load. So I try to destroy Lottie and recreate, But It cause interface caton very much when rolling. So what should I do?

**Comment by bellchen** [comment]
I think you should not destroy&recreate LottieView, cache lottieView and pause&play when your cell hidden&show

**Comment by WZBbiao** [comment]
Thanks, I will try it.

**Comment by buba447** [comment]
We are working to add support for setting animation after initializing a LOTAnimationView

**Comment by buba447** [comment]
Closing as we are tracking the issue here https://github.com/airbnb/lottie-ios/issues/344

**Comment by buba447** [comment]
Added here! https://github.com/airbnb/lottie-ios/pull/347
