### ISSUE TITLE
Using Asset Catalogs with Lottie

### ISSUE THREAD

**Issue by ahmedgharib** [airbnb/lottie-ios#289]
Is this possible? I don't see any documentation on it anywhere. Right now we are scaling 3x assets, but then we miss out on app thinning.

**Comment by buba447** [comment]
@ahmedgharib Lottie is a vector rendering solution, so there shouldnt be a need for assets?

**Comment by ahmedgharib** [comment]
We have some compositions that import pngs so we can add dropshadows, but I get that's not the intended purpose

-Ahmed

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by buba447** [comment]
This pull request adds custom image cache support, which you could use to access images from your asset catalog!
https://github.com/airbnb/lottie-ios/pull/336
Enjoy!
