### ISSUE TITLE
READ BEFORE POSTING A message from the Lottie team

### ISSUE THREAD

**Issue by buba447** [airbnb/lottie-ios#290]
Hello!
Thank you for using Lottie!
If you are here you are probably experiencing some issues with Lottie! Really sorry to hear that! We are still actively working on Lottie and we want to make it the best library we can! Please feel free to post issue, we need your input to make this thing better!

Before you post, however, please take a look at this list of commonly known issues we are working on. If you find an open issue that does match your issue please post there. It is easier for us to track issues and how common they are if everyone posts in the same place.

If you find an issue that isnt in the list of issues, please post a new one!
Thank you again for using lottie and for your feedback!

**My shapes a completely filled and the holes arent appearing**
https://github.com/airbnb/lottie-ios/issues/240
https://github.com/airbnb/lottie-ios/issues/97

We currently dont support mergepaths, or fill rules on ios. This is a major feature we are working on for version 2.0. Expect announcements in July!

**My animation isnt playing correctly and I have precomps in my sequence**
There is a bug with precomps that doesnt properly offset their sub animations on the timeline. There are two fixes for this. 1, you can align the precomp up with the parent comp in time (both start on frame 0) and then move the animation inside of the precomp. 2, you can copy the precomp into the parent comp.

**Where is my text layer, star layer, gradient fill, AE Repeater?**
https://github.com/airbnb/lottie-ios/issues/119
https://github.com/airbnb/lottie-ios/issues/274
https://github.com/airbnb/lottie-ios/issues/105
We are working on support for these. They are supported on android but not yet on ios.

**Negative animation speeds?**
https://github.com/airbnb/lottie-ios/issues/48
Sorry! Coming in version 2.0

**My layer style, shadow, glow isnt showing up**
https://github.com/airbnb/lottie-ios/issues/218
https://github.com/airbnb/lottie-ios/issues/146
We dont support layer styles.

**Comment by adxiaoquan32** [comment]
looking forward to the version 2.0！U guys make an easier way for coding Lottie team. appreciate it!

**Comment by rob-keepsafe** [comment]
(As an fyi: you may want to put this into an `ISSUE_TEMPLATE.md` file so people are forced to read / check a box before posting a new issue: https://github.com/blog/2111-issue-and-pull-request-templates)

**Comment by kuoliangkwong** [comment]
Any plan implementing shadow? Need it so much~
