### ISSUE TITLE
A lot of Swift Compiler Warnings

### ISSUE THREAD

**Issue by wytemusic** [airbnb/lottie-ios#291]
I just updated to the newest version of Lottie (1.5.2) and now a lot of Swift Compiler Warnings show up when building. 
<img width="1280" alt="screen shot 2017-07-02 at 09 05 46" src="https://user-images.githubusercontent.com/29824653/27767885-b7fc9252-5f05-11e7-976e-1a883d685a2d.png">
<img width="1280" alt="screen shot 2017-07-02 at 09 05 40" src="https://user-images.githubusercontent.com/29824653/27767882-b7f90920-5f05-11e7-96a5-5085303c9975.png">
<img width="1280" alt="screen shot 2017-07-02 at 09 05 29" src="https://user-images.githubusercontent.com/29824653/27767883-b7f9f6be-5f05-11e7-91fc-7d80237732de.png">
<img width="1280" alt="screen shot 2017-07-02 at 09 05 24" src="https://user-images.githubusercontent.com/29824653/27767884-b7fb98e8-5f05-11e7-9586-4d0a53206498.png">

**Comment by wytemusic** [comment]
Please note that I not only have nullability warnings also I got Semantic Issues.

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
