### ISSUE TITLE
UI很好集成很麻烦 CocoaPods根本用不了 更新了也不行

### ISSUE THREAD

**Issue by batmanWeng** [airbnb/lottie-ios#292]
[!] The dependency `QMUIKit` is not used in any concrete target.

**Comment by bellchen** [comment]
maybe you are posing this issue in a wrong place, here might be what you want.[https://github.com/QMUI/QMUI_iOS/issues](https://github.com/QMUI/QMUI_iOS/issues)

英文不大好，中文再说一遍：
哥们，你应该是发错地方了。去QMUI提issue吧。
