### ISSUE TITLE
Can't display full animation

### ISSUE THREAD

**Issue by lynn87** [airbnb/lottie-ios#293]
- [sample project](https://github.com/lynn87/TestLottie)
- [ae file](https://github.com/lynn87/TestLottie/blob/master/car.aep)
- [json file](https://github.com/lynn87/TestLottie/blob/master/car.json)

**Comment by therealsalih** [comment]
Hi @lynn87 the car layer has a mask on it thats not being used, but for some reason Lottie is having problems with it. Thats what causing the problems for your animation. If you delete that it should work fine


![image](https://user-images.githubusercontent.com/5893643/27878523-5eabee1c-6173-11e7-90fc-4170f73b93ce.png)

**Comment by lynn87** [comment]
@therealsalih It work fine with your solution,Thanks.You save my day.(*^__^*) ……
