### ISSUE TITLE
Can't subtract paths/masks for iOS

### ISSUE THREAD

**Issue by martyprague** [airbnb/lottie-ios#296]
Hi, I can't find a way how to cut out two animated holes in a shape. I have tried masks and paths with different settings but without success. It works fine on windows and android but not on iOS.

AE project:  [Bodymovin_test.zip](https://github.com/airbnb/lottie-ios/files/1125673/Bodymovin_test.zip)

Thanks for help

**Comment by buba447** [comment]
This is currently not supported, please see issues here: https://github.com/airbnb/lottie-ios/issues/290

We are working to add support, for now the best thing you can do is add a shape that is the same as the hole but with background color on top of your shape. Its not ideal but we are working to add support!
