### ISSUE TITLE
lottie ios download(cocoapods error)

### ISSUE THREAD

**Issue by xavierXing** [airbnb/lottie-ios#300]
I had this problem when I downloaded this library on cocoapods:

[!] Error installing lottie-ios
[!] /usr/bin/git clone https://github.com/airbnb/lottie-ios.git /var/folders/z_/3s43xsg530xgwt9gsjdjffph0000gn/T/d20170709-96465-1my0xz1 --template= --single-branch --depth 1 --branch 1.5.1

Cloning into '/var/folders/z_/3s43xsg530xgwt9gsjdjffph0000gn/T/d20170709-96465-1my0xz1'...
error: RPC failed; curl 56 SSLRead() return error -9806
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

How do you solve this problem?

**Comment by cbiancucci** [comment]
Same problem here.

**Comment by fighterLS** [comment]
I find same problem when I use`pod update`.And I solve it use `pod install`.

**Comment by OgabekDev** [comment]
[!] Error installing lottie-ios
[!] /usr/bin/git clone https://github.com/airbnb/lottie-ios.git /var/folders/3l/f24m17z140bbv86_dsgy4l0w0000gn/T/d20240222-12056-6fl9q6 --template= --single-branch --depth 1 --branch 4.4.1

Cloning into '/var/folders/3l/f24m17z140bbv86_dsgy4l0w0000gn/T/d20240222-12056-6fl9q6'...
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 5122 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Comment by sassiwalid** [comment]
Hello same issue for me also

!] Error installing lottie-ios
[!] /opt/homebrew/bin/git clone https://github.com/airbnb/lottie-ios.git /var/folders/fn/jcf4lzms6d337_zyrnys_3j40000gn/T/d20240222-31896-zwbfpj --template= --single-branch --depth 1 --branch 3.4.3

Clonage dans '/var/folders/fn/jcf4lzms6d337_zyrnys_3j40000gn/T/d20240222-31896-zwbfpj'...
erreur : échec RPC ; curl 18 HTTP/2 stream 5 was reset
erreur : 3986 octets de corps sont encore attendus
fetch-pack: unexpected disconnect while reading sideband packet
fatal : fin de fichier prématurée
fatal : fetch-pack : sortie d'index de pack invalide

**Comment by sassiwalid** [comment]
for me the solution was pod repo update because I change my cocoa pods from 1.15.0 to 1.15.2. maybe it help you @OgabekDev

**Comment by mzying2013** [comment]
Switch your network, I use ClashX, and enable enhanced mode. All is well!
