### ISSUE TITLE
Weird animation whitening

### ISSUE THREAD

**Issue by blazejchwiecko** [airbnb/lottie-ios#301]
Hey, I'm having weird animation glitch on iOS. The animation looks stunning on demo file, in AfterEffects and even Android, but it doesn't seem to work on iOS, where instead of playing the whole screen it's getting white and animation is not visible as it should. I've tried many different approaches, body movin' settings and struggled with it for a while, but can't make it work like it suppose to! He's my .aep file, .json, demo HTML and recorded a short video where you can observe this unintentional behavior. Please, tell me what's might be wrong or how can I fix it. 

[lottie.zip](https://github.com/airbnb/lottie-ios/files/1134623/lottie.zip)

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
