### ISSUE TITLE
Width of animation shrinks on iOS but not Android

### ISSUE THREAD

**Issue by mitch104** [airbnb/lottie-ios#302]
I have a fairly simple circular spinner animation that I am using on both iOS and Android. Android the size of the spinner remains constant throughout the animation however for iOS the width of the animation shrinks to exactly 80%. The same code and JSON are used in both cases.

This zip folder contains the JSON and an example video:
[animaiton.zip](https://github.com/airbnb/lottie-ios/files/1139377/animaiton.zip)

I am using the latest versions of lottie-react-native and lottie-ios, and see the problem on all iOS versions.

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!

**Comment by buba447** [comment]
This is because on iOS the contentMode of the lottieAnimation defaults to UIViewContentModeScaleAspectFill
set it to UIViewContentModeNone for non scaling.

**Comment by FugenApps** [comment]
UIViewcontentmodenone doesn't exist.
