### ISSUE TITLE
Animation not rendering properly in iOS

### ISSUE THREAD

**Issue by valerialombo** [airbnb/lottie-ios#306]
Hi guys, can you help me figure out why this animation is not rendering properly in iOS?
This is how it looks in AE and the JSON file in https://www.lottiefiles.com/preview

![ae](https://user-images.githubusercontent.com/25491872/28228537-f22e2548-68ac-11e7-9e87-6dfe96cbff72.gif)

and it's coming out in iOS like this:

![ios-render2](https://user-images.githubusercontent.com/25491872/28228781-e3947f7c-68ad-11e7-82ae-332d2444606c.gif)

I'm using native AE shape layers... no merge paths, fill rules or precomps. Here's the AE file for more reference

https://www.dropbox.com/s/meerxpzwfvcfttb/heartAnimation.aep?dl=0

Thank you!

**Comment by reallynattu** [comment]
Hi @valerialombo, I think there seems to be an issue with Scaling of the path. I played around a bit and was able to fix it. Deleted the scale keyframes and recreated them. Here is the result. https://lottiefiles.com/share/7EgilO

**Comment by valerialombo** [comment]
thank you thank you thank you @reallynattu
