### ISSUE TITLE
iOS Animation Behaves Differently then Lottie Preview (web)

### ISSUE THREAD

**Issue by jfritzbarnes** [airbnb/lottie-ios#309]
I have the following Lottie animation:

[p2_intro.aep.zip](https://github.com/airbnb/lottie-ios/files/1154328/p2_intro.aep.zip)

I'm guessing that we're using a feature that isn't supported on iOS but is supported on the web. On the web this looks like the following:

![mt-20170717](https://user-images.githubusercontent.com/5162626/28295234-2c46f9b2-6b14-11e7-8a48-83c5f492eb3c.gif)

However, what I get when using in our iOS app (and when using LottiePreview) is that none of the moving images appear and that it just has the white triangles appearing:

![img_0627](https://user-images.githubusercontent.com/5162626/28295388-24bb3dec-6b15-11e7-9297-3033ef4b671c.PNG)

Our other animations are working fine, so I'm not sure what might be going on here that is causing this one not to work. Any ideas?

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
