### ISSUE TITLE
Swift

### ISSUE THREAD

**Issue by terenzeyuen** [airbnb/lottie-ios#31]
Can't seem to be able to get LAAnimationView to work. I have installed using carthage, added briging header. It finds LottieVersionNumber but not  LAAnimationView? Anything I have missed?

<img width="592" alt="screen shot 2017-02-04 at 11 32 07" src="https://cloud.githubusercontent.com/assets/2553680/22618162/a7950fa4-eacd-11e6-94db-b791d40e49f9.png">

<img width="965" alt="screen shot 2017-02-04 at 11 31 08" src="https://cloud.githubusercontent.com/assets/2553680/22618164/ab8ac34c-eacd-11e6-8ae7-25cb6826a304.png">

**Comment by Jauzee** [comment]
@terenzeyuen check out this #28
