### ISSUE TITLE
Animation only perform once when setting loopAnimation to true in ios 

### ISSUE THREAD

**Issue by xxx50236** [airbnb/lottie-ios#312]
Hi, I want to add a loading animation in my app and I met some problem. The animation that I want is:
![hopegif](https://user-images.githubusercontent.com/13476581/28448340-eb60b3cc-6e09-11e7-988e-083535049488.gif)
But I found that the animation only play once in my app, the code is:
<img width="727" alt="screen shot 2017-07-21 at 11 46 41 am" src="https://user-images.githubusercontent.com/13476581/28448406-59134d4e-6e0a-11e7-8fb8-ab4368bd1e29.png">
The system version of simulator is iOS 10.3.2 and There is the aep file and json file
[loading.zip](https://github.com/airbnb/lottie-ios/files/1164377/loading.zip).
So, could anyone help me, thanks

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
