### ISSUE TITLE
Set animation progress to specific value

### ISSUE THREAD

**Issue by dddppp** [airbnb/lottie-ios#314]
I would like to **play** an **animation** from a **specific progress value** (e.g. 0.5) to another (e.g. 0.3).

However whenever I try to set the "**animationProgress**" variable it does not seem to have effect.

I checked on the source code and:

- there is no callback for each progress so I can't set pause when I reach the desired level
- animationProgress is a computed variable so I can't use KVO to observe against it 
- whenever I set the animationProgress the following method is called (however the updateAnimation flag is never true)

```
- (void)setAnimatedProgress:(CGFloat)animatedProgress updateAnimation:(BOOL)updateAnimation {
    
  if (_playFromBeginning) {
    _playFromBeginning = NO;
  }
  _animatedProgress = animatedProgress > 1 ? fmod(animatedProgress, 1) : MAX(animatedProgress, 0);
  _animationIsPlaying = NO;
  
  if (updateAnimation) {
    CFTimeInterval offset = _animatedProgress == 1 ? _animationDuration : _animatedProgress * _animationDuration;
    __unused CFTimeInterval clock = CACurrentMediaTime();
    [self updateAnimationLayerWithTimeOffset:offset];
  }
}

```

This is the way I add the animation:

```
override func viewDidLoad() {
        super.viewDidLoad()
        animatedView = LOTAnimationView(name: "animname")
        animatedView.isHidden = false
        view.addSubview(animatedView)
        animatedView.animationProgress = 0.5
        animatedView.play()
    }
```

It never seems to reach line **134**:

<img width="1152" alt="screen shot 2017-07-24 at 14 47 06" src="https://user-images.githubusercontent.com/653958/28526316-190c76b8-707f-11e7-9501-dbf14a588d5e.png">

**Comment by buba447** [comment]
This is a feature that we are currently working on! Should be available in the next release, version 2.0!

**Comment by buba447** [comment]
Please read here https://github.com/airbnb/lottie-ios/issues/290

**Comment by dddppp** [comment]
Excellent, thank you! Do you know when the next release will be?

**Comment by buba447** [comment]
Lottie 2.0 is out. We have added a method ```[animationView playFromProgress:0.3 toProgress:0.5 withCompletion:nil];```

**Comment by liaocmq** [comment]
Hi Brandon, I'm trying to find support for the same case but for Android, could you please inform how can I manage to control the progress in a custom animation? I'm using a progress bar to set the progress for each user called in a queue. I used setProgress but no success. Thank you.
