### ISSUE TITLE
Animation Works on Android and Web, Renders Incorrectly on iOS

### ISSUE THREAD

**Issue by bajabob** [airbnb/lottie-ios#315]
Here is the end result on Android (thank you team for helping us with the Android issues! https://github.com/airbnb/lottie-android/issues/391) . Two separate animations, one used as a background and one as the foreground logo.

![lottie-android](https://user-images.githubusercontent.com/273841/28582128-ef3d6468-7129-11e7-8448-55cc50d9158c.gif)

However on iOS this is what we are seeing in the Lottie Preview available on the App Store. Can you please help us out with this issue? We are very interested in getting this working across all platforms! 😄  Attached is our After Effects File.
![upload](https://user-images.githubusercontent.com/273841/28582187-23a769c4-712a-11e7-8433-3117e4e33159.png)

[BR Animation.zip](https://github.com/airbnb/lottie-ios/files/1174034/BR.Animation.zip)

**Comment by buba447** [comment]
Please read here! https://github.com/airbnb/lottie-ios/issues/290

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
