### ISSUE TITLE
Animating Stroke dash doesn't work

### ISSUE THREAD

**Issue by ericawong** [airbnb/lottie-ios#317]
Hi,

I'm trying to create a simple loading spinner by animating the stroke dash on a circle but it doesn't seem to work on ios.

Thanks,
Erica
[data.json.zip](https://github.com/airbnb/lottie-ios/files/1174402/data.json.zip)
[ios-animation.aep.zip](https://github.com/airbnb/lottie-ios/files/1174403/ios-animation.aep.zip)

**Comment by michaelgum** [comment]
It looks like you are using a mask on a solid and the stroke effect. You should use a shape layer and trim paths.

**Comment by michaelgum** [comment]
@ericawong Attached is an example using Trim Paths instead of Dashes.

https://www.lottiefiles.com/share/XT9NYJ

[Spinner.zip](https://github.com/airbnb/lottie-ios/files/1174518/Spinner.zip)

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
