### ISSUE TITLE
Image transformation/rotation

### ISSUE THREAD

**Issue by capecrawler** [airbnb/lottie-ios#318]
Hi,

I am trying to make an on-boarding screen with transitions using images when pages are swiped. Animation works fine on android but not on iOS. For example rotating an image while it moves, it supposed to look like a wheel. Right now, it moves but it doesn't rotate. I am not sure if these animations are related to what the current version doesn't supports.

Here is the AEP file that I used.
[lottie_test.aep.zip](https://github.com/airbnb/lottie-ios/files/1175355/lottie_test.aep.zip)

PS. Also if you have a sample code on how to implement an on-boarding with animations for iOS would be helpful.

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
