### ISSUE TITLE
Can't get simple animation to work

### ISSUE THREAD

**Issue by MKGitHub** [airbnb/lottie-ios#32]
Made a simple animation with a square and it's not working at all, see attached files.
Using AE CC 2017
I added the json file to the iOS project and ran it on my device.
Works & looks just fine in the html doc.

[Archive.zip](https://github.com/airbnb/lottie-ios/files/752339/Archive.zip)

![2017-02-04 at 15 32 52](https://cloud.githubusercontent.com/assets/535550/22619219/517de3e8-eaf0-11e6-8ab0-b4f14e55e71a.png)

**Comment by buba447** [comment]
We don't yet support x and y as separate dimensions. We hope to add it in the next dot release!

**Comment by MKGitHub** [comment]
Ohh okey, does that apply for all objects that support separate dimensions in AE?

**Comment by gpeal** [comment]
Android will support this in the next release.

**Comment by buba447** [comment]
@MKGitHub Yes it does! We're working to resolve this :)

**Comment by buba447** [comment]
@MKGitHub A work around is to parent your layer to another layer and do one animation on the parent and another on the layer. I know this is pretty messy and cumbersome but it will work until we get multi-dimension support running

**Comment by buba447** [comment]
@MKGitHub Added support into master, will be in the next cocoa pods release!

**Comment by MKGitHub** [comment]
thx
