### ISSUE TITLE
Pixelated Edges in App

### ISSUE THREAD

**Issue by michaelgum** [airbnb/lottie-ios#320]
We are having an issue of pixelated edges in iOS.
All layers in the AE file are shape layers and an Alpha Track Matte.

This is what it is supposed to look like (Set a background color bc it ends in white):
https://www.lottiefiles.com/share/XbozFI

This is what it looks like in the app (Crop from on-device screenshot; not scaled):
![image uploaded from ios 20](https://user-images.githubusercontent.com/29632314/28635347-e4ca10f4-71ff-11e7-9bdb-86b90ed897dd.jpg)

AE & JSON
[Archive 2.zip](https://github.com/airbnb/lottie-ios/files/1177577/Archive.2.zip)

**Comment by buba447** [comment]
Have you tried running on device?
Sometimes the simulator pixelates lottie animations.
Were working on a fix!

**Comment by michaelgum** [comment]
Yes, that is a screen shot from an iPhone 7, not the simulator.

**Comment by michaelgum** [comment]
Is this something that Lottie 2.0 might fix? If so, is there a way to get early access?

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
