### ISSUE TITLE
Transition bug

### ISSUE THREAD

**Issue by AlexCai21** [airbnb/lottie-ios#321]
Hi, @buba447 , I run demo and touch Animated Transitions Demo, when I touch "Show Transition A ", the present ViewController don't be presented. The B ViewController Shows and then disappear automatically. So I can't present a new ViewController by transition.The release is 1.5.2, iOS 10.3.2. 
When I use 1.0 release , it's ok.
Thanks.

**Comment by buba447** [comment]
We are releasing an update that fixes this very soon!

**Comment by AlexCai21** [comment]
ok , Thanks
