### ISSUE TITLE
Skew on Shape Layer Group transformations

### ISSUE THREAD

**Issue by groenroos** [airbnb/lottie-ios#322]
It appears that the Skew effects on my Shape Layer Group transformations are not reflected on Lottie. I wonder if this is a bug with my aep/Lottie implementation, since the readme does insinuate these being available ("Group Transforms (Anchor point, position, scale etc)"), and the list of unsupported AE features does not list Skew. bodymovin itself does seem to support it just fine.

**Comment by buba447** [comment]
We dont have support for skew just yet! Will update the docs

**Comment by groenroos** [comment]
Aw, shucks. Is it on the roadmap any time soon? Is there a workaround in AE?

**Comment by groenroos** [comment]
@buba447 Any update? I noticed it's not explicitly marked as unsupported in the docs yet, either.

**Comment by groenroos** [comment]
@buba447 Is this planned to be supported in the near term? I'm once again running into needing Skew to get the effect I want, and I haven't really found any real alternatives - frame-by-frame rotoscoping makes the JSON huge and laggy, and I'm not sure raster image sequences will be much better either. Any ideas for workarounds would be very welcome!

BTW Skew is still not explicitly mentioned as unsupported in any of the docs or websites I can find, either. :)

**Comment by buba447** [comment]
Now supported!
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
