### ISSUE TITLE
Rotation y lottie 

### ISSUE THREAD

**Issue by sinzen** [airbnb/lottie-ios#323]
Hi, what's the Best way to do rotation in after effect to export on android project? Thanks

**Comment by sinzen** [comment]
And also on ios project
Thanks for your helping..

**Comment by buba447** [comment]
@sinzen Hello! 
Heres a pretty good tutorial of how to get started with Lottie
https://www.youtube.com/watch?v=ESjFEaZx7UI

For more info on how to animate with after effects Id checkout this
