### ISSUE TITLE
Is there a timeline for Lottie v2 for iOS?

### ISSUE THREAD

**Issue by mkaa00x** [airbnb/lottie-ios#324]
I've seen that the android v2 has been released. My friend and myself are working on an app and the splash animation that I created works on his device (android) but fails to work on mine (which I presume is because mine isn't on Lottie v2 or perhaps because I'm developing on the iOS 11 developer beta). What's essentially happening is that the letters just pop up in intervals without any animations and any part that loops over itself (i.e. if I had an 'O' in there) it just fills in (such that my 'O' would be filled in) with an off-white colour. Is anyone else having similar issues? I submitted my file to lottiefiles.com and will link it when I can!

**Comment by buba447** [comment]
Hello! Thank you for your message!
Yes the problem you are having is due to a missing feature on ios that is
available on android. We are currently hard at work on Lottie v2 on ios. Im
happy to inform you that it should be out in yhe next week. Stay tuned!
