### ISSUE TITLE
Animation speed problem

### ISSUE THREAD

**Issue by zachlucas** [airbnb/lottie-ios#325]
I have an animation that appears correct on the web, but on iOS there is a speed mismatch issue.  There is a van with wheels, and the wheels appear to move at a separate speed from the van itself.  We've removed all easing and any special movement, it's simply an animation from one anchor point to another.  I've attached the json of the animation.  Any idea? 
[animation.json.zip](https://github.com/airbnb/lottie-ios/files/1188805/animation.json.zip)

**Comment by buba447** [comment]
We are releasing an update that fixes this very soon!

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
