### ISSUE TITLE
View Can't play to the last

### ISSUE THREAD

**Issue by juxuechen** [airbnb/lottie-ios#327]
Before view is displying on the screen，set progress or playAnimation cause the animation view can‘t play to  the last or play not. After debugging，I found  when view add to it’s superview，until the next rendering screen（displaylink selector）is complete，to set up progress or play，could play animation to the last

pr：https://github.com/airbnb/lottie-ios/pull/326

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!

**Comment by juxuechen** [comment]
When will you publish 2.0-release？？？

**Comment by buba447** [comment]
Its published now! :)

**Comment by juxuechen** [comment]
why don't support gradient? I know android support it on 2.0

**Comment by buba447** [comment]
@juxuechen Lottie 2.0 supports linear gradient. We are working to add radial gradient, but we want to be careful to add the support without compromising performance on iOS.

**Comment by buba447** [comment]
@juxuechen Radial Gradient is now in master
