### ISSUE TITLE
Animation is broken in Lottie 2.0.1

### ISSUE THREAD

**Issue by welshm** [airbnb/lottie-ios#333]
An animation that was working in Lottie 1.5.0 skips straight to the end in Lottie 2.0.1

Not sure what other files would be beneficial here.

**Comment by buba447** [comment]
Hi! Im sorry youre having trouble! I will need more context to help you though. The animation json file and a code snippet would be a great start

**Comment by federicocappelli-je** [comment]
Same here, Lottie 2.0.1 in Swift, here the updated example app for the bug: 
[LottieBUGExample.zip](https://github.com/airbnb/lottie-ios/files/1196723/LottieBUGExample.zip)

**Comment by buba447** [comment]
Hello @federicocappelli-je I checked your file and it seems you are using `LOTAnimationView(contentsOf: jsonUrl)` to load your local file. ContentsOfUrl is used for downloading the json from the web and will not work in this case, which is why the animation is not working.

You have several options for loading an animation locally.
You can get the url like you are doing and cal:
`LOTAnimationView(filePath: jsonUrl.path)`

Or you can load with just the file name and lottie will find the path for you in the main bundle, saving a few lines of code:
`LOTAnimationView(name: "LottieLogo1")`

Have your animation in another bundle? Lottie can do that too
`LOTAnimationView(name: "LottieLogo1" bundle:yourBundle)`

Hope this helps!

**Comment by federicocappelli-je** [comment]
@buba447 Thanks, this works, just a note: The assumption that an (NS)URL is implicitly remote is a bit too strong, NSURLs are widely used even for local files.

**Comment by buba447** [comment]
@federicocappelli-je I completely agree. Unfortunately its not my assumption, its Apple's. Under the hood LOTAnimationView(contentsOf: jsonUrl) is simply calling NSData's contentsOf:URL inside of an async block. Not sure why it they would mask out local files, but it seems they are.

**Comment by welshm** [comment]
Here's the JSON:
[toggle.json.zip](https://github.com/airbnb/lottie-ios/files/1197704/toggle.json.zip)

In terms of the code, it's pretty simple. We just instantiate it and then call `playWithCompletion:` - not changing the rates or

**Comment by buba447** [comment]
@welshm There does seem to be an issue. If you load a view and immediate call play its jumping to the end. If you set the animated progress to 0 before calling play it seems to work just fine. Im debugging right now!

**Comment by buba447** [comment]
@welshm Wait sorry, that was caused by some debug code on my local branch. On master the animation plays fine for me. 😕 
Can I see the code snippet?

**Comment by welshm** [comment]
Nothing fancy here from what I can see, but here's the snippet below (instantiating, and then the control event).

It's just a UIControl with a animation view inside that's supposed to toggle back and forth.

`
- (instancetype)init {
  NSAssert(padding >= 0 , @"%f must be non-negative", padding);
  self = [super initWithFrame:CGRectZero];
  if (self) {
    _toggle = [LOTAnimationView animationNamed:@"toggle"];
    _toggle.userInteractionEnabled = NO;
    [self addTarget:self action:@selector(toggle:) forControlEvents:UIControlEventTouchUpInside];
    [self addSubview:_toggle];
    [self buildConstraints];
  }
  return self;
}

- (void)toggle:(UIControl *)control {
  if (!self.userInteractionEnabled) {
    // We're already handling an event.
    return;
  }
  LOTAnimationCompletionBlock restoreInteraction = ^(BOOL animationFinished) {
    self.userInteractionEnabled = YES;
  };
  self.userInteractionEnabled = NO;
  self.toggle.animationSpeed = self.selected ? -1 : 1;
  [self.toggle playWithCompletion:restoreInteraction];
  self.selected = !self.selected;
}
`

**Comment by buba447** [comment]
@welshm Hmmm. I created a test project with nearly the same situation. If you remove the constraints and set the frame manually do you still have the problem?

**Comment by welshm** [comment]
I've managed to narrow it down a bit. It will animate the first time properly (yay!). It's when we try to reverse it (speed = -1) that the animation breaks and then any subsequent animation is broken - it just jumps straight to the end state.

This is working in lottie 1.5.1 so we will continue to run on that version for now, but reversal was a very nice feature which allowed for great things like toggles and radial buttons where users can undo selections.

**Comment by buba447** [comment]
@welshm This must be an edge case, I tested reversal with 2.0 and it worked. 
In which state does reverse not work?
Example:
-add lottie view
-play foward
-set speed -1
-play backwards

?
Id love to get this fixed for you ASAP

**Comment by buba447** [comment]
Negative speed is working on my end. I wonder what the difference is. Are you setting the animation speed midflight?
Also have you seen the new api to play only a segment of the timeline?

**Comment by buba447** [comment]
@welshm 
Try calling pause on the animation before setting the negative speed

**Comment by buba447** [comment]
@welshm I just published 2.0.2 that has some updates to play pause. Let me know if this fixes anything for you!

**Comment by welshm** [comment]
@buba447 I will certainly take a look at that first thing tomorrow. We don't do anything fancy, the code snipped above is the entirety of our animation calls (just setting the speed to -1 based on the previous selected state).

So your original assessment of

1. play forward
2. set speed -1
3. play backward

is exactly what we're doing. We don't try to change the animation speed or play any fragments - just whole animations.

I'll update tomorrow and try calling pause before changing the negative

**Comment by welshm** [comment]
Adding pause before changing the speed seems to have done the trick!

There's still some flickering sometimes (jumps to the end-state for a moment before resuming animation at the correct state) but that only seems to happen if I continually click on the control.

**Comment by buba447** [comment]
@welshm Did you pull down the latest version that was posted yesterday afternoon?
I fixed some playing bugs there. Id like to know if there are still some that persist.
Seems like theres some edge cases I might not have thought through.

**Comment by welshm** [comment]
@buba447 I pulled down this morning (around 8 am EST) from cocoapods - so it was running 2.0.2. If there's something even newer you'd like me to try, let me know and I can give that a spin too.
