### ISSUE TITLE
Animation completion block argument animatedFinished is only true if progress is exactly 1

### ISSUE THREAD

**Issue by danthorpe** [airbnb/lottie-ios#335]
In `LOTAnimationView` the completion block is only called if the `CGFloat` property is exactly 1. This is not always the case:

![animated progress > 1](https://user-images.githubusercontent.com/309420/28926273-369224b6-785f-11e7-96dd-fe29ca7f4b45.png)

I would suggest changing this to a `>= 1`.

This is on v 1.5.2

**Comment by buba447** [comment]
This is fixed on lottie v2
