### ISSUE TITLE
Animations preview different on web, iOS and Android

### ISSUE THREAD

**Issue by staletor** [airbnb/lottie-ios#343]
All of my animations preview fine in the web preview, and almost all on Android, but on iOS it's pretty random. I've attached some animations.

- LearnGame_2 looks good on web and Android, but looks like iOS don't handle masking and polystar.
- ConfettiInfinite has some strange artifacts on Android and is skipping on iOS, web is fine. Might be a masking issue.
- NotAWord won't play on either Android or iOS, web is fine.

[AnimationsJSON.zip](https://github.com/airbnb/lottie-ios/files/1200113/AnimationsJSON.zip)
[Animations_AE_files.zip](https://github.com/airbnb/lottie-ios/files/1200117/Animations_AE_files.zip)

**Comment by buba447** [comment]
@staletor Which version of Lottie are you using on iOS?
I just tested all three and they look nearly identical to the After Effects project with Lottie 2.0.2
Unless Im missing something very small.

![notawork](https://user-images.githubusercontent.com/1163980/28980526-f011305a-7902-11e7-9bbe-f45de7c1ec46.gif)
![learngame](https://user-images.githubusercontent.com/1163980/28980527-f01318b6-7902-11e7-849c-e9f4df400837.gif)
![confetti](https://user-images.githubusercontent.com/1163980/28980525-f00fcfb2-7902-11e7-975e-55f47263e238.gif)

**Comment by staletor** [comment]
@buba447 I've been using the Lottie Preview apps. Guess they don't have 2.0.2 yet. I read a little on other issues similar to mine after posting my issue. And seems most of them will be fixed in the 2.0.2 version, I hope. Thanks for testing!

**Comment by buba447** [comment]
You can use the official lottie preview mac app that is in the Example
folder of our repo

**Comment by buba447** [comment]
@staletor Closing for now, feel free to reopen if you find they still dont work with the new version.
