### ISSUE TITLE
Add the ability to use Xcode playgrounds

### ISSUE THREAD

**Issue by MKGitHub** [airbnb/lottie-ios#35]
Add the ability to use Xcode playgrounds.

thx

**Comment by buba447** [comment]
@MKGitHub Lottie already supports playgrounds!
Like all 3rd party libraries the playground must be in a workspace that builds the library. A cocoa pod workspace will work fine for this. 
Then create a new playground in the workspace and `import Lottie` 
Add the JSON to the `Resources` folder under the playground.

Example:
```
import UIKit
import Lottie
import PlaygroundSupport

var str = "Hello, playground"
let lottieView = LOTAnimationView.animationNamed("HamburgerArrow")

PlaygroundPage.current.liveView = lottieView
lottieView?.loopAnimation = true
lottieView?.play()
```

<img width="1107" alt="screen shot 2017-02-13 at 4 10 54 pm" src="https://cloud.githubusercontent.com/assets/1163980/22909120/09a20202-f207-11e6-9f6d-960da65723ff.png">
