### ISSUE TITLE
Unable to play Lottie animation when the animation comes from a Remote URL - iOS

### ISSUE THREAD

**Issue by 1marcosgn** [airbnb/lottie-ios#351]
I can't play the animation when calling

LOTAnimationView(contentsOf: ..

According to the documentation of the method:
/// Loads animation asynchrounously from the specified URL
public init(contentsOf url: URL)

This is my code, I don't know if I'm missing something:

```
let remoteURL = "https://www.lottiefiles.com/storage/datafiles/7HMs29Q0NhBUKCp/data.json"
let animationView = LOTAnimationView(contentsOf: URL(string: remoteURL)!)
animationView.loopAnimation = true
animationView.frame = (self.merchCard.imageView?.frame)!
self.merchCard.imageView?.addSubview(animationView)
animationView.play()

```

This is working fine when I load local files, I tried downloading the same file and I can see the animation with out any issues, the problem is when I try to get this from the remote URL

**Comment by buba447** [comment]
Which version of Lottie do you have? I fixed a bug similar to this in 2.0.3

**Comment by 1marcosgn** [comment]
thanks @buba447 this is working fine in Version 2.0.3

**Comment by smhk** [comment]
We are definitely experiencing this bug, with the current Lottie (Sept 21),

ie, using 
**github "airbnb/lottie-ios" "master"**

Amazing library, sorry to bother you, any thoughts?

**Comment by smhk** [comment]
Heh that's an old one eh !

Glad it helped

**Comment by smhk** [comment]
I have to say (this is a rather general comment), we ultimately gave up on Lottie.

(If you have a iOS person who is very fast at animating, and a droid person who is very fast at animating - in our finding it is really just ultimately cheaper to do it natively by hand.)

our final view was it's great for prototyping when it works.

**Comment by kurupareshan** [comment]
How to load Remote URL in latest Lottie for ios

**Comment by kurupareshan** [comment]
Need to display a GIF from Remote URL. How its possible in latest Lottie version?
