### ISSUE TITLE
questions：Trim Shapes Individually feature of Trim Paths  

### ISSUE THREAD

**Issue by olafchou** [airbnb/lottie-ios#352]
what's the meaning of this sentence ,could you give me an example or an AE simple source file ?
 I want to understand the  meaning of this sentence ？thank you

**Comment by buba447** [comment]
Of course! In after effects the Trim Path node has two modes, Simultaneous and Individual. The default mode is Simultaneous, which will trim ever path about it uniformly. The Individual mode merges all paths into a single path and then trims it.
Like so:

Simultaneous, the default mode
![trimpathsimultaneously](https://user-images.githubusercontent.com/1163980/29039599-c9d476d0-7b60-11e7-8067-04ba6a633f50.gif)

Individually
![trimpathindividually](https://user-images.githubusercontent.com/1163980/29039613-d3661410-7b60-11e7-977b-80102d86eee8.gif)

 If theres only one path, then the behavior is the same for both. 
Lottie iOS currently only supports the default mode, Simultaneous.

**Comment by olafchou** [comment]
thank you , awesome !!!!!!
