### ISSUE TITLE
Cannot render images on the screen

### ISSUE THREAD

**Issue by zhangqifan** [airbnb/lottie-ios#354]
I am using lottie-ios 2.0.3 and it works great before. I embed it in a workspace which contains some static libraries (sub projects), and each lib has its bundle dependency. I put a folder which includes an images folder and a json data file into a sub project's bundle.

And here's my code:

```objc
_animFloatView = [LOTAnimationView animationNamed:@"float" inBundle:MainBundle];
_animFloatView.frame = ...;
return _animFloatView;
```

`MainBundle` is a define that stands for:

```objc
(NSBundle *)[NSBundle bundleWithURL:[[NSBundle mainBundle] URLForResource:@"subProjBundleName" withExtension:@"bundle"]]
```

I did it and add it to the sub view, but there is not working (I mean on the screen there is no visual images). So I check whether the specific image asset has been loaded.

```objc
image = [UIImage imageNamed:components.firstObject inBundle:asset.assetBundle compatibleWithTraitCollection:nil];
```

In LOTLayerContainer, I can watch or print this **image** and I am surely the image asset has been loaded from `MainBundle`.

So where the problem is? Please help me. :(

**Comment by buba447** [comment]
What happens when you set _animFloatView.contentView to UIViewContentModeAspectFit ?

**Comment by zhangqifan** [comment]
I set it. It doesn't work.

**Comment by buba447** [comment]
If the image is loading then the problem must be with something not working in the animation itself. Would you mind sending me the animation so that i may debug?

**Comment by buba447** [comment]
Please update to 2.0.5 and verify if the bug still exists! Reopen if it does.
