### ISSUE TITLE
When does Lottie Render

### ISSUE THREAD

**Issue by nlogioco** [airbnb/lottie-ios#356]
If I instantiate and present an animation (play has not been called yet), have the frames rendered at this point? Or do they render upon first play?

@buba447

**Comment by buba447** [comment]
They render as they play.

**Comment by nlogioco** [comment]
@buba447 Is there a way to pre-render before playing?

**Comment by buba447** [comment]
Whats the use case for this?
The frames are rendered as the progress is updated or when you call play a CABasicAnimaiton is created that sets the frames.
