### ISSUE TITLE
Animation call back is not invoked when app is sent to background and put to foreground in the middle of animation in v2.0.3

### ISSUE THREAD

**Issue by venkatanavn** [airbnb/lottie-ios#357]
I recently updated the Lottie SDK from v1.5.1 to v2.0.3. I see an issue on the new v2.0.3... This issues is not there in v1.5.1

Steps to reproduce:

1) Play the animation using the below method
func play(completion: Lottie.LOTAnimationCompletionBlock? = nil)
2) Dismiss the app to background in the middle of animation.
3) Open the app again (i.e. get to foreground)
4) Now observe that the completionBlock is not invoked.

Please let me know.

**Comment by buba447** [comment]
Ill look into this!

**Comment by buba447** [comment]
I just published an update 2.0.4 that should fix this! Please reopen if it does not.

**Comment by venkatanavn** [comment]
Its still reproducible with v2.0.4
