### ISSUE TITLE
Shape not being rendered correctly (Scale + Position + Rotation)

### ISSUE THREAD

**Issue by lorenappin** [airbnb/lottie-ios#358]
Hi Lottie Team,

I checked in with Bodymovin and they said the JSON was created correctly and it looks like it might be an issue with Lottie...

I'm having issues getting an animation of a Fish to work out. It uses scale, position, and rotation at the same time.

I've attached all files - the AE project file, the expected animation, and the resulting animation, along with the JSON output.

Thanks for your help!

[Fish Animation - Lottie.zip](https://github.com/airbnb/lottie-ios/files/1212714/Fish.Animation.-.Lottie.zip)

**Comment by buba447** [comment]
@lorenappin What versiuon of lottie are you on?
I just trie the animation with the most recent version (2.0.3) and the animation worked, though the background color was missing.

**Comment by buba447** [comment]
![fishy](https://user-images.githubusercontent.com/1163980/29141637-ddc8eabe-7d03-11e7-931e-4834d2d9b901.gif)

**Comment by lorenappin** [comment]
@buba447 Thanks! It seems that I need to update it - I see you guys made an update a few days ago.

Although it fixed this issue, it unfortunately made 80% of the project now entirely unusable with lots of errors.

I'm attaching two examples of the before and after (v1.5.2 vs v2)

1. Moving waves (now shows a very very weird rendering)
[waves.zip](https://github.com/airbnb/lottie-ios/files/1213847/waves.zip)

2. Idle Fish - doesn't show the body.
[fish.zip](https://github.com/airbnb/lottie-ios/files/1213849/fish.zip)

[Fish + Waves.aep.zip](https://github.com/airbnb/lottie-ios/files/1213866/Fish.Waves.aep.zip)

BTW - only in case it's convenient for you - would love to buy you a coffee and show this in person since it's likely more efficient. We're just down the street.

**Comment by buba447** [comment]
Hey! I looked into your AEP file. You might have sent an incomplete version. The Wave Animation composition is completely empty, not a single layer.
Also I noticed the fish composition has expressions, something not supported by Lottie.

Also, Id love to grab coffee and look over this with you in person. Im out of the office today but tomorrow sometime would work. Email me @ brandon.withrow@airbnb.com to coordinate.

**Comment by buba447** [comment]
Theres a bug in solid layer with masks. Will investigate.

**Comment by m-calleja** [comment]
Hi ,

I think that my issue is similar to this as i have a solid shape just using rotation and and scales but somehow it does not render on iOs although it renders perfectly on web. Rotation and scaling are supported according to this webpage: https://airbnb.io/lottie/supported-features.html. I also have the latest version of lottie right now. Can you kindly see if it works for you on iOS? Below is the json and the aep. Many thanks!


[explore_animation.zip](https://github.com/airbnb/lottie-ios/files/2824622/explore_animation.zip)

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
