### ISSUE TITLE
error in playback

### ISSUE THREAD

**Issue by samiam2017** [airbnb/lottie-ios#359]
Hey we are getting an error in playback using the new version of lottie.

The movie plays without errors in iOS version of lottie (1.5.0)
![xcode_using_lottie1 5](https://user-images.githubusercontent.com/29287850/29147985-6abce68a-7d1f-11e7-8ea1-3a51072091c9.gif)

But leaves an artifact in the new version of lottie (2.0.3)

![xcode_using_lottie_2 0 3](https://user-images.githubusercontent.com/29287850/29147997-78c7d7c6-7d1f-11e7-9672-1a3dd450a4e8.gif)

**Comment by buba447** [comment]
Oh interesting! Is there anyway you can send me the animation file so that I may debug?

**Comment by buba447** [comment]
Actually, from frame-by-framing your gif I bet the artifact is a path that has a trim path on it thats animated. The math for trim paths on iOS is slight off right now and we are working to resolve the issue. If you just hide the shape with the trim path after the animation finishes in after effects it will temporarily fix the problem.

**Comment by samiam2017** [comment]
Hey thanks for the feedback super appreciative of the support you guys offer. I'll definitely test an adjustment with the dev. 

If you have any insight into what caused the bug and maybe some info on when a fix would be rolled out. 

I initially had timeline tracks end when an element was not used, but while trying to trouble shoot another bug a moderator had recommended having tracks extend for the entire comp. So not sure what is the best method moving forward.

-S

Here is the current project build:

[2017_0810_BankTransfer_v07_export folder.zip](https://github.com/airbnb/lottie-ios/files/1215806/2017_0810_BankTransfer_v07_export.folder.zip)

**Comment by buba447** [comment]
Oh weird! I opened the JSON file with the preview app and when I play the animation it has the visual error, but when I scrub the animaiton it does not. Theres definitely a different bug here. Im going to dive into it and see what I can find.

**Comment by samiam2017** [comment]
I turned the opacity down from 100% to 0% at frame 126 of the transform group 4 and group 2 of the RING GREY 5 layer. The dev said that fixed it. 

Only thing I'm worried about is if this is going to break other animations we have created prior. If you find a solution soon please post. I'd prefer to just do the update of the library, instead of having to revisit a bunch of prior animations. 

thanks again for all your help.
-S

**Comment by buba447** [comment]
Great!
I can see theres definitely a bug here. Soon as I find the root of it I will update the issues here! Should be early next week as my end of week plate is full of non lottie worrk. Sorry for any delay!

**Comment by buba447** [comment]
@samiam2017 An update! I found the bug and fixed it. Should be fixed in 2.0.4!
