### ISSUE TITLE
Can't compile using Carthage Framework

### ISSUE THREAD

**Issue by MKGitHub** [airbnb/lottie-ios#36]
See attached
[Xcode.zip](https://github.com/airbnb/lottie-ios/files/753414/Xcode.zip)
![2017-02-06 at 00 39 11](https://cloud.githubusercontent.com/assets/535550/22630986/df3e8088-ec04-11e6-87c7-dcae54c2d403.png)

**Comment by buba447** [comment]
Should be fixed now! Just pushed a new version!
@MKGitHub
