### ISSUE TITLE
support features

### ISSUE THREAD

**Issue by olafchou** [airbnb/lottie-ios#360]
<img width="806" alt="2017-08-10 14 31 26" src="https://user-images.githubusercontent.com/19890798/29157272-b6559a7e-7dd8-11e7-9bdf-b6b3ed8934d0.png">
<img width="966" alt="2017-08-10 14 31 54" src="https://user-images.githubusercontent.com/19890798/29157273-b68434f6-7dd8-11e7-9f06-cebe66551530.png">

why it different ?

**Comment by buba447** [comment]
They are actually the same, but this is outdated.

**Comment by buba447** [comment]
Where did you find this chart?

**Comment by olafchou** [comment]
http://airbnb.io/lottie/supported-features.html
