### ISSUE TITLE
Text rendering

### ISSUE THREAD

**Issue by jlongster** [airbnb/lottie-ios#361]
From what I can tell lottie does not support text rendering. I can't find an existing issue about it though. Is it being worked on? Can we keep this issue open until it's fixed, so others know the status?

**Comment by jlongster** [comment]
Looks like it's supported on Android at least: https://github.com/airbnb/lottie-android/pull/343

**Comment by jlongster** [comment]
I just found #290, and I see text rendering is coming, but it would probably be helpful to keep this issue open so other can find it first. People aren't going to go back and read closed issues, and if it's something being worked on it seems like there should be an existing issue for it. You won't get as many people asking about it then :)

**Comment by buba447** [comment]
Will keep open and update as progress happens.
We are currently thinking through Text rendering and deciding on a clean interface to support internationalizations.

**Comment by sjmueller** [comment]
Is there any way that @jlongster and I can help? We are about to write [crude] support for text rendering ourselves, but maybe there's a way we can all work together and perhaps land a more limited version pretty quickly?

**Comment by jnkfong** [comment]
is there any updates for text layering implementation on ios?

**Comment by AndrewBriareZya** [comment]
Add me to the list of people interested in text rendering =]

**Comment by rotorgames** [comment]
Hi everyone. Any news about it?

**Comment by sjmueller** [comment]
Hey there. Haven't heard anything, but our offer still stands; @jlongster and I can help!

**Comment by pegeseus** [comment]
I'm a little confused as to what sort of text rendering you're looking for- can you elaborate?  Lottie seems fully capable of displaying text strings for me. (or was this very recently added?)

**Comment by jfulker** [comment]
@pegeseus are you able to render text dynamically on iOS? We aren't having success rendering text (unless as glyphs exported from Bodymovin). So, dynamic text rendering.

**Comment by pegeseus** [comment]
Hi Jim, no sorry I haven't tried it on iOS.  We are only using it to render
in html and seems to work fine.

**Comment by jtleniger** [comment]
Is there any update to this yet?

**Comment by DanielBoa** [comment]
🙋‍♂️ Would love to see support for this too

**Comment by samiam2017** [comment]
Hey @buba447 thanks again for all your help supporting this tool, been a game changer! I was searching through the github repository and found this request, wanted to +1 on it, we definitely need dynamic text rendering. Is there any target for delivering this functionality?

**Comment by Leocata14** [comment]
Hi @buba447 any update on text rendering? It would be extremely helpful!

**Comment by buba447** [comment]
Hey everyone! Believe it or not this repo is still alive! Hoping to update everyone on the status of this in the new year!

**Comment by denistrofimov** [comment]
+

**Comment by boria-good** [comment]
+1

**Comment by jtleniger** [comment]
@buba447 if you know the nature of the problem I could take a shot at a fix.

**Comment by Leocata14** [comment]
@buba447 any update on Text rendering? Would be great for iOS 😬

**Comment by buba447** [comment]
Expect big updates soon!

Godspeed,
Brandon

**Comment by buba447** [comment]
Now supported in 3.0
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC

**Comment by sadiq81** [comment]
How is dynamic text change supported in 3.0. Could you provide an example?
