### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by wanyongjian** [airbnb/lottie-ios#362]
[lottieView playFromProgress:0 toProgress:1 withCompletion:^(BOOL animationFinished) {
            lottieView.animationProgress = 1;
        }];

the code will cause crash after 2seconds at 
- (void)_removeCurrentAnimationIfNecessary {
  _playAnimation.speed = 0;
  _isAnimationPlaying = NO;
  _playAnimation.delegate = nil;
  [_compContainer removeAllAnimations];
  _playAnimation = nil;
}

**Comment by buba447** [comment]
Oh no! Ill add this to my list of investigations! Will update soon as I have somehting.

**Comment by buba447** [comment]
I just published an update 2.0.4 that should fix this! Please reopen if it does not.
