### ISSUE TITLE
Animation is removed after performing a UINavigationController push

### ISSUE THREAD

**Issue by cikpis** [airbnb/lottie-ios#363]
Hi guys, I'm having this weird issue lately. Basically, the animation is removed after performing a UINavigationController push. So, I come back with a pop, the animation is not displayed.

Seems that after update your SDK to 1.5.2 the problem is happening. Before with 1.5.1 all was working properly.

**Comment by buba447** [comment]
Hello! Have you pulled the latest 2.0.3 release and tested it?
We rewrote most of everything for it so hopefully that fixes the problem!

**Comment by cikpis** [comment]
Not yet. I'll give a try next week and I'll let you guys know. Thanks

**Comment by buba447** [comment]
@cikpis Please update when you get a chance to try out 2.0.4

**Comment by buba447** [comment]
This is fixed in 2.0.5! Please Update and verify!

**Comment by cikpis** [comment]
I'll test and I'll let you know, thanks!
