### ISSUE TITLE
ios8 crash when removeFromSuperview

### ISSUE THREAD

**Issue by whlpkk** [airbnb/lottie-ios#364]
```
- (void)removeFromSuperview {
  [super removeFromSuperview];
  self.completionBlock = nil;
  [self _removeCurrentAnimationIfNecessary];
}
```
This code when run iOS8, `[super removeFromSuperview]`may cause dealloc method, which lead 
to self wild pointer,then crash on `self.completionBlock = nil`. 
I think it may be better like this : 
```
- (void)removeFromSuperview {
  self.completionBlock = nil;
  [self _removeCurrentAnimationIfNecessary];
  [super removeFromSuperview];
}
```
my version is 2.0.3

**Comment by buba447** [comment]
I just published an update 2.0.4 that should fix this! Please reopen if it does not.
