### ISSUE TITLE
SetProgress doesn't work in iOS 8.1

### ISSUE THREAD

**Issue by rockleeee** [airbnb/lottie-ios#365]
[self.videoModeView playFromProgress:0 toProgress:1 withCompletion:nil];

This code when run iOS 8.1.1，When animation finish, the animatonProgress value turn into 0 rather than 1.I guess the reason is
LOTAnimationView will run [_compContainer removeAllAnimations] 
In  - (void)animationDidStop:(CAAnimation *)anim finished:(BOOL)flag 

How can I solve this problem 
my version is 2.0.3

**Comment by buba447** [comment]
I just published an update 2.0.4 that should fix this! Please reopen if it does not.

**Comment by rockleeee** [comment]
It's doesn't work  in iOS 8.1

**Comment by buba447** [comment]
@rockleeee Downloading the 8.1 simulator and debugging now!

**Comment by buba447** [comment]
This is fixed in 2.0.5! Please Update and verify!
