### ISSUE TITLE
support goto and stop to specific frame

### ISSUE THREAD

**Issue by chenyunguiMilook** [airbnb/lottie-ios#367]
after animation stopped, I want to goto first frame, I have tried call stop(), setProgressWithFrame(frame), animationProgress = 0, all not working, how can I do it?

**Comment by buba447** [comment]
@chenyunguiMilook Are you calling stop from the completion block?

**Comment by buba447** [comment]
This is fixed in 2.0.5! Please Update and verify!

**Comment by korntom** [comment]
3.0.4 don't working again
