### ISSUE TITLE
pod 安装失败

### ISSUE THREAD

**Issue by zjjzmw1** [airbnb/lottie-ios#37]
[!] Unable to find a specification for `lottie-ios`

**Comment by Xlff** [comment]
pod update 试试

**Comment by XTShow** [comment]
@Xlff 真的可以，但是巨慢。。。（非网络环境问题，别的速度正常）估计还是这个有什么问题吧~~~

**Comment by zjjzmw1** [comment]
@Xlff ,pod update 就OK了，挺快的。

**Comment by qiaoxueshi** [comment]
@zjjzmw1 OK了，就把 issue 关掉吧

**Comment by zjjzmw1** [comment]
已经OK了。多谢了。
