### ISSUE TITLE
Animation play is delayed

### ISSUE THREAD

**Issue by rickytan** [airbnb/lottie-ios#373]
## Lottie-ios Issue
Hello! Sorry you are having and Issue! Please help us make Lottie better by filling everything below out with as much information as you can so we can try to reproduce and fix the issue!

## Check these before submitting:
- [x] Updated to the latest (2.0.5) version of Lottie
- [x] The issue doesnt involve and [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isnt related to another open issue

## This issue is a
- [x] Non-Crashing (Visual or otherwise) Bug
- [ ] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked doesnt work anymore)

## What Platform are you on? 
- [ ] MacOS (Specify Platform Version)
- [x] iOS (Specify Platform Version)

## Expected Behavior 
![expected-behavior](https://user-images.githubusercontent.com/1250207/29344435-6d22e032-826a-11e7-80d6-c3e30ed223da.gif)

## Actual Behavior
![actual-behavior](https://user-images.githubusercontent.com/1250207/29344445-754cf126-826a-11e7-9b7e-a42770a291d0.gif)

## Code Example

```objective-c
@implementation UIView (MZAEAnimation)
- (LOTAnimationView *)mz_playAnimationNamed:(NSString *)name
                                 withOffset:(UIOffset)offset
                                     center:(CGPoint)center
                                   complete:(void (^)())complete
{
    @try {
        LOTAnimationView *animationView = [LOTAnimationView animationNamed:name];
        animationView.bounds = CGRectMake(0, 0, CGRectGetWidth(animationView.bounds) / 2, CGRectGetHeight(animationView.bounds) / 2);
        animationView.autoresizingMask = UIViewAutoresizingFlexibleTopMargin | UIViewAutoresizingFlexibleLeftMargin | UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
        animationView.contentMode = UIViewContentModeScaleAspectFill;
        animationView.clipsToBounds = NO;
        animationView.center = CGPointMake(center.x + offset.horizontal, center.y + offset.vertical);
        [self addSubview:animationView];
        [animationView playWithCompletion:^(BOOL animationFinished) {

            [animationView removeFromSuperview];
            
            !complete ?: complete();
        }];
        return animationView;
    } @catch (NSException *exception) {
        MZLogError(@"[ERROR] %@", exception);
        return nil;
    }
}
@end

@interface MyButton: UIButton
@property (strong, nonatomic) NSString *animationName;
@property (assign, nonatomic) UIOffset animationOffset;
@end

@implementation MyButton {
    UIView *_animationView;
}
- (void)setSelected:(BOOL)selected animated:(BOOL)animated {
    self.selected = selected;
    if (animated && self.animationName) {
        self.imageView.hidden = YES;
        BOOL enable = self.userInteractionEnabled;
        self.userInteractionEnabled = NO;
        _animationView = [self mz_playAnimationNamed:self.animationName
                                          withOffset:self.animationOffset
                                              center:self.imageView.center
                                            complete:^{
                                                self.imageView.hidden = NO;
                                                self.userInteractionEnabled = enable;
                                                self->_animationView = nil;
                                            }];
    }
}
@end
```

## Animation JSON

[praise-animation.json.zip](https://github.com/airbnb/lottie-ios/files/1226885/praise-animation.json.zip)

> **Notice:** This bug won't occur at the first time, but it will after using the whole app for a while!

**Comment by buba447** [comment]
Hey! This is happening because you are allocating an entire animation view each time the animation is played. Every time the button is set to selected you are making an entirely new animation view.

Allocating the animation requires a bit of overhead.
In this case we suggest allocating a single animation view when the button is initialized and adding it as a subview. Then on `setSelected` just unhide the animation and call play. In the completion block you can hide it and set its animation progress to 0 to replay next time.

The purpose of Lottie is to create Reusable vector animation views.

**Comment by rickytan** [comment]
That's not the problem, because most people only click once! After user uses the app for a while, the delay occurs, and it will delay longer if your stay in the app longer. But version `1.5.3` with #297  works perfectly
