### ISSUE TITLE
Trim Paths & Offset - Easing causes glitches

### ISSUE THREAD

**Issue by webdale** [airbnb/lottie-ios#375]
## Check these before submitting:
- [x ] Updated to the latest (2.0.5) version of Lottie
- [x ] The issue doesnt involve and [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x ] This issue isnt related to another open issue

## This issue is a
- [x ] Non-Crashing (Visual or otherwise) Bug
- [ ] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked doesnt work anymore)

## What Platform are you on? 
- [ ] MacOS (Specify Platform Version)
- [Latest ] iOS (Specify Platform Version)

## Expected Behavior 
![circle-ae](https://user-images.githubusercontent.com/31066069/29360748-3eb08364-827c-11e7-9dc6-8f81a4b4f7b8.gif)

## Actual Behavior
![circle-ios](https://user-images.githubusercontent.com/31066069/29360751-4370e740-827c-11e7-90e8-c4fb37226b0c.gif)

## Animation JSON
[circle.json.zip](https://github.com/airbnb/lottie-ios/files/1227965/circle.json.zip)

Hey all. I'm having issues when animating Trim Paths. Through deduction i've found that applying custom easing to the Start / End keyframes while animating the Offset value in a linear fashion causes visual bugs in iOS. 

I've found that removing the easing all together seems to prevent the bugs from happening, but losing easing does limit me stylistically. Any help appreciated.

**Comment by buba447** [comment]
That is a problem! Seems like some of my bezier math is off slightly! Looking into this!

**Comment by vexkiddy** [comment]
I can also state that I'm having the same issue or a related one. Animating a circle exactly like above using trim paths on a stroke layer. The animation at the bottom half of the circle seems to slow down even though there is no easing or a keyframe at this point. Its just normal linear animation. It makes it look as if the device is having problems animating the circle :(

<img width="981" alt="aftereffects trim path" src="https://user-images.githubusercontent.com/2254553/29414342-ac79bd82-835f-11e7-9bdd-7a9cbc64071c.png">
![slow-down-trim-paths](https://user-images.githubusercontent.com/2254553/29414343-ac7cef48-835f-11e7-9ebb-840a15a8a740.png)

**Comment by Gerrel** [comment]
Difference Lottie V1.5.2 and V2.0.6
![v1 5 2 success animation](https://user-images.githubusercontent.com/391656/29876992-9cac331e-8d9e-11e7-9f2d-f568e739968b.gif)
![v2 0 6 success animation](https://user-images.githubusercontent.com/391656/29876994-9cb53f36-8d9e-11e7-9794-3f3502fdbe53.gif)
![v1 5 2 fail animation](https://user-images.githubusercontent.com/391656/29876993-9cad9718-8d9e-11e7-93a4-f621445443d2.gif)
![v2 0 6 fail animation](https://user-images.githubusercontent.com/391656/29876997-9d4b3342-8d9e-11e7-8b6d-d43aa1c92c13.gif)

**Comment by mnsrv** [comment]
I have the same issue with animation like this.
If this will help you: on Android animation works well.

**Comment by buba447** [comment]
Should be fixed with https://github.com/airbnb/lottie-ios/pull/468
@mnsrv  @Gerrel @vexkiddy @webdale
