### ISSUE TITLE
Reverse animations snap back to "completed" state after animation plays

### ISSUE THREAD

**Issue by welshm** [airbnb/lottie-ios#378]
Related to [PR 337](https://github.com/airbnb/lottie-ios/pull/377)

## Lottie-ios Issue
Hello! Sorry you are having and Issue! Please help us make Lottie better by filling everything below out with as much information as you can so we can try to reproduce and fix the issue!

## Check these before submitting:
- [x] Updated to the latest (2.0.5) version of Lottie
- [x] The issue doesnt involve and [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isnt related to another open issue

## This issue is a
- [x] Non-Crashing (Visual or otherwise) Bug
- [ ] Crashing Bug
- [ ] Feature Request
- [x] Regression (Something that once worked doesnt work anymore)

## What Platform are you on? 
- [ ] MacOS (Specify Platform Version)
- [x] iOS (Specify Platform Version) - 10.3.3

## Expected Behavior 
Reverse animation doesn't snap back

## Actual Behavior
Reverse animation snaps back

## Code Example
```
- (void)toggle:(GRBToggleControl *)control {
  if (!self.userInteractionEnabled) {
    // We're already handling an event.
    return;
  }
  LOTAnimationCompletionBlock restoreInteraction = ^(BOOL animationFinished) {
    self.userInteractionEnabled = YES;
    if (!self.selected) {
      // If we played the animation backwards, the transition looks correct, but upon finishing the
      // animation lottie sets the progress to "1" which causes the animation to then jump to the
      // end state (which is selected, in this case, and incorrect).
      // Ideally this isn't needed.
      self.toggle.animationProgress = 0;
    }
  };
  self.userInteractionEnabled = NO;
  [self.toggle pause];
  self.toggle.animationSpeed = self.selected ? -1 : 1;
  [self.toggle playWithCompletion:restoreInteraction];
  self.selected = !self.selected;
}
```
## Animation JSON
Adding the animation JSON helps us debug the issue faster!

**Comment by buba447** [comment]
Resolved! Thank you!
