### ISSUE TITLE
Running transitions causes delay of all of lottie animations

### ISSUE THREAD

**Issue by MaximKotliar** [airbnb/lottie-ios#380]
Hi, i have experience a very strange behavior with transition. 
Issue also reproduce in sample iOS project.

When you play view controller transition many times, all lottie animations will start playing with delay in entire app. Transition, and other animations delay are strictly related on how many times transition played.

Little  research:
First frame are loads normally, then delay, then animation run.
Don't see any memory leaks.

I've print animation running time in console. 
Capture start time  just above this line in `LOTAnimationTransitionController.m`:
`[tranistionAnimationView_ playWithCompletion:^(BOOL animationFinished) `
and print summary in completion.

Thats what i've got after 10 times of repeating transition:
1. 0.548470973968506
2. 0.615983963012695
3. 0.776231050491333
4. 0.833992004394531
5. 0.920691013336182
6. 0.991307973861694
7. 1.08101916313171
8. 1.14047503471375
9. 1.20183897018433
10. 1.2439692856484

Same behavior in Simulators(9,10,11), phones(10,11)

I don't attach sources, because issue reproduces in iOS Example project.
Keep digging and i'll let you know if i find something.

UPD:
I've found a way to fix it, but i'ts definitely not a right way.
Comment line 325(315 for pod) in `LOTAnimationView.m` which looks:
`animation.beginTime = CACurrentMediaTime() - offset;`

And the most strange thing is that offset calculates right, cause when i remove it like that:
`animation.beginTime = CACurrentMediaTime();`
the issue stays, but if remove all line - all is good.
How can transitions affect CACurrentMediaTime() result? I'm confused.

**Comment by buba447** [comment]
Dang! Ive noticed a lot of weird CAAnimation bugs with begin time. 
Im gonna look into it.

**Comment by buba447** [comment]
Just pushed an update (2.0.6) that might fix this! Please download and verify and let me know! Thank you!
@MaximKotliar

**Comment by MaximKotliar** [comment]
Yup, now works correctly, many thanks @buba44
