### ISSUE TITLE
Memory Leak：100.00% LOT_Subpath *subPath = (LOT_Subpath *)malloc(sizeof(LOT_Subpath));

### ISSUE THREAD

**Issue by colin1994** [airbnb/lottie-ios#381]
![20170820150321001820701.jpg](http://7xkc7a.com1.z0.glb.clouddn.com/20170820150321001820701.jpg?imageView2/0/format/jpg)

100.00% LOT_Subpath *subPath = (LOT_Subpath *)malloc(sizeof(LOT_Subpath));

**How can I fix it ?**

**Comment by imsuperman** [comment]
same problem..

**Comment by rockleeee** [comment]
same problem..

**Comment by buba447** [comment]
Which version of lottie are you on?

**Comment by buba447** [comment]
Released!

**Comment by colin1994** [comment]
@buba447   Validated, it works. Thank you.
