### ISSUE TITLE
Memory Leak issue in [LOTLayerContainer display]

### ISSUE THREAD

**Issue by imsuperman** [airbnb/lottie-ios#388]
**Memory Leak in [LOTLayerContainer display]**
Is there a way to fix it? 
Thank you

<img width="1004" alt="wx20170824-152857 2x" src="https://user-images.githubusercontent.com/11495232/29654763-1b97d36c-88e1-11e7-9729-a2eb93071095.png">

**Comment by buba447** [comment]
Could you please fill out the issue form that was provided?
I cant help you without further context.

**Comment by buba447** [comment]
Closing as I believe the bug was fixed. Please reopen if you update and it persists.

**Comment by asilavistaVeesto** [comment]
Hey, i'm using Lottie too (swift & Objective-C), with the most updated pod ver. and i think there is memory leak too. i'm using xCode's instruments tool to detect the memory issues, and from some reason the memory increasing when loading animation after animation event that i set cacheEnable = false.
