### ISSUE TITLE
i want get more lottieFile,but i don`t kown where is find it 

### ISSUE THREAD

**Issue by xavierXing** [airbnb/lottie-ios#390]
i saw this library and i think this is magic,but when i  go this link(https://www.lottiefiles.com/) didn't find what I wanted
Is there any other resource???

**Comment by buba447** [comment]
Yeah! Our own animator Salih Abdul-Karim just animated a ton of the icons from Modern Pictogram and released them over here https://airbnb.design/modern-pictograms-for-lottie/

Theyre beautiful and delightful.

**Comment by xavierXing** [comment]
@buba447 
thank you answer my question;
I want to say is, at present on the website (https://www.lottiefiles.com/) can see resources cannot meet the requirements of I, I mean in addition to the web site (https://www.lottiefiles.com/), there are other sites offer this animation files to download?

**Comment by buba447** [comment]
There are additional animations to download here https://airbnb.design/modern-pictograms-for-lottie/
