### ISSUE TITLE
Transparency/alpha effect not working

### ISSUE THREAD

**Issue by D-Mx** [airbnb/lottie-ios#397]
## Lottie-ios Issue
Hello! We're doing some tests with lottie and got a problem with a mask/transparency. In this example we have some gradient transitions and a car silhouette zooming in, this car should be transparent to show what it's behind of it. The json works on both android and web, but in iOS we get the car filled with black.

## Check these before submitting:
- [x] Updated to the latest (2.1.0) version of Lottie
- [x] The issue doesnt involve and [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isnt related to another open issue

## This issue is a
- [x] Non-Crashing (Visual or otherwise) Bug
- [ ] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked doesnt work anymore)

## What Platform are you on? 
- [ ] MacOS (Specify Platform Version)
- [x] iOS (Specify Platform Version)

## Expected Behavior 
[https://www.lottiefiles.com/share/H3is69](https://www.lottiefiles.com/share/H3is69)

## Actual Behavior
![screen shot 2017-08-29 at 3 45 20 pm](https://user-images.githubusercontent.com/409270/29843287-1b710036-8cd1-11e7-8aef-a1379171117a.png)

## Animation JSON
[all sequence.json.zip](https://github.com/airbnb/lottie-ios/files/1261691/all.sequence.json.zip)
[States Project.aep.zip](https://github.com/airbnb/lottie-ios/files/1261692/States.Project.aep.zip)

**Comment by buba447** [comment]
Ahh this is because we dont currently support Alpha-Inverted Mattes. Only regular mattes. You can convert your shape to a mask though and us and inverted mask :)

**Comment by D-Mx** [comment]
I see, sorry I thought you did because of this issue https://github.com/airbnb/lottie-ios/issues/93

**Comment by buba447** [comment]
@D-Mx Sorry for the confusion! That was a mis-marked issue!

**Comment by rowanwernham** [comment]
@buba447 - is there any timeline for iOS parity for the Alpha Inverted Mattes?

We created a whole lot of animations for a project which use them and didn't catch that they weren't supported.

Thought I would check in before we go about the (somewhat time consuming!) process of hacking fixes for all the masks.

Thanks!

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
