### ISSUE TITLE
are project settings throwing off an animation?

### ISSUE THREAD

**Issue by tonisevener** [airbnb/lottie-ios#399]
## Lottie-ios Issue
Using Lottie version 2.1.3. It doesn't work in our main project. Animation seems to be dropping frames and has large blocks of the same color, but it works fine when I try it a blank sample project. Both have the same cocoapods setup, same deployment target. We also have other animations that work fine in our main project. ENABLE_DEBUG_LOGGING does not write out anything. Tested on iOS 10.3.3 iPhone 6s Plus.

## Check these before submitting:
- [x ] Updated to the latest (2.0.5) version of Lottie
- [x ] The issue doesnt involve and [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x ] This issue isnt related to another open issue

## This issue is a
- [x ] Non-Crashing (Visual or otherwise) Bug
- [ ] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked doesnt work anymore)

## What Platform are you on? 
- [ ] MacOS (Specify Platform Version)
- [x ] iOS (Specify Platform Version)

## Expected Behavior 
![ezgif-4-22d43f3a8d](https://user-images.githubusercontent.com/3620196/29882653-51c5b7ec-8d73-11e7-8d9c-0e5de750e83a.gif)

## Actual Behavior
![ezgif-4-87e3e5ebf0](https://user-images.githubusercontent.com/3620196/29882662-56618718-8d73-11e7-9a25-a1cb98d72c71.gif)

## Animation JSON
[heartpop.txt](https://github.com/airbnb/lottie-ios/files/1264253/heartpop.txt)

Note from our designer:
It's all size and position, or layer on/off. Even the lines, they resize width from the center and move position — it looks like a mask but it's actually just a positioning trick to make it appear as if it's being masked away.

**Comment by buba447** [comment]
Thats very strange! Ive ran it on a couple of devices and on the mac app and the result is the expected animation everywhere.

Is there anything else you are doing with the animation code wise? Is it only happening on the 6s plus?

**Comment by buba447** [comment]
Did it work on 2.1.0 ?

**Comment by tonisevener** [comment]
I see the same result on a 6S, also same result with version 2.1.0. No difference in code, I just copied AnimationExplorerViewController (and related files) from the example project into our project.

**Comment by buba447** [comment]
Hmmm, I cant seem to reproduce. Can you recreate in a project and send it to me?

**Comment by tonisevener** [comment]
Update on this - it seems to fix itself when I tinker with the "Build Active Architecture Only" flag in the Pods project. If I set them all to NO, then back to their previous values, then clean and build it works. Not sure what's happening behind the scenes but I think I'm good now, thanks.

![pods1](https://user-images.githubusercontent.com/3620196/29948427-67ffa624-8e74-11e7-84a4-fbc41c0d8d5e.jpeg)

**Comment by andreyreddit** [comment]
I have the same issue in Debug conf, but don't have in Release configuration. Please fix.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
