### ISSUE TITLE
Can I use this library with Swift?

### ISSUE THREAD

**Issue by agisilaos** [airbnb/lottie-ios#4]
Hello guys, 

Awesome Library, thanks for sharing it with us! One quick question: Is it possible to use this library with swift? And if I can, how so?

**Comment by buba447** [comment]
@agisilaos If you add it to your bridging header it should work in Swift no problem :) 
This is also how most of UIKit is implemented in swift.

**Comment by galileomd** [comment]
any swift examples?

**Comment by buba447** [comment]
@galileomd @agisilaos 
Add `#import <Lottie/Lottie.h>` to your swift bridging header
Then you can `import Lottie` to your swift files and use lottie as follows:

```let animationView = LAAnimationView.animationNamed("hamburger")
    self.view.addSubview(animationView!)
    
    animationView?.play(completion: { (finished) in
      //Do Something
    })```

**Comment by buba447** [comment]
I will update the readme to include these instructions!

**Comment by agisilaos** [comment]
Nice, thanks a lot @buba447! I will definitely gonna use it!

**Comment by milanivarni** [comment]
## Analyzing dependencies
[!] Unable to find a specification for `lottie-ios`

While integrating with **Swift 3.0** Project **Xcode 8**

**Comment by RahulDhiman93** [comment]
No such module 'Lottie'
