### ISSUE TITLE
Another Trim Paths + Easing Glitch

### ISSUE THREAD

**Issue by phillfarrugia** [airbnb/lottie-ios#401]
## Lottie-ios Issue
Our animation is working mostly fine except for a very odd glitch in which part of a stroke disappears and then reappears mid-way through, the animation. In After Effects we're using trim paths on a black stroke with easing, and it's creating a glitch mid-animation.

Lottie iOS version 2.1.3 on iOS Deployment Target 10.0 and above. 

I've also tested this JSON file in the Lottie Sample MacOS application to validate my iOS implementation and the issue exists when displaying it in the sample app.

Note: We've examined Issue #375 and believe this issue to not be related, so have created this as a separate issue. Apologies if these two are related.

## Check these before submitting:
- [x] Updated to the latest (2.1.3) version of Lottie
- [x] The issue doesnt involve and [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isnt related to another open issue

## This issue is a
- [x] Non-Crashing (Visual or otherwise) Bug
- [ ] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked doesnt work anymore)

## What Platform are you on? 
- [ ] MacOS (Specify Platform Version)
- [x] iOS (Specify Platform Version)

## Expected Behavior 
![correct](https://user-images.githubusercontent.com/4746329/29949177-ccd3e6da-8e67-11e7-8d8d-f5f264b9fdd7.gif)

Black stroke path closes, and then animates into the tick.

## Actual Behavior
![incorrect](https://user-images.githubusercontent.com/4746329/29949179-d1868da4-8e67-11e7-8f88-5acdcb30a672.gif)

As the black stroke path closes, the top right portion of the ring flashes away then back before animating to the tick.

## Code Example

```
@IBOutlet private weak var scanButtonAnimationView: UIView!

    private var scanAnimation = LOTAnimationView(name: "sephora-progress-8")

    override func awakeFromNib() {
        super.awakeFromNib()

        scanAnimation.frame = scanButtonAnimationView.bounds
        scanButtonAnimationView.addSubview(scanAnimation)
        scanAnimation.play()
    }
```

## Animation JSON
Adding the animation JSON helps us debug the issue faster!

[circle-animation.zip](https://github.com/airbnb/lottie-ios/files/1268746/circle-animation.zip)

**Comment by buba447** [comment]
Ahh I think this is actually the same bug as the other, just coming out in a different way!
We are working on a fix! Sorry for the delay!

**Comment by phillfarrugia** [comment]
Thanks @buba447 - much appreciated! 😊

**Comment by binderalex** [comment]
Tell your designer to duplicate the stroke they are animating and put it above the flashing one above. Then remove the easing keyframes right around when the trim paths hits 100%. It's definitely a work around but it worked for me. I am have the same problem and fixed it that way. Let me know if you want details or to see my file @buba447 @phillfarrugia.

**Comment by buba447** [comment]
Should be fixed with https://github.com/airbnb/lottie-ios/pull/468

@phillfarrugia @binderalex
