### ISSUE TITLE
[Bug]Lottie animation being invalidate when calling setImageDrawable after setAnimation in LottieAnimationView

### ISSUE THREAD

**Issue by fengbaobao** [airbnb/lottie-ios#403]
## Lottie-ios Issue

I found some problem in LottieAnimationView(Version 2.1.0). Once I called the LottieAnimationView.setAnimation(animationName, LottieAnimationView.CacheStrategy cacheStrategy) function. Then I call LottieAnimationView.setAnimation with the same animationName after I call the  LottieAnimationView.setImageDrawable() function. The lottie animation will be invalidate. That is because LottieAnimationView and LottieDrawable in LottieAnimationView both cache the same LottieComposition object for animationName is the same. And LottieAnimationView.setAnimation() function just check whether the  LottieComposition is changed, not check whether the Drawable in LottieAnimationView has changed. 

Maybe make LottieAnimationView.setComposition like below will be better?

    `if(isNewComposition) {
          // ...
      } else if (getDrawable() != this.lottieDrawable) {
         this.setImageDrawable(this.lottieDrawable);
         this.requestLayout();
     }`  

## Check these before submitting:
LottieDrawable::
<img width="531" alt="lottie_bugs_001_d4796a2a-603c-45ba-92c6-9ee09113fea1" src="https://user-images.githubusercontent.com/9740623/30021673-c01a306c-919a-11e7-9ccc-d4ec288ef621.png">

LottieAnimationView::
<img width="850" alt="lottie_bug_002_3ba95a47-b391-4f8b-8d7a-ed4d1c426f64" src="https://user-images.githubusercontent.com/9740623/30021674-c01df864-919a-11e7-99a7-25fadb0a3d3a.png">

**Comment by buba447** [comment]
@fengbaobao Hello! this seems to be an android issue? Do you mind posting it over at https://github.com/airbnb/lottie-android ?
