### ISSUE TITLE
Animation flashes in the middle of animation

### ISSUE THREAD

**Issue by aleksanderaleksic** [airbnb/lottie-ios#407]
## Lottie-ios Issue
Hi!

My designer created a animation for me to use in out IOS app.
But for some reason it flashes in the middle of the animation.
This is not at the beginning of the animation, so the problem should not be looping. 

My designer also says that nothing happens in the composition at the moment it flashes.

I added some videos, the one that shows how it should look like (recorded from browser),
and another one showing the problem (recorded from iPhone). The error happens at 10th and 24th second of the video. 

## Check these before submitting:
- [X] Updated to the latest (2.1.3) version of Lottie
- [X] The issue doesnt involve and [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [X] This issue isnt related to another open issue

## This issue is a
- [X] Non-Crashing (Visual or otherwise) Bug
- [ ] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked doesnt work anymore)

## What Platform are you on? 
- [ ] MacOS (Specify Platform Version)
- [X] iOS (Specify Platform Version)

## Expected Behavior 
[Recorded from browser](https://vimeo.com/232475661)

## Actual Behavior
[Vimeo of the problem](https://vimeo.com/232475026)

## Code Example

```
        let animationView = LOTAnimationView(name: "alt-klart")
        animationView.frame = CGRect(x: 0, y: 0, width: self.lottieView.frame.size.width, height: self.lottieView.frame.size.height)
        animationView.contentMode = .scaleAspectFill
        self.lottieView.addSubview(animationView)
        
        animationView.loopAnimation = true
        animationView.play()
```

## Animation JSON
[JSON File](https://www.dropbox.com/s/775zteepyv3bxmx/alt-klart.json?dl=0)

**Comment by buba447** [comment]
Hmm that is strange!
I did not see the flash on my side when I ran it in the Lottie-Example app. Also the animation seems to be playing slower on my side. Is there a chance you are increasing the speed of the animation? Is there any way I could see the animation After Effects file?

**Comment by aleksanderaleksic** [comment]
I tried the same thing and it works fine in the Lottie preview app.
I think the speed looks good, and i am not affecting that in my code eighter.
All the code is in the description, its really nothing else to it.

The Designer didn't really want to share the AE file, but it seams that there is something else in the app that affects it, so i will try to look trough it.

**Comment by aleksanderaleksic** [comment]
Well this was awkward. 
I was certain that i had the latest Lottie version installed, as i updated a weak a go. 
But for some reason the current version was 1.5.2, updating the pod fixed the issue.
