### ISSUE TITLE
Exported .json is looking "wrong" and fails in xcode saying "no current point"

### ISSUE THREAD

**Issue by charlesbibi** [airbnb/lottie-ios#410]
Hi,

I have a problem after the export from AE with bodymovin, when opening the .json file, it looks like this:
<img width="261" alt="screen shot 2017-09-06 at 11 28 17" src="https://user-images.githubusercontent.com/31690551/30118678-ecc71e60-9323-11e7-8a96-87895d21b88b.png">

When everywhere else I look in demos, blog posts and all, it should start like this:
<img width="255" alt="screen shot 2017-09-06 at 11 28 40" src="https://user-images.githubusercontent.com/31690551/30118685-f1c9022a-9323-11e7-93a9-55465ef01921.png">

Am I missing something? Is there something wrong with my comp?

I tried all the different settings in bodymovin, doesn't change a thing.
I have AE version 13.2.0.49
Here is my source file:

[payconfirmmaster.aep.zip](https://github.com/airbnb/lottie-ios/files/1281535/payconfirmmaster.aep.zip)

Thanks for the help!

**Comment by buba447** [comment]
I exported your animation and it opened with the Lottie-Viewer just fine.
There are some glitches with the animation, but the JSON is sound and plays.

Currently Text Layers arent supported by Lottie-iOS and Alpha inverted masks arent supported either.

**Comment by charlesbibi** [comment]
Thanks buba447.
Yes it works but the glitches are definitely coming from trim paths.
I have only shapes with basic animations in after effects, the only "advanced" thing is trim path and it makes the animation break.
I tried without the effect and it looks just fine.
Only the trim paths with an "offset" value are broken.

**Comment by buba447** [comment]
This seems similar to https://github.com/airbnb/lottie-ios/issues/375
Its on my short list of todos right now!
Im going to close this issue and you can track the trim path bug on the other issue.
