### ISSUE TITLE
[iOS] Enable Debugging in Swift

### ISSUE THREAD

**Issue by ZkHaider** [airbnb/lottie-ios#411]
Possibly a very simple answer for this question but I am trying to enable debugging via `LOTHelpers.h` to see if an animation is running properly and I can't seem to access it or set it, how can I do this?

I am using Carthage btw.

**Comment by buba447** [comment]
You have to set it by manually changing the flag in `LOTHelpers.h`
Currently theres no way to programmatically change it.
