### ISSUE TITLE
why set completion block to nil?

### ISSUE THREAD

**Issue by zhousq300** [airbnb/lottie-ios#412]
## Lottie-ios Issue
There is many way invoke completion, thus set the completion to nil, you cannot invoke the completion when you need

## Code Example
- (void)_callCompletionIfNecessary:(BOOL)complete {
  if (self.completionBlock) {
    LOTAnimationCompletionBlock completion = self.completionBlock;
    self.completionBlock = nil;
    completion(complete);
  }
}

**Comment by buba447** [comment]
The completion block is called and nilled out anytime the animation stops. This seemed like the most logical way to build it, as it most closely resembles UIView animation completion blocks.
