### ISSUE TITLE
after app goes to background animation stops

### ISSUE THREAD

**Issue by maurovc** [airbnb/lottie-ios#413]
## This issue is a
- Non-Crashing (Visual or otherwise) Bug
- Regression (Something that once worked doesnt work anymore)

## What Platform are you on? 
- iOS 10

## Expected Behavior 
The animation is resumed.

## Actual Behavior
After the app comes back from background with an infinite animation. The animation is stoped.

**Comment by buba447** [comment]
This is just how Apple handles animations. CAAnimations are stopped and removed when the app is backgrounded. If you pause the animation before the app is backgrounded the state will be preserved so you can play again when the app is foregrounded.

For the best results, pause the animation when the app is backgrounded by either listening to the UIApplicationDidEnterBackgroundNotification or viewWillDissapear, and then play again when the app is foregrounded.

**Comment by revolter** [comment]
@buba447, Couldn't Lottie do this instead?

**Comment by Dellybro** [comment]
@revolter I think the reason they don't is to give more control to the developer.

**Comment by revolter** [comment]
Yeah but I tend to think that the majority of people want animations to automatically pause and resume on app background and foreground.

**Comment by alongenosar** [comment]
Set the backgroundBehavior to .pauseAndRestore 

`let lottie = AnimationView()
lottie. backgroundBehavior = .pauseAndRestore `

**Comment by vipinsaini0** [comment]
> Set the backgroundBehavior to .pauseAndRestore
> 
> `let lottie = AnimationView() lottie.backgroundBehavior = .pauseAndRestore`

Thanks It help a lot 👍

**Comment by Sriharsh11** [comment]
> Set the backgroundBehavior to .pauseAndRestore
> 
> `let lottie = AnimationView() lottie.backgroundBehavior = .pauseAndRestore`

worked like 💫
