### ISSUE TITLE
error: Keypath Not Found

### ISSUE THREAD

**Issue by tehfailsafe** [airbnb/lottie-ios#416]
Using 2.1.3, I am getting an error trying to dynamically change the opacity of a shape layer. I used `animationView.logHierarchyKeypaths()` to get the available paths. Copying a path from the print and using it returns the error `keypath not found`

![image](https://user-images.githubusercontent.com/1388454/30351951-892b5f98-97d2-11e7-8c85-6addfd123869.png)

![image](https://user-images.githubusercontent.com/1388454/30351894-5445586a-97d2-11e7-9c7c-8e152f978dbd.png)

![image](https://user-images.githubusercontent.com/1388454/30351932-7e122150-97d2-11e7-97eb-fdb19cdda3a1.png)

**Comment by buba447** [comment]
Hmm thats odd. Do you mind sharing the animation json with me so I can
debug?

**Comment by tehfailsafe** [comment]
Unfortunately I can't, I'll have to make a replica and see if it does the same.

**Comment by tehfailsafe** [comment]
Made a simpler version and now I can easily access the keypaths... Hm. What could possibly make that happen? Expressions? adding a "/" to a layer name? (not that I have either, just trying to troubleshoot)

**Comment by tehfailsafe** [comment]
Ah ha! I am rendering out a preComp to scale a motion design down from 3x. I am editing in the main comp and totally forgot about the precomp.

So the keypaths listed need to be modified to `preComp.volume.byFilll.Fill 1.opacity`

**Comment by buba447** [comment]
Ahh! That makes sense. Did the precomp name not print in 'logKeypaths' ?
Ill look into adding that.
Thanks for bringing this up!
