### ISSUE TITLE
Keypath Not Found even though the path got printed out using logHierarchyKeypaths

### ISSUE THREAD

**Issue by gracegotlost** [airbnb/lottie-ios#417]
## Lottie-ios Issue
Hi there!

I want to change the color of my animation, so I firstly use

>  [self.spinnerView logHierarchyKeypaths];

 to print out all available paths, and then use 

> [self.spinnerView setValue:[UIColor colorWithRed:0 green:0 blue:0 alpha:1] forKeypath:@"Shape Layer 2.Ellipse 1.Stroke 1.Color" atFrame:@0]; 

to change the color. However, when I ran it, I got an error printed out as 

> -[LOTAnimationView setValue:forKeypath:atFrame:]: Keypath Not Found: Shape Layer 2.Ellipse 1.Stroke 1.Color

I don't know why I still got this error `Keypath Not Found` since I've verified it's an available path. I wonder if anyone has any suggestion on this issue. Thanks a lot!

## Check these before submitting:
- [ x] Updated to the latest (2.1.3) version of Lottie
- [ x] The issue doesn't involve and [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [ x] This issue isn't related to another open issue

## This issue is a
- [ x] Non-Crashing (Visual or otherwise) Bug
- [ ] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked doesn't work anymore)

## What Platform are you on? 
- [ ] MacOS (Specify Platform Version)
- [x ] iOS (Specify Platform Version)

## Code Example
![screen shot 2017-09-13 at 6 37 53 pm](https://user-images.githubusercontent.com/5125549/30408851-42f19530-98b6-11e7-82e6-1e04bb38b448.png)

## Animation JSON
Adding the animation JSON helps us debug the issue faster!

`{"v":"4.10.1","fr":30,"ip":0,"op":156,"w":300,"h":300,"nm":"spinner_lasrt","ddd":0,"assets":[{"id":"comp_6","layers":[{"ddd":0,"ind":1,"ty":0,"nm":"original loader ","refId":"comp_7","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":116.116,"s":[180],"e":[360]},{"t":156.156156156156}],"ix":10},"p":{"a":0,"k":[960,540,0],"ix":2},"a":{"a":0,"k":[960,540,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"w":1920,"h":1080,"ip":116.116116116116,"op":156.156156156156,"st":116.116116116116,"bm":0},{"ddd":0,"ind":2,"ty":0,"nm":"original loader ","refId":"comp_7","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":77.077,"s":[0],"e":[180]},{"t":117.117117117117}],"ix":10},"p":{"a":0,"k":[960,540,0],"ix":2},"a":{"a":0,"k":[960,540,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"w":1920,"h":1080,"ip":77.0770770770771,"op":117.117117117117,"st":77.0770770770771,"bm":0},{"ddd":0,"ind":3,"ty":0,"nm":"original loader ","refId":"comp_7","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":38.038,"s":[180],"e":[360]},{"t":78.0780780780781}],"ix":10},"p":{"a":0,"k":[960,540,0],"ix":2},"a":{"a":0,"k":[960,540,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"w":1920,"h":1080,"ip":38.038038038038,"op":78.0780780780781,"st":38.038038038038,"bm":0},{"ddd":0,"ind":4,"ty":0,"nm":"original loader ","refId":"comp_7","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":0,"s":[0],"e":[180]},{"t":39.039039039039}],"ix":10},"p":{"a":0,"k":[960,540,0],"ix":2},"a":{"a":0,"k":[960,540,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"w":1920,"h":1080,"ip":-1.001001001001,"op":39.039039039039,"st":-1.001001001001,"bm":0}]},{"id":"comp_7","layers":[{"ddd":0,"ind":1,"ty":4,"nm":"Shape Layer 2","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[961.312,540.445,0],"ix":2},"a":{"a":0,"k":[-4,12,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"d":2,"ty":"el","s":{"a":0,"k":[189.094,189.094],"ix":2},"p":{"a":0,"k":[0,0],"ix":3},"nm":"Ellipse Path 1","mn":"ADBE Vector Shape - Ellipse","hd":false},{"ty":"tm","s":{"a":1,"k":[{"i":{"x":[0],"y":[1]},"o":{"x":[0.333],"y":[0]},"n":["0_1_0p333_0"],"t":10.01,"s":[0],"e":[100]},{"t":40.04004004004}],"ix":1},"e":{"a":1,"k":[{"i":{"x":[0],"y":[1]},"o":{"x":[0.333],"y":[0]},"n":["0_1_0p333_0"],"t":0,"s":[0],"e":[100]},{"t":30.03003003003}],"ix":2},"o":{"a":0,"k":0,"ix":3},"m":1,"ix":2,"nm":"Trim Paths 1","mn":"ADBE Vector Filter - Trim","hd":false},{"ty":"st","c":{"a":0,"k":[0.86274510622,0.984313726425,0.011764706112,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":25,"ix":5},"lc":2,"lj":1,"ml":4,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"tr","p":{"a":0,"k":[-5.312,11.555],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Ellipse 1","np":4,"cix":2,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":121.121121121121,"st":0,"bm":0}]}],"layers":[{"ddd":0,"ind":1,"ty":0,"nm":"Spinner","refId":"comp_6","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[150,150,0],"ix":2},"a":{"a":0,"k":[960,540,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"w":1920,"h":1080,"ip":0,"op":480.480480480481,"st":0,"bm":0}]}`

**Comment by buba447** [comment]
The keypath is inside of a precomp, theres a bug in the keypath logger that doesnt log precomp layers in the keypath.

**Comment by gracegotlost** [comment]
@buba447 Thanks so much for your reply! But I've also tried to add the precomp layers before the logger like this:

> [self.spinnerView setValue:[UIColor colorWithRed:0 green:0 blue:0 alpha:1] forKeypath:@"Spinner.original loader.Shape Layer 2.Ellipse 1.Stroke 1.Color" atFrame:@0];

But it still didn't change the color. Do you think it should be a different keypath?

Thanks again for your help!

**Comment by buba447** [comment]
Finally Looked over your JSON. Looks like 'original loader' has a whitespace at the end of the name.

`"Spinner.original loader .Shape Layer 2.Ellipse 1.Stroke 1.Color"`

Id suggest simplifying your names in after effects.

**Comment by gracegotlost** [comment]
@buba447 Thanks so much for helping me to investigate! I've tried and it did work for one cycle of the spin. But it doesn't seem to work for all cycles since under `Spinner` there are four `original loader ` underneath. May I ask if you have any suggestions on this part?

Thanks again!!

**Comment by buba447** [comment]
Finally fixed this bug!
