### ISSUE TITLE
Reopened - Animation call back is not invoked when app is sent to background and put to foreground in the middle of animation in v2.0.5

### ISSUE THREAD

**Issue by venkatanavn** [airbnb/lottie-ios#419]
I updated the Lottie SDK from v1.5.1 to v2.0.3. I see the below mentioned issue on the new v2.0.3 and v2.0.4 (This issues is not there in v1.5.1). It was believed to be fixed in v2.0.5...So I updated to v2.0.5 and I still see the issue. Please help me.
 
Steps to reproduce:
. Play the animation using the below method 
func play(completion: Lottie.LOTAnimationCompletionBlock? = nil)
.  Dismiss the app to background in the middle of animation. Open the app again (i.e. get to foreground) 
. Now observe that the completionBlock is not invoked.

 Please let me know.

Thanks,
Venkata Naveen.

**Comment by buba447** [comment]
The completion block is nil, so its not being called?

Also if the app is backgrounded the animations will be removed and the state will be uncertain. You can use either the viewWillDisappear or the ApplicationWillEnterBackground notification to pause the animation and then start it again when the app foregrounds

**Comment by venkatanavn** [comment]
For my use cases, I am not concerned about the progress of the animation... I dont really care even if the animation is completed / not completed when it is in the background..

But I am expecting the completion block to be called once the animation is completed (The completion block here is from the Lottie SDK of the method play(**completion**: Lottie.LOTAnimationCompletionBlock? = nil))...I am expecting that this **completion block** should be called irrespective of the app state (i.e. foreground / background) once animation is completed.

 DispatchQueue.main.async {
                animationView.play(completion: { finished in
                    // Do Something
**_print("This is not called/invoked after getting the app to foreground")_**
                })
            }

Please correct me if I am wrong..

**Comment by venkatanavn** [comment]
@buba447  can you please help me with this?

**Comment by venkatanavn** [comment]
Hi @buba447 , I am calling the **Pause()** method on the animation which invokes the completion block while app is resigning active in the 'applicationWillResignActive()' method. So my completionBlock is getting called which is what I require for my specific use case... So, my problem is resolved :) Thanks again..

**Comment by buba447** [comment]
Should be fixed with latest update

**Comment by revolter** [comment]
@buba447, It isn't fixed.
