### ISSUE TITLE
should consider exposing containing CALayer for animations

### ISSUE THREAD

**Issue by cgmaier** [airbnb/lottie-ios#42]
Even though it appears all of the animating happens in the domain of Core Animation, the animations can only be accessed via UIView. Would be nice to be able to instantiate animations for CALayers as well, so that they may be used in contexts which require layers.

**Comment by buba447** [comment]
@cgmaier The animations are limited to a single layer, they are nested within a hierarchy of layers so they cannot be easily exposed. What is it that you would like to do with the exposed animations?

**Comment by cgmaier** [comment]
Hey sorry for the late reply! I’d like to explore this as a way of adding dynamic vector-drawn content to video using AVSynchronizedLayer / AVVideoCompositionCoreAnimationTool, or to Scene Kit by setting the diffuse property of a material to a CALayer. In order to do this should just a need a reference to the root/parent layer of that hierarchy you mention, no?

**Comment by buba447** [comment]
@cgmaier The parent layer would be the LOTAnimationView(*).layer
Im not sure if the animation will play or scrub properly in those scenarios. See this issue https://github.com/airbnb/lottie-ios/issues/30
