### ISSUE TITLE
The  animation  json  don't  work . Can you help me solve this problem?

### ISSUE THREAD

**Issue by kule123** [airbnb/lottie-ios#420]
## Lottie-ios Issue
Hello! Sorry you are having an Issue! Please help us make Lottie better by filling everything below out with as much information as you can so we can try to reproduce and fix the issue!

## Check these before submitting:
- [x] Updated to the latest (2.1.3) version of Lottie
- [ ] The issue doesnt involve and [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [ ] This issue isnt related to another open issue

## This issue is a
- [ ] Non-Crashing (Visual or otherwise) Bug
- [ ] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked doesnt work anymore)

## What Platform are you on? 
- [ ] MacOS (Specify Platform Version)
- [x] iOS (Specify Platform Version)

## Expected Behavior 
(Screenshots encouraged)

## Actual Behavior
(Screenshots encouraged)

## Animation JSON
Adding the animation JSON helps us debug the issue faster!
[data.json.zip](https://github.com/airbnb/lottie-ios/files/1309646/data.json.zip)

**Comment by kule123** [comment]
@buba447    Can you help me solve this problem?

**Comment by buba447** [comment]
@kule123 can i see the after effects file?

**Comment by kule123** [comment]
@buba447 
[动画.aep.zip](https://github.com/airbnb/lottie-ios/files/1316394/aep.zip)        you can see the file

**Comment by kule123** [comment]
@buba447     do you  know the reason about the problem?

**Comment by buba447** [comment]
Ahhh The problem is that you are using Difference Masks, which arent supported. Though I looked at your file and you can achieve the same effect using regular Add Masks, which are supported.

@kule123
