### ISSUE TITLE
"contentsOf" async is super-oddball

### ISSUE THREAD

**Issue by smhk** [airbnb/lottie-ios#427]
Friends, everyone absolutely loves Lottie but

**LOTAnimationView(contentsOf: u)**

wth?  if it is async, it has to have a completion, like

**LOTAnimationView(contentsOf: u) {
}**

I don't even know how to use an aysnc call that, uh ... well it's not an async call  :)

(PS contentsOf: seems to, anyway, definitely not work in X9/S4 unfortunately)

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC

**Comment by smhk** [comment]
Brandon, thanks for letting us know this on a per-issue basis. 

Cheers  - thanks!
