### ISSUE TITLE
Carthage build fails

### ISSUE THREAD

**Issue by Ashok28** [airbnb/lottie-ios#433]
Latest Lottie version fails to build with Carthage.

## This issue is a
- [x] Regression (Something that once worked doesnt work anymore)

## What Platform are you on? 
- [x] MacOS Sierra 

## Expected Behavior 
It should compile

## Actual Behavior
It's not compiling

```
*** Building scheme "Lottie" in Lottie.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/ashokuradnicek/Desktop/Angee\ Labs/Carthage/Checkouts/lottie-ios/Lottie.xcodeproj -scheme Lottie -configuration Release -derivedDataPath /Users/ashokuradnicek/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/lottie-ios/2.1.3 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/ashokuradnicek/Desktop/Angee Labs/Carthage/Checkouts/lottie-ios)
```

Here's xcodebuild log:
```
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/ashokuradnicek/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/lottie-ios/2.1.3/Build/Intermediates.noindex/Lottie.build/Release-iphoneos/Lottie_iOS.build/Objects-normal/armv7/LOTAnimationView.o lottie-ios/Classes/Private/LOTAnimationView.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

```

**Comment by abiaad** [comment]
Same for me here

**Comment by tomfrew** [comment]
Had the same issue. Deleting the Carthage folder and the Cartfile.resolved file and re running `carthage update` fixed it for me

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
