### ISSUE TITLE
Dismiss View Controller Transition Broken through Segues

### ISSUE THREAD

**Issue by jlg5379** [airbnb/lottie-ios#434]
## Lottie-ios Issue
When I transition from screenA to screenB, then dismiss screenB with custom Lottie animation, screenA is removed from the stack.  This issue only happens when I present screenB through a segue.  Everything works as expected when I present screenB programatically.   

## This issue is a
Crashing Bug

## What Platform are you on? 
iOS 11 
Xcode 9

## Actual Behavior
![screen shot 2017-09-28 at 11 14 54 am](https://user-images.githubusercontent.com/15957846/30974710-4844340a-a43e-11e7-8d45-714967bd67ec.png)

## Code Example
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        switch segue.identifier! {
        case "segueA":
            let secondVC = segue.destination as! AViewController
            secondVC.transitioningDelegate = self
            secondVC.modalPresentationStyle = .custom
        case "segueB":
            let secondVC = segue.destination as! BViewController
            secondVC.transitioningDelegate = self
            secondVC.modalPresentationStyle = .custom
        default:
            print("Default")
        }
    }

    func animationController(forDismissed dismissed: UIViewController) -> UIViewControllerAnimatedTransitioning? {
        let animationController = LOTAnimationTransitionController(animationNamed: "vcTransition1", fromLayerNamed: "outLayer", toLayerNamed: "inLayer", applyAnimationTransform: false)
        return animationController
    }

    func animationController(forPresented presented: UIViewController, presenting: UIViewController, source: UIViewController) -> UIViewControllerAnimatedTransitioning? {
        let animationController = LOTAnimationTransitionController(animationNamed: "vcTransition1", fromLayerNamed: "outLayer", toLayerNamed: "inLayer", applyAnimationTransform: false)
        return animationController
    }

## Animation JSON
{"assets":[],"layers":[{"ddd":0,"ind":0,"ty":4,"nm":"inLayer","ks":{"o":{"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":61,"s":[0],"e":[100]},{"t":65}]},"r":{"k":0},"p":{"k":[207,368,0]},"a":{"k":[0,0,0]},"s":{"k":[{"i":{"x":[0.667,0.667,0.667],"y":[1,1,0.667]},"o":{"x":[0.333,0.333,0.333],"y":[0,0,0.333]},"n":["0p667_1_0p333_0","0p667_1_0p333_0","0p667_0p667_0p333_0p333"],"t":60,"s":[35,35,100],"e":[28,28,100]},{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.333,0.333,0.333],"y":[0,0,0.333]},"n":["0p833_0p833_0p333_0","0p833_0p833_0p333_0","0p833_0p833_0p333_0p333"],"t":63,"s":[28,28,100],"e":[1058.547,1058.547,100]},{"t":72}]}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ks":{"k":{"i":[[-28.96,0],[0,-28.96],[28.96,0],[0,28.96]],"o":[[28.96,0],[0,28.96],[-28.96,0],[0,-28.96]],"v":[[0,-52.438],[52.438,0],[0,52.438],[-52.438,0]],"c":true}},"nm":"Path 1","mn":"ADBE Vector Shape - Group"},{"ty":"fl","fillEnabled":true,"c":{"k":[0.9,0,0,1]},"o":{"k":100},"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill"},{"ty":"tr","p":{"k":[0,0],"ix":2},"a":{"k":[0,0],"ix":1},"s":{"k":[100,100],"ix":3},"r":{"k":0,"ix":6},"o":{"k":100,"ix":7},"sk":{"k":0,"ix":4},"sa":{"k":0,"ix":5},"nm":"Transform"}],"nm":"Ellipse 1","np":2,"mn":"ADBE Vector Group"}],"ip":60,"op":73,"st":19,"bm":0,"sr":1},{"ddd":0,"ind":1,"ty":4,"nm":"outLayer 4","ks":{"o":{"k":100},"r":{"k":0},"p":{"k":[207,368,0]},"a":{"k":[0,0,0]},"s":{"k":[{"i":{"x":[0.667,0.667,0.667],"y":[1,1,0.667]},"o":{"x":[0.333,0.333,0.333],"y":[0,0,0.333]},"n":["0p667_1_0p333_0","0p667_1_0p333_0","0p667_0p667_0p333_0p333"],"t":60,"s":[35,35,100],"e":[28,28,100]},{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.333,0.333,0.333],"y":[0,0,0.333]},"n":["0p833_0p833_0p333_0","0p833_0p833_0p333_0","0p833_0p833_0p333_0p333"],"t":63,"s":[28,28,100],"e":[1058.547,1058.547,100]},{"t":72}]}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ks":{"k":[{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"n":"0p667_1_0p333_0","t":46,"s":[{"i":[[28.309,8.688],[0,-28.96],[28.96,0],[0,28.96]],"o":[[28.96,0],[0,28.96],[27.941,-12.364],[0,-28.96]],"v":[[0,-52.438],[52.438,0],[0,52.438],[46.827,0]],"c":true}],"e":[{"i":[[-28.96,0],[0,-28.96],[28.96,0],[0,28.96]],"o":[[28.96,0],[0,28.96],[-28.96,0],[0,-28.96]],"v":[[0,-52.438],[52.438,0],[0,52.438],[-52.438,0]],"c":true}]},{"t":51}]},"nm":"Path 1","mn":"ADBE Vector Shape - Group"},{"ty":"fl","fillEnabled":true,"c":{"k":[0.9,0.9,0.9,1]},"o":{"k":100},"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill"},{"ty":"tr","p":{"k":[0,0],"ix":2},"a":{"k":[0,0],"ix":1},"s":{"k":[100,100],"ix":3},"r":{"k":0,"ix":6},"o":{"k":100,"ix":7},"sk":{"k":0,"ix":4},"sa":{"k":0,"ix":5},"nm":"Transform"}],"nm":"Ellipse 1","np":2,"mn":"ADBE Vector Group"}],"ip":46,"op":73,"st":19,"bm":0,"sr":1},{"ddd":0,"ind":2,"ty":4,"nm":"outLayer 7","ks":{"o":{"k":100},"r":{"k":0},"p":{"k":[207,368,0]},"a":{"k":[0,0,0]},"s":{"k":[35,35,100]}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ks":{"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.333,"y":0},"n":"0p833_0p833_0p333_0","t":44,"s":[{"i":[[25.735,6.482],[0,-28.96],[28.96,0],[0,28.96]],"o":[[28.96,0],[0,28.96],[27.574,-6.849],[0,-28.96]],"v":[[0,-52.438],[52.438,0],[0,52.438],[49.033,0]],"c":true}],"e":[{"i":[[-3.716,2.992],[0,-28.96],[-2.867,-4.084],[0,28.96]],"o":[[0.697,3.292],[0,28.96],[-2.868,-3.161],[0,-28.96]],"v":[[0,-52.438],[11.063,0],[0,52.438],[-12.958,0]],"c":true}]},{"i":{"x":0.667,"y":1},"o":{"x":0.167,"y":0.167},"n":"0p667_1_0p167_0p167","t":47,"s":[{"i":[[-3.716,2.992],[0,-28.96],[-2.867,-4.084],[0,28.96]],"o":[[0.697,3.292],[0,28.96],[-2.868,-3.161],[0,-28.96]],"v":[[0,-52.438],[11.063,0],[0,52.438],[-12.958,0]],"c":true}],"e":[{"i":[[-28.96,0],[0,-28.96],[-30.147,-7.585],[0,28.96]],"o":[[-23.529,6.114],[0,28.96],[-28.96,0],[0,-28.96]],"v":[[0,-52.438],[-48.298,0],[0,52.438],[-52.438,0]],"c":true}]},{"t":50}]},"nm":"Path 1","mn":"ADBE Vector Shape - Group"},{"ty":"fl","fillEnabled":true,"c":{"k":[0.89,0.89,0.89,1]},"o":{"k":100},"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill"},{"ty":"tr","p":{"k":[0,0],"ix":2},"a":{"k":[0,0],"ix":1},"s":{"k":[100,100],"ix":3},"r":{"k":0,"ix":6},"o":{"k":100,"ix":7},"sk":{"k":0,"ix":4},"sa":{"k":0,"ix":5},"nm":"Transform"}],"nm":"Ellipse 1","np":2,"mn":"ADBE Vector Group"}],"ip":44,"op":51,"st":27,"bm":0,"sr":1},{"ddd":0,"ind":3,"ty":4,"nm":"outLayer 6","ks":{"o":{"k":100},"r":{"k":0},"p":{"k":[207,368,0]},"a":{"k":[0,0,0]},"s":{"k":[35,35,100]}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ks":{"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.333,"y":0},"n":"0p833_0p833_0p333_0","t":42,"s":[{"i":[[25.735,6.482],[0,-28.96],[28.96,0],[0,28.96]],"o":[[28.96,0],[0,28.96],[27.574,-6.849],[0,-28.96]],"v":[[0,-52.438],[52.438,0],[0,52.438],[49.033,0]],"c":true}],"e":[{"i":[[-3.716,2.992],[0,-28.96],[-2.867,-4.084],[0,28.96]],"o":[[0.697,3.292],[0,28.96],[-2.868,-3.161],[0,-28.96]],"v":[[0,-52.438],[11.063,0],[0,52.438],[-12.958,0]],"c":true}]},{"i":{"x":0.667,"y":1},"o":{"x":0.167,"y":0.167},"n":"0p667_1_0p167_0p167","t":45,"s":[{"i":[[-3.716,2.992],[0,-28.96],[-2.867,-4.084],[0,28.96]],"o":[[0.697,3.292],[0,28.96],[-2.868,-3.161],[0,-28.96]],"v":[[0,-52.438],[11.063,0],[0,52.438],[-12.958,0]],"c":true}],"e":[{"i":[[-28.96,0],[0,-28.96],[-30.147,-7.585],[0,28.96]],"o":[[-23.529,6.114],[0,28.96],[-28.96,0],[0,-28.96]],"v":[[0,-52.438],[-48.298,0],[0,52.438],[-52.438,0]],"c":true}]},{"t":48}]},"nm":"Path 1","mn":"ADBE Vector Shape - Group"},{"ty":"fl","fillEnabled":true,"c":{"k":[0.89,0.89,0.89,1]},"o":{"k":100},"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill"},{"ty":"tr","p":{"k":[0,0],"ix":2},"a":{"k":[0,0],"ix":1},"s":{"k":[100,100],"ix":3},"r":{"k":0,"ix":6},"o":{"k":100,"ix":7},"sk":{"k":0,"ix":4},"sa":{"k":0,"ix":5},"nm":"Transform"}],"nm":"Ellipse 1","np":2,"mn":"ADBE Vector Group"}],"ip":42,"op":49,"st":25,"bm":0,"sr":1},{"ddd":0,"ind":4,"ty":4,"nm":"outLayer 5","ks":{"o":{"k":100},"r":{"k":0},"p":{"k":[207,368,0]},"a":{"k":[0,0,0]},"s":{"k":[35,35,100]}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ks":{"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.333,"y":0},"n":"0p833_0p833_0p333_0","t":40,"s":[{"i":[[25.735,6.482],[0,-28.96],[28.96,0],[0,28.96]],"o":[[28.96,0],[0,28.96],[27.574,-6.849],[0,-28.96]],"v":[[0,-52.438],[52.438,0],[0,52.438],[49.033,0]],"c":true}],"e":[{"i":[[-3.716,2.992],[0,-28.96],[-2.867,-4.084],[0,28.96]],"o":[[0.697,3.292],[0,28.96],[-2.868,-3.161],[0,-28.96]],"v":[[0,-52.438],[11.063,0],[0,52.438],[-12.958,0]],"c":true}]},{"i":{"x":0.667,"y":1},"o":{"x":0.167,"y":0.167},"n":"0p667_1_0p167_0p167","t":43,"s":[{"i":[[-3.716,2.992],[0,-28.96],[-2.867,-4.084],[0,28.96]],"o":[[0.697,3.292],[0,28.96],[-2.868,-3.161],[0,-28.96]],"v":[[0,-52.438],[11.063,0],[0,52.438],[-12.958,0]],"c":true}],"e":[{"i":[[-28.96,0],[0,-28.96],[-30.147,-7.585],[0,28.96]],"o":[[-23.529,6.114],[0,28.96],[-28.96,0],[0,-28.96]],"v":[[0,-52.438],[-48.298,0],[0,52.438],[-52.438,0]],"c":true}]},{"t":46}]},"nm":"Path 1","mn":"ADBE Vector Shape - Group"},{"ty":"fl","fillEnabled":true,"c":{"k":[0.89,0.89,0.89,1]},"o":{"k":100},"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill"},{"ty":"tr","p":{"k":[0,0],"ix":2},"a":{"k":[0,0],"ix":1},"s":{"k":[100,100],"ix":3},"r":{"k":0,"ix":6},"o":{"k":100,"ix":7},"sk":{"k":0,"ix":4},"sa":{"k":0,"ix":5},"nm":"Transform"}],"nm":"Ellipse 1","np":2,"mn":"ADBE Vector Group"}],"ip":40,"op":47,"st":23,"bm":0,"sr":1},{"ddd":0,"ind":5,"ty":4,"nm":"outLayer 3","ks":{"o":{"k":100},"r":{"k":0},"p":{"k":[207,368,0]},"a":{"k":[0,0,0]},"s":{"k":[35,35,100]}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ks":{"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.333,"y":0},"n":"0p833_0p833_0p333_0","t":36,"s":[{"i":[[25.735,6.482],[0,-28.96],[28.96,0],[0,28.96]],"o":[[28.96,0],[0,28.96],[27.574,-6.849],[0,-28.96]],"v":[[0,-52.438],[52.438,0],[0,52.438],[49.033,0]],"c":true}],"e":[{"i":[[-3.716,2.992],[0,-28.96],[-2.867,-4.084],[0,28.96]],"o":[[0.697,3.292],[0,28.96],[-2.868,-3.161],[0,-28.96]],"v":[[0,-52.438],[11.063,0],[0,52.438],[-12.958,0]],"c":true}]},{"i":{"x":0.667,"y":1},"o":{"x":0.167,"y":0.167},"n":"0p667_1_0p167_0p167","t":39,"s":[{"i":[[-3.716,2.992],[0,-28.96],[-2.867,-4.084],[0,28.96]],"o":[[0.697,3.292],[0,28.96],[-2.868,-3.161],[0,-28.96]],"v":[[0,-52.438],[11.063,0],[0,52.438],[-12.958,0]],"c":true}],"e":[{"i":[[-28.96,0],[0,-28.96],[-30.147,-7.585],[0,28.96]],"o":[[-23.529,6.114],[0,28.96],[-28.96,0],[0,-28.96]],"v":[[0,-52.438],[-48.298,0],[0,52.438],[-52.438,0]],"c":true}]},{"t":42}]},"nm":"Path 1","mn":"ADBE Vector Shape - Group"},{"ty":"fl","fillEnabled":true,"c":{"k":[0.89,0.89,0.89,1]},"o":{"k":100},"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill"},{"ty":"tr","p":{"k":[0,0],"ix":2},"a":{"k":[0,0],"ix":1},"s":{"k":[100,100],"ix":3},"r":{"k":0,"ix":6},"o":{"k":100,"ix":7},"sk":{"k":0,"ix":4},"sa":{"k":0,"ix":5},"nm":"Transform"}],"nm":"Ellipse 1","np":2,"mn":"ADBE Vector Group"}],"ip":36,"op":43,"st":19,"bm":0,"sr":1},{"ddd":0,"ind":6,"ty":4,"nm":"outLayer 2","ks":{"o":{"k":100},"r":{"k":0},"p":{"k":[207,368,0]},"a":{"k":[0,0,0]},"s":{"k":[{"i":{"x":[0.667,0.667,0.667],"y":[1,1,0.667]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"n":["0p667_1_0p167_0p167","0p667_1_0p167_0p167","0p667_0p667_0p167_0p167"],"t":13,"s":[4.648,4.648,100],"e":[52.648,52.648,100]},{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.333,0.333,0.333],"y":[0,0,0.333]},"n":["0p833_0p833_0p333_0","0p833_0p833_0p333_0","0p833_0p833_0p333_0p333"],"t":15,"s":[52.648,52.648,100],"e":[19.648,19.648,100]},{"i":{"x":[0.667,0.667,0.667],"y":[1,1,0.667]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"n":["0p667_1_0p167_0p167","0p667_1_0p167_0p167","0p667_0p667_0p167_0p167"],"t":20,"s":[19.648,19.648,100],"e":[39.648,39.648,100]},{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.333,0.333,0.333],"y":[0,0,0.333]},"n":["0p833_0p833_0p333_0","0p833_0p833_0p333_0","0p833_0p833_0p333_0p333"],"t":25,"s":[39.648,39.648,100],"e":[34,34,100]},{"t":32}]}},"ao":0,"shapes":[{"ty":"gr","it":[{"d":1,"ty":"el","s":{"k":[104.875,104.875]},"p":{"k":[0,0]},"nm":"Ellipse Path 1","mn":"ADBE Vector Shape - Ellipse"},{"ty":"fl","fillEnabled":true,"c":{"k":[0.16,0.16,0.16,1]},"o":{"k":100},"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill"},{"ty":"tr","p":{"k":[0,0],"ix":2},"a":{"k":[0,0],"ix":1},"s":{"k":[100,100],"ix":3},"r":{"k":0,"ix":6},"o":{"k":100,"ix":7},"sk":{"k":0,"ix":4},"sa":{"k":0,"ix":5},"nm":"Transform"}],"nm":"Ellipse 1","np":2,"mn":"ADBE Vector Group"}],"ip":13,"op":51,"st":0,"bm":0,"sr":1},{"ddd":0,"ind":7,"ty":4,"nm":"outLayer","ks":{"o":{"k":100},"r":{"k":0},"p":{"k":[207,368,0]},"a":{"k":[0,0,0]},"s":{"k":[{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"n":["0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167"],"t":0,"s":[1175.566,1175.566,100],"e":[4.648,4.648,100]},{"t":13}]}},"ao":0,"shapes":[{"ty":"gr","it":[{"d":1,"ty":"el","s":{"k":[104.875,104.875]},"p":{"k":[0,0]},"nm":"Ellipse Path 1","mn":"ADBE Vector Shape - Ellipse"},{"ty":"fl","fillEnabled":true,"c":{"k":[1,0,0,1]},"o":{"k":100},"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill"},{"ty":"tr","p":{"k":[0,0],"ix":2},"a":{"k":[0,0],"ix":1},"s":{"k":[100,100],"ix":3},"r":{"k":0,"ix":6},"o":{"k":100,"ix":7},"sk":{"k":0,"ix":4},"sa":{"k":0,"ix":5},"nm":"Transform"}],"nm":"Ellipse 1","np":2,"mn":"ADBE Vector Group"}],"ip":0,"op":13,"st":0,"bm":0,"sr":1},{"ddd":0,"ind":8,"ty":4,"nm":"outLayer 9","ks":{"o":{"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":58,"s":[100],"e":[0]},{"t":62}]},"r":{"k":0},"p":{"k":[207,368,0]},"a":{"k":[0,0,0]},"s":{"k":[{"i":{"x":[0.569,0.569,0.569],"y":[0.707,0.707,0.569]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"n":["0p569_0p707_0p167_0p167","0p569_0p707_0p167_0p167","0p569_0p569_0p167_0p167"],"t":53,"s":[20,20,100],"e":[64,64,100]},{"i":{"x":[0.703,0.703,0.703],"y":[1,1,0.703]},"o":{"x":[0.317,0.317,0.317],"y":[1.009,1.009,0.317]},"n":["0p703_1_0p317_1p009","0p703_1_0p317_1p009","0p703_0p703_0p317_0p317"],"t":56,"s":[64,64,100],"e":[89,89,100]},{"t":64}]}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ks":{"k":{"i":[[-28.96,0],[0,-28.96],[28.96,0],[0,28.96]],"o":[[28.96,0],[0,28.96],[-28.96,0],[0,-28.96]],"v":[[0,-52.438],[52.438,0],[0,52.438],[-52.438,0]],"c":true}},"nm":"Path 1","mn":"ADBE Vector Shape - Group"},{"ty":"st","fillEnabled":true,"c":{"k":[1,1,1,1]},"o":{"k":100},"w":{"k":1},"lc":1,"lj":1,"ml":4,"d":[{"n":"d","nm":"dash","v":{"k":4}},{"n":"o","nm":"offset","v":{"k":0}}],"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke"},{"ty":"tr","p":{"k":[0,0],"ix":2},"a":{"k":[0,0],"ix":1},"s":{"k":[153,153],"ix":3},"r":{"k":0,"ix":6},"o":{"k":100,"ix":7},"sk":{"k":0,"ix":4},"sa":{"k":0,"ix":5},"nm":"Transform"}],"nm":"Ellipse 1","np":2,"mn":"ADBE Vector Group"}],"ip":49,"op":76,"st":22,"bm":0,"sr":1},{"ddd":0,"ind":9,"ty":4,"nm":"outLayer 8","ks":{"o":{"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":54,"s":[100],"e":[0]},{"t":58}]},"r":{"k":0},"p":{"k":[207,368,0]},"a":{"k":[0,0,0]},"s":{"k":[{"i":{"x":[0.569,0.569,0.569],"y":[0.707,0.707,0.569]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"n":["0p569_0p707_0p167_0p167","0p569_0p707_0p167_0p167","0p569_0p569_0p167_0p167"],"t":49,"s":[20,20,100],"e":[64,64,100]},{"i":{"x":[0.703,0.703,0.703],"y":[1,1,0.703]},"o":{"x":[0.317,0.317,0.317],"y":[1.009,1.009,0.317]},"n":["0p703_1_0p317_1p009","0p703_1_0p317_1p009","0p703_0p703_0p317_0p317"],"t":52,"s":[64,64,100],"e":[89,89,100]},{"t":60}]}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ks":{"k":{"i":[[-28.96,0],[0,-28.96],[28.96,0],[0,28.96]],"o":[[28.96,0],[0,28.96],[-28.96,0],[0,-28.96]],"v":[[0,-52.438],[52.438,0],[0,52.438],[-52.438,0]],"c":true}},"nm":"Path 1","mn":"ADBE Vector Shape - Group"},{"ty":"st","fillEnabled":true,"c":{"k":[1,1,1,1]},"o":{"k":100},"w":{"k":2},"lc":1,"lj":1,"ml":4,"d":[{"n":"d","nm":"dash","v":{"k":4}},{"n":"o","nm":"offset","v":{"k":0}}],"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke"},{"ty":"tr","p":{"k":[0,0],"ix":2},"a":{"k":[0,0],"ix":1},"s":{"k":[153,153],"ix":3},"r":{"k":0,"ix":6},"o":{"k":100,"ix":7},"sk":{"k":0,"ix":4},"sa":{"k":0,"ix":5},"nm":"Transform"}],"nm":"Ellipse 1","np":2,"mn":"ADBE Vector Group"}],"ip":47,"op":72,"st":18,"bm":0,"sr":1},{"ddd":0,"ind":10,"ty":4,"nm":"Background","ks":{"o":{"k":100},"r":{"k":0},"p":{"k":[207,368,0]},"a":{"k":[0,0,0]},"s":{"k":[100,100,100]}},"ao":0,"shapes":[{"ty":"gr","it":[{"ty":"rc","d":1,"s":{"k":[1042.203,1042.203]},"p":{"k":[0,0]},"r":{"k":0},"nm":"Rectangle Path 1","mn":"ADBE Vector Shape - Rect"},{"ty":"fl","fillEnabled":true,"c":{"k":[0,0.82,0.76,1]},"o":{"k":100},"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill"},{"ty":"tr","p":{"k":[0,0],"ix":2},"a":{"k":[0,0],"ix":1},"s":{"k":[100,100],"ix":3},"r":{"k":0,"ix":6},"o":{"k":100,"ix":7},"sk":{"k":0,"ix":4},"sa":{"k":0,"ix":5},"nm":"Transform"}],"nm":"Rectangle 1","np":2,"mn":"ADBE Vector Group"}],"ip":0,"op":77,"st":0,"bm":0,"sr":1}],"v":"4.5.0","ddd":0,"ip":0,"op":73,"fr":24,"w":414,"h":736}

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
