### ISSUE TITLE
Animation Not Found due to jsonData return nil

### ISSUE THREAD

**Issue by Kidreams** [airbnb/lottie-ios#436]
## Lottie-ios Issue
Hello! Sorry you are having an Issue! Please help us make Lottie better by filling everything below out with as much information as you can so we can try to reproduce and fix the issue!

## Check these before submitting:
- [x] Updated to the latest (2.1.3) version of Lottie
- [x] The issue doesnt involve and [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isnt related to another open issue

## This issue is a
- [x] Non-Crashing (Visual or otherwise) Bug
- [ ] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked doesnt work anymore)

## What Platform are you on? 
- [ ] MacOS (Specify Platform Version)
- [x] iOS (Specify Platform Version)

## Expected Behavior 
(Screenshots encouraged)

## Actual Behavior
(Screenshots encouraged)

## Animation JSON
Adding the animation JSON helps us debug the issue faster!

I'm using macOS version 10.12.6 (16G29) and xCode Version 9.0 (9A235), animation couldn't be load using

1.  drag and drop to add animation files (images and xxx.json) to xCode directly, but it works perfectly by

2. right click to add files to project.

I found this would cause jsonData returning nil at class **LOTComposition** at **Line 54** _NSData *jsonData = [[NSData alloc] initWithContentsOfFile:filePath]_ in **function** _+ (nullable instancetype)animationWithFilePath:(nonnull NSString *)filePath_ using method 1. to add files. This could probably be an xCode bug. I have tried a numbers of files and nothing gonna change, and 1. and 2. just works good by using xCode Version 8.3.3(8E3004b).

![screen shot 2017-09-29 at 3 18 10 pm](https://user-images.githubusercontent.com/6589417/31005260-88e2c2d2-a52a-11e7-99f1-ccb70a60ebef.png)

![screen shot 2017-09-29 at 3 40 42 pm](https://user-images.githubusercontent.com/6589417/31005754-a2f928f8-a52c-11e7-8204-33cdcc6b1b8b.png)

**Comment by buba447** [comment]
Whats the error read?

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
