### ISSUE TITLE
Animation JSON not loading on tvOS

### ISSUE THREAD

**Issue by fasteque** [airbnb/lottie-ios#437]
## Lottie-ios Issue
Hello! Sorry you are having an Issue! Please help us make Lottie better by filling everything below out with as much information as you can so we can try to reproduce and fix the issue!

## Check these before submitting:
- [x] Updated to the latest (2.1.3) version of Lottie
- [x] The issue doesnt involve and [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isnt related to another open issue

## This issue is a
- [x] Non-Crashing (Visual or otherwise) Bug
- [ ] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked doesnt work anymore)

## What Platform are you on? 
- [ ] MacOS (Specify Platform Version)
- [x] iOS (Specify Platform Version) **> actually tvOS**

## Expected Behavior 
Animation should be displayed on the screen.

## Actual Behavior
Nothing is shown on the screen of the tvOS simulator. If I use other animations (i.e. https://github.com/airbnb/lottie-android/raw/master/LottieSample/src/main/assets/City.json), I'm able to see them.
Using the same JSON file on Android, the animation is displayed correctly.
Using the Lottie application on an iPhone 6s (iOS 11), the animation is displayed correctly.
I've tried to add the log flag but I don't get anything in the console (I'm just converting an Android application to tvOS, so I'm not an expert, maybe I'm doing something wrong).

## Code Example
        animationView = LOTAnimationView(contentsOf: URL(string: "http://www.fasteque.com/public/animation.json")!)
        animationView.frame = CGRect(x: 377, y: 247, width: 471, height: 437)
        animationView.contentMode = .scaleAspectFill
        view.addSubview(animationView)
        animationView.play()

## Animation JSON
http://www.fasteque.com/public/animation.json

**Comment by buba447** [comment]
Have you disabled App Transport Security?
Seems like the animation isnt downloading correctly. I noticed the address is not secured. Might be the problem. 

https://gist.github.com/mlynch/284699d676fe9ed0abfa

**Comment by fasteque** [comment]
That was the issue, thanks a lot and sorry for the noise, it's just my second day on iOS so I haven't thought about this possible reason. Anyway I've learned something new and maybe someone with the same issue will find this to be helpful as well.
