### ISSUE TITLE
Animation is incorrect while Android is correct.

### ISSUE THREAD

**Issue by csnu17** [airbnb/lottie-ios#438]
I use Lottie iOS 2.1.3 and found the animation is different from Android. The below is useful information.

Device:
iPhone 6 iOS 11.0.2

Expected:
<img width="318" alt="expected" src="https://user-images.githubusercontent.com/15520417/31163073-d59aad72-a90a-11e7-8c89-043f60c64b5e.png">

Actual:
<img width="164" alt="actual" src="https://user-images.githubusercontent.com/15520417/31163083-e0f7ae22-a90a-11e7-9b18-ac62d16e7569.png">

JSON file:
[json](https://goo.gl/26FbU3)

Thank you,
Kittisak

**Comment by therealsalih** [comment]
Can you attach the .AEP file?

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
