### ISSUE TITLE
Issue with curved animation path

### ISSUE THREAD

**Issue by alex-van-zijl** [airbnb/lottie-ios#439]
Hi guys, I'm having an issue where there's a curve in my animation path, but the render in lottie doesn't conceder these.
Is this unsupported?

Here's my expected animation:
<img width="401" alt="screen shot 2017-10-05 at 11 40 11" src="https://user-images.githubusercontent.com/16916321/31236406-0302c710-a9c2-11e7-9658-59054fda32f1.png">

The red line is what's actually showing up on my iPhone:
<img width="401" alt="screen shot 2017-10-05 at 11 40 11" src="https://user-images.githubusercontent.com/16916321/31236483-30ce6eec-a9c2-11e7-990e-c9cc3837b92a.png">

Thanks in advance.

**Comment by spearmootz** [comment]
i am seeing this behavior also

**Comment by buba447** [comment]
Strange! Cant I see the JSON file?

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
