### ISSUE TITLE
I would like to ask what Lottie is the tool used to do animation

### ISSUE THREAD

**Issue by LabelChuang** [airbnb/lottie-ios#44]

**Comment by ljharb** [comment]
Do you mean After Effects, which is mentioned in the readme?

**Comment by LabelChuang** [comment]
No ，Lottie read the Jason file, so I need to use animation software to create an animation and convert it to Jason file，  Sorry my English is poor

**Comment by ljharb** [comment]
Right - Adobe After Effects is that animation software, as described in the readme.

**Comment by LabelChuang** [comment]
Thank you very much.
