### ISSUE TITLE
I'm having an issue with json file exported from bodimovin. Mask is not working in json while its working fine in html. How can i get a solution for this?

### ISSUE THREAD

**Issue by anjanamta** [airbnb/lottie-ios#440]
## Lottie-ios Issue
Hello! Sorry you are having an Issue! Please help us make Lottie better by filling everything below out with as much information as you can so we can try to reproduce and fix the issue!

## Check these before submitting:
- [x] Updated to the latest (2.1.3) version of Lottie
- [ ] The issue doesnt involve and [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [ ] This issue isnt related to another open issue

## This issue is a
- [x] Non-Crashing (Visual or otherwise) Bug
- [ ] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked doesnt work anymore)

## What Platform are you on? 
- [ ] MacOS (Specify Platform Version)
- [x] iOS (Specify Platform Version)

## Expected Behavior 
(Screenshots encouraged)

## Actual Behavior
(Screenshots encouraged)

## Animation JSON
Adding the animation JSON helps us debug the issue faster!

**Comment by buba447** [comment]
If you attach the json file or after effects file I can help you.

**Comment by anjanamta** [comment]
Hello,

Thank you for your quick reply. Its a logo which is not publicly released
yet. It was our client work, they want to ensure this is not going to
available publicly.

Hope this will be fine for you.

Looking forward your reply,

Anjana.M

**Comment by devildog** [comment]
We are having the same issue. Attached is JSON file.
[data.json.zip](https://github.com/airbnb/lottie-ios/files/1408757/data.json.zip)

**Comment by buba447** [comment]
Currently we only support Add and Subtract masks. If you are having an issue please make sure you arent using a difference or intersect mask

**Comment by anjanamta** [comment]
Hi,
Please find the attached after effects file and json file and please let me
know what is the issue.​​​​​​ Please see the demo.html for what we expected.
​
 data.json
<https://drive.google.com/a/teamta.in/file/d/0B7pMVg69F_nlMkUzaWpNWG80ZlE/view?usp=drive_web>
​​
 demo.html
<https://drive.google.com/a/teamta.in/file/d/0B7pMVg69F_nlQ2VFNXY1czQ0ZDg/view?usp=drive_web>
​​
 logo.aep
<https://drive.google.com/a/teamta.in/file/d/0B7pMVg69F_nlRENwNDdCVF90VUU/view?usp=drive_web>
​

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by buba447** [comment]
From what I can tell I think its because you have imported some Illustrator files but havent converted them properly for Lottie. 
If you select a layer that was imported from an illustrator file you can right click on it and select 'Create Shapes from Vector Layer'

More info and tutorials can be found here: http://airbnb.io/lottie/after-effects/artwork-to-lottie-walkthrough.html

**Comment by anjanamta** [comment]
Sorry for the inconvenience. I have tried this already, but it was not
working.
