### ISSUE TITLE
LOTAnimationView build failures with 2.1.3

### ISSUE THREAD

**Issue by mitch104** [airbnb/lottie-ios#441]
## Lottie-ios Issue
I am having the same issue as https://github.com/airbnb/lottie-react-native/issues/204, which was raised on `lottie-react-native` however I believe the issue originates from `lottie-ios`.

After upgrading from lottie-react-native `1.1.1` to `2.2.7`, which in turn upgraded lottie-ios to `2.1.3` then I am unable to build with the following errors:

`1. Property 'sceneModel' not found on object of type 'LOTAnimationView *'`
`2. No visible @interface for 'LOTAnimationView' declares the selector 'setSceneModel:'`

Also just upgraded to RN 49.0

## Check these before submitting:
- [X] Updated to the latest (2.1.3) version of Lottie
- [X] The issue doesnt involve and [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [X] This issue isnt related to another open issue

## This issue is a
- [ ] Non-Crashing (Visual or otherwise) Bug
- [X] Crashing Bug
- [ ] Feature Request
- [X] Regression (Something that once worked doesnt work anymore)

## What Platform are you on? 
- [ ] MacOS
- [X] iOS (10.3.3)

## Expected Behavior 
To build without errors

## Actual Behavior
<img width="252" alt="lottie_ios_screenshot" src="https://user-images.githubusercontent.com/9034588/31273940-c08366fc-aa88-11e7-952a-4a6a644741fe.png">

**Comment by basequatro** [comment]
Same here

**Comment by spearmootz** [comment]
+1 same here

**Comment by mitch104** [comment]
@basequatro @spearmootz Following these instructions solved the issue for me https://github.com/airbnb/lottie-react-native/issues/204#issuecomment-335425504
