### ISSUE TITLE
Blend Mode support

### ISSUE THREAD

**Issue by pierreliefauche** [airbnb/lottie-ios#443]
Is support for blend modes on the roadmap or not at all?
If it's not, do you guys have a rough idea of how to do it? Or at least apply a blend mode on the whole animation's `CGContext`?

I fooled around with the code but couldn’t figure it out. 
Limited Core Animation on iOS is making this utterly complicated.

Thanks!

**Comment by buba447** [comment]
I have not been able to find a way to do it.
We dont have it on the roadmap either :(

**Comment by pierreliefauche** [comment]
Thanks, good to know 👍
