### ISSUE TITLE
LOTAnimationView doesn't appear in UICollectionViewCell

### ISSUE THREAD

**Issue by Erderg** [airbnb/lottie-ios#444]
Hi,

I was trying to add LOTAnimationView to my collection view cell, but nothing appears in cells when I run the program. I can add the animation to a normal view just fine, but when I'm trying to add it to UICollectionViewCell nothing happens. Here is my code:

```
import UIKit
import Lottie

class Cell: UICollectionViewCell{
    
    var animationView: LOTAnimationView!
    
    
    override func awakeFromNib() {
        super .awakeFromNib()
        
        animationView = LOTAnimationView(name: "button_press")
        animationView.contentMode = .scaleAspectFit
        self.contentView.addSubview(animationView!)
        animationView.centerXAnchor.constraint(equalTo: self.contentView.centerXAnchor)
        animationView.centerYAnchor.constraint(equalTo: self.contentView.centerYAnchor)
        
    }
    
    
}// class
```

**Comment by adenisonafifi** [comment]
Have you attempted to use the view debugger to see if the `LOTAnimationView` properly exists in the `UICollectionViewCell` and has the expected frame?

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
