### ISSUE TITLE
How to update to 2.0 / 1.5 is always installed via CocoaPods?

### ISSUE THREAD

**Issue by ghost** [airbnb/lottie-ios#445]
## Lottie-ios Issue
Hello! Sorry you are having an Issue! Please help us make Lottie better by filling everything below out with as much information as you can so we can try to reproduce and fix the issue!

## Check these before submitting:
- [ ] Updated to the latest (2.1.3) version of Lottie
- [ ] The issue doesnt involve and [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isnt related to another open issue

## This issue is a
- [ ] Non-Crashing (Visual or otherwise) Bug
- [x] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked doesnt work anymore)

## What Platform are you on? 
- [ ] MacOS (Specify Platform Version)
- [x] iOS (Specify Platform Version)

## Actual Behavior
When installing via CocoaPods version 1.5 is installed which produced Nullability errors which should be resolved in version 2 as far as I understand, but I am not able to update to version 2 or installed version 2 in the first place.

I am not sure how much this is of an issue, but again I am getting about two dozen nullability / non null errors and I am not able to get version 2 of Lottie.

**Comment by buba447** [comment]
Check that your .podfile doesnt have the version set to 1.5.
If you open your podfile and see

`pod 'lottie-ios' , '~> 1.5'`
 
remove the last bit so it says:

`pod 'lottie-ios'`

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
