### ISSUE TITLE
Why isn't my animation playing? It just goes straight to the last frame.

### ISSUE THREAD

**Issue by nicholasdmoore** [airbnb/lottie-ios#446]
[Educal.xcworkspace.zip](https://github.com/airbnb/lottie-ios/files/1384840/Educal.xcworkspace.zip)
## Lottie-ios Issue
Hello! Sorry you are having an Issue! Please help us make Lottie better by filling everything below out with as much information as you can so we can try to reproduce and fix the issue!

## Check these before submitting:
- [yes ] Updated to the latest (2.1.3) version of Lottie
- [yes ] The issue doesnt involve and [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [no ] This issue isnt related to another open issue

## This issue is a
- [yes ] Non-Crashing (Visual or otherwise) Bug
- [ no] Crashing Bug
- [ ] Feature Request
- [no ] Regression (Something that once worked doesnt work anymore)

## What Platform are you on? 
- [ working in Xcode] MacOS (Specify Platform Version)
- [yes ] iOS (Specify Platform Version)

## Expected Behavior 
(Screenshots encouraged)

## Actual Behavior
(

## Animation JSON
Adding the animation JSON helps us debug the issue faster!

**Comment by buba447** [comment]
Hmmm your ZIP file only has a blank workspace in it. Without code or json example I cant really help you!
