### ISSUE TITLE
Lottie Images Not Correctly Showing

### ISSUE THREAD

**Issue by tomxue123** [airbnb/lottie-ios#448]
## Check these before submitting:
- [ ] Updated to the latest (2.1.3) version of Lottie

## This issue is a
 Non-Crashing (Visual or otherwise) Bug

## What Platform are you on? 
-  iOS 11

There are 5 images attached to my json file (converted with bodymovin). But those 5 images are not showing when I use the animation.
[playbutton.json.zip](https://github.com/airbnb/lottie-ios/files/1386398/playbutton.json.zip)

Here's the code I used in Xcode:
       let animationView = LOTAnimationView(name: "playbutton")
        animationView.frame = CGRect(x: 0, y: 100, width: self.view.frame.size.width, height: 250)
        animationView.contentMode = .scaleAspectFill
        self.view.addSubview(animationView)
        animationView.loopAnimation = true
        animationView.play()

I guess my question is, how do images work in Lottie and are the images included inside the json file or you have to add them to your iOS project, if so, how?

**Comment by buba447** [comment]
You have to add them to your main bundle in your iOS Project. The easiest way to do this is to drag and drop them into your Project Navigator.

http://www.idev101.com/learn/adding_images.html

**Comment by Cosmin1907** [comment]
I ran the attached JSON through a Lottie diagnostic tool I’m building and found a bit more than just the missing image files.
Preliminary findings:
- it expects 6 external images (images/img_0.png → img_5.png)
- those images aren’t embedded in the file
- 6 asset entries are missing IDs
- 9 layers reference asset IDs that aren’t defined
So adding the images to the iOS bundle may solve part of it, but the JSON also appears to have broken asset references.
If anyone still has the original images, I can test whether restoring them is enough or whether the asset mapping also needs repair.

https://lottiefyr.com/lottie-fix
