### ISSUE TITLE
Animation blinks while looping

### ISSUE THREAD

**Issue by Crunkz** [airbnb/lottie-ios#449]
Hello!

I am using latest version of Lottie (2.1.3).
Pretty little and simple animation, which I attached in _.zip package_ below, blinks only when **looping** is set to **true**.

I've been looking for the solution in another posts from _Issue_ section, but wasn't able to find a good one so far.

Could some kind person take a look at this?

#### Animation package (JSON + AfterEffects):
[logoAnimation.zip](https://github.com/airbnb/lottie-ios/files/1387274/logoAnimation.zip)

**Comment by buba447** [comment]
Looks like this is related to the trim path bugs. If you change the keyframes in the middle to be linear it might fix it.

**Comment by Crunkz** [comment]
Thank you for the answer!
I going to try to do that tomorrow.

**Comment by buba447** [comment]
Should be fixed with https://github.com/airbnb/lottie-ios/pull/468
