### ISSUE TITLE
How to clean assets cache?

### ISSUE THREAD

**Issue by xboy-im** [airbnb/lottie-ios#451]
## Lottie-ios Issue
Hello! Sorry you are having an Issue! Please help us make Lottie better by filling everything below out with as much information as you can so we can try to reproduce and fix the issue!

## Check these before submitting:
- [x] Updated to the latest (2.1.3) version of Lottie
- [ ] The issue doesnt involve and [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [ ] This issue isnt related to another open issue

## This issue is a
- [x] Non-Crashing (Visual or otherwise) Bug
- [ ] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked doesnt work anymore)

## What Platform are you on? 
- [ ] MacOS (Specify Platform Version)
- [x] iOS (Specify Platform Version)

## Code Example
I have two bundles, animationOne.bundle(one.json & img_0.png) and animationTwo.bundle(two.json & img_0.png). Lottie always load image from other bundle. How can I clean the cache after every animation?

**Comment by buba447** [comment]
The image isnt loaded from the cache, the cache only caches the pointer to the deserialized JSON. You will need to specify which bundle using the method
 `+ (nonnull instancetype)animationNamed:(nonnull NSString *)animationName inBundle:(nonnull NSBundle *)bundle NS_SWIFT_NAME(init(name:bundle:));`

You can clear the cache using `[[LOTAnimationChache sharedCache] clearCache]` though I dont anticipate it will fix your specific problem
