### ISSUE TITLE
LOTAnimationCache is not thread safe

### ISSUE THREAD

**Issue by scottmarchington** [airbnb/lottie-ios#453]
When caching LOTCompositions in a background thread, if you also attempt to cache an LOTComposition on the main thread, there's a chance a crash can occur.

The reason for doing this is because I'm using several fairly large animations (>100kb JSON each), in addition to smaller animations for UI elements.  Preloading the LOTAnimationViews for the larger animations in the background is worthwhile as it takes an extended amount of time to parse the JSON (~0.5 seconds total) into LOTComposition objects.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
