### ISSUE TITLE
[Proposed Enhancement] Could add a callback for animationProgress?

### ISSUE THREAD

**Issue by NemoAir** [airbnb/lottie-ios#455]
i want control the animation of backgroundColor through  timeOffset property，and to achieve backgroundColor keep the same pace with LOTAnimationView, or it had another approach?

**Comment by buba447** [comment]
Possible with the most recent update on master! Release 2.5 coming soon.

**Comment by buba447** [comment]
See http://airbnb.io/lottie/ios/dynamic.html
