### ISSUE TITLE
Crash at  LOTAnimatorNode

### ISSUE THREAD

**Issue by juxuechen** [airbnb/lottie-ios#456]
Lottie V2

Thread 2 Crashed:
0   libobjc.A.dylib                 0x00000001803a5474 _lookUpImpOrForward :164 (in libobjc.A.dylib)
1   libobjc.A.dylib                 0x00000001803b0478 _objc_msgSend_uncached :56 (in libobjc.A.dylib)
2   CoreFoundation                  0x000000018181e5ac -[__NSCFNumber isEqual:] :72 (in CoreFoundation)
3   xxx                   0x0000000101baa470 -[LOTAnimatorNode updateWithFrame:withModifierBlock:forceLocalUpdate:] LOTAnimatorNode.m:41 (in xxx)
4   xxx                   0x0000000101ba37d8 -[LOTRenderGroup updateWithFrame:withModifierBlock:forceLocalUpdate:] LOTRenderGroup.m:127 (in xxx)
5   xxx                   0x0000000101bac994 -[LOTLayerContainer displayWithFrame:] LOTLayerContainer.m:204 (in xxx)
6   xxx                   0x0000000101ba844c -[LOTCompositionContainer displayWithFrame:] LOTCompositionContainer.m:86 (in xxx)
7   xxx                   0x0000000101bac79c -[LOTLayerContainer display] LOTLayerContainer.m:184 (in xxx)
8   QuartzCore                      0x0000000184c4ec20 CA::Layer::display_if_needed(CA::Transaction*) :228 (in QuartzCore)
9   QuartzCore                      0x0000000184c4ecb4 CA::Layer::layout_and_display_if_needed(CA::Transaction*) :44 (in QuartzCore)
10  QuartzCore                      0x0000000184bca34c CA::Context::commit_transaction(CA::Transaction*) :252 (in QuartzCore)
11  QuartzCore                      0x0000000184bf13ac CA::Transaction::commit() :504 (in QuartzCore)
12  QuartzCore                      0x0000000184bf1e78 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) :120 (in QuartzCore)
13  CoreFoundation                  0x00000001818e89a8 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ :32 (in CoreFoundation)
14  CoreFoundation                  0x00000001818e6630 __CFRunLoopDoObservers :372 (in CoreFoundation)
15  CoreFoundation                  0x0000000181816dc4 _CFRunLoopRunSpecific :456 (in CoreFoundation)
16  WebCore                         0x00000001864e8d3c _ZL12RunWebThreadPv :456 (in WebCore)
17  libsystem_pthread.dylib         0x00000001809fd68c _pthread_body :240 (in libsystem_pthread.dylib)
18  libsystem_pthread.dylib         0x00000001809fd59c _pthread_start :284 (in libsystem_pthread.dylib)
19  libsystem_pthread.dylib         0x00000001809facb4 _thread_start :4 (in libsystem_pthread.dylib)

**Comment by sueLan** [comment]
It's similar to https://github.com/airbnb/lottie-ios/issues/387.

**Comment by buba447** [comment]
Should be fixed on master!
