### ISSUE TITLE
Xcode 9 warnings

### ISSUE THREAD

**Issue by ivulyov90** [airbnb/lottie-ios#457]
## Lottie-ios Issue
There are 2 warnings in xCode 9.0.1
/Pods/lottie-ios/lottie-ios/Classes/Private/LOTAnimatedSwitch.m:152:15: 'userInterfaceLayoutDirectionForSemanticContentAttribute:' is only available on iOS 9.0 or newer
/Pods/lottie-ios/lottie-ios/Classes/Private/LOTAnimatedSwitch.m:152:15: Enclose 'userInterfaceLayoutDirectionForSemanticContentAttribute:' in an @available check to silence this warning
/Pods/lottie-ios/lottie-ios/Classes/Private/LOTAnimatedSwitch.m:152:76: 'semanticContentAttribute' is only available on iOS 9.0 or newer
/Pods/lottie-ios/lottie-ios/Classes/Private/LOTAnimatedSwitch.m:152:76: Enclose 'semanticContentAttribute' in an @available check to silence this warning

Seems should be fixed here
https://github.com/airbnb/lottie-ios/pull/454

## Check these before submitting:
- [x] Updated to the latest (2.1.3) version of Lottie
- [x] The issue doesnt involve and [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isnt related to another open issue

## This issue is a
- [x] Non-Crashing (Visual or otherwise) Bug
- [ ] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked doesnt work anymore)

## What Platform are you on? 
- [ ] MacOS (Specify Platform Version)
- [x] iOS (Specify Platform Version)

**Comment by buba447** [comment]
Should be fixed!
