### ISSUE TITLE
Does Lottie support adding animation to the launch screen for iOS?

### ISSUE THREAD

**Issue by jnkfong** [airbnb/lottie-ios#461]
## Check these before submitting:
- [x] Updated to the latest (2.1.3) version of Lottie
- [x] The issue doesnt involve and [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isnt related to another open issue

## This issue is a
- [ ] Non-Crashing (Visual or otherwise) Bug
- [ ] Crashing Bug
- [x] Feature Request
- [ ] Regression (Something that once worked doesnt work anymore)

## What Platform are you on? 
- [ ] MacOS (Specify Platform Version)
- [x] iOS (Specify Platform Version)

## Code Example
Can you provide an example?

**Comment by buba447** [comment]
You can add it to a launch view controller and have it be the first view controller the app displays.

Apple doesnt allow anything to move in the launch view controller as far as I know.
