### ISSUE TITLE
Lottie works fine in HTML but skips animation in iOS

### ISSUE THREAD

**Issue by hoosierfan24** [airbnb/lottie-ios#462]
I when attempting to use my JSON export for a view controller transition the app just hangs up and then jumps to the following screen. It works fine when using the .json file in the example project but when I use my own it is not working properly.

When using my .json file in html it works seamlessly any idea whats going on?

```
    func animationController(forPresented presented: UIViewController, presenting: UIViewController, source: UIViewController) -> UIViewControllerAnimatedTransitioning? {
        animationTrans = LOTAnimationTransitionController(animationNamed: "swipe2", fromLayerNamed: "outLayer", toLayerNamed: "inLayer", applyAnimationTransform: false)
        
        print("my custom animation")


        
        return animationTrans
        
    }
```

**Comment by buba447** [comment]
Without seeing the JSON I cant really tell you. Are you trying to mask the two viewControllers or do you want the viewControllers to move with the animation? Try changing `applyAnimationTransform: false` to `applyAnimationTransform: true`

**Comment by VictorZhang2014** [comment]
I have a similar issue, like this Fireworks Effect didn't work on iOS device, but did work in HTML
https://github.com/airbnb/lottie-ios/issues/544

**Comment by sinhpn92** [comment]
I have same issue. Have any suggest or solution to fix this issue?

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
