### ISSUE TITLE
Crash when building animation. 

### ISSUE THREAD

**Issue by khangsile** [airbnb/lottie-ios#463]
## Lottie-ios Issue
Hello! Sorry you are having an Issue! Please help us make Lottie better by filling everything below out with as much information as you can so we can try to reproduce and fix the issue!

## Check these before submitting:
- [ ] Updated to the latest (2.1.3) version of Lottie
- [ ] The issue doesnt involve and [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [ ] This issue isnt related to another open issue

## This issue is a
- [ ] Non-Crashing (Visual or otherwise) Bug
- [X] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked doesnt work anymore)

## What Platform are you on? 
- [ ] MacOS (Specify Platform Version)
- [X] iOS (iOS 9.3.5+)

## Expected Behavior 
(Screenshots encouraged)

## Actual Behavior
(Screenshots encouraged)

## Code Example
We have this stack trace in our app that has been causing us problems. It seems to occur intermittently so I'm not sure if it's the json or some typ
[crash_icon.zip](https://github.com/airbnb/lottie-ios/files/1419505/crash_icon.zip)
e of threading issue.

Exception NSInvalidArgumentException
Reason*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]

Stack Trace:
  | 0x0000000186a7efe0 | (CoreFoundation+ 0x0012cfe0) | __exceptionPreprocess
-- | -- | -- | --
  | 0x00000001854e0534 | (libobjc.A.dylib+ 0x00008534) | objc_exception_throw
  | 0x00000001869659b0 | (CoreFoundation+ 0x000139b0) | -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]
  | 0x0000000186965820 | (CoreFoundation+ 0x00013820) | +[NSDictionary dictionaryWithObjects:forKeys:count:]
  | 0x00000001011d7600 | (App -LOTShapeLayerView.m:98) | -[LOTShapeLayerView _buildAnimation]
  | 0x00000001011d7464 | (App -LOTShapeLayerView.m:91) | -[LOTShapeLayerView initWithShape:fill:stroke:trim:transform:withLayerDuration:]
  | 0x00000001011d221c | (App -LOTGroupLayerView.m:71) | -[LOTGroupLayerView _setupShapeGroupWithFill:stroke:trimPath:]
  | 0x00000001011d1ac8 | (App -LOTGroupLayerView.m:32) | -[LOTGroupLayerView initWithShapeGroup:transform:fill:stroke:trimPath:withLayerDuration:]
  | 0x00000001011d3940 | (App -LOTLayerView.m:179) | -[LOTLayerView _setupViewFromModelWithLayerGroup:]
  | 0x00000001011d2f48 | (App -LOTLayerView.m:101) | -[LOTLayerView initWithModel:inLayerGroup:]
  | 0x00000001011cfb68 | (App -LOTCompositionLayer.m:81) | -[LOTCompositionLayer _setupWithLayerGroup:withAssetGroup:withBounds:]
  | 0x00000001011cf6bc | (App -LOTCompositionLayer.m:40) | -[LOTCompositionLayer initWithLayerGroup:withAssetGroup:withBounds:]
  | 0x00000001011e92a8 | (App -LOTAnimationView.m:307) | -[LOTAnimationView _buildSubviewsFromModel]
  | 0x00000001011e905c | (App -LOTAnimationView.m:282) | -[LOTAnimationView _setupWithSceneModel:restoreAnimationState:]
  | 0x00000001859369dc | (libdispatch.dylib+ 0x000019dc) | _dispatch_call_block_and_release
  | 0x000000018593699c | (libdispatch.dylib+ 0x0000199c) | _dispatch_client_callout
  | 0x000000018593b5e4 | (libdispatch.dylib+ 0x000065e4) | _dispatch_main_queue_callback_4CF
  | 0x0000000186a2d0c4 | (CoreFoundation+ 0x000db0c4) | __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
  | 0x0000000186a2ace0 | (CoreFoundation+ 0x000d8ce0) | __CFRunLoopRun
  | 0x000000018695ada0 | (CoreFoundation+ 0x00008da0) | CFRunLoopRunSpecific
  | 0x00000001883c5070 | (GraphicsServices+ 0x0000c070) | GSEventRunModal
  | 0x000000018cc0ec98 | (UIKit+ 0x00074c98) | UIApplicationMain

## Animation JSON
Attached.

**Comment by buba447** [comment]
Hmmm, The icon seems to load just fine for me in the example app. Are you still seeing this issue?

**Comment by khangsile** [comment]
Hey Brandon,

We picked this up through our crash reporting so we haven't been able to reproduce it ourselves. What makes it difficult is that it seems to happen at a low rate. We have other stack traces that seem to be originating from the same place in initializing the animation view. The JSON seems fine to us, too, and because it isn't happening regularly, it's been hard for us to track the source of the issue.

CRASHED [EXC_SOFTWARE / UNCAUGHT_NS_EXCEPTION
0x000000018e15afe0 | (CoreFoundation+ 0x0012cfe0) | __exceptionPreprocess
-- | -- | --
  | 0x000000018cbbc534 | (libobjc.A.dylib+ 0x00008534) | objc_exception_throw
  | 0x000000018e161ef0 | (CoreFoundation+ 0x00133ef0) | -[NSObject(NSObject) doesNotRecognizeSelector:]
  | 0x000000018e15ef50 | (CoreFoundation+ 0x00130f50) | ___forwarding___
  | 0x000000018e05ad48 | (CoreFoundation+ 0x0002cd48) | _CF_forwarding_prep_0
  | 0x00000001011dbd70 | (App -LOTAnimationView.m:43) | -[LOTAnimationState initWithDuration:layer:frameRate:]
  | 0x00000001011dd0e0 | (App -LOTAnimationView.m:284) | -[LOTAnimationView _setupWithSceneModel:restoreAnimationState:]
  | 0x000000018d0129dc | (libdispatch.dylib+ 0x000019dc) | _dispatch_call_block_and_release
  | 0x000000018d01299c | (libdispatch.dylib+ 0x0000199c) | _dispatch_client_callout
  | 0x000000018d0175e4 | (libdispatch.dylib+ 0x000065e4) | _dispatch_main_queue_callback_4CF
  | 0x000000018e1090c4 | (CoreFoundation+ 0x000db0c4) | __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
  | 0x000000018e106ce0 | (CoreFoundation+ 0x000d8ce0) | __CFRunLoopRun
  | 0x000000018e036da0 | (CoreFoundation+ 0x00008da0) | CFRunLoopRunSpecific
  | 0x000000018faa1070 | (GraphicsServices+ 0x0000c070) | GSEventRunModal
  | 0x00000001942eac98 | (UIKit+ 0x00074c98) | UIApplicationMain
  | 0x00000001005836b8 | (App -main.m:39) | main
  | 0x000000018d045598 | (libdyld.dylib+ 0x00004598) | start

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
