### ISSUE TITLE
Error:Execution failed for task ':app:prepareComAndroidSupportAnimatedVectorDrawable2610Library'

### ISSUE THREAD

**Issue by hsnmrd** [airbnb/lottie-ios#464]
`Error:Execution failed for task ':app:prepareComAndroidSupportAnimatedVectorDrawable2610Library'.
> Unable to unzip 'C:\Users\ramin\.gradle\caches\modules-2\files-2.1\com.android.support\animated-vector-drawable\26.1.0\abdf83a0192c03ff190f941c6c885af18d257a2c\animated-vector-drawable-26.1.0.aar' to 'C:\Users\ramin\.android\build-cache\6b7ed6c6f6a25dd18477727c16a13e0789c57b4e\output'`

android studio shows this error when i try to use lottie in my project

**Comment by buba447** [comment]
Try commenting on the Android Repo https://github.com/airbnb/lottie-android
