### ISSUE TITLE
When can I support 3D layer?

### ISSUE THREAD

**Issue by CdzhcHappy** [airbnb/lottie-ios#469]
When can I support 3D layer? Please

**Comment by buba447** [comment]
We currently havent roadmapped support for this! Sorry!

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
