### ISSUE TITLE
Reset Animation

### ISSUE THREAD

**Issue by nlogioco** [airbnb/lottie-ios#47]
I'm speaking in particular to iOS. Is there currently a way for an animation to be reset before it completes?

**Comment by nlogioco** [comment]
Can you reset an animation by using 'animationProgress = 0.0'?

**Comment by buba447** [comment]
@nlogioco Yeah that should work! is it not working?

**Comment by nlogioco** [comment]
@buba447 
It is. I realized if 'animationProgress' is set before 'play' it'll go to that progress spot via animation. If 'animationProgress' is set after play, it'll cancel the animation and go back to beginning and not play.

I have noticed something weird (not sure if it is by design):

`
animation?.animationProgress = 0.9
animation?.play()
`

Expected results v1:
Start the animation at 0% completed
End the animation at 90% completed

Expected results v1:
Start the animation at 90% completed
End the animation at 100% completed

Actual results:
Start the animation at 0% completed
End the animation at 10% completed

**Comment by buba447** [comment]
Hmm thats very strange @nlogioco 
Is the `animation.animationProgress = 0.9
animation.play()` happening before or after you've added it to a superview? Can I get more context?

**Comment by nlogioco** [comment]
@buba447 

I add it to the superview before setting the properties.

What would you recommend?

**Comment by buba447** [comment]
@nlogioco I think i found a fix. I push pushed it to master.

**Comment by buba447** [comment]
@nlogioco Please check it out and let me know if it didn't work!

https://github.com/airbnb/lottie-ios/pull/91
