### ISSUE TITLE
r2.1.4 build failed in Xcode 8.x

### ISSUE THREAD

**Issue by wing0wind** [airbnb/lottie-ios#472]
## Lottie-ios Issue
After I updated lottie by pod from 2.1.3 to 2.1.4, I got a build failed.

## Check these before submitting:
- [x] Updated to the latest (2.1.4) version of Lottie
- [x] The issue doesnt involve and [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isnt related to another open issue

## This issue is a
- [x] Regression (Something that once worked doesnt work anymore)

## What Platform are you on? 
- [x] iOS (Specify Platform Version)

## Expected Behavior 
It should build success without error in Xcode8.x like r2.1.3.

## Actual Behavior
<img width="1133" alt="2017-11-02 19 26 41" src="https://user-images.githubusercontent.com/6858246/32321262-ea135000-c003-11e7-93e9-f5bb80b7c9e2.png">

## Animation JSON

___
And I create a pull request to fix it.
https://github.com/airbnb/lottie-ios/pull/471

**Comment by ppamorim** [comment]
Happening here too, destroying my evening.

**Comment by buba447** [comment]
Should be fixed on master now!
