### ISSUE TITLE
Lottie Animation Not Working in IOS and Android

### ISSUE THREAD

**Issue by rakeshbijoriyagate6** [airbnb/lottie-ios#473]
## Lottie-ios and Android Issue
Hi,

I have created animation in After Effect and added some masking effects as you explain in doc.
After creating animation exported in JSON file, when I used JSON file in IOS and Android build
it showing bottom part which I have mask in After Effect. Means it works in reverse order.

Please find created animation in attachment files in details. Please provide a solution to this issue as soon as possible.

## Expected Behavior 
(Screenshots encouraged)
[final Animation (1).zip](https://github.com/airbnb/lottie-ios/files/1440131/final.Animation.1.zip)

## Animation JSON
Adding the animation JSON helps us debug the issue faster!

**Comment by buba447** [comment]
Hello! the inverted checkmark is not supported. Try changing the mask type
to subtract!

Also I noticed your AE file has some illustrator files that havent been
converted to vectors. These need to be converted to properly display with
Lottie!

Read more here
http://airbnb.io/lottie/after-effects/artwork-to-lottie-walkthrough.html

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
