### ISSUE TITLE
Lottie animation still freezes after updating to 2.1.4 version

### ISSUE THREAD

**Issue by albertoNovo** [airbnb/lottie-ios#474]
## Lottie-ios Issue
I'm having a similar issue that the one described on #429 after update to the last version 2.1.4 (issue closed and included in the 2.1.4)

## Check these before submitting:
- [x] Updated to the latest (2.1.3) version of Lottie
- [x] The issue doesnt involve and [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isnt related to another open issue

## This issue is a
- [x] Non-Crashing (Visual or otherwise) Bug

## What Platform are you on? 
- [x] iOS (Specify Platform Version)

## Expected Behavior 
I have a view controller that contains a LOTAnimationView running in loop. At the moment I leave the view controller, because i change to another tab or push to a new view controller or present a modal view controller on top, and then go back to the original view controller I'm expecting the animation is still running.

## Actual Behavior
After doing all this steps what I'm seeing is that the animation is frozen. It seems a similar issue that the #429

## Animation JSON
[addToCard_loop.json.zip](https://github.com/airbnb/lottie-ios/files/1441141/addToCard_loop.json.zip)

**Comment by dmcyk** [comment]
@meiwin did the PR you prepare fix the issue for you? It didn't in my case, the state restoration is prepared in `willMoveTo`, which is called just before `animationDidStop`, which then calls `setProgressWithFrame` and there the state restoration is reversed. 
I'm not very familiar with the code, but shouldn't that reverse happen only if the `callCompletionIfNecessary` argument is actually `true`?

**Comment by gokeji** [comment]
I'm seeing the exact same issue in 2.1.4. The animation does not resume playing even if I manually try to trigger `animationView.play()`

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
