### ISSUE TITLE
Unlimited memory

### ISSUE THREAD

**Issue by pluswithplus** [airbnb/lottie-ios#475]
Every time you run a new animation, memory increases. When cacheEnable=NO, it doesn't work either. Can you automatically release memory after each animation run.Thank you!

**Comment by buba447** [comment]
It should release when the view itself is released. 
How are you allocating the animation? Maybe theres a bug with the cache

**Comment by buba447** [comment]
Care to share examples?
Im not seeing the issue here. I just ran a deep memory test over here are the results https://github.com/airbnb/lottie-ios/issues/483

I will close this issue soon if I dont hear back!
