### ISSUE TITLE
Not quite working in React Native

### ISSUE THREAD

**Issue by diligentdonkey** [airbnb/lottie-ios#476]
## Lottie-ios Issue
My team and I are having trouble getting our bodymovin AE export to display properly. We've tried a few times using the export, and tried with various settings on and off, but not much luck. We want to use one of the Animography fonts for the splash screen in our React Native iOS app. I'm attaching the file here. Any advice would be much appreciated! I have a feeling the issue is with how I am exporting the animation. She's tried loading things from lottiefiles and those all work fine.

## Check these before submitting:
- [ ] Updated to the latest (2.1.3) version of Lottie
- [ ] The issue doesnt involve and [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [ ] This issue isnt related to another open issue

## This issue is a
[+] Non-Crashing (Visual or otherwise) Bug

## What Platform are you on? 
 [+] MacOS 10.12.6
[+] iOS11, iPhone 7

## Expected Behavior 
<img width="262" alt="screen shot 2017-11-06 at 10 40 03 pm" src="https://user-images.githubusercontent.com/33424381/32446326-800fce0c-c343-11e7-9c1c-3c2242e588f4.png">

## Actual Behavior
![2017-11-06](https://user-images.githubusercontent.com/33424381/32446847-35fe87e8-c345-11e7-8676-ca3eba76e87f.png)

## Animation JSON

[data.js.zip](https://github.com/airbnb/lottie-ios/files/1446549/data.js.zip)

**Comment by yeomann** [comment]
did you ever manager to solve this? @diligentdonkey

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
