### ISSUE TITLE
I don't know how to use

### ISSUE THREAD

**Issue by AkaShark** [airbnb/lottie-ios#477]
## Lottie-ios Issue
Hello! Sorry you are having an Issue! Please help us make Lottie better by filling everything below out with as much information as you can so we can try to reproduce and fix the issue!

## Check these before submitting:
- [ ] Updated to the latest (2.1.3) version of Lottie
- [ ] The issue doesnt involve and [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [ ] This issue isnt related to another open issue

## This issue is a
- [ ] Non-Crashing (Visual or otherwise) Bug
- [ ] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked doesnt work anymore)

## What Platform are you on? 
- [ ] MacOS (Specify Platform Version)
- [ ] iOS (Specify Platform Version)

## Expected Behavior 
(Screenshots encouraged)

## Actual Behavior
(Screenshots encouraged)

## Animation JSON
Adding the animation JSON helps us debug the issue faster!
I am IOS couple，I download the json from https://www.lottiefiles.com but can't use it ? Thanks

**Comment by buba447** [comment]
I need some more context? What is the problem you are having?
