### ISSUE TITLE
Invalid LOTTIE JSON

### ISSUE THREAD

**Issue by goelay** [airbnb/lottie-ios#478]
How to know the JSON file is invalid which we have given input to the LOTTIE iOS library as right now if I give wrong json file or inavlid file name my finished of play animation is never called. I should get call back like failed or something.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
