### ISSUE TITLE
Reverse Animation

### ISSUE THREAD

**Issue by nlogioco** [airbnb/lottie-ios#48]
Is there a way to set the current progress and then set the end progress and then animate?

Ex:
ToValue: 0.0
FromValue: 0.5

**Comment by buba447** [comment]
I haven't be able to get reverse animations to work yet!

**Comment by nlogioco** [comment]
@buba447 This would be an amazing feature.

**Comment by allanweir** [comment]
I think there is some duplication of Lottie's animation code so this could be improved, but if you want to quickly see partial or reverse playback I've created a class here:

https://gist.github.com/allanweir/badefea836590cfe61edae915b6e40bf

**Comment by welshm** [comment]
If you set the animationSpeed to -1 it goes in reverse. Or is this not the reversal you want?

**Comment by welshm** [comment]
Using a -1 animationSpeed no longer works, but looks like support is planned for 2.0

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
