### ISSUE TITLE
lottie-ios 2.1.4 module not found error when installed by cocoapods

### ISSUE THREAD

**Issue by AdamMak** [airbnb/lottie-ios#480]
I recently updated lottie to 2.1.4 from 2.1.3 and am now getting an error saying no such module 'Lottie' when I try to import the framework.

When I look under my pods, the lottie-ios folder is empty. Can anyone tell me what the issue is here?

**Comment by AdamMak** [comment]
Seems you have to download the new beta version of cocoapods. If you don't when you call pod update, lottie will not install properly. Hope that helps anyone else who has this issue

**Comment by RahulDhiman93** [comment]
Import Lottie - No such module 'Lottie'
