### ISSUE TITLE
Can't deallocate memory for `[LOTKeyframeGroup buildKeyframesFromData:]`

### ISSUE THREAD

**Issue by vipyne** [airbnb/lottie-ios#483]
- [x] Updated to the latest (2.1.3) version of Lottie
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isnt related to another open issue (as far as I could tell)

## This issue is a
- [x] Non-Crashing, non-visual Bug

## What Platform are you on? 
- [x] iOS 11.1/xcode 9/swift 3.2 
(the issue was also present when working with iOS 10/xcode 8/swift 3.2)

## Expected Behavior 
The animation plays once and then the view is destroyed and all the resources dedicated to it are freed.  All memory allocations should be transient, not persistent.

## Actual Behavior
AFAIK there is no way to free the memory allocated to LOTKeyframes, specifically the `-[LOTKeyframeGroup buildKeyframesFromData:]` call.
![screen shot 2017-10-31 at 2 06 23 pm](https://user-images.githubusercontent.com/3700028/32691346-4b8999bc-c6d4-11e7-93ac-e87f49cb5b1b.png)
![screen shot 2017-10-31 at 2 06 15 pm](https://user-images.githubusercontent.com/3700028/32691370-9767afae-c6d4-11e7-80b2-a68ba698b911.png)

## Code Example
`animationView.removeFromSuperview()` is called.  Is there another way to free all the Lottie memory?  Or is it possible to add a free() somewhere in the LOTKeyframeGroup class? (I poked around the code a little, but my experience with Objective C is limited.)

## Animation JSON
[lottie-star.json.zip](https://github.com/airbnb/lottie-ios/files/1463894/lottie-star.json.zip)

Thanks in advance!

**Comment by buba447** [comment]
Hello! Lottie comes with a built in caching mechanism for the model layer. This exists to save time when creating copies of an animation. One of the most cpu expensive parts of creating a Lottie animation is reading and deserializing the JSON into models. So we cache the models in a global cache controlled by `LOTAnimationCache` 
This is turned on by default, which could be argued if its the right behavior. We are working to make this system a bit more sophisticated but currently its just a simple singleton.

To clear the cache you can call `[[LOTAnimationCache sharedCache] clearCache];`
Or you can turn the cache off all together by calling  `[[LOTAnimationCache sharedCache] disableCaching];`

To be sure that there wasnt a memory leak I created a test app with your animaiton. The app creates 100 animation views, waits for them play all the way through then removes them from the superview.

With caching on the allocation profiler shows this after all 100 views are deallocated.
<img width="905" alt="screen shot 2017-11-30 at 11 56 36 am" src="https://user-images.githubusercontent.com/1163980/33452024-a6e314aa-d5c5-11e7-8ca0-a2eb10c1c5f7.png">

With caching disabled we get
<img width="900" alt="screen shot 2017-11-30 at 11 52 17 am" src="https://user-images.githubusercontent.com/1163980/33452041-b39390a8-d5c5-11e7-8065-74bf2eae3e29.png">


I hope this was helpful!
