### ISSUE TITLE
CGAffineTransformMakeScale

### ISSUE THREAD

**Issue by hdyluo** [airbnb/lottie-ios#484]
I want to change LOTAnimationView transform,but it do not work

**Comment by ClockWise89** [comment]
What issue are you experiencing? I might have a similar issue. I add my lottie animations layer to my superviews layer, I then perform AffineTransforms on that superviews sublayers and it works fine with images added in this way, but animations with lottie gets weird. The transform doesn't seem to take place. The lottie animation pops to the right position after the animation of the sublayers are done.

I create my lottie animation as follows:
```
-(CALayer *)fetchAnimationLayer:(NSString*)animationName {
LOTAnimationView *a = [LOTAnimationView animationNamed:animationName];
        a.frame = icon.frame;
        a.loopAnimation = YES;
        [a play];

return a.layer;
}
```
Where my superview adds the returning layer to its sublayers, and then I perform animations on all sublayers of my superview, which works fine except for my lottie animations...

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
