### ISSUE TITLE
KVO on animationProgress is not currently supported

### ISSUE THREAD

**Issue by Alex1989Wang** [airbnb/lottie-ios#485]
I noticed that using KVO on animationProgress on a LOTAnimationView object is not working. So, besides using a timer to query this value, is there a way to continuously get the changing animationProgress while the animation is playing?

**Comment by buba447** [comment]
Try `realtimeAnimationProgress` in Lottie 3.0

Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
