### ISSUE TITLE
Animation shows objects which are out of AEP artboard

### ISSUE THREAD

**Issue by CaitlinRev** [airbnb/lottie-ios#488]
Hi to everybody!
Since the latest release I've got this problem:
Some elements of imported animation go beyond AEP artboard preset (f.e. in attachment - artboard is 450x450px and blue card was out of composition's frames but I still can see it) According to .json composition size is still 450x450px but why I see object beyond it?
Never had this problem before and still don't have this problem on Android
Could you please help me, how can I fix it?
Or if it's bug please fix it immediately
![artboard_issue](https://user-images.githubusercontent.com/33665172/32792922-a21fd23e-c975-11e7-8ab3-33f2d0dee62b.png)

**Comment by buba447** [comment]
Try setting the animation view's .clipsToBounds property to YES.

**Comment by fabiog86** [comment]
Hi buba447,
have the same problem exporting animations from After effects with Bodymovin, where can I set .clipsToBounds property? directly in After Effects? Thanks
