### ISSUE TITLE
Work For Android But Fail on iOS

### ISSUE THREAD

**Issue by LeeWongSnail** [airbnb/lottie-ios#489]
This is my json file

[json.zip](https://github.com/airbnb/lottie-ios/files/1478417/json.zip)

Android platform can complete the animation but the iOS platform can not！

version:2.1.4

I saw u had supported Gradients 

This is my code in Objective-C

`
LOTAnimationView *animation = [LOTAnimationView animationNamed:@"data"];
    [self.view addSubview:animation];
    animation.frame = self.view.bounds;
    animation.contentMode = UIViewContentModeScaleAspectFit;
    animation.loopAnimation = YES;
    [animation playWithCompletion:^(BOOL animationFinished) {
        NSLog(@"succ");
    }];
`
Can anyone tell me if there is any problem with my file?

error log:
+[LOTShapeGroup shapeItemWithJSON:]: Warning: gradient strokes are not supported

Is there any way to solve this problem?

**Comment by buba447** [comment]
Ios doesnt support gradient strokes! Sorry!

**Comment by LeeWongSnail** [comment]
When do you plan to start supporting?

**Comment by Attitrue** [comment]
i meet the same situation,hope gradient strokes will be supported soon

**Comment by JienLee** [comment]
I've been see the same log, when do you start the plan to supporting gradient strokes??

log : 
[LOTShapeGroup shapeItemWithJSON:]: Warning: merge shape is not supported. name: Merge Paths 1

**Comment by emtjoshhart** [comment]
Saw gradients were supported, spent hours making animation with gradients, exported using Bodymovin, tested it in Xcode to find out it isn't supported.  Threw my computer against the wall and stomped on it.

**Comment by buba447** [comment]
Gradients are supported. Gradients strokes are not.
Stay tuned for news around this.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC

**Comment by imran087** [comment]
Hi Buba447 could you please mention when will be fix the problem Gradients strokes are not.

**Comment by buba447** [comment]
Gradient strokes are supported in 3+
