### ISSUE TITLE
Category Methods should be prefixed

### ISSUE THREAD

**Issue by ianegordon** [airbnb/lottie-ios#49]
The methods added in UIColor+Expanded and CAAnimationGroup+LAAnimatableGroup should be prefixed to avoid name collisions.

**Avoid Category Method Name Clashes**
https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/CustomizingExistingClasses/CustomizingExistingClasses.html#//apple_ref/doc/uid/TP40011210-CH6-SW4

This is related to #16

**Comment by buba447** [comment]
Will fix in the next release! Sorry!
