### ISSUE TITLE
stroke dash animates fine on web, not on ios/android

### ISSUE THREAD

**Issue by evanfuture** [airbnb/lottie-ios#490]
* **iOS Version:** 11.1 (need to support 10 as well)
* **After Effects Version:** CC 2017

**What did you do? Please explain the steps you took before you encountered the problem.**
exported from AE, other files from lottiefiles work fine.

**What did you expect to happen?**
![cap-ok](https://user-images.githubusercontent.com/2659994/32890901-beddb004-cae1-11e7-8ad2-b6c5c35a2309.gif)
This is more or less how it should look.  Spinner should repeat properly.

**What actually happened? Please include as much _relevant_ detail as possible.**
So, I built a loader, and exported to json.  It plays fine in the web player.  But using it on mobile there are two problems.

## iOS: 
![cap-ios](https://user-images.githubusercontent.com/2659994/32890921-d0ce4292-cae1-11e7-9aaa-04acb8e47252.gif)
The first time through, the animation works fine, after that the Dash doesn't seem to make it back to 0, and it just keeps repeating like that.  I've tried adding keyframes at the end of the file to jump it back before it repeats, but that didn't change anything.

## Android:
![cap-android](https://user-images.githubusercontent.com/2659994/32890997-0c238852-cae2-11e7-8f95-4c49c37ff710.gif)
The first part of the animation is just fine, but the 2nd part seems to get all weird and play twice as fast.

I'm wondering if there's anything you can spot that's wrong with the AE file, or the JSON.  It's baffling to me.

**Please provide a download link to the After Effects file that demonstrates the problem.**
attached: 
[Archive.zip](https://github.com/airbnb/lottie-ios/files/1481375/Archive.zip)

**Comment by buba447** [comment]
Hmmm this is a weird bug! We will have to dig into it, but for a quick fix you can achieve the same animation using trim paths instead of dashes.

**Comment by karip** [comment]
I have also discovered this bug on iOS/Mac Lottie Player.

Dash animations seem to be sluggish and can't change fast. That's why it can't make it back to 0 in @evanfuture's iOS example.

I've attached an example json file to show the issue. The black dash animation and the blue scale animation should move is sync. On lottie-5.1.16 web player, everything works fine. On the Mac player, the dash animation is behind the scale animation.

[dashes.json.zip](https://github.com/airbnb/lottie-ios/files/2079412/dashes.json.zip)

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
