### ISSUE TITLE
how to add lottie as a universal framework without internet

### ISSUE THREAD

**Issue by ItamarManor** [airbnb/lottie-ios#491]
Hi, 

I've been tasked with adding Lottie at my workplace. 
I'm developing on an iMac running xcode 8.3 and iOS9.

I can't use cocoapods / carthage. (no internet allowed)
how can I add lottie offline so it builds for sim+device and builds in jenkins with all the bitcode shannanigens?
there must be a simple way.

help.

**Comment by buba447** [comment]
Heres a pretty good guide
https://blog.carbonfive.com/2011/04/04/using-open-source-static-libraries-in-xcode-4/
