### ISSUE TITLE
Incorrect Play Animation which contains image assets. And does Lottie-ios support Image Assets?

### ISSUE THREAD

**Issue by YK-Unit** [airbnb/lottie-ios#493]
Lottie-ios incorrect play animation which contains image assets. The [example json](https://www.lottiefiles.com/186-height-increase) is from lottiefiles.com.

When I use [Lottie-Android-Preview-APP](https://www.lottiefiles.com/android) to play the example json, [Lottie-Android-Preview-APP](https://www.lottiefiles.com/android) hints that `Image Assets are not supported yet `

So the other question is: does Lottie-ios support Image Assets?

**Comment by buba447** [comment]
Lottie ios and android both support image assets. I suspect that warning is old.
You must bundle the images in the same bundle as the animation, or specify the resource locaiton programatically.
