### ISSUE TITLE
Animation disappears and comes back a few seconds later 

### ISSUE THREAD

**Issue by mchangxe** [airbnb/lottie-ios#500]
## Lottie-ios Issue
Hello! Sorry you are having an Issue! Please help us make Lottie better by filling everything below out with as much information as you can so we can try to reproduce and fix the issue!

## Check these before submitting:
- [x] Updated to the latest (2.1.3) version of Lottie
- [x] The issue doesnt involve and [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isnt related to another open issue

## This issue is a
- [x] Non-Crashing (Visual or otherwise) Bug
- [ ] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked doesnt work anymore)

## What Platform are you on? 
- [ ] MacOS (Specify Platform Version)
- [x] iOS (Specify Platform Version)

## Expected Behavior 
(Screenshots encouraged)
When an animation's loop attribute is set to true, the animation should loop smoothly

## Actual Behavior
(Screenshots encouraged)
The animation plays for a few seconds, disappears for a few seconds and comes back again. The cycle continues. 

## Code Example
    func loadWaveAnimation(){
        if let animationView = LOTAnimationView(name: "wave"){
            waveView.addSubview(animationView)
            animationView.frame = CGRect(x: 0, y: 0, width: self.view.bounds.width, height: waveView.frame.height)
            animationView.contentMode = .scaleToFill
            
            animationView.loopAnimation = true

            animationView.play()
            waveView .sendSubview(toBack: animationView)
        }
    }

## Animation JSON
Adding the animation JSON helps us debug the issue faster!
https://www.lottiefiles.com/search?q=mild

**Comment by iMatkovic** [comment]
Having same issue with same animation. Any clues?

**Comment by buba447** [comment]
Im not seeing the issue on my end. The waves play, then slow to a stop. After a second they start back. This isnt a bug with lottie, but is how the animation itself is constructed.

**Comment by buba447** [comment]
Fell free to reopen if you encounter further issues
