### ISSUE TITLE
Crash in [LOTBezierPath LOT_appendPath:]

### ISSUE THREAD

**Issue by foadsaliba** [airbnb/lottie-ios#501]
## Lottie-ios Issue
Crash on LOT_appendPath.

The issue happens extremely sporadically. The problem occurs in a controller with a UIWebview that has a loading animation in a view on top of the webview that fades in and out. There is also a progress animation which corresponds to a download progress. The crash only happens on this view. We have several animations on other views that work just fine. It seems to be tied to the webview and the download progress animation. The animation progress is set continuously as the download progress changes.

```
let currentProgress = downloadIconAnimatedControl.animationProgress
downloadIconAnimatedControl.animationView.pause()
downloadIconAnimatedControl.animationView.play(fromProgress: currentProgress, toProgress: toPosition, withCompletion: nil)
```

not pausing or not using the fromProgress:toProgress:withCompletion: doesn't work and would cause the animation to either not update and/or starting from the beginning all the time.

I have seen the crash happen on only 2 threads, main and webthread. 
I saw another issue that saw the same behaviour but the crash in on a different place.

I know it's a long shot, and I wish I could help more, but this is all I got at the moment.

```
malloc: *** error for object 0x17423b2c0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```

## Check these before submitting:
- [x] Updated to the latest (2.1.3) version of Lottie
- [x] The issue doesnt involve and [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isnt related to another open issue

## This issue is a
- [ ] Non-Crashing (Visual or otherwise) Bug
- [x] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked doesnt work anymore)

## What Platform are you on? 
- [ ] MacOS (Specify Platform Version)
- [x] iOS (swift 3.2 iOS 9+)

## Expected Behavior 
No crash. 

## Actual Behavior
Crash

0   ???                                 0x000000010f4bc20c 0x0 + 4551590412,
1   App                                0x00000001003924ec main + 0,
2   libsystem_c.dylib                   0x000000018a0ea3f4 abort + 140,
3   libsystem_malloc.dylib              0x000000018a1ac95c <redacted> + 0,
4   CoreGraphics                        0x000000018c6d1108 <redacted> + 60,
5   CoreGraphics                        0x000000018c6d0ffc <redacted> + 248,
6   CoreGraphics                        0x000000018c6d07b8 <redacted> + 188,
7   Lottie                              0x00000001011f32fc -[LOTBezierPath LOT_appendPath:] + 124,
8   Lottie                              0x000000010120b030 -[LOTRenderGroup rebuildOutputs] + 308,
9   Lottie                              0x00000001011eea88 -[LOTAnimatorNode updateWithFrame:withModifierBlock:forceLocalUpdate:] + 648,
10  Lottie                              0x000000010120ab00 -[LOTRenderGroup updateWithFrame:withModifierBlock:forceLocalUpdate:] + 276,
11  Lottie                              0x000000010120aa94 -[LOTRenderGroup updateWithFrame:withModifierBlock:forceLocalUpdate:] + 168,
12  Lottie                              0x0000000101202490 -[LOTLayerContainer displayWithFrame:forceUpdate:] + 868,
13  Lottie                              0x00000001011f7008 -[LOTCompositionContainer displayWithFrame:forceUpdate:] + 544,
14  Lottie                              0x000000010120210c -[LOTLayerContainer displayWithFrame:] + 80,
15  Lottie                              0x0000000101202094 -[LOTLayerContainer display] + 332,
16  QuartzCore                          0x000000018e4aaf30 <redacted> + 228,
17  QuartzCore                          0x000000018e4aafb4 <redacted> + 44,
18  QuartzCore                          0x000000018e427c64 <redacted> + 252,
19  QuartzCore                          0x000000018e44f0d0 <redacted> + 512,
20  QuartzCore                          0x000000018e44faf0 <redacted> + 120,
21  CoreFoundation                      0x000000018b1557dc <redacted> + 32,
22  CoreFoundation                      0x000000018b15340c <redacted> + 372,
23  CoreFoundation                      0x000000018b15389c <redacted> + 1024,
24  CoreFoundation                      0x000000018b082048 CFRunLoopRunSpecific + 444,
25  GraphicsServices                    0x000000018cb05198 GSEventRunModal + 180,
26  UIKit                               0x000000019105c628 <redacted> + 684,
27  UIKit                               0x0000000191057360 UIApplicationMain + 208,
28  App                                0x0000000100392538 main + 76,
29  libdyld.dylib                       0x000000018a0645b8 <redacted> + 4

**Comment by buba447** [comment]
This should be fixed on master
