### ISSUE TITLE
2.1.4 doesn't work with xcode 8

### ISSUE THREAD

**Issue by RyanMitchellWilson** [airbnb/lottie-ios#503]
We have been using lottie-react-native 2.2.7 for over a month now with no problems. But a couple days ago when lottie-ios version 2.1.4 was released it broke version 2.2.7 since version 2.2.7 of lottie-react-native has a dependency `lottie-ios: ^2.1.3` which is now installing 2.1.4 which doesn't work in xcode 8 due to this line https://github.com/airbnb/lottie-ios/blob/2.1.4/lottie-ios/Classes/Private/LOTAnimatedSwitch.m#L152 

Causes an error in xcode 8 saying `Unrecognized platform name iOS` which causes the build to fail. Can this please get fixed soon? We cannot update to xcode 9 until they actually fix the simulator in it, so until then we need to stay on xcode 8.

**Comment by Ahmeddben** [comment]
Any solution to this? Same problem here! thanks

**Comment by RyanMitchellWilson** [comment]
@Ahmeddben If you add `"lottie-ios": "2.1.3"` to your package.json, npm will then respect what you choice for lottie-ios instead of what lottie-react-native wants.

**Comment by buba447** [comment]
Fixed in 2.1.5 (About to publish)
