### ISSUE TITLE
Has some layer can not display in v2.0.5, and also exists at master

### ISSUE THREAD

**Issue by Tracydeng** [airbnb/lottie-ios#504]
When UI give me a data son file, it has one of layer cannot display at iOS platform, but it work normal at andriod， and I will give you the json data which cannot display as normaly。

## Code Example

```
  self.lottieLogo = [LOTAnimationView animationNamed:@"dislike"];

```
## Animation JSON

the data json just one part of the whole file ， but contains parent and the part of which cannot display。

{"v":"4.7.1","fr":60,"ip":0,"op":90,"w":260,"h":260,"nm":"屎","ddd":0,"assets":[],"layers":[{"ddd":0,"ind":1,"ty":3,"nm":"空 3","ks":{"o":{"a":0,"k":0},"r":{"a":1,"k":[{"i":{"x":[0.756],"y":[0.235]},"o":{"x":[0.449],"y":[0.01]},"n":["0p756_0p235_0p449_0p01"],"t":7,"s":[0],"e":[0.249]},{"i":{"x":[0.637],"y":[0.915]},"o":{"x":[0.362],"y":[-1.984]},"n":["0p637_0p915_0p362_-1p984"],"t":11,"s":[0.249],"e":[0]},{"i":{"x":[0.676],"y":[1]},"o":{"x":[0.24],"y":[-0.026]},"n":["0p676_1_0p24_-0p026"],"t":18,"s":[0],"e":[0]},{"t":31}]},"p":{"a":0,"k":[130,130,0]},"a":{"a":0,"k":[-3,-0.5,0]},"s":{"a":0,"k":[100,100,100]}},"ao":0,"ip":0,"op":600,"st":0,"bm":0,"sr":1},{"ddd":0,"ind":8,"ty":4,"nm":"2💩","parent":1,"ks":{"o":{"a":0,"k":100},"r":{"a":0,"k":0},"p":{"a":1,"k":[{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"n":"0p667_1_0p333_0","t":9,"s":[0,-15,0],"e":[0,-10,0],"to":[0,0.83333331346512,0],"ti":[0,-0.00816909410059,0]},{"i":{"x":0.667,"y":1},"o":{"x":0.167,"y":0},"n":"0p667_1_0p167_0","t":26,"s":[0,-10,0],"e":[0,-14.951,0],"to":[0,0.00816909410059,0],"ti":[0,0.82516425848007,0]},{"t":41}]},"a":{"a":0,"k":[0,0,0]},"s":{"a":0,"k":[100,100,100]}},"ao":0,"shapes":[{"ty":"gr","it":[{"ty":"st","c":{"a":0,"k":[0.4392157,0.0509804,0.0509804,1]},"o":{"a":0,"k":100},"w":{"a":0,"k":10},"lc":1,"lj":1,"ml":4,"nm":"描边 1","mn":"ADBE Vector Graphic - Stroke"},{"ty":"fl","c":{"a":0,"k":[1,0.8039216,0.6588235,1]},"o":{"a":0,"k":100},"r":1,"nm":"填充 1","mn":"ADBE Vector Graphic - Fill"},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"形状 1","np":2,"cix":2,"ix":1,"mn":"ADBE Vector Group"},{"ind":1,"ty":"sh","ix":2,"ks":{"a":1,"k":[{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"n":"0p667_1_0p333_0","t":0,"s":[{"i":[[0,0],[0,2.222],[-12.173,0],[0,-6.889],[17.163,0]],"o":[[-1.264,-1.807],[0,-6.889],[12.173,0],[0,6.889],[0,0]],"v":[[-20.269,21.741],[-22.041,15.625],[0,3.152],[22.041,15.625],[0,28.098]],"c":false}],"e":[{"i":[[0,0],[-1.318,5.267],[-12.173,0],[-2.003,-7.492],[14.793,-0.322]],"o":[[-6.82,-2.773],[2.613,-10.443],[12.173,0],[2.874,10.748],[0,0]],"v":[[-20.428,28.378],[-29.156,16.262],[0,3.152],[23.423,18.371],[0.008,30.973]],"c":false}]},{"i":{"x":0.644,"y":1},"o":{"x":0.333,"y":0},"n":"0p644_1_0p333_0","t":14,"s":[{"i":[[0,0],[-1.318,5.267],[-12.173,0],[-2.003,-7.492],[14.793,-0.322]],"o":[[-6.82,-2.773],[2.613,-10.443],[12.173,0],[2.874,10.748],[0,0]],"v":[[-20.428,28.378],[-29.156,16.262],[0,3.152],[23.423,18.371],[0.008,30.973]],"c":false}],"e":[{"i":[[0,0],[0.572,3.149],[-12.173,0],[-1.923,-14.68],[17.163,0]],"o":[[-2.454,0.516],[-2.719,-14.98],[12.173,0],[0.953,7.27],[0,0]],"v":[[-20.269,21.741],[-29.156,16.262],[0,3.152],[25.423,14.871],[0,28.098]],"c":false}]},{"i":{"x":0.54,"y":0.974},"o":{"x":0.417,"y":0},"n":"0p54_0p974_0p417_0","t":34,"s":[{"i":[[0,0],[0.572,3.149],[-12.173,0],[-1.923,-14.68],[17.163,0]],"o":[[-2.454,0.516],[-2.719,-14.98],[12.173,0],[0.953,7.27],[0,0]],"v":[[-20.269,21.741],[-29.156,16.262],[0,3.152],[25.423,14.871],[0,28.098]],"c":false}],"e":[{"i":[[0,0],[-0.68,3.544],[-12.173,0],[-0.619,-13.428],[17.163,0]],"o":[[-7.231,-3.54],[3.656,-19.061],[12.173,0],[0.327,7.08],[0,0]],"v":[[-20.269,21.741],[-30.406,8.262],[0,3.152],[26.673,12.871],[0,28.098]],"c":false}]},{"i":{"x":0.591,"y":1},"o":{"x":0.516,"y":0.029},"n":"0p591_1_0p516_0p029","t":47,"s":[{"i":[[0,0],[-0.68,3.544],[-12.173,0],[-0.619,-13.428],[17.163,0]],"o":[[-7.231,-3.54],[3.656,-19.061],[12.173,0],[0.327,7.08],[0,0]],"v":[[-20.269,21.741],[-30.406,8.262],[0,3.152],[26.673,12.871],[0,28.098]],"c":false}],"e":[{"i":[[0,0],[0.406,4.564],[-12.173,0],[-0.173,-11.67],[17.163,0]],"o":[[-3.981,-0.29],[-1.143,-12.828],[12.173,0],[0.083,5.58],[0,0]],"v":[[-20.269,21.741],[-29.156,16.262],[0,3.152],[23.423,15.871],[0,28.098]],"c":false}]},{"i":{"x":0.591,"y":1},"o":{"x":0.268,"y":0},"n":"0p591_1_0p268_0","t":65,"s":[{"i":[[0,0],[0.406,4.564],[-12.173,0],[-0.173,-11.67],[17.163,0]],"o":[[-3.981,-0.29],[-1.143,-12.828],[12.173,0],[0.083,5.58],[0,0]],"v":[[-20.269,21.741],[-29.156,16.262],[0,3.152],[23.423,15.871],[0,28.098]],"c":false}],"e":[{"i":[[0,0],[-0.219,3.689],[-12.173,0],[-0.173,-11.67],[11.5,0.103]],"o":[[-3.606,-0.728],[0.759,-12.817],[12.173,0],[0.083,5.58],[0,0]],"v":[[-20.269,21.741],[-26.906,14.762],[0,3.152],[20.673,15.621],[0,28.098]],"c":false}]},{"t":72}]},"nm":"路径 1","mn":"ADBE Vector Shape - Group"},{"ty":"fl","c":{"a":0,"k":[1,0.8039216,0.6588235,1]},"o":{"a":0,"k":100},"r":1,"nm":"填充 1","mn":"ADBE Vector Graphic - Fill"},{"ty":"st","c":{"a":0,"k":[0.4392157,0.0509804,0.0509804,1]},"o":{"a":0,"k":100},"w":{"a":0,"k":10},"lc":2,"lj":2,"nm":"描边 1","mn":"ADBE Vector Graphic - Stroke"}],"ip":-1,"op":606,"st":6,"bm":0,"sr":1},]}

**Comment by buba447** [comment]
Doesnt seem to work with the web player either (www.lottiefiles.com)
Maybe its the emojii layer name.

**Comment by Tracydeng** [comment]
Oh, no , Not that!  the data which I  gave you was the dirty data, and hope you to find why.  now, I  will give you the data which can display normaly, and work with the web player. and it's also contain emojii
layer name
```
{"v":"4.7.1","fr":60,"ip":0,"op":90,"w":260,"h":260,"nm":"屎","ddd":0,"assets":[],"layers":[{"ddd":0,"ind":1,"ty":3,"nm":"空 3","ks":{"o":{"a":0,"k":0},"r":{"a":1,"k":[{"i":{"x":[0.756],"y":[0.235]},"o":{"x":[0.449],"y":[0.01]},"n":["0p756_0p235_0p449_0p01"],"t":7,"s":[0],"e":[0.249]},{"i":{"x":[0.637],"y":[0.915]},"o":{"x":[0.362],"y":[-1.984]},"n":["0p637_0p915_0p362_-1p984"],"t":11,"s":[0.249],"e":[0]},{"i":{"x":[0.676],"y":[1]},"o":{"x":[0.24],"y":[-0.026]},"n":["0p676_1_0p24_-0p026"],"t":18,"s":[0],"e":[0]},{"t":31}]},"p":{"a":0,"k":[130,130,0]},"a":{"a":0,"k":[-3,-0.5,0]},"s":{"a":0,"k":[100,100,100]}},"ao":0,"ip":0,"op":600,"st":0,"bm":0,"sr":1},{"ddd":0,"ind":9,"ty":4,"nm":"1💩","parent":1,"ks":{"o":{"a":0,"k":100},"r":{"a":0,"k":0},"p":{"a":0,"k":[0.5,31.709,0]},"a":{"a":0,"k":[0,18.709,0]},"s":{"a":1,"k":[{"i":{"x":[0.667,0.667,0.667],"y":[1,1,1]},"o":{"x":[0.167,0.167,0.167],"y":[0,0,0]},"n":["0p667_1_0p167_0","0p667_1_0p167_0","0p667_1_0p167_0"],"t":0,"s":[100,85,100],"e":[100,100,100]},{"i":{"x":[0.833,0.833,0.833],"y":[1,1,1]},"o":{"x":[0.167,0.167,0.167],"y":[-0.63,-0.005,0]},"n":["0p833_1_0p167_-0p63","0p833_1_0p167_-0p005","0p833_1_0p167_0"],"t":10,"s":[100,100,100],"e":[100,85,100]},{"t":31}]}},"ao":0,"shapes":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":1,"k":[{"i":{"x":0.405,"y":1},"o":{"x":0.333,"y":0},"n":"0p405_1_0p333_0","t":0,"s":[{"i":[[-23.103,0],[0,10.333],[16.385,0],[0,-10.333]],"o":[[23.103,0],[0,-10.333],[-16.385,0],[0,10.333]],"v":[[0,18.709],[29.669,0],[0,-18.709],[-29.669,0]],"c":true}],"e":[{"i":[[-23.103,0],[0,10.333],[16.378,0.491],[1.296,-13.744]],"o":[[23.103,0],[0,-10.333],[-20.75,-0.622],[-1.238,13.129]],"v":[[0,18.709],[33.669,5.882],[0,-18.709],[-39.046,3.972]],"c":true}]},{"i":{"x":0.833,"y":1},"o":{"x":0.167,"y":0},"n":"0p833_1_0p167_0","t":12,"s":[{"i":[[-23.103,0],[0,10.333],[16.378,0.491],[1.296,-13.744]],"o":[[23.103,0],[0,-10.333],[-20.75,-0.622],[-1.238,13.129]],"v":[[0,18.709],[33.669,5.882],[0,-18.709],[-39.046,3.972]],"c":true}],"e":[{"i":[[-23.103,0],[0.319,11.812],[16.378,0.491],[0.171,-16.244]],"o":[[23.103,0],[-0.419,-15.508],[-20.75,-0.622],[-0.139,13.186]],"v":[[0,18.709],[33.919,5.588],[0,-18.709],[-39.046,3.972]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0},"n":"0p833_0p833_0p167_0","t":32,"s":[{"i":[[-23.103,0],[0.319,11.812],[16.378,0.491],[0.171,-16.244]],"o":[[23.103,0],[-0.419,-15.508],[-20.75,-0.622],[-0.139,13.186]],"v":[[0,18.709],[33.919,5.588],[0,-18.709],[-39.046,3.972]],"c":true}],"e":[{"i":[[-21.763,0.567],[-1.669,11.698],[16.378,0.491],[-0.07,-29.246]],"o":[[20.75,-0.54],[3.088,-21.653],[-20.75,-0.622],[0.035,14.734]],"v":[[0,18.709],[33.928,-7.272],[0,-18.709],[-40.285,-8.036]],"c":true}]},{"i":{"x":0.862,"y":1},"o":{"x":0.167,"y":0.167},"n":"0p862_1_0p167_0p167","t":45,"s":[{"i":[[-21.763,0.567],[-1.669,11.698],[16.378,0.491],[-0.07,-29.246]],"o":[[20.75,-0.54],[3.088,-21.653],[-20.75,-0.622],[0.035,14.734]],"v":[[0,18.709],[33.928,-7.272],[0,-18.709],[-40.285,-8.036]],"c":true}],"e":[{"i":[[-23.103,0],[0.212,9.786],[16.378,0.491],[-2.204,-19.92]],"o":[[23.103,0],[-0.419,-19.331],[-20.75,-0.622],[1.45,13.107]],"v":[[0,18.709],[33.419,1.912],[0,-18.709],[-38.546,0.884]],"c":true}]},{"i":{"x":0.92,"y":1},"o":{"x":0.297,"y":0},"n":"0p92_1_0p297_0","t":60,"s":[{"i":[[-23.103,0],[0.212,9.786],[16.378,0.491],[-2.204,-19.92]],"o":[[23.103,0],[-0.419,-19.331],[-20.75,-0.622],[1.45,13.107]],"v":[[0,18.709],[33.419,1.912],[0,-18.709],[-38.546,0.884]],"c":true}],"e":[{"i":[[-16,0.342],[-0.419,9.051],[16.37,0.72],[-2.204,-19.332]],"o":[[16.273,-0.348],[0.63,-13.624],[-19.986,-0.879],[1.254,10.999]],"v":[[0,18.709],[27.919,3.235],[2.75,-19.004],[-35.546,3.384]],"c":true}]},{"t":72}]},"nm":"路径 1","mn":"ADBE Vector Shape - Group"},{"ty":"fl","c":{"a":0,"k":[1,0.8039216,0.6588235,1]},"o":{"a":0,"k":100},"r":1,"nm":"填充 1","mn":"ADBE Vector Graphic - Fill"},{"ty":"st","c":{"a":0,"k":[0.4392157,0.0509804,0.0509804,1]},"o":{"a":0,"k":100},"w":{"a":0,"k":10},"lc":2,"lj":2,"nm":"描边 1","mn":"ADBE Vector Graphic - Stroke"}],"ip":0,"op":600,"st":0,"bm":0,"sr":1}]}
```
