### ISSUE TITLE
setValue on vertices

### ISSUE THREAD

**Issue by stellanhaglund** [airbnb/lottie-ios#508]
Sorry I accidentally removed the template and I can't get it back, every time I click new issue it's still empty.

Would there be any way to get the vertices of a path drawn with the pen tool using `(void)logHierarchyKeypaths` and then use `setValue` on them?
In javascript it is possible since it's just objects and arrays.
The idea is to make some charts and stuff using lottie and ae then I would need to be able to move the points depending on the data.

**Comment by buba447** [comment]
Now possible in master. Will be version 2.5 when released!
