### ISSUE TITLE
How do I animate LOTAnimationView.layer in accordance with its superlayer/superview?

### ISSUE THREAD

**Issue by ClockWise89** [airbnb/lottie-ios#513]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.1.5)
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [x] iOS

TLDR; How do I animate `LOTAnimationView.layer` in accordance with its superlayer/superview?

I have an UIView, which in turn has several other `UIViews` as `subviews`. When I tap one of these `subviews` I've created an animation which makes it look selected. But in these `subviews` I have `UILabels`, and `UIImageViews`. I decided to switch from `UIImageViews` to an animation in Lottie. So what I do is I save the labels layers, and imageViews icon layers and then animate their change when the UIView animates its selected state. This all works great. When I use Lottie animation it also works great - but only if I don't play the animation. When I play the animation the `LOTAnimationView` is "popping" into the correct position in its `superview` when the select animation is done.

I'm not too explored in the world of layers and animations, but it seems to me that since a paused animation works without any issues, it might have to do with something in the way Lottie animates. It's almost as if the Lottie animation objects layer is not at all added as a sublayer. Below is the only animation code I use in regards to Lottie. The layer is added to the calling UIViews sublayers and also separately in an array where I loop over and change respective values when I perform the select animation. Again, this works fine if I don't play the lottie animation below.

```
 - (CALayer *)fetchAnimationForIcon:(NSString *)iconName {
    LOTAnimationView *a = [LOTAnimationView animationNamed:iconName];
    [a play];

    return a.layer;
}
```
The code below is how I update my layers, where `_lottieLayers` contains the layer from the code above.
```
-(void)updateLayerTransform:(CGAffineTransform)transform zPosition:(CGFloat)zPosition {

    for (NSInteger i = 0; i < _lottieLayers.count; i++) {
        CALayer *iconLayer = _lottieLayers[(NSUInteger) i];
        iconLayer.affineTransform = transform;
        iconLayer.zPosition = [self getZPositionForIcon:(NSUInteger) i] + zPosition;
    }
}
```
I apologize for not showing code in its entirety, but for work related reasons I'm not allowed to. Hope you can help me anyway. Thanks!

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
