### ISSUE TITLE
Custom Layer Animation not working when used in AVExportSession, other is ok.

### ISSUE THREAD

**Issue by lvpengwei** [airbnb/lottie-ios#514]
My app is 猫饼，and i have used lottie-ios to show stickers in video.
but, the custom layer property animation does not work, and the other property is ok.

**Comment by xspyhack** [comment]
Hi @lvpengwei 

Offline rendering (AVAssetExportSession and AVAssetReader) interpreted animations on video's timeline, but Custom Layer Animation (Redraw each frame in CALayer.display or CALayer.drawInContext) on real-time.

So you can set CAAnimation's `beginTime = CACurrentMediaTime() + delay` when offline rendering, just set `beginTime = delay` when real-time playback.

**Comment by jjc235** [comment]
That won’t fix it either- delays will be device specific and unpredictable. 

You’ll need some other way to align frames to time as Lottie is frame specific.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
