### ISSUE TITLE
addSubview not worked.

### ISSUE THREAD

**Issue by ZomboriB** [airbnb/lottie-ios#515]
Hello.
I've prepared pentagons and I want to put a label and clip the bounds on iOS. I noticed that something is not quite right. I find the selected layer and call the function (addSubview: toLayerNamed: applyTransform: YES) then I see this. 
What's the problem?
Or is there any solution to get subView's position and clip the bounds?

[empty_pentagon.json.zip](https://github.com/airbnb/lottie-ios/files/1548386/empty_pentagon.json.zip)
![pentagon](https://user-images.githubusercontent.com/34451732/33839673-2efb4c9c-de93-11e7-9e27-d4a802fa31a4.png)
![img_2469](https://user-images.githubusercontent.com/34451732/33839680-31420a68-de93-11e7-93f8-ed3fab3990e5.jpg)

**Comment by carlostrianag** [comment]
@ZomboriB did you manage to solve this?
