### ISSUE TITLE
using bundles that can't read resource right 

### ISSUE THREAD

**Issue by veryitman** [airbnb/lottie-ios#517]
Thanks provide us lottie to use.

I put bundle more than one to my project of xcode, eg. 1001.bundle and 1002.bundle.

The bundle contains data.json and resource for photo, then it happens error first as follow.

> 1. The Lottie read the resource as same last always.

We review the code and find the class 'LOTAnimationCache', and we understand it.
Next we modify the json file to be different name, eg data1001.json and data1002.json.

`LOTComposition *comp = [[LOTAnimationCache sharedCache] animationForKey:animationName];`

> 2.The ' LOTLayerContainer' can't read the right file in bundle.

`- (void)_setImageForAsset:(LOTAsset *)asset` using the method as follow that cause read wrong resource.

`+ (nullable UIImage *)imageNamed:(NSString *)name inBundle:(nullable NSBundle *)bundle compatibleWithTraitCollection:(nullable UITraitCollection *)traitCollection NS_AVAILABLE_IOS(8_0)`

We modify the src:

`
if (asset.assetBundle) {
            image = [UIImage imageWithContentsOfFile:[asset.assetBundle.bundlePath stringByAppendingPathComponent:asset.imageName]];
        }
        else {
            NSArray *components = [asset.imageName componentsSeparatedByString:@"."];
            image = [UIImage imageNamed:components.firstObject inBundle:asset.assetBundle compatibleWithTraitCollection:nil];
        }
`

But we can't be sure, please give some help.

**Comment by YK-Unit** [comment]
If you use custom bundle, the json file and image files should be in same bundle, and the image files should not in any directory, for example:

![image](https://user-images.githubusercontent.com/4953353/34511778-f2618e28-f098-11e7-89df-06d718666aab.png)

Here is the example code:
``` objc
NSString *bundlePath = [[NSBundle mainBundle] pathForResource:@"Health_increase" ofType:@"bundle"];
NSBundle *resourceBundle = [NSBundle bundleWithPath:bundlePath];
LOTAnimationView *animView = [LOTAnimationView animationNamed:@"data" inBundle:resourceBundle];

```

Here is the example bundle:
[Health_increase.bundle.zip](https://github.com/airbnb/lottie-ios/files/1599628/Health_increase.bundle.zip)

**Comment by veryitman** [comment]
@YK-Unit I get you.
But we can't do this.So, i modify the sorce.

**Comment by jbolter** [comment]
I'm having this issue after updating from 2.1.5 to 2.5.0.  I have my images in my project's Images.xcassets.  

I can pinpoint the issue to this commit https://github.com/airbnb/lottie-ios/commit/48778ebaa3ffb604c9a1b6b49681c2fdb3cc4ab6#diff-5bbc908f7c47452481e176019d86f6a5 as suggested by others.  

I'm not doing anything "special" though so I'm not sure what the proper way to include the image assets for iOS is.

I can modify LOTLayerContainer.m to make things fallback to the 2.1.5 way but if anyone can point me in the right direction as to what I might be doing wrong that would be great.

Forked fix here: https://github.com/jbolter/lottie-ios

**Comment by revolter** [comment]
For me, the problem was fixed by https://github.com/revolter/lottie-ios/commit/7ec99812165d0a20ea64c273f09d3109983ff8f7

**Comment by gregoireLem** [comment]
Hey, I used two Lotties : 

```
 var lottieIndyView = LOTAnimationView(name: "indie", bundle: Bundle(path: Bundle.main.path(forResource: "indie", ofType: "bundle")!)!)
    var lottieCommuView = LOTAnimationView(name: "stack", bundle: Bundle(path: Bundle.main.path(forResource: "stack", ofType: "bundle")!)!)
```

The two JSON are well loaded, but for the two json only image of the first bundle are loaded ..

Thanks for helping

**Comment by wongzigii** [comment]
@gregoireLem 
Your issue is related to #609, one probably fix would be clear the cache.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
