### ISSUE TITLE
Missing Copyright Notice in LICENSE file

### ISSUE THREAD

**Issue by zashiki-01** [airbnb/lottie-ios#518]
Hello

We are planning to ship an app with lottie-ios and have a trouble on its license.
We want to add lottie-ios's copyright notice on our license list, but we couldn't find it in the LICENSE file.

Would you make it clear by adding copyright notice anywhere?

As far as we know, some libraries applying APL present their copyright in NOTICE file or LICENSE file.
    ex. https://github.com/moby/moby , https://github.com/tensorflow/tensorflow

Lottie-android also provides it in the LICENSE file but it replaces placeholders of the Appendix section. It looks incorrect since the section is just a sample.
    cf. https://github.com/kubernetes/kubernetes/commit/d30db1f9a915aa95402e1190461469a1889d92be

**Comment by buba447** [comment]
Updated! Thank you!
