### ISSUE TITLE
Lottie Viewer macOS

### ISSUE THREAD

**Issue by sogen** [airbnb/lottie-ios#519]
## Check these before submitting:
- [X ] Updated to the latest version of Lottie (2.1.5)
- [X ] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [X ] This issue isn't related to another open issue

## This issue is a:
- [X ] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [X ] MacOS

## Expected Behavior 
The docs show a Lottie Viewer for macOS that supports drag and drop of JSON files, is this a standalone app? Can't find it in any repo.

**Comment by OskarGroth** [comment]
lottie-ios/Example/Example for lottie-macos/

**Comment by buba447** [comment]
You have to build it from the xcode workspace!
Hoping to put it up on the app store soon!
