### ISSUE TITLE
Pause animation at a specified progress amount

### ISSUE THREAD

**Issue by rustyshelf** [airbnb/lottie-ios#52]
Just having a look at this project and it looks great! One thing that seems to be missing though is the ability to pause an animation at an amount of progress. So imagine being able to play to say 50% of the way through then automatically pause.

Why might this be handy?
Well imagine a play/pause button that we want to animate when the user taps it. So the sequence of events would be:
[user taps] -> animate from play to pause
[user taps again] -> animate from pause to play (this is not just the reverse of the first animation)

We could use one animation for that, if we had the ability to tell the framework to only play 50% of the animation, then later from 50% to completion (that second part already exists). I've attached the animation in question so that hopefully this makes more sense.

[playpause5.json.zip](https://github.com/airbnb/lottie-ios/files/759721/playpause5.json.zip)

I might be missing something, but having support for things that have 2 states and going between them seems fairly common?

**Comment by buba447** [comment]
Great suggestion!  We were also looking into supporting time markers.
Ill add it to the features request list! Thank you!

**Comment by allanweir** [comment]
Hey, as a temporary workaround until the Airbnb guys get it in, I have a Lottie subclass which might help that plays from A to B. It's not full featured such as triggering completion blocks but could help you get started https://gist.github.com/allanweir/badefea836590cfe61edae915b6e40bf

**Comment by rustyshelf** [comment]
@allanweir thanks for that. Tried it out but It seems like in the current version (1.0.4) setting it up using the `contentsOf` initialiser results in an empty view.

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!

**Comment by voghDev** [comment]
Cool! I see this feature is supported :)
Can someone paste a small code example on how to pause the animation at 50% or at 100%?
Thanks in advance!
