### ISSUE TITLE
When the application is switched from the background to the foreground, the animation is not executed

### ISSUE THREAD

**Issue by TopCoder2014** [airbnb/lottie-ios#524]
## Lottie-iOS Issue
Hello! Sorry you're having an Issue! Please help us make Lottie better by filling everything below out with as much information as you can, so we can try to reproduce and fix the issue!

## This issue is a:
- Non-Crashing Bug (Visual or otherwise)

When the application is switched from the background to the foreground, the animation is not executed

My Suggestion:

```
- (void)animationDidStop:(CAAnimation *)anim finished:(BOOL)complete {
  if ([_compContainer animationForKey:kCompContainerAnimationKey] == anim &&
      [anim isKindOfClass:[CABasicAnimation class]]) {
    CABasicAnimation *playAnimation = (CABasicAnimation *)anim;
    NSNumber *frame = _compContainer.presentationLayer.currentFrame;
    if (complete) {
      // Set the final frame based on the animation to/from values. If playing forward, use the
      // toValue otherwise we want to end on the fromValue.
      frame = [self _isSpeedNegative] ? (NSNumber *)playAnimation.toValue : (NSNumber *)playAnimation.fromValue;
    }
    if (complete) {
        [self _removeCurrentAnimationIfNecessary];
        [self setProgressWithFrame:frame callCompletionIfNecessary:NO];
    }
    [self _callCompletionIfNecessary:complete];
  }
}
```
## What Platform are you on? 
- iOS

**Comment by ZZinKin** [comment]
I have the same issue

**Comment by elsenpan** [comment]
same issue, for loop animation, should not remove animation after switch to background.

**Comment by AshishKapoor** [comment]
Same issue. Any work around?

**Comment by petretR** [comment]
Same issue here. My Animation is playing during the Splashscreen (start) of the App. 
After switching to background and coming back to Foreground, the animation is frozen, App is not responding. Do you have any workaround ?

**Comment by AshishKapoor** [comment]
We solved it with: https://facebook.github.io/react-native/docs/appstate.html

**Comment by filipstoklasa** [comment]
@AshishKapoor thanks! This solved my problem.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
