### ISSUE TITLE
Outline gradient (linear) used with trim path effect -> not working on iOS

### ISSUE THREAD

**Issue by pattogato** [airbnb/lottie-ios#525]
## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
## What Platform are you on? 
- [] iOS 10 - 11

## Expected Behavior 
Showing the outline gradient circle

## Actual Behavior
It's not showing the desired trimmed (blue - red) circle at all. If we remove the gradient from the animation, with solid a solid color it works.

## Animation JSON
https://www.lottiefiles.com/share/v5c3Td

**Comment by buba447** [comment]
Gradient strokes arent supported yet! Sorry!

**Comment by pattogato** [comment]
Do you have maybe a roadmap or any plans when is it going to be supported? :)

**Comment by natanrolnik** [comment]
This is related to #569

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
