### ISSUE TITLE
Is twist not supported? 

### ISSUE THREAD

**Issue by EriksenLasse** [airbnb/lottie-ios#529]
## Check these before submitting:
- [] Updated to the latest version of Lottie (2.1.5)
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [] iOS

**Comment by buba447** [comment]
Twist and Skew are currently unsupported! Sorry!

**Comment by EriksenLasse** [comment]
Thx. Gonna do it manually then.. ;) Thx for responding.

**Comment by buba447** [comment]
Skew now supported. Still no support for twist though.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
