### ISSUE TITLE
How to add it without pod or Carthage

### ISSUE THREAD

**Issue by zhengyaoyuan** [airbnb/lottie-ios#53]
How can I use it?  I want to just add some files to use it. thanks for help

**Comment by buba447** [comment]
Hello! You can use it without pods or carthage.
First your project must be converted to a workspace if its not already.
Then you must drag the Lottie.xcodeproj into the the workspace.
Finally you must go to your project target and add Lottie.framework under the section 'Linked Frameworks and libraries'
