### ISSUE TITLE
Attempting to change value at keyPath gives: NSUnknownKeyException

### ISSUE THREAD

**Issue by ben5516** [airbnb/lottie-ios#531]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.1.5)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [ ] Non-Crashing Bug (Visual or otherwise)
- [x] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [x] iOS

## Expected Behavior 

I'm expecting to be able to change the color of the Rectangle fill programmatically.

## Actual Behavior

Instead, it crashes with the following error:
```
 *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<LOTAnimationView 0x7f9fe5809820> valueForUndefinedKey:]: this class is not key value coding-compliant for the key Trigger.'
```

`[shutter logHierarchyKeypaths]` gives me:
```
LOTRenderGroup |Trigger.Rectangle 1.Transform.Scale
LOTRenderGroup |Trigger.Rectangle 1.Transform.Position
LOTRenderGroup |Trigger.Rectangle 1.Transform.Anchor Point
LOTRenderGroup |Trigger.Rectangle 1.Transform.Rotation
LOTRenderGroup |Trigger.Rectangle 1.Transform.Opacity
LOTFillRenderer |Trigger.Rectangle 1.Fill 1.Color
LOTFillRenderer |Trigger.Rectangle 1.Fill 1.Opacity
```

## Code Example
```objective-c
LOTAnimationView *shutter;
shutter = [LOTAnimationView animationNamed:@"button.json"];
shutter.animationSpeed = 20;
    
[shutter setValue:[UIColor redColor] forKeyPath:@"Trigger.Rectangle 1.Fill 1.Color"];
    
[self.view addSubview:shutter];
```

## Animation JSON
```son
{"v":"4.10.1","fr":29.9700012207031,"ip":0,"op":300.00001221925,"w":168,"h":168,"nm":"Shutter","ddd":0,"assets":[],"layers":[{"ddd":0,"ind":1,"ty":4,"nm":"Trigger","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":1,"k":[{"i":{"x":[0.666],"y":[0.981]},"o":{"x":[0.108],"y":[0.863]},"n":["0p666_0p981_0p108_0p863"],"t":0,"s":[0],"e":[90]},{"t":299.00001217852}],"ix":10},"p":{"a":0,"k":[84,84,0],"ix":2},"a":{"a":0,"k":[0,0,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ty":"rc","d":1,"s":{"a":1,"k":[{"i":{"x":[0.37,0.37],"y":[0.997,0.997]},"o":{"x":[0.211,0.211],"y":[0.901,0.901]},"n":["0p37_0p997_0p211_0p901","0p37_0p997_0p211_0p901"],"t":0,"s":[123,123],"e":[74,74]},{"t":299.00001217852}],"ix":2},"p":{"a":0,"k":[0,0],"ix":3},"r":{"a":1,"k":[{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.086],"y":[0.652]},"n":["0p667_1_0p086_0p652"],"t":0,"s":[64],"e":[14]},{"t":299.00001217852}],"ix":4},"nm":"Rectangle Path 1","mn":"ADBE Vector Shape - Rect","hd":false},{"ty":"fl","c":{"a":0,"k":[1,1,1,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0.125,-0.125],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Rectangle 1","np":3,"cix":2,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":300.00001221925,"st":0,"bm":0}]}
```

**Comment by buba447** [comment]
The method is 

`- (void)setValue:(nonnull id)value
      forKeypath:(nonnull NSString *)keypath
         atFrame:(nullable NSNumber *)frame;`

You're missing the `atFrame` part!

Also just and FYI, i just deprecated this method on master. You are free to use it with 2.1.5, but in the next release it will be deprecated. Ive replaced it with a new api for changing properties that I hope you will enjoy! Read more here http://airbnb.io/lottie/ios/dynamic.html

**Comment by ben5516** [comment]
@buba447 Doh! Sorry about that. I had seen the `atFrame` argument but got an error when I tried it because of the capitalization difference in `KeyPath` vs `Keypath`.

**Comment by superarts** [comment]
> http://airbnb.io/lottie/ios/dynamic.html

This link is dead.
