### ISSUE TITLE
iOS issues using After Effect‘s repeater

### ISSUE THREAD

**Issue by lnknig** [airbnb/lottie-ios#532]
Hi there, I am a designer and made an animation in which I used the After Effects repeater. All looks perfect on Android, but on iOS the repeated parts are missing. Has anyone an idea how to fix that? Thanks a lot :)

**Comment by rodrigoelp** [comment]
I had the same issue, with the exception that, it does not work in android nor iOS. However, it seems to work in web (which is bizarre).

**Comment by lnknig** [comment]
> I had the same issue, with the exception that, it does not work in android nor iOS. However, it seems to work in web (which is bizarre).

apparently iOS doesn't support the after effects repeater. In the end I animated the single objects and it worked.

**Comment by rodrigoelp** [comment]
Uh, that is the part I find bizarre... I have exported three different animations using repeaters out of which it works the others does not.

In any case, is good to receive some confirmation about other people having the same issue.

May I bother you asking: where did you read is not supported?

**Comment by lnknig** [comment]
puh, I don't remember where I read about it, I am sorry! It is already a very long time ago...
