### ISSUE TITLE
font dont render in iOS, not even like shape

### ISSUE THREAD

**Issue by pavelzIOS** [airbnb/lottie-ios#534]
## Check these before submitting:
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
## What Platform are you on? 
- [Any] iOS

## Animation JSON

Hi there, I am not sending the JSON, but will if needed. The issue is that font is not rendering inside iOS app even as shape. I have seen a closed issue with this information, but I'd like to know if there will be some opportunities to gain text result. 

Just to understand if it would be faster to try make it by my own.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
