### ISSUE TITLE
Animation completes as soon as it starts

### ISSUE THREAD

**Issue by eric-ludlow** [airbnb/lottie-ios#535]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.1.5)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [x] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [x] iOS

## Issue:
When I call the `playWithCompletion:` method of the animation view, it calls the `playFromFrame:toFrame:withCompletion:` method and successfully begins the animation.
Then, immediately after, something calls the `willMoveToWindow:` method, setting the `newWindow` parameter value to `nil`, even though the animationView is not leaving the window (no `present`, `push`, `dismiss`, or `pop`).
This then, apparently, calls `pause` immediately which calls `setProgressWithFrame:callCompletionIfNecessary:`, which removes the current animation and then calls the completion block of the `playWithCompletion:` method called on the animationView in my custom ViewController.

## Expected Behavior 
I expect the animation to play through as it used to in v. 2.1.3 and earlier and for the completion block to be called when the animation ends.

## Actual Behavior
The completion block is called as soon as the animation begins which leads to undesired behaviors between the ViewController and the animationView, specifically, in my case, the animation being dismissed early (as soon as it begins).

## Code Example
```
    private var animationView: LOTAnimationView?

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let animationView = LOTAnimationView(name: "animationOne")
        animationView.contentMode = .scaleAspectFit
        animationView.backgroundColor = .red
        animationView.frame = view.bounds
        view.addSubview(animationView)
        
        self.animationView = animationView
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        animationView?.play(completion: { (_) in
            self.dismissAnimationView()
        })
    }
    
    private func dismissAnimationView() {
        UIView.animate(withDuration: 0.9, animations: {
            self.animationView?.alpha = 0.0
        }, completion: { (_) in
            self.animationView?.removeFromSuperview()
            self.animationView = nil
        })
    }
```

## Animation JSON

Animation JSON is irrelevant to the issue.

**Comment by jocelynzz** [comment]
i'm having the same issue. Can anyone have a look??

**Comment by srikanth-ft** [comment]
I'm also facing same issue. Any update on this issue?

Version 2.1.5

Observation: If we run playFromFrame:toFrame:withCompletion: method in main thread after some delay (It's working some time delay time 0.1 and some times 1.0 not fixed delay time ) it is working.

**Comment by srikanthmca54** [comment]
same issue with V2.5 also

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
