### ISSUE TITLE
Mask Problem Lottie iOS not working

### ISSUE THREAD

**Issue by elisathielemann** [airbnb/lottie-ios#537]
Hey, I have the same problem :( Did my animation with Masks and in the bodymovin preview everything works fine. But when I put the .json in the lottie editor, the mask did not work anymore. I need to export as a svg file, because I need the logo animation for my mobile app. Do you have any idea how to fix? Here is the link in lottie: not working in any browser sadly :(

https://www.lottiefiles.com/share/2SpDDe

**Comment by buba447** [comment]
Hello! Are you using inverted masks? Any chance you can share the after effects file with us?

**Comment by elisathielemann** [comment]
Hey, yes. jere is the after effects file and also the .json file. But in the app it is not showing all elements with masks. 

https://we.tl/lZeYr7qOgC

**Comment by elisathielemann** [comment]
the previed in lottie is working with the .json file, but in the app its not.

**Comment by tuna-f1sh** [comment]
I have the same problem. This warning shows up in the debugger, not sure if masks become merged shape?: https://github.com/airbnb/lottie-ios/blob/master/lottie-ios/Classes/Models/LOTShapeGroup.m#L84 

I understood merge paths to be added in 2.->, are merge shape something else?

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC

**Comment by jatinRB** [comment]
still not working
