### ISSUE TITLE
Carthage installation documentation is wrong

### ISSUE THREAD

**Issue by mbuchetics** [airbnb/lottie-ios#54]
The readme states: 

> In your application targets “General” tab under the “Embedded Binaries” section, drag and drop lottie-ios.framework from the Carthage/Build/iOS directory that carthage update produced.

However, this is not correct. According to Carthage, you need to 

> On your application targets’ “General” settings tab, in the “Linked Frameworks and Libraries” section, drag and drop each framework you want to use from the Carthage/Build folder on disk.

[Carthage Readme](https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos)

**Comment by buba447** [comment]
Fixed!
