### ISSUE TITLE
Number of Frames

### ISSUE THREAD

**Issue by CassianoMouraLeao** [airbnb/lottie-ios#541]
How can I discover the number of frames? Is it on json?

**Comment by kubatruhlar** [comment]
There is the `endFrame` value in the `sceneModel` property

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
