### ISSUE TITLE
Is it possible to have lottie control the placement of a webM (or any file format other than png)?

### ISSUE THREAD

**Issue by pegeseus** [airbnb/lottie-ios#543]
I need to combine my lottie animation with webM video to create my final project.  It would be great if there was a way to have lottie control the position and timing of the webM instead of having to code it manually.  Is this possible?

**Comment by pegeseus** [comment]
eg. If I exported an animation from after effects using Lottie and had a png as a placeholder which could then be swapped out for a webM in the json.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
