### ISSUE TITLE
Colours are not rendered correctly

### ISSUE THREAD

**Issue by jmfriend** [airbnb/lottie-ios#547]
## Check these before submitting:
- [] Updated to the latest version of Lottie (2.1.5)
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [] This issue isn't related to another open issue. 

Don't know whether this relates to an unsupported feature or open issue as not sure what's causing this issue. Regardless, want to get this issue expedited if at all possible.

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

Colours go wrong as can be very easily seen in the screenshot in the attached zip file.

## What Platform are you on? 

- [] MacOS
- [X] iOS, but see the problem on the HTML viewer for Lottie as well

## Actual Behavior

Screenshot of what it looks like is in the attached issue.zip. It's quite clear that the colours have gone wrong. The zip file also contains the original illustrator file and the json produced.

## Animation JSON

[issue.zip](https://github.com/airbnb/lottie-ios/files/1681479/issue.zip)

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
