### ISSUE TITLE
the property of completionBlock may be setted nil in class LOTAnimationView，than the completionBlock will never be called ~ 

### ISSUE THREAD

**Issue by nikisu** [airbnb/lottie-ios#549]
platform：iOS
problem in this case:the object of LOTAnimationView view is leaving the screen,  than the method of willMoveToWindow is called first in file LOTAnimationView.m, now,let us look at the code first:

`- (void)willMoveToWindow:(UIWindow *)newWindow {
  // When this view or its superview is leaving the screen, e.g. a modal is presented or another
  // screen is pushed, this method will get called with newWindow value set to nil - indicating that
  // this view will be detached from the visible window.
  // When a view is detached, animations will stop - but will not automatically resumed when it's
  // re-attached back to window, e.g. when the presented modal is dismissed or another screen is
  // pop.
  if (newWindow) {
    // The view is being re-attached, resume animation if needed.
    if (_shouldRestoreStateWhenAttachedToWindow) {
      _shouldRestoreStateWhenAttachedToWindow = NO;
      _isAnimationPlaying = YES;
      _completionBlock = _completionBlockToRestoreWhenAttachedToWindow;
      _completionBlockToRestoreWhenAttachedToWindow = nil;

      [self performSelector:@selector(_restoreState) withObject:nil afterDelay:0];
    }
  } else {
    // The view is being detached, capture information that need to be restored later.
    if (_isAnimationPlaying) {
      _shouldRestoreStateWhenAttachedToWindow = YES;
      _completionBlockToRestoreWhenAttachedToWindow = _completionBlock;
      _completionBlock = nil;
    }
  }
}
`
in this process, the _completionBlock is setted nil, _completionBlockToRestoreWhenAttachedToWindow stored the address of _completionBlock.

after that, if we set LoopAnimation or set AnimationSpeed ,the logic triggers the method playFromFrame:toFrame:withCompletion: to be invoked, and than it will match the condition like the code below：

`
- (void)setLoopAnimation:(BOOL)loopAnimation {
  _loopAnimation = loopAnimation;
  if (_isAnimationPlaying && _sceneModel) {
    NSNumber *frame = [_compContainer.presentationLayer.currentFrame copy];
    [self setProgressWithFrame:frame callCompletionIfNecessary:NO];
    [self playFromFrame:_playRangeStartFrame toFrame:_playRangeEndFrame withCompletion:self.completionBlock]; /*  Afferent null value in logic  */
  }
}

- (void)playFromFrame:(nonnull NSNumber *)fromStartFrame
              toFrame:(nonnull NSNumber *)toEndFrame
       withCompletion:(nullable LOTAnimationCompletionBlock)completion {
......
if (!self.window) {  /* self.window is nil */
      _shouldRestoreStateWhenAttachedToWindow = YES;
/* self.completionBlock is nil, but the backup value _completionBlockToRestoreWhenAttachedToWindow will be setted nil too */
      _completionBlockToRestoreWhenAttachedToWindow = self.completionBlock; 
      self.completionBlock = nil;
  }
......
`
now , something happen, the _completionBlockToRestoreWhenAttachedToWindow has setted nil , and self.completionBlock is nil too, so self.completionBlock will never be called after that .

**Comment by iPHYZLL** [comment]
This is still an issue.
My non ideal but working workaround for this is that i put this block of code:

`delay(0.1) { [weak self] in
            guard let welf = self else { return }
            welf.animationView?.completionBlock = { [weak self] (finished) in
                guard let welf = self else { return }
                welf.showReplayView()
            }
        }`

in function, which is called by UIApplication.willEnterForegroundNotification.

So does anybody know why is this block set to nil ?

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
