### ISSUE TITLE
Lottie Swift Support.

### ISSUE THREAD

**Issue by GerardWoldendorp** [airbnb/lottie-ios#55]
When I try to download Lottie with Carthage for Swift it gives me an error that it can't run the Objective-C module Lottie. 

<img width="259" alt="schermafbeelding 2017-02-08 om 15 29 02" src="https://cloud.githubusercontent.com/assets/23334267/22741400/76f07106-ee13-11e6-8f62-3232a2fa1536.png">

**Comment by liu044100** [comment]
Maybe you can drag framework to your project directly

**Comment by terenzeyuen** [comment]
Getting same issue here.

**Comment by buba447** [comment]
Just updated the cocoa pod and the carthage file to 1.0.2
This should work now! Please reopen if you continue to have troubles @terenzeyuen @GerardWoldendorp
