### ISSUE TITLE
Carthage build is not working 

### ISSUE THREAD

**Issue by dkimitsa** [airbnb/lottie-ios#550]
## Check these before submitting:
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)

## What Platform are you on? 

- [x] iOS

Hi there is an issue with Carthage build, error log is bellow (older version 2.1.5 works). 

*** Checking out lottie-ios at "2.5.0"
*** xcodebuild output can be found in /var/folders/vr/vkkqdlys4mq0nvfnf_mwnfh5g3f__x/T/carthage-xcodebuild.eMJyM8.log
*** Building scheme "Lottie_tvOS" in Lottie.xcodeproj
....
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_LOTKeypath", referenced from:
      objc-class-ref in LOTAnimationTransitionController.o
      objc-class-ref in LOTAnimationView.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by oojojjeoo** [comment]
Got the same issue!

**Comment by blender** [comment]
Any updated on this? It's not just carthage. The project does not build at all even when opened in xcode

**Comment by giridharvc7** [comment]
Any updates on this? Happens in Cocoapods too

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
