### ISSUE TITLE
Animation not displaying correctly

### ISSUE THREAD

**Issue by borispl** [airbnb/lottie-ios#553]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.1.5)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [ ] MacOS
- [x] iOS

## Expected Behavior 

![expected](https://user-images.githubusercontent.com/31802034/35808482-3036068c-0a86-11e8-9874-7bdb35fea8ed.png)

## Actual Behavior

![actual](https://user-images.githubusercontent.com/31802034/35808487-358c35c0-0a86-11e8-92de-0555d54a2ee9.png)

On animation, inside "magnifier", there shouldn't be this orange frame.
When we run animation in browser (same animation exported in html), we don't have this problem.

## Code Example

```
@IBOutlet var lottieContainer: UIView!
```

 ```
private lazy var animationView: LOTAnimationView = {
    let animationView = LOTAnimationView(animation: presenter.animation) 
    animationView.contentMode = .scaleAspectFit
    lottieContainer.addSubview(animationView)
    animationView.snp.makeConstraints { (make) in
    make.edges.equalToSuperview()
    }
  return animationView
}()
```

```
func onboardingContainer(didPresent: Bool) {
    if didPresent {
         animationView.play()
    } else {
        animationView.stop()
    }
}
```

## Animation JSON

{"v":"5.1.4","fr":30,"ip":0,"op":60,"w":360,"h":200,"nm":"Onboarding illustration 5","ddd":0,"assets":[],"layers":[{"ddd":0,"ind":1,"ty":4,"nm":"Lupa Outlines","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":1,"k":[{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"n":"0p667_1_0p333_0","t":15,"s":[290.688,114.385,0],"e":[233.688,114.385,0],"to":[-9.5,0,0],"ti":[9.5,0,0]},{"i":{"x":0.667,"y":0.667},"o":{"x":0.333,"y":0.333},"n":"0p667_0p667_0p333_0p333","t":25,"s":[233.688,114.385,0],"e":[233.688,114.385,0],"to":[0,0,0],"ti":[0,0,0]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"n":"0p667_1_0p333_0","t":30,"s":[233.688,114.385,0],"e":[199.688,105.385,0],"to":[0,0,0],"ti":[42.3119506835938,-23.3848571777344,0]},{"t":45}],"ix":2},"a":{"a":0,"k":[233.75,195.01,0],"ix":1},"s":{"a":1,"k":[{"i":{"x":[0.509,0.509,0.833],"y":[1.221,1.221,1]},"o":{"x":[0.333,0.333,0.333],"y":[0,0,0]},"n":["0p509_1p221_0p333_0","0p509_1p221_0p333_0","0p833_1_0p333_0"],"t":15,"s":[0,0,100],"e":[100,100,100]},{"t":25}],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[11.17,-11.748],[0,0],[1.642,-1.479],[0,0],[1.479,1.642],[0,0],[12.918,0],[0,36.175],[-36.174,0],[0,-36.175]],"o":[[0,0],[1.478,1.642],[0,0],[-1.642,1.478],[0,0],[-10.148,6.455],[-36.174,0],[0,-36.175],[36.175,0],[0,17.49]],"v":[[42.474,34.33],[69.023,63.816],[68.728,69.466],[62.783,74.819],[57.133,74.522],[30.108,44.509],[-5.001,54.703],[-70.501,-10.797],[-5.001,-76.297],[60.499,-10.797]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ind":1,"ty":"sh","ix":2,"ks":{"a":0,"k":{"i":[[-27.614,0],[0,27.614],[27.615,0],[0,-27.614]],"o":[[27.615,0],[0,-27.614],[-27.614,0],[0,27.614]],"v":[[-4.501,39.703],[45.499,-10.297],[-4.501,-60.297],[-54.501,-10.297]],"c":true},"ix":2},"nm":"Path 2","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"mm","mm":1,"nm":"Merge Paths 1","mn":"ADBE Vector Filter - Merge","hd":false},{"ty":"fl","c":{"a":0,"k":[0.764999988032,0,0.090000002992,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[233.976,195.235],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Group 1","np":4,"cix":2,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":60,"st":0,"bm":0},{"ddd":0,"ind":2,"ty":4,"nm":"Fingerprint Zuti Outlines 2","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":1,"k":[{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"n":"0p667_1_0p333_0","t":30,"s":[98.651,95.697,0],"e":[66.651,86.697,0],"to":[7.66666650772095,-35.625,0],"ti":[0,0,0]},{"t":45}],"ix":2},"a":{"a":0,"k":[98.651,175.697,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"hasMask":true,"masksProperties":[{"inv":false,"mode":"i","pt":{"a":0,"k":{"i":[[-33.196,0],[0,-33.196],[33.196,0],[0,33.196]],"o":[[33.196,0],[0,33.196],[-33.196,0],[0,-33.196]],"v":[[227.5,123.393],[287.607,183.5],[227.5,243.607],[167.393,183.5]],"c":true},"ix":1},"o":{"a":0,"k":100,"ix":3},"x":{"a":0,"k":0,"ix":4},"nm":"Mask 1"}],"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[15.852,-8.337],[-2.045,1.072],[-16.875,0],[-16.363,-8.172],[2.13,1.073],[18.152,0]],"o":[[-2.045,1.073],[14.574,-7.759],[16.959,0],[0.597,0.329],[-17.386,-8.667],[-18.323,0]],"v":[[-51.977,-69.371],[-47.885,-62.107],[-0.414,-73.746],[47.055,-62.107],[50.976,-69.454],[-0.414,-82]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ind":1,"ty":"sh","ix":2,"ks":{"a":0,"k":{"i":[[13.491,-6.617],[8.482,-11.401],[0,0],[-0.684,1.14],[-11.651,5.7],[-24.588,-11.972],[-7.71,-10.261],[1.371,1.792],[12.851,6.271],[15.299,0]],"o":[[-12.852,6.27],[-1.37,1.873],[1.372,0],[7.711,-10.262],[24.502,-12.053],[11.565,5.618],[1.371,1.874],[-8.482,-11.32],[-13.453,-6.576],[-15.393,0]],"v":[[-44.163,-52.064],[-76.292,-25.434],[-72.779,-19],[-69.438,-20.71],[-40.309,-44.816],[40.223,-44.897],[69.265,-20.955],[76.291,-25.678],[44.164,-52.146],[0.111,-62]],"c":true},"ix":2},"nm":"Path 2","mn":"ADBE Vector Shape - Group","hd":false},{"ind":2,"ty":"sh","ix":3,"ks":{"a":0,"k":{"i":[[11.405,-22.791],[0,-9.803],[-4.203,-10.701],[0.857,2.124],[0,6.371],[-3.345,6.617],[-24.358,0],[0,-30.795],[9.863,0],[0,8.741],[14.58,0],[0,-13.233],[-12.007,-11.354],[-13.636,-3.594],[-0.343,0],[2.317,0.572],[8.148,7.678],[0,13.969],[-9.863,0],[0,-8.74],[-14.581,0],[0,13.234],[39.023,0]],"o":[[-3.86,7.759],[0,11.028],[0.771,2.042],[-5.147,-13.068],[0,-8.495],[10.034,-20.012],[34.306,0],[0,8.741],[-9.863,0],[0,-13.233],[-14.58,0],[0,16.174],[9.35,8.74],[0.342,0.082],[0,0],[-12.092,-3.187],[-10.378,-9.802],[0,-8.74],[9.863,0],[0,13.234],[14.58,0],[0,-35.288],[-27.702,0]],"v":[[-64.701,-4.424],[-70.533,22.042],[-64.272,54.39],[-56.296,51.53],[-62.044,22.042],[-56.982,-0.831],[-0.29,-33.75],[61.89,22.042],[44.051,37.889],[26.211,22.042],[-0.205,-1.974],[-26.621,22.042],[-8.01,64.683],[23.896,81.836],[25.011,82],[26.039,73.913],[-2.007,58.801],[-18.045,21.96],[-0.205,6.114],[17.635,21.96],[44.051,45.976],[70.468,21.96],[-0.29,-42]],"c":true},"ix":2},"nm":"Path 3","mn":"ADBE Vector Shape - Group","hd":false},{"ind":3,"ty":"sh","ix":4,"ks":{"a":0,"k":{"i":[[0,-24.196],[-5.912,-10.021],[-7.455,-7.089],[-1.115,0],[1.629,1.629],[5.482,9.37],[0,11.732],[-22.022,0],[0,-19.715],[-2.399,0],[0,2.282],[26.735,0]],"o":[[0,13.117],[5.742,9.858],[0.772,0.815],[0,0],[-6.598,-6.355],[-5.228,-8.798],[0,-19.715],[22.022,0],[0,2.282],[2.399,0],[0,-24.196],[-26.735,0]],"v":[[-49.533,21.912],[-40.536,57.27],[-23.312,78.778],[-20.313,80],[-17.143,72.994],[-32.994,53.277],[-40.964,21.912],[-1.033,-13.853],[38.898,21.912],[43.183,25.986],[47.467,21.912],[-1.033,-22]],"c":true},"ix":2},"nm":"Path 4","mn":"ADBE Vector Shape - Group","hd":false},{"ind":4,"ty":"sh","ix":5,"ks":{"a":0,"k":{"i":[[0,-2.276],[-12.87,-8.213],[-10.278,0],[-4.923,0.895],[2.332,-0.406],[2.074,0],[6.131,3.903],[0,11.466],[2.419,0]],"o":[[0,14.149],[7.428,4.798],[1.21,0],[2.417,-0.406],[-3.454,0.569],[-8.637,0],[-10.538,-6.668],[0,-2.276],[-2.418,0]],"v":[[-4.533,21.065],[16.023,56.763],[42.799,64],[53.251,63.023],[51.782,54.974],[42.799,55.787],[20.861,50.014],[4.104,21.065],[-0.215,17]],"c":true},"ix":2},"nm":"Path 5","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":0,"k":[0.921568632126,0.92549020052,0.941176474094,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":1,"k":[{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"n":"0p667_1_0p333_0","t":30,"s":[182.684,176.697],"e":[222.684,149.697],"to":[6.66666650772095,-4.5],"ti":[-6.66666650772095,4.5]},{"t":45}],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":1,"k":[{"i":{"x":[0.751,0.751],"y":[1.35,1.35]},"o":{"x":[0.758,0.758],"y":[-0.341,-0.341]},"n":["0p751_1p35_0p758_-0p341","0p751_1p35_0p758_-0p341"],"t":22,"s":[100,100],"e":[136,136]},{"t":27}],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":1,"k":[{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"n":["0p667_1_0p333_0"],"t":22,"s":[0],"e":[100]},{"t":30}],"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Group 1","np":6,"cix":2,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":60,"st":0,"bm":0},{"ddd":0,"ind":3,"ty":4,"nm":"Bijeli Krug/Onboarding illustration 5 Outlines","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":1,"k":[{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"n":"0p667_1_0p333_0","t":23,"s":[232.072,104.584,0],"e":[229.072,104.584,0],"to":[0,0,0],"ti":[-0.07457867264748,6.93581628799438,0]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"n":"0p667_1_0p333_0","t":30,"s":[229.072,104.584,0],"e":[195.072,94.584,0],"to":[0.33333334326744,-31,0],"ti":[12.6666669845581,-1.5,0]},{"t":45}],"ix":2},"a":{"a":0,"k":[228.5,184.5,0],"ix":1},"s":{"a":1,"k":[{"i":{"x":[0.667,0.667,0.667],"y":[1,1,1]},"o":{"x":[0.333,0.333,0.333],"y":[0,0,0]},"n":["0p667_1_0p333_0","0p667_1_0p333_0","0p667_1_0p333_0"],"t":19,"s":[-3,-3,100],"e":[97,97,100]},{"i":{"x":[0.833,0.833,0.833],"y":[1,1,1]},"o":{"x":[0.167,0.167,0.167],"y":[0,0,0]},"n":["0p833_1_0p167_0","0p833_1_0p167_0","0p833_1_0p167_0"],"t":23,"s":[97,97,100],"e":[87,87,100]},{"i":{"x":[0.833,0.833,0.833],"y":[1,1,1]},"o":{"x":[0.167,0.167,0.167],"y":[0,0,0]},"n":["0p833_1_0p167_0","0p833_1_0p167_0","0p833_1_0p167_0"],"t":25,"s":[87,87,100],"e":[90,90,100]},{"t":30}],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,-35.623],[35.622,0],[0,35.622],[-35.622,0]],"o":[[0,35.622],[-35.622,0],[0,-35.623],[35.622,0]],"v":[[64.5,0],[0,64.5],[-64.5,0],[0,-64.5]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":0,"k":[1,1,1,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[228.5,184.5],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Group 1","np":2,"cix":2,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":20,"op":60,"st":-3,"bm":0},{"ddd":0,"ind":4,"ty":4,"nm":"Fingerprint Zuti Outlines","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":1,"k":[{"i":{"x":[0.527],"y":[1.062]},"o":{"x":[0.478],"y":[0]},"n":["0p527_1p062_0p478_0"],"t":0,"s":[90],"e":[0]},{"t":10}],"ix":10},"p":{"a":0,"k":[148.651,96.697,0],"ix":2},"a":{"a":0,"k":[148.651,176.697,0],"ix":1},"s":{"a":1,"k":[{"i":{"x":[0.49,0.49,0.667],"y":[1.476,1.476,1]},"o":{"x":[0.505,0.505,0.333],"y":[-0.2,-0.2,0]},"n":["0p49_1p476_0p505_-0p2","0p49_1p476_0p505_-0p2","0p667_1_0p333_0"],"t":0,"s":[0,0,100],"e":[100,100,100]},{"t":10}],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[15.852,-8.337],[-2.045,1.072],[-16.875,0],[-16.363,-8.172],[2.13,1.073],[18.152,0]],"o":[[-2.045,1.073],[14.574,-7.759],[16.959,0],[0.597,0.329],[-17.386,-8.667],[-18.323,0]],"v":[[-51.977,-69.371],[-47.885,-62.107],[-0.414,-73.746],[47.055,-62.107],[50.976,-69.454],[-0.414,-82]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ind":1,"ty":"sh","ix":2,"ks":{"a":0,"k":{"i":[[13.491,-6.617],[8.482,-11.401],[0,0],[-0.684,1.14],[-11.651,5.7],[-24.588,-11.972],[-7.71,-10.261],[1.371,1.792],[12.851,6.271],[15.299,0]],"o":[[-12.852,6.27],[-1.37,1.873],[1.372,0],[7.711,-10.262],[24.502,-12.053],[11.565,5.618],[1.371,1.874],[-8.482,-11.32],[-13.453,-6.576],[-15.393,0]],"v":[[-44.163,-52.064],[-76.292,-25.434],[-72.779,-19],[-69.438,-20.71],[-40.309,-44.816],[40.223,-44.897],[69.265,-20.955],[76.291,-25.678],[44.164,-52.146],[0.111,-62]],"c":true},"ix":2},"nm":"Path 2","mn":"ADBE Vector Shape - Group","hd":false},{"ind":2,"ty":"sh","ix":3,"ks":{"a":0,"k":{"i":[[11.405,-22.791],[0,-9.803],[-4.203,-10.701],[0.857,2.124],[0,6.371],[-3.345,6.617],[-24.358,0],[0,-30.795],[9.863,0],[0,8.741],[14.58,0],[0,-13.233],[-12.007,-11.354],[-13.636,-3.594],[-0.343,0],[2.317,0.572],[8.148,7.678],[0,13.969],[-9.863,0],[0,-8.74],[-14.581,0],[0,13.234],[39.023,0]],"o":[[-3.86,7.759],[0,11.028],[0.771,2.042],[-5.147,-13.068],[0,-8.495],[10.034,-20.012],[34.306,0],[0,8.741],[-9.863,0],[0,-13.233],[-14.58,0],[0,16.174],[9.35,8.74],[0.342,0.082],[0,0],[-12.092,-3.187],[-10.378,-9.802],[0,-8.74],[9.863,0],[0,13.234],[14.58,0],[0,-35.288],[-27.702,0]],"v":[[-64.701,-4.424],[-70.533,22.042],[-64.272,54.39],[-56.296,51.53],[-62.044,22.042],[-56.982,-0.831],[-0.29,-33.75],[61.89,22.042],[44.051,37.889],[26.211,22.042],[-0.205,-1.974],[-26.621,22.042],[-8.01,64.683],[23.896,81.836],[25.011,82],[26.039,73.913],[-2.007,58.801],[-18.045,21.96],[-0.205,6.114],[17.635,21.96],[44.051,45.976],[70.468,21.96],[-0.29,-42]],"c":true},"ix":2},"nm":"Path 3","mn":"ADBE Vector Shape - Group","hd":false},{"ind":3,"ty":"sh","ix":4,"ks":{"a":0,"k":{"i":[[0,-24.196],[-5.912,-10.021],[-7.455,-7.089],[-1.115,0],[1.629,1.629],[5.482,9.37],[0,11.732],[-22.022,0],[0,-19.715],[-2.399,0],[0,2.282],[26.735,0]],"o":[[0,13.117],[5.742,9.858],[0.772,0.815],[0,0],[-6.598,-6.355],[-5.228,-8.798],[0,-19.715],[22.022,0],[0,2.282],[2.399,0],[0,-24.196],[-26.735,0]],"v":[[-49.533,21.912],[-40.536,57.27],[-23.312,78.778],[-20.313,80],[-17.143,72.994],[-32.994,53.277],[-40.964,21.912],[-1.033,-13.853],[38.898,21.912],[43.183,25.986],[47.467,21.912],[-1.033,-22]],"c":true},"ix":2},"nm":"Path 4","mn":"ADBE Vector Shape - Group","hd":false},{"ind":4,"ty":"sh","ix":5,"ks":{"a":0,"k":{"i":[[0,-2.276],[-12.87,-8.213],[-10.278,0],[-4.923,0.895],[2.332,-0.406],[2.074,0],[6.131,3.903],[0,11.466],[2.419,0]],"o":[[0,14.149],[7.428,4.798],[1.21,0],[2.417,-0.406],[-3.454,0.569],[-8.637,0],[-10.538,-6.668],[0,-2.276],[-2.418,0]],"v":[[-4.533,21.065],[16.023,56.763],[42.799,64],[53.251,63.023],[51.782,54.974],[42.799,55.787],[20.861,50.014],[4.104,21.065],[-0.215,17]],"c":true},"ix":2},"nm":"Path 5","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"mm","mm":1,"nm":"Merge Paths 1","mn":"ADBE Vector Filter - Merge","hd":false},{"ty":"fl","c":{"a":0,"k":[0.902000038297,0.654999976065,0,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[148.684,176.697],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Group 1","np":7,"cix":2,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":60,"st":0,"bm":0}],"markers":[]}

**Comment by emtjoshhart** [comment]
It's because you are using aspectFit, try aspectFill

**Comment by rotemda** [comment]
Hi, I have an issue with jason file I exported with bodymovin.
animation seems to work fine at the beginning but at the end the 2 last elements are crossing behind the pacman.
![image](https://user-images.githubusercontent.com/47501824/53081288-34e35b00-3503-11e9-86a3-72f50801b5c2.png)

How I can solve this? all elements are shapes - see attached files:
[pacman files.zip](https://github.com/airbnb/lottie-web/files/2849086/pacman.files.zip)

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
