### ISSUE TITLE
lottie animation stopped when I loaded the network with AFNetworking?why?

### ISSUE THREAD

**Issue by QYunFat** [airbnb/lottie-ios#555]
## Check these before submitting:
- [] Updated to the latest version of Lottie (2.1.5)
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [] iOS

**Comment by QYunFat** [comment]
lottie animation stopped when I loaded the network with AFNetworking?why?It's been a lot of trouble for me for days and I'm going crazy.help me ,thanyou!

**Comment by buba447** [comment]
Can I have some more information? Hard to debug without any context!

**Comment by Osama92** [comment]
Just implemented viewDidLayoutSubview() method, put the animation within the method and it works fine. Thank you!

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
