### ISSUE TITLE
Set animationProgress to end

### ISSUE THREAD

**Issue by its-micah** [airbnb/lottie-ios#56]
I've been trying to see if I can set the animation to it's end, or 'animationProgress = 1.0', in case I want to see it at it's finished state without having it go through the animation. I know I could just use a still image instead, but is this possible?

**Comment by buba447** [comment]
@its-micah That should work! Are you having an issue?

**Comment by its-micah** [comment]
@buba447 Similar to the #47 , I'm setting the animationProgress to 1, then calling play(). This is all after adding the LAAnimationView to it's superview. When doing this, I'm getting the issue of the animation not appearing at all.

For more context, I'm also adding the LAAnimationView as a subview of an IBOutlet view from a storyboard. See below. Any suggestions or recommendations? 


iconView = LAAnimationView.animationNamed("\(index)")
iconView.frame = animationFrame!
animationView.addSubview(iconView)
iconView.animationProgress = 1.0
iconView?.play(completion: { (true) in
print("done playing")
})

**Comment by buba447** [comment]
@its-micah why are you calling play? What are you hoping to happen here?
You should be able to just set animationProgress to 1 if you want to display the final frame statically.

**Comment by its-micah** [comment]
@buba447 Ahh, my mistake. But by setting animationProgress to 1 and removing play, the final frame still does not display. However, if I set the progress  to 1 asynchronously, the final frame does display statically. It seems to not display if it's set immediately after being added to it's parent view.

**Comment by buba447** [comment]
@its-micah Hey! I finally think i found a fix for this! Please pull the latest master and give it a shot.
Lemme know if it doesn't work.

Heres the fix if you're interest.
https://github.com/airbnb/lottie-ios/pull/91

**Comment by its-micah** [comment]
@buba447 Hey! The fix works like a charm. Thank you!

**Comment by AntonicaAlexandru** [comment]
How could i achieve this in iOS ?

**Comment by mangochen** [comment]
Another issue here. When animationView is subview of tableViewCell's contentView and I scroll the tableview  slowly ,  the animationProgress setting to end  not work.
