### ISSUE TITLE
Can't control progress of animation 

### ISSUE THREAD

**Issue by Alexef910** [airbnb/lottie-ios#561]
Hi guys I have an issue regarding the progress of an animation in Xcode.
My code is this:

```
let animationView = LOTAnimationView(name: "AnimationOne")
animationView.frame = CGRect(x: 100, y: 100, width: 250, height: 250)
animationView.contentMode = .scaleAspectFill

    self.view.addSubview(animationView)
    animationView.play(fromProgress: 0.25, toProgress: 0.5, withCompletion: nil)
```

If I set the last line to "animationView.play()" it works fine, but as soon as I try to control its progress I get an error that says:
"Argument passed to call that takes no arguments"

Does anyone knows how to fix this?

**Comment by buba447** [comment]
How are you trying to change the progress?

**Comment by Alexef910** [comment]
@buba447 , All the way down in this article : http://airbnb.io/lottie/ios.html#swift-examples , there is an example that says " Or you can play just a portion of the animation: " ... But when I add that line to my code It doesn't work. However if I just put "animationView.play()" it works just fine.

**Comment by kontarsoma** [comment]
I have the exact same issue here..

**Comment by buba447** [comment]
Thats how you are playing it.
How are you trying to change the progress?

Can you show me some code?

**Comment by kontarsoma** [comment]
`let endProgress: CGFloat = (1 / 23.03) * 3.05
			foregroundAnimationView.play(fromProgress: 0, toProgress: endProgress, withCompletion: { (completion) in
				if completion {
					print("setting new animationProgress: \(self.animationProgress)")
					self.animationProgress = endProgress
				}
			})`

This is the latest version, but the animation doesn't pause either if I use simply `foregroundAnimation.play(toProgress:completion:)`

**Comment by liaocmq** [comment]
Hi Brandon, I'm trying to control a custom progress bar (advance the animation progress according to the user in queue) but I found only a way in IOS, can you point me out how to do it as I've read all the docs for Android and couldn't find the same as IOS, which can control a portion of the animation. Thank you.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC

**Comment by idevChandra6** [comment]
Looks like we still have similar issue:

>             animationView.play(fromProgress: speedAmmo, toProgress: speedAmmo + 0.1, loopMode: .playOnce, completion: {
>                 self.reloadSquare()
>             })
> 

When I build I see this error: 

> Extra argument 'fromProgress' in call
