### ISSUE TITLE
iOS - Animation loop/"restart" issue on 2.5.0. (Animation works on 2.1.5)

### ISSUE THREAD

**Issue by Kostykins** [airbnb/lottie-ios#562]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [x] Regression (Something that once worked, but doesn't work anymore)
(works on 2.1.5)

## What Platform are you on? 

- [] MacOS
- [x] iOS

## Expected Behavior 

Animation loops as expected. 
(gif restarts so it looks a little weird, but the full animation is there)
![2 1 5](https://user-images.githubusercontent.com/6924795/36568458-b35e9e54-17ef-11e8-8f5c-78a8e940928f.gif)

## Actual Behavior

Animation "restarts" mid-loop, and is much faster.
(gif restarts so it looks a little weird, but the full animation is there)
![2 5 0](https://user-images.githubusercontent.com/6924795/36568466-b9c87b84-17ef-11e8-8116-a1cd0a2aeb56.gif)

## Code Example
`self.pulsingBeacon.frame = CGRect(x: 3, y: 3, width: 30, height: 30)`
`self.pulsingBeacon.animationProgress = 0.6 // animation paused state, icon only animates if certain criteria are met`
`self.pulsingBeacon.loopAnimation = true`
`self.pulsingBeacon.contentMode = .scaleAspectFit`
`self.pulsingBeacon.play()`

## Animation JSON

{"v":"5.1.7","fr":29.9700012207031,"ip":0,"op":27.0000010997325,"w":115,"h":100,"nm":"Comp 3","ddd":0,"assets":[],"layers":[{"ddd":0,"ind":1,"ty":4,"nm":"Geofence-Icon-Top Outlines","sr":0.55,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":1,"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":0,"s":[57.5,48,0],"e":[57.5,54,0],"to":[0,1,0],"ti":[0,0,0]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":16,"s":[57.5,54,0],"e":[57.5,48,0],"to":[0,0,0],"ti":[0,1,0]},{"t":29.900001217852}],"ix":2},"a":{"a":0,"k":[49,45,0],"ix":1},"s":{"a":1,"k":[{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"n":["0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167"],"t":0.2,"s":[140.556,140.556,100],"e":[155.556,155.556,100]},{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"n":["0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167"],"t":16,"s":[155.556,155.556,100],"e":[140.556,140.556,100]},{"t":29.900001217852}],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[1.131,-2.707],[2.756,-4.635],[1.737,-2.804],[0.811,1.351],[0.648,1.144],[1.049,5.152],[-9.307,-0.06],[-0.187,-8.739]],"o":[[-2.126,5.06],[-1.689,2.836],[-0.829,1.34],[-2.533,-4.236],[-2.495,-4.42],[-2.168,-10.687],[9.391,0.056],[0.055,2.459]],"v":[[15.91,-0.224],[7.484,13.625],[2.35,22.088],[-1.12,22.051],[-8.82,9.096],[-15.368,-4.759],[0.84,-23.368],[17.48,-8.017]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ind":1,"ty":"sh","ix":2,"ks":{"a":0,"k":{"i":[[0,3.662],[3.663,0],[0,-3.663],[-3.663,0]],"o":[[0,-3.663],[-3.663,0],[0,3.662],[3.663,0]],"v":[[7.533,-6.78],[0.896,-13.415],[-5.739,-6.78],[0.896,-0.145]],"c":true},"ix":2},"nm":"Path 2","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":0,"k":[0.999999940162,0.999999940162,1,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[45.84,36.119],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Group 1","np":3,"cix":2,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":-2.00000008146167,"op":29.900001217852,"st":-1.45000005905971,"bm":0},{"ddd":0,"ind":2,"ty":4,"nm":"Geofence-Icon-Bottom Outlines","sr":0.55,"ks":{"o":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":5.15,"s":[0],"e":[100]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":5.7,"s":[100],"e":[100]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":18.9,"s":[100],"e":[0]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":22.75,"s":[0],"e":[0]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":36.5,"s":[0],"e":[100]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":37.05,"s":[100],"e":[100]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":47.5,"s":[100],"e":[0]},{"t":52.4500021363323}],"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[53,72,0],"ix":2},"a":{"a":0,"k":[46,54,0],"ix":1},"s":{"a":1,"k":[{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"n":["0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167"],"t":5.7,"s":[63.556,63.556,100],"e":[111.837,111.837,100]},{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"n":["0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167"],"t":20,"s":[111.837,111.837,100],"e":[63.556,63.556,100]},{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"n":["0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167"],"t":37.05,"s":[63.556,63.556,100],"e":[166.556,166.556,100]},{"t":52.4500021363323}],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,-5.381],[-7.378,-2.153],[-8.295,0],[-5.932,1.728],[0,4.111],[8.078,0.906],[0,0],[0.683,-0.654],[0,-0.956],[-1.699,-0.195],[-0.162,-0.278],[0,0],[0,0],[16.372,0],[1.606,1.314],[0,0],[0,0],[-8.454,1.357],[0.07,1.695],[0.68,0.604],[0.737,0],[0.152,-0.019]],"o":[[0,4.111],[5.932,1.728],[8.294,0],[7.378,-2.153],[0,-8.039],[0,0],[-0.893,-0.106],[-0.663,0.634],[0,1.725],[10.992,1.255],[0,0],[0,0],[-1.516,1.685],[-16.572,0],[0,0],[0,0],[0.948,-0.813],[1.642,-0.265],[-0.046,-0.952],[-0.571,-0.501],[-0.149,0],[-12.203,1.938]],"v":[[-33.177,-0.467],[-22.06,8.973],[0,11.654],[22.059,8.973],[33.177,-0.467],[14.362,-11.549],[14.359,-11.549],[11.92,-10.708],[10.871,-8.204],[13.851,-4.837],[26.763,-0.819],[26.883,-0.618],[26.727,-0.452],[0,4.926],[-26.492,-0.142],[-26.778,-0.377],[-26.495,-0.616],[-13.971,-4.816],[-11.168,-8.31],[-12.309,-10.756],[-14.333,-11.529],[-14.787,-11.495]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":0,"k":[0.999999940162,0.999999940162,1,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[46.737,64.132],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Group 1","np":2,"cix":2,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":-2.00000008146167,"op":29.900001217852,"st":-1.45000005905971,"bm":0},{"ddd":0,"ind":3,"ty":4,"nm":"Geofence-Icon-Bottom-Right Outlines 3","sr":0.55,"ks":{"o":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":20,"s":[0],"e":[100]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":20.55,"s":[100],"e":[0]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":32.1,"s":[0],"e":[0]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":43.1,"s":[0],"e":[100]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":43.65,"s":[100],"e":[0]},{"t":56.300002293146}],"ix":11},"r":{"a":0,"k":-181,"ix":10},"p":{"a":1,"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":20,"s":[78.35,91.955,0],"e":[89.85,101.955,0],"to":[1.91666662693024,1.66666662693024,0],"ti":[0,0,0]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":32.65,"s":[89.85,101.955,0],"e":[78.35,91.955,0],"to":[0,0,0],"ti":[0,0,0]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":43.65,"s":[78.35,91.955,0],"e":[89.85,101.955,0],"to":[0,0,0],"ti":[-1.91666662693024,-1.66666662693024,0]},{"t":56.300002293146}],"ix":2},"a":{"a":0,"k":[49,45,0],"ix":1},"s":{"a":1,"k":[{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"n":["0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167"],"t":20,"s":[-77.321,77.321,100],"e":[-128,128,100]},{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"n":["0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167"],"t":32.65,"s":[-128,128,100],"e":[-77.321,77.321,100]},{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"n":["0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167"],"t":43.65,"s":[-77.321,77.321,100],"e":[-128,128,100]},{"t":56.300002293146}],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0.022,0],[0.036,1.358],[-1.38,0.037],[-1.249,2.668],[0.145,0.265],[6.906,0.917],[-0.182,1.368],[-1.368,-0.185],[-3.493,-6.384],[0.85,-1.816],[10.067,-1.688],[0.267,-0.007]],"o":[[-1.35,0],[-0.036,-1.38],[16.526,-0.438],[0.189,-0.405],[-1.67,-3.053],[-1.368,-0.182],[0.182,-1.369],[3.278,0.434],[0.939,1.715],[-1.916,4.094],[-6.926,1.161],[-0.023,0.001]],"v":[[-14.874,12.415],[-17.372,9.981],[-14.938,7.416],[12.03,0.355],[12.036,-0.523],[-7.535,-7.273],[-9.684,-10.08],[-6.878,-12.23],[16.422,-2.923],[16.558,2.475],[-1.251,11.068],[-14.807,12.414]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":0,"k":[0.999999940162,0.999999940162,1,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[48.986,57.638],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Group 1","np":2,"cix":2,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":-2.00000008146167,"op":29.900001217852,"st":-1.45000005905971,"bm":0},{"ddd":0,"ind":4,"ty":4,"nm":"Geofence-Icon-Bottom-Right Outlines 2","sr":0.55,"ks":{"o":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":20,"s":[0],"e":[100]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":20.55,"s":[100],"e":[0]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":32.1,"s":[0],"e":[0]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":43.1,"s":[0],"e":[100]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":43.65,"s":[100],"e":[0]},{"t":56.300002293146}],"ix":11},"r":{"a":0,"k":-181,"ix":10},"p":{"a":1,"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":20,"s":[29.5,91.5,0],"e":[14.5,102,0],"to":[-2.5,1.75,0],"ti":[0,0,0]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":32.65,"s":[14.5,102,0],"e":[29.5,91.5,0],"to":[0,0,0],"ti":[0,0,0]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":43.65,"s":[29.5,91.5,0],"e":[14.5,102,0],"to":[0,0,0],"ti":[2.5,-1.75,0]},{"t":56.300002293146}],"ix":2},"a":{"a":0,"k":[49,45,0],"ix":1},"s":{"a":1,"k":[{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"n":["0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167"],"t":20,"s":[75,75,100],"e":[128,128,100]},{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"n":["0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167"],"t":32.56,"s":[128,128,100],"e":[75,75,100]},{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"n":["0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167"],"t":43.65,"s":[75,75,100],"e":[128,128,100]},{"t":56.2099397894777}],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0.022,0],[0.036,1.358],[-1.38,0.037],[-1.249,2.668],[0.145,0.265],[6.906,0.917],[-0.182,1.368],[-1.368,-0.185],[-3.493,-6.384],[0.85,-1.816],[10.067,-1.688],[0.267,-0.007]],"o":[[-1.35,0],[-0.036,-1.38],[16.526,-0.438],[0.189,-0.405],[-1.67,-3.053],[-1.368,-0.182],[0.182,-1.369],[3.278,0.434],[0.939,1.715],[-1.916,4.094],[-6.926,1.161],[-0.023,0.001]],"v":[[-14.874,12.415],[-17.372,9.981],[-14.938,7.416],[12.03,0.355],[12.036,-0.523],[-7.535,-7.273],[-9.684,-10.08],[-6.878,-12.23],[16.422,-2.923],[16.558,2.475],[-1.251,11.068],[-14.807,12.414]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":0,"k":[0.999999940162,0.999999940162,1,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[48.986,57.638],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Group 1","np":2,"cix":2,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":-2.00000008146167,"op":29.900001217852,"st":-1.45000005905971,"bm":0}],"markers":[]}

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
