### ISSUE TITLE
Mask doesn't show correctly

### ISSUE THREAD

**Issue by liangsharon24** [airbnb/lottie-ios#563]
## Check these before submitting:
- [V] Updated to the latest version of Lottie (2.5.0)
- [V] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [V] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [V] iOS

## Expected Behavior 

![image](https://user-images.githubusercontent.com/12822216/36570014-ff7f86fa-17e4-11e8-850f-1d5c694503ea.png)
I am using mask (add and subtract) to create hollow shape. My files always look fine in lottie preview(web) but act weird on mobile preview app. It would be great if you can help me solve the problem. Thanks!

Here is my AE file
https://drive.google.com/file/d/1GksOrCuGUG7ULJUEdCY6y0bT6wX5yoP3/view?usp=sharing

## Actual Behavior

On lottie preview(Web)
![image](https://user-images.githubusercontent.com/12822216/36570046-17f55eb2-17e5-11e8-845c-49ea853d64d3.png)
It looks fine.

However, the mask looks weird on the iphone preview app.
![img_032e0317dcde-1](https://user-images.githubusercontent.com/12822216/36570081-3d6925ac-17e5-11e8-8849-8226236f8759.jpeg)

## Animation JSON

{"v":"5.1.3","fr":40,"ip":0,"op":140,"w":500,"h":500,"nm":"Comp 1","ddd":0,"assets":[],"layers":[{"ddd":0,"ind":1,"ty":1,"nm":"White Solid 1","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[250,250,0],"ix":2},"a":{"a":0,"k":[250,250,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"hasMask":true,"masksProperties":[{"inv":false,"mode":"a","pt":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0]],"v":[[402.566,141],[131,141],[131,404.715],[402.566,404.715]],"c":true},"ix":1},"o":{"a":0,"k":100,"ix":3},"x":{"a":0,"k":0,"ix":4},"nm":"Mask 1"},{"inv":false,"mode":"s","pt":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0]],"v":[[380.895,167],[150,167],[150,376.871],[380.895,376.871]],"c":true},"ix":1},"o":{"a":0,"k":100,"ix":3},"x":{"a":0,"k":0,"ix":4},"nm":"Mask 2"}],"sw":500,"sh":500,"sc":"#ffffff","ip":0,"op":140,"st":0,"bm":0}],"markers":[]}

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
