### ISSUE TITLE
memory not leak

### ISSUE THREAD

**Issue by indenpendman** [airbnb/lottie-ios#565]
## Check these before submitting:
- [] Updated to the latest version of Lottie (2.5.0)
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [] iOS

## Expected Behavior 
memory leak  when  view = nil;

## Actual Behavior
memory not free

## Code Example
    @weakify(self)
    [lottieAnimate playWithCompletion:^(BOOL animationFinished) {
        @strongify(self)
        if (self) {
            [self->lottieAnimate removeFromSuperview];
            self->lottieAnimate = nil;
        }
    }];

**Comment by buba447** [comment]
Im fairly certain you need to call @weakify(self) before the block is executed.

You could try

```
__weak __typeof__(self) weakSelf = self;
[lottieAnimate playWithCompletion:^(BOOL animationFinished) {
    __typeof__(self) strongSelf = weakSelf;
   [strongSelf.lottieAnimate removeFromSuperview];
   strongSelf.lottieAnimate = nil;
}];
```

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
