### ISSUE TITLE
Text font with stroke effect not working on mobile

### ISSUE THREAD

**Issue by heytekro** [airbnb/lottie-ios#566]
Hi I'm working on a logo animation, I used stroke effect on the text logo and it's properly working on Google Chrome or any browsers but unfortunately not on Lottie mobile app. Do you have any idea how can I fix this issue or do I have to use trim paths and trace the text font? Thanks.

**Comment by gpxlBen** [comment]
Hi.  Stroke effect didn't work for me either (iOS).  Trim path works very well though. [This tutorial](https://graphicdesign.stackexchange.com/questions/49643/how-to-use-after-effects-trim-path-with-an-illustrator-path) helped me a lot.

**Comment by heytekro** [comment]
Thanks for the tutorial, @gpxlBen . Here's my sample animation https://www.lottiefiles.com/share/XvxNMC I'll just use trim paths instead.

**Comment by buba447** [comment]
Text support now works in ios
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
