### ISSUE TITLE
Animation glitches in Safari

### ISSUE THREAD

**Issue by itshamy** [airbnb/lottie-ios#567]
My site http://nvelupredesign.wpengine.com has 5 lottie svg animation on the homepage slider. Animation works fine in chrome etc. but glitches in Safari, especially the first and 3rd slide. The first slide's animation has some random glitching white lines on them and the animation is very fast. I've tried setting lottie.setSpeed(10); but it's still too fast.

I'm on a MacOS. This site is WordPress. There's no error in console. Expected behavior is supposed to be smooth like in Chrome. Unexpected behavior is the glitches in Safari. 

I want to slow down animation on slide 1 as well. How do I go about correctly setting it? 

Thanks

**Comment by buba447** [comment]
@itshamy This is the lottie-ios repo. Sounds like you are having an issue with https://github.com/airbnb/lottie-web

Might want to post over there so someone will see it!
