### ISSUE TITLE
How do I return an Unmanaged<CGColor>!

### ISSUE THREAD

**Issue by jlubeck** [airbnb/lottie-ios#568]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)

## What Platform are you on? 

- [x] iOS

I'm trying to implement the new delegates for changing color during an animation, but I can't seem to get my head around it and couldn't find proper documentation about it. 

Examples are only about changing position, but not color. The only example I found for changing color it just says 

```
let colorBlock = LOTColorBlockCallback { (currentFrame, startKeyFrame, endKeyFrame, interpolatedProgress, startColor, endColor, interpolatedColor) -> Unmanaged<CGColor> in
    return aColor
}
```

But doesn't say how that aColor is created.

If I just try to return  `UIColor.white.cgColor` I get an error that says 

Cannot convert return expression of type 'CGColor' to return type 'Unmanaged<CGColor>!'

Thank you

**Comment by chansen22** [comment]
Unmanaged.passRetained(UIColor.red.cgColor) should give back Unmanged<CGColor>!, but the compiler complains about objc ownership.
It looks like there's updated docs on airbnb's website http://airbnb.io/lottie/ios/dynamic.html

I think you're looking for something more like this:
```
let a = LOTAnimationView(name: "progress")
let colorCallback = LOTColorValueCallback(color: UIColor.red.cgColor)
let keypath = LOTKeypath(string: "Key.Path.Your.Designer.Gave.You")
a.setValueDelegate(colorCallback, for: keypath)
a.frame = foodPlanProgressView.frame
addSubview(a)
a.play()
```

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
