### ISSUE TITLE
Feature request. Support gradient strokes

### ISSUE THREAD

**Issue by gerchicov-bp** [airbnb/lottie-ios#569]
https://editor.lottiefiles.com/?src=https://www.lottiefiles.com/download_public/927

```
+[LOTShapeGroup shapeItemWithJSON:]: Warning: gradient strokes are not supported
```

**Comment by RamblinWreck77** [comment]
Commenting to +1 on this, would be really useful! :)

PS: Lottie rocks!

**Comment by MariusRei** [comment]
Still not available while it is supported on Android since 2 years?
+1

**Comment by buba447** [comment]
Updates coming soon!

**Comment by JUSTINMKAUFMAN** [comment]
@buba447 Great work on Lottie! Any sense of ETA on enabling gradient paths in iOS?

**Comment by kaiden-dragon** [comment]
@buba447 Lottie is awesome! Any updates on the gradient paths?

**Comment by buba447** [comment]
Big Update coming soon! Hold tight!

**Comment by buba447** [comment]
You got it! Now supported in Lottie 3.0

Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
