### ISSUE TITLE
Animated composition

### ISSUE THREAD

**Issue by eXhausted** [airbnb/lottie-ios#57]
Hello guys! Nicely done.

I have a question. Does lottie support transforms on composition? Something like on the screenshot:
![screen shot 2017-02-08 at 17 09 10](https://cloud.githubusercontent.com/assets/597039/22743038/8def1bce-ee21-11e6-8761-831bc480511b.png)

If not, are you planning to add it in the nearest future? I could try to do it myself, in case you don't have such plans. I saw some class named LACustomChild, is it related? 

Thanks!

**Comment by eXhausted** [comment]
I've found related issue in android's issues https://github.com/airbnb/lottie-android/issues/61

**Comment by buba447** [comment]
@eXhausted Yes we are working to add pre comp support!

**Comment by buba447** [comment]
Added @eXhausted
