### ISSUE TITLE
Animation restarts the device. (Is it vulnerability in iOS ?)

### ISSUE THREAD

**Issue by mixo44** [airbnb/lottie-ios#570]
Hello!
When I use this animation simulator and device are restarted.
Simulator Version 10.0 (SimulatorApp-835.5 CoreSimulator-494.33) (11.2 (15C107))
iPhone 6S 11.2.1 (15C153)

## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] Updated to the latest version of Lottie (2.5.0)
- [] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [x] iOS

## Animation JSON

{"v":"5.1.1","fr":29.9700012207031,"ip":0,"op":27.0000010997325,"w":300,"h":300,"nm":"Comp 2","ddd":0,"assets":[],"layers":[{"ddd":0,"ind":1,"ty":4,"nm":"Shape Layer 1","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":1,"k":[{"i":{"x":[0.999],"y":[1]},"o":{"x":[0.001],"y":[0]},"n":["0p999_1_0p001_0"],"t":-57,"s":[0],"e":[180]},{"i":{"x":[0.999],"y":[1]},"o":{"x":[0.167],"y":[0]},"n":["0p999_1_0p167_0"],"t":27,"s":[180],"e":[360]},{"i":{"x":[0.833],"y":[1]},"o":{"x":[0.001],"y":[0]},"n":["0p833_1_0p001_0"],"t":71,"s":[360],"e":[480]},{"i":{"x":[0.833],"y":[1]},"o":{"x":[0.167],"y":[0]},"n":["0p833_1_0p167_0"],"t":151,"s":[480],"e":[540]},{"t":171.000006964973}],"ix":10},"p":{"a":0,"k":[150.526,150.344,0],"ix":2},"a":{"a":0,"k":[-2.067,-19.25,0],"ix":1},"s":{"a":1,"k":[{"i":{"x":[0.48,0.48,0.48],"y":[1,1,1]},"o":{"x":[0.26,0.26,0.26],"y":[0.556,0.556,0]},"n":["0p48_1_0p26_0p556","0p48_1_0p26_0p556","0p48_1_0p26_0"],"t":-62,"s":[100,100,100],"e":[140,140,100]},{"i":{"x":[0.833,0.833,0.833],"y":[1,1,1]},"o":{"x":[0.167,0.167,0.167],"y":[0,0,0]},"n":["0p833_1_0p167_0","0p833_1_0p167_0","0p833_1_0p167_0"],"t":-57,"s":[140,140,100],"e":[140,140,100]},{"i":{"x":[0.833,0.833,0.833],"y":[1,1,1]},"o":{"x":[0.167,0.167,0.167],"y":[0,0,0]},"n":["0p833_1_0p167_0","0p833_1_0p167_0","0p833_1_0p167_0"],"t":22,"s":[140,140,100],"e":[100,100,100]},{"i":{"x":[0.48,0.48,0.48],"y":[1,1,1]},"o":{"x":[0.167,0.167,0.167],"y":[0,0,0]},"n":["0p48_1_0p167_0","0p48_1_0p167_0","0p48_1_0p167_0"],"t":27,"s":[100,100,100],"e":[100,100,100]},{"i":{"x":[0.48,0.48,0.48],"y":[1,1,1]},"o":{"x":[0.26,0.26,0.26],"y":[0.556,0.556,0]},"n":["0p48_1_0p26_0p556","0p48_1_0p26_0p556","0p48_1_0p26_0"],"t":66,"s":[100,100,100],"e":[140,140,100]},{"t":71.0000028918893}],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"d":1,"ty":"el","s":{"a":0,"k":[180,180],"ix":2},"p":{"a":0,"k":[0,0],"ix":3},"nm":"Ellipse Path 1","mn":"ADBE Vector Shape - Ellipse","hd":false},{"ty":"st","c":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":22,"s":[0.258823543787,0.819607853889,0.521568655968,1],"e":[0.937254905701,0.372549027205,0.443137258291,1]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":27,"s":[0.937254905701,0.372549027205,0.443137258291,1],"e":[0.937254905701,0.372549027205,0.443137258291,1]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":66,"s":[0.937254905701,0.372549027205,0.443137258291,1],"e":[0.258823543787,0.819607853889,0.521568655968,1]},{"t":70.0000028511585}],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":2,"ix":5},"lc":1,"lj":1,"ml":4,"d":[{"n":"d","nm":"dash","v":{"a":1,"k":[{"i":{"x":[0.48],"y":[1]},"o":{"x":[0.26],"y":[1]},"n":["0p48_1_0p26_1"],"t":-62,"s":[0],"e":[90]},{"i":{"x":[0.48],"y":[1]},"o":{"x":[0.26],"y":[0]},"n":["0p48_1_0p26_0"],"t":-61,"s":[90],"e":[90]},{"i":{"x":[0.833],"y":[1]},"o":{"x":[0.167],"y":[0]},"n":["0p833_1_0p167_0"],"t":-57,"s":[90],"e":[90]},{"i":{"x":[0.833],"y":[1]},"o":{"x":[0.167],"y":[0]},"n":["0p833_1_0p167_0"],"t":26,"s":[90],"e":[0]},{"i":{"x":[0.48],"y":[1]},"o":{"x":[0.167],"y":[0]},"n":["0p48_1_0p167_0"],"t":27,"s":[0],"e":[0]},{"i":{"x":[0.48],"y":[1]},"o":{"x":[0.26],"y":[1]},"n":["0p48_1_0p26_1"],"t":66,"s":[0],"e":[90]},{"i":{"x":[0.48],"y":[1]},"o":{"x":[0.26],"y":[0]},"n":["0p48_1_0p26_0"],"t":67,"s":[90],"e":[90]},{"t":71.0000028918893}],"ix":1}},{"n":"o","nm":"offset","v":{"a":0,"k":0,"ix":7}}],"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"fl","c":{"a":0,"k":[0,0,0,1],"ix":4},"o":{"a":0,"k":0,"ix":5},"r":1,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[-2.594,-19.594],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Ellipse 1","np":3,"cix":2,"ix":1,"mn":"ADBE Vector Group","hd":false},{"ty":"tm","s":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":151,"s":[0],"e":[90]},{"t":171.000006964973}],"ix":1},"e":{"a":0,"k":100,"ix":2},"o":{"a":0,"k":0,"ix":3},"m":1,"ix":2,"nm":"Trim Paths 1","mn":"ADBE Vector Filter - Trim","hd":false}],"ip":0,"op":27.0000010997325,"st":-123.000005009893,"bm":0}],"markers":[]}

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
