### ISSUE TITLE
Get lottie layer frame in relation to it's UIView superview

### ISSUE THREAD

**Issue by oojojjeoo** [airbnb/lottie-ios#571]
Hey.
Is there a way to get the lottie layer frame in relation to it's UIView superview?

In other words: Where is the after effects layer in the UIView superview as a CGRect.

I've tried this: 
CGRect test = [lottie convertRect: ani.lottieLogoFrame1 fromKeypathLayer: [LOTKeypath keypathWithString:@"Background"]];

where the lottieLogoFrame1 is the After effects coordinate space layer position at a specific frame and the "Background" is the filled size of the LOTView in after effects coordinate space. This gives me the right X value, width and height but the wrong Y value. Y is always the center in the UIView coordinate space.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

Should now work in Lottie 3.0

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC

**Comment by carlostrianag** [comment]
@oojojjeoo did you manage to solve this?

**Comment by oojojjeoo** [comment]
No not more than I posted in this post. I add the Y value manually for each view that is not centered. Works, but it's a bit of a hassle. I'm using an old version of lottie though so not sure if this has changed in later versions.
