### ISSUE TITLE
Expression not Supporting in lottie-ios

### ISSUE THREAD

**Issue by Piedistrict** [airbnb/lottie-ios#574]
Dear Team,

We implemented Expression in After Effects and its working fine, the same needs to be in ios also.Below code is not working in ios swift when implemented through lottie framework

thisComp.layer("Null 1").transform.rotation*-1

Please suggest the other way of doing the transform rotation

**Comment by louisscott** [comment]
If you select the layer you have the expression in and go to 'animation - keyframe assistant - convert expressions to keyframes' it should work!

**Comment by Piedistrict** [comment]
it is helpful.
Thanks for help.
