### ISSUE TITLE
Repeater not working, help!

### ISSUE THREAD

**Issue by louisscott** [airbnb/lottie-ios#575]
I'm using the repeater to duplicate a line 6 times onto a book page, along with trim paths to then make it look like they're being written onto the page. However once it's exported to Lottie it only shows the one line being drawn (the lines being made by the repeater aren't being drawn).

Is there a way to either convert the repeated lines into shapes in the same group as the original, or a temp fix for now?

Much appreciated!

- [] Non-Crashing Bug (Visual or otherwise)

## What Platform are you on? 
- [] iOS

**Comment by rodrigoelp** [comment]
I had the same issue... had to copy each shape and apply an animation manually. (I've applied comments here #699)

**Comment by r1kut0desu** [comment]
Me too.
I'm addicted to being fixed soon. Please!!

**Comment by ra1028** [comment]
I'm in same here. 

We using repeater for duplicate elements beyond human managing.
Inability to use it is a big issue for us.

**Comment by buba447** [comment]
Repeater is not yet working in 3.x.x

Repeater is partially supported in 2.5.x

**Comment by ra1028** [comment]
@buba447 
ok, thanks.
Do you have plans to support it in the future?

**Comment by buba447** [comment]
Yes absolutely! 
It wasnt adapted from objective c to swift because the objective c implementation only halfway supported the feature. I plan to add full repeater support to swift. I currently dont have a timeline on this though, as work is happening in my free time. Ill be sure to keep you posted.

**Comment by ra1028** [comment]
That's great news :+1:
We are expectantly waiting for that.
Thanks.

**Comment by kylebrowning** [comment]
Add another user to this list. :(

**Comment by dtsantiago** [comment]
some here :(

**Comment by TimiOSdev** [comment]
plus 1

**Comment by kylebrowning** [comment]
@buba447 Is there any reason Repeaters are not listed as an Unsupported feature in the documentation?

Is there any time line on when this issue will get fixed in 3.x? Desperately want to upgrade.

**Comment by kylebrowning** [comment]
@buba447 totally understand on the time thing. Thanks for responding so quickly!

**Comment by thehomme** [comment]
Just wondering if there's an update on this? Working with XCode and not having this feature from AE is really tough

**Comment by Kondamon** [comment]
Any news regarding repeater? They are still broken on iOS.

**Comment by theorosendorf** [comment]
Plus 1

**Comment by 778477** [comment]
Plus 1

**Comment by colderoshay** [comment]
I just discovered a solution using a custom script to bake the repeaters. 

Works on Android AND iOS 🍾 

https://github.com/ae-scripting/shapeRepeaterBaker?tab=readme-ov-file
