### ISSUE TITLE
Lottie animation is not showing properly

### ISSUE THREAD

**Issue by mehtavatsal** [airbnb/lottie-ios#578]
## This issue is a:
Lottie animation is not showing properly in Xcode. Means we tried to see in phone simulator, but animation is not showing properly as I have made in aftereffect. 

## What Platform are you on? 

- [] MacOS
- [] iOS

## Animation JSON

[Like-45_V2.zip](https://github.com/airbnb/lottie-ios/files/1801427/Like-45_V2.zip)

**Comment by buba447** [comment]
Animation uses expressions, which arent supported by lottie-ios. Try baking the expression to keyframes or manually keyframing the scale property.

**Comment by mehtavatsal** [comment]
Hello Brandon,
I tried baking the expression to keyframes and it worked as good as expression.
Thanks for the help!
