### ISSUE TITLE
Cannot access pathForResource from Assets catalog

### ISSUE THREAD

**Issue by MaximKeegan** [airbnb/lottie-ios#580]
## Check these before submitting:
- [+] Updated to the latest version of Lottie (2.5.0)
- [+] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [+] This issue isn't related to another open issue

## This issue is a:
- [+] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [+] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [+] iOS

## Code Example

2.1.5 code
```
NSArray *components = [asset.imageName componentsSeparatedByString:@"."];
image = [UIImage imageNamed:components.firstObject inBundle:asset.assetBundle compatibleWithTraitCollection:nil];
```
2.5.0 Code
```
NSString *imagePath = [asset.assetBundle pathForResource:asset.imageName ofType:nil];
image = [UIImage imageWithContentsOfFile:imagePath];
```
When using image inside assets catalog, pathForResource return nil in LOTLayerContainer line 164.
Can anyone help to resolve issue?

**Comment by MaximKeegan** [comment]
Related to comment https://github.com/airbnb/lottie-ios/issues/517#issuecomment-370622730

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
