### ISSUE TITLE
Weird shaking issue

### ISSUE THREAD

**Issue by RamblinWreck77** [airbnb/lottie-ios#581]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 
- [] MacOS
- [x] iOS

## Expected Behavior 
This file looks smooth on web/android, but some of the scaled letters jump/shake on iOS. 
https://www.lottiefiles.com/share/mcG1Tw

## Actual Behavior
Smooth scaling just like you see on the web/android versions.

## Code Example
See the JSON file

## Animation JSON
https://www.lottiefiles.com/share/mcG1Tw

Is this a lottie iOS bug? I can provide the .aep file for this if it would help. 

Thank you so much for any help in advance!

**Comment by mas-iota** [comment]
Is this resolved? The same issue still occurring on iPhone browsers. But working fine on desktop browsers. Will test it on Android and see what happens.
