### ISSUE TITLE
Animation works on web but not on iOS sample app

### ISSUE THREAD

**Issue by SamMcNeilly** [airbnb/lottie-ios#583]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [x] iOS

## Expected Behavior 
Animation works for both HTML sample and iOS sample app.

## Actual Behavior
Animation only displays correctly on web. On iOS, it appears totally blank.

## Code Example
I've added the JSON file to the Lottie sample app bundle and am attempting to preview it in that way.

## Animation JSON
[Lottie tick green 2.zip](https://github.com/airbnb/lottie-ios/files/1815283/Lottie.tick.green.2.zip)

**Comment by nyeu** [comment]
Hey @SamMcNeilly , I checked your file in the iOS Lottie Preview app and is blank as well, I believe there's an issue with the JSON. I had an issue that my animation was being shown perfectly on the web but not on the app. The designer changed it and now works. I recommend you to always check it with the lottie Preview app, if it works there it should work in your app.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
