### ISSUE TITLE
Trim path animation timing incorrect

### ISSUE THREAD

**Issue by anaiszm** [airbnb/lottie-ios#585]
Hi,

I'm having problems with my trim path animations rendering correctly. The timing of when the paths are draw in  isn't correct. I made sure that the Trim Multiple Shapes setting is set to simultaneously and I'm unsure what else I might be doing incorrectly. 

Thanks for your help!

## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [x] iOS

## Expected Behavior 
https://www.dropbox.com/s/x5hoyfseewx72ci/LoadingLoop_Expected.mov?dl=0

## Actual Behavior
https://www.dropbox.com/s/x5hoyfseewx72ci/LoadingLoop_Expected.mov?dl=0

## Animation JSON
https://www.dropbox.com/s/h8ahnzif2c7pqfi/LoadingLoop6.json?dl=0

## After Effects File
https://www.dropbox.com/s/6toqpopwm90cxj1/LoadingLoop.aep?dl=0

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
