### ISSUE TITLE
Animation not working properly in iOS

### ISSUE THREAD

**Issue by aaasifrz9** [airbnb/lottie-ios#587]
I have added JSON file in the app and added same as in the sample. 
**Issue:** All lines are not showing around the circle. Only a single line is showing in animation.

I have attached sample project, HTML file, and JSON file.

Please suggest what I am missing in implementation.
Thanks in advance.

[LottieAnimationSamples.zip](https://github.com/airbnb/lottie-ios/files/1823646/LottieAnimationSamples.zip)
[Animation files.zip](https://github.com/airbnb/lottie-ios/files/1823647/Animation.files.zip)

**Comment by buba447** [comment]
Are you using expressions to set the rotations of the other rays of light, or is it a shape repeater?

**Comment by aaasifrz9** [comment]
Hi @buba447 ,

I have created below attached file and animation is not working properly.
Please help, what I am missing in implementation.

[sunny.aep.zip](https://github.com/airbnb/lottie-ios/files/1837625/sunny.aep.zip)

Thanks in advance.

**Comment by aaasifrz9** [comment]
Hi @buba447 , 

Can you please check my sample attached in above comment that what am I missing in implementation? So it only showing a single line outside of circle. Actually it should show as like as in animation attached.
Please help. 
Thanks in advance.

**Comment by buba447** [comment]
Ahh its becuase you are using difference masks to make the animation. Lottie-ios doesnt support difference masks yet. This type of animation should be done with shapes. You cant copy your mask shapes and turn them into shape layers pretty easily though. Here is a file that has the sun mask converted into shape layers for example.


[ClearSky_Shapes.zip](https://github.com/airbnb/lottie-ios/files/1842560/ClearSky_Shapes.zip)

**Comment by aaasifrz9** [comment]
Thanks for the quick reply @buba447 .

I have tried above provided JSON file in above `LottieAnimationSamples.zip` and it is not animating, showing idle.
After effect file: I am not able to open to see the composition because it is created in After Effect 15.0.1 and I am using After Effect CC 14.1.0.57.

I'll try to create it as described above and let you know.
Thanks again.

**Comment by rodrigoelp** [comment]
I think this issue is related to #699

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
