### ISSUE TITLE
Animation synchronized with transition progress for no reason

### ISSUE THREAD

**Issue by denisPoifol** [airbnb/lottie-ios#591]
Hello I am having the following issue when I dismiss interactively a viewController the animation does not run but instead update itself with the transitionCoodinator or so it seems like it.
This only happen on iOS 10

this following testProject highlights the issue.
[LottieTest.zip](https://github.com/airbnb/lottie-ios/files/1828288/LottieTest.zip)

To test it you just have to press the button to present a new viewController and interactively dismiss it : on ios11 the loadingView do play the animation while on ios10 the animathie is progressing accordingly to the progress of the transition between viewControllers
We would expect it to behave like it does on iOS11 and play the animation as requested.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
