### ISSUE TITLE
1 block of code for alternate onboard animations

### ISSUE THREAD

**Issue by samiam2017** [airbnb/lottie-ios#593]
Is it possible to use one block of code that will treat two animations of varying lengths consistently? 

I would like to test a few different versions of an onboarding animation without having to do a new app release or have the dev need to make custom code updates.

Example would be  have an animation that has 4 to 5 segments that progress and hold based on a user swiping. And then be able to switch out that animation  as a simple asset switch with another version that might have only 2 to 3 segments. 

Is it possible to embedding elements or markers in the after effects comp (naming layers by classes or ids) and then use 1 block of code that will maintain consistent functionality on these json files with different structures and lengths (2 segments or 5 segments, and etc.) because it is saying play till you hit next marker. 

Goal is to get playback behavior based on the existence of a marker rather than a specific frame number or proportionality of clip. That way you can switch out multiple test animations and get consistent behavior without having to go back into code.

**Comment by buba447** [comment]
Marker support is in the works!

**Comment by buba447** [comment]
Now supported!

Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
