### ISSUE TITLE
Changing image path

### ISSUE THREAD

**Issue by binnari1120** [airbnb/lottie-ios#594]
Could somebody show how to change images with Swift? The developer says the library already supports image, but I am having a hard time getting the examples..

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
