### ISSUE TITLE
Distort animation

### ISSUE THREAD

**Issue by henriqrossatto** [airbnb/lottie-ios#595]
Hi guys!
I'm a lottie animation and the dev that works with me report this problem. When he insert the animation on code, the animation distort. I would like to know if this problem is when I export the lottie file on After Effects or is on coding. And how could we solve this.

When I export this, the size on comp was 1080*1280. I reexported the animations in 1:1 to see if this will be solve. So, I will update you later.

![6cc905fe-43bf-406b-9bd5-54c71fd81c70](https://user-images.githubusercontent.com/30601233/37983509-13c51aa4-31ca-11e8-805a-c1f963cbbfb7.jpg)
![cdcf0829-96b8-4053-aeab-90a680f9b09e](https://user-images.githubusercontent.com/30601233/37983511-13eac222-31ca-11e8-8c8b-1b7798b2c101.jpg)
![5ba6e7a4-b0fa-4c6d-9762-88d39e86c433](https://user-images.githubusercontent.com/30601233/37983512-1410bd38-31ca-11e8-809f-50ae71611ce4.jpg)
![2f35e93c-5176-4ab8-9b8c-5bf82a772cfe](https://user-images.githubusercontent.com/30601233/37983513-1437e052-31ca-11e8-9ec1-3073399b3fd7.jpg)

**Comment by nyeu** [comment]
Hey @henriqrossatto , how is your developer adding the animation? You can tell him to try to set contentMode to .scaleAspectFit. As Lottie animation are vectorised, it just adjusts to the size of the full view, adding the scale Aspect Fit, will resize at it maximum but always respecting the aspect ratio.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
