### ISSUE TITLE
Can we load json and images from remote server to render animation in iOS?

### ISSUE THREAD

**Issue by kanakaraju043** [airbnb/lottie-ios#600]
## Check these before submitting:
- [] Updated to the latest version of Lottie (2.5.0)
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [] iOS

**Comment by kanakaraju043** [comment]
Can we load json and images from remote server to render lottie animations in iOS?

**Comment by nemoleo** [comment]
yes，I'm using the lib just like this

**Comment by kanakaraju043** [comment]
Can i see sample code for that

**Comment by kanakaraju043** [comment]
Hello Lee,

I added code for load images from remote server to render dynamic lottie json animations in iOS from remote server.

Could you please review and commit on lottie frame work

**Comment by buba447** [comment]
Theres already code in the framework for that 
https://github.com/airbnb/lottie-ios/blob/master/lottie-ios/Classes/PublicHeaders/LOTAnimationView.h#L38

**Comment by fmricky** [comment]
@buba447 These do not support remote images resource rendering. Just support only JSON file resource.

**Comment by bhavukjain1** [comment]
Hi @premyslvlcek. Have you got any possible solution for loading the images directly from the URL? Any help is appreciated.

**Comment by kanakaraju043** [comment]
yes , i modified few methods in lottie library to get it work.


Thanks,
kanakaraju

**Comment by premyslvlcek** [comment]
Hey @bhavukjain1, feel free to check my fork of this library, which adds support for loading images from dictionary. The key in the dictionary is the name of the image in the lottie json, for example img_01.png. The code is not final, but it works. It doesn’t support loading from the url, but you can load the image from the remote url yourself and then put it into the dictionary. https://github.com/premyslvlcek/lottie-ios/tree/imagesOutsideBundles?files=1

**Comment by bhavukjain1** [comment]
Hey @premyslvlcek. Great work! Works perfectly, thanks.

**Comment by SantiagoGaleano** [comment]
Does anyone know how to load json files from firebase
