### ISSUE TITLE
Brandon Withrow email id is not working

### ISSUE THREAD

**Issue by Vivek-gamer** [airbnb/lottie-ios#601]
I tried to reach brandon.withrow@airbnb.com, it's not working. is there any other way to reach him?

**Comment by buba447** [comment]
Hello!
My email is brandon@withrow.io
My GitHub is buba447 and my email is on there too. Where did you find the old email so I can fix it?

Godspeed,
Brandon

**Comment by Vivek-gamer** [comment]
While clicking on your name in "https://github.com/airbnb/lottie-ios#issues-or-feature-requests", its showing your old mail id.

**Comment by buba447** [comment]
Fixed it! Thanks for the heads up
