### ISSUE TITLE
Cocoapods 1.5.0 static support

### ISSUE THREAD

**Issue by RamblinWreck77** [airbnb/lottie-ios#602]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [x] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [x] iOS

Hello! When you update to cocoapods 1.5.0 you have the option to remove use_frameworks! from your podfile. This greatly improves the launch speed of your app. 

Unfortunately lottie-ios-umbrella.h fails with "LOTAnimatedControl.h" file not found when attempting to do this. 

This is the only pod I use that has this issue and is preventing me from upgrading, so a fix would be greatly appreciated :)

Thanks again for an awesome tool!!!

**Comment by taglia3** [comment]
Hi, any updates on this feature request?

**Comment by JoeSzymanski** [comment]
I've been looking into this, and I'm starting to think this is a Cocoapods issue rather than a lottie issue. First, all of the headers in the umbrella can't be found.

That being said, in looking at the generated files and folders when using lottie as a static framework rather than a dynamic framework, the lottie header files are placed in a completely different folder than the umbrella header, and in a subdirectory of that separate folder.

Other libraries I've seen either have all of the public headers in the same folder as the umbrella header, or the secondary folder contains the headers with no subdirectories.

I'll update here if I can figure anything else out.

**Comment by JoeSzymanski** [comment]
Opened an issue with Cocoapods, as it looks like this could be an issue on their end: https://github.com/CocoaPods/CocoaPods/issues/7751

**Comment by markuswinkler** [comment]
try installing cocoapods from this commit hash:
89a273882d75f42e51e486410dbab4fc15292a09

This one works for me.

**Comment by JoeSzymanski** [comment]
@RamblinWreck77 I was able to get things building and running using the latest beta. I was not trying to mix static and dynamic pods, however, just change from 100% dynamic to 100% static.

**Comment by rustyshelf** [comment]
I also tried on Cocoapods 1.6.0.beta.1 and removing `use_frameworks!` from my Podfile. Deleted all the pods then did a clean `pod install`. It doesn't work for me, Lottie is still unrecognised in the project.

**Comment by kyle-fox** [comment]
Same situation as @rustyshelf here - would love a fix for this to take advantage of the improved launch times

**Comment by canalesb93** [comment]
I just tried `1.6.0.beta.2` and can confirm it's working now.

**Comment by chuganzy** [comment]
CocoaPods 1.6.0 is out! Check it out. I guess we can close this issue.

**Comment by rustyshelf** [comment]
This still isn't working for me in the released version of CocoaPods 1.6.0. Are there any other config changes I need to be making?

**Comment by chuganzy** [comment]
@rustyshelf Can you share the error log you got?

**Comment by rustyshelf** [comment]
Adding `use_modular_headers!` to my Podfile fixed the issue.

**Comment by chuganzy** [comment]
@rustyshelf Yeah, that's the step needed to use libraries in the same way as frameworks, since CocoaPods by default does not generate module maps.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
