### ISSUE TITLE
A Crash Bug Happen when using the lottie-ios, please help to fix it.

### ISSUE THREAD

**Issue by nemoleo** [airbnb/lottie-ios#603]
## Check these before submitting:
- [y] Updated to the latest version of Lottie (2.5.0)
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [y] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [y] iOS

## Actual Behavior

![b6698e18-284e-4747-ab09-afd6c5d9bf52](https://user-images.githubusercontent.com/7390571/38467523-6d16368c-3b6c-11e8-9db9-62274f01206a.png)

## Code Example

      `NSError *error;
        NSData *jsonSrc = [DYMarchFansResourcesManager dataWithContentsOfFileName:@"bloody.json"];
        NSDictionary *dic = [NSJSONSerialization JSONObjectWithData:jsonSrc options:NSJSONReadingAllowFragments error:&error];
        if (!error && dic) {
            LOTAnimationView *blood = [LOTAnimationView animationFromJSON:dic];
            [blood setContentMode:UIViewContentModeScaleAspectFit];
            blood.loopAnimation = YES;
            [blood setFrame:CGRectMake(5.f, 30.f, CGRectGetWidth(self.bounds) - 10.f , CGRectGetHeight(self.bounds) - 35.f)];
            blood.tag = DANGERVTAG;
            [self insertSubview:blood atIndex:0];
            [blood play];
        }`

## Animation JSON

[bloody.json.zip](https://github.com/airbnb/lottie-ios/files/1887456/bloody.json.zip)

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
