### ISSUE TITLE
Can you please fix it as I found dead link URL ?

### ISSUE THREAD

**Issue by Shinproxy** [airbnb/lottie-ios#604]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [ ] MacOS
- [x] iOS

## Code Example
```
https://github.com/airbnb/lottie-ios/blob/master/lottie-ios/Classes/Extensions/UIColor+Expanded.m
```

Hello.
I investigate whether other OSS is mixed in this OSS to use ‘lottie-ios’ as follows.
As I found this URL is dead link, can you please fix it?
Thank you.
 ```
// From http://github.com/ars/uicolor-utilities ```

**Comment by Shinproxy** [comment]
Sorry for the additional question.
If you are using another OSS, I want to know what license it is.

**Comment by buba447** [comment]
The original OSS has been removed.

**Comment by Shinproxy** [comment]
Thank you for reply.
I removed this url. Please merge this PR.

https://github.com/airbnb/lottie-ios/pull/614
