### ISSUE TITLE
Dynamic property as upload progress

### ISSUE THREAD

**Issue by astrokin** [airbnb/lottie-ios#606]
## This issue is a:
- [x] Feature Request

## What Platform are you on? 
- [x] iOS

## Expected Behavior 
Can i animate digits (as dynamic property) inside loading indicator [like this](https://cloud.netlifyusercontent.com/assets/344dbf88-fdf9-42bb-adb4-46f01eedd629/5695b1f4-157c-4e43-b60e-ed7c6cae5374/percentdone-opt.jpg)? 
(0..100 will be set as upload progress from owner's `NSURLSessionUploadTask`  `_totalBytesWritten` / `totalBytesExpectedToWrite_` )

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
