### ISSUE TITLE
Animation cached by animationName  

### ISSUE THREAD

**Issue by wongzigii** [airbnb/lottie-ios#609]
## Issue background:

In my project, there are several sets of assets (bundles) for one animation, they are grouped by different colors.

It seems like lottie-ios doesn't provide a template api to reuse an animation for different bundles.

However, I then copy the `animation.json` into each bundle and it indeed works.

![image](https://user-images.githubusercontent.com/7384288/38851731-83ade55a-4249-11e8-8722-7ebcd03d9878.png)

## Issue

FYI, `LOTAnimationCache` is caching animation by `animationName`, in my case, the `animationName` is same, so this cause the animation using the same assets as my first shot. 
https://github.com/airbnb/lottie-ios/blob/8c9a728676d19c470548cf2d5b8c0368ad51ad7d/lottie-ios/Classes/Private/LOTComposition.m#L27

## Proposal

- [ ] Expose new function to reuse animation with different template bundle
- [ ] Cache animation not just by animationName, but other identifier

**Comment by iPermanent** [comment]
Yeah, I had the same problem, and I suggest to change the reuse animation key name with a bundlePath combined with the json name? However I really do this in my  project, but still want to office support as I want to update the Lottie version at the first time.

**Comment by iPermanent** [comment]
Finally, I found that maybe you used the wrong method, you can try [LOTAnimationView animationWithFilePath:filePath]; 
this method will cache the animation by it's path, but not name, it will do all right.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
