### ISSUE TITLE
Add Support for Looping at Certain Progress

### ISSUE THREAD

**Issue by EncodedNybble** [airbnb/lottie-ios#61]
I have some animations which are designed to play a small "intro", then play the "main" part of the animation. The "main" part of the animation is to then be looped (to save space) either indefinitely or for a particular number of loops (specified outside of After Effects, obviously).

In my current system I have the ability to specify a frame/progress percentage in which the animation will start from when looping as well as a loop count. It would be a nice if a similar feature existed in Lottie.

I've tried using a completion callback and setting `loopAnimation` to be `false` to get similar behavior, but I seem to be hitting a race condition or logical error in which the animation's completion callback will be called once, but not called a second time. Setting `animationProgress` in the completion callback also does not appear to do anything.

**Comment by jmyers0022** [comment]
This would be great. I am working on something similar as well.

What I ended up doing for the meantime was layering the two animations, adding them both to the view with the intro animation on top. When the complete callback fires for the intro, I remove its subview and start the looping animation. It worked great with no obvious stutters. You just have to make sure the looping animation transitions in a nice way from the end of the intro animation.

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
