### ISSUE TITLE
Is there any chance to open source the Lottie Preview app for iOS?

### ISSUE THREAD

**Issue by revolter** [airbnb/lottie-ios#610]
Or is it not associated with Airbnb at all? The reason I opened this here is because I couldn't find any repo for it, and the developer website and app support from https://itunes.apple.com/us/app/lottie-preview/id1231821260?mt=8 point to https://lottiefiles.com

**Comment by buba447** [comment]
Its made by a third party! 
There is a different sample mac app and ios app in the repo though they arent as feature complete as the lottie files one.

**Comment by revolter** [comment]
And how can I contact them? It's also a bit odd that it's feature on https://www.lottiefiles.com without any disclaimer that it's a 3rd party one.

**Comment by buba447** [comment]
Lottiefiles is also 3rd party. Its their app and website. I believe the website has a contact link.

**Comment by revolter** [comment]
Oh, I didn't know that, sorry!

**Comment by reallynattu** [comment]
@revolter we currently manage LottieFiles.com and the iOS app linked there. Let me know if you need any help with it.

**Comment by revolter** [comment]
@reallynattu, I wanted to know if the Lottie Preview app is or could be open source, though I forgot what I wanted to contribute to it.
