### ISSUE TITLE
Text issue

### ISSUE THREAD

**Issue by mehtavatsal** [airbnb/lottie-ios#611]
## What Platform are you on? 

- [] Web for just now.

## Expected Behavior 
https://www.lottiefiles.com/1405-scroll-down

## Actual Behavior
https://www.lottiefiles.com/share/ueQ1nV

## Description
I have shared a link of Expected Behavior. I was not happy with the down arrow. So tried to make the way I want, but ended getting the result of Actual Behavior (Link shared). Please help me out. AE project attached.

## Animation JSON
[Scroll-4.aep.zip](https://github.com/airbnb/lottie-ios/files/1923642/Scroll-4.aep.zip)

**Comment by mehtavatsal** [comment]
@buba447

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
