### ISSUE TITLE
Constant time animation looks like it is slowing down and speeding up

### ISSUE THREAD

**Issue by roberthoglund** [airbnb/lottie-ios#613]
I'm using the latest release of Lottie, and, according to the designer, we are not using any unsupported features. I have looked at the other open issues and I don't think this is related to any other open issue.
 
## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)

## What Platform are you on? 
- [x] iOS

## Expected Behavior 
The correct animation can be seen here: https://www.lottiefiles.com/share/hb0zXr

## Actual Behavior
![ticket-to-gif mov](https://user-images.githubusercontent.com/1888703/39057817-087c4ff2-446f-11e8-8be9-e4ecf2560810.gif)

The clear distance between the lines should remain constant, as it looks on the web, but when running on iOS it looks like the clear distance grows and shrinks, or maybe it is the path that slows down and speeds up.

## Animation JSON
[animation.zip](https://github.com/airbnb/lottie-ios/files/1932559/animation.zip)

## After Effects files
[ticket animation raw.aep.zip](https://github.com/airbnb/lottie-ios/files/1932563/ticket.animation.raw.aep.zip)

**Comment by buba447** [comment]
This is a bug with trim path calculations. The current trim path algorithm has a small (~1%) margin of error compared to after effects.  This usually isn't too noticable until you trim very long paths close together like you're animation does.  It's a known bug. The algorithm that web and after effects uses for path trimmings more precise but at the cost of performance. Ive got the bug on my short list of things to fix.

You can tell your designer to try breaking the paths up into shorter segments or increase the gap between the trims. Alternatively they can create outline shapes. This will increase the filesize a bit but might be worth it.

Hope this helps!

**Comment by roberthoglund** [comment]
Awesome. Thanks for the quick reply.

**Comment by RamblinWreck77** [comment]
Oh wow, this is impacting me as well! We're seeing weird sinusoidal non-linearity on very long paths.

For example: 
0 , 50, and 100% are right, however 25% is less and 75% is too far.
