### ISSUE TITLE
How to replace the Image when completed?

### ISSUE THREAD

**Issue by MrSpiceTea** [airbnb/lottie-ios#616]
excuse me ，How to replace the Image when completed? I need to cycle through several sets of pictures，

**Comment by dmiluski** [comment]
@MrSpiceTea I'd assume if you add a completion to the play(completion:xx)
Once done,  you could set a new animation then play?

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
