### ISSUE TITLE
Not all development environments support paths with spaces

### ISSUE THREAD

**Issue by pappy74** [airbnb/lottie-ios#62]
Looks like a recent update added folders with spaces. Not all development environments support that. You might want to consider camel-casing instead.

**Comment by buba447** [comment]
@pappy74 which folder?

**Comment by pappy74** [comment]
https://github.com/airbnb/lottie-ios/tree/master/lottie-ios/Classes/Animatable%20Layers
https://github.com/airbnb/lottie-ios/tree/master/lottie-ios/Classes/Animation%20Cache
https://github.com/airbnb/lottie-ios/tree/master/lottie-ios/Classes/OSX%20Compatability

**Comment by buba447** [comment]
@pappy74 just pushed a dot release that fixes this! Sorry!

**Comment by pappy74** [comment]
Thanks!
