### ISSUE TITLE
scaleToFill issue

### ISSUE THREAD

**Issue by vburojevic** [airbnb/lottie-ios#620]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [x] iOS

## Expected Behavior 
LOTAnimatedView will scale animation over the whole view if contentMode is set to scaleToFill.

## Actual Behavior
Animation is not scaled to fill in the view.
<img width="674" alt="screenshot" src="https://user-images.githubusercontent.com/2234474/39424415-e9dc91c8-4c76-11e8-8a87-ce48acf56eb3.png">

## Code Example
`animationView.contentMode = .scaleToFill
        animationView.loopAnimation = true
        animationView.setAnimation(named: "pulse-notext")
        animationView.play()
`

## Animation JSON
[pulse-notext.json.zip](https://github.com/airbnb/lottie-ios/files/1960300/pulse-notext.json.zip)

**Comment by adxworld** [comment]
Did you find a solution to this?

**Comment by vburojevic** [comment]
Unfortunately no.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
