### ISSUE TITLE
Consider replacing calls to malloc with calloc

### ISSUE THREAD

**Issue by Pepsi1x1** [airbnb/lottie-ios#621]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [x] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [x] iOS

## Proposal

Replace calls to malloc with calls to calloc

## Actual Behavior
The results of static analysis following a pen test suggest replacing calls to malloc with calloc for security, there are seven calls to malloc in Lottie-ios

## Code Example

[lottie-ios/Classes/AnimatableProperties/LOTBezierData.m](https://github.com/airbnb/lottie-ios/blob/67d478dcd41205e5a4eade5258d6ab1648146a19/lottie-ios/Classes/AnimatableProperties/LOTBezierData.m#L69)

```
_vertices = (CGPoint *)malloc(sizeof(CGPoint) * pointsArray.count);
_inTangents = (CGPoint *)malloc(sizeof(CGPoint) * pointsArray.count);
_outTangents = (CGPoint *)malloc(sizeof(CGPoint) * pointsArray.count);
```

```
_vertices = (CGPoint *)calloc(pointsArray.count, sizeof(CGPoint));
_inTangents = (CGPoint *)calloc(pointsArray.count, sizeof(CGPoint));
_outTangents = (CGPoint *)calloc(pointsArray.count, sizeof(CGPoint));
```

[lottie-ios/Classes/MacCompatability/UIBezierPath.m L79 and L266](https://github.com/airbnb/lottie-ios/blob/84d36703fcbdc9994896906c1f77172bffb42b06/lottie-ios/Classes/MacCompatability/UIBezierPath.m#L79)

```
if (lineDashCount > 0) {
 CGFloat *lineDashPattern = malloc(sizeof(CGFloat) * lineDashCount);
```

```
if (lineDashCount > 0) {
 CGFloat *lineDashPattern = calloc(lineDashCount, sizeof(CGFloat));
```

[lottie-ios/Classes/Extensions/LOTBezierPath.m L112](https://github.com/airbnb/lottie-ios/blob/5a75d50609612c131f2b3b263ef524f351e16591/lottie-ios/Classes/Extensions/LOTBezierPath.m#L112)

`LOT_Subpath *subPath = (LOT_Subpath *)malloc(sizeof(LOT_Subpath));`

`LOT_Subpath *subPath = (LOT_Subpath *)calloc(1, sizeof(LOT_Subpath));`

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
