### ISSUE TITLE
Xcode 9 warning  - Block implicitly retains 'self

### ISSUE THREAD

**Issue by rajeshbeats** [airbnb/lottie-ios#624]
## Check these before submitting:
- [] Updated to the latest version of Lottie (2.5.0)
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)

## What Platform are you on? 

- [] iOS

## Expected Behavior 
There shouldn't be any warning 
![image](https://user-images.githubusercontent.com/1560365/39681203-f981554e-51eb-11e8-8587-fc065667969b.png)
![image](https://user-images.githubusercontent.com/1560365/39681204-fe1e75dc-51eb-11e8-8ec4-47f764636ed1.png)

## Actual Behavior

![image](https://user-images.githubusercontent.com/1560365/39681209-04ad170a-51ec-11e8-9812-440711e921a2.png)

**Comment by omidontop** [comment]
I have the same issue and it has to do with the latest version of Xcode (9.3).

**Comment by carminelavalle** [comment]
I have the same issue. Also please fix typo "**tranistion**AnimationView_" :)

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
