### ISSUE TITLE
Feature request: Time Remapping

### ISSUE THREAD

**Issue by Fideas** [airbnb/lottie-ios#625]
## Check these before submitting:
- [ :white_check_mark:] Updated to the latest version of Lottie (2.5.0)
- [ :white_check_mark:] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [ :white_check_mark:] This issue isn't related to another open issue

## This issue is a:
Feature Request

## What Platform are you on? 
 iOS

The team I work on is currently using the time remapping feature to control animations in an Android app we are developing and we would love to use the same APIs, and even more the same json file, to control the same animation in the iOS version of the app. Is there an ETA for that feature in the iOS version? Are PR accepted for that task?

**Comment by buba447** [comment]
You got it!

Now available in lottie 3.0
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
