### ISSUE TITLE
Default property attribute 'assign' not appropriate for non-GC object when manually including the library into a non arc project.

### ISSUE THREAD

**Issue by kgeorgy** [airbnb/lottie-ios#626]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [X] iOS

## Expected Behavior 
When including the framework manually (without carthage or cocoapods), there should be no compiler warning.

## Actual Behavior
When including the framework manually (without carthage or cocoapods), there are compiler warning when including the library header file (`#import <Lottie/Lottie.h>;`):

 * `Default property attribute 'assign' not appropriate for non-GC object`
 * `No 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed`

I don't know why the compiler warn, but this is fixable by just adding the `strong` attribute to the warned properties. See examples below.

## Code Example

For example, in `LOTAnimatedControl.h` at line 25 and 26:

`@property (nonatomic, readonly, nonnull) LOTAnimationView *animationView;`
`@property (nonatomic, nullable) LOTComposition *animationComp;`

Should be replayced by :
`@property (nonatomic, strong, readonly, nonnull) LOTAnimationView *animationView;`
`@property (nonatomic, strong, nullable) LOTComposition *animationComp;`

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
