### ISSUE TITLE
Can't add a gradient at runtime

### ISSUE THREAD

**Issue by mix717** [airbnb/lottie-ios#628]
Hi guys,

So, I think this topic needs a bit clarification here. There is Gradient Support in supported AF features section. But somehow it doesn't work in the app? I've tried linear gradients and those just won't load.

Then I assume that support section is for those features that we can add at runtime. Is that correct? How do I do that then? I clearly see how to use this code:
`animationView2.setValue(UIColor.green, forKeypath: "BG-On.Group 1.Fill 1.Color", atFrame: 0)`

But if there is support for gradients how do I add a gradient to a group/fill at runtime? `setValue` function won't accept `CAGradientLayer()` object

Thanks in advance

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
