### ISSUE TITLE
We want to put Lottie's picture in Images.xcassets. Is there any solution now?

### ISSUE THREAD

**Issue by lianghaoxintai** [airbnb/lottie-ios#629]
## Check these before submitting:
- [] Updated to the latest version of Lottie (2.5.0)
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [] iOS

**Comment by NemoAir** [comment]
you can do this by modify the json file.
open the json file that export from AE,find the string like below: notice the string with assets begin
`
"assets":[{"id":"image_0","w":119,"h":101,"u":"images/","p":"image_freshAir_animation_0.png"},{"id":"image_1","w":63,"h":59,"u":"images/","p":"image_freshAir_animation_1.png"},{"id":"image_2","w":445,"h":433,"u":"images/","p":"image_freshAir_animation_2.png"},{"id":"image_3","w":349,"h":335,"u":"images/","p":"image_freshAir_animation_3.png"}
`

in this json file ,i had modify the image name,
```
"image_freshAir_animation_0.png" 
"image_freshAir_animation_1.png"
"image_freshAir_animation_2.png"
"image_freshAir_animation_3.png"
```
original name was "image_0.png" to "image_1.png",you can change the name, and put the image into your image assets,it will work fine.

**Comment by smeshko** [comment]
This has already been fixed on master, is there any chance to get a new release soon? I fixed it locally, but need to apply the fix every time we update the pods.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
