### ISSUE TITLE
animationProgress can't by KVO to get progress 

### ISSUE THREAD

**Issue by XiaoYiS** [airbnb/lottie-ios#631]
## Check these before submitting:
- [] Updated to the latest version of Lottie (2.5.0)
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:

- [] Feature Request

## What Platform are you on? 

- [] iOS

## Code Example
 [self.lottieLogo addObserver:self forKeyPath:@"animationProgress" options:(NSKeyValueObservingOptionNew) context:nil];

- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary<NSKeyValueChangeKey,id> *)change context:(void *)context{
    //Do not perform here
}

I want to do somethine by animation.progress, I can set progress but I can't usage kvo to do something

**Comment by XiaoYiS** [comment]
I want loopAnimation a json file ,  I want to do something and animation continue when once stop(progress:0-->1-->0--->1-->0--->1...), when progress is 1, I want to write customer code ,but I can't get progress by KVO.  if I set progress I can observe progress. so what can I do ? please help me. thank you very much.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
