### ISSUE TITLE
Android animation blinks on start

### ISSUE THREAD

**Issue by MedveDomg** [airbnb/lottie-ios#632]
Hello, friends)

I have custom animation with JSON and custom pictures, which are attached from resources. When launch animation, my animation blinks.

## Version
- 2.5.4

## This issue is a:
- Non-Crashing Bug (Visual or otherwise)

## What Platform are you on? 
- Android

## Expected Behavior 
- animation `with out` blinking

## Actual Behavior
- animation `with` blinking

## Code Example
```
<com.airbnb.lottie.LottieAnimationView
                        android:id="@+id/lottie_cards_view"
                        android:layerType="software"
                        android:layout_width="400dp"
                        android:layout_height="200dp"
                        android:layout_marginBottom="32dp"
                        app:layout_constraintBottom_toTopOf="@+id/textView"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintHorizontal_bias="0"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toTopOf="parent"
                        app:lottie_cacheStrategy="strong"
                        app:lottie_enableMergePathsForKitKatAndAbove="true"
                        app:lottie_rawRes="@raw/cards" />
```
```
            binding.lottieCardsView.useHardwareAcceleration(true)
            binding.lottieCardsView.playAnimation()

**Comment by MedveDomg** [comment]
FIXED: `binding.lottieCardsView.animation` was causing blinking

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
