### ISSUE TITLE
Lottie 2.5.0 "No Such Module 'Lottie'"

### ISSUE THREAD

**Issue by Scixza** [airbnb/lottie-ios#634]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [X] iOS

## Expected Behavior 
Import Works

## Actual Behavior
When installing the cocoa pod "lottie-ios" into my Xcode 9.3.1 project I get an error message when importing resulting in "No Such Module 'Lottie'". All the obj-c files are in the pods->lottie-ios folder and it seems that everything is here, but does not allow me to import into my swift files. This is my first time using Lottie, and the first time having an import issue with a cocoa pod.

<img width="867" alt="screen shot 2018-05-24 at 2 29 49 pm" src="https://user-images.githubusercontent.com/26414216/40504331-f7d823fa-5f5e-11e8-8b80-f4ecda387756.png">

**Comment by dmiluski** [comment]
I've run into this recently as well using 2.5

My use case:
   Carthage install via submodules
   Project added to the XcodeProj & embedded frameworks

I'm up and running fine, then wanted to test on Device and got the error you are seeing.

My work around:
   Remove embedded framework and re-add
   Clean Build Folder

So I was up and running again, until I switched branches, and needed to run these steps over again once I returned.

**Comment by unnnyong** [comment]
iOS 11 / Swift 4.1 / Lottie 2.1.5, 2.5.0

My project occured same issue.
I solved that deleted `import Lottie` and added bridge file.

My project will be only swift. So I want to use `import lottie` at swift file instead of objc bridge.
Can I receive advice about this problem?

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC

**Comment by msqar** [comment]
Using lottie 3.0.3 and happens the same issue with react-native project 0.60.4. How can i solve it?

**Comment by heiwake** [comment]
This has worked for me. 
Lottie doesn't support ios 5 so I think that is causing the problem. 
This may be the solution: 
If you in your workspace in xCode, click on pods and go to the build settings. Scroll down to Swift language version and select 4.2. 
I hope this also works for other people with this error.

**Comment by iOSprojectsmaxwell** [comment]
> Before you do `import Lottie` try to run your project on Simulator or just build it, after that you can import Lottie to your project.
> I had the same problem and it helped me.

Thankyou !

**Comment by gischy** [comment]
solved this issue with the hints from: https://stackoverflow.com/questions/29865899/ld-framework-not-found-pods?page=2&tab=active#tab-top

> **This is usually caused by having the .xcodeproj file open instead of .xcworkspace. When you run 'pod install' for the first time, it will create an .xcworkspace file, which includes your original .xcodeproj and a Pods project. You'll need to close your .xcodeproj and open the .xcworkspace instead. This is a common issue when creating a project through Xcode's new project wizard - I often forget that I'm not in a workspace, which is required to get Cocoapods to link correctly.**
