### ISSUE TITLE
Lottie animation lags when there's additional UI work happening

### ISSUE THREAD

**Issue by steve-wang-ht** [airbnb/lottie-ios#635]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [x] iOS

## Expected Behavior 
The animation shouldn't lag based on other animation/UI work that's happening

## Actual Behavior
https://gyazo.com/f7f495e6da74fe2993819de2e25601a8

## Code Example
I'm setting up the Lottie view during appDidFinishLaunching and then adding the Lottie view to the keyWindow as a subview whenever I need to show my loading spinner.

## Animation JSON
{"v":"5.1.8","fr":60,"ip":109,"op":150,"w":88,"h":88,"nm":"Comp 17","ddd":0,"assets":[],"layers":[{"ddd":0,"ind":1,"ty":4,"nm":"Shape Layer 4","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":109.4,"s":[0],"e":[360]},{"t":149}],"ix":10},"p":{"a":0,"k":[44,44,0],"ix":2},"a":{"a":0,"k":[-25.654,-69.654,0],"ix":1},"s":{"a":0,"k":[121,121,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[15.931,0],[0,-15.931],[-15.931,0],[0,15.931]],"o":[[-15.931,0],[0,15.931],[15.931,0],[0,-15.931]],"v":[[0,-28.846],[-28.846,0],[0,28.846],[28.846,0]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"st","c":{"a":0,"k":[0.525490196078,0.341176470588,0.643137254902,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":3,"ix":5},"lc":2,"lj":2,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"tr","p":{"a":0,"k":[-25.654,-69.654],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Ellipse 1","np":3,"cix":2,"ix":1,"mn":"ADBE Vector Group","hd":false},{"ty":"tm","s":{"a":0,"k":100,"ix":1},"e":{"a":0,"k":60,"ix":2},"o":{"a":0,"k":180,"ix":3},"m":1,"ix":2,"nm":"Trim Paths 1","mn":"ADBE Vector Filter - Trim","hd":false}],"ip":0,"op":1769,"st":0,"bm":0}],"markers":[]}

**Comment by banaslee** [comment]
This one seems related with https://github.com/airbnb/lottie-ios/issues/642

**Comment by steve-wang-ht** [comment]
@banaslee  You just made a circular loop in comments..

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
