### ISSUE TITLE
3D rotation invalid

### ISSUE THREAD

**Issue by z624821876** [airbnb/lottie-ios#637]
The rotation along Y-axis 3d in iOS is invalid

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
