### ISSUE TITLE
Lottie Animation breaks in XCode/iOS app

### ISSUE THREAD

**Issue by WSamatis** [airbnb/lottie-ios#640]
Hello - I'm new (And just an animator, not a coder/dev) so please forgive me if I'm doing anything wrong, I've searched everywhere for an answer to this and figured I would sign up to see if anyone could help.

I have created an animation in After Effects, and when I preview it in BodyMovin as well as the Lottie Animation viewer available online it works fine. (Also if I do an .html preview it looks correct)

The problem I am having is when I hand this file over to my developer and they implement it into the app, things are breaking that I cannot replicate on my end or any other viewer.

I have uploaded the project file and .json here - specifically and most notably, the wings on my character have no animation/movement once we are previewing it on his end inside the app.

I wish I could replicate this on my machine to troubleshoot, but I can't so I'm hoping someone here might be able to help me understand what is happening. I really appreciate anyone taking the time to check this out.

Thanks!

[Lottie-test-00.zip](https://github.com/airbnb/lottie-ios/files/2054224/Lottie-test-00.zip)
[Checkout_TEST.zip](https://github.com/airbnb/lottie-ios/files/2054262/Checkout_TEST.zip)

**Comment by WSamatis** [comment]
After spending more time on this - it seems like it's (obviously) the 3D functionality which is probably breaking it.

However my question/title still stands in regards to is their a truly accurate previewer I can use that will actually break the parts it's supposed to before I send to my developer (In the case something happens that isn't as obvious as the 3D layer)?

This would be great, as it seems difficult to troubleshoot things if they aren't really breaking until after I send them out. I'm a PC user for what it's worth.

Thanks for the help!

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
