### ISSUE TITLE
LOTKeyPath not working on iOS but working fine on Android

### ISSUE THREAD

**Issue by ScubaInstructor** [airbnb/lottie-ios#643]
Hi

I  try to change the colors of a lottie files in iOS.

In Android this works fine:

`lottieAnimationView.addValueCallback(new KeyPath("foreground", "**"), LottieProperty.COLOR_FILTER, new LottieValueCallback(colorFilterForeground));`

How to translate this to iOS objecive c?
`LOTKeypath *keypath = [LOTKeypath keypathWidhKeys:@"foreground", @"**", nil];
LOTColorValueCallback *colorCallback = [LOTColorCallback withCGColor:[UIColor redColor].CGColor};
[lottieAnimation setValueDelegate:colorCallback forKeypath:keypath];`

The above does not work, the color is not changed.
I work with exactly the same lottie.json on Android and iOS.

Is this a bug or is the approach fundamentally different on iOS?

Best Regards Jochen

**Comment by leotumwattana** [comment]
Hi Lottie Team,

Thanks for the amazing library. I'm having a similar issue as well. In my case, I'm trying to set the stroke color on a LOTAnimatedSwitch, but nothing happens.

```
let keypath = LOTKeypath(string: "front Outlines.Group 1.Fill 1.Color")
let color = LOTColorValueCallback(color: UIColor.red.cgColor)
setValueDelegate(color, for: keypath)
```

Appreciate the help in advance! 

Cheers / Leo

**Comment by thomasouk** [comment]
Hello,

I had the same troubles with changing colors and found out thanks to the docs saying:
> NOTE: The delegate is weakly retained. Be sure that the creator of a delegate is retained.

```
let colorRetainer: LOTColorValueCallback = LOTColorValueCallback.init(color: UIColor.red.cgColor)

func setupLottie(){
    let path = "front Outlines.Group 1.Fill 1.Color"
    let keypath = LOTKeypath(string: path) 
    self.lottieView.setValueDelegate(colorRetainer, for: keypath)
} 
```
Then I tried to have a variable and it worked for me.

**Comment by willsmillie** [comment]
I was running into the same issue. What following the BodyMovin installation instructions here: https://github.com/airbnb/lottie-web

and then using this code: 

`    LOTKeypath *kp = [LOTKeypath keypathWithString:@"**.Fill 1.Color"];
    LOTColorValueCallback *callback = [LOTColorValueCallback withCGColor:[UIColor greenColor].CGColor];
    [animationView setValueDelegate:callback forKeypath:kp];
`

similarly to @exevil my `logHierarchyKeypaths()` does not list `"**.Fill 1.Color"` as property, but it doesn't seem to be causing any issues after following the install instructions in the read me.

**Comment by fredpi** [comment]
Just to share my experience:

I subclassed `LOTAnimationView` and created a custom initializer that internally called the designated `super.init(contentsOf:)` initializer. With this configuration I faced issues with key path adjustments not taking effect immediately.

When I used the convenience `self.init(name:bundle)` initializer instead, forcing me to make my custom initializer a convenience initializer too, and allowing me to replace my custom `required init(coder:)` implementation, all issues went straight away.

Maybe someone with a similar issues may find this workaround helpful...

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
