### ISSUE TITLE
Easing with zero values is played back as linear

### ISSUE THREAD

**Issue by karip** [airbnb/lottie-ios#644]
## Check these before submitting:
- [X] Updated to the latest version of Lottie (2.5.0)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [X] MacOS
- [] iOS

## Expected Behavior 
The black bar in the attached JSON file should start fast and slow down in the end, just like the blue bar does. The black bar is animated wrong. The blue bar is animated correctly.

The black bar uses easing with values 0, 0, 0, 1. The blue bar uses slightly different easing with values 0, *0.01*, 0, 1. The easing for the black bar should look almost the same as the easing for the blue bar.

The attached JSON file works fine on the web viewer and the Android player.

## Actual Behavior
The animation for the black bar plays linearly. It should be almost identical to the blue bar.
It seems that all easings which have the value (0, 0) as the first values play linearly.

## Code Example
JSON: ...  {"i":{"x":[0],"y":[1]},"o":{"x":[0],"y":[0]} ...

## Animation JSON
(in a zip file because GitHub doesn't allow json files)
[easing.json.zip](https://github.com/airbnb/lottie-ios/files/2079232/easing.json.zip)

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
