### ISSUE TITLE
Square end caps are not rendered correctly

### ISSUE THREAD

**Issue by karip** [airbnb/lottie-ios#645]
## Check these before submitting:
- [X] Updated to the latest version of Lottie (2.5.0)
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [X] MacOS
- [] iOS

## Expected Behavior 
The web and Android players render all caps correctly. Below is the rendering from the web player.

![caps-web-shot](https://user-images.githubusercontent.com/6185066/41089446-82d5223c-6a4a-11e8-9b63-5e6ba02e4928.png)

## Actual Behavior
The end cap isn't rendered correctly for "square" caps (the bottom line). Butt and round caps look good (the two top lines).

![caps-mac-shot](https://user-images.githubusercontent.com/6185066/41089634-fb905174-6a4a-11e8-8fb5-632979a3cbb6.png)

## Animation JSON

[caps.json.zip](https://github.com/airbnb/lottie-ios/files/2079720/caps.json.zip)

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
