### ISSUE TITLE
Line miter limit is not rendered correctly

### ISSUE THREAD

**Issue by karip** [airbnb/lottie-ios#646]
## Check these before submitting:
- [X] Updated to the latest version of Lottie (2.5.0)
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [X] MacOS
- [] iOS

## Expected Behavior 
The miter limit should create a beveled corner to the first path. Below is a screenshot from the Lottie web player.

![miter-web](https://user-images.githubusercontent.com/6185066/41090072-0a1aea82-6a4c-11e8-88cd-be929bd9d34c.png)

## Actual Behavior
The first path has a sharp corner. Below is a screenshot from the Mac Viewer.

![miter-mac](https://user-images.githubusercontent.com/6185066/41090079-0ed47354-6a4c-11e8-9248-4f1b80720af1.png)

## Animation JSON
[miter.json.zip](https://github.com/airbnb/lottie-ios/files/2079752/miter.json.zip)

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
