### ISSUE TITLE
[iOS] Lottie animation broken when placed over a UIVisualEffectView

### ISSUE THREAD

**Issue by krisl88** [airbnb/lottie-ios#647]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)

## What Platform are you on? 

- [x] iOS

## Expected Behavior 
I'm placing a Lottie animation over a UIVisualEffectView and it's glitching out visually.

 I've tried adding the lottie animation direction to the blurEffectView's contentview and as a siblings view over it, but both are broken.

Screenshot of lottie animation over a solid color:
![good](https://user-images.githubusercontent.com/4227579/41169539-2fa70620-6afe-11e8-8286-e57d59ed62f8.gif)

## Actual Behavior
Screenshot of lottlie animation over a blurred visual effect view:
![bad](https://user-images.githubusercontent.com/4227579/41169564-3f9c68ae-6afe-11e8-9585-eb35f0276711.gif)

## Code Example
 let blurEffect = UIBlurEffect(style: .regular)
 let blurEffectView = UIVisualEffectView(effect: blurEffect)

## Animation JSON
Any JSON animation

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
