### ISSUE TITLE
Luma matte

### ISSUE THREAD

**Issue by zhengs** [airbnb/lottie-ios#648]
Hi,

Just to make sure, does Lottie/Bodymovin support luma matte through any of the 3 web renderers (svg, canvas, html)? The supported features page marks Luma Matte and Luma Inverted Matte using question marks, thus asking.

http://airbnb.io/lottie/supported-features.html

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
