### ISSUE TITLE
s.header_dir = 'Lottie' 这个配置在cocopods 1.5.2下导致不能使用静态库的方式导入

### ISSUE THREAD

**Issue by flypigrmvb** [airbnb/lottie-ios#649]
## Check these before submitting:
- [-] Updated to the latest version of Lottie (2.5.0)
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [-] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [-] iOS

## Actual Behavior
s.header_dir = 'Lottie' 这个配置在cocopods 1.5.2下导致不能使用静态库的方式导入

## Code Example
```ruby
target 'SavePoint' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  #use_frameworks!
  use_modular_headers!
  pod 'lottie-ios'
end
```

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
