### ISSUE TITLE
iOS/Android device form factor - design pattern (for Edge to Edge animation)

### ISSUE THREAD

**Issue by yozef** [airbnb/lottie-ios#65]
I've noticed that each device (iPhone 5, 6 and 6+) form factors, require each it's own aep (and it's own .json) composition reflecting the size of the targeted device for *pixel perfect edge to edge* screen animation _(example, placing a border around the screen)_.

In other words, for each of the iPhone device form factor, the Compositions are:
- iPhone 5: 568 x 320
- iPhone 6, 7: 667 x 375
- iPhone 6, 7 Plus: 736 x 414

My question is, is there a design pattern (or composition) to follow in order to generate **one json file for all form factors (including Androids)** ?

_For non edge to edge compositions, the animations should be centered at the smallest form factor size._

**Comment by buba447** [comment]
@yozef if you use the content mode ScaleAspectFill  you can scale it to fit edge to edge screen. 
There will be a very minimum amount of cropping but if you anticipate that you can craft the composition to look good on all devices!

After effects works in an absolute coordinate system, so theres no way to specify things as a percentage of the screen.
