### ISSUE TITLE
Excessive logging.

### ISSUE THREAD

**Issue by mdelamata** [airbnb/lottie-ios#650]
## Check these before submitting:
- [✅] Updated to the latest version of Lottie (2.5.0)
- [✅] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [✅] This issue isn't related to another open issue

## This issue is a:
- [✅] Non-Crashing Bug (Visual or otherwise)

## What Platform are you on? 

- [✅] iOS

## Problem:

I am using an animation that works visually perfectly, however the console is full of warnings that are not really affecting the animation and it is just adding noise. 

Such as:
```[LOTShapeGroup shapeItemWithJSON:]: Warning: merge shape is not supported. name: Merge Paths 1```

Is there a way to silence this log?

Thank you very much, this tool is so good.

**Comment by alan-andrade** [comment]
Could you add a link to the asset you're using ?

**Comment by buba447** [comment]
Those logs are there to let you know that the animation you are loading is using unsupported after effects features and wont render properly.

**Comment by mdelamata** [comment]
Yes, I understand, thanks. But the truth is that the animation is not really getting affected. They play exactly as expected and I was wondering if there is a way to disable these warnings.

**Comment by sench93** [comment]
Is there a way to disable logging ? If animation is small and is looping all logcat logs are something like this

`W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.`

or 

`I/chatty: uid=10096(com.getsteven.app.debug) identical 350 lines`

350 log in 100 ms !!!

**Comment by farshadtx** [comment]
Is there a way to disable logging?

We get tons of warnings for `Merge Path` but animations looks good. These objects are not part of our design and auto-generate from tooling our design team use to make Lottie `JSON` files.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
