### ISSUE TITLE
Replace image with set of images for animation play

### ISSUE THREAD

**Issue by NarenLK** [airbnb/lottie-ios#651]
How can I replace the Image when actual PLAY is completed? I would like to loop in through 4 images and do a circular set of animation of 4 images.??

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
