### ISSUE TITLE
Making all headers public

### ISSUE THREAD

**Issue by AmitYitzhack** [airbnb/lottie-ios#652]
Hi, 

I wonder if there is a chance to make all headers public, in order to use them outside the `UIKit` framework. For example in my case I want to be able to use the `LOTComposition` along with the interpolators to sample each underlying layer for a given frame, and pass the values to a shader for further processing.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
