### ISSUE TITLE
exc_bad_access when changing sceneModel

### ISSUE THREAD

**Issue by zippo227** [airbnb/lottie-ios#653]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [x] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [x] iOS

## Expected Behavior 

Setting a new sceneModel in a LOTAnimationView changes the animation.

## Actual Behavior

Setting a new sceneModel (after having set one previously) in a LOTAnimationView often crashes in the function _setupWithSceneModel, and crashes every time in a certain circumstance in my codebase. Since it works well in most situations, I assume this is supported behavior.

## Code Example
![screen shot 2018-06-15 at 11 12 23 am](https://user-images.githubusercontent.com/1617031/41485448-2e245052-70a6-11e8-8df1-1473c2e27aaa.png)

self.animationView.sceneModel = LOTComposition(filePath: json.path)

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
