### ISSUE TITLE
Animation freezes on Phonecalls and when the top menu is pulled down

### ISSUE THREAD

**Issue by Dellybro** [airbnb/lottie-ios#654]
Create a lottie animation, get a phone call. Decline or answer, doesn't matter. When the app reappears the animation will not be running anymore.

Create a lottie animation, pull down the top menu of any IOS device, pull it back up for the app to reappear. 

Lottie view doesn't play animation when called after "UIApplicationWillBecomeActive" and a call to [animation play] is made. The to scenarios mentioned above both call UIApplicationDidBecomeActiveNotification, but do not call UIApplicationWillEnterForegroundNotification, which i currently use to replay animation.

## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [x] iOS

## Expected Behavior 

Animation should continue to play, or should continue to play after calling [animation play]

## Actual Behavior

Freezes and stops playing

## Code Example

-(void)stopAnimation:(NSNotification*)notifier{
    [animation pause];
}

- (void)playAnimation:(NSNotification*)notifier{
    if(![animation isAnimationPlaying]){
        [animation play];
    }
}

-(void)addObservers{
    /* Setup listener for background / foreground, Animation stops playing when enters foreground */
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(playAnimation:) name:UIApplicationWillEnterForegroundNotification object:nil];
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(stopAnimation:) name:UIApplicationWillResignActiveNotification object:nil];
}

-(void)removeFromSuperview{
    [[NSNotificationCenter defaultCenter] removeObserver:self name:UIApplicationDidBecomeActiveNotification object:nil];
    [[NSNotificationCenter defaultCenter] removeObserver:self name:UIApplicationWillResignActiveNotification object:nil];
    
    [super removeFromSuperview];
}

## Animation JSON

[findingAnimation.json.zip](https://github.com/airbnb/lottie-ios/files/2107462/findingAnimation.json.zip)

**Comment by ivangodfather** [comment]
any updates on this?

**Comment by Dellybro** [comment]
Nope nothing.

**Comment by chrislongden** [comment]
I saw this when I was setting up an animation which when entering the background did stop and wouldn't continue when opening the app again, however I did get it to work.

I just added an observer for UIApplication.didBecomeActiveNotification and then play it and it works.

In the code example above there is an issue which is two observers are being added for:

- UIApplicationWillEnterForegroundNotification
- UIApplicationWillResignActiveNotification

but then removing the observers:

- UIApplicationDidBecomeActiveNotification
- UIApplicationWillResignActiveNotification

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
