### ISSUE TITLE
Change opacity indefinite

### ISSUE THREAD

**Issue by Matic1993** [airbnb/lottie-ios#655]
Hi!

Is there a way to get single path from the animation?

So I have one path that I have to change opacity from 0.0 to 1.0 and from 1.0 to 0.0 indefinite.

This opacity change also has to work when the animation pauses on certain progress.

Is there a way to achieve this?

- [X] Updated to the latest version of Lottie (2.5.0)

- [X] Non-Crashing Bug (Visual or otherwise)

- [X] iOS

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
