### ISSUE TITLE
Custom ease not rendering properly in iOS

### ISSUE THREAD

**Issue by itzjshine** [airbnb/lottie-ios#656]
## Check these before submitting:
- [✓] Updated to the latest version of Lottie (2.5.0)
- [✓] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [✓] This issue isn't related to another open issue

## This issue is a:
- [✓] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [✓] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [✓] iOS 11.3.1

## Expected Behavior 

The animation should include the custom easing from the After Effects file
![expected_behavior](https://user-images.githubusercontent.com/19598302/41546426-99736626-72eb-11e8-8766-8da0537cc739.gif)

## Actual Behavior

The easing is being rendered as if it was linear only on iOS. Works perfect on Web and Android.

![ios_actual_behavior](https://user-images.githubusercontent.com/19598302/41546223-132a3734-72eb-11e8-9a9a-344c32d37989.gif)

## Animation JSON

[Fast_Leaf.zip](https://github.com/airbnb/lottie-ios/files/2111926/Fast_Leaf.zip)

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
