### ISSUE TITLE
How to Load Images From a Remote URL

### ISSUE THREAD

**Issue by bhavukjain1** [airbnb/lottie-ios#658]
Hi,

I'm having trouble loading remote images in Lottie-iOS library. Currently, it loads the images present in the bundle but I need to load the images from a URL.

I also checked this issue raised on Github: https://github.com/airbnb/lottie-ios/issues/600

Here the developer says, the library already supports it but I cannot find any possible way of doing it. Only the JSON file seems to be loading from the remote URL.

This is a part of my JSON file:

```sh
"assets":[{"id":"image_0","w":256,"h":256,"u":"images/","p":"img_0.png"},
```

If I put an image named `img_0.png` in the app bundle only then it works. I want to load this image from an URL. Is it possible to load images from the documents, temporary or cache directory or directly from the URL?

**Comment by tw93** [comment]
+1

**Comment by wensixing** [comment]
+1

**Comment by Leocata14** [comment]
+ 1

**Comment by beyondfengyu** [comment]
+1，the json file and source file load from url

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC

**Comment by xingyao1015** [comment]
How to Load Images From a Remote URL
