### ISSUE TITLE
iOS problem with repeated animation

### ISSUE THREAD

**Issue by IronTony** [airbnb/lottie-ios#661]
Heya,
I am new to Lottie. I am using the package in an iOS app (using Swift 4).
I am trying to have an animation looping all the time.
Unfortunately the animation is slowing down when reaching the end, and then start normally again.
Is there a wait to run the animation at the same speed all the time? How?

Thank you in advance.

## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [x] iOS

## Expected Behavior 
Same as below but no slow down at the end.

## Actual Behavior
![dsadsa](https://user-images.githubusercontent.com/3645225/42378985-958f7ab2-8129-11e8-854d-410644ce1242.gif)

## Code Example
```
       // Create Plane Animation
        let planeAnimation = LOTAnimationView(name: "looping_landscape_+_plane_+_clouds")
        // Set view to full screen, aspectFill
        planeAnimation!.autoresizingMask = [.flexibleHeight, .flexibleWidth]
        planeAnimation!.contentMode = .scaleAspectFill
        planeAnimation!.frame = view.bounds
        // Add the Animation
        view.addSubview(planeAnimation!)
        
        planeAnimation!.loopAnimation = true
        planeAnimation?.play()
```

## Animation JSON
[looping_landscape_+_plane_+_clouds.json.zip](https://github.com/airbnb/lottie-ios/files/2170503/looping_landscape_._plane_._clouds.json.zip)

**Comment by jessenaugher** [comment]
Hello! We are noticing some of the same behavior. Did you find a specific piece of the animation that caused this? @IronTony

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
