### ISSUE TITLE
Polygon Roundness Creates Artefacts in Some Circumstances

### ISSUE THREAD

**Issue by wfltaylor** [airbnb/lottie-ios#662]
When animating the outer roundness of a polygon some strange artefacts have been created around the shape.
## This issue is a:
- Non-Crashing Bug (Visual or otherwise)

## What Platform are you on? 

- iOS

## Expected Behavior 

<img width="386" alt="screen shot 2018-07-11 at 11 52 11 am" src="https://user-images.githubusercontent.com/13045470/42546486-ef0671ba-8500-11e8-9130-8a23d8f924a7.png">

## Actual Behavior

<img width="468" alt="screen shot 2018-07-11 at 11 51 27 am" src="https://user-images.githubusercontent.com/13045470/42546483-e75d7d0a-8500-11e8-9768-b964da08aade.png">

## Animation JSON

[loadingIndicator.json.zip](https://github.com/airbnb/lottie-ios/files/2182688/loadingIndicator.json.zip)

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
