### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by yhkaplan** [airbnb/lottie-ios#663]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Feature Request/Inquiry

## What Platform are you on? 
- [x] iOS

## Inquiry
This is just a question, but what approach do you taking with testing Lottie when used in your codebase? We're looking into adding Lottie animations to UI elements, but we would like to be able to check if the json file name is set correctly, if the animation is actually played, etc, but I was unable to find any public properties where the file name and such are exposed. Currently, is the best technique just subclassing a LOTView and its initializers?

**Comment by buba447** [comment]
We test Lottie json decoding with good old fashioned unit tests and test the animations themselves with visual regression testing by loading up an animation and snapshotting it at intervals then comparing to the previous version of lottie.
