### ISSUE TITLE
Pod installed but framework not found Lottie

### ISSUE THREAD

**Issue by loisyang** [airbnb/lottie-ios#67]
```
ld: warning: directory not found for option '-F/Users/jingqiyanglois/Library/Developer/Xcode/DerivedData/lottie-ios-cpbpeohptyuobhbmovrxchqlbhcp/Build/Products/Debug-iphonesimulator/lottie-ios-iOS'
ld: framework not found Lottie
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I used cocoapod to install but still fail to have the framework working. Any solutions?

**Comment by paulsumit1993** [comment]
Cocoapod works fine both on ObjC and Swift projects.
Carthage installation seems to be broken.

**Comment by buba447** [comment]
@paulsumit1993 @loisyang We've just pushed a dot release that should fix these problems! 1.0.2

**Comment by Tough-Guy** [comment]
I'm having the same issue. Any idea how to resolve this?

**Comment by jvieiraABC** [comment]
I am seeing this problem too

> ld: framework not found Lottie
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Cypaubr** [comment]
Same issue here.

**Comment by Liyongcong** [comment]
I'm having the same issue. Any idea how to resolve this?
