### ISSUE TITLE
Changing color At Runtime

### ISSUE THREAD

**Issue by NicolasMatiasWW** [airbnb/lottie-ios#673]
Hello,
 i tried to make a color change to my animation for testing but its doesnt work, however i dont see mistake. 

maybe it's because my After effect is in french ? make the line : "boule.Ellipse 1.Fill.Color" wrong ? 

```
  @IBAction func showBoule(_ sender: UIButton) {
        let animationBoule = LOTAnimationView(name: "boule")
        self.view.addSubview(animationBoule)
        
        animationBoule.loopAnimation = true
        animationBoule.frame = CGRect(x: 0, y: 0, width: self.view.frame.size.width, height: self.view.frame.size.height)
        
        //TEST changer propriété animation

          animationBoule.setValue(UIColor.green, forKeypath: "boule.Ellipse 1.Fill 1.Color", atFrame: 0)
        
        animationBoule.play{ (finished) in
            
        }
    }
```
![screen](https://user-images.githubusercontent.com/26058079/42660755-6695c7c2-862c-11e8-8a4a-1dc8eb543410.png)

**Comment by buba447** [comment]
See the new documentation for this.

Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
