### ISSUE TITLE
Trim path is not average

### ISSUE THREAD

**Issue by fanyinan** [airbnb/lottie-ios#674]
The start parameter of Every path increases 5% orderly.
But they are not average.

## Check these before submitting:
- [✅] Updated to the latest version of Lottie (2.5.0)
- [✅] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [✅] This issue isn't related to another open issue

## This issue is a:
- [✅] Non-Crashing Bug (Visual or otherwise)

## What Platform are you on? 
- [✅] iOS

## Expected Behavior 
AE
<img width="300" alt="2018-07-16 12 16 17" src="https://user-images.githubusercontent.com/8432803/42735825-88c3255c-888d-11e8-9481-24c6a77938c8.png">
Web
<img width="300" alt="2018-07-16 12 16 17" src="https://user-images.githubusercontent.com/8432803/42735831-b2a31e40-888d-11e8-85df-ff4051fd1969.PNG">

## Actual Behavior
iOS
<img width="300" alt="2018-07-16 12 16 17" src="https://user-images.githubusercontent.com/8432803/42735851-3726fb78-888e-11e8-866c-5476502f2076.png">

## AEP
[dash.aep.zip](https://github.com/airbnb/lottie-ios/files/2195882/dash.aep.zip)

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
