### ISSUE TITLE
iOS base64 image support

### ISSUE THREAD

**Issue by mlf2020** [airbnb/lottie-ios#675]
why did version2.5.0 removed base64 image support  ？

**Comment by candidodmv** [comment]
I`m with the same problem  with XamarinLottie

**Comment by Peeeep** [comment]
Just had the same problem, upgrading to #2.5.2 has base64 support again...

**Comment by candidodmv** [comment]
let me check out

**Comment by chupakabr** [comment]
seems to work in 2.5.2. thanks guys :)

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
