### ISSUE TITLE
This bug occurs when multiple LOTAnimatedSwitchs are added.

### ISSUE THREAD

**Issue by myouzh** [airbnb/lottie-ios#678]
## Check these before submitting:
- [v] Updated to the latest version of Lottie (2.5.0)
- [v] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [v] This issue isn't related to anoth

er open issue

## This issue is a:
- [v] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [v] iOS

## Expected Behavior 

[TestProjPodOC-lott.zip](https://github.com/airbnb/lottie-ios/files/2213175/TestProjPodOC-lott.zip)
## Actual Behavior
![qq20180720-164120](https://user-images.githubusercontent.com/13919664/42993823-f6dc5310-8c3e-11e8-8ca6-4725e94c93d5.gif)
When a button is clicked, another button responds.

**Comment by myouzh** [comment]
When a button is clicked, another button responds

**Comment by PauloxD** [comment]
I am having this issue as well. Glad to see that I wasn't losing my marbles :)

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
