### ISSUE TITLE
Place LOTAnimationView inside uibarbuttonitem

### ISSUE THREAD

**Issue by rjt3662** [airbnb/lottie-ios#679]
Hi guys,
I'm new to lottieanimation. 
I have added the LOTAnimationView inside the uibarbutton by adding customView. 
I'm using [https://www.lottiefiles.com/63-hamburger-arrow-transition] LottieAnimation.
Can anyone please explain why is this happening?

`

        lazy var drawerBarView: UIView = {
                let vw = UIView(frame: CGRect(x: 0, y: 0, width: 44, height: 44))
                vw.backgroundColor = .blue
                let tapGesture = UITapGestureRecognizer(target: self, action:#selector(didTapDrawerBarButton))
                vw.addGestureRecognizer(tapGesture)
                return vw
        }()
        let drawerAnimationView = LOTAnimationView(name: "data")

        override func viewDidLoad() {
                 super.viewDidLoad()
                 drawerBarView.addSubview(drawerAnimationView)
                 navItem.setLeftBarButton(UIBarButtonItem(customView: drawerBarView), animated: true)
         }
 `

![simulator screen shot - ipad pro 12 9-inch - 2018-07-22 at 16 22 15](https://user-images.githubusercontent.com/21313219/43044878-0e7b0924-8dcc-11e8-8cb5-35d50aacbfc7.png)

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
