### ISSUE TITLE
Loop a limited number of times in Swift (Repeat count)

### ISSUE THREAD

**Issue by LetRod** [airbnb/lottie-ios#680]
Hi ! How can i do to loop limited number of times y Swift ? Thank you!

## Check these before submitting:
- [] Updated to the latest version of Lottie (2.5.0)
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [] iOS

**Comment by zhangferry** [comment]
I get the same requirements. I can't find any api relevant to repeat count.
