### ISSUE TITLE
Mixing animation with active elements

### ISSUE THREAD

**Issue by pgawlowski** [airbnb/lottie-ios#682]
## This issue is a:
- [] Feature Request

## What Platform are you on? 
- [] iOS

Let's assume that I want to animate UIView with fancy transition that makes some tranformations, expanding etc. and as a final result it is showing (with that fancy animation) some active elements (like buttons). 

How am I supposed to achieve this?
Using one animation for whole element, and after animation replacing "image" with active elements? Or separate animation per element? 
How to coordinate this in case of multiple elements with separate animation per element?
Will try to upload gif with animation sample soon.

![jul-30-2018 10-22-50](https://user-images.githubusercontent.com/9845024/43386062-ca84c17a-93e2-11e8-9ede-447b8f3d6c31.gif)

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
