### ISSUE TITLE
When is the next Lottie release?

### ISSUE THREAD

**Issue by ttanatb** [airbnb/lottie-ios#683]
Title says it -- really need the fix for loading static images from the asset catalogue and wanted to know when the next release would be.

**Comment by bettola** [comment]
Waiting for next release as well!

**Comment by eneko** [comment]
We are currently migrating to Xcode 10 and Swift 4.2. Seems like the `master` branch is good to go. However, pulling from `master` is not ideal.

Looking forward to a new release 🙏

**Comment by GolombYotam** [comment]
Still waiting for a release ....

**Comment by TomerGlick** [comment]
From which version is Xcode10 + Swift 4.2 is supported?

**Comment by bill350** [comment]
Still waiting too, there are improvements we need 🚀

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
