### ISSUE TITLE
Animation Renders wrongly on Mobile

### ISSUE THREAD

**Issue by Felixchip** [airbnb/lottie-ios#684]
[Loader.zip](https://github.com/airbnb/lottie-web/files/2245234/Loader.zip)

* **I use Google Chrome and Lottie Preview for iOS:**
* **After Effects Version 15.1.1:**

I created a loading animation using After Effects and rendered with Bodymovin Version 5.2.0.
Now, when I preview the animation on my browser, it plays well, as well as on the Lottie website Previewer. But, when I preview it on my mobile phone, it shows something completely different.

And, from my experience, if it doesn't render well on mobile preview, it won't when implemented into an app. 

The animation is supposed to be a path revealing the image.
But instead, it renders something different. Entirely.

I attached the JSON file.

**After Effects file: https://www.datafilehost.com/d/c1ccbf85**

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
