### ISSUE TITLE
 change the string from a finished work (.json)

### ISSUE THREAD

**Issue by ReyesWei** [airbnb/lottie-ios#686]
Hi.
Is there a easy way to change the string from a finished work (.json)?

because some animation is amazing, I want to change the words

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
