### ISSUE TITLE
麻烦改改bug吧。。。。。。。。

### ISSUE THREAD

**Issue by leeliangliang** [airbnb/lottie-ios#687]
<img width="855" alt="image" src="https://user-images.githubusercontent.com/5946002/43832185-29b7f272-9b39-11e8-808f-1db3301f161a.png">

**Comment by namedssy** [comment]
您好，麻烦问一下您做过 从沙盒中拿图片的操作吗？ 而不是从bundle中

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
