### ISSUE TITLE
Inconsistent Speed on iOS

### ISSUE THREAD

**Issue by olohere** [airbnb/lottie-ios#688]
I made a simple "spinning" globe animation (for iOS) by passing a flat map through a circle mask. No effects, nothing special, just a position change (2 keyframes) and an alpha matte.

[https://www.lottiefiles.com/share/gJamPA](https://www.lottiefiles.com/share/gJamPA)

It plays correctly (consistent speed) on chrome, safari, and android... but not iOS. **On iOS it slows down as though there's an ease when it gets to the end of the loop.** The keyframes are plain and the graph is straight as shown in the screen below.

Any idea what could be happening?

![image](https://user-images.githubusercontent.com/42187443/43864979-0c87db7c-9b16-11e8-945c-9a5aa4b09500.png)

[After Effects file](https://drive.google.com/file/d/1821VFni3ws2B25G4sT9TbBD0UdDP0gS6/view?usp=sharing) (v14.0.1.5) (Bodymovin v5.1.20)

Thanks!

**Comment by RamblinWreck77** [comment]
I have observed this as well. 

Long movements that should be linear will speed up and slow down in some cases. The only solution we found was lots of short paths but even then it's not ideal. It's a bug with Lottie.

**Comment by deluxeroyale** [comment]
I have the same issue. A very long path make it "ease" on iOS. Android and web doesn't have the issue.

**Comment by deluxeroyale** [comment]
I think I've figured it out. Try this:
Right click on the keyframes (all of them selected) of the layer you want to "fix". Select **Keyframe Interpolation** and set both **temporal interpolation** and **spatial interpolation** to **linear**

**Comment by YoshyB** [comment]
> I think I've figured it out. Try this:
> Right click on the keyframes (all of them selected) of the layer you want to "fix". Select **Keyframe Interpolation** and set both **temporal interpolation** and **spatial interpolation** to **linear**

Good to hear that it worked for you man! However, sadly enough this still did not fix the issue for me. Hoping that the team from Lottie can get back to us with a response.

**Comment by deluxeroyale** [comment]
> > I think I've figured it out. Try this:
> > Right click on the keyframes (all of them selected) of the layer you want to "fix". Select **Keyframe Interpolation** and set both **temporal interpolation** and **spatial interpolation** to **linear**
> 
> Good to hear that it worked for you man! However, sadly enough this still did not fix the issue for me. Hoping that the team from Lottie can get back to us with a response.

Very strange indeed. Is the path masked?

**Comment by YoshyB** [comment]
> > > I think I've figured it out. Try this:
> > > Right click on the keyframes (all of them selected) of the layer you want to "fix". Select **Keyframe Interpolation** and set both **temporal interpolation** and **spatial interpolation** to **linear**
> > 
> > 
> > Good to hear that it worked for you man! However, sadly enough this still did not fix the issue for me. Hoping that the team from Lottie can get back to us with a response.
> 
> Very strange indeed. Is the path masked?

The path is not masked. Its a path with a trim path which is animated

**Comment by deluxeroyale** [comment]
Did you try setting all keyframes to linear interpolation?

**Comment by ThierryVC** [comment]
Possibly related: #60

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
