### ISSUE TITLE
White gap between shape layer and solid layer 

### ISSUE THREAD

**Issue by taropuffgurl** [airbnb/lottie-ios#690]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)

## What Platform are you on? 

- [x] MacOS

## Expected Behavior 
No bar/gap in AE. 

<img width="159" alt="screen shot 2018-08-14 at 11 08 57 am" src="https://user-images.githubusercontent.com/42387889/44109738-9d9c6ccc-9fb2-11e8-8947-602c406bc4f6.png">

## Actual Behavior
I have a two layers with color - a solid layer and a shape layer. Even though in AE the files have overlap and show no gap (and exporting into a mp4 file confirms this as well), when I use the Lottiefiles preview I keep seeing this white bar. 

<img width="340" alt="screen shot 2018-08-14 at 11 09 28 am" src="https://user-images.githubusercontent.com/42387889/44109762-b08b18d8-9fb2-11e8-8756-cf2f5580a033.png">

## Animation JSON

https://www.dropbox.com/s/vd4eidtgupr3225/data.json?dl=0

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
