### ISSUE TITLE
LOTColorValueCallback Only Coloring One Layer

### ISSUE THREAD

**Issue by willsmillie** [airbnb/lottie-ios#691]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [x] iOS

## Expected Behavior 
![image](https://user-images.githubusercontent.com/1259117/44157531-ad62ee00-a080-11e8-9bf3-dc5208b32c55.png)

## Actual Behavior

![image](https://user-images.githubusercontent.com/1259117/44158250-45ada280-a082-11e8-8daa-55ee5ea271f0.png)

## Code Example

```
    LOTKeypath *kp = [LOTKeypath keypathWithString:@"**.Fill 1.Color"];
    LOTColorValueCallback *callback = [LOTColorValueCallback withCGColor:[UIColor redColor].CGColor];
    [self.animationView setValueDelegate:callback forKeypath:kp];

```
## Animation JSON

[Animation JSON on Pastebin](https://pastebin.com/raw/KkmLVu3H)

**Comment by timaktimak** [comment]
@willsmillie valueDelegate is not retained by the animationView, so since the callback is created in scope and not retained by anything, it will be released, and that might be the reason for the issue. Try storing the callback in a property. Hope that helps!

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
