### ISSUE TITLE
PageViewController reloads animation twice

### ISSUE THREAD

**Issue by mickeyevers77** [airbnb/lottie-ios#692]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [x] iOS

## Expected Behavior 

I am trying to create an onboarding with multiple animations using a pageviewcontroller. I wan't to start the animation in the viewWillAppear. The reason for this choise is that I wan't to start the animation from the moment the pagination starts.

## Actual Behavior

When I start to scroll the animation starts like I want it to. But when the scroll ended on the next page, the animation starts again whitout calling my funtion a second time instead of  continuing the animation. Any help?

## Code Example

@IBOutlet weak var animationTwo: UIView!
    private var headAnimationTwo: LOTAnimationView?
    private var firstAppear: Bool = true

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        playAnimation(name: "Text", start: 0, end: 0.6, annimationView: animationTwo)
      
    }

      func playAnimation(name: String, start: CGFloat, end: CGFloat, annimationView: UIView) {
        let currentAnimationView = annimationView
        headAnimationTwo?.removeFromSuperview()
        headAnimationTwo = LOTAnimationView(name: name).then {
            $0.autoresizingMask = [.flexibleHeight, .flexibleWidth]
            $0.contentMode = .scaleAspectFit
            $0.frame = animationTwo.bounds
            currentAnimationView.addSubview($0)
        }
        headAnimationTwo?.play(fromProgress: start, toProgress: end)
    }

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
