### ISSUE TITLE
LOTAnimationView doesn't update frame while scrolling

### ISSUE THREAD

**Issue by mindz-eye** [airbnb/lottie-ios#693]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [x] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [x] iOS

## Expected Behavior 
```-[LOTAnimationView playFromFrame:toFrame:withCompletion]``` method animates and calls the completion right after the view was added to the window.

## Actual Behavior
```-[LOTAnimationView playFromFrame:toFrame:withCompletion]``` method doesn't start animation if it's called while the user scrolls. This happens because there's a call to
```[self performSelector:@selector(_restoreState) withObject:nil afterDelay:0]```
inside ```-[LOTAnimationView willMoveToWindow:]```

Possible solution: ```[self performSelector:@selector(_restoreState) withObject:nil afterDelay:0 inModes:@[NSRunLoopCommonModes]];```
I think it worth adding a comment for why this ```performSelector``` is needed.

This behavior is a degradation compared to Lottie 2.0.2, which we've used before.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
