### ISSUE TITLE
Exist sawtooth around the view in iOS 8.4

### ISSUE THREAD

**Issue by Arnold134777** [airbnb/lottie-ios#696]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)

## What Platform are you on? 

- [x] iOS 

## Actual Behavior
![img_1834](https://user-images.githubusercontent.com/12479572/44462147-37ddbb80-a646-11e8-8462-87cb1b68e1dd.PNG)

## Code Example

```objc
   self.lottieTestView = [LOTAnimationView animationNamed:@"video_70"];
    self.lottieTestView.animationProgress = 0.0;
    self.lottieTestView.contentMode = UIViewContentModeScaleAspectFit;
    self.lottieTestView.frame = CGRectMake(100, 400, 70, 70);
    [self.view addSubview:self.lottieTestView];
```

## Animation JSON
[video_70.json.zip](https://github.com/airbnb/lottie-ios/files/2310194/video_70.json.zip)

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
