### ISSUE TITLE
How to add target on animation's element?Can animation be userInteractable?

### ISSUE THREAD

**Issue by FFFang** [airbnb/lottie-ios#697]
## Check these before submitting:
- [] Updated to the latest version of Lottie (2.5.0)
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [] iOS

**Comment by buba447** [comment]
This isnt currently supported.
