### ISSUE TITLE
Carthage update fails

### ISSUE THREAD

**Issue by rossrossp** [airbnb/lottie-ios#698]
## Check these before submitting:
- [NA] Updated to the latest version of Lottie (2.5.0)
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [X] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [X] iOS

## Expected Behavior 
Carthage update is successful

## Actual Behavior
Carthage update fails

## Code Example
`Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/rosspatman/Documents/Apps/Core/concertlive.core.ios/Carthage/Checkouts/lottie-ios/Lottie.xcodeproj -scheme Lottie_tvOS -configuration Release -derivedDataPath /Users/rosspatman/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/lottie-ios/2.5.0 -sdk appletvos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/6s/nws8ng4d4wl4mr6jgt_kvzvr0000gn/T/lottie-ios SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/rosspatman/Documents/Apps/Core/concertlive.core.ios/Carthage/Checkouts/lottie-ios)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/6s/nws8ng4d4wl4mr6jgt_kvzvr0000gn/T/carthage-xcodebuild.VuP5c8.log`

and the log file:
`Ld /Users/rosspatman/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/lottie-ios/2.5.0/Build/Intermediates.noindex/ArchiveIntermediates/Lottie_tvOS/IntermediateBuildFilesPath/UninstalledProducts/appletvos/Lottie.framework/Lottie normal arm64
    cd /Users/rosspatman/Documents/Apps/Core/concertlive.core.ios/Carthage/Checkouts/lottie-ios
    export PATH="/Applications/Xcode-9.4.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/usr/bin:/Applications/Xcode-9.4.app/Contents/Developer/usr/bin:/Users/rosspatman/.nvm/versions/node/v10.0.0/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin"
    export TVOS_DEPLOYMENT_TARGET=9.0
    /Applications/Xcode-9.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -dynamiclib -isysroot /Applications/Xcode-9.4.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS11.4.sdk -L/Users/rosspatman/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/lottie-ios/2.5.0/Build/Intermediates.noindex/ArchiveIntermediates/Lottie_tvOS/BuildProductsPath/Release-appletvos -F/Users/rosspatman/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/lottie-ios/2.5.0/Build/Intermediates.noindex/ArchiveIntermediates/Lottie_tvOS/BuildProductsPath/Release-appletvos -filelist /Users/rosspatman/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/lottie-ios/2.5.0/Build/Intermediates.noindex/ArchiveIntermediates/Lottie_tvOS/IntermediateBuildFilesPath/Lottie.build/Release-appletvos/Lottie_tvOS.build/Objects-normal/arm64/Lottie.LinkFileList -install_name @rpath/Lottie.framework/Lottie -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -mtvos-version-min=9.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/rosspatman/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/lottie-ios/2.5.0/Build/Intermediates.noindex/ArchiveIntermediates/Lottie_tvOS/IntermediateBuildFilesPath/Lottie.build/Release-appletvos/Lottie_tvOS.build/Objects-normal/arm64/Lottie_lto.o -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/rosspatman/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/lottie-ios/2.5.0/Build/Intermediates.noindex/ArchiveIntermediates/Lottie_tvOS/BuildProductsPath/Release-appletvos -fobjc-arc -fobjc-link-runtime -fapplication-extension -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/rosspatman/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/lottie-ios/2.5.0/Build/Intermediates.noindex/ArchiveIntermediates/Lottie_tvOS/IntermediateBuildFilesPath/Lottie.build/Release-appletvos/Lottie_tvOS.build/Objects-normal/arm64/Lottie_dependency_info.dat -o /Users/rosspatman/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/lottie-ios/2.5.0/Build/Intermediates.noindex/ArchiveIntermediates/Lottie_tvOS/IntermediateBuildFilesPath/UninstalledProducts/appletvos/Lottie.framework/Lottie
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_LOTKeypath", referenced from:
      objc-class-ref in LOTAnimationTransitionController.o
      objc-class-ref in LOTAnimationView.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **

The following build commands failed:
	Ld /Users/rosspatman/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/lottie-ios/2.5.0/Build/Intermediates.noindex/ArchiveIntermediates/Lottie_tvOS/IntermediateBuildFilesPath/UninstalledProducts/appletvos/Lottie.framework/Lottie normal arm64
(1 failure)`

**Comment by eneko** [comment]
Hello @rossrossp, I was just having the same issue while prepping our project for Xcode 10/Swift 4.2.

I've updated our `Cartfile` to point to "master" and now it builds properly:

```
github "airbnb/lottie-ios" "master"
```

```bash
$ carthage update --cache-builds
[...]
*** Building scheme "Lottie" in Lottie.xcodeproj
*** Building scheme "Lottie_tvOS" in Lottie.xcodeproj
*** Building scheme "Lottie_macOS" in Lottie.xcodeproj
[...]
```

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC

**Comment by gevorg94** [comment]
use
`github "airbnb/lottie-ios" "lottie/objectiveC"`
for ObjectiveC project.
