### ISSUE TITLE
[LOTAnimationView animationNamed:]: unrecognized selector sent to class

### ISSUE THREAD

**Issue by kapoorsahil** [airbnb/lottie-ios#702]
## Check these before submitting:

- [x] Updated to the latest version of Lottie (2.5.0)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Crashing Bug
- [x] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 
- [x] iOS

## Expected Behavior 
`+[LOTAnimationView animationNamed:] should initialize lottie`

## Code
`private var animatingView: LOTAnimationView?`
`animatingView = LOTAnimationView(name: "TrolleyLoader")`

## Crash
`+[LOTAnimationView animationNamed:]: unrecognized selector sent to class 0x104ce04b0`

## Animation JSON
All files in the project.

Issue is happening when using 'ExpressCheckout' cocoapod.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
