### ISSUE TITLE
iOS View Controller Transitioning has wrong layout

### ISSUE THREAD

**Issue by alexkiri** [airbnb/lottie-ios#703]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0); also tried the latest version on the repo using `pod 'lottie-ios',  :git => 'https://github.com/airbnb/lottie-ios.git'`
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [ ] MacOS
- [x] iOS

## Expected Behavior 
![Alt text](https://raw.githubusercontent.com/airbnb/lottie-ios/master/_Gifs/transitionMasked.gif)

## Actual Behavior
![out2](https://user-images.githubusercontent.com/6061770/45105049-17305e00-b13c-11e8-80ba-42d9c6f69a4f.gif)

## Code Example
It's the unchange code from the lottie-ios-Example project, included in the repo. I have edited the Podfile in order to use the latest official release, as well as the most recent version

The layout is completely wrong. I tried to debug the LOTAnimationTransitionController, but as far as I can tell, everything seems ok in the animateTransition: method.

**Comment by mikeKane** [comment]
Yes, I've downloaded the Sample Project and ran it on my iPhone X iOS 12.1 and the animation transitions are broken. Hopefully there will be fa fix soon.

**Comment by carlosfernandez** [comment]
I can confirm this is still happening with Lottie 2.5.2

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
