### ISSUE TITLE
why the animation stops when the UI is loaded?

### ISSUE THREAD

**Issue by liguangyi1991** [airbnb/lottie-ios#707]
I've created five animated views in the controller View controller, and when I go into the controller the regression is slow, and when I have UI creation the animation stops

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
