### ISSUE TITLE
README is using deprecated APIs that don't do anything

### ISSUE THREAD

**Issue by marcelofabri** [airbnb/lottie-ios#709]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [ ] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [ ] Feature Request
- [x] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 
- [ ] MacOS
- [x] iOS

## Expected Behavior 

Following the README I'd be able to make a dynamic animation by using methods like:

```swift
animationView.setValue(UIColor.darkGray, forKeypath: "OuterRing.Stroke.Color", atFrame: 0)
```

## Actual Behavior

That method is deprecated and logs a warning during runtime saying that it won't have any effect. README should mention the `setValueDelegate` method, as [the docs](http://airbnb.io/lottie/ios/dynamic.html#).

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
