### ISSUE TITLE
Accessing single compositions in json file

### ISSUE THREAD

**Issue by millertfin** [airbnb/lottie-ios#717]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [x] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [x] iOS

is it possible to access and play single compositions inside a lottie json file, as secondary animations alongside a central composition?

Use case:
* One composition, showing a growing box. The size (property: animationProgress) is bound to some number input or slider value
* Multiple secondary compositions to illustrate that something was put into that box.

One of those secondary animations shall get played randomly at a time, if a conditions is meet.

Apparently I can access a composition element, via a LOTKeyPath. But theres seems to be no way to convert them in playable animations.

I'm working with Xcode 10 / Swift 4 on iOS 11

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
