### ISSUE TITLE
Analyzer Issue in LOTComposition.m

### ISSUE THREAD

**Issue by steipete** [airbnb/lottie-ios#718]
I noticed Analyzer issues using Xcode 10 GM.

<img width="1312" alt="screenshot 2018-10-10 at 09 23 08" src="https://user-images.githubusercontent.com/58493/46719435-2ee49000-cc6e-11e8-8b13-5613e93f9723.png">

I added a local variable to compensate:

```
NSNumber *framerate = _framerate ?: @(60);
```

<img width="909" alt="screenshot 2018-10-10 at 09 28 14" src="https://user-images.githubusercontent.com/58493/46719678-d3ff6880-cc6e-11e8-96e7-a7e1fcbe4eeb.png">

I am not familiar with the codebase so don't feel confident enough to make a PR.
What is the default frame-rate? What happens if that is missing from the definition file?

(Lottie 2.5.2/iOS here)

## Check these before submitting:
- [X] Updated to the latest version of Lottie (2.5.0)
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)

## What Platform are you on? 
- [X] iOS

## Expected Behavior
No Analyzer warning.

## Actual Behavior
Analyzer warning.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
