### ISSUE TITLE
separate dimensions position

### ISSUE THREAD

**Issue by bitwisp** [airbnb/lottie-ios#720]
If I use separate dimensions on the position and animate, it does not work.
Is there a way to make it work?

I tried using expressions or linking multiple layers for the animation, but nothing works...

**Comment by buba447** [comment]
Expressions are not supported

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
