### ISSUE TITLE
iPhone is overheating while lottie animation is playing?

### ISSUE THREAD

**Issue by romansorochak** [airbnb/lottie-ios#722]
Hello 

I'm experiencing overheating while lottie animation is playing. 
I have full screen lottie animation that plays in a loop.
To check the issue I tried to remove lottie animation and iphone stopped overheating.

I saw a bit similar issue for Android platform.
It is said to try to set 
setSubframes(false)
but I cannot find this function in Lottie iOS.

Could anyone help ?

Thanks in advance!

**Comment by buba447** [comment]
If you are making extensive use of masks, images, or gradients, it could cause the iPhone to warm up as these are heavy CPU intensive features.
