### ISSUE TITLE
Access and replace the Lottie  Layer group in iOS 

### ISSUE THREAD

**Issue by animios** [airbnb/lottie-ios#723]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Feature Request

## What Platform are you on? 

- [x] iOS

## Expected Behavior 
Hello,

I'm trying to change the layer group with similar layer group. But I cannot able to access the layer group and trying to finding the layers subgroup in the JSON leads to looping issue, So I'm try to figure it out to replace the layer group with other. 

Eg: I have a Lottie JSON animation file contain a MacBook on a table and I'm going to replace the MacBook layer group with iMac layer JSON file.  How could I do this with the help of Lottie?

Could anyone help ?

Thanks in advance!

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
