### ISSUE TITLE
How to use Lottie In SpriteKit

### ISSUE THREAD

**Issue by amannayak0007** [airbnb/lottie-ios#724]
## Check these before submitting:
- [] Updated to the latest version of Lottie (2.5.0)
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [Lottie In SpriteKit] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [iOS] iOS

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC

**Comment by kvaDrug** [comment]
I believe this issue may be reopened. Lottie now supports only UIKit. But it would be cool to use it in games, for this purpose SpriteKit support is required. We need something like `LottiNode` which can be inserted into `SKScene`.

**Comment by pavelreva1998** [comment]
Agree with the comment above, need to be reopened

**Comment by matthewdovey** [comment]
Can't wait for this feature! will unlock big things for Spritekit.
