### ISSUE TITLE
Is the JSON Structure specified anywhere for iOS ?

### ISSUE THREAD

**Issue by animios** [airbnb/lottie-ios#725]
I can't find anywhere that explains the structure of the JSON file. We would like to potential change it at runtime and I was wondering if it was explained anywhere. I'd like to see how all the layers are grouping in the current format.

**Comment by DavidBertet** [comment]
Did you read the documentation mentioned here #575 ?

**Comment by buba447** [comment]
https://raw.githubusercontent.com/airbnb/lottie-ios/529b48545411e08949a59f065762dc8e36eec0bd/Lotte/LotteJsonTaxonomy
