### ISSUE TITLE
Modify a value on existing keyframe

### ISSUE THREAD

**Issue by DavidBertet** [airbnb/lottie-ios#726]
I want to slightly modify my animation by moving the starting point of a layer, depending on external conditions

With the deprecated version of the API `setValue:forKeyPath:atFrame` I was able to change the value for a specific frame and the animation was interpolated, but with the new one `setValueDelegate:forKeyPath` it seems impossible.
There is an example with the `LOTPointInterpolatorCallback` but it is a trivial translation with only 2 keyframes. I don't wan't to recreate the whole translation in code as its not the point of Lottie.

With the new API, is it possible to change a value for a keyframe that exists in the source file ?

**Comment by clakk** [comment]
Looks like I'm having a similar problem. I'd want to change the ending point of a layer to avoid using LOTPointInterpolatorCallback and redo the translation in code.
Did you find a solution to this?

**Comment by buba447** [comment]
You can use the LOTPointInterpolatorCallback to change a single keyframe, without recreating all keyframes, though it will be a bit more work than the previous API.

The LOTPointInterpolatorCallback passes in the frame, progress, and what the value would be for each rendered frame. Check if the frame passed in is in the range that you want to change, if not just return the value that lottie gives you and the animation will continue as normal. Once you get into the range that you want to change you will have to calculate your new interpolation manually, which is a bit of a pain in the butt.

**Comment by clakk** [comment]
Thanks a lot for your clarification!

In the end, I just used the LOTPointInterpolatorCallback with the start and end point, using a Timer to move the progress and the image.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
