### ISSUE TITLE
use this json have a issue

### ISSUE THREAD

**Issue by erduoniba** [airbnb/lottie-ios#727]
## Check these before submitting:
Lottie (2.5.0)

## What Platform are you on? 
iOS

## Code Example
    LOTAnimationView *_animation1 = [LOTAnimationView animationNamed:@"follow"];
    _animation1.contentMode = UIViewContentModeScaleToFill;
    [self.view addSubview:_animation1];
    _animation1.frame = CGRectMake(100, 100, 50, 50);
    _animation1.animationSpeed = 2;
    [_lastA play];

## Animation JSON 
[follow.json.zip](https://github.com/airbnb/lottie-ios/files/2508921/follow.json.zip)

**Comment by erduoniba** [comment]
![image](https://user-images.githubusercontent.com/6082855/47405301-852ff380-d783-11e8-9bff-7d67f4244906.png)
this is iOS result

![image](https://user-images.githubusercontent.com/6082855/47405373-d17b3380-d783-11e8-9892-1dcf012ac1c1.png)
this is Android result

**Comment by tingxins** [comment]
I've the same problem.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
