### ISSUE TITLE
Add image support

### ISSUE THREAD

**Issue by Harvey4431** [airbnb/lottie-ios#73]
my animator need to operate some .png img ,build a new folder "images" and put .png file in it .
json like this:"
{
"assets": [
{
"id": "image_0",
"w": 960,
"h": 540,
"u": "images/",
"p": "img_0.png"
}
],
...
} "
but I has run app ,can't see anything without empty

**Comment by definefeeling** [comment]
i use ae app create a aep file and contain a png,export it.use lottie open and show empty.

**Comment by paulsumit1993** [comment]
Image support is on the [roadmap.](https://github.com/airbnb/lottie-ios#roadmap-in-no-particular-order)
see #14

**Comment by buba447** [comment]
Gonna close this as its a duplicate issue :)

**Comment by joel-petersen** [comment]
@buba447 Looks like both issues for image support got closed, what is the timeline for images or parent support for custom children? Are you guys up for proposed solutions?

**Comment by buba447** [comment]
@joel-petersen We have added image support :)

**Comment by jeffreylyg** [comment]
@buba447 hi, is there a document for how to use images? I add images to my project but they can not be showed.

**Comment by leimingdu** [comment]
Hi all,

after investigate the code, I found the right usage of image for iOS:

in the json file, just replace "id" with the animation name, and images as the picture.

{"assets":[{"id":"image_0","w":800,"h":678,"u":"images/","p":"img_0.png"}]

it works.

**Comment by leimingdu** [comment]
one word more, need also change the "refId":"image_0" as the animation name.

**Comment by bujordet** [comment]
Do you have an working example, @leimingdu ?
So we can see the different?

**Comment by leimingdu** [comment]
Yes, for example.

**Comment by leimingdu** [comment]
{"assets":[{"id":"image_0","w":296,"h":162,"u":"images/","p":"guide_addtext_popup.png"},{"id":"image_1","w":148,"h":126,"u":"images/","p":"guide_addtext_hand.png"}],"layers":[{"ddd":0,"ind":0,"ty":2,"nm":"text pop up@2x.png","cl":"png","refId":"image_0","ks":{"o":{"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":95,"s":[0],"e":[100]},{"t":102}]},"r":{"k":0},"p":{"k":[{"i":{"x":1,"y":1},"o":{"x":0.597,"y":0.748},"n":"1_1_0p597_0p748","t":95,"s":[290,81,0],"e":[290,142,0],"to":[0,10.1666669845581,0],"ti":[0,-5.16666650772095,0]},{"i":{"x":0.654,"y":1},"o":{"x":0.167,"y":0.167},"n":"0p654_1_0p167_0p167","t":102,"s":[290,142,0],"e":[290,112,0],"to":[0,5.16666650772095,0],"ti":[0,0,0]},{"i":{"x":1,"y":1},"o":{"x":0.576,"y":0},"n":"1_1_0p576_0","t":130,"s":[290,112,0],"e":[290,142,0],"to":[0,0,0],"ti":[0,0,0]},{"i":{"x":0.928,"y":1},"o":{"x":0.154,"y":0.713},"n":"0p928_1_0p154_0p713","t":138,"s":[290,142,0],"e":[290,368,0],"to":[0,37.6666679382324,0],"ti":[0,-37.6666679382324,0]},{"t":145}]},"a":{"k":[148,81,0]},"s":{"k":[100,100,100]}},"ao":0,"ip":77,"op":146,"st":-285,"bm":0,"sr":1},{"ddd":0,"ind":2,"ty":2,"nm":"hand@2x.png","cl":"png","refId":"image_1","ks":{"o":{"k":100},"r":{"k":0},"p":{"k":[{"i":{"x":1,"y":0},"o":{"x":0.167,"y":0},"n":"1_0_0p167_0","t":0,"s":[224,84.75,0],"e":[224,84.75,0],"to":[9.47390342581232e-15,-2.36847585645308e-15,0],"ti":[0,0,0]},{"i":{"x":0.74,"y":0},"o":{"x":0.298,"y":0.616},"n":"0p74_0_0p298_0p616","t":23,"s":[224,84.75,0],"e":[202,84.75,0],"to":[-3.66666674613953,-2.36847585645308e-15,0],"ti":[-29.6666660308838,10.5,0]},{"i":{"x":0.149,"y":1},"o":{"x":0.258,"y":0.286},"n":"0p149_1_0p258_0p286","t":46,"s":[202,84.75,0],"e":[414,84.75,0],"to":[29.8520603179932,-10.565616607666,0],"ti":[-35.3333320617676,0,0]},{"t":79}]},"a":{"k":[0,0,0]},"s":{"k":[{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"n":["0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167"],"t":0,"s":[100,100,100],"e":[80,80,100]},{"i":{"x":[0.667,0.667,0.667],"y":[0.667,0.667,0.667]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"n":["0p667_0p667_0p167_0p167","0p667_0p667_0p167_0p167","0p667_0p667_0p167_0p167"],"t":16,"s":[80,80,100],"e":[80,80,100]},{"i":{"x":[0.667,0.667,0.667],"y":[1,1,0.667]},"o":{"x":[0.876,0.876,0.333],"y":[-0.02,-0.02,0.333]},"n":["0p667_1_0p876_-0p02","0p667_1_0p876_-0p02","0p667_0p667_0p333_0p333"],"t":81,"s":[80,80,100],"e":[110,110,100]},{"t":89}]}},"ao":0,"ip":0,"op":92,"st":0,"bm":0,"sr":1},{"ddd":0,"ind":3,"ty":4,"nm":"touch","parent":2,"ks":{"o":{"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":0,"s":[100],"e":[50]},{"t":16}]},"r":{"k":0},"p":{"k":[10.4,9.462,0]},"a":{"k":[-61.88,-50.13,0]},"s":{"k":[{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"n":["0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167"],"t":0,"s":[30,30,100],"e":[125,125,100]},{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"n":["0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167"],"t":16,"s":[125,125,100],"e":[125,125,100]},{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"n":["0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167"],"t":81,"s":[125,125,100],"e":[33,33,100]},{"t":86}]}},"ao":0,"shapes":[{"ty":"gr","it":[{"d":1,"ty":"el","s":{"k":[46.739,46.739]},"p":{"k":[0,0]},"nm":"Ellipse Path 1","mn":"ADBE Vector Shape - Ellipse"},{"ty":"st","fillEnabled":true,"c":{"k":[1,0.15,0.44,1]},"o":{"k":100},"w":{"k":0},"lc":1,"lj":1,"ml":4,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke"},{"ty":"fl","fillEnabled":true,"c":{"k":[1,1,1,1]},"o":{"k":100},"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill"},{"ty":"tr","p":{"k":[-61.88,-50.13],"ix":2},"a":{"k":[0,0],"ix":1},"s":{"k":[100,100],"ix":3},"r":{"k":0,"ix":6},"o":{"k":100,"ix":7},"sk":{"k":0,"ix":4},"sa":{"k":0,"ix":5},"nm":"Transform"}],"nm":"Ellipse 1","np":3,"mn":"ADBE Vector Group"}],"ip":0,"op":92,"st":0,"bm":0,"sr":1}],"v":"4.5.0","ddd":0,"ip":0,"op":160,"fr":30,"w":580,"h":280}
