### ISSUE TITLE
lottie Animation doesn't work as expected on iOS but working on Android

### ISSUE THREAD

**Issue by xinsting** [airbnb/lottie-ios#730]
## Problem

lottie Animation **doesn't work as expected on iOS** but **working on Android**. (lottie-iOS **v2.5.2**)

## What Platform are you on? 
* iOS

## Expected Behavior 
![image](https://user-images.githubusercontent.com/26273816/47844078-71783300-ddfc-11e8-98f3-476953da8544.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/26273816/47844132-8ead0180-ddfc-11e8-8f61-c36ffebe8e1d.png)

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
