### ISSUE TITLE
Individually Trimming Paths Doesn't Work

### ISSUE THREAD

**Issue by CentrumGuy** [airbnb/lottie-ios#731]
## Check these before submitting:
- [X] Updated to the latest version of Lottie (2.5.0)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [X] iOS

## Expected Behavior 

<img width="1434" alt="screen shot 2018-11-05 at 11 36 50 am" src="https://user-images.githubusercontent.com/6200459/48012604-679e4a80-e0f0-11e8-97f7-5ca5d9716972.png">
I would like these separate paths to trim individually. This is a feature that lottie-ios says is supported but when I run the actual animation...

## Actual Behavior

The shapes trim simultaneously. I've uploaded the file so you could try this out for yourself.
[Animation.zip](https://github.com/airbnb/lottie-ios/files/2549681/Animation.zip)
Go to lottie preview and try to preview the animation.
The internet renders the animation the way I want it to render however, using the lottie preview app on my iPhone, the shapes trim together and not individually
## Code Example
- No code requred

## Animation JSON

[Animation.zip](https://github.com/airbnb/lottie-ios/files/2549684/Animation.zip)
Animation is attached in the zip file

**Comment by CentrumGuy** [comment]
Does anyone know a solution to this issue???

**Comment by buba447** [comment]
This now works in Lottie 3.0

Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
