### ISSUE TITLE
Lottie Animations looks different on iOS

### ISSUE THREAD

**Issue by galadril** [airbnb/lottie-ios#732]
## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 
- [] MacOS
- [X] iOS

### Expected behavior :thinking:
I use the lottie library for Xamarin Forms, and the same animation file should renderer the same on iOS and Android.

### Actual behavior :bug:
This ship animation looks different on Android / iOS

**Android:**
![afbeelding](https://user-images.githubusercontent.com/14561640/47841856-3e617f80-ddbb-11e8-9104-63cde99223f6.png)

**iOS:**
![afbeelding](https://user-images.githubusercontent.com/14561640/47841867-428d9d00-ddbb-11e8-86b2-fd454f8b07c5.png)

## Animation JSON
Please PM me for a lottie json file (can't share it on github)

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
