### ISSUE TITLE
Child layer not transforming properly when parent is transformed in iOS

### ISSUE THREAD

**Issue by Shubhayu** [airbnb/lottie-ios#735]
## Check these before submitting:
- [] Updated to the latest version of Lottie (2.5.0)
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [X] iOS

## Expected Behavior 
Child Layers should transform automatically and correctly when the parent is transformed. Parent has rotation in it. Parent's position is transformed. But the child's position is not updated.

## Actual Behavior
I am using an Image Layer based Lottie Animation file and the design has been done such that my animation is at the centre of the Animation View. I am trying to move this to the Bottom-Left corner using "Transform.Position" in iOS and Transform_Position property in Android.

My animation consists of a few top level layers (hand, leg, body) and a few layers (eyes, mouth) that have "body" as the parent layer. This works fine in Android but in iOS, the top levels get translated properly, but the child layers are not offsetting themselves based on the parent. When I explicitly try to offset them, it works as long as there is no rotation. The layers that have rotation behave in a very strange way.

## Code Example
```
class PointCallback : LOTPointValueDelegate
{
    public override CGPoint StartKeyframe(nfloat currentFrame, nfloat startKeyframe, nfloat endKeyframe, nfloat interpolatedProgress, CGPoint startPoint, CGPoint endPoint, CGPoint interpolatedPoint)
    {
        CGPoint newPosi = new CGPoint(interpolatedPoint);
        newPosi.X -= 200;
        newPosi.Y += 200;
        return newPosi;
    }
}

_animationView.SetValueDelegate(new PointCallback(), LOTKeypath.KeypathWithString("body1.Transform.Position"));
_animationView.SetValueDelegate(new PointCallback(), LOTKeypath.KeypathWithString("left hand1.Transform.Position"));
_animationView.SetValueDelegate(new PointCallback(), LOTKeypath.KeypathWithString("right hand1.Transform.Position"));
_animationView.SetValueDelegate(new PointCallback(), LOTKeypath.KeypathWithString("acc1.Transform.Position"));
_animationView.SetValueDelegate(new PointCallback(), LOTKeypath.KeypathWithString("mouth1.Transform.Position"));
```
## Animation JSON
[Roll_In.zip](https://github.com/airbnb/lottie-ios/files/2606345/Roll_In.zip)

**Comment by buba447** [comment]
Lottie does not maintain a atrong reference to value callbacks. In the example your value callbacks will be released unless you hold reference to them.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
