### ISSUE TITLE
About playing speed

### ISSUE THREAD

**Issue by syyjay** [airbnb/lottie-ios#743]
## Lottie-iOS Issue
In the latest version, the animation is abnormal, and in version 2.1.0, it is normal, but the playback speed is slow after exporting video

- (void)videoOutput
{
    // 1 - Early exit if there's no video file selected
    if (!self.videoAsset) {
        UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"Error" message:@"Please Load a Video Asset First"
                                                       delegate:nil cancelButtonTitle:@"OK" otherButtonTitles:nil];
        [alert show];
        return;
    }
    
    // 2 - Create AVMutableComposition object. This object will hold your AVMutableCompositionTrack instances.
    AVMutableComposition *mixComposition = [[AVMutableComposition alloc] init];
    
    // 3 - Video track
    CMTime rangeTime=CMTimeMakeWithSeconds(self.lotView.animationDuration, 25);
    AVMutableCompositionTrack *videoTrack = [mixComposition addMutableTrackWithMediaType:AVMediaTypeVideo
                                                                        preferredTrackID:kCMPersistentTrackID_Invalid];
    [videoTrack insertTimeRange:CMTimeRangeMake(kCMTimeZero, rangeTime)
                        ofTrack:[[self.videoAsset tracksWithMediaType:AVMediaTypeVideo] objectAtIndex:0]
                         atTime:kCMTimeZero error:nil];
    
    // 3.1 - Create AVMutableVideoCompositionInstruction
    AVMutableVideoCompositionInstruction *mainInstruction = [AVMutableVideoCompositionInstruction videoCompositionInstruction];
    mainInstruction.enablePostProcessing=YES;
    mainInstruction.timeRange = CMTimeRangeMake(kCMTimeZero,rangeTime);
    
    // 3.2 - Create an AVMutableVideoCompositionLayerInstruction for the video track and fix the orientation.
    AVMutableVideoCompositionLayerInstruction *videolayerInstruction = [AVMutableVideoCompositionLayerInstruction videoCompositionLayerInstructionWithAssetTrack:videoTrack];
    

    [videolayerInstruction setOpacity:0.0 atTime:rangeTime];
    
    // 3.3 - Add instructions
    mainInstruction.layerInstructions = [NSArray arrayWithObjects:videolayerInstruction,nil];
    
    AVMutableVideoComposition *mainCompositionInst = [AVMutableVideoComposition videoComposition];
    
    CGSize naturalSize=self.videoAsset.naturalSize;

    float renderWidth, renderHeight;
    renderWidth = naturalSize.width;
    renderHeight = naturalSize.height;
    mainCompositionInst.renderSize = CGSizeMake(renderWidth, renderHeight);
    mainCompositionInst.instructions = [NSArray arrayWithObject:mainInstruction];
    mainCompositionInst.frameDuration = CMTimeMake(1, 25);
    
    [self applyVideoEffectsToComposition:mainCompositionInst size:naturalSize];
    
    // 4 - Get path
    NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
    NSString *documentsDirectory = [paths objectAtIndex:0];
    NSString *myPathDocs =  [documentsDirectory stringByAppendingPathComponent:
                             [NSString stringWithFormat:@"FinalVideo-%d.mov",arc4random() % 1000]];
    NSURL *url = [NSURL fileURLWithPath:myPathDocs];
    
    // 5 - Create exporter
    AVAssetExportSession *exporter = [[AVAssetExportSession alloc] initWithAsset:mixComposition
                                                                      presetName:AVAssetExportPresetHighestQuality];
    exporter.outputURL=url;
    exporter.outputFileType = AVFileTypeQuickTimeMovie;
    exporter.shouldOptimizeForNetworkUse = YES;
    exporter.videoComposition = mainCompositionInst;
    [exporter exportAsynchronouslyWithCompletionHandler:^{
        dispatch_async(dispatch_get_main_queue(), ^{
            [self exportDidFinish:exporter];
        });
    }];
}

- (void)applyVideoEffectsToComposition:(AVMutableVideoComposition *)composition size:(CGSize)size
{
    
    
    CALayer *parentLayer = [CALayer layer];
    CALayer *videoLayer = [CALayer layer];
    parentLayer.frame = CGRectMake(0, 0, size.width, size.height);
    videoLayer.frame = CGRectMake(0, 0, size.width, size.height);
    [parentLayer addSublayer:videoLayer];
    self.lotView.layer.frame=parentLayer.bounds;
    [parentLayer addSublayer:self.lotView.layer];

    
    composition.animationTool = [AVVideoCompositionCoreAnimationTool
                                 videoCompositionCoreAnimationToolWithPostProcessingAsVideoLayer:videoLayer inLayer:parentLayer];
}

## Animation JSON

[jsonT.txt](https://github.com/airbnb/lottie-ios/files/2642427/jsonT.txt)
![img_0](https://user-images.githubusercontent.com/8310177/49419147-9b889080-f7c0-11e8-8c87-79dc11e5b087.png)
[img_4](https://user-images.githubusercontent.com/8310177/49419148-9b889080-f7c0-11e8-9156-0b1d951af7f8.png)
[img_6](https://user-images.githubusercontent.com/8310177/49419152-9e838100-f7c0-11e8-987b-ad703e48672f.png)
[img_1](https://user-images.githubusercontent.com/8310177/49419154-9f1c1780-f7c0-11e8-985f-7b9e9c0b68e6.png)
[img_2](https://user-images.githubusercontent.com/8310177/49419156-9fb4ae00-f7c0-11e8-9b64-6d5e5035ddca.png)
[img_5](https://user-images.githubusercontent.com/8310177/49419157-a04d4480-f7c0-11e8-800b-36bffb41ab5b.png)
[img_3](https://user-images.githubusercontent.com/8310177/49419158-a0e5db00-f7c0-11e8-8b1a-9b534afb7393.png)

**Comment by syyjay** [comment]
About playing speed

**Comment by smallqiang** [comment]
> ## Lottie-iOS Issue
> In the latest version, the animation is abnormal, and in version 2.1.0, it is normal, but the playback speed is slow after exporting video
> 
> * (void)videoOutput
>   {
>   // 1 - Early exit if there's no video file selected
>   if (!self.videoAsset) {
>   UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"Error" message:@"Please Load a Video Asset First"
>   delegate:nil cancelButtonTitle:@"OK" otherButtonTitles:nil];
>   [alert show];
>   return;
>   }
>   // 2 - Create AVMutableComposition object. This object will hold your AVMutableCompositionTrack instances.
>   AVMutableComposition *mixComposition = [[AVMutableComposition alloc] init];
>   // 3 - Video track
>   CMTime rangeTime=CMTimeMakeWithSeconds(self.lotView.animationDuration, 25);
>   AVMutableCompositionTrack *videoTrack = [mixComposition addMutableTrackWithMediaType:AVMediaTypeVideo
>   preferredTrackID:kCMPersistentTrackID_Invalid];
>   [videoTrack insertTimeRange:CMTimeRangeMake(kCMTimeZero, rangeTime)
>   ofTrack:[[self.videoAsset tracksWithMediaType:AVMediaTypeVideo] objectAtIndex:0]
>   atTime:kCMTimeZero error:nil];
>   // 3.1 - Create AVMutableVideoCompositionInstruction
>   AVMutableVideoCompositionInstruction *mainInstruction = [AVMutableVideoCompositionInstruction videoCompositionInstruction];
>   mainInstruction.enablePostProcessing=YES;
>   mainInstruction.timeRange = CMTimeRangeMake(kCMTimeZero,rangeTime);
>   // 3.2 - Create an AVMutableVideoCompositionLayerInstruction for the video track and fix the orientation.
>   AVMutableVideoCompositionLayerInstruction *videolayerInstruction = [AVMutableVideoCompositionLayerInstruction videoCompositionLayerInstructionWithAssetTrack:videoTrack];
>   [videolayerInstruction setOpacity:0.0 atTime:rangeTime];
>   // 3.3 - Add instructions
>   mainInstruction.layerInstructions = [NSArray arrayWithObjects:videolayerInstruction,nil];
>   AVMutableVideoComposition *mainCompositionInst = [AVMutableVideoComposition videoComposition];
>   CGSize naturalSize=self.videoAsset.naturalSize;
>   float renderWidth, renderHeight;
>   renderWidth = naturalSize.width;
>   renderHeight = naturalSize.height;
>   mainCompositionInst.renderSize = CGSizeMake(renderWidth, renderHeight);
>   mainCompositionInst.instructions = [NSArray arrayWithObject:mainInstruction];
>   mainCompositionInst.frameDuration = CMTimeMake(1, 25);
>   [self applyVideoEffectsToComposition:mainCompositionInst size:naturalSize];
>   // 4 - Get path
>   NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
>   NSString *documentsDirectory = [paths objectAtIndex:0];
>   NSString *myPathDocs =  [documentsDirectory stringByAppendingPathComponent:
>   [NSString stringWithFormat:@"FinalVideo-%d.mov",arc4random() % 1000]];
>   NSURL *url = [NSURL fileURLWithPath:myPathDocs];
>   // 5 - Create exporter
>   AVAssetExportSession *exporter = [[AVAssetExportSession alloc] initWithAsset:mixComposition
>   presetName:AVAssetExportPresetHighestQuality];
>   exporter.outputURL=url;
>   exporter.outputFileType = AVFileTypeQuickTimeMovie;
>   exporter.shouldOptimizeForNetworkUse = YES;
>   exporter.videoComposition = mainCompositionInst;
>   [exporter exportAsynchronouslyWithCompletionHandler:^{
>   dispatch_async(dispatch_get_main_queue(), ^{
>   [self exportDidFinish:exporter];
>   });
>   }];
>   }
> * (void)applyVideoEffectsToComposition:(AVMutableVideoComposition *)composition size:(CGSize)size
>   {
>   CALayer *parentLayer = [CALayer layer];
>   CALayer *videoLayer = [CALayer layer];
>   parentLayer.frame = CGRectMake(0, 0, size.width, size.height);
>   videoLayer.frame = CGRectMake(0, 0, size.width, size.height);
>   [parentLayer addSublayer:videoLayer];
>   self.lotView.layer.frame=parentLayer.bounds;
>   [parentLayer addSublayer:self.lotView.layer];
>   composition.animationTool = [AVVideoCompositionCoreAnimationTool
>   videoCompositionCoreAnimationToolWithPostProcessingAsVideoLayer:videoLayer inLayer:parentLayer];
>   }
> 
> ## Animation JSON
> [jsonT.txt](https://github.com/airbnb/lottie-ios/files/2642427/jsonT.txt)
> ![img_0](https://user-images.githubusercontent.com/8310177/49419147-9b889080-f7c0-11e8-8c87-79dc11e5b087.png)
> [img_4](https://user-images.githubusercontent.com/8310177/49419148-9b889080-f7c0-11e8-9156-0b1d951af7f8.png)
> [img_6](https://user-images.githubusercontent.com/8310177/49419152-9e838100-f7c0-11e8-987b-ad703e48672f.png)
> [img_1](https://user-images.githubusercontent.com/8310177/49419154-9f1c1780-f7c0-11e8-985f-7b9e9c0b68e6.png)
> [img_2](https://user-images.githubusercontent.com/8310177/49419156-9fb4ae00-f7c0-11e8-9b64-6d5e5035ddca.png)
> [img_5](https://user-images.githubusercontent.com/8310177/49419157-a04d4480-f7c0-11e8-800b-36bffb41ab5b.png)
> [img_3](https://user-images.githubusercontent.com/8310177/49419158-a0e5db00-f7c0-11e8-8b1a-9b534afb7393.png)

I export the video. But the LOTAnimationView is not show animation. Can u help me to solve it.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
