### ISSUE TITLE
Problem with Rubberhose on iOS devices

### ISSUE THREAD

**Issue by MrLizer** [airbnb/lottie-ios#745]
https://www.lottiefiles.com/share/K4ePIo

Hopefully the link above works ok, this is a super simple wave animation using Bodymovin and Rubber Hose the preview works fine in the browser but breaks when viewed on an iOS device and I can not figure out why!

[WaveTest.aep.zip](https://github.com/airbnb/lottie-ios/files/2662932/WaveTest.aep.zip)

**Comment by MrLizer** [comment]
Pushing this up to try and get an response!?

**Comment by buba447** [comment]
Hello!
Sorry you are having troubles! The problem almost certainly has to do with
expressions. Rubberhose uses expressions in after effects. Expressions are
supported by the Lottie Web Player, but are not supported by the mobile
players. You can bake the expressions to keyframes to fix the problem,
however this will increase the size of your animation files. Read more here
https://airbnb.io/lottie/after-effects/general-tips.html

**Comment by buba447** [comment]
Heres a quick tutorial https://academy.idomoo.com/en/support/solutions/articles/4000066468-baking-keyframes-and-parenting
