### ISSUE TITLE
Completion block is not restored with animation when re-attached to window

### ISSUE THREAD

**Issue by Liz-Wilson** [airbnb/lottie-ios#746]
## Check these before submitting:
- [✓] Updated to the latest version of Lottie (2.5.2)
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [✓] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [✓] iOS

## Expected Behavior 
When an animation is re-attached to the window after (e.g.) backgrounding the app, the completion block should be restored so that it is called when the animation completes.

## Actual Behavior
When an animation is re-attached to the window after (e.g.) backgrounding the app, the completion block is not restored and is never called.
This is because in the logic to handle the animation becoming detached, ```pause``` is called before the completion block is stored, and within the pause logic, the completion block is nilled.

## Code Example
```
    // The view is being detached, capture information that need to be restored later.
    if (_isAnimationPlaying) {
      [self pause];
      _shouldRestoreStateWhenAttachedToWindow = YES;
      _completionBlockToRestoreWhenAttachedToWindow = _completionBlock;
      _completionBlock = nil;
    }
```
The ```pause``` function calls through to ```callCompletionIfNecessary``` which nils the completion block:
```
- (void)_callCompletionIfNecessary:(BOOL)complete {
  if (self.completionBlock) {
    LOTAnimationCompletionBlock completion = self.completionBlock;
    self.completionBlock = nil;
    completion(complete);
  }
}
```

**Comment by Liz-Wilson** [comment]
Fix is PR'd here: https://github.com/airbnb/lottie-ios/pull/747

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
