### ISSUE TITLE
Latest master issues with Carthage framework

### ISSUE THREAD

**Issue by MKGitHub** [airbnb/lottie-ios#75]
Ran carthage update and tried adding the iOS framework as embedded, compiled and got this

![2017-02-10 at 22 51 05](https://cloud.githubusercontent.com/assets/535550/22846503/1fb8c772-efe8-11e6-9dfd-7a0072e5d53f.png)

**Comment by dcow** [comment]
I get the infamous: 

   Ineligible destinations for the "Lottie" scheme:
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device }
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Generic iOS Simulator Device }

When running `carthage update`.

**Comment by buba447** [comment]
@MKGitHub This is because we renamed the LAAnimationView to LOTAnimationView
I should've made it a major version update and notified everyone! Sorry!

@dcow your issue is due to the iOS version
