### ISSUE TITLE
Automatic calculation of the LOTAnimationView frame based on the element frame

### ISSUE THREAD

**Issue by alexanderkhitev** [airbnb/lottie-ios#750]
Hello! I have a task to replace the element from the animation with a regular static image. For a regular image, I will use a UIImageView which has a specific frame. Is it possible to somehow calculate the frame for LOTAnimationView, based on a specific element from JSON. For example, I set the frame not for LOTAnimationView, but for star shape, then LOTAnimationView automatically calculates its frame based on the aspect ratio of star shape.

## What Platform are you on? 

- [] MacOS
- [x] iOS

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
