### ISSUE TITLE
Unable to implement custom behaviour when app enters foreground or background.

### ISSUE THREAD

**Issue by MrAPolk** [airbnb/lottie-ios#753]
In the attached workspace, the app pauses the animation when it enters the background then only plays the animation again if the Accessibility setting "Reduce Motion" is disabled.

To replicate the issue do the following:

1. Open the Test app
2. Open the Settings app and navigate to General > Accessibility > Reduce Motion and enable Reduce Motion.
3. Open the Test app 

## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [x] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [x] iOS

## Expected Behavior 
Animation should stop when opening the app with the "Reduce Motion" Accessibility feature enabled.

## Actual Behavior
Animation continues to animate.

## Code Example
[Test.zip](https://github.com/airbnb/lottie-ios/files/2723551/Test.zip)

## Workaround Solution
Remove the AnimationView's observers for the `UIApplication.didEnterBackgroundNotification` & `UIApplication.willEnterForegroundNotification` notifications.

## Animation JSON
Can be found in attached project (even though the issue is not related to the animation JSON itself).

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
