### ISSUE TITLE
Exported frame rate seemingly ignored

### ISSUE THREAD

**Issue by AnimationsDeveloper** [airbnb/lottie-ios#756]
Lottie animations exported at 30 fps look the same as animations exported at 15 fps, 2 fps, etc in my iOS application. I've tried this in versions `2.5.0` and `2.5.2`. I also tried w/ `"master"`.

I don't really want to show animations at 2 fps. It's just a test value to prove that the exported frame rate is being ignored. I'm really looking for something like 15-20 fps.

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)

## What Platform are you on? 
- [x] iOS

## Expected Behavior 
Animations in iOS honor exported frame rate in json config. For example, `"fr":2` should show a really simple two-frame animation.

## Actual Behavior
Animations in iOS seemingly ignore exported frame rate in json config. For example, `"fr":2` shows an animation with much more than two frames per second.

**Comment by buba447** [comment]
Hello!
This is because Lottie runs natively inside of Apple's Core Animation library. On the iphone framerateis fixed at ~60. If you want the effect of a lower framerate you can bake keyframes and convert them to Hold keyframes. This will force a lower framerate by turning off interpolation. Cheers!

**Comment by sunil-targe** [comment]
```
 /// When "true" the animation will play back at the framerate encoded in the "Animation" model. When "false" the animation will play at the framerate of the device.

  /// Defaults to false
  public var respectAnimationFrameRate = false {
    didSet {
      animationLayer?.respectAnimationFrameRate = respectAnimationFrameRate
    }
  }

```
