### ISSUE TITLE
Release 2.5.2 not available in NPM

### ISSUE THREAD

**Issue by jeremybviseo** [airbnb/lottie-ios#760]
## Expected Behavior 
lottie-ios release 2.5.2 shoud be available in NPM

## Actual Behavior
Latest version available in npm is 2.5.0

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
