### ISSUE TITLE
crash when input chinese

### ISSUE THREAD

**Issue by supergithuber** [airbnb/lottie-ios#762]
## Check these before submitting:
- Updated to the latest version of Lottie (2.5.2)

## This issue is a:
- Crashing Bug

## What Platform are you on? 

- iOS 12.1

## Expected Behavior 
non crash

## Actual Behavior
crash in TypingDemoViewController, when I typing chinese

## Code Example
crash in AnimatedTextField.m file line 171
code: [newText replaceCharactersInRange:range withString:replacementString];

**Comment by buba447** [comment]
This is an issue with the example app no the lottie repo.
