### ISSUE TITLE
Changing LOTAnimationView frame size with UIView.animate just snaps to final frame

### ISSUE THREAD

**Issue by markohlebar** [airbnb/lottie-ios#763]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [ ] MacOS
- [x] iOS

## Expected Behavior 
The `LOTAnimationView` frame size change animates smoothly when calling 
```
UIView.animate(withDuration:) 
```
function.

## Actual Behavior
The `LOTAnimationView` animation layer just snaps to the final size instead of interpolating between initial and final values. 

![resize_issue](https://user-images.githubusercontent.com/148891/51758730-b099e580-20c6-11e9-88f0-55a5c47effcb.gif)

## Code Example

To reproduce this issue easily:
- download [Lottie](https://github.com/airbnb/lottie-ios/archive/master.zip)
- open `Example-Swift` project
- in `ViewController.swift`, replace the `@objc func startDownload(button: UIButton)` implementation with 
```
  @objc func startDownload(button: UIButton) {
    button.isHidden = true
    createDownloadTask()

    var frame = boatAnimation!.frame
    frame.size.width = frame.size.width / 2
    frame.size.height = frame.size.height / 2
    UIView.animate(withDuration: 5.0) {
        self.boatAnimation?.frame = frame
    }
  }
```
- run example, and press `Start Download`

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
