### ISSUE TITLE
How to export video or LOTAnimationView insert to a video?

### ISSUE THREAD

**Issue by smallqiang** [airbnb/lottie-ios#764]
I've tried (https://github.com/airbnb/lottie-ios/issues/30). The LOTAnimationView is added, but there is no animation. I don't know how to export the LOTAnimationView to video or add it to video. Thanks!

**Comment by smallqiang** [comment]
It can be exported on a real machine but not in an emulator. And the exported animation rates don't match.

**Comment by lvpengwei** [comment]
You can try this. [LottieInVideo](https://github.com/lvpengwei/LottieInVideo)

**Comment by smallqiang** [comment]
> You can try this. [LottieInVideo](https://github.com/lvpengwei/LottieInVideo)

Thanks! I try it.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
