### ISSUE TITLE
Animation not showing text in iOS.

### ISSUE THREAD

**Issue by parthadroja247** [airbnb/lottie-ios#765]
## This issue is a:
- Non-Crashing Bug (Visual or otherwise)

## What Platform are you on? 
- iOS

## Expected Behavior 
Animation should work as Lottie preview. Check https://www.lottiefiles.com/3641-start-button

## Actual Behavior
Animation works but there is no text "START" visible on the animation.

## Animation JSON
Json File
[start_button.json.zip](https://github.com/airbnb/lottie-ios/files/2799835/start_button.json.zip)

**Comment by parthadroja247** [comment]
> Text is not currently supported by ios Godspeed, Brandon
> […](#)

@buba447 Thanks for the update.

**Comment by brunomunizaf** [comment]
Still?

**Comment by jamalalayq** [comment]
Still?

**Comment by brunomunizaf** [comment]
For those who are still facing this, in my team we did a workaround: We had each letter on a separate layer from illustrator. Or you can do it straight into AE but click convert to shapes from text.
cc: @jamalalayq

**Comment by jamalalayq** [comment]
Thanks 😃 @brunomunizaf
