### ISSUE TITLE
Set animation image destination on iOS

### ISSUE THREAD

**Issue by clakk** [airbnb/lottie-ios#767]
Hi everyone!

I'm having some screen size issues with an animation. The animation in question moves an image from the center of the screen to a set position, which will have the UIImageView with the same image in it after the animation is removed from the superview. This works on the iPhone X simulator, but changing to a different screen size breaks the animation, moving the image to a different point than where the image will be.

I wanted to know if it's possible to set the animation's image destination before playing it, and possibly how to do this.

Thanks!

## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [x] iOS

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
