### ISSUE TITLE
Transform/Repeater: Not rendering Repeater instances of shape layers

### ISSUE THREAD

**Issue by DonMegaGB** [airbnb/lottie-ios#769]
This is a visual, non-crashing bug. I'm not 100% positive if I should report this issue to Lottie iOS, or bodymovin's repository, but I'll start here. 

I was tasked with making a falling confetti animation. I avoided using CC Particle World, as well as using randomized locations via expressions. 

The After Effects project is made using rows of animated "confetti noodle" shapes, which are comp'd together in a "confetti wave", which are then comp'd again to make the final falling confetti animation. I realize now in hindsight I could have probably done this differently... But. Anyway. 

The issue I've run into is repeater instances of a shape are not rendered in the Lottie Preview app or when ran from XCode's simulator, although these repeater instances are previewed both on the web and Android without any problems. I realize in the documentation that AE repeater transform "offset" is not supported, and it has not been changed (default of 0.0).

## Check these before submitting:
- [N/A?] Updated to the latest version of Lottie (2.5.0)
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features) 
**re: https://github.com/airbnb/lottie-ios#repeaters**
- [X] This issue isn't related to another open issue 
**Doesn't appear to be related to any open issues**

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [X] MacOS
**After Effects v16.0.1 (Build 48), Mojave 10.14.3 (18D42)**
**Bodymovin v5.3.4**
- [X] iOS 
**Lottie Preview App v2.5.2**

## Expected Behavior (All Shapes, works) 

![confetti-all-shapes](https://user-images.githubusercontent.com/21246353/52134854-242d7c80-260a-11e9-881c-284459a68319.PNG)

## Actual Behavior (Repeater, nodda)

![confetti-repeater](https://user-images.githubusercontent.com/21246353/52135881-77083380-260c-11e9-9cd9-57078e7178e4.PNG)

_Description of issue ^^^_ 

The layered comps are all being scaled in this final render, so the original shape instances, which are the only "confettis" that render, are basically clipped out due to that scaling (I'm doing this to effectively "zoom" into a more random looking area within the entire falling confetti comp).

After scratching my head for some time, a simple test using a lone rectangle with the default repeater applied showed me iOS simply doesn't respect/render this transform control. 

I've got the animation working, so I don't need someone to investigate or fix whatever the issue is right away in order to get my task done, this exercise just highlighted what I think is a problem. Repeater does not appear to be supported by Lottie iOS, currently. 

## Animation JSON

All Shapes:
JSON/Lottie preview URL: https://lottiefiles.com/share/2RmxFc

Repeater:
Lottie/JSON (Previews with web and Android) - https://lottiefiles.com/share/N2SPZF

AEP files: 
[Lottie-Falling-Confetti.zip](https://github.com/airbnb/lottie-ios/files/2822352/Lottie-Falling-Confetti.zip)

**Comment by petro2050** [comment]
I can confirm this. Repeater works on Android, but iOS does not seem to support it. What's worse is that a lot of designers on LottieFiles are unaware of it. Considering many animations make use of repeaters, a lot of the publicly shared ones do not work on iOS.

**Comment by CripGod** [comment]
Is there a way to EXPAND (i.e. have AE draw out the actual repeated elements) , much the same way you can convert expressions to keyframes, as a work around?
