### ISSUE TITLE
When will gradient stroke be supported?

### ISSUE THREAD

**Issue by kaiden-dragon** [airbnb/lottie-ios#773]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0)
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [x] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [x] iOS

## Expected Behavior 
To see gradient stroke working fine like android and web

## Actual Behavior
It seems to be not supported

**Comment by buba447** [comment]
It is now supported!

Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC

**Comment by sgordon1024** [comment]
Gradient strokes work but they always render to black and white. Is there a way to keep the original colors?

**Comment by meylinbayr** [comment]
Save the ae file before exporting and original colours will show, as colours are saved externally
