### ISSUE TITLE
LOTAnimationView Crash on iOS8 

### ISSUE THREAD

**Issue by linkhui** [airbnb/lottie-ios#775]
## This issue is a:
Crashing Bug

## What Platform are you on? 
iOS 8

Lottie-iOS V2.5.2

Handler: Sig Handler

Hardware Model: iPhone7,2
Code Type: ARM-64 (Native)
Parent Process: launchd [1]

Date/Time: 2019-03-06 07:53:09.804 +0800
OS Version: iPhone OS 8.1.2 (12B440)
Report Version: 104

SDK start time: 2019-03-06 00:54:47
SDK server time delta: 0 s
Last record time delta : 25102805 ms

RDM SDK Version: 2.4.1.2
RDM Registed Uin : 229587105
RDM DeviceId: 3F802449-0B35-4C11-A770-5707BA90EBF9
RDM CI UUID: (null)
RDM APP KEY: 0I000F4V8B1JYMSP

Exception Type: SIGSEGV
Exception Codes: SEGV_ACCERR at 0x534f20656e6f6858
Crashed Thread: 0

Thread 0 Crashed: 
0  libsystem_blocks.dylib         0x0000000196ed55dc __Block_copy_internal +  36
1  QDReaderAppStore               0x00000001014229ec -[LOTAnimationView _handleWindowChanges:] (LOTAnimationView.m:258)
2  QDReaderAppStore               0x0000000101422ab8 -[LOTAnimationView _handleWillEnterForeground] (LOTAnimationView.m:269)
3  CoreFoundation                 0x000000018608cae4 ___CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ +  20
4  CoreFoundation                 0x0000000185fcb220 _CFXNotificationPost + 2060
5  Foundation                     0x0000000186ecacc0 -[NSNotificationCenter postNotificationName:object:userInfo:] +  72
6  UIKit                          0x000000018ab2f72c -[UIApplication _handleApplicationActivationWithScene:transitionContext:completion:] +  1992
7  UIKit                          0x000000018ab2ecec ___88-[UIApplication _handleApplicationLifecycleEventWithScene:transitionContext:completion:]_block_invoke +  140
8  UIKit                          0x000000018ab2ec44 -[UIApplication _handleApplicationLifecycleEventWithScene:transitionContext:completion:] +  380
9  UIKit                          0x000000018ab22578 -[UIApplication scene:didUpdateWithDiff:transitionContext:completion:] +  512
10 FrontBoardServices             0x000000018e35562c ___31-[FBSSerialQueue performAsync:]_block_invoke +  28
11 CoreFoundation                 0x000000018609ea28 ___CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ +  20+  20
12 CoreFoundation                 0x000000018609db30 ___CFRunLoopDoBlocks +  312
13 CoreFoundation                 0x000000018609c154 ___CFRunLoopRun +  1756
14 CoreFoundation                 0x0000000185fc90a4 CFRunLoopRunSpecific + 392
15 GraphicsServices               0x000000018f16b5a4 GSEventRunModal + 164
16 UIKit                          0x000000018a8fe3c0 UIApplicationMain + 1488
17 QDReaderAppStore               0x0000000100863378 main (main.m:13)
18 libdyld.dylib                  0x0000000196eaaa08 _start +  4

Thread 1: 
0  libsystem_kernel.dylib         0x0000000196fa8c94 kevent64 + 4
1  libdispatch.dylib              0x0000000196e833b4 __dispatch_source_invoke

Thread 2: 
0  libsystem_kernel.dylib         0x0000000196fa8e7c host_self_trap + 8
1  CoreFoundation                 0x000000018609ded0 ___CFRunLoopServiceMachPort +  200
2  CoreFoundation                 0x000000018609be24 ___CFRunLoopRun +  940
14 CoreFoundation                 0x0000000185fc90a4 CFRunLoopRunSpecific + 392
4  Foundation                     0x0000000186ed1804 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] +  316
5  Foundation                     0x0000000186f2bef8 -[NSRunLoop(NSRunLoop) run] +  96
6  Foundation                     0x0000000186fb9c0c ___NSThread__main__ +  1072
7  libsystem_pthread.dylib        0x000000019705fe80 __pthread_body +  164
8  libsystem_pthread.dylib        0x000000019705fddc _pthread_start + 148
9  libsystem_pthread.dylib        0x000000019705cfb0 thread_start + 4

Thread 3 Name: com.apple.NSURLConnectionLoader
Thread 3: 
0  libsystem_kernel.dylib         0x0000000196fa8e7c host_self_trap + 8
1  CoreFoundation                 0x000000018609ded0 ___CFRunLoopServiceMachPort +  200
2  CoreFoundation                 0x000000018609be24 ___CFRunLoopRun +  940
14 CoreFoundation                 0x0000000185fc90a4 CFRunLoopRunSpecific + 392
4  CFNetwork                      0x0000000185ace4e8 +[NSURLConnection(Loader) _resourceLoadLoop:] +  440
6  Foundation                     0x0000000186fb9c0c ___NSThread__main__ +  1072
7  libsystem_pthread.dylib        0x000000019705fe80 __pthread_body +  164
8  libsystem_pthread.dylib        0x000000019705fddc _pthread_start + 148
9  libsystem_pthread.dylib        0x000000019705cfb0 thread_start + 4

Thread 4 Name: AFNetworking
Thread 4: 
0  libsystem_kernel.dylib         0x0000000196fa8e7c host_self_trap + 8
1  CoreFoundation                 0x000000018609ded0 ___CFRunLoopServiceMachPort +  200
2  CoreFoundation                 0x000000018609be24 ___CFRunLoopRun +  940
14 CoreFoundation                 0x0000000185fc90a4 CFRunLoopRunSpecific + 392
4  Foundation                     0x0000000186ed1804 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] +  316
5  Foundation                     0x0000000186f2bef8 -[NSRunLoop(NSRunLoop) run] +  96
6  QDReaderAppStore               0x0000000100fd11c8 +[AFURLConnectionOperation networkRequestThreadEntryPoint:] (AFURLConnectionOperation.m:164)
6  Foundation                     0x0000000186fb9c0c ___NSThread__main__ +  1072
7  libsystem_pthread.dylib        0x000000019705fe80 __pthread_body +  164
8  libsystem_pthread.dylib        0x000000019705fddc _pthread_start + 148
9  libsystem_pthread.dylib        0x000000019705cfb0 thread_start + 4

Thread 5 Name: com.apple.CFSocket.private
Thread 5: 
0  libsystem_kernel.dylib         0x0000000196fc3498 __select + 0
7  libsystem_pthread.dylib        0x000000019705fe80 __pthread_body +  164
8  libsystem_pthread.dylib        0x000000019705fddc _pthread_start + 148
9  libsystem_pthread.dylib        0x000000019705cfb0 thread_start + 4

Thread 6 Name: com.squareup.SocketRocket.NetworkThread
Thread 6: 
0  libsystem_kernel.dylib         0x0000000196fa8e7c host_self_trap + 8
1  CoreFoundation                 0x000000018609ded0 ___CFRunLoopServiceMachPort +  200
2  CoreFoundation                 0x000000018609be24 ___CFRunLoopRun +  940
14 CoreFoundation                 0x0000000185fc90a4 CFRunLoopRunSpecific + 392
4  Foundation                     0x0000000186ed1804 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] +  316
5  QDReaderAppStore               0x000000010125f044 -[_SRRunLoopThread main] (SRWebSocket.m:1903)
6  Foundation                     0x0000000186fb9c0c ___NSThread__main__ +  1072
7  libsystem_pthread.dylib        0x000000019705fe80 __pthread_body +  164
8  libsystem_pthread.dylib        0x000000019705fddc _pthread_start + 148
9  libsystem_pthread.dylib        0x000000019705cfb0 thread_start + 4

Thread 7: 
0  libsystem_kernel.dylib         0x0000000196fc3c78 __workq_kernreturn + 0
1  libsystem_pthread.dylib        0x000000019705cfa8 __pthread_set_self + 12

Thread 8: 
0  libsystem_kernel.dylib         0x0000000196fc3c78 __workq_kernreturn + 0
1  libsystem_pthread.dylib        0x000000019705cfa8 __pthread_set_self + 12

Thread 9: 
0  libsystem_kernel.dylib         0x0000000196fc3c78 __workq_kernreturn + 0
1  libsystem_pthread.dylib        0x000000019705cfa8 __pthread_set_self + 12

Thread 10: 
0  libsystem_kernel.dylib         0x0000000196fc3c78 __workq_kernreturn + 0
1  libsystem_pthread.dylib        0x000000019705cfa8 __pthread_set_self + 12

Thread 11: 
0  libsystem_kernel.dylib         0x0000000196fc3c78 __workq_kernreturn + 0
1  libsystem_pthread.dylib        0x000000019705cfa8 __pthread_set_self + 12

Thread 12: 
0  libsystem_kernel.dylib         0x0000000196fc3c78 __workq_kernreturn + 0
1  libsystem_pthread.dylib        0x000000019705cfa8 __pthread_set_self + 12

Thread 13: 
0  libsystem_kernel.dylib         0x0000000196fc3c78 __workq_kernreturn + 0
1  libsystem_pthread.dylib        0x000000019705cfa8 __pthread_set_self + 12

Thread 14: 
0  libsystem_kernel.dylib         0x0000000196fc3c78 __workq_kernreturn + 0
1  libsystem_pthread.dylib        0x000000019705cfa8 __pthread_set_self + 12

Thread 15: 
0  libsystem_kernel.dylib         0x0000000196fc3c78 __workq_kernreturn + 0
1  libsystem_pthread.dylib        0x000000019705cfa8 __pthread_set_self + 12

Thread 0 crashed with ARM 64 Thread State:
     x0:  0x534f20656e6f6850    x1: 0x0000000000000001    x2: 0x0000000000000008     x3: 0x0000000196ffda74
     x4:  0x0000000000000010    x5: 0x0000000000000001    x6: 000000000000000000     x7: 000000000000000000
     x8:  0x534f20656e6f6850    x9: 0x0000000000000001   x10: 0x0000000103558000    x11: 0x00000000005c1909
    x12: 0x00000001382a3400    x13: 0x0000000137548000   x14: 0x0000000000003fff    x15: 0x0000000000003fff
    x16: 0x0000000196ed55b0    x17: 0x0000000185fcda90   x18: 000000000000000000    x19: 0x534f20656e6f6850
    x20: 0x0000000000000128    x21: 0x0000000000000001   x22: 0x000000016fd26738    x23: 0x00000000000f436b
    x24: 000000000000000000    x25: 0x00000001700f3f10   x26: 0x000000016fd26660    x27: 0x0000000000000008
    x28: 0x00000000000f436b    fp: 0x000000016fd264b0    lr: 0x00000001014229ec -[LOTAnimationView _handleWindowChanges:] (LOTAnimationView.m:258)
    sp: 0x000000016fd26480     pc: 0x0000000196ed55dc __Block_copy_internal +  36

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
