### ISSUE TITLE
Lottie file works on Lottiefiles.com but crashes in app

### ISSUE THREAD

**Issue by jwoodrow** [airbnb/lottie-ios#776]
## Check these before submitting:
- [x] Updated to the latest version of Lottie (2.5.0) (actually 2.5.2)
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features) Not to my knowledge and no warnings are raised
- [x] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [x] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [x] iOS

## Expected Behavior 

I tested my export on Lottiefiles.com first to check if it worked there and it does (link included below)
I expect my lottie file to open correctly and animate

## Actual Behavior

The application crashes:
`Message from debugger: Terminated due to memory issue`
If I remove the lottie part of the code it works just fine (it's been working fine with no memory leaks for months now).

Note: when I tried scanning the qrcode using the lottiefiles app the app doesn't crash but no animation is displayed either.

## Code Example
```Swift
override func viewDidLoad() {
  super.viewDidLoad()
  self.lottieTest = LOTAnimationView(name: "teeeeest")
  self.lottieTest.contentMode = .scaleAspectFit
  self.lottieTest.frame = CGRect(x: 0, y: 0, width: 480, height: 640)
  self.view.addSubview(self.lottieTest)
  self.lottieTest.loopAnimation = true
}

override func viewDidAppear(_ animated: Bool) {
  super.viewDidAppear(animated)
  self.lottieTest.play()
}
```
## Animation JSON

https://lottiefiles.com/share/KJdj4I

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
