### ISSUE TITLE
"duration" returns seconds on iOS, milliseconds on Android

### ISSUE THREAD

**Issue by hansemannn** [airbnb/lottie-ios#78]
Not much more to say I guess. iOS returns the playback duration in seconds, Android in milliseconds. The general unit for playback durations is in milliseconds, so they should probably be normalized.

**Comment by buba447** [comment]
@hansemannn The seconds on iOS is in keeping with the media interval that is established with CALayer. Im not sure what the standard is on Android.
This might be a difference in platforms and not this framework though. If thats the case we will stay in line with the platforms. If not we will normalize.

**Comment by hansemannn** [comment]
Thanks for the feedback, I'm good with that then :-)
