### ISSUE TITLE
Stroke circle showing a solid fill inside

### ISSUE THREAD

**Issue by Bigbigann** [airbnb/lottie-ios#783]
Hi I have asked the same question on lottie-android and it seems the problem is due to not using the latest version of lottie library but recently I have found out the same problem also occurs on IOS which is using the latest version of lottie.

The file I have the problem is a simple loading animation using the basic trim effect.

The animation looks good when preview in lottie on web however when it is tested on the app the stroke circle have a solid shape inside it.

I am not using any effect and the round shape is just a circle only with stroke so not sure what is going on here.

Would anyone know what causes the issue?

Any help would be appreciated. 

Here is the aep file.
[loading_debug.aep.zip](https://github.com/airbnb/lottie-ios/files/2963847/loading_debug.aep.zip)

And the json file.
[loading_1.json.zip](https://github.com/airbnb/lottie-ios/files/2963851/loading_1.json.zip)

The screenshot of the problem.
![image](https://user-images.githubusercontent.com/48397314/54317797-10cdf200-4649-11e9-923f-7e2d41fddaa2.png)

**Comment by buba447** [comment]
Hello! 

Ive taken a look at your file and found the issue. You have a `Gradient Fill` on the circle that is set to hidden. Currently iOS and Android don't respect the hidden property on shape items. Simply deleting the hidden layer will export a working animation. Ive attached anew export below. Cheers!

<img width="707" alt="Screen Shot 2019-03-14 at 10 12 31 AM" src="https://user-images.githubusercontent.com/1163980/54363821-17a53680-4642-11e9-80db-92eddc737af1.png">


[loading2.json.zip](https://github.com/airbnb/lottie-ios/files/2966815/loading2.json.zip)
