### ISSUE TITLE
Latest version doesn't work with swift 4.2

### ISSUE THREAD

**Issue by tfonfara** [airbnb/lottie-ios#787]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [ ] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [ ] Feature Request
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [ ] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift 4.2
- [ ] Objective-C

## Expected Behavior 
Lottie 3.0 should be able to work with swift 4.2

## Actual Behavior
Lottie 3.0 is not compiling against swift 4.2

**Comment by buba447** [comment]
Lottie Swift is written in Swift 4.0.

You can use 4.0 swift in a 4.2 project easily by setting the framework to compile in 4.0.

**Comment by tfonfara** [comment]
@buba447 sure, but why not support the latest swift version? Swift 4.2 was release almost 1 year ago, swift 5.0 is almost there (expected in 2 weeks)...

**Comment by gabors** [comment]
It would be great if it complied against current swift 4.2 though. 

What about Xcode 10.2 beta and swift 5?

**Comment by Sashom** [comment]
Same issue here. Please convert to combat with 4.2.

**Comment by buba447** [comment]
https://github.com/airbnb/lottie-ios/pull/793
