### ISSUE TITLE
Swift 4.2

### ISSUE THREAD

**Issue by RamblinWreck77** [airbnb/lottie-ios#788]
Congrats on the new release/rewrite! Setting it up now to test it out!

Quick question, I noticed it's built for Swift 4, and on first glance Swift 4.2 would only require some renames/auto-fixes. I'm assuming this was intentional?

If not, I'd be happy to put a PR up with Swift 4.2 changes. 

Thanks again!

**Comment by lijin88121** [comment]
it doesn't work for Swift 4.2 now. it was working fine a few days ago.

**Comment by tfonfara** [comment]
+1
My issue was just dumped https://github.com/airbnb/lottie-ios/issues/787 🙄

**Comment by wirnico** [comment]
When I try to install the new 3.0 with pod install in Terminal it always installs 2.5.2 again. What am I doing wrong. In my Pod File I call **pod 'lottie-ios'** Thanks for helping

**Comment by lijin88121** [comment]
> When I try to install the new 3.0 with pod install in Terminal it always installs 2.5.2 again. What am I doing wrong. In my Pod File I call **pod 'lottie-ios'** Thanks for helping

try pod repo update, or specify the pod version when you do `pod install`.

**Comment by lijin88121** [comment]
The problem is the latest release does not work for Swift4.2

**Comment by wirnico** [comment]
Thanks it worked with pod 'lottie-ios', '3.0.0'

**Comment by wirnico** [comment]
> The problem is the latest release does not work for Swift4.2

What exactly does not work with Swift 4.2

**Comment by tfonfara** [comment]
> What exactly does not work with Swift 4.2

Compiling^^

**Comment by buba447** [comment]
It can be compiled in 4.0 and used in 4.2 perfectly fine. You just need to specify 4.0 in the framework’s compile settings. 

Godspeed,
Brandon

**Comment by tfonfara** [comment]
@buba447 I did, but at least for me this leads to crashes if I use it same way as I did before, just update the breaking changes.
Starting with the usage in nib files, `AnimationView` cannot be picked here (module always resets to empty which is quite annoying, in previous version this worked as is should) and if I select the module by hand the "xcode agent" crashes. Even if I ignore this (this agent should only be necessary for updating nibs and storyboards with IBDesignables) it crashes at runtime when setting `animation` property.
I reverted back to latest 2.x version as this looks to me more as a beta version than production ready.

**Comment by buba447** [comment]
@tfonfara These issues seem to be separate issues from swift language version. Please file individual tickets for these so that they may be addressed.

**Comment by buba447** [comment]
@tfonfara As far as setting from the nib. Im not having trouble over here selecting the module or the class. Maybe cleaning would help? If you can provide more information in a separate ticket id love to get to the bottom of your problems.

<img width="962" alt="Screen Shot 2019-03-18 at 8 43 56 AM" src="https://user-images.githubusercontent.com/1163980/54530800-1e8dbb00-495a-11e9-8823-d002a2ce452e.png">

**Comment by buba447** [comment]
Migrated to 4.2 and should be available in the next release. Cheers!

https://github.com/airbnb/lottie-ios/pull/793

**Comment by RamblinWreck77** [comment]
@buba447 thanks! You're the best!

**Comment by Sashom** [comment]
Yep, same issue here + there is an additional warning
something about "Project settings" update in Xcode.
