### ISSUE TITLE
Lottie 2.5.3 Recommendation for OC version independence

### ISSUE THREAD

**Issue by ccworld1000** [airbnb/lottie-ios#790]
## Lottie-iOS Issue 
Lottie 2.5.3 Recommendation for OC version independence

## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 2.5.3

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [] Swift
- [x] Objective-C

**Comment by ccworld1000** [comment]
It is suggested that the version of OC code should be independent, and the sudden switch to swift will affect project dependency. The project itself is mainly OC code. Should it be considered?

**Comment by buba447** [comment]
Im not entirely sure what you mean. If you are referring to the switch from swift to objective c, we are maintaining the objective-c code in a branch over here -> https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC

**Comment by ccworld1000** [comment]
I mean to completely separate OC and swift into two separate git data warehouses

**Comment by buba447** [comment]
Ahh. We are going to continue with a singular repository.  The objective C branch will be maintained with minor fixes and can be accessed over here https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC

It's just easier for us to manage and test as a single repo. Thanks for the feedback!
