### ISSUE TITLE
Lottie 3.0 issues with interface builder

### ISSUE THREAD

**Issue by tfonfara** [airbnb/lottie-ios#794]
## Check these before submitting:
- [ ] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [ ] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [ ] Feature Request
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [ ] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [ ] Objective-C

## Code Example
[LottieTest.zip](https://github.com/airbnb/lottie-ios/files/2978172/LottieTest.zip)

@buba447 as reply to https://github.com/airbnb/lottie-ios/issues/788#issuecomment-473895047 I've created a small sample.
Seems that I was not completely correct regarding the crash, it only happens if you don't set the module manually.

What I can 100% reproduce in this sample:
1. If I go to IB and select `AnimationView` the module is always empty (and also always resets automatically to empty). If you run the app then, it just crashes while setting `animation` property.
    <img width="260" alt="Bildschirmfoto 2019-03-18 um 13 59 21" src="https://user-images.githubusercontent.com/728683/54532238-958d7880-4987-11e9-926b-ea5a0bbe4591.png">

2. If you select the module manually it causes xcode crashes.
    <img width="264" alt="Bildschirmfoto 2019-03-18 um 13 59 34" src="https://user-images.githubusercontent.com/728683/54532350-d9807d80-4987-11e9-8765-57d94782a1a2.png">

**Comment by buba447** [comment]
Found the issue and a fix is here: https://github.com/airbnb/lottie-ios/pull/796

The fix will be in the next release.
If the fix doesnt work please feel free to reopen the issue. Please note that cleaning and sometimes deleting derived data is needed to verify the fix. This is common with xcode and storyboards unfortunately.

Cheers!
