### ISSUE TITLE
Swift 4 Lottie Animation not working on my Swift 3 code

### ISSUE THREAD

**Issue by adithimev** [airbnb/lottie-ios#795]
## This issue is a:
- [✓] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [✓] iOS

## What Language are you in?
- [✓] Swift
- [] Objective-C

## Code Example
lottieControl is an iboutlet of AnimationView

lottieControl = AnimationView(name: "bell")
            lottieControl.contentMode = .scaleAspectFit
            lottieControl.backgroundBehavior = .pauseAndRestore
            lottieControl.loopMode = .loop
            lottieControl.play()
            print("(lottieControl.isAnimationPlaying)", lottieControl.isAnimationPlaying)

**Comment by buba447** [comment]
Could you please provide some more information? What is not working? What are the environment conditions?

**Comment by adithimev** [comment]
It doesnt animate . it shows a blank view. I have added the class as AnimationView and module as Lottie. My code is as above.

**Comment by buba447** [comment]
Can you provide the animation?

**Comment by adithimev** [comment]
{"v":"5.1.18","fr":29.9700012207031,"ip":0,"op":45.0000018328876,"w":200,"h":200,"nm":"Pre-comp 1","ddd":0,"assets":[],"layers":[{"ddd":0,"ind":1,"ty":4,"nm":"bell Outlines 2","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":1,"k":[{"i":{"x":[0.584],"y":[1]},"o":{"x":[0.761],"y":[0]},"n":["0p584_1_0p761_0"],"t":5,"s":[0],"e":[-17]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.577],"y":[0]},"n":["0p667_1_0p577_0"],"t":12,"s":[-17],"e":[17]},{"i":{"x":[0],"y":[1]},"o":{"x":[0.333],"y":[0]},"n":["0_1_0p333_0"],"t":18,"s":[17],"e":[-17]},{"i":{"x":[0.08],"y":[1]},"o":{"x":[0.479],"y":[0]},"n":["0p08_1_0p479_0"],"t":23.51,"s":[-17],"e":[0]},{"t":31.9612513018084}],"ix":10},"p":{"a":0,"k":[100.103,55.5,0],"ix":2},"a":{"a":0,"k":[142,53,0],"ix":1},"s":{"a":0,"k":[50,50,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[8.245,-0.024],[0,0],[0,0],[0,0],[0,0],[0,0],[2.397,5.381],[-1.429,3.739],[-3.645,1.627],[0,0],[0,0],[-20.644,8.682],[0,0],[0,0],[-3.669,3.672],[-5.187,0],[0,0],[-3.667,-3.676],[0,-5.195],[0,0],[0,0],[-0.051,-22.612],[0,0],[0,0],[-0.02,-5.89]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0],[-5.884,-0.019],[-1.63,-3.657],[1.431,-3.742],[0,0],[0,0],[0.021,-22.425],[0,0],[0,0],[0,-5.196],[3.669,-3.673],[0,0],[5.187,0],[3.668,3.673],[0,0],[0,0],[20.649,9.168],[0,0],[0,0],[5.373,2.4],[0.024,8.268]],"v":[[61.621,74.641],[25.695,74.641],[25.691,74.664],[-25.279,74.664],[-25.282,74.641],[-61.196,74.641],[-74.824,65.755],[-75.133,54.286],[-67.258,45.959],[-55.197,40.609],[-55.197,1.838],[-21.179,-49.372],[-19.214,-50.199],[-19.214,-55.217],[-13.525,-68.969],[0.207,-74.665],[0.21,-74.665],[13.941,-68.965],[19.63,-55.212],[19.63,-50.036],[21.536,-49.189],[55.61,3.135],[55.61,40.609],[67.663,45.956],[76.538,59.602]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"st","c":{"a":0,"k":[0.984313726425,0.913725495338,0.29411765933,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":8,"ix":5},"lc":1,"lj":1,"ml":10,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"tr","p":{"a":0,"k":[141.529,128.472],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Group 1","np":3,"cix":2,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":45.0000018328876,"st":0,"bm":0},{"ddd":0,"ind":2,"ty":4,"nm":"ball Outlines 2","parent":1,"sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":1,"k":[{"i":{"x":0.667,"y":1},"o":{"x":1,"y":0},"n":"0p667_1_1_0","t":5,"s":[142,54,0],"e":[120,54,0],"to":[-3.66666674613953,0,0],"ti":[-3,0,0]},{"i":{"x":0.667,"y":1},"o":{"x":0.692,"y":0},"n":"0p667_1_0p692_0","t":8,"s":[120,54,0],"e":[160,54,0],"to":[3,0,0],"ti":[0,0,0]},{"i":{"x":0.438,"y":1},"o":{"x":0.639,"y":0},"n":"0p438_1_0p639_0","t":15,"s":[160,54,0],"e":[120,54,0],"to":[0,0,0],"ti":[-0.16666667163372,0,0]},{"i":{"x":0.438,"y":1},"o":{"x":0.639,"y":0},"n":"0p438_1_0p639_0","t":21,"s":[120,54,0],"e":[161,54,0],"to":[0.16666667163372,0,0],"ti":[-2.66666674613953,0,0]},{"i":{"x":0.19,"y":1},"o":{"x":0.333,"y":0},"n":"0p19_1_0p333_0","t":27,"s":[161,54,0],"e":[136,54,0],"to":[2.66666674613953,0,0],"ti":[3.16666674613953,0,0]},{"i":{"x":0.071,"y":1},"o":{"x":0.333,"y":0},"n":"0p071_1_0p333_0","t":32,"s":[136,54,0],"e":[142,54,0],"to":[-3.16666674613953,0,0],"ti":[-1,0,0]},{"t":36.0000014663101}],"ix":2},"a":{"a":0,"k":[142,54,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[-3.085,12.217],[0,0],[-14.396,0.001],[-1.72,0.279]],"o":[[0,0],[3.576,14.162],[1.689,0],[12.596,-2.053]],"v":[[30.814,-12.005],[-30.814,-12.005],[-0.018,12.005],[5.105,11.59]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":0,"k":[0.984313726425,0.913725495338,0.29411765933,1],"ix":4},"o":{"a":0,"k":0,"ix":5},"r":1,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"st","c":{"a":0,"k":[0.984313726425,0.913725495338,0.29411765933,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":10,"ix":5},"lc":1,"lj":1,"ml":10,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"tr","p":{"a":0,"k":[141.732,217.653],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Group 1","np":3,"cix":2,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":45.0000018328876,"st":0,"bm":0}],"markers":[]}

**Comment by buba447** [comment]
Hmmm. It seems to be loading on my end...
Maybe it's something to do with how your views are set up?

<img width="493" alt="Screen Shot 2019-03-18 at 9 49 45 AM" src="https://user-images.githubusercontent.com/1163980/54534652-37e73500-4963-11e9-8ebb-12184b117a29.png">

**Comment by adithimev** [comment]
Did you try with an iboutlet?

**Comment by buba447** [comment]
Yes. The animation view comes from an IBOutlet.

Couple things to note, I noticed you are overriding the view with this line
`lottieControl = AnimationView(name: "bell")`
This will create a *new* AnimationView, but does not add it to the view hierarchy. 
Instead of creating a new AnimationView just set the animation on the AnimationView with

`lottieControl.animation = Animation.named("bell")`

Also another thing to note, I just fixed an issue with storyboards that affects the way they load in preview. This bug should not affect a running app though.

**Comment by adithimev** [comment]
Thanks, works fine.. closing the issue

**Comment by adithimev** [comment]
Hi,


Im facing an issue with Animated Button

Im trying to add an AnimatedButton via storyboard. It doesnt allow me to add animatedbutton in custom class name, so added it in properties alone
@IBOutlet<https://github.com/IBOutlet> var button1: AnimatedButton!

Secondly, after this
I get a crash while adding
button1.animation = Animation.named("animationfile")


Regards,

Adithi Bolar
iOS Developer
