### ISSUE TITLE
[3.0] Animations with radial trim stopped working after update, still work in 2.5.3

### ISSUE THREAD

**Issue by RamblinWreck77** [airbnb/lottie-ios#798]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 
-Radial trim/sweep to function as in 2.5.3

## Actual Behavior
-Something funky, the path freaks out and jumps from various states of completion as you sweep from 0.0 -> 1.0

-Animation still works great in lottie preview/2.5.3. Behavior is 100% reproducible in the 3.0 update.

## Animation JSON
email sent to brandon w/json :) Subject "Lottie 3.0 bug + sample animation"

**Comment by buba447** [comment]
Fixed it here https://github.com/airbnb/lottie-ios/pull/799

Will be published in 3.0.1

**Comment by Dfmarulanda** [comment]
When it's going to be published? Half of my animations stopped working and I don't know why!

**Comment by RamblinWreck77** [comment]
@Dfmarulanda I can confirm that 3.0.1 fixes the above issue for me!
