### ISSUE TITLE
Minimum Deployment Target set at iOS11

### ISSUE THREAD

**Issue by satindar** [airbnb/lottie-ios#803]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0.1

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 
iOS 9 compatibility

## Actual Behavior
Minimum Target of iOS11 is specified
![Screen Shot 2019-03-20 at 11 38 10 AM](https://user-images.githubusercontent.com/836745/54710556-2fc6fb00-4b05-11e9-89db-e27158869e33.png)

I'm building Lottie with Carthage and seems like the project is specified with iOS11 as a min target (our app supports iOS9).

I do see that the podspec supports iOS9. I believe the target needs to change in `project.pbxproj` as well (not certain of that though).

**Comment by buba447** [comment]
Oh, yeah this is an oversight on my end. ill update that

**Comment by buba447** [comment]
Updated on master now.

**Comment by satindar** [comment]
@buba447 Thanks for the quick fix and for all the hard work on Lottie. It's been a very valuable library for us at Juvo. Excited to upgrade this!
