### ISSUE TITLE
Adding subviews in Lottie 3.x not working as expected

### ISSUE THREAD

**Issue by kyle-fox** [airbnb/lottie-ios#810]
## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [X] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0.1

## What Platform are you on? 

- [X] iOS

## What Language are you in?
- [X] Swift

## Expected Behavior 

Adding a subview to a Keypath should work as it did in the previous version.

## Actual Behavior

Subviews added to a Keypath are being placed in the top left corner of the animation, seemingly because the layer bounds of all Keypaths in the animation are returning the full size of the animation, in my specific case:

Goal layer:
```
 Optional<CALayer>
  - some : <Lottie.NullCompositionLayer:0x6000022ddf80; position = CGPoint (0 0); bounds = CGRect (0 0; 1920 1080); sublayers = (<CALayer: 0x6000010893c0>); allowsGroupOpacity = YES; actions = {
    anchorPoint = "<null>";
    bounds = "<null>";
    opacity = "<null>";
    sublayerTransform = "<null>";
    transform = "<null>";
}; anchorPoint = CGPoint (0 0)>
```

Example of another Keypath:
```
▿ Optional<CALayer>
  ▿ some : <Lottie.ShapeCompositionLayer:0x6000027ddad0; position = CGPoint (0 0); bounds = CGRect (0 0; 1920 1080); sublayers = (<CALayer: 0x6000010892c0>); allowsGroupOpacity = YES; actions = {
    anchorPoint = "<null>";
    bounds = "<null>";
    opacity = "<null>";
    sublayerTransform = "<null>";
    transform = "<null>";
}; anchorPoint = CGPoint (0 0)>
```

## Animation JSON

I'll go ahead and email you the animation file.

**Comment by buba447** [comment]
Ah hah! Yes, i found the bug here. Small bug from a refactor. 
Got a fix up https://github.com/airbnb/lottie-ios/pull/814

Will be in a release later today.

**Comment by kyle-fox** [comment]
Awesome - thank you!
