### ISSUE TITLE
lottie-ios 2.5.1, 2.5.2 and 2.5.3 haven't been pushed to the npm registry

### ISSUE THREAD

**Issue by jgreen210** [airbnb/lottie-ios#812]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

N/A.

2.5.3 is currently the last objective-C version of lottie-ios before the move to swift in 3.0.0

**Comment by jgreen210** [comment]
lottie-react-native declares an npm dependency on lottie-ios ^2.5.0, but 2.5.0 is currently the last version that matches this range in the npm registry.

https://www.npmjs.com/package/lottie-ios

See also:

https://github.com/react-native-community/lottie-react-native/issues/177#issuecomment-475302012

**Comment by jgreen210** [comment]
When using lottie-ios via lottie-react-native, this means I have to choose between:

* running "react-native link lottie-ios", which adds symlinks to Podfile pointing into node_modules/, and means we use lottie-ios 2.5.0, complete with all the bugs that have been fixed in the later 2.5.x versions.
* getting lottie-ios 2.5.3 as a normal cocoapod, by hacking around in Podfile and Podfile.lock. This should be possible, but will probably cause problems the next time someone in my team changes a cocoapod version or lottie-react-native changes to a newer lottie-ios version.

To try and use lottie-ios 3.0.0 and therefore swift, lottie-react-native would have to be changed to alter its ^2.5.0 version declaration (and maybe fix any other problems that arise). We'd probably have to fix problems in all the other libraries we use.

**Comment by buba447** [comment]
@jgreen210 Just published 2.5.1 2.5.2 and 2.5.3 to npm.
Sorry for the oversight!
