### ISSUE TITLE
Animations load correctly but do not play in Lottie 3.0.1

### ISSUE THREAD

**Issue by james-rantmedia** [airbnb/lottie-ios#813]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [ ] Feature Request
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [ ] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [ ] Objective-C

## Expected Behavior 
Some (not all) animations that worked fine in Lottie 2.5.2 do not play in Lottie 3.0.1. They appear to load correctly, and If the animation has visible elements in the first frame, I see them on screen when the app runs, but they do not play. 

I don't see anything relevant in the console log, but I am able to print properties of the animation via the debugger, which is why I think the animations are loading correctly, just not playing.

```
(lldb) po animation.animation!
<Animation: 0x281a91170>

(lldb) po animation.animation!.duration
1.6666666666666667

(lldb) po animation.animation!.framerate
30.0

(lldb) po animation.animation!.size
▿ (60.0, 60.0)
  - width : 60.0
  - height : 60.0
```

**Comment by buba447** [comment]
Can you provide the animations? I cant really debug anything without them.

**Comment by james-rantmedia** [comment]
I will email it. Please do not share it publicly.

**Comment by buba447** [comment]
The animation you sent is loading and playing fine for me in the example project. How are you initializing the animation?

**Comment by buba447** [comment]
Got a possible fix here https://github.com/airbnb/lottie-ios/pull/815
Please pull and verify.

**Comment by james-rantmedia** [comment]
Can confirm this is fixed as of 3.0.2. Thanks!

**Comment by brurend** [comment]
@buba447 I'm having this exact same problem in version 3.0.3

**Comment by TSonono** [comment]
Same here (3.0.3)

**Comment by buba447** [comment]
@brurend @TSonono Could you please open new issues with your animations?

The reason an animation does not play can vary from animation to animation, so they may not be the *exact* problems. This issue fixes the problem James was having, and is a verified fix. Please open a new issue with your problem so that it can be debugged. Thanks!
