### ISSUE TITLE
Content mode calculations in `AnimationView` are wrong

### ISSUE THREAD

**Issue by dimovskidamjan** [airbnb/lottie-ios#818]
## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [X] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0.2

## What Platform are you on? 

- [] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift
- [] Objective-C

## Expected Behavior 
When setting `contentMode` to `scaleAspectFill` on an `AnimationView` instance, the animation is supposed to fill all of the available view while preserving the aspect ratio.

## Actual Behavior
When setting `contentMode` to `scaleAspectFill` on an `AnimationView` instance, the animation is not being resized to fit the view at all.

## Code Example
I believe this issue occurred with the recent transition to Swift, as I have compared with the older version of this class (`LOTAnimationView`) which was written in ObjC and that logic works as expected.

Current misbehaving code:
```
position = bounds.center
let compAspect = animation.size.width / animation.size.height
let viewAspect = bounds.size.width / bounds.size.height
let dominantDimension = compAspect > viewAspect ? bounds.size.width : bounds.size.height
let compDimension = compAspect < viewAspect ? animation.size.width : animation.size.height
let scale = dominantDimension / compDimension
xform = CATransform3DMakeScale(scale, scale, 1)
```

 Code which works as expected (adapted from ObjC version):
```
position = bounds.center
let compAspect = animation.size.width / animation.size.height
let viewAspect = bounds.size.width / bounds.size.height
let scaleWidth = compAspect < viewAspect
let dominantDimension = scaleWidth ? bounds.size.width : bounds.size.height
let compDimension = scaleWidth ? animation.size.width : animation.size.height
let scale = dominantDimension / compDimension
xform = CATransform3DMakeScale(scale, scale, 1)
```

## Animation JSON
I don't think that it matters which animation is being used in this case.

**Comment by buba447** [comment]
I see that you are right! Fixed in master. Thank you!
