### ISSUE TITLE
Does this library support zooming in on a specific part of the animation?

### ISSUE THREAD

**Issue by jpmcglone** [airbnb/lottie-ios#821]
In other words, if we have a BIG animation (like a map) with many moving parts, can I zoom in and out on that animation? And how is the performance?

**Comment by jpmcglone** [comment]
Update: Is there a way to animate only what's showing on screen? We tried a large animation and it seems to render and animate EVERYTHING (including what is off-screen)

**Comment by buba447** [comment]
Yes! There is now a function to zoom on a specific part of an animation. Use the `viewportFrame` function.
