### ISSUE TITLE
OSX standalone player?

### ISSUE THREAD

**Issue by sogen** [airbnb/lottie-ios#822]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [x] MacOS
- [] iOS

## What Language are you in?
- [x] Swift
- [x] Objective-C

## Expected Behavior 

is there a standalone player?
There's a reference to this folder (https://github.com/airbnb/lottie-ios/tree/master/MacOS_Viewer), but now is 404.

**Comment by buba447** [comment]
Theres one over here: https://github.com/buba447/Lottie-Preview

Where did you find that reference?

**Comment by sogen** [comment]
Went through my history but can't find the link.
Thanks for the app!

**Comment by sogen** [comment]
Update, stumbled upon the reference link:
https://github.com/buba447/Lottie-Sketch-Export
text: "Lottie Mac Preview"
