### ISSUE TITLE
What is the counterpart of this method. setProgressWithFrame

### ISSUE THREAD

**Issue by sdaheng** [airbnb/lottie-ios#825]
## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] iOS

## What Language are you in?
- [] Swift

## Actual Behavior
<img width="1172" alt="lotties_issue" src="https://user-images.githubusercontent.com/1405754/54970662-081cda80-4fbe-11e9-9047-8a1cc7cae815.png">

## Code Example
func loopFromFrame(_ frameNumber: NSNumber) {
        self.animationView?.setProgressWithFrame(frameNumber)        self.animationView?.play(completion: { (completed) in
            if completed {
                self.loopFromFrame(frameNumber)
            }
        })
    }
## Animation JSON

I didn't find this method in migration guide. Its appreciated that anyone could tell me.

**Comment by buba447** [comment]
`self.animationView?.currentFrame = frameNumber`

Cheers!

**Comment by sdaheng** [comment]
> `self.animationView?.currentFrame = frameNumber` Cheers!
> […](#)

Thank you!
