### ISSUE TITLE
AnimationView causes crash when initialized in Interface Builder

### ISSUE THREAD

**Issue by DennisHirschgaenger** [airbnb/lottie-ios#826]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [x] Crashing Bug
- [] Feature Request
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0.3

## What Platform are you on? 
- [] MacOS
- [x] iOS 12.1

## What Language are you in?
- [x] Swift 4.2
- [] Objective-C

## Expected Behavior 
An AnimationView can be initialized in interface builder like LOTAnimationView in lottie-ios version 2.5.3.

## Actual Behavior
When an AnimationView is initialized through a storyboard, accessing properties of the animation view causes the app to crash with an EXC_BAD_ACCESS error.

**Comment by alextudge** [comment]
I get the same crash after updating our pods on` removeCurrentAnimation()`

**Comment by hordurhauks** [comment]
Same. Swift 5.0.

**Comment by dylanmaryk** [comment]
Same here. Also Swift 5.0.

**Comment by hoangtuanfithou** [comment]
Same.

**Comment by jcooperation0137** [comment]
Same here, swift 4.2, lottie version: 3.0.3

**Comment by buba447** [comment]
If anyone has a repo please send it to me. I haven't been able to recreate the crash, and cant find a fix until I do.

**Comment by avivm** [comment]
Same. Swift 4.2.

**Comment by hoangtuanfithou** [comment]
<img width="259" alt="Screen Shot 2019-03-28 at 10 13 02 AM" src="https://user-images.githubusercontent.com/93890/55124706-185dc280-5142-11e9-8698-32ddef9ee3e5.png">
@DennisHirschgaenger @jcooperation0137 @dylanmaryk 
can be resolved by choosing the Module

**Comment by DennisHirschgaenger** [comment]
That works. Thank you

**Comment by patthehuman** [comment]
thank u

**Comment by macalbert** [comment]
The solution provided by @hoangtuanfithou doesn't work in my case. 
Swift 4.2
lottie-ios (3.1.2)
