### ISSUE TITLE
The animation doesn't works but only shows the background layer

### ISSUE THREAD

**Issue by zyxscientist** [airbnb/lottie-ios#83]
![wechatimg1397](https://cloud.githubusercontent.com/assets/16728209/22861301/9ae666e8-f150-11e6-80ea-9e540b290705.jpeg)

I render the comp and get the json,everything looks fine,but it just not works on my iPhone.But when i use the .json file download from the official blog,things work fine.So in one word,the json file rendered by my own After Effect doesn't work.

- After Effect CC 2015 & bodymovin 4.5.4

**Comment by therealsalih** [comment]
Hi @zyxscientist as said in your other issue, Lottie iOS does not yet support precomps. Please follow this issue as we'll be adding support soon

https://github.com/airbnb/lottie-ios/issues/57

Thanks!

**Comment by allanweir** [comment]
Are there any plans to give debug output when unavailable features are used in an animation? I'm trying to integrate an animation from a designer in a different location at the moment but I don't have access to the after effects file so I can't tell what exactly is stopping the animation from appearing.

**Comment by zyxscientist** [comment]
Sounds great but maybe it is a big project.

2017年2月13日 +0800 PM10:55 Allan Weir <notifications@github.com>，写道：

**Comment by buba447** [comment]
@allanweir Great idea! Were gonna look into it.
