### ISSUE TITLE
Bad Avocado 🥑

### ISSUE THREAD

**Issue by geoff-davis-smule** [airbnb/lottie-ios#832]
## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
**Unknown, as I did not create it. It was downloaded from lottiefiles.com**
https://lottiefiles.com/4675-a-guakka-loader-for-foodvisor

## This issue is a:
- [X] Crashing Bug

## Which Version of Lottie are you using?

Lottie 3.0.3

## What Platform are you on? 

- [X] iOS

## What Language are you in?
- [X] Swift

## Expected Behavior 
The animation file is only 102k, so not huge. We are testing Lottie by running animations in the individual cells of a large collection view, loading more as we scroll down.

![Screen Shot 2019-03-27 at 11 24 38 AM](https://user-images.githubusercontent.com/9537104/55102115-ec2f3c80-5082-11e9-878f-58245db86c26.png)

## Actual Behavior
As I scroll, memory usage soars dramatically, quickly climbing up to 2GB and crashing the app. I don't see anything close to this behavior in other Lottie animations of similar size and complexity. Perhaps something in this animation file is triggering the runaway memory. I didn't create the original animation, and don't know enough yet about the bodymovin file structure to make any inferences about what's causing it, but I though you guys might want to take a look.

## Code Example
If you want, I can ZIP the Xcode test project and send it to you.

## Animation JSON
Download from here: 
https://lottiefiles.com/4675-a-guakka-loader-for-foodvisor

## Additional Random Question
Hey, if Lottie is named after Lottie Reineger, did you guys get the idea from her movies that they project on the wall in the Alchemist bar in SF?

**Comment by buba447** [comment]
Can you send the project for debugging?

RE: Lotte Renninger (not Lottie Renninger). It is named after her, but I have not seen her Animations playing at the Alchemist. I did a paper on her in my history of animation class in college. Her story has always stuck with me so I named the library after her.

**Comment by geoff-davis-smule** [comment]
Hey,

Here's the project. I had called it "Reiniger", which seems the correct spelling of her last name according to the mighty Google:

[reiniger.zip](https://github.com/airbnb/lottie-ios/files/3020363/reiniger.zip)

You can compare the avocado JSON versus some of the others by commenting in/out the various filenames in the main ViewController's array. You'll see the memory skyrocket while scrolling, whereas the others all seem fine.

BTW, thanks for making this framework!

**Comment by RamblinWreck77** [comment]
I'm running into a similar issue, but at smaller scale. It seems that the animation (when set to loop) will continue to run when the cell goes off screen and consume CPU/memory.

**Comment by RamblinWreck77** [comment]
It seems like there's some kind of bug in CompositionLayer.displayWithFrame

It seems like looped animations will keep updating even when .stop() is called and they're not on-screen anymore.

Using instruments, all the CPU time is in:

AnimatorNode.updateTree
 - AnimatorNode.updateContents

I'm only using one animation and it will chew up ~20% of your CPU until you exit the page. Interestingly setting the AnimationView and/or the animation to nil doesn't stop the cycle, the parent has to be deallocated.

**Comment by RamblinWreck77** [comment]
Hmmm, on further inspection what I posted above seems to be my fault. There were a few cases where I was not calling .stop() on animations.

**Comment by buba447** [comment]
This issue is being tracked here
https://github.com/airbnb/lottie-ios/issues/895

Closing to reduce confusion.
