### ISSUE TITLE
LOTColorValueCallback released too soon with ARC

### ISSUE THREAD

**Issue by willsmillie** [airbnb/lottie-ios#833]
I'm working on making some animations change based on user settings. I have a for loop that has a list of layers to color from the specific animation. In that loop I create a LOTColorValueCallback for each corresponding key. 

The issue is only one of these LOTColorValueCallbacks is retained. All others are released. If I switch to manual reference counting it works perfectly, however MRC is not ideal. 

## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 2.5.3 (Objective C branch)

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [] Swift
- [x] Objective-C

## Expected Behavior 
All layers colored to the correct, user defined, color

## Actual Behavior
Only one layer is colored to the correct, user defined, color.

## Code Example

    for (NSString *key in self.properties.allKeys) {
        LOTKeypath *kp = [LOTKeypath keypathWithString:key];
        
        UIColor *c = [UIColor randomColor];
        LOTColorValueCallback *callback = [LOTColorValueCallback withCGColor:c.CGColor];
        [self.view setValueDelegate:callback forKeypath:kp];
    }

**Comment by buba447** [comment]
This api is designed to hold no reference to the value delegates to avoid memory leaks. You must hold reference to them. You can do this without switching to manual reference counting by putting the callbacks into an array that you keep around as a class variable.
