### ISSUE TITLE
Can't set completion block

### ISSUE THREAD

**Issue by valerio-bettini** [airbnb/lottie-ios#834]
In the previous version I could do:
`instanceOfLOTAnimationView.completionBlock = aBlock`

I can't see any way of doing this in the new API

## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [X] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift
- [] Objective-C

**Comment by ugenlik** [comment]
Same here

I can't see the new version of completion block in migration docs as well.

This doesnt compile anymore.
```
self.recordButton.completionBlock = { (result: Bool) in ()
                        self.recordButton.play(fromProgress: 0.95, toProgress: 0.95, withCompletion: { (finished) in
                        })
                    }
```

**Comment by jerilyngigigo** [comment]
@bettola did you manage to work around this?

**Comment by bettola** [comment]
@jerilyngigigo not yet. There is no way to do that in the latest release

**Comment by jerilyngigigo** [comment]
For state-animations as a loading animation that loops indefinitely until a certain process is finished, it seems impossible with the latest release to stop this animation smoothly, i.e.: trigger one last loop before it being stopped. 

The API for version 2.* enabled you to update the animation view loop property and set it's completion block to whatever we needed to do (trigger another animation, etc.)

Is there anyway to achieve this with the new API?

I'm posting this issue on this thread as it's directly related to the completion block issue.
