### ISSUE TITLE
blinking animation Lottie 3.0.3

### ISSUE THREAD

**Issue by alexanderkhitev** [airbnb/lottie-ios#836]
## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0.3

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

Hello! We used Lottie 2.5.2, our animation worked correctly, then we updated to Lottie 3.0.3, while playing the animation (when the animation ends) there is flickering, in the previous version it was not. I created a demo project for two versions.
[Test-Lottie-2.5.2.zip](https://github.com/airbnb/lottie-ios/files/3024341/Test-Lottie-2.5.2.zip)
[Test-Lottie-3.0.3.zip](https://github.com/airbnb/lottie-ios/files/3024342/Test-Lottie-3.0.3.zip)

**Comment by mohammed-shakeer** [comment]
Even I am facing the same issue of flickering after updating the library to 3.0

**Comment by caioremedio** [comment]
Same issue here with some old files. Still happening on 3.1

**Comment by JustinasKristopaitis** [comment]
Still happens with lottie v3.2.1. Any updates how to solve the issue?

**Comment by calda** [comment]
In 3.4.0 we added a new rendering engine implementation powered by Core Animation. This new engine has better performance and also fixed this type of flickering issue. You can learn more here: https://github.com/airbnb/lottie-ios/discussions/1627

I tested the animation you shared, and it plays as expected using the new Core Animation engine.
