### ISSUE TITLE
Cannot programmatically set AnimatedButton on/off state

### ISSUE THREAD

**Issue by Speedrockracer** [airbnb/lottie-ios#837]
Hi,
I just upgraded our app from Lottie 2.5.2 to 3.0.3 and I ran into an Issue with the new AnimatedSwitch.
Previously I would use `button.setOn(true, animated: true)` to programmatically set the on/off state and it would animate nicely to that state.
However the new AnimatedSwitch does not have this method I can only do `button.isOn = true` and it wil jump to that state.
I checked the code and internally it uses the function `updateOnState(isOn: Bool, animated: Bool)`
But this function is internal and swift wont allow me to call it from my app.
Can we make this function public so we can animate the on/off state? I can make a pr for this if you guys are busy.

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?
Lottie 3.0

## What Platform are you on? 
- [] iOS

## What Language are you in?
- [] Swift

## Expected Behavior 
Being able to programmatically set the button on/off state animated.

## Actual Behavior
Can only set the button on/off state without animation.

**Comment by buba447** [comment]
Added here https://github.com/airbnb/lottie-ios/pull/856
