### ISSUE TITLE
Can change to gradient Color for Layer in runtime?

### ISSUE THREAD

**Issue by zhangjunmax** [airbnb/lottie-ios#839]
Can change to gradient Color for Layer in runtime?

**Comment by buba447** [comment]
Unfortunately this is not supported yet. I will add it to my list.

**Comment by imjoeybrennan** [comment]
Would love this supported for iOS. Looks like android has it implemented https://github.com/airbnb/lottie-android/pull/1153.

Thank you for continued work on this amazing tool!

**Comment by buba447** [comment]
Now supported in 3.1.4
