### ISSUE TITLE
play toFrame method not working as expected

### ISSUE THREAD

**Issue by nisargmehta** [airbnb/lottie-ios#843]
Hello,
We have a lottie file with 100 frames. Its a circular dial with values from 0 to 99. The idea is to set the animation to a particular frame to show that value on the dial.
When using play toFrame method on iOS, visually it appears to show two numbers. So if toFrame value is 5 the animation visually shows numbers 4 and 5. 

On Android we were able to achieve this by using this code:
`override fun onAnimationEnd(animation: Animator?) {
                        sampleInterpretationImage.removeAllAnimatorListeners()
                        sampleInterpretationImage.setAnimation(it.getInt(IMAGETAG))
                        sampleInterpretationImage.setMinAndMaxFrame(ppm, ppm)
                        sampleInterpretationImage.playAnimation()
                    }`

Since there is no method to setMinAndMaxFrame on iOS we cannot figure out how to solve this.

## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 2.5.0

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 

![expected](https://user-images.githubusercontent.com/8175781/55361571-79f89680-548c-11e9-9895-e22d6d466a49.png)

## Actual Behavior

![actual](https://user-images.githubusercontent.com/8175781/55361575-811fa480-548c-11e9-9400-fd6a043fc12c.png)

## Code Example
`self.animationView.setAnimation(named: lottieFile)
let frame = Int(lround(value))
self.animationView.play(toFrame: frame as NSNumber, withCompletion: nil)`

**Comment by calda** [comment]
Could you share your animation json, and a sample project that reproduces this issue?
