### ISSUE TITLE
Make all the Codable models public

### ISSUE THREAD

**Issue by joekim** [airbnb/lottie-ios#849]
## Check these before submitting:
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Feature Request

For projects I'm working on we are using more and more information in Lottie files to construct user interfaces. A lot of useful information is decoded by the `Animation` model but most of it is not public. For example, `markers` are on the `Animation` object but they cannot be iterated over for use with the `func progressTime(forMarker named: String) -> AnimationProgressTime?` method. What if we made all the Codable models and properties public? I'd be happy to make a PR for it.

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [x] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift

## Code Example

```    
   func printAnimations(values: TemplateValues) {
        let markerNames =  animationView.animation!.markerNames!.sorted()
        for markerName in markerNames{
            print("\(markerName): \(animationView.progressTime(forMarker: markerName)!)")
        }
    }
````

**Comment by Coeur** [comment]
Then, please make a PR. :)

**Comment by calda** [comment]
I'd prefer to keep these `internal`, to avoid growing the public API surface of the library (e.g. changing these types would become source-breaking)
