### ISSUE TITLE
SIGTRAP crashes on iOS 10

### ISSUE THREAD

**Issue by gravy-luke** [airbnb/lottie-ios#851]
## Check these before submitting:
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Crashing Bug
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0.3

## What Platform are you on? 
- [x] iOS

## What Language are you in?
- [x] Swift

## Expected Behavior 
When running animations that worked fine with 2.5.2 they should not result in SIGTRAP crashes.

## Actual Behavior
When running animations that worked fine with 2.5.2 SIGTRAP crashes occur on iOS 10; iOS 11 and 12 seem to be unaffected.

## Animation JSON
[exampleAnimation1.json.txt](https://github.com/airbnb/lottie-ios/files/3050070/exampleAnimation1.json.txt)

## Crash Log(s)
[crashExample1.txt](https://github.com/airbnb/lottie-ios/files/3050065/crashExample1.txt)
[crashExample2.txt](https://github.com/airbnb/lottie-ios/files/3050066/crashExample2.txt)
[crashExample3.txt](https://github.com/airbnb/lottie-ios/files/3050067/crashExample3.txt)

## Note(s)
- Doesn't happen immediately
- In a span of ~5 days, we saw 150+ crashes caused by this issue

**Comment by buba447** [comment]
Are you still seeing this with the latest release?

**Comment by gravy-luke** [comment]
We have since dropped iOS 10 support; however, last time we had iOS 10 supported this was still an issue.

**Comment by calda** [comment]
Closing since this seems like a potentially outdated issue. Feel free to re-open if you're still experiencing this issue.
