### ISSUE TITLE
[Feature Request] Disable animations globally

### ISSUE THREAD

**Issue by xavierLowmiller** [airbnb/lottie-ios#854]
# Description

In our app, we do a lot of [snapshot testing](https://github.com/pointfreeco/swift-snapshot-testing).
To keep these deterministic, we disable the Lottie animations by hand, which works :+1:.

It would be much easier, though, if Lottie looked at `UIView.areAnimationsEnabled` so that animations could be enabled or disabled globally.

If you're interested, I can try and submit a pull request.

## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [ ] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [x] Feature Request
- [ ] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 
- [ ] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [ ] Objective-C

**Comment by kwstasna** [comment]
@xavierLowmiller how do you disable the animations while you take the snapshots?

**Comment by xavierLowmiller** [comment]
Just set `UIView.areAnimationsEnabled = false`

**Comment by kwstasna** [comment]
@xavierLowmiller ah ok! Do you know how to display only the final frame so that the test don’t have to wait for the animation to finish ?

**Comment by xavierLowmiller** [comment]
Oh sorry, you mean how we disable the Lottie animations?

I can't take a look how we exactly did it because I've switched jobs and don't have access to the code base.

As far as I remember, we just called `stop()` on the view, and maybe set the `animationProgress` to some deterministic value.
