### ISSUE TITLE
[Feature Request] Create callback when markers are reached

### ISSUE THREAD

**Issue by JoeSzymanski** [airbnb/lottie-ios#858]
## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [X] Feature Request

## Which Version of Lottie are you using?
Lottie 3.0

## What Platform are you on? 
- [] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift
- [] Objective-C

## Feature Request
Markers are a new and interesting feature that allows for better updates to synchronize key times in an animation to actions that happen outside of the animation. Unfortunately, the only uses for them right now are either limiting parts of an animation to play and getting the timestamp for how long into an animation the marker is placed.

Since there is only a mechanism for getting a time value, any synchronization still requires pulling that time and then setting separate timers to manage the other events.

Instead, Lottie should be updated to support an optional AnimationMarkerDelegate that gets called with the name of the Marker whenever a marker is reached in the animation. This would significantly simplify synchronization with the animations without a huge overhead.

**Comment by calda** [comment]
We are using the Core Animation rendering engine by default in Lottie 4.0, which doesn't support performing arbitrary callbacks when the animation reaches a given frame.
