### ISSUE TITLE
Outdated version on Cocoapods

### ISSUE THREAD

**Issue by steve228uk** [airbnb/lottie-ios#86]
The current version pushed to the Cocoapods trunk is 1.0.0 which is not inline with the latest version 1.0.3.

**Comment by alapergola** [comment]
Is that why I'm getting this error message when installing pods ? 
Analyzing dependencies
[!] Unable to find a specification for `lottie-ios`

**Comment by steve228uk** [comment]
@alapergola It should find one, try running `pod repo update`.

This will load the latest direct from Github:

```ruby
pod 'lottie-ios', :git => 'https://github.com/airbnb/lottie-ios.git', :tag => '1.0.3'
```
