### ISSUE TITLE
AnimatedButton event firing twice

### ISSUE THREAD

**Issue by prmacias** [airbnb/lottie-ios#862]
AnimatedButton firing events twice. I implemented the animatedbutton in storyboard and linked the action event and it is firing twice. I reproduced the issue in example folder by programmatically added the target to call the function. See below for the code. 

## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift
- [] Objective-C

## Expected Behavior 
The expected behavior is to click once which fires an event once. 

## Actual Behavior
The actual behavior is the event is firing twice. 

Here is the attached screenshot - 

![Uploading Screen Shot 2019-04-13 at 1.22.53 PM.png…]()

## Code Example

twitterButton.addTarget(self, action:#selector(hi), for: .touchUpInside)

@objc func hi() {
        print("hi")
    }

output is 
hi
hi

you can find this code in https://github.com/prmacias/lottie-ios-tests. Thank you for all of this work!

**Comment by buba447** [comment]
Found a fix and pushed it here https://github.com/airbnb/lottie-ios/pull/877
