### ISSUE TITLE
Debug View Hierarchy fails to run with Lottie 3.0.4

### ISSUE THREAD

**Issue by nezhyborets** [airbnb/lottie-ios#865]
## Check these before submitting:
- [+] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [+] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [+] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [+] iOS

## What Language are you in?
- [+] Swift
- [] Objective-C

## Expected Behavior 

Ability to use View Debugger on screens that contains Lottie. 

## Actual Behavior

When trying to run View Debugger on screen that contains Lottie, the View Debugger starts, but doesn't finish it's initial process with an error:
> path_to_project/Pods/lottie-ios/lottie-swift/src/Private/LayerContainers/CompLayers/MaskContainerLayer.swift: 85: 19: Fatal error: Use of unimplemented initializer 'init(layer:)' for class 'Lottie.MaskLayer'

![Screen Shot 2019-04-15 at 2 15 51 PM](https://user-images.githubusercontent.com/2803931/56128998-d3cb8700-5f89-11e9-9466-00e1cb9ab694.png)

**Comment by buba447** [comment]
Just put a fix here https://github.com/airbnb/lottie-ios/pull/874
Will go out in 3.0.5
