### ISSUE TITLE
Loop animation stops when coming from background

### ISSUE THREAD

**Issue by AlbGarciam** [airbnb/lottie-ios#866]
## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0.3

## What Platform are you on? 

- [] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift
- [] Objective-C

## Expected Behavior 
When coming from background if I set loop mode to true, it should continue with the animation

## Actual Behavior
When coming from background, animation stops.

## Code Example
```
   func showLoader() {
        let animation = AnimationView(name: "loader_animation_white")
        animation.loopMode = .loop
        animation.play()
        animation.frame = bounds
        addSubview(animation)
        self.loader = animation
    }
```

**Comment by buba447** [comment]
Try setting the `animation.backgroundBehavior` to `pauseAndRestore`

That should fix your issue. Read more about background behavior in the readme.

https://github.com/airbnb/lottie-ios/blob/master/README.md#background-behavior

**Comment by AlbGarciam** [comment]
Nice 👍
