### ISSUE TITLE
Performance problems with specific animations

### ISSUE THREAD

**Issue by JoeSzymanski** [airbnb/lottie-ios#871]
## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [X] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift
- [] Objective-C

## Expected Behavior 
We have a complex animation that was working fine in Lottie 2.5.2, but is hitting major performance issues in Lottie 3.0.4. We attempting to display the animation using Instruments, Lottie 2.5.2 maxes out at ~50% CPU usage, but Lottie 3.0.4 hits 100% CPU usage and appears to be dropping a lot of frames.

We aren't sure what specifically is causing the performance issues, but this is blocking our ability to update to the latest version of Lottie.

Related to the animation performance issues, the same animation also takes a long time to initialize, likely for similar reasons.

## Animation JSON
Animation file in question:
[treasurechest-animation1.json.zip](https://github.com/airbnb/lottie-ios/files/3085784/treasurechest-animation1.json.zip)

**Comment by buba447** [comment]
Im investigating performance issues with Swift and will add your animation to the list. Im not sure when I will be able to get a performance update, as I'm maintaining this in my free time, but I will let you know. 

Cheers!

**Comment by JoeSzymanski** [comment]
@buba447 Thanks for the quick update. If there is anything I can look into to try to help track down specific issues, please let me know. I'll likely have some time to try to dig into our specific animation, but I'm not overly familiar with the Lottie code to know where the best places to look will be.

**Comment by buba447** [comment]
Ive taken a couple cursory looks into the issues. I fairly sure a large part of it has to do with how swift manages memory reference count with structs, but I'm not 100% certain.

**Comment by JoeSzymanski** [comment]
I'm digging a bit and finding some pieces to dig into. First, it turns out we have a full set of layers that are never displayed (related to an old version of the animation before we split it into multiple parts). Those "invisible" layers are causing a large amount of the time spent running the display code.
I'm still working to figure out why a small shape layer would take almost a full millisecond to display by itself (a lot of time given there are dozens of them in the entire animation).

**Comment by JoeSzymanski** [comment]
@buba447 I've spent an afternoon digging into the Swift code without too much success, mostly finding that there seems to be a hard lower bound on how long it takes to process each node, so animations with a large number of nodes take very long to process.

I stopped for a minute to look back at the ObjC implementation and noticed that there is occlusion handling in ObjC that isn't done in the Swift version (see https://github.com/airbnb/lottie-ios/blob/lottie/objectiveC/lottie-ios/Classes/AnimatableLayers/LOTLayerContainer.m#L257-L265). This looks like it's most likely the primary cause of the performance issues we are seeing, as I found out that there are hidden nodes in the animation that the ObjC implementation appears to be ignoring.

**Comment by buba447** [comment]
Ahh that bit isn’t exactly occlusion testing. Its checking if the current frame is outside the time bounds of the layer. Hidden layers are still evaluated because they can have an affect on visible layers in parenting, though I could be a bit more clever about that.

That might be a quick win, ill get something up and we can test it.

Thanks for digging in!

**Comment by JoeSzymanski** [comment]
With a quick test, it does look like it's improving performance a ton and the animation no longer drops frames, so I think that's probably a good candidate for a big performance improvement.

**Comment by buba447** [comment]
@JoeSzymanski just put a PR https://github.com/airbnb/lottie-ios/pull/873 Please check it to see if that helps.

**Comment by JoeSzymanski** [comment]
With a quick test of our animation files, that looks like it fixed the performance issues we were hitting. :)
