### ISSUE TITLE
Kerning is way off

### ISSUE THREAD

**Issue by joekim** [airbnb/lottie-ios#875]
## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [x] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift

## Expected Behavior 

I have a simple after effects file with a single text document. I modified the tracking slightly. For my export I unselected "Glyphs" so that fonts are not converted to shapes.

Here's how it looks in after effects:

![image](https://user-images.githubusercontent.com/133459/56322788-d3182980-611e-11e9-863e-7188b755d7d6.png)

lottie-web can render the export reasonably:

![image](https://user-images.githubusercontent.com/133459/56322777-cd224880-611e-11e9-94ff-f430c8935cb0.png)

## Actual Behavior

lottie-ios renders the tracking way off:

![image](https://user-images.githubusercontent.com/133459/56322904-25594a80-611f-11e9-88e8-1f9924eb4d3a.png)

## Code Example

I'm wondering if lottie-ios is trying to use the tracking directly instead of converting it to kerning using the following formula:

```
kerning = (fontSize * tracking ) / 1000.0 
```

## Animation JSON

Animation json:
https://drive.google.com/uc?export=download&id=1maehdnxAPv5GwWWaNybWN9YhU09g-Hqd

After effects:
https://drive.google.com/uc?export=download&id=1h884ABx1lIPP26XwZodMM2yokq_a1C-S

**Comment by buba447** [comment]
Yup. You are totally right! Fixing now.

**Comment by buba447** [comment]
Got a fix here https://github.com/airbnb/lottie-ios/pull/876

![giphy](https://user-images.githubusercontent.com/1163980/56386774-b2b89f80-61f0-11e9-80d7-13c431c1e23a.gif)
