### ISSUE TITLE
Lottie Doesn't Animate

### ISSUE THREAD

**Issue by iadxworld** [airbnb/lottie-ios#879]
## Check these before submitting:
- [-] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [-] This issue isn't related to another open issue

## This issue is a:
- [-] Non-Crashing Bug (Visual or otherwise)

## Which Version of Lottie are you using?

Lottie 3.0.4

## What Platform are you on? 

- [] MacOS
- [-] iOS

## What Language are you in?
- [-] Swift
- [] Objective-C

## Expected Behavior 
<img width="739" alt="Screen Shot 2019-04-19 at 7 42 59 PM" src="https://user-images.githubusercontent.com/11725530/56450480-5e3e1e80-62db-11e9-8780-ef0e4de1a353.png">

## Actual Behavior
<img width="284" alt="Screen Shot 2019-04-19 at 7 41 39 PM" src="https://user-images.githubusercontent.com/11725530/56450466-3f3f8c80-62db-11e9-99ff-9f8c5be5539e.png">

## Code Example
`
    import UIKit
    import Lottie
    
    class ViewController: UIViewController {

    let animationLogo = AnimationView(name: "intro")
    
    override func viewDidLoad() {
        super.viewDidLoad()
        DispatchQueue.main.asyncAfter(deadline: .now() + 3/2) {
            self.setupLottie()
        }
       }

    func setupLottie() {
        animationLogo.frame = CGRect(x: view.frame.maxX/2 - 150, y: view.frame.maxY/2 - 150, width: 300, height: 300)
        animationLogo.contentMode = .scaleAspectFit
        animationLogo.backgroundColor = .black
        self.view.addSubview(animationLogo)
        animationLogo.loopMode = .loop
        animationLogo.play()
    }

    }
`

## MVC 
[Lottie Test.zip](https://github.com/airbnb/lottie-ios/files/3099697/Lottie.Test.zip)

**Comment by buba447** [comment]
This animation is using Effects + Expressions. Lottie-ios and Lottie-android do not support Effects or Expressions. Sorry! You can try baking the animation or manually transferring the keyframes.

**Comment by iadxworld** [comment]
Thanks for the response. Well, wouldn't those options eat up a chunk of memory ?

**Comment by iadxworld** [comment]
baking works. thanks for help. cheers
