### ISSUE TITLE
Text layers not supported?

### ISSUE THREAD

**Issue by ysfnjr** [airbnb/lottie-ios#88]
Heyo, I'm new to animations so sorry if I'm doing something dumb. 

I'm having a hard time getting simple text layers to display on iOS. I have an example AE project attached.

I have a text layer and a shape layer. I then use Bodymovin to export as .json, and run it in my test iOS app. I can see the shape animating, but the text isn't there at all. 

If I try to use the same .json in an html player, I'm able to see the text just fine. 

[textTest.zip](https://github.com/airbnb/lottie-ios/files/771657/textTest.zip)

**Comment by therealsalih** [comment]
Hi @ysfnjr I took a look at your AE file and yes you are correct, text layers aren't supported in Lottie but they are supported in Bodymovins web renderer.  
We'll be working on supporting them in the coming months.
Here are a couple of other features that aren't yet supported

**Currently Unsupported After Effects Features**
Image Layers
Precomps (coming soon)
Even-Odd winding paths
Trim Shapes Individually feature of Trim Paths
Expressions
3d Layer support
Gradients


Thanks!
