### ISSUE TITLE
Cannot initialize LayerType from invalid Int value 9

### ISSUE THREAD

**Issue by jantimar** [airbnb/lottie-ios#882]
Hi I have issue with current animation. Older, more simple animation in project still wokrs, but new animation don't create, just return nil.
Pars json animation return 
```
▿ DecodingError
  ▿ dataCorrupted : Context
    ▿ codingPath : 3 elements
      - 0 : CodingKeys(stringValue: "assets", intValue: nil)
      ▿ 1 : _JSONKey(stringValue: "Index 0", intValue: 0)
        - stringValue : "Index 0"
        ▿ intValue : Optional<Int>
          - some : 0
      - 2 : Discriminator(stringValue: "ty", intValue: nil)
    - debugDescription : "Cannot initialize LayerType from invalid Int value 9"
    - underlyingError : nil
```

Current version `LayerType` support just this cases
```
  case precomp
  case solid
  case image
  case null
  case shape
  case text
```
 So number `9` is of course not supported, current beta (3.0.5) has same `LayerType` cases. It can be problem with exporting json ?

## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

**Comment by buba447** [comment]
Sound like an unsupported layer type. I believe 9 is MOV files, though Im not certain. Check your AE file to see if there are any layers that arent Text, Shape, Image, Null, or Solid.
