### ISSUE TITLE
3D orientation / rotation

### ISSUE THREAD

**Issue by atom22** [airbnb/lottie-ios#883]
Hello guys,

My After Effect animation is making use of 3D layers in order to apply rotations on X and Y axis. The rotations are well applied in the bodymovin json (it's ok in preview and in html too), but when imported in iOS these are not working (Lottie 3.0). Same with the orientation transformation.

Is it an unsupported transformation (doesn't look like it is following your list) ? How can I achieve it ?

**Comment by buba447** [comment]
3d Layers are not supported in iOS or Android.

**Comment by proxemics** [comment]
Any updates on this as a possible feature update? I had asked on the Slack and it sounds like this is now possible on iOS and maybe even planned? This is definitely a feature that comes up a lot in my work and would be an amazing addition!

**Comment by proxemics** [comment]
Just curious if this feature is now possible or planned with some of the recent updates to iOS? Thanks!

**Comment by AlanCourt** [comment]
I'm really want this feature too.

**Comment by isblvgara** [comment]
is there a way to transform the 3D Paths into keyframes or something similar?

**Comment by pawel3ala** [comment]
hey guys, does anybody have some info if this feature is supported in the latest version `3.4.x` ?
