### ISSUE TITLE
Favoriting animation isn't right after upgrade to 3.0

### ISSUE THREAD

**Issue by ramharshvardhan** [airbnb/lottie-ios#885]
A "favoriting" animation isn't right anymore after upgrading to 3.0 version with Swift.

What we expect is some sort of "fireworks" around the heart while favoriting, instead we find just one arrow pointing out from the top right. (see details below).

## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] iOS

## What Language are you in?
- [] Swift

## Expected Behavior 
https://lottiefiles.com/share/GHH04A

## Actual Behavior
<img width="378" alt="Screen Shot 2019-04-23 at 3 52 46 PM" src="https://user-images.githubusercontent.com/13264459/56611464-dbb9a580-65df-11e9-9a00-0c901f977130.png">

This video might be of better help:
[Lottie 3.0 Favorite.MP4.zip](https://github.com/airbnb/lottie-ios/files/3109342/Lottie.3.0.Favorite.MP4.zip)

You can also use your `LottiePreview` to QR-scan this link here: https://lottiefiles.com/share/GHH04A, you should be able to see the difference.

And we do use an `After Effects` repeater for that animation (fyi):

![After Effects Repeater](https://user-images.githubusercontent.com/13264459/56611597-2804e580-65e0-11e9-9ec2-bb5a62723ce1.png)

## Code Example
```
private var animationView = AnimationView(name: "") //loads from JSON
public func prepareForReuse() {
        guard let startFrame = animationView.animation?.startFrame else { return }
        animationView.currentFrame = startFrame
    }
    
    @objc func buttonTapped() {
        if isSelected {
            animationView.animationSpeed = -1 //to reverse the animation
        } else {
            animationView.animationSpeed = 1
        }
        isAnimating = true
        animationView.play { _ in
            self.isAnimating = false
        }
        actions?.didTapAction()
    }
    
    override public var isSelected: Bool {
        didSet {
            guard !isAnimating else { return }
            if isSelected {
                guard let endFrame = animationView.animation?.endFrame else { return }
                animationView.currentFrame = endFrame
            } else {
                guard let startFrame = animationView.animation?.startFrame else { return }
                animationView.currentFrame = startFrame
            }
        }
    }
```

## Animation JSON

[LottieFavorite.json.zip](https://github.com/airbnb/lottie-ios/files/3109365/LottieFavorite.json.zip)

**Comment by buba447** [comment]
This is a repeat of https://github.com/airbnb/lottie-ios/issues/846

Currently in 3.0.x Repeaters are not supported. Will update when support is added.

**Comment by ramharshvardhan** [comment]
Ah okay, sorry for missing that out. And thank you for the info. Is there a tentative timeline on the repeater support?
