### ISSUE TITLE
When will we have Swift5 support for Lottie?

### ISSUE THREAD

**Issue by purifier1990** [airbnb/lottie-ios#890]
## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [Yes] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [Yes] iOS

## What Language are you in?
- [Yes] Swift
- [] Objective-C

## Expected Behavior 
Lottie can be compiled with Swift5 based project

## Actual Behavior
Xcode error
Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0.1 compiler

**Comment by nekrich** [comment]
#870 Closes this issue
