### ISSUE TITLE
Animation doesn't load

### ISSUE THREAD

**Issue by renanstig** [airbnb/lottie-ios#894]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 
![IMG_8C25213AB4C3-1](https://user-images.githubusercontent.com/4225270/56816713-66024380-6844-11e9-8ff7-46d843f250a0.jpeg)

## Actual Behavior
![Simulator Screen Shot - iPhone Xʀ - 2019-04-26 at 15 55 18](https://user-images.githubusercontent.com/4225270/56816650-423efd80-6844-11e9-9b8f-5df4ee0cb64d.png)

## Code Example

I've used the Swift example provided by you guys from this github repo: https://github.com/airbnb/lottie-ios/tree/master/Example

I replaced the json being loaded by the one I'm using and it still didn't load

## Animation JSON

[onboarding_animation.json.zip](https://github.com/airbnb/lottie-ios/files/3121801/onboarding_animation.json.zip)

Hello guys,

Above you can find all information of the problem I'm having.
Currently, I'm trying to render the animation from the JSON attached here, but for some reason it doesn't load. The `Animation.Named()` is nil after I try to load the file. 
The funny thing is when I use this website: https://lottiefiles.com/share/vs6y3Y it renders the file, if I scan the QRCode, the app is also able to load the file, but it doesn't work in the Example project. 

Could you please help me with this or give me an idea why this is happening?

Best regards,
Renan.

**Comment by kylebrowning** [comment]
Are you using a repeater?

**Comment by renanstig** [comment]
no, although I've just added `animationView.loopMode = .loop` and it still doesn't load. 
Any other ideas?

**Comment by renanstig** [comment]
@kylebrowning , I looked into the issue deeper and I found out that there's an exception being thrown: `Cannot initialize ShapeType from invalid string value op`, I checked the `Enum` for ShapeType and I could see that `op` isn't one of them. Is it a bug in the lib or is it something that the design team here did wrong?

**Comment by buba447** [comment]
@renanstig Hello! A shape layer with `op` is an Offset Path. Offset Paths are not supported by lottie-ios or lottie-android yet. You can see the full list of supported features here http://airbnb.io/lottie/#/supported-features

Sorry for the trouble!

**Comment by christie-alphero** [comment]
Hi @renanstig - I am having the same issue as you described. When you say you saw there is an exception, where did you find this? I'm having trouble seeing anything printed in the standard console from lottie :(

**Comment by renanstig** [comment]
Hi @christie-alphero , what I did wasn't super fancy, I just added a breakpoint in the `AnimationPublic.swift`, in the line `46`, did I couple of changes and I logged the error by using the command `po`. As my issue was related to Decoding the json file, I could get the exception at this point.

I do hope it helps you.

**Comment by focker321** [comment]
Hi, I had the same problem, but it was fixed adding bundle in signature.

**Comment by calda** [comment]
Closing since this animation appears to render correctly on master. Thanks for the report!
