### ISSUE TITLE
Lottie iOS rendering issue

### ISSUE THREAD

**Issue by jacobcxdev** [airbnb/lottie-ios#896]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 

See `YAK Loading Animation.mp4` in the [ZIP](https://github.com/airbnb/lottie-ios/files/3124422/Archive.zip).

## Actual Behavior

See `ScreenRecording_04-23-2019 13-52-28.mp4` in the [ZIP](https://github.com/airbnb/lottie-ios/files/3124422/Archive.zip).

## Code Example
```swift
import UIKit
import Lottie

class ViewController: UIViewController {
    @IBOutlet weak var lottieView: UIView!
    let animationView = LOTAnimationView()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        animationView.animation = "LaunchAnimation"
        animationView.frame.size = lottieView.frame.size
        
        lottieView.addSubview(animationView)
    }

    @IBAction func playButton(_ sender: Any) {
        animationView.play()
    }
    
}
```

## Animation JSON

See `data.json` in the [ZIP](https://github.com/airbnb/lottie-ios/files/3124422/Archive.zip).

## Message
I created a launch animation for my app in After Effects, although I’m running into many issues when trying to render it. It’s so horribly wrong that I’m not sure if anything’s actually rendered correctly! Because of this, it’s quite hard to explain the issues, so I’ve taken the liberty of attaching:

- The After Effects project file
- A test Xcode project for rendering it
- An mp4 rendered by After Effects, showcasing the expected behaviour
- A screen recording of it’s actual behaviour
- The Lottie json and images
- A demo html

If you are able to help with this, I’d be greatly appreciative. I’ve been stuck with this issue for several weeks, and I’ve gotten nowhere.

Thanks :)

**Comment by jacobcxdev** [comment]
Just commenting to say I'm still stuck on this, over 11 days later... any help would be appreciated.

**Comment by jacobcxdev** [comment]
1 week later... You must be busy, but surely you could spare 5 out of the ~25920 minutes since I posted this?

**Comment by buba447** [comment]
Thanks for you patience. I have opened your AE file, and I see that it links to serveral AI files that are not in the zip. First thing Id suggest is expanding AE files into vector layers. In the current configuration lottie will just output images and render the image on screen, so the animation is not a true vector animation.

As for your problem I cannot say what the issue it. The ae file is hard to debug without the linked files so it's hard to say whats happening. I see that you have several masks on each layer, all of which are set to subtract. Its possible theres an issue with the configuration of masks but again Im not sure.

Again, it is highly suggested that you work with vector layers instead of masks.

Finally the project file you sent is using lottie 2.5 not the new swift version, I ran the animation in the new swift version and while the animation is still broken, it's broken in a different way. So thats something.

![giphy](https://user-images.githubusercontent.com/1163980/57938933-3a98d480-7897-11e9-9d41-d9c5b2ef87ab.gif)

**Comment by jacobcxdev** [comment]
> Thanks for you patience. I have opened your AE file, and I see that it links to serveral AI files that are not in the zip. First thing Id suggest is expanding AE files into vector layers. In the current configuration lottie will just output images and render the image on screen, so the animation is not a true vector animation.
> 
> As for your problem I cannot say what the issue it. The ae file is hard to debug without the linked files so it's hard to say whats happening. I see that you have several masks on each layer, all of which are set to subtract. Its possible theres an issue with the configuration of masks but again Im not sure.
> 
> Again, it is highly suggested that you work with vector layers instead of masks.
> 
> Finally the project file you sent is using lottie 2.5 not the new swift version, I ran the animation in the new swift version and while the animation is still broken, it's broken in a different way. So thats something.
> 
> ![giphy](https://user-images.githubusercontent.com/1163980/57938933-3a98d480-7897-11e9-9d41-d9c5b2ef87ab.gif)

Thank you for the reply! I’m currently being spammed with random Duolingo emails (when I don’t even have an account with them), so this is certainly a nice notification to receive. I’ll try what you’ve suggested and will get back to you - I had thought I had included everything in the ZIP, but perhaps not - my bad!

**Comment by jacobcxdev** [comment]
Having taken your advice, I've recreated the animation using vector layers, shapes, a mask and a track matte. Despite being listed as supported, the track matte isn't rendering at all, meaning that only half of the animation renders correctly.

You can find a ZIP containing the following items [here](https://github.com/airbnb/lottie-ios/files/3198067/Archive.zip):
- the After Effects project (use the composition named `Bubble`)
- an `MP4` of the desired animation
- the `data.json` and `demo.html` produced by Bodymovin
- the Lottie-iOS example Xcode project modified to play this animation

Thank you for your time :)

**Comment by buba447** [comment]
Ive taken a look at your new file. Layer Alpha Mattes (aka Track Mattes)
are supported but the `Set Matte` effects are not supported. No effects of
any kind are supported.

You can set track mattes by selecting the dropdown in the timeline editor.
[image: Screen Shot 2019-05-20 at 9.35.21 AM.png]

Cheers!

>

**Comment by buba447** [comment]
Theres a nice guide for making animations in AE here
http://airbnb.io/lottie/#/after-effects

>

**Comment by jacobcxdev** [comment]
> Ive taken a look at your new file. Layer Alpha Mattes (aka Track Mattes) are supported but the `Set Matte` effects are not supported. No effects of any kind are supported. You can set track mattes by selecting the dropdown in the timeline editor. [image: Screen Shot 2019-05-20 at 9.35.21 AM.png] Cheers!
> […](#)

Thanks for your quick response! Is there any way for me to achieve what I am trying to achieve with set matte with track matte? I essentially need the `Dots` layer to be a mask for the underlying layers, with all the animations intact.

> Theres a nice guide for making animations in AE here
> http://airbnb.io/lottie/#/after-effects

Thanks! I will take a look at this.

**Comment by jacobcxdev** [comment]
Nevermind - I managed to get it done with this setup:

![](https://user-images.githubusercontent.com/27970288/58027011-a1282780-7b0f-11e9-90ba-a5b48067b42d.png)

Thanks again for your help :)
