### ISSUE TITLE
big json lead to crash

### ISSUE THREAD

**Issue by VVege** [airbnb/lottie-ios#897]
- [] iOS

## What Language are you in?
- [] Swift

## Expected Behavior 

memory keep normal

## Actual Behavior

memory explosion，1.2G。crashed
## Animation JSON

https://resources.laihua.com/2019-4-28/a041f460-6983-11e9-8c29-fdc51134b5a1.json

**Comment by MadeBugs** [comment]
+1，me too

**Comment by calda** [comment]
Closing since this seems like a potentially outdated issue. Feel free to re-open if you're still experiencing this issue.
