### ISSUE TITLE
how to load a url with zip,the zip contains json file and Image resources required for the file

### ISSUE THREAD

**Issue by 463292462** [airbnb/lottie-ios#898]

**Comment by buba447** [comment]
Lottie does not decompress compressed files automatically. You will have to unzip them elsewhere in your code and then load the animations. You will probably want to unzip them to the local disk and then load the animation/images from disk using the file method and a `FileImageProvider`.
Read more here:
https://github.com/airbnb/lottie-ios#loading-animation
https://github.com/airbnb/lottie-ios#filepathimageprovider

For decompressing consider using a library such as https://github.com/marmelroy/Zip or https://github.com/ZipArchive/ZipArchive

Cheers!

**Comment by 463292462** [comment]
Thanks for your reply! Is there an official follow-up support plan for this issue?

**Comment by 463292462** [comment]
Thanks for your reply! I think Android has API support, so does iOS have an official follow-up support plan for this problem?

**Comment by 463292462** [comment]
> Lottie does not decompress compressed files automatically. You will have to unzip them elsewhere in your code and then load the animations. You will probably want to unzip them to the local disk and then load the animation/images from disk using the file method and a `FileImageProvider`.
> Read more here:
> https://github.com/airbnb/lottie-ios#loading-animation
> https://github.com/airbnb/lottie-ios#filepathimageprovider
> 
> For decompressing consider using a library such as https://github.com/marmelroy/Zip or https://github.com/ZipArchive/ZipArchive
> 
> Cheers!

Thanks for your reply! I think Android has API support, so does iOS have an official follow-up support plan for this problem?
