### ISSUE TITLE
Animation performance issue.

### ISSUE THREAD

**Issue by adad184** [airbnb/lottie-ios#901]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)

## Which Version of Lottie are you using?

Lottie 3.0.4

## What Platform are you on? 

- [x] iOS

## What Language are you in?
- [x] Swift

## Expected Behavior 
In `AnimationView`, `addAnimation` & `removeAnimation` should be paired.

## Actual Behavior
`removeAnimation` is missing in `animationMovedToWindow`, so in some cases `animationMovedToWindow` were called multiple times, causes the animation be added multiple times without being cleared.

## Code Example

```
  override func animationMovedToWindow() {

    if let context = self.animationContext {
      self.removeCurrentAnimation()    // this line is missing.
      self.addNewAnimationForContext(context)
    }
  }
```

**Comment by TheyCallMeTank** [comment]
same problem
