### ISSUE TITLE
Cannot extend AnimationView

### ISSUE THREAD

**Issue by ppamorim** [airbnb/lottie-ios#904]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [X] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0.4

## What Platform are you on? 
- [x] iOS

## What Language are you in?
- [X] Swift 5.0

## Actual Behavior

I cannot extend `AnimationView` (old `LOTAnimationView`) anymore. I use it on a custom class from my project.

<img width="716" alt="Screenshot 2019-05-11 at 17 18 11" src="https://user-images.githubusercontent.com/5521682/57572350-c4b4e900-7410-11e9-9d38-00f2feec7616.png">

**Comment by buba447** [comment]
The animation view is not really intended to be subclassed, theres a lot of state logic in there and subclassing could produce a lot of unexpected results. You could subclass UIView and add an animationview to it to add touch functionality.

**Comment by shelbygold** [comment]
I am having this same issue I was using LOTAnimationView before to extend the view and separate it from the controller. Now I am not able to extend AnimationVIew. Any way you can make that available to extend the class/
