### ISSUE TITLE
load downloaded and saved JSON file

### ISSUE THREAD

**Issue by SajjadKharrazi** [airbnb/lottie-ios#908]
hi
i downloaded a JSON file with `URLSession.shared.downloadTask` and saved it with `FileManager.default.moveItem`
now i have path of that JSON file

but now how can i load this JSON file in `AnimationView()`?

**Comment by lorenc-tomasz** [comment]
Have similar problem with objective-c project. Now I wondering how to properly load the JSON file (now I use animationFromJSON).

**Comment by calda** [comment]
Closing since this is a question and not a bug report. Feel free to start a [discussion](https://github.com/airbnb/lottie-ios/discussions) if you'd still like support.
