### ISSUE TITLE
What happended to LOTAnimationTransitionController support in 3.0?

### ISSUE THREAD

**Issue by 51d4** [airbnb/lottie-ios#909]
## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [X] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0.4

## What Platform are you on? 

- [] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift
- [] Objective-C

## Expected Behavior 

So recently I have updated to the latest Lottie version and have noticed that LOTAnimationTransitionController is no longer supported. I couldn't find any mention in the migration guide or other notes that would state the reason for removing this feature. Thus, I was wondering if this feature is indeed no longer supported, or is there now a different way of handling transitions between ViewControllers? And if so, perhaps there are some good examples for this? So far I haven't seen anything in the official example code either.

## Code Example
```
    // Old way of handling transitions using UIViewControllerTransitioningDelegate method
    func animationController(forPresented presented: UIViewController, presenting: UIViewController, source: UIViewController) -> UIViewControllerAnimatedTransitioning? {
        let animationController = LOTAnimationTransitionController(animationNamed: "transitionAnimation",
                                                                   fromLayerNamed: "layer1",
                                                                   toLayerNamed: "layer2",
                                                                   applyAnimationTransform: true)
        return animationController
    }
```

**Comment by buba447** [comment]
It is not yet supported in swift.

**Comment by 51d4** [comment]
@buba447 I see, thanks for the clarification :) Do you know when we could expect to see it back?
