### ISSUE TITLE
animation = nil 

### ISSUE THREAD

**Issue by inflamesonly** [airbnb/lottie-ios#914]
## comment

I'm trying to load animation with assets [], but for some reason it does not work. Everything works fine.

Ticks for target membership all cost

this problem may be due to http://airbnb.io/lottie/#/supported-features
How can you find out?

## This issue is a:
- [+] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [+] iOS

## What Language are you in?
- [+] Swift
- [] Objective-C

## Screenshot

![Screenshot at May 16 17-54-45](https://user-images.githubusercontent.com/16308988/57863992-c7924e00-7803-11e9-9cdc-82dc9c6439f5.png)

## Code Example

        let animationView = AnimationView(frame: self.view.frame)
        let animation = Animation.named("LottieLogo1")
        animationView.animation = animation
        animationView.loopMode = .loop
        animationView.frame = self.view.frame
        animationView.center = self.view.center
        self.view.addSubview(animationView)
        animationView.play()

## Animation JSON

[data.json.zip](https://github.com/airbnb/lottie-ios/files/3187695/data.json.zip)

**Comment by buba447** [comment]
I looked over your file and it is using several (https://github.com/airbnb/lottie-ios#supported-after-effects-features)[unsupported features]. Lottie-ios does not support adjustment layers or expressions.

**Comment by inflamesonly** [comment]
thx
