### ISSUE TITLE
Animation only goes half way with 3.0

### ISSUE THREAD

**Issue by khoogheem** [airbnb/lottie-ios#915]
## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0.4

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

[checkmark-animation.json.zip](https://github.com/airbnb/lottie-ios/files/3188787/checkmark-animation.json.zip)

This animation seems to only go about half way when we play it.  Then if we use speed -1 starts at half

**Comment by khoogheem** [comment]
ok.. looks like part of the problem was a tint we were using in objc that probably isn't correct now with swift 

```
extension LOTAnimationView {
    func tint(withColor tintColor: CGColor) {
        let keypath1 = LOTKeypath(string: "**.Color")
        let keypath2 = LOTKeypath(string: "**.**.Color")
        let keypath3 = LOTKeypath(string: "**.**.**.Color")
        let keypath4 = LOTKeypath(string: "**.**.**.**.Color")
        
        let primaryColorValue = LOTColorValueCallback(color: tintColor)
        
        self.setValueDelegate(primaryColorValue, for: keypath1)
        self.setValueDelegate(primaryColorValue, for: keypath2)
        self.setValueDelegate(primaryColorValue, for: keypath3)
        self.setValueDelegate(primaryColorValue, for: keypath4)
    }
}
```

swift - 
```
    func tint(withColor tintColor: UIColor) {
        let keypath1 = AnimationKeypath(keypath: "**.Color")
        let keypath2 = AnimationKeypath(keypath: "**.**.Color")
        let keypath3 = AnimationKeypath(keypath: "**.**.**.Color")
        let keypath4 = AnimationKeypath(keypath: "**.**.**.**.Color")
    
        let primaryColorValue = ColorValueProvider(tintColor.lottieColorValue)

        self.setValueProvider(primaryColorValue, keypath: keypath1)
        self.setValueProvider(primaryColorValue, keypath: keypath2)
        self.setValueProvider(primaryColorValue, keypath: keypath3)
        self.setValueProvider(primaryColorValue, keypath: keypath4)
    }
```

**Comment by khoogheem** [comment]
That seems to explain the forward animation.. but the reverse animation is still a little goofy

**Comment by buba447** [comment]
Just a heads up double wildcards `**` will search any depth. You should only have one `**` per keypath.

If you want to control the depth of the search use a single wildcard `*`

So `**.Color` will find every color node in your project.

**Comment by khoogheem** [comment]
cool... figured as much.. inherited code..  I think we got it all figured it out now

Thanks!!!!
