### ISSUE TITLE
Some animations don't show after updating lottie from version 2 to 3.0.6

### ISSUE THREAD

**Issue by CentrumGuy** [airbnb/lottie-ios#916]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [X] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0.6

## What Platform are you on? 

- [] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift
- [] Objective-C

## Expected Behavior 
Animation to show and play as expected. The specific animations that I am referring to worked in Lottie v2 but no longer work in version 3 despite not having any unsupported features

## Actual Behavior
Animation does not appear at all and print(Animation.named("Success Animation")) prints "nil" even though the animation did not change path and stayed the same as the animation before updating to version 3.0.6 of lottie from version 2. I even tried uploading the JSON to the lottie website to preview the animation on iOS via QR code but that didn't work as well.

## Code Example
print(Animation.named("Success Animation")) prints "nil" and for other animations it prints Optional(Lottie.Animation)

## Animation JSON
[Success Animation.json.zip](https://github.com/airbnb/lottie-ios/files/3189159/Success.Animation.json.zip)

**Comment by buba447** [comment]
The animation attached has an offset path, and also expressions. Both of which arent supported by any version of lottie-ios.
