### ISSUE TITLE
Rectangle size animation bugs

### ISSUE THREAD

**Issue by therealsalih** [airbnb/lottie-ios#92]
There are some bugs with the rectangle size when it animates.  JSON files and AE file are here:
[RectangleSize.zip](https://github.com/airbnb/lottie-ios/files/773215/RectangleSize.zip)

Youll see some various things within the different files in this AE file
In some animations the top right corner looks like its closing and un-closing
![feb-13-2017 21-23-33](https://cloud.githubusercontent.com/assets/5893643/22916339/bb486656-f232-11e6-800e-6a6cb10c33a7.gif)

In Rect_Size_07 you'll see the edges are supposed to look like they are sticky like this
![feb-13-2017 21-24-51](https://cloud.githubusercontent.com/assets/5893643/22916416/47f14d70-f233-11e6-9918-e3fc1c414e08.gif)

But instead its rendering them like this, and it looks like the square its bouncing around
![feb-13-2017 21-26-54](https://cloud.githubusercontent.com/assets/5893643/22916421/4d50a4e6-f233-11e6-914c-abbd8ed01261.gif)

I think it has something to do with it ignoring the easing along the Y axis, because Rect_Size_04_YsideonlyEased is supposed to look eased but it looks linear. Here is what it looks like
![feb-13-2017 21-29-43](https://cloud.githubusercontent.com/assets/5893643/22916465/944a08ba-f233-11e6-93d5-fda72e7b0a09.gif)
I think fixing the ease on the Y axis might fix the other issues

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
