### ISSUE TITLE
is there a way to remove ValueProvider

### ISSUE THREAD

**Issue by harryzjm** [airbnb/lottie-ios#920]
I had tried to AnimationView.reloadImages, but it doesn't work.

**Comment by harryzjm** [comment]
I have done this, let it all reload
animateV.animation = animateV.animation
so,  I close this issue.

**Comment by endy-s** [comment]
That doesn't work for me.
Any other tips?
This is my code to set the valueProvider:
```swift
        let keypath = AnimationKeypath(keypath: "**.Color")
        let colorValueProvider = ColorValueProvider(.red.lottieColorValue)
        animationView.setValueProvider(colorValueProvider, keypath: keypath)
```
