### ISSUE TITLE
Caching?!

### ISSUE THREAD

**Issue by devny** [airbnb/lottie-ios#922]
Hi. I have a question.
I wonder if the animations created at this time will be caching when I start with AnimationView (url: url, closure: closure).

**Comment by buba447** [comment]
It only caches if you pass in an animation cache to `AnimationView.loadedFrom(url: , closure:, animationCache:)`

Read more here: https://github.com/airbnb/lottie-ios#animation-cache

**Comment by RamblinWreck77** [comment]
@buba447 Are you saying something like:

```
let aView = AnimationView(name: "Example.json", animationCache: LRUAnimationCache.sharedCache)
```

Would not use the AnimationCache?

**Comment by buba447** [comment]
That would also use the animationCache.
