### ISSUE TITLE
Lottie Scaling Problem

### ISSUE THREAD

**Issue by wirnico** [airbnb/lottie-ios#924]
## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 
I have a view which can be dragged so that the header is getting shrinked. In the header I am using an AnimationView with Lottie 3.0

## Actual Behavior
Once I was on Lottie 2.5 the LottieView was shrinking immediately, but now since the update on 3.0 it lacks.
Is it a setting error I have made or is it a bug in Lottie 3.0?

## Code Example
I create a view in the Storyboard and give it the class AnimationView. Module is Lottie.
In the Swift File I wrote just this:
animationView.animation = Animation.named("analysis_saving")

## Animation JSON

I attached the Lottie File and also a scrrencapture
[Lottie Scaling Problem.zip](https://github.com/airbnb/lottie-ios/files/3232113/Lottie.Scaling.Problem.zip)

**Comment by buba447** [comment]
How are you changing the scale of the view?

**Comment by wirnico** [comment]
In the video I attached you can see a container in the header where the AnimationView is implemented. It has constraints to the top and bottom and no height or width. If the user swipes up the container gets compressed and with it the AnimationView.

**Comment by gregligierko** [comment]
// Perhaps related... I posted this a few days ago on StackOverflow. //

Title: 'How can I disable the content scale animation, when changing frame size?'

I am using Lottie 3.0 (Swift 4.2) mixed in an Objective-C project. I control the progress "manually":

       animationView.currentFrame = p

When I change the AnimationView instance's .frame (CGRect) in order to resize the view, then the the view moves instantly to the new position and size, but the contents/assets scale over time (maybe 0.2-0.5s) from the old to the final size. This scaling animation seems to have a linear progress.

I tried both with UIView.performWithoutAnimation and without it (I can see actions are disabled in Lottie's code anyway):

        UIView.performWithoutAnimation {
            animationView.frame = rect
        }
A note: the scaling animation progresses even when the animation itself is paused/stopped (in my case, also when I do not increase/cycle the animationView.currentFrame)

What I need are contents that instantly fit the updated AnimationView .frame/.bounds (CGRect).

**Comment by wirnico** [comment]
@gregligierko That's exactly the same behaviour we noticed.
@buba447 Maybe you can have a look at it again. Would be nice to have a smooth solution for this.
Thanks for all the work you put in this. Lottie is such a great framework.

**Comment by buba447** [comment]
I checked it out and something definitely doesnt look right! Ill look into it and let yall know. Hold tight.

**Comment by wirnico** [comment]
@buba447 Thanks, I am looking forward to.

**Comment by gregligierko** [comment]
Sounds great. 
I thought the issue may be around `layoutAnimation()` in `AnimationView.swift`, where I could see the new bound size becomes part of the `animationLayer.transform` but I could not resolve what happens next (I may be totally wrong about it).

**Comment by buba447** [comment]
@gregligierko  @wirnico  added a fix here https://github.com/airbnb/lottie-ios/pull/932

Please pull and verify.

**Comment by gregligierko** [comment]
Works now perfectly. Thanks a lot for the update. 

-

Completely unrelated - we were experimenting with drawing a Lottie into an OpenGL atlas texture (series of tiles as subsequent frames). It is a slow process when using drawViewHierarchyWithAnimationView:afterScreenUpdates: and only MAIN thread. Did you ever found a way to render Lottie animation content in a background thread?

I think an efficient method of exporting Lottie as a texture atlas could be interesting for 2D game developers/artist to create light weight sprites on runtime from JSON.

**Comment by juergenm** [comment]
I had the same issue, thank you for responding so quick, works great!

**Comment by wirnico** [comment]
@buba447 Thanks for all the hard work you put in it. Now everything works like a charm.

**Comment by kanisht1993** [comment]
use masanory in objective c to set lottie view top, bottom, left, right constraints to fit it in view.
