### ISSUE TITLE
Play to a point and then loop from there doesn't work

### ISSUE THREAD

**Issue by infiniteNIL** [airbnb/lottie-ios#928]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0.6

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 

Animation plays to a certain frame once and then loops from that frame to the end

## Actual Behavior

Animation plays to a certain frame and then stops.

## Code Example
```
// Play from zero to the start of the loop, then loop
animationContainerView.loopMode = .playOnce
animationContainerView.play(fromFrame: 0, toFrame: AnimationFrameTime(viewModel.animationLoopStartFrame)) { [weak self]  _ in
    self?.animationContainerView.loopMode = .loop
    self?.animationContainerView.play(fromFrame: AnimationFrameTime(viewModel.animationLoopStartFrame),
                                      toFrame: AnimationFrameTime(viewModel.animationLoopEndFrame))
}
```

animationContainerView is just a class that wraps Animation view and forwards calls. This worked with version 2.5

## Animation JSON

It should happen with any animation.

**Comment by infiniteNIL** [comment]
Github is not allowing me to upload a zip. Can I email it somewhere?

**Comment by ferico55** [comment]
@infiniteNIL  I checked this on version 3.1.0 and it works as expected
