### ISSUE TITLE
i find different effect with the same json between swift last version and oc version,how can i deal with it? thanks

### ISSUE THREAD

**Issue by zhmios** [airbnb/lottie-ios#929]
i find different effect with the same json between swift last version and oc version,how can i deal with it? thanks

**Comment by buba447** [comment]
In order to help I need more information. Mind sharing the animation and/or a description of whats not working?

**Comment by zhmios** [comment]
this is the json file.Different effect between swift last version and oc version
[animation.json.zip](https://github.com/airbnb/lottie-ios/files/3256713/animation.json.zip)

**Comment by zhmios** [comment]
this is content of json file with different effect between swift and oc lottie:    {"v":"5.4.2","fr":60,"ip":84,"op":129,"w":48,"h":48,"nm":"icon/tab/续班率normal","ddd":0,"assets":[],"layers":[{"ddd":0,"ind":1,"ty":4,"nm":"Path 8","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[20.869,27.535,0],"ix":2},"a":{"a":0,"k":[0,0,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"ef":[{"ty":5,"nm":"模式 - 合并路径 1 - Smoothness","np":3,"mn":"ADBE Slider Control","ix":1,"en":1,"ef":[{"ty":0,"nm":"滑块","mn":"ADBE Slider Control-0001","ix":1,"v":{"a":0,"k":4,"ix":1,"x":"var $bm_rt;\n$bm_rt = clamp(value, 0, 100);"}}]},{"ty":5,"nm":"模式 - 合并路径 1 - Blend Precision","np":3,"mn":"ADBE Slider Control","ix":2,"en":1,"ef":[{"ty":0,"nm":"滑块","mn":"ADBE Slider Control-0001","ix":1,"v":{"a":0,"k":25,"ix":1,"x":"var $bm_rt;\n$bm_rt = clamp(value, 0, 100);"}}]},{"ty":5,"nm":"模式 - 合并路径 1 - Blend On/Off","np":3,"mn":"ADBE Checkbox Control","ix":3,"en":1,"ef":[{"ty":7,"nm":"复选框","mn":"ADBE Checkbox Control-0001","ix":1,"v":{"a":0,"k":1,"ix":1}}]},{"ty":5,"nm":"开始 - 修剪路径 1 - Smoothness","np":3,"mn":"ADBE Slider Control","ix":4,"en":1,"ef":[{"ty":0,"nm":"滑块","mn":"ADBE Slider Control-0001","ix":1,"v":{"a":0,"k":4,"ix":1,"x":"var $bm_rt;\n$bm_rt = clamp(value, 0, 100);"}}]},{"ty":5,"nm":"开始 - 修剪路径 1 - Blend Precision","np":3,"mn":"ADBE Slider Control","ix":5,"en":1,"ef":[{"ty":0,"nm":"滑块","mn":"ADBE Slider Control-0001","ix":1,"v":{"a":0,"k":25,"ix":1,"x":"var $bm_rt;\n$bm_rt = clamp(value, 0, 100);"}}]},{"ty":5,"nm":"开始 - 修剪路径 1 - Blend On/Off","np":3,"mn":"ADBE Checkbox Control","ix":6,"en":1,"ef":[{"ty":7,"nm":"复选框","mn":"ADBE Checkbox Control-0001","ix":1,"v":{"a":0,"k":1,"ix":1}}]},{"ty":5,"nm":"结束 - 修剪路径 1 - Smoothness","np":3,"mn":"ADBE Slider Control","ix":7,"en":1,"ef":[{"ty":0,"nm":"滑块","mn":"ADBE Slider Control-0001","ix":1,"v":{"a":0,"k":4,"ix":1,"x":"var $bm_rt;\n$bm_rt = clamp(value, 0, 100);"}}]},{"ty":5,"nm":"结束 - 修剪路径 1 - Blend Precision","np":3,"mn":"ADBE Slider Control","ix":8,"en":1,"ef":[{"ty":0,"nm":"滑块","mn":"ADBE Slider Control-0001","ix":1,"v":{"a":0,"k":25,"ix":1,"x":"var $bm_rt;\n$bm_rt = clamp(value, 0, 100);"}}]},{"ty":5,"nm":"结束 - 修剪路径 1 - Blend On/Off","np":3,"mn":"ADBE Checkbox Control","ix":9,"en":1,"ef":[{"ty":7,"nm":"复选框","mn":"ADBE Checkbox Control-0001","ix":1,"v":{"a":0,"k":1,"ix":1}}]}],"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0]],"v":[[15.129,-6.323],[4.329,4.137],[-3.521,-4.023],[-15.131,6.327]],"c":false},"ix":2},"nm":"路径 1","mn":"ADBE Vector Shape - Group","hd":false},{"ind":1,"ty":"sh","ix":2,"ks":{"a":0,"k":{"i":[[0,0],[-7.96,0],[0,11.6],[11.6,0],[0,-11.6],[-0.08,-0.74]],"o":[[3.57,6.53],[11.6,0],[0,-11.6],[-11.6,0],[0,0.76],[0,0]],"v":[[-15.319,6.515],[3.131,17.475],[24.131,-3.525],[3.131,-24.525],[-17.869,-3.525],[-17.749,-1.275]],"c":false},"ix":2},"nm":"路径 2","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"st","c":{"a":0,"k":[0.301960796118,0.364705890417,0.458823531866,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":4,"ix":5},"lc":2,"lj":2,"nm":"描边 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"Path 5","np":3,"cix":2,"ix":1,"mn":"ADBE Vector Group","hd":false},{"ty":"mm","mm":1,"nm":"合并路径 1","mn":"ADBE Vector Filter - Merge","hd":false},{"ty":"tm","s":{"a":1,"k":[{"i":{"x":[0.46],"y":[1]},"o":{"x":[0.001],"y":[0.56]},"n":["0p46_1_0p001_0p56"],"t":94,"s":[100],"e":[0]},{"t":124}],"ix":1,"x":"var $bm_rt;\nvar range, samples, on_off;\nrange = div(effect('\\u5f00\\u59cb - \\u4fee\\u526a\\u8def\\u5f84 1 - Smoothness')('ADBE Slider Control-0001'), 20);\nsamples = div(effect('\\u5f00\\u59cb - \\u4fee\\u526a\\u8def\\u5f84 1 - Blend Precision')('ADBE Slider Control-0001'), 2);\n$bm_rt = on_off = effect('\\u5f00\\u59cb - \\u4fee\\u526a\\u8def\\u5f84 1 - Blend On/Off')('ADBE Checkbox Control-0001');\nif (on_off == 1) {\n    try {\n        $bm_rt = smooth(range, samples);\n    } catch (e$$4) {\n        $bm_rt = smooth(1, 1);\n    }\n} else {\n    $bm_rt = value = value;\n}"},"e":{"a":0,"k":100,"ix":2,"x":"var $bm_rt;\nvar range, samples, on_off;\nrange = div(effect('\\u7ed3\\u675f - \\u4fee\\u526a\\u8def\\u5f84 1 - Smoothness')('ADBE Slider Control-0001'), 20);\nsamples = div(effect('\\u7ed3\\u675f - \\u4fee\\u526a\\u8def\\u5f84 1 - Blend Precision')('ADBE Slider Control-0001'), 2);\n$bm_rt = on_off = effect('\\u7ed3\\u675f - \\u4fee\\u526a\\u8def\\u5f84 1 - Blend On/Off')('ADBE Checkbox Control-0001');\nif (on_off == 1) {\n    try {\n        $bm_rt = smooth(range, samples);\n    } catch (e$$4) {\n        $bm_rt = smooth(1, 1);\n    }\n} else {\n    $bm_rt = value = value;\n}"},"o":{"a":0,"k":0,"ix":3},"m":2,"ix":3,"nm":"修剪路径 1","mn":"ADBE Vector Filter - Trim","hd":false},{"ty":"st","c":{"a":0,"k":[0.301960796118,0.364705890417,0.458823531866,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":4,"ix":5},"lc":2,"lj":2,"nm":"描边 1","mn":"ADBE Vector Graphic - Stroke","hd":false}],"ip":0,"op":3684,"st":84,"bm":0},{"ddd":0,"ind":2,"ty":4,"nm":"Path 7","sr":1,"ks":{"o":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":123,"s":[100],"e":[0]},{"t":124}],"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[20.869,27.535,0],"ix":2},"a":{"a":0,"k":[0,0,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"ef":[{"ty":5,"nm":"开始 - 修剪路径 1 - Smoothness","np":3,"mn":"ADBE Slider Control","ix":1,"en":1,"ef":[{"ty":0,"nm":"滑块","mn":"ADBE Slider Control-0001","ix":1,"v":{"a":0,"k":4,"ix":1,"x":"var $bm_rt;\n$bm_rt = clamp(value, 0, 100);"}}]},{"ty":5,"nm":"开始 - 修剪路径 1 - Blend Precision","np":3,"mn":"ADBE Slider Control","ix":2,"en":1,"ef":[{"ty":0,"nm":"滑块","mn":"ADBE Slider Control-0001","ix":1,"v":{"a":0,"k":25,"ix":1,"x":"var $bm_rt;\n$bm_rt = clamp(value, 0, 100);"}}]},{"ty":5,"nm":"开始 - 修剪路径 1 - Blend On/Off","np":3,"mn":"ADBE Checkbox Control","ix":3,"en":1,"ef":[{"ty":7,"nm":"复选框","mn":"ADBE Checkbox Control-0001","ix":1,"v":{"a":0,"k":1,"ix":1}}]},{"ty":5,"nm":"结束 - 修剪路径 1 - Smoothness","np":3,"mn":"ADBE Slider Control","ix":4,"en":1,"ef":[{"ty":0,"nm":"滑块","mn":"ADBE Slider Control-0001","ix":1,"v":{"a":0,"k":4,"ix":1,"x":"var $bm_rt;\n$bm_rt = clamp(value, 0, 100);"}}]},{"ty":5,"nm":"结束 - 修剪路径 1 - Blend Precision","np":3,"mn":"ADBE Slider Control","ix":5,"en":1,"ef":[{"ty":0,"nm":"滑块","mn":"ADBE Slider Control-0001","ix":1,"v":{"a":0,"k":25,"ix":1,"x":"var $bm_rt;\n$bm_rt = clamp(value, 0, 100);"}}]},{"ty":5,"nm":"结束 - 修剪路径 1 - Blend On/Off","np":3,"mn":"ADBE Checkbox Control","ix":6,"en":1,"ef":[{"ty":7,"nm":"复选框","mn":"ADBE Checkbox Control-0001","ix":1,"v":{"a":0,"k":1,"ix":1}}]}],"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0]],"v":[[15.129,-6.323],[4.329,4.137],[-3.521,-4.023],[-15.131,6.327]],"c":false},"ix":2},"nm":"路径 1","mn":"ADBE Vector Shape - Group","hd":false},{"ind":1,"ty":"sh","ix":2,"ks":{"a":0,"k":{"i":[[0,0],[-7.96,0],[0,11.6],[11.6,0],[0,-11.6],[-0.08,-0.74]],"o":[[3.57,6.53],[11.6,0],[0,-11.6],[-11.6,0],[0,0.76],[0,0]],"v":[[-15.319,6.515],[3.131,17.475],[24.131,-3.525],[3.131,-24.525],[-17.869,-3.525],[-17.749,-1.275]],"c":false},"ix":2},"nm":"路径 2","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"st","c":{"a":0,"k":[1,0.333333343267,0.188235297799,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":4,"ix":5},"lc":2,"lj":2,"nm":"描边 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"Path 5","np":3,"cix":2,"ix":1,"mn":"ADBE Vector Group","hd":false},{"ty":"mm","mm":1,"nm":"合并路径 1","mn":"ADBE Vector Filter - Merge","hd":false},{"ty":"tm","s":{"a":1,"k":[{"i":{"x":[0.46],"y":[1]},"o":{"x":[0.001],"y":[0.56]},"n":["0p46_1_0p001_0p56"],"t":92,"s":[100],"e":[0]},{"t":122}],"ix":1,"x":"var $bm_rt;\nvar range, samples, on_off;\nrange = div(effect('\\u5f00\\u59cb - \\u4fee\\u526a\\u8def\\u5f84 1 - Smoothness')('ADBE Slider Control-0001'), 20);\nsamples = div(effect('\\u5f00\\u59cb - \\u4fee\\u526a\\u8def\\u5f84 1 - Blend Precision')('ADBE Slider Control-0001'), 2);\n$bm_rt = on_off = effect('\\u5f00\\u59cb - \\u4fee\\u526a\\u8def\\u5f84 1 - Blend On/Off')('ADBE Checkbox Control-0001');\nif (on_off == 1) {\n    try {\n        $bm_rt = smooth(range, samples);\n    } catch (e$$4) {\n        $bm_rt = smooth(1, 1);\n    }\n} else {\n    $bm_rt = value = value;\n}"},"e":{"a":0,"k":100,"ix":2,"x":"var $bm_rt;\nvar range, samples, on_off;\nrange = div(effect('\\u7ed3\\u675f - \\u4fee\\u526a\\u8def\\u5f84 1 - Smoothness')('ADBE Slider Control-0001'), 20);\nsamples = div(effect('\\u7ed3\\u675f - \\u4fee\\u526a\\u8def\\u5f84 1 - Blend Precision')('ADBE Slider Control-0001'), 2);\n$bm_rt = on_off = effect('\\u7ed3\\u675f - \\u4fee\\u526a\\u8def\\u5f84 1 - Blend On/Off')('ADBE Checkbox Control-0001');\nif (on_off == 1) {\n    try {\n        $bm_rt = smooth(range, samples);\n    } catch (e$$4) {\n        $bm_rt = smooth(1, 1);\n    }\n} else {\n    $bm_rt = value = value;\n}"},"o":{"a":0,"k":0,"ix":3},"m":2,"ix":3,"nm":"修剪路径 1","mn":"ADBE Vector Filter - Trim","hd":false},{"ty":"st","c":{"a":0,"k":[1,0.333333343267,0.188235297799,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":4,"ix":5},"lc":2,"lj":2,"nm":"描边 1","mn":"ADBE Vector Graphic - Stroke","hd":false}],"ip":0,"op":3684,"st":84,"bm":0},{"ddd":0,"ind":3,"ty":4,"nm":"Path 5","sr":1,"ks":{"o":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":121,"s":[100],"e":[1]},{"t":122}],"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[20.869,27.535,0],"ix":2},"a":{"a":0,"k":[0,0,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"ef":[{"ty":5,"nm":"开始 - 修剪路径 1 - Smoothness","np":3,"mn":"ADBE Slider Control","ix":1,"en":1,"ef":[{"ty":0,"nm":"滑块","mn":"ADBE Slider Control-0001","ix":1,"v":{"a":0,"k":4,"ix":1,"x":"var $bm_rt;\n$bm_rt = clamp(value, 0, 100);"}}]},{"ty":5,"nm":"开始 - 修剪路径 1 - Blend Precision","np":3,"mn":"ADBE Slider Control","ix":2,"en":1,"ef":[{"ty":0,"nm":"滑块","mn":"ADBE Slider Control-0001","ix":1,"v":{"a":0,"k":25,"ix":1,"x":"var $bm_rt;\n$bm_rt = clamp(value, 0, 100);"}}]},{"ty":5,"nm":"开始 - 修剪路径 1 - Blend On/Off","np":3,"mn":"ADBE Checkbox Control","ix":3,"en":1,"ef":[{"ty":7,"nm":"复选框","mn":"ADBE Checkbox Control-0001","ix":1,"v":{"a":0,"k":1,"ix":1}}]},{"ty":5,"nm":"结束 - 修剪路径 1 - Smoothness","np":3,"mn":"ADBE Slider Control","ix":4,"en":1,"ef":[{"ty":0,"nm":"滑块","mn":"ADBE Slider Control-0001","ix":1,"v":{"a":0,"k":4,"ix":1,"x":"var $bm_rt;\n$bm_rt = clamp(value, 0, 100);"}}]},{"ty":5,"nm":"结束 - 修剪路径 1 - Blend Precision","np":3,"mn":"ADBE Slider Control","ix":5,"en":1,"ef":[{"ty":0,"nm":"滑块","mn":"ADBE Slider Control-0001","ix":1,"v":{"a":0,"k":25,"ix":1,"x":"var $bm_rt;\n$bm_rt = clamp(value, 0, 100);"}}]},{"ty":5,"nm":"结束 - 修剪路径 1 - Blend On/Off","np":3,"mn":"ADBE Checkbox Control","ix":6,"en":1,"ef":[{"ty":7,"nm":"复选框","mn":"ADBE Checkbox Control-0001","ix":1,"v":{"a":0,"k":1,"ix":1}}]}],"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0]],"v":[[15.129,-6.323],[4.329,4.137],[-3.521,-4.023],[-15.131,6.327]],"c":false},"ix":2},"nm":"路径 1","mn":"ADBE Vector Shape - Group","hd":false},{"ind":1,"ty":"sh","ix":2,"ks":{"a":0,"k":{"i":[[0,0],[-7.96,0],[0,11.6],[11.6,0],[0,-11.6],[-0.08,-0.74]],"o":[[3.57,6.53],[11.6,0],[0,-11.6],[-11.6,0],[0,0.76],[0,0]],"v":[[-15.319,6.515],[3.131,17.475],[24.131,-3.525],[3.131,-24.525],[-17.869,-3.525],[-17.749,-1.275]],"c":false},"ix":2},"nm":"路径 2","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"st","c":{"a":0,"k":[0,0.752941191196,0.768627464771,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":4,"ix":5},"lc":2,"lj":2,"nm":"描边 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"Path 5","np":3,"cix":2,"ix":1,"mn":"ADBE Vector Group","hd":false},{"ty":"mm","mm":1,"nm":"合并路径 1","mn":"ADBE Vector Filter - Merge","hd":false},{"ty":"tm","s":{"a":1,"k":[{"i":{"x":[0.46],"y":[1]},"o":{"x":[0.001],"y":[0.56]},"n":["0p46_1_0p001_0p56"],"t":90,"s":[100],"e":[0]},{"t":120}],"ix":1,"x":"var $bm_rt;\nvar range, samples, on_off;\nrange = div(effect('\\u5f00\\u59cb - \\u4fee\\u526a\\u8def\\u5f84 1 - Smoothness')('ADBE Slider Control-0001'), 20);\nsamples = div(effect('\\u5f00\\u59cb - \\u4fee\\u526a\\u8def\\u5f84 1 - Blend Precision')('ADBE Slider Control-0001'), 2);\n$bm_rt = on_off = effect('\\u5f00\\u59cb - \\u4fee\\u526a\\u8def\\u5f84 1 - Blend On/Off')('ADBE Checkbox Control-0001');\nif (on_off == 1) {\n    try {\n        $bm_rt = smooth(range, samples);\n    } catch (e$$4) {\n        $bm_rt = smooth(1, 1);\n    }\n} else {\n    $bm_rt = value = value;\n}"},"e":{"a":0,"k":100,"ix":2,"x":"var $bm_rt;\nvar range, samples, on_off;\nrange = div(effect('\\u7ed3\\u675f - \\u4fee\\u526a\\u8def\\u5f84 1 - Smoothness')('ADBE Slider Control-0001'), 20);\nsamples = div(effect('\\u7ed3\\u675f - \\u4fee\\u526a\\u8def\\u5f84 1 - Blend Precision')('ADBE Slider Control-0001'), 2);\n$bm_rt = on_off = effect('\\u7ed3\\u675f - \\u4fee\\u526a\\u8def\\u5f84 1 - Blend On/Off')('ADBE Checkbox Control-0001');\nif (on_off == 1) {\n    try {\n        $bm_rt = smooth(range, samples);\n    } catch (e$$4) {\n        $bm_rt = smooth(1, 1);\n    }\n} else {\n    $bm_rt = value = value;\n}"},"o":{"a":0,"k":0,"ix":3},"m":2,"ix":3,"nm":"修剪路径 1","mn":"ADBE Vector Filter - Trim","hd":false},{"ty":"st","c":{"a":0,"k":[0,0.752941191196,0.768627464771,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":4,"ix":5},"lc":2,"lj":2,"nm":"描边 1","mn":"ADBE Vector Graphic - Stroke","hd":false}],"ip":0,"op":3684,"st":84,"bm":0},{"ddd":0,"ind":4,"ty":4,"nm":"Path 6","sr":1,"ks":{"o":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":119,"s":[100],"e":[0]},{"t":120}],"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[20.869,27.535,0],"ix":2},"a":{"a":0,"k":[0,0,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0]],"v":[[-15.131,6.327],[-3.521,-4.023],[4.329,4.137],[15.129,-6.323]],"c":false},"ix":2},"nm":"路径 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"st","c":{"a":0,"k":[0.77254897356,0.77254897356,0.77254897356,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":4,"ix":5},"lc":2,"lj":2,"nm":"描边 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"Path 5","np":2,"cix":2,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":3684,"st":84,"bm":0},{"ddd":0,"ind":5,"ty":4,"nm":"Oval","sr":1,"ks":{"o":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":119,"s":[100],"e":[0]},{"t":120}],"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[24,24,0],"ix":2},"a":{"a":0,"k":[0,0,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[-7.96,0],[0,11.6],[11.6,0],[0,-11.6],[-0.08,-0.74]],"o":[[3.57,6.53],[11.6,0],[0,-11.6],[-11.6,0],[0,0.76],[0,0]],"v":[[-18.45,10.04],[0,21],[21,0],[0,-21],[-21,0],[-20.88,2.25]],"c":false},"ix":2},"nm":"路径 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"st","c":{"a":0,"k":[0.77254897356,0.77254897356,0.77254897356,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":4,"ix":5},"lc":2,"lj":2,"nm":"描边 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"Oval","np":2,"cix":2,"ix":1,"mn":"ADBE Vector Group","hd":false},{"ty":"tm","s":{"a":0,"k":0,"ix":1},"e":{"a":0,"k":100,"ix":2},"o":{"a":0,"k":0,"ix":3},"m":1,"ix":2,"nm":"修剪路径 1","mn":"ADBE Vector Filter - Trim","hd":false}],"ip":0,"op":3684,"st":84,"bm":0}],"markers":[]}

**Comment by calda** [comment]
Could you share more details about your issue? Testing on master, the animation looks the same as it does when I preview it on lottiefiles.com
