### ISSUE TITLE
3.0.6 > 3.0.7 (and 3.1.0) bug involving looping animations initialized off screen that then appear.

### ISSUE THREAD

**Issue by RamblinWreck77** [airbnb/lottie-ios#930]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0.7, 3.1.0 (bug showed up in 3.0.7). 3.0.6 is not effected.

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 
Animations to loop properly inside collection view cells

## Actual Behavior
Situation:
-Top level is a tab bar/page view controller (PageBoy controller w/swipe)
-Pages load in like so: [0,1,2,3], and if you're on page 1 pages 0 and 2 are loaded in next to it because you can swipe. This is important.
-The issue page has a collection view, 2x6 grid of cells. Inside each cell is a playing lottie animation set to loop.
-As you swipe on to the target page, mid-swipe in the animations play (and will loop indefinitely). As soon as you let go/land on the page (and viewDidAppear triggers on the parent VC), the loop stops and the animation will not restart.
-No reload data happens on the collection view/change occurs inside the cell viewDidLayout, or the view controller for the collection view (besides viewDidAppear, which does nothing). 
-This does not happen in 3.0.6, and does in 3.0.7

## Animation JSON
I'm 99.9% sure the animation is not the issue, as it runs perfectly on several different pages throughout the app, including w/same loop mode and speed/scaling. My hunch is that somehow a looping animation that gets started off-screen is breaking on viewDidAppear.

## Reproducibility
100%. Downgrading to 3.0.6 fixes it, 3.0.7/3.1.0 breaks it. I can try and get a video tomorrow

**Comment by buba447** [comment]
try setting `animation.backgroundBehavior = .pauseAndRestore`

**Comment by RamblinWreck77** [comment]
That fixed it! Thanks!

**Comment by zenghaojim33** [comment]
`animation.backgroundBehavior = .pauseAndRestore` does not solve my problem, while switching tabs between view controllers the animation still freeze.
