### ISSUE TITLE
Cannot restart animation after updating its `currentProgress` value

### ISSUE THREAD

**Issue by bertrandprenat** [airbnb/lottie-ios#931]
## Which Version of Lottie are you using?
Lottie 3.1.0

## What Platform are you on? 
iOS

## What Language are you in?
Swift

## Expected Behavior
The animation should restart and be played with `newValue` as `currentProgress` each time `updateAnimation(withProgress:)` is called.

## Actual Behavior
The animation is played entirely.

## Code Example
```
func updateAnimation(withProgress progress:  AnimationProgressTime) {
    animationView.stop()
    animationView.currentProgress = 0.0
    animationView.play(fromProgress: 0.0, toProgress: progress, loopMode: .playOnce, completion: { (hasFinished) in
        debugPrint(hasFinished)
    })
}
```

## Animation JSON
[Progress.json.zip](https://github.com/airbnb/lottie-ios/files/3242510/Progress.json.zip)

**Comment by ErickApps** [comment]
has this been solved?
