### ISSUE TITLE
Animation loading but not playing

### ISSUE THREAD

**Issue by Namuerse** [airbnb/lottie-ios#936]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.0

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x

] Swift
- [] Objective-C

## Code Example

```

override func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "cardView", for: indexPath) as! CardPlayScreen


       //just FYI cardType variable is defined, I didn't include the full code here
        cell.cardBackground?.animation = Animation.named(cardType+"_xl")
        cell.cardBackground?.play()
        cell.cardBackground?.addGestureRecognizer(swipeLeftGesture!)
        cell.cardBackground?.addGestureRecognizer(swipeRightGesture!)

        return cell
    }
```
## Animation JSON
Emailed you the JSON Files!

The animations are loading and displaying fine although they are not playing. AnimationView.animation is not nil and the AnimationView.isAnimationPlaying is always false. The animation all use gradient stroke animation where the stroke changes position over time but this does not seem to play.

Let me know if you need any more info

**Comment by ferico55** [comment]
I would like to help on this, can you provide the animation json via a link here?

**Comment by Namuerse** [comment]
Thanks ferrico, link is below

https://we.tl/t-fqVEUCHBDD

**Comment by ferico55** [comment]
@Namuerse I am terribly sorry, I didn't check back on this and looks like your we transfer link has been invalidated :( would you please email the json to me?

**Comment by Namuerse** [comment]
@ferico55 I've emailed you it
