### ISSUE TITLE
Trim path animation is not working when masked out of other shape with Alpha Matte

### ISSUE THREAD

**Issue by analoguee** [airbnb/lottie-ios#940]
I have a trim path animation that is masked out of another shape using alpha matte. When uploaded to Lottie preview, the trim path motion doesn't seem to happen at all, and there is some strange distortion and movement happening inside the mask, which wasn't part of the After Effects file.

I have used trim paths inside of masks before, and they've worked fine. Something about this setup, though, leads to this strange distortion. 

Expected Behavior:
![Expected-Behavior-2](https://user-images.githubusercontent.com/51487654/59118611-6db60d00-8905-11e9-8153-6488637fadb2.gif)

Lottie Preview:
![Actual-Behavior](https://user-images.githubusercontent.com/51487654/59118522-3e9f9b80-8905-11e9-9434-3d0f31764ed5.gif)

**Comment by calda** [comment]
Can you share a copy of your Lottie animation json?
