### ISSUE TITLE
Animation loading but not playing

### ISSUE THREAD

**Issue by YayongLi** [airbnb/lottie-ios#941]
## Check these before submitting:
- [ ] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [ ] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0.6

## What Platform are you on? 

- [ ] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [ ] Objective-C

**Comment by buba447** [comment]
Can you please provide some more context? What is the animation? How are you playing the animation? Without context Im afraid I cannot help you debug the situation.
