### ISSUE TITLE
Timeline for supporting dynamic text

### ISSUE THREAD

**Issue by sadiq81** [airbnb/lottie-ios#942]
Is there a timeline for implementing support for dynamically changing text?

**Comment by buba447** [comment]
It has been added in the latest version. Cheers!

**Comment by sadiq81** [comment]
Could you point me to some documentation or somewhere in the code where I can see how to use it.

**Comment by buba447** [comment]
Theres no documentation yet, but the PR that added the support is here
https://github.com/airbnb/lottie-ios/pull/938

>

**Comment by arvindkumar-gr** [comment]
Post some code on how to change text dynamically. Been trying this for 2 days.

**Comment by khawajafarooq** [comment]
I am also trying to figure out but no luck. It would be great help if you post some example.

**Comment by Heidan34** [comment]
@khawajafarooq A little late but I've had the same issue. Turns out you need to set the textProvider BEFORE setting the animation into your animationView. Works fine when you do it that way.

**Comment by khawajafarooq** [comment]
@Heidan34 thanks for sharing. Mine was fixing in the Lottie file.

**Comment by turk-jk** [comment]
> @Heidan34 thanks for sharing. Mine was fixing in the Lottie file.

what was the issue in the Lottie file ?

**Comment by InfiniteFalltrough** [comment]
> It would be great help if you could post some example. I am using `DictionaryTextProvider` but no luck: `animationView.textProvider = DictionaryTextProvider(["**.Amount": "10 kr."])`

sane issue here, Lottie 4.4.2


`    
func makeUIView(context: Context) -> UIView {
        let animation = LottieAnimation.named(animationName)
        var animationView = LottieAnimationView()
        let textProvider = DictionaryTextProvider(["123": "321"]) // "123" - from .logHierarchyKeypaths()

        animationView.configuration.renderingEngine = renderingEngine
        animationView.textProvider = textProvider
        animationView.animation = animation

        return animationView
    }
`
