### ISSUE TITLE
Animation not looping properly on iOS but is OK on web & Android

### ISSUE THREAD

**Issue by jgodon** [airbnb/lottie-ios#943]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)

## Which Version of Lottie are you using?
- Lottie 3.1.0
- The json file is generated from **Bodymovin v5.5.5**

## What Platform are you on? 
- [x] iOS

## What Language are you in?
- [x] Swift

## Expected Behavior 
When looping, animation should loop softly, with no _jump_ between the end of the animation and its restart. 
You can see it working nicely by opening `demo.html` file including in zip file [testexportblabla.zip](https://github.com/airbnb/lottie-ios/files/3285850/testexportblabla.zip)

## Actual Behavior
It seems to me that a small part of the animation is missing at the end of the loop, making it stoping during a small time and create a feeling of a jump...
See `flamantKO.mov` ziped in [flamantKO.mov.zip](https://github.com/airbnb/lottie-ios/files/3285892/flamantKO.mov.zip) for details

The fact is that the same JSON works nicely on the web and on Android platform...

## Animation JSON
You'll find in ZIP file [testexportblabla.zip](https://github.com/airbnb/lottie-ios/files/3285850/testexportblabla.zip) the JSON animation itself: `flamant.json` and a `demo.html` to see it working nicely on Safari.

Best regards

Jeremie

**Comment by karimElJed** [comment]
Any progress on this? I am facing the same issue.

**Comment by hawk-garethf** [comment]
As am I, is there a fix?

**Comment by calda** [comment]
The attached animation appears to play correctly when I test it in Lottie 4.0
