### ISSUE TITLE
Images from Assets.xcassets are not loading

### ISSUE THREAD

**Issue by adrgrondin** [airbnb/lottie-ios#944]
## This issue is a:
- Regression

## Which Version of Lottie are you using?
Lottie 3.1.0

## What Platform are you on? 
- iOS 12.3.1

## What Language are you in?
- Swift

## Expected Behavior 
Using JSON animations exported by Bodymovin and using assets, if these assets are in Assets.xcassets (Xcode) as image set, the animations should have the images (in the corresponding size @2x or @3x).

## Actual Behavior
Using JSON animations exported by Bodymovin the images in Assets.xcassets are not loading (only svg parts visible).
 Before Lottie 3.0 putting the images in Assets.xcassets was working.

## Code Example

```swift
let animationView = AnimationView(name: myAnimation)
animationView.loopMode = .loop
animationView.translatesAutoresizingMaskIntoConstraints = false
addSubview(animationView)
self.animationView = animationView
self.animationView.play()
```

## Animation JSON

You just need an animation exported with Bodymovin with a .png image.

**Comment by zxy1829760** [comment]
Yes

**Comment by mobilejin** [comment]
Has the same issue

**Comment by idoNaveh** [comment]
I had the same problem, I manage to solve it by using AnimationImageProvider.

e.g.
`extension ViewController: AnimationImageProvider {
    
    func imageForAsset(asset: ImageAsset) -> CGImage? {
        return UIImage(named: asset.name)?.cgImage
    }
}`

And you will need set the imageProvider in your AnimationView

**Comment by abhishekkr99** [comment]
`public class CustomBundleImageProvider: AnimationImageProvider {
  let bundle: Bundle
  let searchPath: String?
  
  public init(bundle: Bundle, searchPath: String?) {
    self.bundle = bundle
    self.searchPath = searchPath
  }
  
  public func imageForAsset(asset: ImageAsset) -> CGImage? {
    if asset.name.hasPrefix("data:"),
      let url = URL(string: asset.name),
      let data = try? Data(contentsOf: url),
      let image = UIImage(data: data) {
        return UIImage(named: "image_0")?.cgImage
    }
    
    let image1 =  UIImage(named: "image 15")
    return image1?.cgImage
  }
}
` 
image 15 - this image is present in assets.xcassets

trying to return this image when "data:" not present but this image is not displayed
