### ISSUE TITLE
Animation not scaling properly on Obj

### ISSUE THREAD

**Issue by BoogieMAN2K** [airbnb/lottie-ios#945]
## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [X] iOS

## What Language are you in?
- [] Swift
- [X] Objective-C

## Expected Behavior 
The animation should be able to adapt to the size of the desired View.

## Actual Behavior
The animation gets cropped inside the selected View with no way of moving it.

## Code Example

CompatibleAnimationView *animationView = [[CompatibleAnimationView alloc] init];
CompatibleAnimation *animation = [[CompatibleAnimation alloc] initWithName:@"lf20_0AZMnD" bundle:[NSBundle mainBundle]];
[animationView setContentMode: UIViewContentModeScaleAspectFill];
[animationView setContentScaleFactor: 0.1];
[animationView setCompatibleAnimation: animation];
[animationView setLoopAnimationCount: -1];
[animationView play];

[[self logoImage] addSubview:animationView];
[[self logoImage] setBackgroundColor:[UIColor blueColor]];

## Animation JSON
Added the animation as a zip file
[SpecdrumPluginAnimation_Cropped.json.zip](https://github.com/airbnb/lottie-ios/files/3292048/SpecdrumPluginAnimation_Cropped.json.zip)

**Comment by buba447** [comment]
Set contentMode to `UIViewContentModeScaleAspectFit`

Should fix ya up! Cheers.

**Comment by YuDiyi** [comment]
Hello, I have encountered the same problem now. How did you solve it?
