### ISSUE TITLE
Partial animation

### ISSUE THREAD

**Issue by GusevAndrey** [airbnb/lottie-ios#95]
Hi,

Is there any way to play just a part of animation: stop at given progress, play from A progress to B progress or so?

e.g. for HumburgerArrow play just the first half of it after tap and menu opened and then (after second tap) play the rest of it.

**Comment by buba447** [comment]
Hey @GusevAndrey 
This has been requested before and we are trying to come up with a good way to do it :) 

Duplicate here:
https://github.com/airbnb/lottie-ios/issues/52

**Comment by GusevAndrey** [comment]
Thx! Look forward to see it soon)
