### ISSUE TITLE
Animation is not playing when entering foreground then popping viewcontroller 

### ISSUE THREAD

**Issue by rosskrasner** [airbnb/lottie-ios#950]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 
Animation plays and then continues to play, even if a user leaves the app then come back/ pops view controller to see the animation

## Actual Behavior
If a user leaves the app and pops a view controller to a view controller with the animation, the animation is paused.

## Code Example
```
    override func viewDidLoad() {
        super.viewDidLoad()
            animationView = AnimationView(name: lottieAnimationName)
            animationView.frame = view.frame
            animationView.contentMode = .scaleAspectFill
            animationView.animationSpeed = lottieSpeed
            
            view.addSubview(animationView)

    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)

            NotificationCenter.default.addObserver(
                self,
                selector:#selector(self.play),
                name: UIApplication.willEnterForegroundNotification,
                object: nil)
            NotificationCenter.default.addObserver(
                self,
                selector:#selector(self.play),
                name: UIApplication.didBecomeActiveNotification,
                object: nil)
            play()
       
    }

    @objc func play() {
        DispatchQueue.main.async {
            self.animationView.play(completion: { _ in
                DispatchQueue.main.async {
                    self.animationView.play(fromFrame: AnimationFrameTime(truncating: self.lottieStartFrame),
                                            toFrame: AnimationFrameTime(truncating: self.lottieEndFrame),
                                            loopMode: .loop,
                                            completion: nil)
                }
            })
        }
    }
```
## Animation JSON
[circlesAnimation.txt](https://github.com/airbnb/lottie-ios/files/3299725/circlesAnimation.txt)

**Comment by buba447** [comment]
Setting the backgroundBehavior is the proper way to play/pause with app background:

https://github.com/airbnb/lottie-ios/blob/master/README.md#background-behavior
