### ISSUE TITLE
Time remapping not working on iOS / Android

### ISSUE THREAD

**Issue by kerumo2** [airbnb/lottie-ios#951]
Hi, I recently made an animation which has many shorter looping animations inside the main timeline in After effects, using the time remapping feature with the loopout function.

It works on the lottie web, but for iOS / Android those animations that has the LoopOut time remapping code does not repeat...

I saw that the time remap is supported in version 3.0, and the iOS/android has updated to that version but still not working.

**Comment by buba447** [comment]
Can you give me some more specifics about whats not working? Do you mind sharing the animation?

**Comment by kerumo2** [comment]
Hey,
I have an animation that's 2 seconds long. Inside this 2 second animation I have multiple shorter pre composed animations which run for about 0.5 seconds and they repeat over and over again.

To repeat the animations, I used The Time remap function and added an expression **loopOut(type = "cycle", numKeyframes = 0)**  to loop the animations.

You will see in the animation below that it stops half way then starts again.

This animation works on the WEB version of lottie but it does not work on iOS or Android and the developers recently updated to 3.0 which didn't fix the issue.

https://www.dropbox.com/s/40ed8a5vg04kdb2/animation.zip?dl=0

**Comment by buba447** [comment]
I checked out your animation and I see you are using expressions to animated the time remapping. Expressions are not supported on ios or android. Sorry!
