### ISSUE TITLE
Animation is played with a small copy of itself in background 

### ISSUE THREAD

**Issue by vasiliy-s** [airbnb/lottie-ios#954]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?
Though i use Xamarin forms the issue is not there for Android devices so i submit it here.
Com.Airbnb.Xamarin.Forms.Lottie 2.7.1

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [] Swift
- [] Objective-C

## Actual Behavior
Lottie perfectly plays my animation but at the same time it plays the smaller version of an animation in the background of the original one. It happens only on real iOs device (iPhone 8 plus in my case). In an emulator for the same device it works fine.

Can`t attach videos to the request so here is a link:
 - real device : https://yadi.sk/i/yYwjWcU2437zxg
 - emulator: https://yadi.sk/i/xaXG2cBeS7NtxA

## Code Example
<forms:AnimationView
  Animation="splash.json"
  Loop="false"
  AutoPlay="True"
  Margin="30, 0"/>

## Animation JSON
[splash.zip](https://github.com/airbnb/lottie-ios/files/3348914/splash.zip)

**Comment by ferico55** [comment]
can you provide the animation json?

**Comment by vasiliy-s** [comment]
> can you provide the animation json @vasiliy-s ?

I've updated the request @ferico55

**Comment by ferico55** [comment]
Hey @vasiliy-s , I saw an update for Xamarin Forms, they're releasing [3.0.0](https://www.nuget.org/packages/Com.Airbnb.Xamarin.Forms.Lottie/3.0.0)
I am not used to Xamarin by the way, but in the dependencies list, I saw `Com.Airbnb.iOS.Lottie (>= 2.5.8)`. Could this means we can use `lottie-ios` at version 2.5.8 or later? If it does, I suggest you upgrade the ios dependencies to the [latest (3.1.1)](https://github.com/airbnb/lottie-ios/tree/3.1.1). I've tested in the latest release and it is looking fine there
(running on iPhone 8, iOS 13.0, lottie-ios 3.1.1)[https://drive.google.com/file/d/1WZBu35t9B9c-8-sXvHW6oaxVin1P-h5G/view?usp=sharing]
