### ISSUE TITLE
Animating point via Nulls not working in iOS

### ISSUE THREAD

**Issue by dansmithingson** [airbnb/lottie-ios#957]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [] Swift
- [x] Objective-C

## Expected Behavior 
The attached JSON behaves correctly on OSX, Chrome, Lottie Preview

## Actual Behavior
When I view it on the iOS version of Lottie preview or in my app, the edges of my morphing shape don't move

## Animation JSON
[Unfold.json.zip](https://github.com/airbnb/lottie-ios/files/3311867/Unfold.json.zip)

**Comment by buba447** [comment]
This animation is using Expressions to set the animated point. Expressions are not supported by lottie-ios or android. 

You can try parenting, or baking the animation.
