### ISSUE TITLE
[Feature Request] Wide Gamut color space

### ISSUE THREAD

**Issue by cipolleschi** [airbnb/lottie-ios#958]
## Useful Data
**Lottie Version:** 3.1.0
**Platform:** iOS
**Language:** Swift

## Expected Behavior 
When an animation view is initialized, there should be a parameter that tells Lottie about which color space should be used so that we can render it in wide-gamut instead of sRGB.
(The iOS API is this one: https://developer.apple.com/documentation/uikit/uicolor/1648568-init)

## Actual Behavior
All the colors are interpreted in sRGB. It results in a less brilliant animation.

## Samples
The sRGB version (the current one)
![lottie_sRGB](https://user-images.githubusercontent.com/11162307/59937644-4dcd3000-9453-11e9-8f4a-2d4ad9cec4fb.gif)

the P3 version (with better colors)
![lottie_p3](https://user-images.githubusercontent.com/11162307/59937643-4dcd3000-9453-11e9-8ebc-57a625eb33a2.gif)

**Comment by alexisbronchart** [comment]
I gave a shot in https://github.com/airbnb/lottie-ios/pull/1857
Let me know what you think.

**Comment by calda** [comment]
Thanks for implementing this @alexisbronchart! Appreciate it.
