### ISSUE TITLE
Expose animationView property for AnimatedSwitch

### ISSUE THREAD

**Issue by ctreffs** [airbnb/lottie-ios#960]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [x] Feature Request
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.0

## What Platform are you on? 

- [ ] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [ ] Objective-C

## Expected Behavior 

Access `animationView` property to set the `.backgroundBehavior = .pauseAndRestore` to have switch animations finish even if the switch is not visible.

## Actual Behavior
`animationView`is not accessible due to internal protection level.

## Code Example

Current workaround:

```
class AnimatedSwitchSubclass: AnimatedSwitch {
lazy var animationView: AnimationView = {
        let view = subviews.lazy.compactMap { $0 as? AnimationView }.first ?? AnimationView()
        view.backgroundBehavior = .pauseAndRestore
        return view
    }()
}
```

**Comment by buba447** [comment]
Ive added a `forceFinish` background behavior and set it by default on `AnimatedControl`

This should fix your problem. Cheers!

https://github.com/airbnb/lottie-ios/pull/967
