### ISSUE TITLE
Lottie Preview: iOS & Android Bottom Layer Appearance Difference

### ISSUE THREAD

**Issue by yakushevichsv** [airbnb/lottie-ios#964]
## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)

## Which Version of Lottie are you using?
Lottie 3.1

## What Platform are you on? 

- [X] iOS

## What Language are you in?
- [X] Swift

## Expected Behavior 

[Lottie Web Preview](https://lottiefiles.com/share/DatPCE)

Correctly displayed by Lottie Preview on Android
![Correctly displayed by Lottie Preview on Android](https://user-images.githubusercontent.com/1941238/60397313-68d72880-9b54-11e9-83ad-bb4280b86a01.jpg)

## Actual Behavior

Wrongly displayed by Lottie on iOS
![Wrongly displayed by Lottie on iOS](https://user-images.githubusercontent.com/1941238/60397439-f6ffde80-9b55-11e9-9e0a-6d2a9f97792e.jpeg)

## Code Example
You can use official **Lottie Preview** app from the App Store.
In my similar preview scene I tried to change `UIView`'s `contentMode` property, but I can't make the same appearance as on Android & Web.
 
What is wrong? Why my bottom content is shrunk(compressed) on iOS? 
P.S. Pls see red shape on actual image... :)

## Animation JSON
[Actual JSON] (https://github.com/airbnb/lottie-ios/files/3348550/start_f2.json.zip)

**Comment by buba447** [comment]
Hello! I tried to debug your issue. The file you link does not have any json in it so it's hard to say what the issue is.

Have you set the `contentMode` to `.scaleAspectFill` ?

**Comment by yakushevichsv** [comment]
@buba447 Sorry, my fault. I've updated the archive.

**Comment by yakushevichsv** [comment]
@buba447 pls try - check :)

**Comment by buba447** [comment]
I took a look on my end and didnt see anything out of the ordinary. 
I did a test with a full screen animation. Setting the `contentMode` seemed to fix the problem on my end. Be sure that you are on the latest version of Lottie. Check out the screenshots below.

`contentMode = .scaleAspectFit`
<img width="758" alt="Screen Shot 2019-07-11 at 8 40 53 AM" src="https://user-images.githubusercontent.com/1163980/61055776-d3d7f900-a3b7-11e9-8816-c0fc2a077ce4.png">

`contentMode = .scaleAspectFill`
<img width="752" alt="Screen Shot 2019-07-11 at 8 40 31 AM" src="https://user-images.githubusercontent.com/1163980/61055798-dd616100-a3b7-11e9-82e1-0f26692f0b6b.png">


If you still have a problem then perhaps you could set set up some code that reproduces the issue in a new project. Id be happy to help debug the problem from there.

Cheers!

**Comment by yakushevichsv** [comment]
@buba447 Thank you, you're absolutely right. 
However, I am almost at the latest version (3.1.0)
My fault... I was using cached app at the simulation.
Plus I have forgotten in a rush about my framing logic... 
I was selecting top part from the scene.  In case if someone is interested....

 ```
.....
view.rx.layoutSubviews.bind { [weak self] (_) in
            guard let `self` = self else { return }
            
            self.animationViewLayer?.setNeedsLayout()
            self.adjustTransform()
        }.disposed(by: disposeBag)
        
        adjustTransform()
        
        animationView.play()
.....

var animationViewLayer: CALayer! {
        return animationView?.layer.sublayers?.first
    }

func adjustTransform() {
        guard let animationLayer = animationViewLayer else {
            assertFailure("Where is Main Animation Layer?")
            return
        }
        if animationLayer.needsLayout() {
            animationLayer.layoutIfNeeded()
        }
        guard animationView.contentMode == .scaleAspectFill else { return }
        
        var position = CGPoint.zero
        position.x = animationLayer.superlayer!.bounds.midX
        assert(animationView.contentMode == .scaleAspectFill)
        position.y = animationLayer.bounds.height * max(animationLayer.transform.m11, animationLayer.transform.m22) * 0.5
        animationLayer.position = position
    }
```
