### ISSUE TITLE
AnimationView should finish the loop of current animation before the new animation starts

### ISSUE THREAD

**Issue by Hoppsen** [airbnb/lottie-ios#969]
## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [X] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.0

## What Platform are you on? 
- [] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift
- [] Objective-C

## Expected Behavior 
I got an animationView with an animated circle in loopMode: .loop. When I now override the animation attribute of this animationView, the new animation (slightly different circle in another color) starts immediately. Is there a simple way to tell the animationView to finish the current loop iteration until it starts the new animation? Ideally with an bool attribute e.g. "animationView.shouldFinishAnimation" or something similar.

**Comment by Hoppsen** [comment]
Found a solution, will close this one.

For any one looking for the same thing:

    
    func startAnimation(name: String, loopMode: LottieLoopMode = .playOnce, completion: ((Bool) -> Void)? = nil) {
        if animationView.isAnimationPlaying {
            animationView.play(fromProgress: animationView.currentProgress, toProgress: 1, loopMode: .playOnce) { _ in
                self.triggerAnimation(name: name, loopMode: loopMode, completion: completion)
            }
        } else {
            triggerAnimation(name: name, loopMode: loopMode, completion: completion)
        }
    }

    fileprivate func triggerAnimation(name: String, loopMode: LottieLoopMode, completion: ((Bool) -> Void)?) {
        animationView.animation = Animation.named(name)
        animationView.loopMode = loopMode
        animationView.play { finished in
            completion?(finished)
        }
    }

**Comment by Oliver-Binns** [comment]
> Found a solution, will close this one.
> 
> For any one looking for the same thing:
> 
> ```
> func startAnimation(name: String, loopMode: LottieLoopMode = .playOnce, completion: ((Bool) -> Void)? = nil) {
>     if animationView.isAnimationPlaying {
>         animationView.play(fromProgress: animationView.currentProgress, toProgress: 1, loopMode: .playOnce) { _ in
>             self.triggerAnimation(name: name, loopMode: loopMode, completion: completion)
>         }
>     } else {
>         triggerAnimation(name: name, loopMode: loopMode, completion: completion)
>     }
> }
> 
> fileprivate func triggerAnimation(name: String, loopMode: LottieLoopMode, completion: ((Bool) -> Void)?) {
>     animationView.animation = Animation.named(name)
>     animationView.loopMode = loopMode
>     animationView.play { finished in
>         completion?(finished)
>     }
> }
> ```

Who found a solution? ;)
