### ISSUE TITLE
Outlined shapes via Illustrator losing colors, paths

### ISSUE THREAD

**Issue by svenultimate** [airbnb/lottie-ios#97]
All layers are outlined shapes, no effects being used - just position & rotation, with a couple layers parented to some null layers.

Looking like this in AE:
![you_did_it](https://cloud.githubusercontent.com/assets/25779943/22997654/86a5ddde-f390-11e6-9b53-ba92eb95f3b9.gif)

Coming out in iOS like this:
![animation](https://cloud.githubusercontent.com/assets/25779943/22997671/a0b129f4-f390-11e6-83af-ffaf6696910f.gif)

Any help out there?

**Comment by svenultimate** [comment]
Got the answer. It hates merged paths.

**Comment by buba447** [comment]
Yeah! Sorry about this! We are working on adding Merge Paths! Will mark this as a feature request and update when we add it.

**Comment by thomasmathew** [comment]
+1 for this enhancement—not having Merge Paths is creating a lot of additional overhead at my company currently.

**Comment by chrisfarrell** [comment]
+1

**Comment by BASEDGODBRIAN** [comment]
+1

**Comment by JoeSchofield** [comment]
+1

**Comment by svenultimate** [comment]
Hey guys, I made a screen recording (tutorial?) of the workaround I came up with. Hope it helps. Hella props to the guys who gave us Lottie and Bodymovin!

https://youtu.be/FE7n6cJKlto

**Comment by brianliebler** [comment]
Any updates on when the Merged Paths feature will be added?

**Comment by Alexi-Pourret** [comment]
Still waiting for some updates about the merge paths feature, anyone ?

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
