### ISSUE TITLE
shape layer group transform scaling broken by 3.0

### ISSUE THREAD

**Issue by mariuslibman** [airbnb/lottie-ios#972]
## This issue is a:
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1

## What Platform are you on? 

- [x] iOS

## Expected Behavior 
When animating a shape layer group's scale, both the stroke and fill would animate in accordance to the the scale animation.

## Actual Behavior
As far as I can tell, after updating to 3.0, the stroke(s) within the group are scaling down as expected, but the fill(s) are not - they maintain whatever scale they had at the beginning of the animation.

Worth noting - if I scrub the animation in LottieFiles, it animates correctly, but when playing back, it displays the behavior described above.

## Animation JSON

https://www.dropbox.com/s/hgwtbwa57718j7o/FII_close.json?dl=0

**Comment by mariuslibman** [comment]
Another note - the issue seems to be with moving the fill outside of a shape layer group. If it's moved into a group, the phantom fill does not appear.

**Comment by calda** [comment]
The linked animation appears to play correctly when I test it in Lottie 4.0
