### ISSUE TITLE
Edit text when animation is loaded

### ISSUE THREAD

**Issue by KamilGrotowski** [airbnb/lottie-ios#973]
## Which Version of Lottie are you using?

Lottie 3.1.0

## What Platform are you on? 
- iOS

## What Language are you in?
- Swift

## Questions:

1. Is it possible to edit text using Dynamic Animation Properties?  Or do I have to edit JSON configuration and load it again?
2. Do you have a plan to support _Expressions_ on iOS?

**Comment by buba447** [comment]
You can set a `AnimationTextProvider` on `AnimationView.textProvider`

**Comment by RolandasRazma** [comment]
is there way too reload it without reloading whole animation?

**Comment by shirley737** [comment]
Can you show an example of how to use dynamic texting by setting keypath and source text? Thank you so much!

**Comment by RolandasRazma** [comment]
```swift
class TextProvider: AnimationTextProvider {
    let keypathName: String
    let sourceText: String
    
    init(keypathName: String, sourceText: String) {
        self.keypathName = keypathName
        self.sourceText = sourceText
    }
    
    // MARK: - AnimationTextProvider
    
    func textFor(keypathName: String, sourceText: String) -> String {
        guard keypathName == self.keypathName else { return sourceText }
        
        return self.sourceText
    }
    
}

animationView.textProvider = TextProvider(keypathName: "main_text", sourceText: "your text")
```

Text is cached and will be requested only once. 
As far as I can say the only way to update it is to set animation again. (`animationView.animation ...`)

**Comment by shirley737** [comment]
Thank you for your example. Not sure if I understand it correctly, but you mean I can only edit the text layer once? if not, is there any way to edit two text layers of the Lottie Animation? 

Thanks again!

**Comment by RolandasRazma** [comment]
you can edit as many layers as you want. Everything is handled by `AnimationTextProvider` protocol

**Comment by shirley737** [comment]
Sorry for keep asking you... after setting the textProvider class, I add 4 lines to edit 4 different text layers: 

```
    animationView.textProvider = TextProvider(keypathName:name1 , sourceText: text1)
    animationView.textProvider = TextProvider(keypathName:name2, sourceText: text2)
    animationView.textProvider = TextProvider(keypathName:name3, sourceText: text3)
    animationView.textProvider = TextProvider(keypathName:name4, sourceText: text4)
```
But during runtime only the fourth text layer changed. I think it is because I update textProvider 4 times. Curious: did I miss any function in order to change all the text layers? 

Thank you so much again!

**Comment by RolandasRazma** [comment]
```swift
class TextProvider: AnimationTextProvider {
	
	...
	
    // MARK: - AnimationTextProvider
    
    func textFor(keypathName: String, sourceText: String) -> String {
       if name1 == keypathName {
              return text1
       }
       else if name2 == keypathName {
              return text2
       }
       else if name3 == keypathName {
              return text3
       }
       else if name4 == keypathName {
              return text4
       }
       
       return sourceTextelf.sourceText
    }
    
}
```

**Comment by shirley737** [comment]
Awesome it worked this time! Super appreciate your help!!

**Comment by adamdahan** [comment]
@buba447 I've been reading our comments to issues being posted by the public for the past 30 minutes. Your a real douche.

**Comment by georgbachmann** [comment]
Quick question. I'd like to dynamically replace text in a lottie file (to localize content). We generate our lottie file using after effects. Is that possible that way?

**Comment by georgbachmann** [comment]
and can this be done using after effects? (i am the app-developer, not the designer, so I don't know much about after effects)

**Comment by RolandasRazma** [comment]
export is just JSON file
