### ISSUE TITLE
Pod [!] Unable to find a specification for `lottie-ios`

### ISSUE THREAD

**Issue by alexviquez** [airbnb/lottie-ios#98]
Hi Bro!, i got this problem when i try to install lottie-ios i make Pod Install and this happend [!] Unable to find a specification for `lottie-ios` , then i tried to make a pod repo update but i cant solve this issue.
![captura de pantalla 2017-02-15 a la s 15 03 24](https://cloud.githubusercontent.com/assets/13012209/22999422/199673a2-f390-11e6-9780-7a180ede3c70.png)

**Comment by xinsight** [comment]
This is a cocoapods/git issue. Just remove the index.lock file

**Comment by dungeonsnd** [comment]
Where is the index.lock file?

**Comment by alexviquez** [comment]
It works Sir @xinsight , Thank you so much!, and the index.lock in my case is in "/Users/alex/.cocoapods/repos/master" just open in terminal and put this command rm -f index.lock, and then use pod repo update, and then pod install !

**Comment by iegik** [comment]
Podfile.lock

**Comment by mdtipusultan** [comment]
just delete the podfile.lock is working for me. Thank you guys.
