### ISSUE TITLE
AnimationView setSceneModel blocks main thread for a noticeable amount of time

### ISSUE THREAD

**Issue by GPF253904828** [airbnb/lottie-ios#984]
I used Cache, but it doesn't work.
![cache](https://user-images.githubusercontent.com/8220675/61119838-3fac8580-a4ce-11e9-8545-f1f077f4123e.png)
![cache1](https://user-images.githubusercontent.com/8220675/61119839-3fac8580-a4ce-11e9-8e98-cdee189bc778.png)
![lot cache](https://user-images.githubusercontent.com/8220675/61119840-40451c00-a4ce-11e9-8efb-05688e5d1515.png)

**Comment by GPF253904828** [comment]
I want to use OC

**Comment by cddjr** [comment]
OC就老老实实继续用2.x版本

**Comment by GPF253904828** [comment]
我写了一套缓存策略， 哈哈哈，现在看着还可以

**Comment by cddjr** [comment]
你还自己写呀？  我们用lottie自带的cache没发现有什么毛病，可能是因为用的最新的3.x版本

**Comment by calda** [comment]
Closing since this API no longer exists in Lottie 3
