### ISSUE TITLE
Set Colour for Array of Keypath string doesn't work

### ISSUE THREAD

**Issue by animios** [airbnb/lottie-ios#988]
# This issue is a:
- [yes] Non-Crashing Bug (Visual or otherwise)

## Which Version of Lottie are you using?
Lottie 3.1.1

## What Platform are you on? 
-  iOS

## What Language are you in?
-   Swift

## Expected Behavior 
Colour should change only for the give Keypaths

## Actual Behavior
No action is performing if we give as an array of string in AnimakerKeypath to setValueProvider. But If I set every keypath color individually it work and the colour changed

## Code Example

import UIKit
import Lottie

class ViewController: UIViewController {

    @IBOutlet weak var lottieView: AnimationView! {
        didSet {
            lottieView.loopMode = .loop
            lottieView.play()
        }
    }

    @IBAction func changeImages(_ sender: UIButton) {
        print(lottieView.imageProvider)
        lottieView.imageProvider = BundleImageProvider(bundle: Bundle.main, searchPath: "ssd")
        print(lottieView.imageProvider)
    }

    @IBAction func setBlue(_ sender: Any) {
        let colorProvider = ColorValueProvider(Color(r: 0, g: 0, b: 1, a: 1))

        let colorSet = [ "#Layer1.Fill 1.Color","Layer2.Fill 1.Color","Layer3.Fill 1.Color","Layer6.Fill 1.Color","Layer10.Fill 1.Color"]

        lottieView.setValueProvider(colorProvider, keypath: AnimationKeypath(keys: colorSet))
    }

    
}

**Comment by buba447** [comment]
You need to create an `AnimationKeypath` for each keypath you want to set.
Every `AnimationKeypath` keypath object represents only one keypath to set.
The `AnimationKeypath(keys:)` constructor is used to create a single keypath from a list of keys.
EG: 
```
// "Layer3.Fill 1.Color"
let keypath = AnimationKeypath(keys: ["Layer 3", "Fill 1", " Color"])
```

You can also create the same keypath using dot syntax:
```
// "Layer3.Fill 1.Color"
let keypath = AnimationKeypath(keypath:"Layer3.Fill 1.Color")
```

Now I see in your case you are trying to set three different keypaths to the same color. You can either create three different keypath objects and call `lottieView.setValueProvider` three times, or you can use wildcards to save some code.
Wildcards are simple regex like syntax used to search for keypaths. For your use you could use the following keypath to set all instances of "Fill 1.Color":

 ```
// "#Layer1.Fill 1.Color","Layer2.Fill 1.Color","Layer3.Fill 1.Color","Layer6.Fill 1.Color","Layer10.Fill 1.Color"

let keypath = AnimationKeypath(keypath:"*.Fill 1.Color")
// OR
let keypath = AnimationKeypath(keys: ["*", "Fill 1", " Color"])
```
I hope this helps!

**Comment by alexanderkhitev** [comment]
Hey @buba447 ! can we get all key paths from `AnimationView`?

**Comment by buba447** [comment]
@alexanderkhitev yup just use `animationview.logHierarchyKeypaths()`

**Comment by alexanderkhitev** [comment]
@buba447 thank you!

**Comment by Wistrand1965** [comment]
I whant to unscribe at once.
