### ISSUE TITLE
[Feature Request/Discussion] Updating interpolating colors

### ISSUE THREAD

**Issue by Ben-Henshall** [airbnb/lottie-ios#990]
## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features) - sort of? 🤷‍♂ 
- [X] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [x] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?
Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [X] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 
Ideally, Lottie should be able to handle dynamically providing colors for animations that use linear interpolation to transition between colors. Currently, there are two methods of supplying colors using ColorValueProvider for animations that are built this way:
* ColorValueProvider(color:) which applies a single color to the key path, regardless of the active frame - this doesn't really work with animations that include interpolating colors, as it's a single color change across the whole group for the full period of the animation.
* ColorValueProvider(block:) which allows the consumer to change the color based on the current frame. It is, in theory, possible to add interpolating colors based on this, but it requires the consumer to know various keyframes and manually interpolate colors themselves to successfully replace any interpolating colors.

Instead, I believe it would be better to have some ValueProvider that has context on the existing keyframes for the colors and replace the values, while maintaining the keyframes that they change during.
For example, an early idea I had was that a consumer could set a new value provider that takes an array of `Color` and iterates through the existing keyframes (if available) of the keyframe and sets the colors accordingly (keyFrames[0].value = newValues[0], keyFrames[1].value = newValues[1] etc)

An issue with this, though, is that once the original `KeyFrameInterpolator` reference for a property has been changed, then there is no detail of the keyframes for that value, so the new value provider would not be able to have more a single value provided over the whole animation.
For example, when I set a new ColorValueProvider for a stroke node, then the original `KeyFrameInterpolator` value provider is lost, meaning we no longer have any idea which keyframes the color changes in.

I'm interested in looking into this further, but wanted to stop and ask for opinions on how to approach this, in case some thought has already gone into it.

## Animation JSON
Here's an example of an animation with interpolating colours: https://pastebin.com/abD7Lifc

**Comment by creister** [comment]
Also wondering about this and the equivalent for points as well. 

Lottie 2.5 had the `ValueDelegate` api, for example `ColorValueDelegate`:
```
- (CGColorRef)colorForFrame:(CGFloat)currentFrame
              startKeyframe:(CGFloat)startKeyframe
                endKeyframe:(CGFloat)endKeyframe
       interpolatedProgress:(CGFloat)interpolatedProgress
                 startColor:(CGColorRef)startColor
                   endColor:(CGColorRef)endColor
               currentColor:(CGColorRef)interpolatedColor;
```
But the replacement, `ValueProvider`, only provides `currentFrame`.

**Comment by buba447** [comment]
Done!

**Comment by michaelfransen** [comment]
@buba447 How is this done?

**Comment by Cookizza** [comment]
Sorry to revive this, but I'm struggling to implement animation of colors in the colorFilters prop using reanimated.

I know all my code is fine, as it works on any other element - but not lottie colorFilters prop :(

     const animatedStyle = useAnimatedProps(() => {
    return {
      progress: Math.min(1, animatedProgress.value),
      colorFilters: [
        {
          keypath: "Ring",
          color: interpolateColor(animatedProgress.value, [0, 1], ['#ff0000', '#4b57f4'])
        }
      ]
    }
  });
...
    <AnimatedLottie
        style={style.ring}
        source={types[type].animation}
        loop={false}
        animatedProps={animatedStyle}
      />

This just results in Lottie defaulting to the lime green it does when invalid colorFilters are passed.

Any advice on how to handle this for lottie would be appreciated!
