### ISSUE TITLE
Make AnimationContainer public

### ISSUE THREAD

**Issue by gmore** [airbnb/lottie-ios#993]
In order to render a Lottie animation to OpenGl (without a UIView), 
I added the public modifier to AnimationContainer.

Please make AnimationContainer public
Also an initializer with blank imageProvider and textProvider is useful.

**Comment by calda** [comment]
Thanks for the suggestion -- we don't plan on making this public since it's an implementation detail and currently requires tight integration with the `LottieAnimationView` class
