### ISSUE TITLE
guard self.window != nil prevents layer animation from playing

### ISSUE THREAD

**Issue by jeffepic** [airbnb/lottie-ios#999]
## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)

## Which Version of Lottie are you using?

Lottie 3.1.2

## What Platform are you on? 
- iOS

## What Language are you in?
- Swift

## Code Example
Adding an AnimationView's layer to another CALayer, the animation will never play because of this line in AnimationView.swift:
``` guard self.window != nil else { waitingToPlayAimation = true; return }```

If I comment that out, it works as expected. The reason is that I am not adding the AnimationView to the view hierarchy, and therefore its window is nil. Layer does not have a window property.

works:
```view.addSubview(lottieView)```

does not work:
```customLayer.addSublayer(lottieView.layer)```

I think I understand the purpose of that line, you don't want it playing if it isn't on the screen, but maybe an option could be added for layer animations to bypass that?

**Comment by damikdk** [comment]
I spent days trying to export CALayer without real UIView rendered on the screen (through AVMutableVideoComposition and AVAssetExportSession) and I got the same results. This line really ruin the coolest way to export animations.

**Comment by croossin** [comment]
I am also seeing this issue... even when adding an `AnimationView` directly to the .xib...

**Comment by ole-kr-stumpf** [comment]
I had this issue, and I resolved it by moving the initialisation of `AnimationView`, i.e. `let animationView = AnimationView()` to inside of `makeUIView`.
Also, this was an issue only on iOS v. 14.1, but not on 14.2

**Comment by devmea** [comment]
Using version 3.1.5 and came across this issue.
I have a collectionView with several AnimationViews, and it works the first time I scroll down. When I scroll back up, and I instantiate a new AnimationView, its window is returning nil.

**Comment by calda** [comment]
> Adding an `AnimationView`'s layer to another `CALayer`

Closing since I don't think this is a supported way to use a `UIView` subclass
